
  CREATE TABLE "SBMO"."MEDICAL_SUPPLIES_28MAY26" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TENANT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RX_CORE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(60) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 