
  CREATE TABLE "SBMO"."MEDICAL_SUPPLIES" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TENANT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RX_CORE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(60) NOT NULL ENABLE, 
	 CONSTRAINT "MEDICAL_SUPPLIES_PK" PRIMARY KEY ("TENANT_ID", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_X"  ENABLE, 
	 CONSTRAINT "MEDICAL_SUPPLIES_UK1" UNIQUE ("RX_CORE_ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_X"  ENABLE, 
	 CONSTRAINT "MEDICAL_SUPPLIES_FK1" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "SBMO"."TENANTS" ("ID") ENABLE, 
	 CONSTRAINT "MEDICAL_SUPPLIES_FK2" FOREIGN KEY ("TENANT_ID", "RX_CORE_ID")
	  REFERENCES "SBMO"."RX_CORES" ("TENANT_ID", "ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 