
  CREATE TABLE "SBMO"."PDX_SCHEMA_UPD_HELPER_DEBUG_D" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PDX_SCHEMA_UPD_HLPR_DBG_H_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"START_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	"END_TIMESTAMP" TIMESTAMP (6), 
	"MESSAGE" VARCHAR2(1000), 
	"SQL_ERROR" CLOB, 
	"SQL" CLOB, 
	 CONSTRAINT "PDX_SCHEMA_UPD_HLPR_DBG_D_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PDX_SCHEMA_UPD_HLPR_DBG_D_FK1" FOREIGN KEY ("PDX_SCHEMA_UPD_HLPR_DBG_H_ID")
	  REFERENCES "SBMO"."PDX_SCHEMA_UPD_HELPER_DEBUG_H" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SBMO_MULTITENANT_D" 
 LOB ("SQL_ERROR") STORE AS SECUREFILE (
  TABLESPACE "SBMO_MULTITENANT_D" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("SQL") STORE AS SECUREFILE (
  TABLESPACE "SBMO_MULTITENANT_D" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 