
  CREATE TABLE "SBMO"."ADJUSTMENT_CODES" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CODE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"LAST_UPDATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DEACTIVATED_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CHANGE_ON_HAND" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "ADJUSTMENT_CODES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 