
  CREATE TABLE "SBMO"."AUDIT_DBU_LOG" 
   (	"ID" NUMBER, 
	"EXEC_TIME_STAMP" TIMESTAMP (6), 
	"USER_ID" VARCHAR2(30), 
	"DBU_TABLE" VARCHAR2(30), 
	"DBU_PARMS" VARCHAR2(2000), 
	"DBU_ROWS" NUMBER, 
	"SQL_TEXT" VARCHAR2(2000), 
	"ERROR_TEXT" VARCHAR2(2000), 
	 CONSTRAINT "AUDIT_DBU_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_X"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 