
  CREATE TABLE "SBMO"."EXT_DRUG_LOAD" 
   (	"NAME" VARCHAR2(255), 
	"DRUG_FULL_NAME" VARCHAR2(255), 
	"NDC" VARCHAR2(255), 
	"GENERIC_NAME" VARCHAR2(255), 
	"GENERIC_FULL_NAME" VARCHAR2(255), 
	"MFG" VARCHAR2(255), 
	"UNIT" VARCHAR2(255), 
	"STRENGTH" VARCHAR2(255), 
	"SCHEDULE" VARCHAR2(255), 
	"PACK" VARCHAR2(255), 
	"DECIMAL_PACK" VARCHAR2(255), 
	"PACKAGE_QTY" VARCHAR2(255), 
	"IND_PACK" VARCHAR2(255), 
	"AWP" VARCHAR2(255), 
	"AWP_LAST_UPDATED" VARCHAR2(255), 
	"MULTI_SOURCE" VARCHAR2(255), 
	"TRIPLIC" VARCHAR2(255), 
	"INJECT" VARCHAR2(255), 
	"REFRIGERATED" VARCHAR2(255), 
	"SIGNATURE_REQUIRED" VARCHAR2(255), 
	"HAZMAT" VARCHAR2(255), 
	"LAST_UPDATED_DATE" VARCHAR2(255), 
	"BARCODE" VARCHAR2(255), 
	"DRUG_NOTE" VARCHAR2(255), 
	"GPI" VARCHAR2(255), 
	"ID" VARCHAR2(255), 
	"MFG_DISCONTINUE_DATE" VARCHAR2(255), 
	"NDCFMT" VARCHAR2(255), 
	"PREVIOUS_NDC" VARCHAR2(255), 
	"REPLACEMENT_NDC" VARCHAR2(255)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "EXT_TABLES"
      ACCESS PARAMETERS
      ( records delimited by newline
           fields terminated by '	'
                 )
      LOCATION
       ( 'sbmo_meijer_veterinary_drug_file.txt'
       )
    )
   REJECT LIMIT 0 