
  CREATE TABLE "SBMO"."PURGE_HISTORY_CHUNKS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_PURGE_HISTORY_PARTITIONS" NUMBER NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PART_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"TASK_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"START_TIME" DATE NOT NULL ENABLE, 
	"END_TIME" DATE NOT NULL ENABLE, 
	"ROW_COUNT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PURGE_HISTORY_CHUNKS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PURGE_HISTORY_CHUNKS_FK1" FOREIGN KEY ("ID_PURGE_HISTORY_PARTITIONS")
	  REFERENCES "SBMO"."PURGE_HISTORY_PARTITIONS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 