
  CREATE TABLE "SBMO"."QRTZ_CALENDARS" 
   (	"CALENDAR_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"CALENDAR" BLOB NOT NULL ENABLE, 
	"SCHED_NAME" VARCHAR2(120) DEFAULT 'TestScheduler' NOT NULL ENABLE, 
	 CONSTRAINT "QRTZ_CALENDARS_PK" PRIMARY KEY ("SCHED_NAME", "CALENDAR_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SBMO_MULTITENANT_D" 
 LOB ("CALENDAR") STORE AS SECUREFILE (
  TABLESPACE "SBMO_MULTITENANT_D" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 