
  CREATE TABLE "SBMO"."PDX_SCHEMA_PRIV_EXCEPTION" 
   (	"OBJECT_TYPE" VARCHAR2(19) NOT NULL ENABLE, 
	"OBJECT_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PRIVILEGE" VARCHAR2(40) NOT NULL ENABLE, 
	"GRANTEE" VARCHAR2(30) NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(1), 
	 CONSTRAINT "PDX_SCHEMA_PRIV_EXCEPTION_PK" PRIMARY KEY ("GRANTEE", "OBJECT_TYPE", "OBJECT_NAME", "PRIVILEGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 