
  CREATE TABLE "SBMO"."QRTZ_FIRED_TRIGGERS" 
   (	"ENTRY_ID" VARCHAR2(95) NOT NULL ENABLE, 
	"TRIGGER_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"TRIGGER_GROUP" VARCHAR2(200) NOT NULL ENABLE, 
	"INSTANCE_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"FIRED_TIME" NUMBER(13,0) NOT NULL ENABLE, 
	"STATE" VARCHAR2(16) NOT NULL ENABLE, 
	"JOB_NAME" VARCHAR2(200), 
	"JOB_GROUP" VARCHAR2(200), 
	"REQUESTS_RECOVERY" VARCHAR2(1), 
	"PRIORITY" NUMBER(13,0), 
	"IS_NONCONCURRENT" VARCHAR2(11), 
	"IS_UPDATE_DATA" VARCHAR2(11), 
	"SCHED_NAME" VARCHAR2(120) DEFAULT 'TestScheduler' NOT NULL ENABLE, 
	"SCHED_TIME" NUMBER(13,0), 
	 CONSTRAINT "QRTZ_FIRED_TRIGGERS_PK" PRIMARY KEY ("SCHED_NAME", "ENTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 