
  CREATE TABLE "SBMO"."PDX_SCHEMA_UPD_HELPER_DEBUG_H" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROC" VARCHAR2(30) NOT NULL ENABLE, 
	"PARMS" VARCHAR2(4000), 
	"DEBUG_TIMESTAMP" TIMESTAMP (6), 
	"SQL_ERROR" CLOB, 
	 CONSTRAINT "PDX_SCHEMA_UPD_HLPR_DBG_H_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SBMO_MULTITENANT_D" 
 LOB ("SQL_ERROR") STORE AS SECUREFILE (
  TABLESPACE "SBMO_MULTITENANT_D" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 