
  CREATE TABLE "SBMO"."PURGE_ERROR_LOG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ERROR_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"CODE_BLOCK" VARCHAR2(30) NOT NULL ENABLE, 
	"SQL_CODE" NUMBER, 
	"SQL_ERRM" VARCHAR2(250), 
	"EXCEPTION_MESSAGE" VARCHAR2(4000) NOT NULL ENABLE, 
	"PARAMETER_VALUES" VARCHAR2(4000), 
	 CONSTRAINT "PURGE_ERROR_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 