
  CREATE TABLE "SBMO"."QRTZ_TRIGGERS" 
   (	"TRIGGER_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"TRIGGER_GROUP" VARCHAR2(200) NOT NULL ENABLE, 
	"JOB_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"JOB_GROUP" VARCHAR2(200) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(250), 
	"NEXT_FIRE_TIME" NUMBER(13,0), 
	"PREV_FIRE_TIME" NUMBER(13,0), 
	"TRIGGER_STATE" VARCHAR2(16) NOT NULL ENABLE, 
	"TRIGGER_TYPE" VARCHAR2(8) NOT NULL ENABLE, 
	"START_TIME" NUMBER(13,0) NOT NULL ENABLE, 
	"END_TIME" NUMBER(13,0), 
	"CALENDAR_NAME" VARCHAR2(200), 
	"MISFIRE_INSTR" NUMBER(2,0), 
	"PRIORITY" NUMBER(13,0), 
	"JOB_DATA" BLOB, 
	"SCHED_NAME" VARCHAR2(120) DEFAULT 'TestScheduler' NOT NULL ENABLE, 
	 CONSTRAINT "QRTZ_TRIGGERS_PK" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "QRTZ_TRIGGERS_FK1" FOREIGN KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP")
	  REFERENCES "SBMO"."QRTZ_JOB_DETAILS" ("SCHED_NAME", "JOB_NAME", "JOB_GROUP") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 
 LOB ("JOB_DATA") STORE AS SECUREFILE (
  TABLESPACE "SBMO_MULTITENANT_D" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 