
  CREATE TABLE "SBMO"."TENANTS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(15) NOT NULL ENABLE, 
	"ADDRESS_LINE_1" VARCHAR2(30) NOT NULL ENABLE, 
	"ADDRESS_LINE_2" VARCHAR2(30), 
	"CITY" VARCHAR2(35) NOT NULL ENABLE, 
	"STATE" VARCHAR2(2) NOT NULL ENABLE, 
	"ZIP" VARCHAR2(15) NOT NULL ENABLE, 
	"COUNTY" VARCHAR2(15) NOT NULL ENABLE, 
	"NHINID" NUMBER(19,0) NOT NULL ENABLE, 
	"TIME_ZONE" VARCHAR2(50) NOT NULL ENABLE, 
	"LOCAL_PHONE_NUMBER" VARCHAR2(10) NOT NULL ENABLE, 
	"TOLL_FREE_PHONE_NUMBER" VARCHAR2(10) NOT NULL ENABLE, 
	"ALTERNATE_PHONE_NUMBER" VARCHAR2(10), 
	"ACTIVE_DIRECTORY_GROUP" VARCHAR2(255) NOT NULL ENABLE, 
	"IS_RXCOM" VARCHAR2(5) NOT NULL ENABLE, 
	"NHIN_NAME_ABBREVIATION" VARCHAR2(3), 
	 CONSTRAINT "TENANTS_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 CONSTRAINT "TENANTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 