
  CREATE TABLE "SBMO"."RX_DIGITAL_DOCUMENTS" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TENANT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RX_CORES_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"QR_CODE_IMAGE" BLOB, 
	"QR_CODE_LINK" VARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "RX_DIGITAL_DOCUMENTS_PK" PRIMARY KEY ("TENANT_ID", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_X"  ENABLE, 
	 CONSTRAINT "PRX_DIGITAL_DOCUMENTS_CK1" CHECK (QR_CODE_IMAGE is not null or QR_CODE_LINK is not null) ENABLE, 
	 CONSTRAINT "RX_DIGITAL_DOCUMENTS_FK1" FOREIGN KEY ("TENANT_ID", "RX_CORES_ID")
	  REFERENCES "SBMO"."RX_CORES" ("TENANT_ID", "ID") ENABLE, 
	 CONSTRAINT "RX_DIGITAL_DOCUMENTS_FK2" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "SBMO"."TENANTS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 
 LOB ("QR_CODE_IMAGE") STORE AS SECUREFILE (
  TABLESPACE "SBMO_MULTITENANT_D" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 