
  CREATE TABLE "SBMO"."RX_HOURS_OF_ADMIN_DOSES" 
   (	"ID" NUMBER(38,0), 
	"TENANT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RX_HOURS_OF_ADMINISTRATION_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"DATE_OF_DOSE" TIMESTAMP (6), 
	"TIME_OF_DOSE" VARCHAR2(28) NOT NULL ENABLE, 
	"QUANTITY" NUMBER(13,0) NOT NULL ENABLE, 
	 CONSTRAINT "RX_HOURS_OF_ADMIN_DOSES_PK" PRIMARY KEY ("TENANT_ID", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_X"  ENABLE, 
	 CONSTRAINT "RX_HOURS_OF_ADMIN_DOSES_UK1" UNIQUE ("RX_HOURS_OF_ADMINISTRATION_ID", "TENANT_ID", "DATE_OF_DOSE", "TIME_OF_DOSE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_X"  ENABLE, 
	 CONSTRAINT "RX_HOURS_OF_ADMIN_DOSES_FK1" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "SBMO"."TENANTS" ("ID") ENABLE, 
	 CONSTRAINT "RX_HOURS_OF_ADMIN_DOSES_FK2" FOREIGN KEY ("TENANT_ID", "RX_HOURS_OF_ADMINISTRATION_ID")
	  REFERENCES "SBMO"."RX_HOURS_OF_ADMINISTRATION" ("TENANT_ID", "ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 