-- BATCH 1 TABLES
-- ------------------------------------------------------------------

CREATE TABLE [SBMO].[BIN_UPC_LINK] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [BIN_BARCODE] VARCHAR(MAX) NULL,
    [DRUG_UPC] VARCHAR(MAX) NULL,
    [DEVICE_NUMBER] VARCHAR(MAX) NULL,
    [DRUG_NAME] VARCHAR(MAX) NULL,
    [NDC] VARCHAR(MAX) NULL,
    [NDC_FMT] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[CARRIER] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [NAME] VARCHAR(MAX) NULL,
    [SHIP_IDENT] VARCHAR(MAX) NULL,
    [SHIP_PRIORITY] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[ENCRYPTION_KEYS] (
    [ID] DECIMAL(38,0) NULL,
    [TENANT_ID] DECIMAL(38,0) NULL,
    [VALUE] VARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [DEACTIVATED_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[FACILITIES] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [SHORT_NAME] VARCHAR(MAX) NULL,
    [NAME] VARCHAR(MAX) NULL,
    [ADDRESS_LINE_1] VARCHAR(MAX) NULL,
    [ADDRESS_LINE_2] VARCHAR(MAX) NULL,
    [CITY] VARCHAR(MAX) NULL,
    [STATE] VARCHAR(MAX) NULL,
    [ZIP] VARCHAR(MAX) NULL,
    [COUNTY] VARCHAR(MAX) NULL,
    [DEA_NUMBER] VARCHAR(MAX) NULL,
    [FEDERAL_TAX_IDENTIFIER] DECIMAL(38,0) NULL,
    [NCPDP_NUMBER] VARCHAR(MAX) NULL,
    [NHINID] DECIMAL(38,0) NULL,
    [DEA_EXPIRATION_DATE] DATETIME2 NULL,
    [TIME_ZONE] VARCHAR(MAX) NULL,
    [LOCAL_PHONE_NUMBER] VARCHAR(MAX) NULL,
    [TOLL_FREE_PHONE_NUMBER] VARCHAR(MAX) NULL,
    [ALTERNATE_PHONE_NUMBER] VARCHAR(MAX) NULL,
    [EXPORT_ORDER_DISPENSER_MODULE] VARCHAR(MAX) NULL,
    [DISPENSER_COMM_ENABLED] VARCHAR(MAX) NULL,
    [CHECK_INV_FOR_HOME_DELIVERY] VARCHAR(MAX) NULL,
    [DRUG_LOT_NOT_REQUIRED] VARCHAR(MAX) NULL,
    [ORDER_PULL_DELAY] DECIMAL(38,0) NULL,
    [ENABLE_ITEM_LOCATIONS] VARCHAR(MAX) NULL,
    [RED_HOURS] DECIMAL(38,0) NULL,
    [YELLOW_HOURS] DECIMAL(38,0) NULL,
    [ACTIVE_DIRECTORY_GROUP] VARCHAR(MAX) NULL,
    [PAUSE_ORDER_PROCESSING_DATE] DATETIME2 NULL,
    [DOC_ERROR_RESET_DATE] DATETIME2 NULL,
    [DOC_CON_ERROR_RESET_DATE] DATETIME2 NULL,
    [DISPLAY_TX_COST_ERROR] VARCHAR(MAX) NULL,
    [LANDING_PAGE] DECIMAL(38,0) NULL,
    [STATUS_ALERT_THRESHOLD] DECIMAL(38,0) NULL,
    [PROMISED_DATE_ALERT_THRESHOLD] DECIMAL(38,0) NULL,
    [ORDER_PULL_JOB_FREQUENCY] DECIMAL(38,0) NULL,
    [CHECK_INV_FOR_SPECIALTY] DECIMAL(38,0) NULL,
    [TRANSITION_POLLTIME] DECIMAL(38,0) NULL,
    [TRANSITION_ALERT_THRESHOLD] DECIMAL(38,0) NULL,
    [TRANSITION_AUTO_TASK_DISABLED] VARCHAR(MAX) NULL,
    [TRANSITION_ALERT_EMAIL] VARCHAR(MAX) NULL,
    [PROMISE_DATE_ENABLED] VARCHAR(MAX) NULL,
    [PROMISE_DATE_SUN] DECIMAL(38,0) NULL,
    [PROMISE_DATE_MON] DECIMAL(38,0) NULL,
    [PROMISE_DATE_TUE] DECIMAL(38,0) NULL,
    [PROMISE_DATE_WED] DECIMAL(38,0) NULL,
    [PROMISE_DATE_THU] DECIMAL(38,0) NULL,
    [PROMISE_DATE_FRI] DECIMAL(38,0) NULL,
    [PROMISE_DATE_SAT] DECIMAL(38,0) NULL,
    [AUTO_CANCEL_TO_STORE] VARCHAR(MAX) NULL,
    [QUEUE_MAX_DAYS_BACK] DECIMAL(38,0) NULL,
    [CHECK_INV_FOR_STORE_DELIVERY] DECIMAL(38,0) NULL,
    [MAINTAIN_INVENTORY_QUANTITIES] VARCHAR(MAX) NULL,
    [PO_EMAIL] VARCHAR(MAX) NULL,
    [ORDER_PULL_THREAD_CNT] DECIMAL(38,0) NULL,
    [ORDER_PULL_MAX_CNT] DECIMAL(38,0) NULL,
    [ENABLE_HOLD_SPECIALTY_ORDERS] VARCHAR(MAX) NULL,
    [LAST_UPDATED_DATE] DATETIME2 NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(MAX) NULL,
    [ENABLE_ORDER_CANCEL_REASON] VARCHAR(MAX) NULL,
    [DASHBOARD_JOB_ENABLED] VARCHAR(MAX) NULL,
    [STATUS_UPDATE_MAX_DAYS_BACK] DECIMAL(38,0) NULL,
    [IGNORE_PROM_DATE_HOME_DELIVERY] VARCHAR(MAX) NULL,
    [IGNORE_PROM_DATE_SPECIALTY] VARCHAR(MAX) NULL,
    [CHECK_INV_FOR_UNIT_DOSE] DECIMAL(38,0) NULL,
    [START_OF_DAY_TIME] DATETIME2 NULL,
    [ADHERIS_DOCUMENT_SIZE] VARCHAR(MAX) NULL,
    [ALLOW_SINGLE_RX_CANCELLATION] VARCHAR(MAX) NULL,
    [SEND_ALT_NHIN_DRUG_NAME] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[FORMULARY_REORDER] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [ORDER_POINT] FLOAT NULL,
    [ORDER_QTY] FLOAT NULL,
    [MINIMUM_QTY] FLOAT NULL,
    [LAST_ORDER_DATE] DATETIME2 NULL,
    [HOLD_UNTIL_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[INVENTORY_DATE] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [INVENTORY_LAST_UPDATED_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[LABEL_IMAGES] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [IMAGE_DATA] VARBINARY(MAX) NULL,
    [IMAGE_FORMAT] VARCHAR(MAX) NULL,
    [IMAGE_NAME] VARCHAR(MAX) NULL,
    [IMAGE_SOURCE] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[LOCATION] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [LOCATION_TYPE] DECIMAL(38,0) NULL,
    [PARENT_ID] DECIMAL(38,0) NULL,
    [USE_TYPE] DECIMAL(38,0) NULL,
    [DESCRIPTOR] VARCHAR(MAX) NULL,
    [LOCATION_STATUS] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_D] (
    [ID] DECIMAL(38,0) NULL,
    [PDX_SCHEMA_UPD_HLPR_DBG_H_ID] DECIMAL(38,0) NULL,
    [START_TIMESTAMP] DATETIME2 NULL,
    [END_TIMESTAMP] DATETIME2 NULL,
    [MESSAGE] VARCHAR(MAX) NULL,
    [SQL_ERROR] VARCHAR(MAX) NULL,
    [SQL] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_UPD_PKGCALL_ERR_LOG] (
    [ID] DECIMAL(38,0) NULL,
    [ERROR_MESSAGE] VARCHAR(MAX) NULL,
    [SQL_ERROR_CODE] VARCHAR(MAX) NULL,
    [SQL_ERROR_MESSAGE] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_VERSION_HISTORY] (
    [ID] DECIMAL(38,0) NULL,
    [PDX_SCHEMA_UPD_PKGCALL_HIST_ID] DECIMAL(38,0) NULL,
    [CURRENT_VERSION] VARCHAR(MAX) NULL,
    [TARGET_VERSION] VARCHAR(MAX) NULL,
    [STATUS_CODE] VARCHAR(MAX) NULL,
    [START_DATE] DATETIME2 NULL,
    [END_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[PHONE_ADDRESS_OWNERS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[PURGE_HISTORY] (
    [ID] DECIMAL(38,0) NULL,
    [TABLE_NAME] VARCHAR(MAX) NULL,
    [START_DATE] DATETIME2 NULL,
    [PURGE_DATE] DATETIME2 NULL,
    [END_DATE] DATETIME2 NULL,
    [TOT_ELAPSED_SECS] DECIMAL(38,0) NULL,
    [TOT_INDEX_SECS] DECIMAL(38,0) NULL,
    [TOT_NBR_CHUNKS] DECIMAL(38,0) NULL,
    [NBR_ROWS_PURGED] DECIMAL(38,0) NULL,
    [NBR_ROWS_DELETED_FK] DECIMAL(38,0) NULL,
    [TOT_ELAPSED_FK_SECS] DECIMAL(38,0) NULL,
    [NBR_SUBPARTS_DROPPED] DECIMAL(38,0) NULL,
    [TOT_ELAPSED_DROP_SECS] DECIMAL(38,0) NULL,
    [STATUS] VARCHAR(MAX) NULL,
    [INDEX_SQL] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[QRTZ_TRIGGERS] (
    [TRIGGER_NAME] VARCHAR(MAX) NULL,
    [TRIGGER_GROUP] VARCHAR(MAX) NULL,
    [JOB_NAME] VARCHAR(MAX) NULL,
    [JOB_GROUP] VARCHAR(MAX) NULL,
    [DESCRIPTION] VARCHAR(MAX) NULL,
    [NEXT_FIRE_TIME] DECIMAL(38,0) NULL,
    [PREV_FIRE_TIME] DECIMAL(38,0) NULL,
    [TRIGGER_STATE] VARCHAR(MAX) NULL,
    [TRIGGER_TYPE] VARCHAR(MAX) NULL,
    [START_TIME] DECIMAL(38,0) NULL,
    [END_TIME] DECIMAL(38,0) NULL,
    [CALENDAR_NAME] VARCHAR(MAX) NULL,
    [MISFIRE_INSTR] DECIMAL(38,0) NULL,
    [PRIORITY] DECIMAL(38,0) NULL,
    [JOB_DATA] VARBINARY(MAX) NULL,
    [SCHED_NAME] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[REGION] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [NAME] VARCHAR(MAX) NULL,
    [SUN_START_TIME] DATETIME2 NULL,
    [SUN_STOP_TIME] DATETIME2 NULL,
    [MON_START_TIME] DATETIME2 NULL,
    [MON_STOP_TIME] DATETIME2 NULL,
    [TUE_START_TIME] DATETIME2 NULL,
    [TUE_STOP_TIME] DATETIME2 NULL,
    [WED_START_TIME] DATETIME2 NULL,
    [WED_STOP_TIME] DATETIME2 NULL,
    [THU_START_TIME] DATETIME2 NULL,
    [THU_STOP_TIME] DATETIME2 NULL,
    [FRI_START_TIME] DATETIME2 NULL,
    [FRI_STOP_TIME] DATETIME2 NULL,
    [SAT_START_TIME] DATETIME2 NULL,
    [SAT_STOP_TIME] DATETIME2 NULL
);

CREATE TABLE [SBMO].[RX_PATSTORES] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PARTITION_STAMP] DATETIME2 NULL,
    [FIRST_NAME] VARCHAR(MAX) NULL,
    [LAST_NAME] VARCHAR(MAX) NULL,
    [MIDDLE_NAME] VARCHAR(MAX) NULL,
    [PATIENT_ID] VARCHAR(MAX) NULL,
    [STORE_RPH_INITS] VARCHAR(MAX) NULL,
    [STORE_RPH_NAME] VARCHAR(MAX) NULL,
    [STORE_USER_INITS] VARCHAR(MAX) NULL,
    [STORE_USER_ID] VARCHAR(MAX) NULL,
    [STORE_TECH_INITS] VARCHAR(MAX) NULL,
    [STORE_RPH_LICENSE_NUM] VARCHAR(MAX) NULL,
    [ADDRESS] VARCHAR(MAX) NULL,
    [ADDRESS2] VARCHAR(MAX) NULL,
    [CITY] VARCHAR(MAX) NULL,
    [STATE] VARCHAR(MAX) NULL,
    [ZIP] VARCHAR(MAX) NULL,
    [BIRTH_DATE] DATETIME2 NULL,
    [PHONE] VARCHAR(MAX) NULL,
    [PATIENT_RXCOM_ID] VARCHAR(MAX) NULL,
    [STORE_RPH_ID] VARCHAR(MAX) NULL,
    [STORE_TECH_ID] VARCHAR(MAX) NULL,
    [CARDHOLDERID] VARCHAR(MAX) NULL,
    [DRUG_UPC] VARCHAR(MAX) NULL,
    [PATIENT_DL_NUM] VARCHAR(MAX) NULL,
    [STORE_PATIENT_CODE] VARCHAR(MAX) NULL,
    [MEDICAL_RECORD_NUMBER] VARCHAR(MAX) NULL,
    [LANGUAGE] VARCHAR(MAX) NULL,
    [GENDER] VARCHAR(MAX) NULL,
    [PATIENT_EMAIL_ADDRESS] VARCHAR(MAX) NULL,
    [LOYALTY_CARD_NUMBER] VARCHAR(MAX) NULL,
    [IS_NEW_PATIENT] DECIMAL(38,0) NULL,
    [PATIENT_RECORD_TYPE] VARCHAR(MAX) NULL,
    [ANIMAL_TYPE] VARCHAR(MAX) NULL,
    [CARRIER_CODE] VARCHAR(MAX) NULL,
    [PLAN_CODE] VARCHAR(MAX) NULL,
    [PLAN_NAME] VARCHAR(MAX) NULL,
    [BIN] VARCHAR(MAX) NULL,
    [PCN] VARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [RESPONSIBLE_PARTY_LAST_NAME] VARCHAR(MAX) NULL,
    [RESPONSIBLE_PARTY_FIRST_NAME] VARCHAR(MAX) NULL,
    [VISUALLY_IMPAIRED] VARCHAR(MAX) NULL,
    [PATIENT_DIGITAL_DOC_STATUS] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[RX_PRINT_INFO] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PARTITION_STAMP] DATETIME2 NULL,
    [LABEL] VARCHAR(MAX) NULL,
    [PATIENT_ED] VARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [FREE_FORM_REPORT_FORMAT] VARCHAR(MAX) NULL,
    [FREE_FORM_REPORT_MESSAGE] VARCHAR(MAX) NULL,
    [FREE_FORM_LABEL_FORMAT] VARCHAR(MAX) NULL,
    [FREE_FORM_LABEL_MESSAGE] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[SHIPMENT] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PARTITION_STAMP] DATETIME2 NULL,
    [SIGNATURE] VARCHAR(MAX) NULL,
    [RECEIVED_DATE] DATETIME2 NULL,
    [PRINTED_NAME] VARCHAR(MAX) NULL,
    [RECEIVE_USERID] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[VENDOR_PROP] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [OWNED_ACCOUNT_NUMBER] VARCHAR(MAX) NULL,
    [AUTHORIZATION_INFORMATION] VARCHAR(MAX) NULL,
    [SECURITY_INFORMATION] VARCHAR(MAX) NULL,
    [INTERCHANGE_SENDER_ID_QLF] VARCHAR(MAX) NULL,
    [INTERCHANGE_SENDER_ID] VARCHAR(MAX) NULL,
    [ICHANGE_RECEIVER_ID_QLF] VARCHAR(MAX) NULL,
    [INTERCHANGE_RECEIVER_ID] VARCHAR(MAX) NULL,
    [ICHANGE_CONTROL_STANDARDS_ID] VARCHAR(MAX) NULL,
    [ICHANGE_CTRL_VERSION_NUM] VARCHAR(MAX) NULL,
    [ACK_REQUESTED] VARCHAR(MAX) NULL,
    [USAGE_INDICATOR] VARCHAR(MAX) NULL,
    [COMPONENT_ELEMENT_SEPARATOR] VARCHAR(MAX) NULL,
    [SEGMENT_TERMINATOR] VARCHAR(MAX) NULL,
    [DATA_ELEMENT_SEPARATOR] VARCHAR(MAX) NULL,
    [FUNCTIONAL_IDENTIFIER_CODE] VARCHAR(MAX) NULL,
    [APPLICATION_SENDERS_CODE] VARCHAR(MAX) NULL,
    [APP_RECEIVERS_CODE] VARCHAR(MAX) NULL,
    [RESPONSIBLE_AGENCY_CODE] VARCHAR(MAX) NULL,
    [EDI_VERSION_SUPPORTED] VARCHAR(MAX) NULL,
    [EDI_VERSION_TEXT] VARCHAR(MAX) NULL,
    [PURCHASE_ORDER_TYPE_CODE] VARCHAR(MAX) NULL,
    [IDENTIFICATION_CODE_QLF] VARCHAR(MAX) NULL,
    [IDENTIFICATION_CODE] VARCHAR(MAX) NULL,
    [OWNED_IDENTIFICATION_CODE] VARCHAR(MAX) NULL,
    [CONSIGNED_ACCOUNT_NUMBER] VARCHAR(MAX) NULL,
    [URL_STRING] VARCHAR(MAX) NULL,
    [OWNED_APPLICATION_SENDERS_CODE] VARCHAR(MAX) NULL,
    [OWNED_INTERCHANGE_SENDER_ID] VARCHAR(MAX) NULL,
    [LAST_UPDATED_DATE] DATETIME2 NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(MAX) NULL
);

