-- BATCH 2 TABLES
-- ------------------------------------------------------------------

CREATE TABLE [SBMO].[ADDRESSES] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [ADDRESS] VARCHAR(MAX) NULL,
    [ADDRESS_LINE_2] VARCHAR(MAX) NULL,
    [CITY] VARCHAR(MAX) NULL,
    [STATE] DECIMAL(38,0) NULL,
    [ZIP] VARCHAR(MAX) NULL,
    [OWNER_ID] DECIMAL(38,0) NULL,
    [IDX] DECIMAL(38,0) NULL,
    [COUNTRY] VARCHAR(MAX) NULL,
    [LAST_UPDATED_DATE] DATETIME2 NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[AUDIT_LOG] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [ACTION] DECIMAL(38,0) NULL,
    [NEW_VALUE] VARCHAR(MAX) NULL,
    [OBJECT_NAME] VARCHAR(MAX) NULL,
    [OBJECT_ID] DECIMAL(38,0) NULL,
    [OLD_VALUE] VARCHAR(MAX) NULL,
    [PROPERTY] VARCHAR(MAX) NULL,
    [TIME_STAMP] DATETIME2 NULL,
    [USER_ID] VARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[DASHBOARD_SETTINGS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [REFRESH_MINUTES] DECIMAL(38,0) NULL,
    [DAY_OF_WEEK] DECIMAL(38,0) NULL,
    [START_TIME] DATETIME2 NULL,
    [STOP_TIME] DATETIME2 NULL
);

CREATE TABLE [SBMO].[DASHBOARD_STATISTICS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PEND_STORE] DECIMAL(38,0) NULL,
    [PEND_STORE_OUTSTANDING] DECIMAL(38,0) NULL,
    [PEND_MAIL] DECIMAL(38,0) NULL,
    [PEND_MAIL_OUTSTANDING] DECIMAL(38,0) NULL,
    [PEND_SPECIALTY] DECIMAL(38,0) NULL,
    [PEND_SPECIALTY_OUTSTANDING] DECIMAL(38,0) NULL,
    [PEND_PROMISED_DATE] DECIMAL(38,0) NULL,
    [PEND_PROMISED_DATE_OUTSTANDING] DECIMAL(38,0) NULL,
    [PEND_INADEQ_INVENT] DECIMAL(38,0) NULL,
    [PEND_INADEQ_INVENT_OUTSTANDING] DECIMAL(38,0) NULL,
    [QUEUED] DECIMAL(38,0) NULL,
    [QUEUED_OUTSTANDING] DECIMAL(38,0) NULL,
    [ERROR_TO_DISPENSE] DECIMAL(38,0) NULL,
    [ERROR_TO_DISPENSE_OUTSTANDING] DECIMAL(38,0) NULL,
    [SENT_TO_DISPENSER] DECIMAL(38,0) NULL,
    [CANCELLED_BY_DISPENSER] DECIMAL(38,0) NULL,
    [PROCESSED] DECIMAL(38,0) NULL,
    [REJECTED_INADEQUATE_INVENTORY] DECIMAL(38,0) NULL,
    [CANCELLED_BY_FACILITY] DECIMAL(38,0) NULL,
    [CANCELLED_BY_PHARMACY] DECIMAL(38,0) NULL,
    [NON_FORMULARY] DECIMAL(38,0) NULL,
    [DUPLICATE] DECIMAL(38,0) NULL,
    [LAST_UPDATED_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[ENCRYPTION_KEYS_AUDIT] (
    [ID] DECIMAL(38,0) NULL,
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ENCRYPTION_KEYS_ID] DECIMAL(38,0) NULL,
    [USER_IDENTIFIER] VARCHAR(MAX) NULL,
    [ACTION] DECIMAL(38,0) NULL,
    [OLD_VALUE] VARCHAR(MAX) NULL,
    [NEW_VALUE] VARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [DEACTIVATED_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[ENTITIES] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[FILLING_STATION] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL,
    [TYPE] VARCHAR(MAX) NULL,
    [DESCRIPTION] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[INVENTORY] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [NAME] VARCHAR(MAX) NULL,
    [DATE_OF_LAST_PHYSICAL_COUNT] DATETIME2 NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL,
    [AVAILABLE_FOR_TYPE] DECIMAL(38,0) NULL,
    [IGNORE_NDC_FORMULARY_STORE_DEL] VARCHAR(MAX) NULL,
    [IGNORE_NDC_FORMULARY_MAIL_DEL] VARCHAR(MAX) NULL,
    [IGNORE_NDC_FORMULARY_SPECIALTY] VARCHAR(MAX) NULL,
    [CATEGORY] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_PROCESS_HISTORY] (
    [ID] DECIMAL(38,0) NULL,
    [PDX_SCHEMA_UPD_PKGCALL_HIST_ID] DECIMAL(38,0) NULL,
    [PDX_SCHEMA_VERSION_HISTORY_ID] DECIMAL(38,0) NULL,
    [PROCESS] VARCHAR(MAX) NULL,
    [START_DATE] DATETIME2 NULL,
    [END_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_TASK_HISTORY] (
    [ID] DECIMAL(38,0) NULL,
    [FILE_NAME] VARCHAR(MAX) NULL,
    [PDX_SCHEMA_UPD_PKGCALL_HIST_ID] DECIMAL(38,0) NULL,
    [PDX_SCHEMA_VERSION_HISTORY_ID] DECIMAL(38,0) NULL,
    [TASK_TYPE] VARCHAR(MAX) NULL,
    [ACTION_CODE] VARCHAR(MAX) NULL,
    [STATUS_CODE] VARCHAR(MAX) NULL,
    [START_DATE] DATETIME2 NULL,
    [END_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_VERSION_ERROR_LOG] (
    [ID] DECIMAL(38,0) NULL,
    [ERROR_MESSAGE] VARCHAR(MAX) NULL,
    [SQL_ERROR_CODE] VARCHAR(MAX) NULL,
    [SQL_ERROR_MESSAGE] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[PHONES] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PHONE_NUMBER] VARCHAR(MAX) NULL,
    [OWNER_ID] DECIMAL(38,0) NULL,
    [IDX] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[PURGE_HISTORY_PARTITIONS] (
    [ID] DECIMAL(38,0) NULL,
    [ID_PURGE_HISTORY] DECIMAL(38,0) NULL,
    [TABLE_NAME] VARCHAR(MAX) NULL,
    [PARTITION_NAME] VARCHAR(MAX) NULL,
    [TASK_NAME] VARCHAR(MAX) NULL,
    [START_DATE] DATETIME2 NULL,
    [END_DATE] DATETIME2 NULL,
    [TOT_ELAPSED_SECS] DECIMAL(38,0) NULL,
    [TOT_INDEX_SECS] DECIMAL(38,0) NULL,
    [TOT_NBR_CHUNKS] DECIMAL(38,0) NULL,
    [NBR_ROWS_PURGED] DECIMAL(38,0) NULL,
    [NBR_ROWS_DELETED_FK] DECIMAL(38,0) NULL,
    [NBR_ROWS_DELETED_CHILD_FK] DECIMAL(38,0) NULL,
    [NBR_ROWS_DELETED_GRANDCHILD_FK] DECIMAL(38,0) NULL,
    [TOT_ELAPSED_FK_SECS] DECIMAL(38,0) NULL,
    [NBR_SUBPARTS_DROPPED] DECIMAL(38,0) NULL,
    [TOT_ELAPSED_DROP_SECS] DECIMAL(38,0) NULL,
    [STATUS] VARCHAR(MAX) NULL,
    [CHUNK_SQL] VARCHAR(MAX) NULL,
    [TASK_SQL] VARCHAR(MAX) NULL,
    [FK_SQL] VARCHAR(MAX) NULL,
    [CHILD_FK_SQL] VARCHAR(MAX) NULL,
    [GRANDCHILD_FK_SQL] VARCHAR(MAX) NULL,
    [INDEX_SQL] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[QRTZ_BLOB_TRIGGERS] (
    [TRIGGER_NAME] VARCHAR(MAX) NULL,
    [TRIGGER_GROUP] VARCHAR(MAX) NULL,
    [BLOB_DATA] VARBINARY(MAX) NULL,
    [SCHED_NAME] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[QRTZ_CRON_TRIGGERS] (
    [TRIGGER_NAME] VARCHAR(MAX) NULL,
    [TRIGGER_GROUP] VARCHAR(MAX) NULL,
    [CRON_EXPRESSION] VARCHAR(MAX) NULL,
    [TIME_ZONE_ID] VARCHAR(MAX) NULL,
    [SCHED_NAME] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[QRTZ_SIMPLE_TRIGGERS] (
    [TRIGGER_NAME] VARCHAR(MAX) NULL,
    [TRIGGER_GROUP] VARCHAR(MAX) NULL,
    [REPEAT_COUNT] DECIMAL(38,0) NULL,
    [REPEAT_INTERVAL] DECIMAL(38,0) NULL,
    [TIMES_TRIGGERED] DECIMAL(38,0) NULL,
    [SCHED_NAME] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[QRTZ_SIMPROP_TRIGGERS] (
    [SCHED_NAME] VARCHAR(MAX) NULL,
    [TRIGGER_NAME] VARCHAR(MAX) NULL,
    [TRIGGER_GROUP] VARCHAR(MAX) NULL,
    [STR_PROP_1] VARCHAR(MAX) NULL,
    [STR_PROP_2] VARCHAR(MAX) NULL,
    [STR_PROP_3] VARCHAR(MAX) NULL,
    [INT_PROP_1] DECIMAL(38,0) NULL,
    [INT_PROP_2] DECIMAL(38,0) NULL,
    [LONG_PROP_1] DECIMAL(38,0) NULL,
    [LONG_PROP_2] DECIMAL(38,0) NULL,
    [DEC_PROP_1] DECIMAL(38,0) NULL,
    [DEC_PROP_2] DECIMAL(38,0) NULL,
    [BOOL_PROP_1] VARCHAR(MAX) NULL,
    [BOOL_PROP_2] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[REPORT_REQUEST] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [REPORT_NAME] VARCHAR(MAX) NULL,
    [USER_ID] VARCHAR(MAX) NULL,
    [FORMAT] VARCHAR(MAX) NULL,
    [SUBMISSION_DATE] DATETIME2 NULL,
    [START_DATE] DATETIME2 NULL,
    [COMPLETION_DATE] DATETIME2 NULL,
    [STATUS] VARCHAR(MAX) NULL,
    [DOWNLOAD_LINK] VARCHAR(MAX) NULL,
    [HASH] DECIMAL(38,0) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[RX_CORES_MIN_DATE] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [STATUS] DECIMAL(38,0) NULL,
    [MIN_DATE] DATETIME2 NULL,
    [DATE_TYPE] DECIMAL(38,0) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[SCHEDULED_TASKS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [JOB_NAME] VARCHAR(MAX) NULL,
    [REPEAT] DECIMAL(38,0) NULL,
    [REPEAT_INTERVAL] DECIMAL(38,0) NULL,
    [REPEAT_INTERVAL_UNIT] DECIMAL(38,0) NULL,
    [TASK_NAME] VARCHAR(MAX) NULL,
    [START_TIME] DATETIME2 NULL,
    [ENABLED] DECIMAL(38,0) NULL,
    [LAST_EXECUTION_DATE] DATETIME2 NULL,
    [LAST_EXECUTION_RESULT] VARCHAR(MAX) NULL,
    [PROPS] VARBINARY(MAX) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[SHIP_ITEMS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PARTITION_STAMP] DATETIME2 NULL,
    [PURCHASE_ORDER_NUMBER] VARCHAR(MAX) NULL,
    [SHIPMENT_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[SYSTEM_MESSAGES] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PARTITION_STAMP] DATETIME2 NULL,
    [MESSAGE] VARCHAR(MAX) NULL,
    [ADDED_DATE] DATETIME2 NULL,
    [MESSAGE_TYPE] DECIMAL(38,0) NULL,
    [ACKNOWLEDGED_BY] VARCHAR(MAX) NULL,
    [ACKNOWLEDGED] DATETIME2 NULL,
    [DATA] VARBINARY(MAX) NULL,
    [ERROR_TYPE] DECIMAL(38,0) NULL,
    [RESOLUTION_TEXT] VARCHAR(MAX) NULL,
    [REFERENCE_ID] DECIMAL(38,0) NULL,
    [REFERENCE_TYPE] DECIMAL(38,0) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL
);

