-- BATCH 0 TABLES
-- --------------------------------------------------------

CREATE TABLE [SBMO].[ADJUSTMENT_CODES] (
    [ID] BIGINT NOT NULL,
    [CODE] VARCHAR(3) NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2 NOT NULL,
    [DEACTIVATED_DATE] DATETIME2 NULL,
    [DESCRIPTION] VARCHAR(255) NOT NULL,
    [CREATED_DATE] DATETIME2 NOT NULL,
    [CHANGE_ON_HAND] VARCHAR(1) NOT NULL
);

CREATE TABLE [SBMO].[AUDIT_DBU_LOG] (
    [ID] DECIMAL(38,0) NULL,
    [EXEC_TIME_STAMP] DATETIME2 NULL,
    [USER_ID] VARCHAR(30) NULL,
    [DBU_TABLE] VARCHAR(30) NULL,
    [DBU_PARMS] VARCHAR(2000) NULL,
    [DBU_ROWS] DECIMAL(38,0) NULL,
    [SQL_TEXT] VARCHAR(2000) NULL,
    [ERROR_TEXT] VARCHAR(2000) NULL
);

CREATE TABLE [SBMO].[CR18985_LOG] (
    [TABLE_NAME] VARCHAR(35) NULL,
    [OBJECT_NAME] VARCHAR(35) NULL,
    [OBJECT_TYPE] VARCHAR(35) NULL,
    [ERROR_CODE] VARCHAR(35) NULL,
    [ERROR_MSG] VARCHAR(210) NULL
);

CREATE TABLE [SBMO].[DRUGS] (
    [ID] BIGINT NOT NULL,
    [DECIMAL_PACK] FLOAT NOT NULL,
    [GENERIC_FULL_NAME] VARCHAR(60) NOT NULL,
    [DRUG_FULL_NAME] VARCHAR(60) NOT NULL,
    [GENERIC_NAME] VARCHAR(28) NOT NULL,
    [GPI] VARCHAR(14) NULL,
    [INJECT] DECIMAL(1,0) NOT NULL,
    [DRUG_NOTE] VARCHAR(255) NULL,
    [MFG] VARCHAR(10) NOT NULL,
    [NAME] VARCHAR(28) NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [PACK] BIGINT NOT NULL,
    [PREVIOUS_NDC] VARCHAR(11) NULL,
    [REPLACEMENT_NDC] VARCHAR(11) NULL,
    [SCHEDULE] VARCHAR(1) NOT NULL,
    [STRENGTH] VARCHAR(8) NULL,
    [TRIPLIC] DECIMAL(1,0) NOT NULL,
    [UNIT] VARCHAR(3) NOT NULL,
    [MFG_DISCONTINUE_DATE] DATETIME2 NULL,
    [LAST_UPDATED_DATE] DATETIME2 NOT NULL,
    [SIGNATURE_REQUIRED] DECIMAL(1,0) NOT NULL,
    [AWP] FLOAT NOT NULL,
    [AWP_LAST_UPDATED] DATETIME2 NOT NULL,
    [BARCODE] VARCHAR(16) NULL,
    [NDCFMT] INT NULL,
    [PACKAGE_QTY] FLOAT NULL,
    [IND_PACK] FLOAT NULL,
    [MULTI_SOURCE] VARCHAR(1) NULL,
    [DDID] INT NULL,
    [NARCOTIC_INDICATOR] VARCHAR(2) NULL,
    [DEEP_FROZEN] DECIMAL(1,0) NOT NULL,
    [BIN_STORAGE_TYPE] DECIMAL(1,0) NULL,
    [HAZARDOUS_DRUG] VARCHAR(1) NULL,
    [INNER_PACK_INDICATOR] VARCHAR(1) NULL
);

CREATE TABLE [SBMO].[EXT_DRUG_LOAD] (
    [DRUG_FULL_NAME] VARCHAR(255) NULL,
    [NDC] VARCHAR(255) NULL,
    [GENERIC_NAME] VARCHAR(255) NULL,
    [GENERIC_FULL_NAME] VARCHAR(255) NULL,
    [MFG] VARCHAR(255) NULL,
    [UNIT] VARCHAR(255) NULL,
    [STRENGTH] VARCHAR(255) NULL,
    [SCHEDULE] VARCHAR(255) NULL,
    [PACK] VARCHAR(255) NULL,
    [DECIMAL_PACK] VARCHAR(255) NULL,
    [PACKAGE_QTY] VARCHAR(255) NULL,
    [IND_PACK] VARCHAR(255) NULL,
    [AWP] VARCHAR(255) NULL,
    [AWP_LAST_UPDATED] VARCHAR(255) NULL,
    [MULTI_SOURCE] VARCHAR(255) NULL,
    [TRIPLIC] VARCHAR(255) NULL,
    [INJECT] VARCHAR(255) NULL,
    [REFRIGERATED] VARCHAR(255) NULL,
    [SIGNATURE_REQUIRED] VARCHAR(255) NULL,
    [HAZMAT] VARCHAR(255) NULL,
    [LAST_UPDATED_DATE] VARCHAR(255) NULL,
    [BARCODE] VARCHAR(255) NULL,
    [DRUG_NOTE] VARCHAR(255) NULL,
    [GPI] VARCHAR(255) NULL,
    [ID] VARCHAR(255) NULL,
    [MFG_DISCONTINUE_DATE] VARCHAR(255) NULL,
    [NDCFMT] VARCHAR(255) NULL,
    [PREVIOUS_NDC] VARCHAR(255) NULL,
    [REPLACEMENT_NDC] VARCHAR(255) NULL
);

CREATE TABLE [SBMO].[MEDICAL_SUPPLIES_28MAY26] (
    [ID] DECIMAL(38,0) NOT NULL,
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [RX_CORE_ID] DECIMAL(38,0) NOT NULL,
    [NAME] VARCHAR(60) NOT NULL
);

CREATE TABLE [SBMO].[MUTEX] (
    [STATUS] VARCHAR(25) NOT NULL,
    [LAST_RUN_TIME] DATETIME2 NOT NULL
);

CREATE TABLE [SBMO].[MV_FORMULARY] (
    [NDC] VARCHAR(11) NOT NULL,
    [ITEM_NUMBER] VARCHAR(15) NOT NULL,
    [ONHAND_QTY] BIGINT NOT NULL,
    [ALLOCATED_QTY] BIGINT NOT NULL,
    [REFRESH_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[OBJECT_MAPPING] (
    [OBJECT_NAME] VARCHAR(30) NULL,
    [OBJECT_TYPE] VARCHAR(30) NULL,
    [SOURCE_TABLE] VARCHAR(30) NULL,
    [REDEF_OWNER] VARCHAR(30) NULL,
    [REDEF_OBJECT_NAME] VARCHAR(35) NULL,
    [REDEF_TABLE] VARCHAR(30) NULL,
    [REDEF_SQL] VARCHAR(MAX) NULL,
    [REDEF_STATUS] VARCHAR(10) NULL,
    [RENAME_STATUS] VARCHAR(10) NULL
);

CREATE TABLE [SBMO].[PARTITION_SQL_HISTORY] (
    [ID] DECIMAL(38,0) NULL,
    [SQL_TIMESTAMP] DATETIME2 NULL,
    [SQL_TEXT] VARCHAR(MAX) NULL,
    [SQL_ERROR] VARCHAR(4000) NULL,
    [REPORT_ERROR] VARCHAR(1) NULL
);

CREATE TABLE [SBMO].[PARTITION_TABLE_LIST] (
    [TABLE_NAME] VARCHAR(30) NOT NULL
);

CREATE TABLE [SBMO].[PDX_DBA_APPLIED] (
    [ACTION_CODE] VARCHAR(25) NULL,
    [ACTIVITY_DATE] DATETIME2 NULL,
    [ACTIVITY_USER] VARCHAR(30) NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_CONFIG] (
    [VALUE] VARCHAR(1000) NOT NULL,
    [SOURCE] VARCHAR(1) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_FILE_HASH] (
    [FILE_SOURCE] VARCHAR(1) NOT NULL,
    [FILE_HASH] VARCHAR(32) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_FILE_TASKVER] (
    [TASK_VERSION] VARCHAR(255) NOT NULL,
    [FILE_TYPE] VARCHAR(1) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_MAPPING] (
    [SEARCH] VARCHAR(40) NOT NULL,
    [REPLACE] VARCHAR(30) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_PRIV_DEFAULT] (
    [PRIVILEGE] VARCHAR(40) NOT NULL,
    [GRANTEE] VARCHAR(30) NOT NULL,
    [SOURCE] VARCHAR(1) NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_PRIV_EXCEPTION] (
    [OBJECT_NAME] VARCHAR(30) NOT NULL,
    [PRIVILEGE] VARCHAR(40) NOT NULL,
    [GRANTEE] VARCHAR(30) NOT NULL,
    [SOURCE] VARCHAR(1) NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_TASKVER_META] (
    [TASK_SOURCE] VARCHAR(1) NOT NULL,
    [META_TAG] VARCHAR(20) NOT NULL,
    [TASK_VERSION_VALUE] VARCHAR(255) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_UPDATER_MANIFEST] (
    [VERSION] VARCHAR(20) NOT NULL,
    [FILE_NAME] VARCHAR(100) NOT NULL,
    [APPLY_ORDER] INT NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_UPDATER_SQL] (
    [FILE_NAME] VARCHAR(255) NOT NULL,
    [VERSION] VARCHAR(20) NULL,
    [ACTION_CODE] VARCHAR(1) NULL,
    [ACTION_DATE] DATETIME2 NULL,
    [STATUS_CODE] VARCHAR(1) NULL,
    [STATEMENT_INDEX] DECIMAL(38,0) NULL,
    [SQL] VARCHAR(MAX) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_H] (
    [ID] DECIMAL(38,0) NOT NULL,
    [PROC] VARCHAR(30) NOT NULL,
    [PARMS] VARCHAR(4000) NULL,
    [DEBUG_TIMESTAMP] DATETIME2 NULL,
    [SQL_ERROR] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_UPD_PKGCALL_HIST] (
    [ID] DECIMAL(38,0) NOT NULL,
    [TARGET_VERSION] VARCHAR(20) NULL,
    [STATUS_CODE] VARCHAR(1) NULL,
    [RETURN_CODE] DECIMAL(2,0) NULL,
    [START_DATE] DATETIME2 NULL,
    [END_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[PRESTATS_INVENTORY] (
    [TYPE] CHAR(1) NULL,
    [VERSION] DECIMAL(38,0) NULL,
    [FLAGS] DECIMAL(38,0) NULL,
    [C1] VARCHAR(128) NULL,
    [C2] VARCHAR(128) NULL,
    [C3] VARCHAR(128) NULL,
    [C4] VARCHAR(128) NULL,
    [C5] VARCHAR(128) NULL,
    [C6] VARCHAR(128) NULL,
    [N1] DECIMAL(38,0) NULL,
    [N2] DECIMAL(38,0) NULL,
    [N3] DECIMAL(38,0) NULL,
    [N4] DECIMAL(38,0) NULL,
    [N5] DECIMAL(38,0) NULL,
    [N6] DECIMAL(38,0) NULL,
    [N7] DECIMAL(38,0) NULL,
    [N8] DECIMAL(38,0) NULL,
    [N9] DECIMAL(38,0) NULL,
    [N10] DECIMAL(38,0) NULL,
    [N11] DECIMAL(38,0) NULL,
    [N12] DECIMAL(38,0) NULL,
    [N13] DECIMAL(38,0) NULL,
    [D1] DATETIME2 NULL,
    [T1] DATETIME2 NULL,
    [R1] VARBINARY(1000) NULL,
    [R2] VARBINARY(1000) NULL,
    [R3] VARBINARY(1000) NULL,
    [CH1] VARCHAR(1000) NULL,
    [CL1] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[PRESTATS_ORDERS] (
    [TYPE] CHAR(1) NULL,
    [VERSION] DECIMAL(38,0) NULL,
    [FLAGS] DECIMAL(38,0) NULL,
    [C1] VARCHAR(128) NULL,
    [C2] VARCHAR(128) NULL,
    [C3] VARCHAR(128) NULL,
    [C4] VARCHAR(128) NULL,
    [C5] VARCHAR(128) NULL,
    [C6] VARCHAR(128) NULL,
    [N1] DECIMAL(38,0) NULL,
    [N2] DECIMAL(38,0) NULL,
    [N3] DECIMAL(38,0) NULL,
    [N4] DECIMAL(38,0) NULL,
    [N5] DECIMAL(38,0) NULL,
    [N6] DECIMAL(38,0) NULL,
    [N7] DECIMAL(38,0) NULL,
    [N8] DECIMAL(38,0) NULL,
    [N9] DECIMAL(38,0) NULL,
    [N10] DECIMAL(38,0) NULL,
    [N11] DECIMAL(38,0) NULL,
    [N12] DECIMAL(38,0) NULL,
    [N13] DECIMAL(38,0) NULL,
    [D1] DATETIME2 NULL,
    [T1] DATETIME2 NULL,
    [R1] VARBINARY(1000) NULL,
    [R2] VARBINARY(1000) NULL,
    [R3] VARBINARY(1000) NULL,
    [CH1] VARCHAR(1000) NULL,
    [CL1] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[PRESTATS_RX_CORES] (
    [TYPE] CHAR(1) NULL,
    [VERSION] DECIMAL(38,0) NULL,
    [FLAGS] DECIMAL(38,0) NULL,
    [C1] VARCHAR(128) NULL,
    [C2] VARCHAR(128) NULL,
    [C3] VARCHAR(128) NULL,
    [C4] VARCHAR(128) NULL,
    [C5] VARCHAR(128) NULL,
    [C6] VARCHAR(128) NULL,
    [N1] DECIMAL(38,0) NULL,
    [N2] DECIMAL(38,0) NULL,
    [N3] DECIMAL(38,0) NULL,
    [N4] DECIMAL(38,0) NULL,
    [N5] DECIMAL(38,0) NULL,
    [N6] DECIMAL(38,0) NULL,
    [N7] DECIMAL(38,0) NULL,
    [N8] DECIMAL(38,0) NULL,
    [N9] DECIMAL(38,0) NULL,
    [N10] DECIMAL(38,0) NULL,
    [N11] DECIMAL(38,0) NULL,
    [N12] DECIMAL(38,0) NULL,
    [N13] DECIMAL(38,0) NULL,
    [D1] DATETIME2 NULL,
    [T1] DATETIME2 NULL,
    [R1] VARBINARY(1000) NULL,
    [R2] VARBINARY(1000) NULL,
    [R3] VARBINARY(1000) NULL,
    [CH1] VARCHAR(1000) NULL,
    [CL1] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[PURGE_CONFIG_SETTINGS] (
    [VALUE] VARCHAR(4000) NOT NULL,
    [COMMENTS] VARCHAR(4000) NULL
);

CREATE TABLE [SBMO].[PURGE_ERROR_LOG] (
    [ID] DECIMAL(38,0) NOT NULL,
    [ERROR_TIME] DATETIME2 NOT NULL,
    [CODE_BLOCK] VARCHAR(30) NOT NULL,
    [SQL_CODE] DECIMAL(38,0) NULL,
    [SQL_ERRM] VARCHAR(250) NULL,
    [EXCEPTION_MESSAGE] VARCHAR(4000) NOT NULL,
    [PARAMETER_VALUES] VARCHAR(4000) NULL
);

CREATE TABLE [SBMO].[PURGE_RUN_CHECK] (
    [ACTIVITY_DATE] DATETIME2 NOT NULL,
    [PURGE_RUNNING] CHAR(1) NOT NULL
);

CREATE TABLE [SBMO].[PURGE_TABLES] (
    [PURGE_POSITION] DECIMAL(38,0) NOT NULL,
    [PURGE_COLUMN] VARCHAR(30) NOT NULL,
    [PARALLEL_COUNT] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[QRTZ_CALENDARS] (
    [CALENDAR] VARBINARY(MAX) NOT NULL,
    [SCHED_NAME] VARCHAR(120) NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_FIRED_TRIGGERS] (
    [TRIGGER_NAME] VARCHAR(200) NOT NULL,
    [TRIGGER_GROUP] VARCHAR(200) NOT NULL,
    [INSTANCE_NAME] VARCHAR(200) NOT NULL,
    [FIRED_TIME] DECIMAL(13,0) NOT NULL,
    [STATE] VARCHAR(16) NOT NULL,
    [JOB_NAME] VARCHAR(200) NULL,
    [JOB_GROUP] VARCHAR(200) NULL,
    [REQUESTS_RECOVERY] VARCHAR(1) NULL,
    [PRIORITY] DECIMAL(13,0) NULL,
    [IS_NONCONCURRENT] VARCHAR(11) NULL,
    [IS_UPDATE_DATA] VARCHAR(11) NULL,
    [SCHED_NAME] VARCHAR(120) NOT NULL,
    [SCHED_TIME] DECIMAL(13,0) NULL
);

CREATE TABLE [SBMO].[QRTZ_JOB_DETAILS] (
    [JOB_GROUP] VARCHAR(200) NOT NULL,
    [DESCRIPTION] VARCHAR(250) NULL,
    [JOB_CLASS_NAME] VARCHAR(250) NOT NULL,
    [IS_DURABLE] VARCHAR(1) NOT NULL,
    [REQUESTS_RECOVERY] VARCHAR(1) NOT NULL,
    [JOB_DATA] VARBINARY(MAX) NULL,
    [IS_NONCONCURRENT] VARCHAR(11) NULL,
    [IS_UPDATE_DATA] VARCHAR(11) NULL,
    [SCHED_NAME] VARCHAR(120) NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_LOCKS] (
    [SCHED_NAME] VARCHAR(120) NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_PAUSED_TRIGGER_GRPS] (
    [SCHED_NAME] VARCHAR(120) NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_SCHEDULER_STATE] (
    [LAST_CHECKIN_TIME] DECIMAL(13,0) NOT NULL,
    [CHECKIN_INTERVAL] DECIMAL(13,0) NOT NULL,
    [SCHED_NAME] VARCHAR(120) NOT NULL
);


CREATE TABLE [SBMO].[SBMO_LOCKS] (
    [LOCK_NAME] VARCHAR(40) NOT NULL
);

CREATE TABLE [SBMO].[SBMO_PROPERTIES] (
    [ID] BIGINT NOT NULL,
    [KEY] VARCHAR(255) NOT NULL,
    [VALUE] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[SCHEMA_UPDATER_MANIFEST] (
    [FILE_NAME] VARCHAR(100) NOT NULL,
    [VERSION] VARCHAR(20) NOT NULL,
    [APPLY_ORDER] INT NOT NULL
);

CREATE TABLE [SBMO].[SCHEMA_UPDATER_SQL] (
    [FILE_NAME] VARCHAR(255) NOT NULL,
    [CHECKSUM] VARCHAR(64) NOT NULL,
    [SQL] VARCHAR(MAX) NOT NULL
);

CREATE TABLE [SBMO].[STAT_EXPORT] (
    [TYPE] CHAR(1) NULL,
    [VERSION] DECIMAL(38,0) NULL,
    [FLAGS] DECIMAL(38,0) NULL,
    [C1] VARCHAR(30) NULL,
    [C2] VARCHAR(30) NULL,
    [C3] VARCHAR(30) NULL,
    [C4] VARCHAR(30) NULL,
    [C5] VARCHAR(30) NULL,
    [N1] DECIMAL(38,0) NULL,
    [N2] DECIMAL(38,0) NULL,
    [N3] DECIMAL(38,0) NULL,
    [N4] DECIMAL(38,0) NULL,
    [N5] DECIMAL(38,0) NULL,
    [N6] DECIMAL(38,0) NULL,
    [N7] DECIMAL(38,0) NULL,
    [N8] DECIMAL(38,0) NULL,
    [N9] DECIMAL(38,0) NULL,
    [N10] DECIMAL(38,0) NULL,
    [N11] DECIMAL(38,0) NULL,
    [N12] DECIMAL(38,0) NULL,
    [D1] DATETIME2 NULL,
    [R1] VARBINARY(32) NULL,
    [R2] VARBINARY(32) NULL,
    [CH1] VARCHAR(1000) NULL
);

CREATE TABLE [SBMO].[TENANTS] (
    [ID] BIGINT NOT NULL,
    [NAME] VARCHAR(15) NOT NULL,
    [ADDRESS_LINE_1] VARCHAR(30) NOT NULL,
    [ADDRESS_LINE_2] VARCHAR(30) NULL,
    [CITY] VARCHAR(35) NOT NULL,
    [STATE] VARCHAR(2) NOT NULL,
    [ZIP] VARCHAR(15) NOT NULL,
    [COUNTY] VARCHAR(15) NOT NULL,
    [NHINID] BIGINT NOT NULL,
    [TIME_ZONE] VARCHAR(50) NOT NULL,
    [LOCAL_PHONE_NUMBER] VARCHAR(10) NOT NULL,
    [TOLL_FREE_PHONE_NUMBER] VARCHAR(10) NOT NULL,
    [ALTERNATE_PHONE_NUMBER] VARCHAR(10) NULL,
    [ACTIVE_DIRECTORY_GROUP] VARCHAR(255) NOT NULL,
    [IS_RXCOM] VARCHAR(5) NOT NULL,
    [NHIN_NAME_ABBREVIATION] VARCHAR(3) NULL
);

CREATE TABLE [SBMO].[USER_AUDIT_LOG] (
    [ID] BIGINT NOT NULL,
    [ACTION] INT NOT NULL,
    [TIME_STAMP] DATETIME2 NOT NULL,
    [USER_ID] VARCHAR(255) NOT NULL,
    [MESSAGE] VARCHAR(255) NULL,
    [CREATED_DATE] DATETIME2 NULL
);