-- BATCH 5 TABLES
-- ------------------------------------------------------------------

CREATE TABLE [SBMO].[CF_SEC_STORE] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [LOAD_DATE] DATETIME2 NULL,
    [PASS_PHRASE] VARCHAR(MAX) NULL,
    [PRIVATE_KEY] VARCHAR(MAX) NULL,
    [REGISTRATION_DATE] DATETIME2 NULL,
    [SSL_CERTIFICATE] VARCHAR(MAX) NULL,
    [CHAIN_ID] DECIMAL(38,0) NULL,
    [REG_STATUS] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[DRUG_ORDERS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PARTITION_STAMP] DATETIME2 NULL,
    [NDC] VARCHAR(MAX) NULL,
    [ACK_RECEIVED_QTY] FLOAT NULL,
    [PACK] FLOAT NULL,
    [COST] FLOAT NULL,
    [COUNTER] DECIMAL(38,0) NULL,
    [ITEM_STATUS] VARCHAR(MAX) NULL,
    [SUB_ITEM_NUMBER] VARCHAR(MAX) NULL,
    [ITEM_NUMBER] VARCHAR(MAX) NULL,
    [ORDER_QTY] FLOAT NULL,
    [RECQTY] FLOAT NULL,
    [CHECK_IN_DATE] DATETIME2 NULL,
    [APPLIED_TO_INVENTORY_DATE] DATETIME2 NULL,
    [FORMULARY_ID] DECIMAL(38,0) NULL,
    [PURCHASE_ORDER_ID] DECIMAL(38,0) NULL,
    [VENDOR_ORDER_QTY] FLOAT NULL,
    [VENDOR_ACK_RECEIVED_QTY] FLOAT NULL,
    [VENDOR_RECQTY] FLOAT NULL,
    [APPLIED_QTY] DECIMAL(38,0) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [CONVERSION_FACTOR] FLOAT NULL,
    [VENDOR_ORDER_CASE] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[ITEM_LOCATION] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [FORMULARY_ID] DECIMAL(38,0) NULL,
    [QUANTITY] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[MASTER_PRODUCT_PO_VERIFY] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PURCHASE_ORDER_ID] DECIMAL(38,0) NULL,
    [VENDOR_ID] DECIMAL(38,0) NULL,
    [ORDER_DATE] DATETIME2 NULL,
    [TOTAL_ITEMS] DECIMAL(38,0) NULL,
    [PERCENT_SCANNED] DECIMAL(38,0) NULL,
    [PERCENT_PASSED] DECIMAL(38,0) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [PURCHASE_ORDER_STATUS] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[MESSAGE_LOG] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [MESSAGE_DATE] DATETIME2 NULL,
    [MESSAGE] VARCHAR(MAX) NULL,
    [STORE_ID] DECIMAL(38,0) NULL,
    [USER_INITS] VARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[ORDERS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PARTITION_STAMP] DATETIME2 NULL,
    [ORDER_NUMBER] DECIMAL(38,0) NULL,
    [SHIP_ADDRESS] VARCHAR(MAX) NULL,
    [SHIP_ADDRESS2] VARCHAR(MAX) NULL,
    [SHIP_CITY] VARCHAR(MAX) NULL,
    [SHIP_FIRST_NAME] VARCHAR(MAX) NULL,
    [SHIP_MIDDLE_NAME] VARCHAR(MAX) NULL,
    [SHIP_LAST_NAME] VARCHAR(MAX) NULL,
    [SHIP_PHONE] VARCHAR(MAX) NULL,
    [SHIP_STATE] VARCHAR(MAX) NULL,
    [ORDER_TYPE] DECIMAL(38,0) NULL,
    [SHIP_TYPE] DECIMAL(38,0) NULL,
    [SHIP_ZIP] VARCHAR(MAX) NULL,
    [STORE_DEA] VARCHAR(MAX) NULL,
    [STORE_LIC] VARCHAR(MAX) NULL,
    [STORE_EST_SHIP_AMT] FLOAT NULL,
    [SIGNATURE_REQUIRED] DECIMAL(38,0) NULL,
    [STORE_ID] DECIMAL(38,0) NULL,
    [ORDER_PROCESSED] DECIMAL(38,0) NULL,
    [INVENTORY_ID] DECIMAL(38,0) NULL,
    [GROUPING_CODE] VARCHAR(MAX) NULL,
    [ALLOW_GROUPING] DECIMAL(38,0) NULL,
    [BATCH_IDENTIFIER] DECIMAL(38,0) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [PROMISED_DATE] DATETIME2 NULL,
    [PROMISE_DATE_OVERRIDE] VARCHAR(MAX) NULL,
    [REQUESTED_SHIP_DATE] DATETIME2 NULL,
    [SHIPPING_INSTRUCTIONS] VARCHAR(MAX) NULL,
    [EXTERNAL_ORDER_IDENTIFIER] VARCHAR(MAX) NULL,
    [VENDOR_CARRIER_CODE_IDENT] VARCHAR(MAX) NULL,
    [VENDOR_CARRIER_CODE_DESC] VARCHAR(MAX) NULL,
    [VENDOR_SHIP_BOX_IDENT] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[PRIORITY_CHANGE_ALERTS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [FORMULARY_ID] DECIMAL(38,0) NULL,
    [NDC] VARCHAR(MAX) NULL,
    [ACTION] DECIMAL(38,0) NULL,
    [ADDED_DATE] DATETIME2 NULL,
    [ACKNOWLEDGED] DATETIME2 NULL,
    [ACKNOWLEDGED_BY] VARCHAR(MAX) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[STORE_SHIP_VIA] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [ORDER_TYPE] DECIMAL(38,0) NULL,
    [SHIP_TYPE] DECIMAL(38,0) NULL,
    [SHIP_VIA] VARCHAR(MAX) NULL,
    [STORE_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[STORE_VENDOR_ACCOUNT] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [MAIL_ACCOUNT_NUM] VARCHAR(MAX) NULL,
    [STORE_ID] DECIMAL(38,0) NULL,
    [STORE_ACCOUNT_NUM] VARCHAR(MAX) NULL,
    [VENDOR_ID] DECIMAL(38,0) NULL
);

