CREATE TABLE DIB5_AUX.AGFILE
( 
	AG CHAR(3) NOT NULL,
	ACLASS VARCHAR2(25),
	CSC_0 CHAR(3),
	CSC_1 CHAR(3),
	CSC_2 CHAR(3),
	CSC_3 CHAR(3),
	CSC_4 CHAR(3),
	CSC_5 CHAR(3),
	CR CHAR(1)
)
/
CREATE TABLE DIB5_AUX.DISFILE
( 
	CODE VARCHAR2(10) NOT NULL,
	DESCRIPTION VARCHAR2(25) NOT NULL,
	MNEMONIC VARCHAR2(10) NOT NULL,
	DURATION VARCHAR2(1) NOT NULL,
	DEACTIVATE_DATE TIMESTAMP(6)
)
/
CREATE TABLE DIB5_AUX.MMW_FC_CONTENT
( 
	ID NUMBER(6, 0) NOT NULL,
	CONTENT CLOB
)
/
CREATE TABLE DIB5_AUX.MMW_FC_DRUGLINK
( 
	DRUGID VARCHAR2(20) NOT NULL,
	ELEMENTID NUMBER(38, 0) NOT NULL,
	DOCUMENTCODE VARCHAR2(10) NOT NULL
)
/
CREATE TABLE DIB5_AUX.MMW_FC_ELEMENT
( 
	ELEMENTID NUMBER(38, 0) NOT NULL,
	DOCUMENTCODE VARCHAR2(10) NOT NULL,
	PARENTID NUMBER(38, 0) NOT NULL,
	CHILDSEQUENCE NUMBER(38, 0) NOT NULL,
	TAGTYPE VARCHAR2(40) NOT NULL,
	IDATTRIBUTE VARCHAR2(32),
	HASSECTIONSIND NUMBER(38, 0) NOT NULL,
	FILENAME VARCHAR2(30) NOT NULL,
	ELEMENTTITLE VARCHAR2(255) NOT NULL,
	XPATH VARCHAR2(255)
)
/
CREATE TABLE DIB5_AUX.MMW_FC_SECTION
( 
	SECTIONID NUMBER(38, 0) NOT NULL,
	SECTIONTITLE VARCHAR2(40) NOT NULL,
	XPATH VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB5_AUX.MMW_FC_SECTION_CONTENT
( 
	MONOGRAPH_ID NUMBER(6, 0) NOT NULL,
	SECTION_ID NUMBER(22, 0) NOT NULL,
	CONTENT CLOB
)
/
CREATE TABLE DIB5_AUX.MMW_FC_SECTIONLINK
( 
	ELEMENTID NUMBER(38, 0) NOT NULL,
	SECTIONID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB5_AUX.TOP_DRUGS
( 
	DESCSEARCH VARCHAR2(35)
)
/
CREATE INDEX DIB5_AUX.IXMMWFCELEMENT1 ON DIB5_AUX.MMW_FC_ELEMENT
(
	IDATTRIBUTE
)
/
CREATE UNIQUE INDEX DIB5_AUX.MMW_FC_CONTENT_ID_PK_1 ON DIB5_AUX.MMW_FC_CONTENT
(
	ID
)
/
CREATE UNIQUE INDEX DIB5_AUX.MMW_FC_SECTION_CONTENT_PK ON DIB5_AUX.MMW_FC_SECTION_CONTENT
(
	MONOGRAPH_ID,
	SECTION_ID
)
/
CREATE UNIQUE INDEX DIB5_AUX.PKMMWFCDRUGLINK ON DIB5_AUX.MMW_FC_DRUGLINK
(
	DRUGID,
	ELEMENTID,
	DOCUMENTCODE
)
/
CREATE UNIQUE INDEX DIB5_AUX.PKMMWFCELEMENT ON DIB5_AUX.MMW_FC_ELEMENT
(
	ELEMENTID
)
/
CREATE UNIQUE INDEX DIB5_AUX.PKMMWFCSECTION ON DIB5_AUX.MMW_FC_SECTION
(
	SECTIONID
)
/
CREATE UNIQUE INDEX DIB5_AUX.PKMMWFCSECTIONLINK ON DIB5_AUX.MMW_FC_SECTIONLINK
(
	ELEMENTID,
	SECTIONID
)
/
