CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_BASIC
	FOR DIB5_1.IMGIPT_BASIC
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_CATEGORY
	FOR DIB5_1.IMGIPT_CATEGORY
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_DESC
	FOR DIB5_1.IMGIPT_DESC
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_DOSE_FORM
	FOR DIB5_1.IMGIPT_DOSE_FORM
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_IMAGE
	FOR DIB5_1.IMGIPT_IMAGE
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_IMPRINT
	FOR DIB5_1.IMGIPT_IMPRINT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_JOURNAL
	FOR DIB5_1.IMGIPT_JOURNAL
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_LIB_VERSION
	FOR DIB5_1.IMGIPT_LIB_VERSION
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_MANUFACT
	FOR DIB5_1.IMGIPT_MANUFACT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_PROP_DESC
	FOR DIB5_1.IMGIPT_PROP_DESC
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_PROP_TEXT
	FOR DIB5_1.IMGIPT_PROP_TEXT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_PROPERTY
	FOR DIB5_1.IMGIPT_PROPERTY
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_TEXT
	FOR DIB5_1.IMGIPT_TEXT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.IMGIPT_UNIQUE
	FOR DIB5_1.IMGIPT_UNIQUE
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_ADE_COM
	FOR DIB5_1.MMW_ADE_COM
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_ADE_DRUGLINK
	FOR DIB5_1.MMW_ADE_DRUGLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_ADE_SPECCOND
	FOR DIB5_1.MMW_ADE_SPECCOND
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_ALLERGEN_LIST
	FOR DIB5_1.MMW_ALLERGEN_LIST
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_CLS_AHFS
	FOR DIB5_1.MMW_CLS_AHFS
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_CLS_AHFSDRUG
	FOR DIB5_1.MMW_CLS_AHFSDRUG
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_CLS_GPI
	FOR DIB5_1.MMW_CLS_GPI
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_CLS_GPIDRUG
	FOR DIB5_1.MMW_CLS_GPIDRUG
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_CM_DISPLINK
	FOR DIB5_1.MMW_CM_DISPLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_CM_PACKLINK
	FOR DIB5_1.MMW_CM_PACKLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_CM_TEXT
	FOR DIB5_1.MMW_CM_TEXT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DCK_COM
	FOR DIB5_1.MMW_DCK_COM
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DCK_DRUGLINK
	FOR DIB5_1.MMW_DCK_DRUGLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_AUNIT
	FOR DIB5_1.MMW_DDA_AUNIT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_DOSEFORGPI
	FOR DIB5_1.MMW_DDA_DOSEFORGPI
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_DOSEROUTECOMPATABILITY
	FOR DIB5_1.MMW_DDA_DOSEROUTECOMPATABILITY
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_GPI_DOSE
	FOR DIB5_1.MMW_DDA_GPI_DOSE
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_GPI_DOSE_TEXT
	FOR DIB5_1.MMW_DDA_GPI_DOSE_TEXT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_PATIENT_PROFILE
	FOR DIB5_1.MMW_DDA_PATIENT_PROFILE
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_ROUTE
	FOR DIB5_1.MMW_DDA_ROUTE
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_TEXT
	FOR DIB5_1.MMW_DDA_TEXT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_UNIT
	FOR DIB5_1.MMW_DDA_UNIT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_UNIT_XREF
	FOR DIB5_1.MMW_DDA_UNIT_XREF
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_UNITCONVERSION
	FOR DIB5_1.MMW_DDA_UNITCONVERSION
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DDA_WEIGHT_CAT_UOM
	FOR DIB5_1.MMW_DDA_WEIGHT_CAT_UOM
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DFA_INT
	FOR DIB5_1.MMW_DFA_INT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DFA_TEXT
	FOR DIB5_1.MMW_DFA_TEXT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DI_CLASSLINK
	FOR DIB5_1.MMW_DI_CLASSLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DI_INT
	FOR DIB5_1.MMW_DI_INT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DI_RPIDLINK
	FOR DIB5_1.MMW_DI_RPIDLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DI_TEXT
	FOR DIB5_1.MMW_DI_TEXT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_DISP
	FOR DIB5_1.MMW_DRUG_DISP
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_DISP_LBLR
	FOR DIB5_1.MMW_DRUG_DISP_LBLR
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_DOSEFORM
	FOR DIB5_1.MMW_DRUG_DOSEFORM
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_GPI
	FOR DIB5_1.MMW_DRUG_GPI
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_GPILINK
	FOR DIB5_1.MMW_DRUG_GPILINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_KDC
	FOR DIB5_1.MMW_DRUG_KDC
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_KDCLINK
	FOR DIB5_1.MMW_DRUG_KDCLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_LABELER
	FOR DIB5_1.MMW_DRUG_LABELER
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_NAME
	FOR DIB5_1.MMW_DRUG_NAME
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_PACK
	FOR DIB5_1.MMW_DRUG_PACK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_PACK_MOD
	FOR DIB5_1.MMW_DRUG_PACK_MOD
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_ROUTE
	FOR DIB5_1.MMW_DRUG_ROUTE
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DRUG_ROUTED
	FOR DIB5_1.MMW_DRUG_ROUTED
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DUP_DRUGLINK
	FOR DIB5_1.MMW_DUP_DRUGLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_DUP_TEXT
	FOR DIB5_1.MMW_DUP_TEXT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_IND_COM
	FOR DIB5_1.MMW_IND_COM
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_IND_COTREAT
	FOR DIB5_1.MMW_IND_COTREAT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_IND_DRUGLINK
	FOR DIB5_1.MMW_IND_DRUGLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_IND_RPID
	FOR DIB5_1.MMW_IND_RPID
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_IND_SOURCE
	FOR DIB5_1.MMW_IND_SOURCE
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_LIB_CODEDEF
	FOR DIB5_1.MMW_LIB_CODEDEF
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_LIB_DISCLAIMER
	FOR DIB5_1.MMW_LIB_DISCLAIMER
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_LIB_VERSION
	FOR DIB5_1.MMW_LIB_VERSION
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_MED
	FOR DIB5_1.MMW_MED
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_MED_CIT
	FOR DIB5_1.MMW_MED_CIT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_MED_EXTVOCAB
	FOR DIB5_1.MMW_MED_EXTVOCAB
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_MED_HIER
	FOR DIB5_1.MMW_MED_HIER
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_MED_INTVOCAB
	FOR DIB5_1.MMW_MED_INTVOCAB
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_MED_LINK
	FOR DIB5_1.MMW_MED_LINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_MED_NAME
	FOR DIB5_1.MMW_MED_NAME
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_MED_TEXT
	FOR DIB5_1.MMW_MED_TEXT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_MED_TEXT_CIT
	FOR DIB5_1.MMW_MED_TEXT_CIT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_MONO_CLSNAME
	FOR DIB5_1.MMW_MONO_CLSNAME
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_MONO_TEXT
	FOR DIB5_1.MMW_MONO_TEXT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PAR_CLASS
	FOR DIB5_1.MMW_PAR_CLASS
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PAR_CLASS_MAP
	FOR DIB5_1.MMW_PAR_CLASS_MAP
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PAR_CLASS_OLD
	FOR DIB5_1.MMW_PAR_CLASS_OLD
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PAR_CLASSLINK
	FOR DIB5_1.MMW_PAR_CLASSLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PAR_DRUGLINK
	FOR DIB5_1.MMW_PAR_DRUGLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PAR_INGRLINK
	FOR DIB5_1.MMW_PAR_INGRLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PAR_INT
	FOR DIB5_1.MMW_PAR_INT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PDE_DRUGLINK
	FOR DIB5_1.MMW_PDE_DRUGLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PRCA_COM
	FOR DIB5_1.MMW_PRCA_COM
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PRCA_DRUGLINK
	FOR DIB5_1.MMW_PRCA_DRUGLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PRCA_SPECCOND
	FOR DIB5_1.MMW_PRCA_SPECCOND
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PRCC_COM
	FOR DIB5_1.MMW_PRCC_COM
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PRCC_DRUGLINK
	FOR DIB5_1.MMW_PRCC_DRUGLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PRCC_SPECCOND
	FOR DIB5_1.MMW_PRCC_SPECCOND
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_PRI
	FOR DIB5_1.MMW_PRI
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_ROUTE_ACTCODE
	FOR DIB5_1.MMW_ROUTE_ACTCODE
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_SNOMED_MC_LINK
	FOR DIB5_1.MMW_SNOMED_MC_LINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_WL_DRUGLINK
	FOR DIB5_1.MMW_WL_DRUGLINK
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_WL_TEXT
	FOR DIB5_1.MMW_WL_TEXT
/
CREATE OR REPLACE SYNONYM DIB5_AUX.MMW_WL_VENDCODE
	FOR DIB5_1.MMW_WL_VENDCODE
/
CREATE OR REPLACE SYNONYM DIB5_AUX.PR2AC
	FOR DIB5_1.PR2AC
/
CREATE OR REPLACE SYNONYM DIB5_AUX.PR2ACPC
	FOR DIB5_1.PR2ACPC
/
CREATE OR REPLACE SYNONYM DIB5_AUX.PR2KDCN
	FOR DIB5_1.PR2KDCN
/
CREATE OR REPLACE SYNONYM DIB5_AUX.PR2MAP
	FOR DIB5_1.PR2MAP
/
CREATE OR REPLACE SYNONYM DIB5_AUX.PR2TEXT
	FOR DIB5_1.PR2TEXT
/
