-- FIND THE EXTRA FK
-- Query to see what the 170th FK is

-- Check for any remaining incorrect FKs that should have been dropped
SELECT CONSTRAINT_NAME, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'EPS' 
    AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    AND CONSTRAINT_NAME IN ('PATIENT_FK_CHAIN', 'PRESCRIBER_FK_CHAIN', 'PRESCRIBER_FK_STORE',
                             'RX_TX_DIAGNOSIS_CODES_FK_RX_TX', 'RX_TX_DUR_LIST_FK_RX_TX',
                             'RX_TX_PAYMENT_FK_RX_TX', 'RX_TX_SIG_STRUCTURED_PART_FK_RX_TX')
ORDER BY CONSTRAINT_NAME;
