-- ========================================================================
-- FK FIX SCRIPT: Remove Incorrect FKs + Create Missing FKs
-- Date: 2026-06-25
-- Purpose: Align Azure FKs with Source Database (169 total FKs required)
-- ========================================================================

-- ========================================================================
-- PHASE 1: DROP 7 INCORRECT/EXTRA FKs
-- ========================================================================

PRINT '========== PHASE 1: Dropping Incorrect FKs =========='

-- Drop PATIENT_FK_CHAIN (incorrect naming - should use PATIENT_FK_ESCHAIN only)
ALTER TABLE "EPS"."PATIENT" DROP CONSTRAINT [PATIENT_FK_CHAIN];
PRINT 'Dropped: PATIENT_FK_CHAIN'

-- Drop PRESCRIBER FKs with wrong naming
ALTER TABLE "EPS"."PRESCRIBER" DROP CONSTRAINT [PRESCRIBER_FK_CHAIN];
PRINT 'Dropped: PRESCRIBER_FK_CHAIN'

ALTER TABLE "EPS"."PRESCRIBER" DROP CONSTRAINT [PRESCRIBER_FK_STORE];
PRINT 'Dropped: PRESCRIBER_FK_STORE'

-- Drop RX_TX_DIAGNOSIS_CODES variant (keep FK1 and FK2)
ALTER TABLE "EPS"."RX_TX_DIAGNOSIS_CODES" DROP CONSTRAINT [RX_TX_DIAGNOSIS_CODES_FK_RX_TX];
PRINT 'Dropped: RX_TX_DIAGNOSIS_CODES_FK_RX_TX'

-- Drop RX_TX_DUR_LIST variant (keep FKIDRXTX)
ALTER TABLE "EPS"."RX_TX_DUR_LIST" DROP CONSTRAINT [RX_TX_DUR_LIST_FK_RX_TX];
PRINT 'Dropped: RX_TX_DUR_LIST_FK_RX_TX'

-- Drop RX_TX_PAYMENT variant (keep CHAIN_PAYID, ESCHAIN, ESSTORE)
ALTER TABLE "EPS"."RX_TX_PAYMENT" DROP CONSTRAINT [RX_TX_PAYMENT_FK_RX_TX];
PRINT 'Dropped: RX_TX_PAYMENT_FK_RX_TX'

-- Drop RX_TX_SIG_STRUCTURED_PART variant (use correct naming)
ALTER TABLE "EPS"."RX_TX_SIG_STRUCTURED_PART" DROP CONSTRAINT [RX_TX_SIG_STRUCTURED_PART_FK_RX_TX];
PRINT 'Dropped: RX_TX_SIG_STRUCTURED_PART_FK_RX_TX'

PRINT 'Phase 1 Complete: 7 incorrect FKs dropped'
PRINT ''

-- ========================================================================
-- PHASE 2: CREATE 13 MISSING FKs
-- ========================================================================

PRINT '========== PHASE 2: Creating Missing FKs =========='

-- FK1: PATIENT_AR_AC_FK_PATIENT
ALTER TABLE "EPS"."PATIENT_AR_ACCOUNT" 
ADD CONSTRAINT "PATIENT_AR_AC_FK_PATIENT" 
FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") 
REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");
PRINT 'Created: PATIENT_AR_AC_FK_PATIENT'

-- FK2: PATIENT_CARE_PROVIDER_FK1
ALTER TABLE "EPS"."PATIENT_CARE_PROVIDER" 
ADD CONSTRAINT "PATIENT_CARE_PROVIDER_FK1" 
FOREIGN KEY ("CHAIN_ID") 
REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");
PRINT 'Created: PATIENT_CARE_PROVIDER_FK1'

-- FK3: PATIENT_CARE_PROVIDER_FK2
ALTER TABLE "EPS"."PATIENT_CARE_PROVIDER" 
ADD CONSTRAINT "PATIENT_CARE_PROVIDER_FK2" 
FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") 
REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");
PRINT 'Created: PATIENT_CARE_PROVIDER_FK2'

-- FK4: PATIENT_CC_FK_ESCHAIN (PATIENT_CREDIT_CARD)
ALTER TABLE "EPS"."PATIENT_CREDIT_CARD" 
ADD CONSTRAINT "PATIENT_CC_FK_ESCHAIN" 
FOREIGN KEY ("CHAIN_ID") 
REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");
PRINT 'Created: PATIENT_CC_FK_ESCHAIN'

-- FK5: PATIENT_CC_FK_PATIENT (PATIENT_CREDIT_CARD)
ALTER TABLE "EPS"."PATIENT_CREDIT_CARD" 
ADD CONSTRAINT "PATIENT_CC_FK_PATIENT" 
FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") 
REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");
PRINT 'Created: PATIENT_CC_FK_PATIENT'

-- FK6: PATIENT_DOCUMENT_FK1
ALTER TABLE "EPS"."PATIENT_DOCUMENT" 
ADD CONSTRAINT "PATIENT_DOCUMENT_FK1" 
FOREIGN KEY ("CHAIN_ID") 
REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");
PRINT 'Created: PATIENT_DOCUMENT_FK1'

-- FK7: PATIENT_DOCUMENT_FK2
ALTER TABLE "EPS"."PATIENT_DOCUMENT" 
ADD CONSTRAINT "PATIENT_DOCUMENT_FK2" 
FOREIGN KEY ("CHAIN_ID", "NHIN_ID") 
REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");
PRINT 'Created: PATIENT_DOCUMENT_FK2'

-- FK8: PATIENT_DOCUMENT_FK3
ALTER TABLE "EPS"."PATIENT_DOCUMENT" 
ADD CONSTRAINT "PATIENT_DOCUMENT_FK3" 
FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") 
REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");
PRINT 'Created: PATIENT_DOCUMENT_FK3'

-- FK9: PATIENT_EMERGENCY_CONTACT_FK1
ALTER TABLE "EPS"."PATIENT_EMERGENCY_CONTACT" 
ADD CONSTRAINT "PATIENT_EMERGENCY_CONTACT_FK1" 
FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") 
REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");
PRINT 'Created: PATIENT_EMERGENCY_CONTACT_FK1'

-- FK10: PATIENT_EMERGENCY_CONTACT_FK2
ALTER TABLE "EPS"."PATIENT_EMERGENCY_CONTACT" 
ADD CONSTRAINT "PATIENT_EMERGENCY_CONTACT_FK2" 
FOREIGN KEY ("CHAIN_ID") 
REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");
PRINT 'Created: PATIENT_EMERGENCY_CONTACT_FK2'

-- FK11: RX_TX_SIG_STR_PRT_FK_ESCHAIN (RX_TX_SIG_STRUCTURED_PART)
ALTER TABLE "EPS"."RX_TX_SIG_STRUCTURED_PART" 
ADD CONSTRAINT "RX_TX_SIG_STR_PRT_FK_ESCHAIN" 
FOREIGN KEY ("CHAIN_ID") 
REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");
PRINT 'Created: RX_TX_SIG_STR_PRT_FK_ESCHAIN'

-- FK12: RX_TX_SIG_STR_PRT_FK_RX_TX (RX_TX_SIG_STRUCTURED_PART)
ALTER TABLE "EPS"."RX_TX_SIG_STRUCTURED_PART" 
ADD CONSTRAINT "RX_TX_SIG_STR_PRT_FK_RX_TX" 
FOREIGN KEY ("CHAIN_ID", "ID_RX_TX") 
REFERENCES "EPS"."RX_TX" ("CHAIN_ID", "ID");
PRINT 'Created: RX_TX_SIG_STR_PRT_FK_RX_TX'

-- FK13: SIGNATURE_FK_ESCHAIN
ALTER TABLE "EPS"."SIGNATURE" 
ADD CONSTRAINT "SIGNATURE_FK_ESCHAIN" 
FOREIGN KEY ("CHAIN_ID") 
REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");
PRINT 'Created: SIGNATURE_FK_ESCHAIN'

PRINT 'Phase 2 Complete: 13 missing FKs created'
PRINT ''

-- ========================================================================
-- PHASE 3: VERIFICATION
-- ========================================================================

PRINT '========== PHASE 3: Verification =========='

SELECT 'Total FK Constraints' as Check_Type, COUNT(DISTINCT CONSTRAINT_NAME) as Count
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'EPS' AND CONSTRAINT_TYPE = 'FOREIGN KEY'

UNION ALL

SELECT 'Expected', 169

UNION ALL

SELECT 'Correct (should be 0)', COUNT(*)
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'EPS' 
    AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    AND CONSTRAINT_NAME IN ('PATIENT_FK_CHAIN', 'PRESCRIBER_FK_CHAIN', 'PRESCRIBER_FK_STORE',
                             'RX_TX_DIAGNOSIS_CODES_FK_RX_TX', 'RX_TX_DUR_LIST_FK_RX_TX',
                             'RX_TX_PAYMENT_FK_RX_TX', 'RX_TX_SIG_STRUCTURED_PART_FK_RX_TX')

ORDER BY Check_Type DESC;

PRINT ''
PRINT '========== SCRIPT COMPLETE =========='
PRINT 'Result: All 169 FKs should now be present and correct'
