-- DROP 7 INCORRECT FKs (if they exist)
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='PATIENT' AND CONSTRAINT_NAME='PATIENT_FK_CHAIN') 
  ALTER TABLE "EPS"."PATIENT" DROP CONSTRAINT [PATIENT_FK_CHAIN];

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='PRESCRIBER' AND CONSTRAINT_NAME='PRESCRIBER_FK_CHAIN') 
  ALTER TABLE "EPS"."PRESCRIBER" DROP CONSTRAINT [PRESCRIBER_FK_CHAIN];

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='PRESCRIBER' AND CONSTRAINT_NAME='PRESCRIBER_FK_STORE') 
  ALTER TABLE "EPS"."PRESCRIBER" DROP CONSTRAINT [PRESCRIBER_FK_STORE];

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='RX_TX_DIAGNOSIS_CODES' AND CONSTRAINT_NAME='RX_TX_DIAGNOSIS_CODES_FK_RX_TX') 
  ALTER TABLE "EPS"."RX_TX_DIAGNOSIS_CODES" DROP CONSTRAINT [RX_TX_DIAGNOSIS_CODES_FK_RX_TX];

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='RX_TX_DUR_LIST' AND CONSTRAINT_NAME='RX_TX_DUR_LIST_FK_RX_TX') 
  ALTER TABLE "EPS"."RX_TX_DUR_LIST" DROP CONSTRAINT [RX_TX_DUR_LIST_FK_RX_TX];

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='RX_TX_PAYMENT' AND CONSTRAINT_NAME='RX_TX_PAYMENT_FK_RX_TX') 
  ALTER TABLE "EPS"."RX_TX_PAYMENT" DROP CONSTRAINT [RX_TX_PAYMENT_FK_RX_TX];

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='RX_TX_SIG_STRUCTURED_PART' AND CONSTRAINT_NAME='RX_TX_SIG_STRUCTURED_PART_FK_RX_TX') 
  ALTER TABLE "EPS"."RX_TX_SIG_STRUCTURED_PART" DROP CONSTRAINT [RX_TX_SIG_STRUCTURED_PART_FK_RX_TX];

-- CREATE 13 MISSING FKs
ALTER TABLE "EPS"."PATIENT_AR_ACCOUNT" ADD CONSTRAINT "PATIENT_AR_AC_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");
ALTER TABLE "EPS"."PATIENT_CARE_PROVIDER" ADD CONSTRAINT "PATIENT_CARE_PROVIDER_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");
ALTER TABLE "EPS"."PATIENT_CARE_PROVIDER" ADD CONSTRAINT "PATIENT_CARE_PROVIDER_FK2" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");
ALTER TABLE "EPS"."PATIENT_CREDIT_CARD" ADD CONSTRAINT "PATIENT_CC_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");
ALTER TABLE "EPS"."PATIENT_CREDIT_CARD" ADD CONSTRAINT "PATIENT_CC_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");
ALTER TABLE "EPS"."PATIENT_DOCUMENT" ADD CONSTRAINT "PATIENT_DOCUMENT_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");
ALTER TABLE "EPS"."PATIENT_DOCUMENT" ADD CONSTRAINT "PATIENT_DOCUMENT_FK2" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");
ALTER TABLE "EPS"."PATIENT_DOCUMENT" ADD CONSTRAINT "PATIENT_DOCUMENT_FK3" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");
ALTER TABLE "EPS"."PATIENT_EMERGENCY_CONTACT" ADD CONSTRAINT "PATIENT_EMERGENCY_CONTACT_FK1" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");
ALTER TABLE "EPS"."PATIENT_EMERGENCY_CONTACT" ADD CONSTRAINT "PATIENT_EMERGENCY_CONTACT_FK2" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");
ALTER TABLE "EPS"."RX_TX_SIG_STRUCTURED_PART" ADD CONSTRAINT "RX_TX_SIG_STR_PRT_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");
ALTER TABLE "EPS"."RX_TX_SIG_STRUCTURED_PART" ADD CONSTRAINT "RX_TX_SIG_STR_PRT_FK_RX_TX" FOREIGN KEY ("CHAIN_ID", "ID_RX_TX") REFERENCES "EPS"."RX_TX" ("CHAIN_ID", "ID");
ALTER TABLE "EPS"."SIGNATURE" ADD CONSTRAINT "SIGNATURE_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- VERIFY
SELECT COUNT(DISTINCT CONSTRAINT_NAME) as Total_FKs FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'EPS' AND CONSTRAINT_TYPE = 'FOREIGN KEY';
