-- DEFAULT CONSTRAINTS
-- Converted from Oracle BEFORE INSERT triggers
-- ========================================================

ALTER TABLE [SBMO].[ADJUSTMENT_GROUP]
ADD CONSTRAINT DF_ADJUSTMENT_GROUP_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[AUDIT_LOG]
ADD CONSTRAINT DF_AUDIT_LOG_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[CHARGE_PAYMENT_INFO]
ADD CONSTRAINT DF_CHARGE_PAYMENT_INFO_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[DRUG_ORDERS]
ADD CONSTRAINT DF_DRUG_ORDERS_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT DF_INVENTORY_AUDIT_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[MESSAGE_LOG]
ADD CONSTRAINT DF_MESSAGE_LOG_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[ORDERS]
ADD CONSTRAINT DF_ORDERS_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[PURCHASE_ORDER_GROUP]
ADD CONSTRAINT DF_PURCHASE_ORDER_GROUP_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[PURCHASE_ORDER]
ADD CONSTRAINT DF_PURCHASE_ORDER_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT DF_RETURN_AND_ADJUSTMENT_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT DF_RX_CORES_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RX_DETAILS]
ADD CONSTRAINT DF_RX_DETAILS_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[rx_digital_documents]
ADD CONSTRAINT DF_rx_digital_documents_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[rx_documents]
ADD CONSTRAINT DF_rx_documents_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[rx_image_data]
ADD CONSTRAINT DF_rx_image_data_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RX_LOTS]
ADD CONSTRAINT DF_RX_LOTS_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RX_PATSTORES]
ADD CONSTRAINT DF_RX_PATSTORES_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RX_PRINT_CHR]
ADD CONSTRAINT DF_RX_PRINT_CHR_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RX_PRINT_INFO]
ADD CONSTRAINT DF_RX_PRINT_INFO_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RX_REQUEST_ERROR]
ADD CONSTRAINT DF_RX_REQUEST_ERROR_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RX_SHIPPING_PACKAGES]
ADD CONSTRAINT DF_RX_SHIPPING_PACKAGES_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RX_TP_INFO]
ADD CONSTRAINT DF_RX_TP_INFO_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RX_VIAL_INFOS]
ADD CONSTRAINT DF_RX_VIAL_INFOS_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[RX_WARNING_LABELS]
ADD CONSTRAINT DF_RX_WARNING_LABELS_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[SYSTEM_MESSAGES]
ADD CONSTRAINT DF_SYSTEM_MESSAGES_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

ALTER TABLE [SBMO].[USER_AUDIT_LOG]
ADD CONSTRAINT DF_USER_AUDIT_LOG_CREATED_DATE
DEFAULT SYSUTCDATETIME() FOR CREATED_DATE;

