CREATE OR REPLACE SYNONYM WL_EPHARMACY.APP_INFO
	FOR EPHARM.APP_INFO
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.ATTR_DESC
	FOR EPHARM.ATTR_DESC
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.CHAIN_RULE_GROUP
	FOR EPHARM.CHAIN_RULE_GROUP
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.CREDIT_CARD
	FOR EPHARM.CREDIT_CARD
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.CREDIT_CARD_DESC
	FOR EPHARM.CREDIT_CARD_DESC
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.CUSTOMER
	FOR EPHARM.CUSTOMER
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.CUSTOMER_AUDIT
	FOR EPHARM.CUSTOMER_AUDIT
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.CUSTOMER_ECOMMERCE_SERVICE
	FOR EPHARM.CUSTOMER_ECOMMERCE_SERVICE
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.CUSTOMER_EMAIL_SETTINGS
	FOR EPHARM.CUSTOMER_EMAIL_SETTINGS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.CUSTOMER_PIN_BATCH
	FOR EPHARM.CUSTOMER_PIN_BATCH
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.CUSTOMER_REFILL_PRINTING
	FOR EPHARM.CUSTOMER_REFILL_PRINTING
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.EVENT_QUESTION_LOG
	FOR EPHARM.EVENT_QUESTION_LOG
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.EVENT_RX_BILLING_LOG
	FOR EPHARM.EVENT_RX_BILLING_LOG
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.FAX_JOB
	FOR EPHARM.FAX_JOB
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.FLOW_ACTION
	FOR EPHARM.FLOW_ACTION
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.FLOW_ACTION_TYPE
	FOR EPHARM.FLOW_ACTION_TYPE
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.FLOW_CONTROL
	FOR EPHARM.FLOW_CONTROL
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.ID_GEN
	FOR EPHARM.ID_GEN
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.MAIL_ORDER_DELIVERY
	FOR EPHARM.MAIL_ORDER_DELIVERY
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.MAIL_ORDER_DELIVERY_DESC
	FOR EPHARM.MAIL_ORDER_DELIVERY_DESC
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.MASTER_SEQ
	FOR EPHARM.MASTER_SEQ
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.MEMBER_ACCOUNT
	FOR EPHARM.MEMBER_ACCOUNT
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.MEMBER_EXTERNAL_LINK
	FOR EPHARM.MEMBER_EXTERNAL_LINK
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.MEMBER_NOTIFY
	FOR EPHARM.MEMBER_NOTIFY
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.MEMBER_PIN_BATCH
	FOR EPHARM.MEMBER_PIN_BATCH
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.MEMBER_PROFILE
	FOR EPHARM.MEMBER_PROFILE
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.MEMBER_RX
	FOR EPHARM.MEMBER_RX
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.MONITOR_TIMES
	FOR EPHARM.MONITOR_TIMES
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.NOTIFICATION_TYPE
	FOR EPHARM.NOTIFICATION_TYPE
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.NOTIFICATIONS
	FOR EPHARM.NOTIFICATIONS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.OPEN_CLOSE_TIME
	FOR EPHARM.OPEN_CLOSE_TIME
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PARENT_CHILD
	FOR EPHARM.PARENT_CHILD
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_CONFIG
	FOR EPHARM.PDX_SCHEMA_CONFIG
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_MAPPING
	FOR EPHARM.PDX_SCHEMA_MAPPING
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_PRIV_DEFAULT
	FOR EPHARM.PDX_SCHEMA_PRIV_DEFAULT
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_PRIV_EXCEPTION
	FOR EPHARM.PDX_SCHEMA_PRIV_EXCEPTION
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_PROCESS_HISTORY
	FOR EPHARM.PDX_SCHEMA_PROCESS_HISTORY
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_TASK_ERROR_LOG
	FOR EPHARM.PDX_SCHEMA_TASK_ERROR_LOG
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_TASK_HISTORY
	FOR EPHARM.PDX_SCHEMA_TASK_HISTORY
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG
	FOR EPHARM.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPD_PKGCALL_HIST
	FOR EPHARM.PDX_SCHEMA_UPD_PKGCALL_HIST
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPDATER_MANIFEST
	FOR EPHARM.PDX_SCHEMA_UPDATER_MANIFEST
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPDATER_SQL
	FOR EPHARM.PDX_SCHEMA_UPDATER_SQL
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_VERSION_ERROR_LOG
	FOR EPHARM.PDX_SCHEMA_VERSION_ERROR_LOG
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PDX_SCHEMA_VERSION_HISTORY
	FOR EPHARM.PDX_SCHEMA_VERSION_HISTORY
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PIN_BATCH_LOG
	FOR EPHARM.PIN_BATCH_LOG
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PKG_PDX_SCHEMA_UPDATER
	FOR EPHARM.PKG_PDX_SCHEMA_UPDATER
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.PKG_PDX_SCHEMA_UPDATER_RPT
	FOR EPHARM.PKG_PDX_SCHEMA_UPDATER_RPT
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.QRTZ_BLOB_TRIGGERS
	FOR EPHARM.QRTZ_BLOB_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.QRTZ_CALENDARS
	FOR EPHARM.QRTZ_CALENDARS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.QRTZ_CRON_TRIGGERS
	FOR EPHARM.QRTZ_CRON_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.QRTZ_FIRED_TRIGGERS
	FOR EPHARM.QRTZ_FIRED_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.QRTZ_JOB_DETAILS
	FOR EPHARM.QRTZ_JOB_DETAILS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.QRTZ_LOCKS
	FOR EPHARM.QRTZ_LOCKS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.QRTZ_PAUSED_TRIGGER_GRPS
	FOR EPHARM.QRTZ_PAUSED_TRIGGER_GRPS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.QRTZ_SCHEDULER_STATE
	FOR EPHARM.QRTZ_SCHEDULER_STATE
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.QRTZ_SIMPLE_TRIGGERS
	FOR EPHARM.QRTZ_SIMPLE_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.QRTZ_SIMPROP_TRIGGERS
	FOR EPHARM.QRTZ_SIMPROP_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.QRTZ_TRIGGERS
	FOR EPHARM.QRTZ_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.SCHEMA_UPDATER_MANIFEST
	FOR EPHARM.SCHEMA_UPDATER_MANIFEST
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.SCHEMA_UPDATER_SQL
	FOR EPHARM.SCHEMA_UPDATER_SQL
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.SERVICE_MODIFY
	FOR EPHARM.SERVICE_MODIFY
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.SHR_DAY_OF_WEEK
	FOR EPHARM.SHR_DAY_OF_WEEK
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.SHR_GROUP
	FOR EPHARM.SHR_GROUP
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.SHR_NTH_WEEKDAY_OF_MONTH
	FOR EPHARM.SHR_NTH_WEEKDAY_OF_MONTH
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.SHR_SPECIFIC_DATE
	FOR EPHARM.SHR_SPECIFIC_DATE
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.STATE_MAJORITY_AGE
	FOR EPHARM.STATE_MAJORITY_AGE
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY."STORE"
	FOR EPHARM."STORE"
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.STORE_ATTR
	FOR EPHARM.STORE_ATTR
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.STORE_AUDIT
	FOR EPHARM.STORE_AUDIT
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.STORE_ECOMMERCE_SERVICE
	FOR EPHARM.STORE_ECOMMERCE_SERVICE
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.STORE_HOUR_RULE
	FOR EPHARM.STORE_HOUR_RULE
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.STORE_VERSION
	FOR EPHARM.STORE_VERSION
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.SYS_MSG
	FOR EPHARM.SYS_MSG
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.TERMS_OF_USE
	FOR EPHARM.TERMS_OF_USE
/
CREATE OR REPLACE SYNONYM WL_EPHARMACY.USAGE
	FOR EPHARM.USAGE
/
