-- TRIGGER: [EPS].[AUDIT_ACCESS_LOG_BIUR] - Oracle to Azure SQL conversion  
-- Converted: BEFORE INSERT OR UPDATE trigger that sets timestamp

IF OBJECT_ID('[EPS].[AUDIT_ACCESS_LOG_BIUR]', 'TR') IS NOT NULL
    DROP TRIGGER [EPS].[AUDIT_ACCESS_LOG_BIUR];
GO

CREATE TRIGGER [EPS].[AUDIT_ACCESS_LOG_BIUR]
ON [EPS].[AUDIT_ACCESS_LOG]
INSTEAD OF INSERT, UPDATE
AS
BEGIN
    INSERT INTO [EPS].[AUDIT_ACCESS_LOG] (
        SELECT * FROM inserted UNION ALL
        SELECT * FROM deleted
    );
    
    UPDATE [EPS].[AUDIT_ACCESS_LOG]
    SET [AUDIT_TIMESTAMP] = SYSDATETIME()
    WHERE [AUDIT_TIMESTAMP] IS NULL;
END;
GO
