INSERT INTO ALL_TABLES (DDL) VALUES
	 (TO_CLOB('
  CREATE TABLE "ARS"."ARS_PROPERTIES" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"KEY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "ARS_PROPERTIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ARS_PROP_UQ_KEY" UNIQUE ("KEY")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."BILLABLE_PRODUCT" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"MULTIVENDOR" VARCHAR2(1) NOT NULL ENABLE, 
	"VENDOR_ELIGIBLE_SELECTION" VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT "BILLABLE_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BILLABLE_PRODUCT_UK1" UNIQUE ("NAME")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."BILLABLE_VENDOR" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VENDOR_SHORT_NAME" VARCHAR2(10) NOT NULL ENABLE, 
	"VENDOR_NAME" VARCHAR2(60), 
	"VENDOR_NPI" VARCHAR2(15), 
	"VENDOR_NCPDP" VARCHAR2(255), 
	"VENDOR_NHIN" VARCHAR2(255), 
	"DELETED_DATE" TIMESTAMP (6), 
	"DISABLED_DATE" TIMESTAMP (6), 
	"VERSION" TIMESTAMP (6), 
	"CREATE_DATE" TIMESTAMP (6), 
	"SINGLE_SIGN_ON_TYPE" VARCHAR2(25), 
	 CONSTRAINT "BILLABLE_VENDOR_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BILLABLE_VENDOR_UK1" UNIQUE ("VENDOR_SHORT_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BILLABLE_VENDOR_UK2" UNIQUE ("VENDOR_NPI")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BILLABLE_VENDOR_UK3" UNIQUE ("VENDOR_NCPDP")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BILLABLE_VENDOR_UK4" UNIQUE ("VENDOR_NHIN")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."BILLABLE_VENDOR_PRODUCT" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BILLABLE_VENDOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BILLABLE_PRODUCT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	 CONSTRAINT "BILLABLE_VENDOR_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BILLABLE_VENDOR_PRODUCT_UK1" UNIQUE ("BILLABLE_VENDOR_ID", "BILLABLE_PRODUCT_ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "BILLABLE_VENDOR_PRODUCT_FK1" FOREIGN KEY ("BILLABLE_VENDOR_ID")
	  REFERENCES "ARS"."BILLABLE_VENDOR" ("ID") ENABLE, 
	 CONSTRAINT "BILLABLE_VENDOR_PRODUCT_FK2" FOREIGN KEY ("BILLABLE_PRODUCT_ID")
	  REFERENCES "ARS"."BILLABLE_PRODUCT" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."BILLABLE_VEND_PROD_STORE" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BILLABLE_VENDOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BILLABLE_PRODUCT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STORE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "BILLABLE_VEND_PROD_STORE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BILLABLE_VEND_PROD_STORE_UK1" UNIQUE ("BILLABLE_VENDOR_ID", "BILLABLE_PRODUCT_ID", "STORE_ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "BILLABLE_VEND_PROD_STORE_FK2" FOREIGN KEY ("BILLABLE_VENDOR_ID", "BILLABLE_PRODUCT_ID")
	  REFERENCES "ARS"."BILLABLE_VENDOR_PRODUCT" ("BILLABLE_VENDOR_ID", "BILLABLE_PRODUCT_ID") ENABLE, 
	 CONSTRAINT "BILLABLE_VEND_PROD_STORE_FK1" FOREIGN KEY ("STORE_ID")
	  REFERENCES "ARS"."STORES" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."BILL_VEND_PROD_STORE_AUDIT" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STORE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BILLABLE_PRODUCT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BILLABLE_VENDOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACTION" VARCHAR2(1) NOT NULL ENABLE, 
	"CHANGED_BY_USER" VARCHAR2(255) NOT NULL ENABLE, 
	"TIME_STAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "BILL_VEND_PROD_STORE_AUDIT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."CHAINS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VERSION" TIMESTAMP (6), 
	"LAST_UPDATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"NHINID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CHAIN_PASSWORD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PARENT_ID" NUMBER(19,0), 
	"HQ_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"DEACTIVATED_DATE" TIMESTAMP (6), 
	"EMPLOYER_ID_NUMBER" VARCHAR2(9), 
	"GLOBAL_STANDARD" VARCHAR2(1) NOT NULL ENABLE, 
	"PDX_GATEWAY_ROUTING_URL" VARCHAR2(255), 
	 CONSTRAINT "CHAINS_UQ_NHINID" UNIQUE ("NHINID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHAINS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHAINS_UQ_HQ_ID" UNIQUE ("HQ_ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS, 
	 SUPPLEMENTAL LOG DATA (UNIQUE INDEX) COLUMNS, 
	 SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "CHAINS_FK_CHAI_PARE" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "ARS"."CHAINS" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."CHAIN_PRODUCT" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CHAINS_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PRODUCTS_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "CHAIN_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHAIN_PRODUCT_UK1" UNIQUE ("CHAINS_ID", "PRODUCTS_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHAIN_PRODUCT_FK1" FOREIGN KEY ("CHAINS_ID")
	  REFERENCES "ARS"."CHAINS" ("ID") ENABLE, 
	 CONSTRAINT "CHAIN_PRODUCT_FK2" FOREIGN KEY ("PRODUCTS_ID")
	  REFERENCES "ARS"."PRODUCTS" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."CHAIN_PRODUCT_AUDIT" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CHAINS_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PRODUCTS_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACTION" VARCHAR2(1) NOT NULL ENABLE, 
	"CHANGED_BY_USER" VARCHAR2(255) NOT NULL ENABLE, 
	"TIME_STAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "CHAIN_PRODUCT_AUDIT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHAIN_PRODUCT_AUDIT_FK1" FOREIGN KEY ("CHAINS_ID")
	  REFERENCES "ARS"."CHAINS" ("ID") ENABLE, 
	 CONSTRAINT "CHAIN_PRODUCT_AUDIT_FK2" FOREIGN KEY ("PRODUCTS_ID")
	  REFERENCES "ARS"."PRODUCTS" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."COMM_RESTRICTIONS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VENDOR_ID" NUMBER(19,0), 
	"PRODUCT_ID" NUMBER(19,0), 
	"CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "COMM_RESTRICTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "COMM_RESTRICTIONS_FK1" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "ARS"."VENDOR" ("ID") ENABLE, 
	 CONSTRAINT "COMM_RESTRICTIONS_FK2" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "ARS"."PRODUCTS" ("ID") ENABLE
   ) '));
INSERT INTO ALL_TABLES (DDL) VALUES
	 (TO_CLOB('
  CREATE TABLE "ARS"."CONTACT_INFO" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"ADDRESS_LINE_2" VARCHAR2(30 CHAR), 
	"CITY" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"COUNTY" VARCHAR2(30 CHAR), 
	"FAX_NUMBER" VARCHAR2(10 CHAR), 
	"STATE" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"VERSION" TIMESTAMP (6), 
	"VOICE_NUMBER" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"ZIP" VARCHAR2(9 CHAR) NOT NULL ENABLE, 
	"EMAIL_ADDRESS" VARCHAR2(60), 
	 CONSTRAINT "CONTACT_INFO_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."DIVISIONS" 
   (	"ID" NUMBER(38,0), 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"CHAIN_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"DEACTIVATED_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "DIVISIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DIVISIONS_UK1" UNIQUE ("CHAIN_ID", "NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DIVISIONS_FK1" FOREIGN KEY ("CHAIN_ID")
	  REFERENCES "ARS"."CHAINS" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."INTERFACES" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(22) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(22) NOT NULL ENABLE, 
	"STORE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PATH" VARCHAR2(255), 
	"PROTOCOL" VARCHAR2(10), 
	"PORT" VARCHAR2(16), 
	 CONSTRAINT "INTERFACES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INTERFACES_UK1" UNIQUE ("NAME", "STORE_ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "INTERFACES_FK1" FOREIGN KEY ("STORE_ID")
	  REFERENCES "ARS"."STORES" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."INTERFACE_VERSION_MAP" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"STORE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"SERVICE_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(22) NOT NULL ENABLE, 
	"PATH" VARCHAR2(255) NOT NULL ENABLE, 
	"PROTOCOL" VARCHAR2(10) NOT NULL ENABLE, 
	"PORT" VARCHAR2(16) NOT NULL ENABLE, 
	 CONSTRAINT "INTERFACE_VERSION_MAP_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INTERFACE_VERSION_MAP_UK1" UNIQUE ("STORE_ID", "SERVICE_NAME")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "INTERFACE_VERSION_MAP_FK1" FOREIGN KEY ("STORE_ID")
	  REFERENCES "ARS"."STORES" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_DBA_APPLIED" 
   (	"TASK_NAME" VARCHAR2(25), 
	"ACTION_CODE" VARCHAR2(25), 
	"ACTIVITY_DATE" TIMESTAMP (6), 
	"ACTIVITY_USER" VARCHAR2(30), 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_CONFIG" 
   (	"KEY" VARCHAR2(256) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(1000) NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_CONFIG_PK" PRIMARY KEY ("KEY")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_FILE_HASH" 
   (	"FILE_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"FILE_SOURCE" VARCHAR2(1) NOT NULL ENABLE, 
	"FILE_HASH" VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_FILE_HASH_PK" PRIMARY KEY ("FILE_NAME", "FILE_SOURCE")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_FILE_TASKVER" 
   (	"FILE_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"TASK_VERSION" VARCHAR2(255) NOT NULL ENABLE, 
	"FILE_TYPE" VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_FILE_TASKVER_PK" PRIMARY KEY ("FILE_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_FILE_TASKVER_UK1" UNIQUE ("TASK_VERSION")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_MAPPING" 
   (	"MAPPING_TYPE" VARCHAR2(19) NOT NULL ENABLE, 
	"SEARCH" VARCHAR2(40) NOT NULL ENABLE, 
	"REPLACE" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_MAPPING_PK" PRIMARY KEY ("SEARCH")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_PRIV_DEFAULT" 
   (	"OBJECT_TYPE" VARCHAR2(19) NOT NULL ENABLE, 
	"PRIVILEGE" VARCHAR2(40) NOT NULL ENABLE, 
	"GRANTEE" VARCHAR2(30) NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(1), 
	 CONSTRAINT "PDX_SCHEMA_PRIV_DEFAULT_PK" PRIMARY KEY ("GRANTEE", "OBJECT_TYPE", "PRIVILEGE")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) '));
INSERT INTO ALL_TABLES (DDL) VALUES
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_PRIV_EXCEPTION" 
   (	"OBJECT_TYPE" VARCHAR2(19) NOT NULL ENABLE, 
	"OBJECT_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PRIVILEGE" VARCHAR2(40) NOT NULL ENABLE, 
	"GRANTEE" VARCHAR2(30) NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(1), 
	 CONSTRAINT "PDX_SCHEMA_PRIV_EXCEPTION_PK" PRIMARY KEY ("GRANTEE", "OBJECT_TYPE", "OBJECT_NAME", "PRIVILEGE")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_PROCESS_HISTORY" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PDX_SCHEMA_UPD_PKGCALL_HIST_ID" NUMBER(38,0), 
	"PDX_SCHEMA_VERSION_HISTORY_ID" NUMBER(38,0), 
	"PROCESS" VARCHAR2(50), 
	"START_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	 CONSTRAINT "PDX_SCHEMA_PROCESS_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_PROCESS_HISTORY_UK1" UNIQUE ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID", "PDX_SCHEMA_VERSION_HISTORY_ID", "PROCESS")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PDX_SCHEMA_PROCESS_HISTORY_FK1" FOREIGN KEY ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID")
	  REFERENCES "ARS"."PDX_SCHEMA_UPD_PKGCALL_HIST" ("ID") ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_PROCESS_HISTORY_FK2" FOREIGN KEY ("PDX_SCHEMA_VERSION_HISTORY_ID")
	  REFERENCES "ARS"."PDX_SCHEMA_VERSION_HISTORY" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_TASKVER_META" 
   (	"TASK_VERSION" VARCHAR2(255) NOT NULL ENABLE, 
	"TASK_SOURCE" VARCHAR2(1) NOT NULL ENABLE, 
	"META_TAG" VARCHAR2(20) NOT NULL ENABLE, 
	"TASK_VERSION_VALUE" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_TASKVER_META_PK" PRIMARY KEY ("TASK_VERSION", "TASK_SOURCE", "META_TAG", "TASK_VERSION_VALUE")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_TASK_ERROR_LOG" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(200), 
	"SQL_ERROR_CODE" VARCHAR2(20), 
	"SQL_ERROR_MESSAGE" VARCHAR2(4000), 
	"SQL_TEXT" CLOB, 
	"STATEMENT_INDEX" NUMBER(38,0), 
	 CONSTRAINT "PDX_SCHEMA_TASK_ERROR_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PDX_SCHEMA_TASK_ERROR_LOG_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ARS"."PDX_SCHEMA_TASK_HISTORY" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_TASK_HISTORY" 
   (	"ID" NUMBER(38,0), 
	"FILE_NAME" VARCHAR2(255), 
	"PDX_SCHEMA_UPD_PKGCALL_HIST_ID" NUMBER(38,0), 
	"PDX_SCHEMA_VERSION_HISTORY_ID" NUMBER(38,0), 
	"TASK_TYPE" VARCHAR2(20), 
	"ACTION_CODE" VARCHAR2(2), 
	"STATUS_CODE" VARCHAR2(1), 
	"START_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	 CONSTRAINT "PDX_SCHEMA_TASK_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PDX_SCHEMA_TASK_HISTORY_FK1" FOREIGN KEY ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID")
	  REFERENCES "ARS"."PDX_SCHEMA_UPD_PKGCALL_HIST" ("ID") ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_TASK_HISTORY_FK2" FOREIGN KEY ("PDX_SCHEMA_VERSION_HISTORY_ID")
	  REFERENCES "ARS"."PDX_SCHEMA_VERSION_HISTORY" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_UPDATER_MANIFEST" 
   (	"VERSION" VARCHAR2(20) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"APPLY_ORDER" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_UPDATER_MANIFEST_PK" PRIMARY KEY ("VERSION")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_UPDATER_MANIFST_UK1" UNIQUE ("FILE_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_UPDATER_MANIFST_UK2" UNIQUE ("APPLY_ORDER")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_UPDATER_SQL" 
   (	"FILE_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(20), 
	"ACTION_CODE" VARCHAR2(1), 
	"ACTION_DATE" TIMESTAMP (6), 
	"STATUS_CODE" VARCHAR2(1), 
	"STATEMENT_INDEX" NUMBER(38,0), 
	"SQL" CLOB NOT NULL ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_UPDATER_SQL_PK" PRIMARY KEY ("FILE_NAME")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_UPD_HELPER_DEBUG_D" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PDX_SCHEMA_UPD_HLPR_DBG_H_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"START_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	"END_TIMESTAMP" TIMESTAMP (6), 
	"MESSAGE" VARCHAR2(1000), 
	"SQL_ERROR" CLOB, 
	"SQL" CLOB, 
	 CONSTRAINT "PDX_SCHEMA_UPD_HLPR_DBG_D_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PDX_SCHEMA_UPD_HLPR_DBG_D_FK1" FOREIGN KEY ("PDX_SCHEMA_UPD_HLPR_DBG_H_ID")
	  REFERENCES "ARS"."PDX_SCHEMA_UPD_HELPER_DEBUG_H" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_UPD_HELPER_DEBUG_H" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROC" VARCHAR2(30) NOT NULL ENABLE, 
	"PARMS" VARCHAR2(4000), 
	"DEBUG_TIMESTAMP" TIMESTAMP (6), 
	"SQL_ERROR" CLOB, 
	 CONSTRAINT "PDX_SCHEMA_UPD_HLPR_DBG_H_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_UPD_PKGCALL_ERR_LOG" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(200), 
	"SQL_ERROR_CODE" VARCHAR2(20), 
	"SQL_ERROR_MESSAGE" VARCHAR2(4000), 
	 CONSTRAINT "PDX_SCHEMA_UPD_PKGCALL_ELOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PDX_SCHEMA_UPD_PKGCALL_ELG_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ARS"."PDX_SCHEMA_UPD_PKGCALL_HIST" ("ID") ENABLE
   ) '));
INSERT INTO ALL_TABLES (DDL) VALUES
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_UPD_PKGCALL_HIST" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TARGET_VERSION" VARCHAR2(20), 
	"STATUS_CODE" VARCHAR2(1), 
	"RETURN_CODE" NUMBER(2,0), 
	"START_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	 CONSTRAINT "PDX_SCHEMA_UPD_PKGCALL_HIST_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_VERSION_ERROR_LOG" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(200), 
	"SQL_ERROR_CODE" VARCHAR2(20), 
	"SQL_ERROR_MESSAGE" VARCHAR2(4000), 
	 CONSTRAINT "PDX_SCHEMA_VERSION_ERR_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PDX_SCHEMA_VERSION_ERR_LOG_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ARS"."PDX_SCHEMA_VERSION_HISTORY" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PDX_SCHEMA_VERSION_HISTORY" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PDX_SCHEMA_UPD_PKGCALL_HIST_ID" NUMBER(38,0), 
	"CURRENT_VERSION" VARCHAR2(20), 
	"TARGET_VERSION" VARCHAR2(20), 
	"STATUS_CODE" VARCHAR2(1), 
	"START_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	 CONSTRAINT "PDX_SCHEMA_VERSION_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PDX_SCHEMA_VERSION_HISTORY_FK1" FOREIGN KEY ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID")
	  REFERENCES "ARS"."PDX_SCHEMA_UPD_PKGCALL_HIST" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PRODUCTS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"HOST" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PATH" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PORT" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CONNECT_STRING" VARCHAR2(255 CHAR), 
	"MODULE" VARCHAR2(255 CHAR), 
	"MULTIVENDOR" VARCHAR2(1) NOT NULL ENABLE, 
	"VENDOR_ELIGIBLE_SELECTION" VARCHAR2(1) NOT NULL ENABLE, 
	"CHAIN_ELIGIBLE_SELECTION" VARCHAR2(1), 
	 CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PRODUCTS_UQ_NAME" UNIQUE ("NAME")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."PUSH_UPDATES" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"URL" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MESSAGE_VERSION" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PUSH_UPDATES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."RXCOM_CA_CERT" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CERTIFICATE" CLOB NOT NULL ENABLE, 
	"CRL" BLOB, 
	"PASS_PHRASE" CLOB NOT NULL ENABLE, 
	"PRIVATE_KEY" CLOB NOT NULL ENABLE, 
	"VALID_FROM" TIMESTAMP (6) NOT NULL ENABLE, 
	"VALID_TO" TIMESTAMP (6) NOT NULL ENABLE, 
	"KEY_NAME" VARCHAR2(10), 
	 CONSTRAINT "RXCOM_CA_CERT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."RXCOM_CERTIFICATES" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CERTIFICATE" CLOB NOT NULL ENABLE, 
	"PASS_PHRASE" CLOB, 
	"PRIVATE_KEY" CLOB, 
	"REVOCATION_DATE" TIMESTAMP (6), 
	"SERIAL_NUMBER" NUMBER(19,2) NOT NULL ENABLE, 
	"VALID_FROM" TIMESTAMP (6) NOT NULL ENABLE, 
	"VALID_TO" TIMESTAMP (6) NOT NULL ENABLE, 
	"SHA1_THUMBPRINT" VARCHAR2(40), 
	"STORE_ID" NUMBER(22,0), 
	"CERT_TYPE" VARCHAR2(1), 
	 CONSTRAINT "RXCOM_CERTIFICATES_UK1" UNIQUE ("SHA1_THUMBPRINT")
  USING INDEX  ENABLE, 
	 CONSTRAINT "RXCOM_CERTIFICATES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "RXCOM_CERTIFICATES_FK1" FOREIGN KEY ("STORE_ID")
	  REFERENCES "ARS"."STORES" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."RXCOM_CERT_REMV_AFTER_20150201" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CERTIFICATE" CLOB NOT NULL ENABLE, 
	"PASS_PHRASE" CLOB, 
	"PRIVATE_KEY" CLOB, 
	"REVOCATION_DATE" TIMESTAMP (6), 
	"SERIAL_NUMBER" NUMBER(19,2) NOT NULL ENABLE, 
	"VALID_FROM" TIMESTAMP (6) NOT NULL ENABLE, 
	"VALID_TO" TIMESTAMP (6) NOT NULL ENABLE, 
	"SHA1_THUMBPRINT" VARCHAR2(40), 
	"STORE_ID" NUMBER(22,0), 
	"CERT_TYPE" VARCHAR2(1), 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."SCHEMA_UPDATER_MANIFEST" 
   (	"FILE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(20) NOT NULL ENABLE, 
	"APPLY_ORDER" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "SCHEMA_UPDATER_MANIFEST_PK" PRIMARY KEY ("FILE_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SCHEMA_UPDATER_MANIFEST_UK1" UNIQUE ("VERSION")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SCHEMA_UPDATER_MANIFST_UK2" UNIQUE ("APPLY_ORDER")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."SCHEMA_UPDATER_SQL" 
   (	"FILE_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"CHECKSUM" VARCHAR2(64) NOT NULL ENABLE, 
	"SQL" CLOB NOT NULL ENABLE, 
	 CONSTRAINT "SCHEMA_UPDATER_SQL_PK" PRIMARY KEY ("FILE_NAME")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) '));
INSERT INTO ALL_TABLES (DDL) VALUES
	 (TO_CLOB('
  CREATE TABLE "ARS"."STORES" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VERSION" TIMESTAMP (6), 
	"DC_NUMBER" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"LAST_UPDATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"NAME" VARCHAR2(60) NOT NULL ENABLE, 
	"NCPDP" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"NHINID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"REG_STATUS" VARCHAR2(16 CHAR) NOT NULL ENABLE, 
	"REGISTRATION_DATE" TIMESTAMP (6), 
	"OBS_CERT_ID" NUMBER(19,0), 
	"CHAIN_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STORE_NUMBER" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"DEACTIVATED_DATE" TIMESTAMP (6), 
	"LICENSED_DATE" TIMESTAMP (6), 
	"OBS_SSL_CERT_ID" NUMBER(19,0), 
	"NPI" VARCHAR2(15), 
	"PRIOR_AUTH_IDENTIFIER" VARCHAR2(30), 
	"CLIENT_VERSION" VARCHAR2(25), 
	"CLIENT_TYPE" VARCHAR2(8), 
	"CLIENT_ORACLE_VERSION" VARCHAR2(22), 
	"WORKFLOW_ENABLED" VARCHAR2(1), 
	"OS_TYPE" VARCHAR2(22), 
	"OS_VERSION" VARCHAR2(30), 
	"IMM_FACILITY_IDENT" VARCHAR2(20), 
	"IMM_ORGANIZATION_IDENT" VARCHAR2(20), 
	"JAVA_VERSION" VARCHAR2(22), 
	"EFFECTIVE_DATE" TIMESTAMP (6), 
	"SYSTEM_TYPE" VARCHAR2(8), 
	"SYSTEM_CATEGORY" VARCHAR2(8), 
	"CERTIFICATE_ALGORITHM" VARCHAR2(30), 
	"HOST_NAME" VARCHAR2(128), 
	"TIME_ZONE" VARCHAR2(40), 
	"VTRCKS_PIN" VARCHAR2(9), 
	"DIVISIONS_ID" NUMBER(38,0), 
	"CLIENT_GS1_GLN" VARCHAR2(15), 
	"LONGITUDE" NUMBER(10,6), 
	"LATITUDE" NUMBER(10,6), 
	 CONSTRAINT "STORES_UQ_NHINID" UNIQUE ("NHINID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "STORES_UQ_NPI" UNIQUE ("NPI")
  USING INDEX  ENABLE, 
	 CONSTRAINT "STORES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "STORES_UQ_NCPDP" UNIQUE ("NCPDP")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS, 
	 SUPPLEMENTAL LOG DATA (UNIQUE INDEX) COLUMNS, 
	 SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "STORES_FK_CHAI_CHAI" FOREIGN KEY ("CHAIN_ID")
	  REFERENCES "ARS"."CHAINS" ("ID") ENABLE, 
	 CONSTRAINT "STORES_FK1" FOREIGN KEY ("DIVISIONS_ID")
	  REFERENCES "ARS".')||TO_CLOB('"DIVISIONS" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."STORE_HOURS" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"STORE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(1) NOT NULL ENABLE, 
	"DAY" VARCHAR2(9) NOT NULL ENABLE, 
	"OPEN" VARCHAR2(9), 
	"CLOSE" VARCHAR2(9), 
	"HOLIDAY_NAME" VARCHAR2(50), 
	"HOLIDAY_DATE" TIMESTAMP (6), 
	"DELETED" VARCHAR2(1), 
	 CONSTRAINT "STORE_HOURS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "STORE_HOURS_FK1" FOREIGN KEY ("STORE_ID")
	  REFERENCES "ARS"."STORES" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."STORE_PRODUCT_VENDOR" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STORE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VENDOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "STORE_PRODUCT_VENDOR_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "STORE_PRODUCT_VENDOR_UK1" UNIQUE ("STORE_ID", "VENDOR_ID", "PRODUCT_ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "STORE_PRODUCT_VENDOR_FK1" FOREIGN KEY ("STORE_ID")
	  REFERENCES "ARS"."STORES" ("ID") ENABLE, 
	 CONSTRAINT "STORE_PRODUCT_VENDOR_FK2" FOREIGN KEY ("VENDOR_ID", "PRODUCT_ID")
	  REFERENCES "ARS"."VENDOR_PRODUCT" ("VENDOR_ID", "PRODUCT_ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."STORE_PRODUCT_VENDOR_AUDIT" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STORE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VENDOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACTION" VARCHAR2(1) NOT NULL ENABLE, 
	"CHANGED_BY_USER" VARCHAR2(255) NOT NULL ENABLE, 
	"TIME_STAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "STORE_PRODUCT_VENDOR_AUDIT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."USER_AUDIT_LOG" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACTION" NUMBER(19,0) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(255 CHAR), 
	"TIME_STAMP" DATE NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "USER_AUDIT_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."VENDOR" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VENDOR_SHORT_NAME" VARCHAR2(10) NOT NULL ENABLE, 
	"VENDOR_NAME" VARCHAR2(60), 
	"VENDOR_NPI" VARCHAR2(15), 
	"VENDOR_NCPDP" VARCHAR2(255), 
	"VENDOR_NHIN" VARCHAR2(255), 
	"DELETED_DATE" TIMESTAMP (6), 
	"DISABLED_DATE" TIMESTAMP (6), 
	"VERSION" TIMESTAMP (6), 
	"CREATE_DATE" TIMESTAMP (6), 
	"SINGLE_SIGN_ON_TYPE" VARCHAR2(25), 
	"CERTIFICATE_ALGORITHM" VARCHAR2(5), 
	 CONSTRAINT "VENDOR_PK" PRIMARY KEY ("ID")
  USING INDEX REVERSE  ENABLE, 
	 CONSTRAINT "VENDOR_UQ_SHORTNAME" UNIQUE ("VENDOR_SHORT_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "VENDOR_UQ_VENDOR_NPI" UNIQUE ("VENDOR_NPI")
  USING INDEX  ENABLE, 
	 CONSTRAINT "VENDOR_UQ_VENDOR_NCPDP" UNIQUE ("VENDOR_NCPDP")
  USING INDEX  ENABLE, 
	 CONSTRAINT "VENDOR_UQ_VENDOR_NHIN" UNIQUE ("VENDOR_NHIN")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."VENDOR_CERT" 
   (	"ID" NUMBER(19,0), 
	"VENDOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VENDOR_CERT" CLOB, 
	"VENDOR_CERT_THUMBPRINT" VARCHAR2(128), 
	"ISSUE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"EXPIRY_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DISABLED_DATE" TIMESTAMP (6), 
	"CERTIFICATE_ALGORITHM" VARCHAR2(5), 
	 CONSTRAINT "VENDOR_CERT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "VENDOR_CERT_UQ_VNDR_CERT_THUMB" UNIQUE ("VENDOR_CERT_THUMBPRINT")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "VENDOR_CERT_FK_VENDOR" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "ARS"."VENDOR" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."VENDOR_CERT_REQUEST" 
   (	"ID" NUMBER(19,0), 
	"VENDOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VENDOR_CERT_ID" NUMBER(19,0), 
	"REQUEST_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"TIMEOUT_DATE" TIMESTAMP (6), 
	"EMAIL_ADDRESS" VARCHAR2(60) NOT NULL ENABLE, 
	"SUPPORT_USERNAME" VARCHAR2(22), 
	"ACCESS_KEY" VARCHAR2(22), 
	"ACCESS_KEY_CONFIRMATION_CODE" VARCHAR2(15), 
	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"DISABLED_DATE" TIMESTAMP (6), 
	"REGISTRATION_ATTEMPTS" NUMBER(2,0), 
	 CONSTRAINT "VNDR_CERT_REQUEST_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "VNDR_CERT_REQUEST_UQ_ACCESSKEY" UNIQUE ("ACCESS_KEY")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "VNDR_CERT_REQUEST_FK_VENDOR" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "ARS"."VENDOR" ("ID") ENABLE, 
	 CONSTRAINT "VNDR_CERT_REQUEST_FK_VNDR_CERT" FOREIGN KEY ("VENDOR_CERT_ID")
	  REFERENCES "ARS"."VENDOR_CERT" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."VENDOR_PRODUCT" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VENDOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VENDOR_URL" VARCHAR2(2000), 
	 CONSTRAINT "VENDOR_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "VENDOR_PRODUCT_UK1" UNIQUE ("VENDOR_ID", "PRODUCT_ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "VENDOR_PRODUCT_FK1" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "ARS"."VENDOR" ("ID") ENABLE, 
	 CONSTRAINT "VENDOR_PRODUCT_FK2" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "ARS"."PRODUCTS" ("ID") ENABLE
   ) ')),
	 (TO_CLOB('
  CREATE TABLE "ARS"."VENDOR_PRODUCT_INFO" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VENDOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CHAIN_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VENDOR_IDENT" VARCHAR2(255) NOT NULL ENABLE, 
	"VENDOR_PASSPHRASE" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "VENDOR_PRODUCT_INFO_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "VENDOR_PRODUCT_INFO_UK" UNIQUE ("VENDOR_ID", "PRODUCT_ID", "CHAIN_ID")
  USING INDEX  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "VENDOR_PRODUCT_INFO_FK1" FOREIGN KEY ("VENDOR_ID", "PRODUCT_ID")
	  REFERENCES "ARS"."VENDOR_PRODUCT" ("VENDOR_ID", "PRODUCT_ID") ENABLE, 
	 CONSTRAINT "VENDOR_PRODUCT_INFO_FK2" FOREIGN KEY ("CHAIN_ID")
	  REFERENCES "ARS"."CHAINS" ("ID") ENABLE
   ) '));
