INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."ARS_PROPERTIES_PK" ON "ARS"."ARS_PROPERTIES" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."ARS_PROP_UQ_KEY" ON "ARS"."ARS_PROPERTIES" ("KEY") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILLABLE_PRODUCT_PK" ON "ARS"."BILLABLE_PRODUCT" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILLABLE_PRODUCT_UK1" ON "ARS"."BILLABLE_PRODUCT" ("NAME") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILLABLE_VENDOR_PK" ON "ARS"."BILLABLE_VENDOR" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."BILLABLE_VENDOR_PRODUCT_IX1" ON "ARS"."BILLABLE_VENDOR_PRODUCT" ("BILLABLE_VENDOR_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."BILLABLE_VENDOR_PRODUCT_IX2" ON "ARS"."BILLABLE_VENDOR_PRODUCT" ("BILLABLE_PRODUCT_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILLABLE_VENDOR_PRODUCT_PK" ON "ARS"."BILLABLE_VENDOR_PRODUCT" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILLABLE_VENDOR_PRODUCT_UK1" ON "ARS"."BILLABLE_VENDOR_PRODUCT" ("BILLABLE_VENDOR_ID", "BILLABLE_PRODUCT_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILLABLE_VENDOR_UK1" ON "ARS"."BILLABLE_VENDOR" ("VENDOR_SHORT_NAME") 
  '));
INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILLABLE_VENDOR_UK2" ON "ARS"."BILLABLE_VENDOR" ("VENDOR_NPI") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILLABLE_VENDOR_UK3" ON "ARS"."BILLABLE_VENDOR" ("VENDOR_NCPDP") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILLABLE_VENDOR_UK4" ON "ARS"."BILLABLE_VENDOR" ("VENDOR_NHIN") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."BILLABLE_VEND_PROD_STORE_IX1" ON "ARS"."BILLABLE_VEND_PROD_STORE" ("BILLABLE_VENDOR_ID", "BILLABLE_PRODUCT_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."BILLABLE_VEND_PROD_STORE_IX2" ON "ARS"."BILLABLE_VEND_PROD_STORE" ("STORE_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILLABLE_VEND_PROD_STORE_PK" ON "ARS"."BILLABLE_VEND_PROD_STORE" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILLABLE_VEND_PROD_STORE_UK1" ON "ARS"."BILLABLE_VEND_PROD_STORE" ("BILLABLE_VENDOR_ID", "BILLABLE_PRODUCT_ID", "STORE_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."BILL_VEND_PROD_STORE_AUDIT_PK" ON "ARS"."BILL_VEND_PROD_STORE_AUDIT" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."CHAINS_IX1" ON "ARS"."CHAINS" ("PARENT_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."CHAINS_PK" ON "ARS"."CHAINS" ("ID") 
  '));
INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."CHAINS_UQ_HQ_ID" ON "ARS"."CHAINS" ("HQ_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."CHAINS_UQ_NHINID" ON "ARS"."CHAINS" ("NHINID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."CHAIN_PRODUCT_AUDIT_IX1" ON "ARS"."CHAIN_PRODUCT_AUDIT" ("CHAINS_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."CHAIN_PRODUCT_AUDIT_IX2" ON "ARS"."CHAIN_PRODUCT_AUDIT" ("PRODUCTS_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."CHAIN_PRODUCT_AUDIT_PK" ON "ARS"."CHAIN_PRODUCT_AUDIT" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."CHAIN_PRODUCT_IX1" ON "ARS"."CHAIN_PRODUCT" ("CHAINS_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."CHAIN_PRODUCT_IX2" ON "ARS"."CHAIN_PRODUCT" ("PRODUCTS_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."CHAIN_PRODUCT_PK" ON "ARS"."CHAIN_PRODUCT" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."CHAIN_PRODUCT_UK1" ON "ARS"."CHAIN_PRODUCT" ("CHAINS_ID", "PRODUCTS_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."COMM_RESTRICTIONS_IX1" ON "ARS"."COMM_RESTRICTIONS" ("VENDOR_ID") 
  '));
INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE INDEX "ARS"."COMM_RESTRICTIONS_IX2" ON "ARS"."COMM_RESTRICTIONS" ("PRODUCT_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."COMM_RESTRICTIONS_PK" ON "ARS"."COMM_RESTRICTIONS" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."CONTACT_INFO_PK" ON "ARS"."CONTACT_INFO" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."DIVISIONS_IX1" ON "ARS"."DIVISIONS" ("CHAIN_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."DIVISIONS_PK" ON "ARS"."DIVISIONS" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."DIVISIONS_UK1" ON "ARS"."DIVISIONS" ("CHAIN_ID", "NAME") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."INTERFACES_IX1" ON "ARS"."INTERFACES" ("STORE_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."INTERFACES_PK" ON "ARS"."INTERFACES" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."INTERFACES_UK1" ON "ARS"."INTERFACES" ("NAME", "STORE_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."INTERFACE_VERSION_MAP_IX1" ON "ARS"."INTERFACE_VERSION_MAP" ("STORE_ID") 
  '));
INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."INTERFACE_VERSION_MAP_PK" ON "ARS"."INTERFACE_VERSION_MAP" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."INTERFACE_VERSION_MAP_UK1" ON "ARS"."INTERFACE_VERSION_MAP" ("STORE_ID", "SERVICE_NAME") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_CONFIG_PK" ON "ARS"."PDX_SCHEMA_CONFIG" ("KEY") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_FILE_HASH_PK" ON "ARS"."PDX_SCHEMA_FILE_HASH" ("FILE_NAME", "FILE_SOURCE") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_FILE_TASKVER_PK" ON "ARS"."PDX_SCHEMA_FILE_TASKVER" ("FILE_NAME") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_FILE_TASKVER_UK1" ON "ARS"."PDX_SCHEMA_FILE_TASKVER" ("TASK_VERSION") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_MAPPING_PK" ON "ARS"."PDX_SCHEMA_MAPPING" ("SEARCH") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_PRIV_DEFAULT_PK" ON "ARS"."PDX_SCHEMA_PRIV_DEFAULT" ("GRANTEE", "OBJECT_TYPE", "PRIVILEGE") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_PRIV_EXCEPTION_PK" ON "ARS"."PDX_SCHEMA_PRIV_EXCEPTION" ("GRANTEE", "OBJECT_TYPE", "OBJECT_NAME", "PRIVILEGE") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."PDX_SCHEMA_PROCESS_HISTORY_IX1" ON "ARS"."PDX_SCHEMA_PROCESS_HISTORY" ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID") 
  '));
INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE INDEX "ARS"."PDX_SCHEMA_PROCESS_HISTORY_IX2" ON "ARS"."PDX_SCHEMA_PROCESS_HISTORY" ("PDX_SCHEMA_VERSION_HISTORY_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_PROCESS_HISTORY_PK" ON "ARS"."PDX_SCHEMA_PROCESS_HISTORY" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_PROCESS_HISTORY_UK1" ON "ARS"."PDX_SCHEMA_PROCESS_HISTORY" ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID", "PDX_SCHEMA_VERSION_HISTORY_ID", "PROCESS") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."PDX_SCHEMA_TASKVER_META_IX1" ON "ARS"."PDX_SCHEMA_TASKVER_META" ("META_TAG", "TASK_SOURCE", "TASK_VERSION") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."PDX_SCHEMA_TASKVER_META_IX2" ON "ARS"."PDX_SCHEMA_TASKVER_META" ("META_TAG", "TASK_SOURCE", "TASK_VERSION_VALUE") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_TASKVER_META_PK" ON "ARS"."PDX_SCHEMA_TASKVER_META" ("TASK_VERSION", "TASK_SOURCE", "META_TAG", "TASK_VERSION_VALUE") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_TASK_ERROR_LOG_PK" ON "ARS"."PDX_SCHEMA_TASK_ERROR_LOG" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."PDX_SCHEMA_TASK_HISTORY_IX2" ON "ARS"."PDX_SCHEMA_TASK_HISTORY" ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_TASK_HISTORY_PK" ON "ARS"."PDX_SCHEMA_TASK_HISTORY" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_UPDATER_MANIFEST_PK" ON "ARS"."PDX_SCHEMA_UPDATER_MANIFEST" ("VERSION") 
  '));
INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_UPDATER_MANIFST_UK1" ON "ARS"."PDX_SCHEMA_UPDATER_MANIFEST" ("FILE_NAME") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_UPDATER_MANIFST_UK2" ON "ARS"."PDX_SCHEMA_UPDATER_MANIFEST" ("APPLY_ORDER") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_UPDATER_SQL_PK" ON "ARS"."PDX_SCHEMA_UPDATER_SQL" ("FILE_NAME") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."PDX_SCHEMA_UPD_HLPR_DBG_D_IX1" ON "ARS"."PDX_SCHEMA_UPD_HELPER_DEBUG_D" ("PDX_SCHEMA_UPD_HLPR_DBG_H_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_UPD_HLPR_DBG_D_PK" ON "ARS"."PDX_SCHEMA_UPD_HELPER_DEBUG_D" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."PDX_SCHEMA_UPD_HLPR_DBG_H_IX1" ON "ARS"."PDX_SCHEMA_UPD_HELPER_DEBUG_H" ("DEBUG_TIMESTAMP") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_UPD_HLPR_DBG_H_PK" ON "ARS"."PDX_SCHEMA_UPD_HELPER_DEBUG_H" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_UPD_PKGCALL_ELOG_PK" ON "ARS"."PDX_SCHEMA_UPD_PKGCALL_ERR_LOG" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_UPD_PKGCALL_HIST_PK" ON "ARS"."PDX_SCHEMA_UPD_PKGCALL_HIST" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_VERSION_ERR_LOG_PK" ON "ARS"."PDX_SCHEMA_VERSION_ERROR_LOG" ("ID") 
  '));
INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE INDEX "ARS"."PDX_SCHEMA_VERSION_HISTORY_IX1" ON "ARS"."PDX_SCHEMA_VERSION_HISTORY" ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PDX_SCHEMA_VERSION_HISTORY_PK" ON "ARS"."PDX_SCHEMA_VERSION_HISTORY" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PRODUCTS_PK" ON "ARS"."PRODUCTS" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PRODUCTS_UQ_NAME" ON "ARS"."PRODUCTS" ("NAME") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."PUSH_UPDATES_PK" ON "ARS"."PUSH_UPDATES" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."RXCOM_CA_CERT_PK" ON "ARS"."RXCOM_CA_CERT" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."RXCOM_CERTIFICATES_IX1" ON "ARS"."RXCOM_CERTIFICATES" ("STORE_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."RXCOM_CERTIFICATES_PK" ON "ARS"."RXCOM_CERTIFICATES" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."RXCOM_CERTIFICATES_UK1" ON "ARS"."RXCOM_CERTIFICATES" ("SHA1_THUMBPRINT") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."SCHEMA_UPDATER_MANIFEST_PK" ON "ARS"."SCHEMA_UPDATER_MANIFEST" ("FILE_NAME") 
  '));
INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."SCHEMA_UPDATER_MANIFEST_UK1" ON "ARS"."SCHEMA_UPDATER_MANIFEST" ("VERSION") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."SCHEMA_UPDATER_MANIFST_UK2" ON "ARS"."SCHEMA_UPDATER_MANIFEST" ("APPLY_ORDER") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."SCHEMA_UPDATER_SQL_PK" ON "ARS"."SCHEMA_UPDATER_SQL" ("FILE_NAME") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."STORES_IX1" ON "ARS"."STORES" ("OBS_CERT_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."STORES_IX2" ON "ARS"."STORES" ("CHAIN_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."STORES_IX3" ON "ARS"."STORES" ("DIVISIONS_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."STORES_PK" ON "ARS"."STORES" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."STORES_UQ_NCPDP" ON "ARS"."STORES" ("NCPDP") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."STORES_UQ_NHINID" ON "ARS"."STORES" ("NHINID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."STORES_UQ_NPI" ON "ARS"."STORES" ("NPI") 
  '));
INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE INDEX "ARS"."STORE_HOURS_IX1" ON "ARS"."STORE_HOURS" ("STORE_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."STORE_HOURS_PK" ON "ARS"."STORE_HOURS" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."STORE_PRODUCT_VENDOR_AUDIT_PK" ON "ARS"."STORE_PRODUCT_VENDOR_AUDIT" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."STORE_PRODUCT_VENDOR_IX1" ON "ARS"."STORE_PRODUCT_VENDOR" ("STORE_ID", "PRODUCT_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."STORE_PRODUCT_VENDOR_IX2" ON "ARS"."STORE_PRODUCT_VENDOR" ("VENDOR_ID", "PRODUCT_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."STORE_PRODUCT_VENDOR_PK" ON "ARS"."STORE_PRODUCT_VENDOR" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."STORE_PRODUCT_VENDOR_UK1" ON "ARS"."STORE_PRODUCT_VENDOR" ("STORE_ID", "VENDOR_ID", "PRODUCT_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."USER_AUDIT_LOG_PK" ON "ARS"."USER_AUDIT_LOG" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."VENDOR_CERT_IDX_VENDORID" ON "ARS"."VENDOR_CERT" ("VENDOR_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VENDOR_CERT_PK" ON "ARS"."VENDOR_CERT" ("ID") 
  '));
INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VENDOR_CERT_UQ_VNDR_CERT_THUMB" ON "ARS"."VENDOR_CERT" ("VENDOR_CERT_THUMBPRINT") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VENDOR_PK" ON "ARS"."VENDOR" ("ID") REVERSE 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."VENDOR_PRODUCT_INFO_IX1" ON "ARS"."VENDOR_PRODUCT_INFO" ("VENDOR_ID", "PRODUCT_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."VENDOR_PRODUCT_INFO_IX2" ON "ARS"."VENDOR_PRODUCT_INFO" ("CHAIN_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VENDOR_PRODUCT_INFO_PK" ON "ARS"."VENDOR_PRODUCT_INFO" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VENDOR_PRODUCT_INFO_UK" ON "ARS"."VENDOR_PRODUCT_INFO" ("VENDOR_ID", "PRODUCT_ID", "CHAIN_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."VENDOR_PRODUCT_IX1" ON "ARS"."VENDOR_PRODUCT" ("VENDOR_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."VENDOR_PRODUCT_IX2" ON "ARS"."VENDOR_PRODUCT" ("PRODUCT_ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VENDOR_PRODUCT_PK" ON "ARS"."VENDOR_PRODUCT" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VENDOR_PRODUCT_UK1" ON "ARS"."VENDOR_PRODUCT" ("VENDOR_ID", "PRODUCT_ID") 
  '));
INSERT INTO ALL_INDEXES ("DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)") VALUES
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VENDOR_UQ_SHORTNAME" ON "ARS"."VENDOR" ("VENDOR_SHORT_NAME") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VENDOR_UQ_VENDOR_NCPDP" ON "ARS"."VENDOR" ("VENDOR_NCPDP") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VENDOR_UQ_VENDOR_NHIN" ON "ARS"."VENDOR" ("VENDOR_NHIN") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VENDOR_UQ_VENDOR_NPI" ON "ARS"."VENDOR" ("VENDOR_NPI") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VNDR_CERT_REQUEST_PK" ON "ARS"."VENDOR_CERT_REQUEST" ("ID") 
  ')),
	 (TO_CLOB('
  CREATE UNIQUE INDEX "ARS"."VNDR_CERT_REQUEST_UQ_ACCESSKEY" ON "ARS"."VENDOR_CERT_REQUEST" ("ACCESS_KEY") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."VNDR_CRT_REQUEST_IDX_REQUESTDT" ON "ARS"."VENDOR_CERT_REQUEST" ("REQUEST_DATE") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."VNDR_CRT_REQUEST_IDX_VENDORID" ON "ARS"."VENDOR_CERT_REQUEST" ("VENDOR_ID") 
  ')),
	 (TO_CLOB('
  CREATE INDEX "ARS"."VNDR_CRT_REQUEST_IDX_VNDRCRTID" ON "ARS"."VENDOR_CERT_REQUEST" ("VENDOR_CERT_ID") 
  '));
