
USE [nonEPR-DB]
GO
 IF NOT EXISTS(SELECT * FROM sys.schemas WHERE [name] = N'SBMO')      
     EXEC (N'CREATE SCHEMA SBMO')                                   
 GO                                                               

USE [nonEPR-DB]
GO
IF EXISTS (SELECT * FROM sys.sequences seq JOIN sys.schemas sch ON seq.schema_id=sch.schema_id WHERE seq.name=N'AUDIT_DBU_LOG_SEQ'  AND sch.name=N'SBMO' )
 DROP SEQUENCE [SBMO].[AUDIT_DBU_LOG_SEQ]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SEQUENCE [SBMO].[AUDIT_DBU_LOG_SEQ]
    AS bigint
    START WITH 201
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    NO CYCLE
    CACHE 
GO

USE [nonEPR-DB]
GO
IF EXISTS (SELECT * FROM sys.sequences seq JOIN sys.schemas sch ON seq.schema_id=sch.schema_id WHERE seq.name=N'ICN_SEQ'  AND sch.name=N'SBMO' )
 DROP SEQUENCE [SBMO].[ICN_SEQ]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SEQUENCE [SBMO].[ICN_SEQ]
    AS bigint
    START WITH 57151
    INCREMENT BY 1
    MINVALUE 0
    MAXVALUE 9223372036854775807
    NO CYCLE
    CACHE 
GO

USE [nonEPR-DB]
GO
IF EXISTS (SELECT * FROM sys.sequences seq JOIN sys.schemas sch ON seq.schema_id=sch.schema_id WHERE seq.name=N'MASTER_SEQ'  AND sch.name=N'SBMO' )
 DROP SEQUENCE [SBMO].[MASTER_SEQ]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SEQUENCE [SBMO].[MASTER_SEQ]
    AS bigint
    START WITH 3168762366
    INCREMENT BY 1
    MINVALUE 0
    MAXVALUE 9223372036854775807
    NO CYCLE
    CACHE 
GO

USE [nonEPR-DB]
GO
IF EXISTS (SELECT * FROM sys.sequences seq JOIN sys.schemas sch ON seq.schema_id=sch.schema_id WHERE seq.name=N'NHIN_BATCH_SEQ'  AND sch.name=N'SBMO' )
 DROP SEQUENCE [SBMO].[NHIN_BATCH_SEQ]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SEQUENCE [SBMO].[NHIN_BATCH_SEQ]
    AS bigint
    START WITH 201
    INCREMENT BY 1
    MINVALUE 0
    MAXVALUE 9223372036854775807
    NO CYCLE
    CACHE 
GO

USE [nonEPR-DB]
GO
IF EXISTS (SELECT * FROM sys.sequences seq JOIN sys.schemas sch ON seq.schema_id=sch.schema_id WHERE seq.name=N'ORDER_SEQ'  AND sch.name=N'SBMO' )
 DROP SEQUENCE [SBMO].[ORDER_SEQ]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SEQUENCE [SBMO].[ORDER_SEQ]
    AS bigint
    START WITH 151361921
    INCREMENT BY 1
    MINVALUE 0
    MAXVALUE 9223372036854775807
    NO CYCLE
    CACHE 
GO

USE [nonEPR-DB]
GO
IF EXISTS (SELECT * FROM sys.sequences seq JOIN sys.schemas sch ON seq.schema_id=sch.schema_id WHERE seq.name=N'PDX_SCHEMA_MASTER_SEQ'  AND sch.name=N'SBMO' )
 DROP SEQUENCE [SBMO].[PDX_SCHEMA_MASTER_SEQ]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SEQUENCE [SBMO].[PDX_SCHEMA_MASTER_SEQ]
    AS bigint
    START WITH 1104
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    NO CYCLE
    CACHE 
GO

USE [nonEPR-DB]
GO
IF EXISTS (SELECT * FROM sys.sequences seq JOIN sys.schemas sch ON seq.schema_id=sch.schema_id WHERE seq.name=N'PO_SEQ'  AND sch.name=N'SBMO' )
 DROP SEQUENCE [SBMO].[PO_SEQ]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SEQUENCE [SBMO].[PO_SEQ]
    AS bigint
    START WITH 13080631
    INCREMENT BY 1
    MINVALUE 0
    MAXVALUE 9223372036854775807
    NO CYCLE
    CACHE 
GO

USE [nonEPR-DB]
GO
IF EXISTS (SELECT * FROM sys.sequences seq JOIN sys.schemas sch ON seq.schema_id=sch.schema_id WHERE seq.name=N'PURGE_SEQ'  AND sch.name=N'SBMO' )
 DROP SEQUENCE [SBMO].[PURGE_SEQ]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SEQUENCE [SBMO].[PURGE_SEQ]
    AS bigint
    START WITH 400473
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    NO CYCLE
    CACHE 
GO

USE [nonEPR-DB]
GO
IF EXISTS (SELECT * FROM sys.sequences seq JOIN sys.schemas sch ON seq.schema_id=sch.schema_id WHERE seq.name=N'QUEUE_SEQ'  AND sch.name=N'SBMO' )
 DROP SEQUENCE [SBMO].[QUEUE_SEQ]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SEQUENCE [SBMO].[QUEUE_SEQ]
    AS bigint
    START WITH 152671541
    INCREMENT BY 1
    MINVALUE 0
    MAXVALUE 9223372036854775807
    NO CYCLE
    CACHE 
GO
