;

;

CREATE UNIQUE CLUSTERED INDEX ADJUSTMENT_CODES_PK ON nonEPR-DB.SBMO.ADJUSTMENT_CODES (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE UNIQUE CLUSTERED INDEX AUDIT_DBU_LOG_PK ON nonEPR-DB.SBMO.AUDIT_DBU_LOG (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

;

CREATE NONCLUSTERED INDEX CARRIER_IX1 ON nonEPR-DB.SBMO.CARRIER (  TENANT_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

;

;

;

CREATE NONCLUSTERED INDEX CHAINS_IX2 ON nonEPR-DB.SBMO.CHAINS (  TENANT_ID ASC  , PARENT_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX CHAINS_PK ON nonEPR-DB.SBMO.CHAINS (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX CHAINS_UQ_HQID ON nonEPR-DB.SBMO.CHAINS (  HQ_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX CHAINS_UQ_NHINID ON nonEPR-DB.SBMO.CHAINS (  NHINID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

;

;

;

;

;

;

;

;

;

;

CREATE UNIQUE NONCLUSTERED INDEX DASHBOARD_SETTINGS_UK1 ON nonEPR-DB.SBMO.DASHBOARD_SETTINGS (  TENANT_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

CREATE NONCLUSTERED INDEX DISPENSERS_IX2 ON nonEPR-DB.SBMO.DISPENSERS (  TENANT_ID ASC  , INVENTORY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX DISPENSERS_IX3 ON nonEPR-DB.SBMO.DISPENSERS (  TENANT_ID ASC  , FACILITY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX DISPENSERS_PK ON nonEPR-DB.SBMO.DISPENSERS (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

CREATE UNIQUE NONCLUSTERED INDEX DISPENSER_LOCATION_UK1 ON nonEPR-DB.SBMO.DISPENSER_LOCATION (  TENANT_ID ASC  , CELLID ASC  , STATIONID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

CREATE UNIQUE CLUSTERED INDEX DRUGS_PK ON nonEPR-DB.SBMO.DRUGS (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX DRUGS_UQ_NDC ON nonEPR-DB.SBMO.DRUGS (  NDC ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

;

;

CREATE NONCLUSTERED INDEX ENCRYPTION_KEYS_IX1 ON nonEPR-DB.SBMO.ENCRYPTION_KEYS (  TENANT_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

CREATE UNIQUE NONCLUSTERED INDEX ENCRYPTION_KEYS_UK1 ON nonEPR-DB.SBMO.ENCRYPTION_KEYS (  TENANT_ID ASC  , CREATED_DATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

CREATE UNIQUE CLUSTERED INDEX ENTITIES_PK ON nonEPR-DB.SBMO.ENTITIES (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK__EXT_DRUG__3214EC2700F7D8C8 ON nonEPR-DB.SBMO.EXT_DRUG_LOAD (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX FACILITIES_PK ON nonEPR-DB.SBMO.FACILITIES (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX FILLING_STATION_IX2 ON nonEPR-DB.SBMO.FILLING_STATION (  TENANT_ID ASC  , FACILITY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX FILLING_STATION_IX3 ON nonEPR-DB.SBMO.FILLING_STATION (  TENANT_ID ASC  , FACILITY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX FILLING_STATION_PK ON nonEPR-DB.SBMO.FILLING_STATION (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX FORMULARY_IX1 ON nonEPR-DB.SBMO.FORMULARY (  TENANT_ID ASC  , DRUG_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX FORMULARY_IX2 ON nonEPR-DB.SBMO.FORMULARY (  TENANT_ID ASC  , NDC ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX FORMULARY_IX3 ON nonEPR-DB.SBMO.FORMULARY (  TENANT_ID ASC  , INVENTORY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX FORMULARY_IX4 ON nonEPR-DB.SBMO.FORMULARY (  TENANT_ID ASC  , VENDOR_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX FORMULARY_IX5 ON nonEPR-DB.SBMO.FORMULARY (  TENANT_ID ASC  , OVERRIDE_SHIP_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX FORMULARY_IX6 ON nonEPR-DB.SBMO.FORMULARY (  TENANT_ID ASC  , FILLING_STATION_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX FORMULARY_PK ON nonEPR-DB.SBMO.FORMULARY (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX FORMULARY_UK1 ON nonEPR-DB.SBMO.FORMULARY (  TENANT_ID ASC  , DRUG_ID ASC  , INVENTORY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX FORMULARY_REORDER_PK ON nonEPR-DB.SBMO.FORMULARY_REORDER (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX INVENTORY_IX2 ON nonEPR-DB.SBMO.INVENTORY (  TENANT_ID ASC  , FACILITY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX INVENTORY_IX3 ON nonEPR-DB.SBMO.INVENTORY (  TENANT_ID ASC  , FACILITY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX INVENTORY_PK ON nonEPR-DB.SBMO.INVENTORY (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX INVENTORY_UK1 ON nonEPR-DB.SBMO.INVENTORY (  TENANT_ID ASC  , NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

;

;

CREATE UNIQUE CLUSTERED INDEX INVENTORY_DATE_PK ON nonEPR-DB.SBMO.INVENTORY_DATE (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE UNIQUE NONCLUSTERED INDEX LABEL_IMAGES_PK ON nonEPR-DB.SBMO.LABEL_IMAGES (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX LABEL_IMAGES_UK1 ON nonEPR-DB.SBMO.LABEL_IMAGES (  TENANT_ID ASC  , IMAGE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX LABEL_IMAGES_UQ_IMAGE_NAME ON nonEPR-DB.SBMO.LABEL_IMAGES (  IMAGE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX LOCATION_PK ON nonEPR-DB.SBMO.LOCATION (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX LOCATION_UK1 ON nonEPR-DB.SBMO.LOCATION (  TENANT_ID ASC  , DESCRIPTOR ASC  , PARENT_ID ASC  , LOCATION_TYPE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

;

;

;

;

CREATE UNIQUE CLUSTERED INDEX PK__MUTEX__D9C1FA0172E797BD ON nonEPR-DB.SBMO.MUTEX (  NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE NONCLUSTERED INDEX ORDERS_IX2 ON nonEPR-DB.SBMO.ORDERS (  TENANT_ID ASC  , INVENTORY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX ORDERS_IX3 ON nonEPR-DB.SBMO.ORDERS (  TENANT_ID ASC  , STORE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX ORDERS_IX4 ON nonEPR-DB.SBMO.ORDERS (  TENANT_ID ASC  , BATCH_IDENTIFIER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX ORDERS_IX5 ON nonEPR-DB.SBMO.ORDERS (  TENANT_ID ASC  , EXTERNAL_ORDER_IDENTIFIER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX ORDERS_IX7 ON nonEPR-DB.SBMO.ORDERS (  TENANT_ID ASC  , SHIP_CITY ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX ORDERS_PK ON nonEPR-DB.SBMO.ORDERS (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX ORDERS_UQ_ORDER_NUMBER ON nonEPR-DB.SBMO.ORDERS (  ORDER_NUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX SQL_HISTORY_PK ON nonEPR-DB.SBMO.PARTITION_SQL_HISTORY (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PARTITION_TABLE_LIST_PK ON nonEPR-DB.SBMO.PARTITION_TABLE_LIST (  TABLE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK__PDX_DBA___CAE1EFADFCEA58F2 ON nonEPR-DB.SBMO.PDX_DBA_APPLIED (  TASK_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK__PDX_SCHE__C41F3ED0B36CCCA9 ON nonEPR-DB.SBMO.PDX_SCHEMA_CONFIG (  KEY ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK__PDX_SCHE__448AD0BEC8DAB38C ON nonEPR-DB.SBMO.PDX_SCHEMA_FILE_HASH (  FILE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX PDX_SCHEMA_FILE_TASKVER_UK1 ON nonEPR-DB.SBMO.PDX_SCHEMA_FILE_TASKVER (  TASK_VERSION ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK__PDX_SCHE__448AD0BEBBD810BC ON nonEPR-DB.SBMO.PDX_SCHEMA_FILE_TASKVER (  FILE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PDX_SCHEMA_MAPPING_PK ON nonEPR-DB.SBMO.PDX_SCHEMA_MAPPING (  SEARCH ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK__PDX_SCHE__6F2491106154BD8C ON nonEPR-DB.SBMO.PDX_SCHEMA_PRIV_DEFAULT (  GRANTEE ASC  , OBJECT_TYPE ASC  , PRIVILEGE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK__PDX_SCHE__78B20A84370724C6 ON nonEPR-DB.SBMO.PDX_SCHEMA_PRIV_EXCEPTION (  GRANTEE ASC  , OBJECT_TYPE ASC  , OBJECT_NAME ASC  , PRIVILEGE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX PDX_SCHEMA_PROCESS_HISTORY_IX1 ON nonEPR-DB.SBMO.PDX_SCHEMA_PROCESS_HISTORY (  PDX_SCHEMA_UPD_PKGCALL_HIST_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX PDX_SCHEMA_PROCESS_HISTORY_IX2 ON nonEPR-DB.SBMO.PDX_SCHEMA_PROCESS_HISTORY (  PDX_SCHEMA_VERSION_HISTORY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX PDX_SCHEMA_PROCESS_HISTORY_UK1 ON nonEPR-DB.SBMO.PDX_SCHEMA_PROCESS_HISTORY (  PDX_SCHEMA_UPD_PKGCALL_HIST_ID ASC  , PDX_SCHEMA_VERSION_HISTORY_ID ASC  , PROCESS ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK_PDX_SCHEMA_PROCESS_HISTORY ON nonEPR-DB.SBMO.PDX_SCHEMA_PROCESS_HISTORY (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PDX_SCHEMA_TASKVER_META_PK ON nonEPR-DB.SBMO.PDX_SCHEMA_TASKVER_META (  TASK_VERSION ASC  , TASK_SOURCE ASC  , META_TAG ASC  , TASK_VERSION_VALUE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX PDX_SCHEMA_TASK_ERROR_LOG_PK ON nonEPR-DB.SBMO.PDX_SCHEMA_TASK_ERROR_LOG (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK_PDX_SCHEMA_TASK_ERROR_LOG ON nonEPR-DB.SBMO.PDX_SCHEMA_TASK_ERROR_LOG (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK_PDX_SCHEMA_TASK_HISTORY ON nonEPR-DB.SBMO.PDX_SCHEMA_TASK_HISTORY (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PDX_SCHEMA_UPDATER_MANIFEST_PK ON nonEPR-DB.SBMO.PDX_SCHEMA_UPDATER_MANIFEST (  VERSION ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PDX_SCHEMA_UPDATER_SQL_PK ON nonEPR-DB.SBMO.PDX_SCHEMA_UPDATER_SQL (  FILE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX PDX_SCHEMA_UPD_HLPR_DBG_D_IX1 ON nonEPR-DB.SBMO.PDX_SCHEMA_UPD_HELPER_DEBUG_D (  PDX_SCHEMA_UPD_HLPR_DBG_H_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK_PDX_SCHEMA_UPD_HELPER_DEBUG_D ON nonEPR-DB.SBMO.PDX_SCHEMA_UPD_HELPER_DEBUG_D (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PDX_SCHEMA_UPD_HELPER_DEBUG_H_PK ON nonEPR-DB.SBMO.PDX_SCHEMA_UPD_HELPER_DEBUG_H (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX PDX_SCHEMA_UPD_PKGCALL_ELOG_PK ON nonEPR-DB.SBMO.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK_PDX_SCHEMA_UPD_PKGCALL_ERR_LOG ON nonEPR-DB.SBMO.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PDX_SCHEMA_UPD_PKGCALL_HIST_PK ON nonEPR-DB.SBMO.PDX_SCHEMA_UPD_PKGCALL_HIST (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK_PDX_SCHEMA_VERSION_ERROR_LOG ON nonEPR-DB.SBMO.PDX_SCHEMA_VERSION_ERROR_LOG (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX PDX_SCHEMA_VERSION_HISTORY_IX1 ON nonEPR-DB.SBMO.PDX_SCHEMA_VERSION_HISTORY (  PDX_SCHEMA_UPD_PKGCALL_HIST_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK_PDX_SCHEMA_VERSION_HISTORY ON nonEPR-DB.SBMO.PDX_SCHEMA_VERSION_HISTORY (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

CREATE UNIQUE NONCLUSTERED INDEX PHONES_UK1 ON nonEPR-DB.SBMO.PHONES (  TENANT_ID ASC  , OWNER_ID ASC  , IDX ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX PHONE_ADDRESS_OWNERS_PK ON nonEPR-DB.SBMO.PHONE_ADDRESS_OWNERS (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE NONCLUSTERED INDEX PURCHASE_ORDER_IX2 ON nonEPR-DB.SBMO.PURCHASE_ORDER (  TENANT_ID ASC  , PO_GROUP_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX PURCHASE_ORDER_IX3 ON nonEPR-DB.SBMO.PURCHASE_ORDER (  TENANT_ID ASC  , VENDOR_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX PURCHASE_ORDER_IX4 ON nonEPR-DB.SBMO.PURCHASE_ORDER (  TENANT_ID ASC  , FACILITY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PURCHASE_ORDER_PK ON nonEPR-DB.SBMO.PURCHASE_ORDER (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX PURCHASE_ORDER_UK1 ON nonEPR-DB.SBMO.PURCHASE_ORDER (  TENANT_ID ASC  , PURCHASE_ORDER_NUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

CREATE UNIQUE CLUSTERED INDEX PK__PURGE_CO__D9C1FA01FFD964EB ON nonEPR-DB.SBMO.PURGE_CONFIG_SETTINGS (  NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX PURGE_CONFIG_SETTINGS_PK ON nonEPR-DB.SBMO.PURGE_CONFIG_SETTINGS (  NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PURGE_ERROR_LOG_PK ON nonEPR-DB.SBMO.PURGE_ERROR_LOG (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK_PURGE_HISTORY ON nonEPR-DB.SBMO.PURGE_HISTORY (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK_PURGE_HISTORY_CHUNKS ON nonEPR-DB.SBMO.PURGE_HISTORY_CHUNKS (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX PURGE_HISTORY_CHUNKS_IX2 ON nonEPR-DB.SBMO.PURGE_HISTORY_CHUNKS (  TABLE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PURGE_HISTORY_PARTITIONS_PK ON nonEPR-DB.SBMO.PURGE_HISTORY_PARTITIONS (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PURGE_RUN_CHECK_PK ON nonEPR-DB.SBMO.PURGE_RUN_CHECK (  ACTIVITY_DATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK__PURGE_TA__CF56543B0CF3D5D6 ON nonEPR-DB.SBMO.PURGE_TABLES (  TABLE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX PURGE_TABLES_PK ON nonEPR-DB.SBMO.PURGE_TABLES (  TABLE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX QRTZ_BLOB_TRIGGERS_PK ON nonEPR-DB.SBMO.QRTZ_BLOB_TRIGGERS (  TRIGGER_NAME ASC  , TRIGGER_GROUP ASC  , SCHED_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX QRTZ_CALENDARS_PK ON nonEPR-DB.SBMO.QRTZ_CALENDARS (  SCHED_NAME ASC  , CALENDAR_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX QRTZ_CRON_TRIGGERS_PK ON nonEPR-DB.SBMO.QRTZ_CRON_TRIGGERS (  TRIGGER_NAME ASC  , TRIGGER_GROUP ASC  , SCHED_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX IDX_QRTZ_FT_TRIG_NM_GP ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  TRIGGER_NAME ASC  , TRIGGER_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIGGERS_IX1 ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  SCHED_NAME ASC  , INSTANCE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIGGERS_IX2 ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  SCHED_NAME ASC  , INSTANCE_NAME ASC  , REQUESTS_RECOVERY ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIGGERS_IX3 ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  SCHED_NAME ASC  , JOB_NAME ASC  , JOB_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIGGERS_IX4 ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  SCHED_NAME ASC  , JOB_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIGGERS_IX5 ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  SCHED_NAME ASC  , TRIGGER_NAME ASC  , TRIGGER_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIGGERS_IX6 ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  SCHED_NAME ASC  , TRIGGER_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX QRTZ_FIRED_TRIGGERS_PK ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  SCHED_NAME ASC  , ENTRY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIG_IDX_INSTNAME ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  INSTANCE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIG_IDX_JOBGRP ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  JOB_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIG_IDX_JOBNAME ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  JOB_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIG_IDX_REQRECOVER ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  REQUESTS_RECOVERY ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIG_IDX_TRIGGRP ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  TRIGGER_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_FIRED_TRIG_IDX_TRIGNAME ON nonEPR-DB.SBMO.QRTZ_FIRED_TRIGGERS (  TRIGGER_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_JOB_DETAILS_IX1 ON nonEPR-DB.SBMO.QRTZ_JOB_DETAILS (  SCHED_NAME ASC  , REQUESTS_RECOVERY ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_JOB_DETAILS_IX2 ON nonEPR-DB.SBMO.QRTZ_JOB_DETAILS (  SCHED_NAME ASC  , JOB_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_JOB_DETAILS_IX3 ON nonEPR-DB.SBMO.QRTZ_JOB_DETAILS (  SCHED_NAME ASC  , REQUESTS_RECOVERY ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX QRTZ_JOB_DETAILS_PK ON nonEPR-DB.SBMO.QRTZ_JOB_DETAILS (  SCHED_NAME ASC  , JOB_NAME ASC  , JOB_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_JOB_DTLS_IDX_REQRECOVER ON nonEPR-DB.SBMO.QRTZ_JOB_DETAILS (  REQUESTS_RECOVERY ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX QRTZ_LOCKS_PK ON nonEPR-DB.SBMO.QRTZ_LOCKS (  SCHED_NAME ASC  , LOCK_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX QRTZ_PAUSED_TRIGGER_GRPS_PK ON nonEPR-DB.SBMO.QRTZ_PAUSED_TRIGGER_GRPS (  SCHED_NAME ASC  , TRIGGER_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX QRTZ_SCHEDULER_STATE_PK ON nonEPR-DB.SBMO.QRTZ_SCHEDULER_STATE (  SCHED_NAME ASC  , INSTANCE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX QRTZ_SIMPLE_TRIGGERS_PK ON nonEPR-DB.SBMO.QRTZ_SIMPLE_TRIGGERS (  TRIGGER_NAME ASC  , TRIGGER_GROUP ASC  , SCHED_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX QRTZ_SIMPROP_TRIGGERS_PK ON nonEPR-DB.SBMO.QRTZ_SIMPROP_TRIGGERS (  SCHED_NAME ASC  , TRIGGER_NAME ASC  , TRIGGER_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX IDX_QRTZ_T_NFT_ST ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  NEXT_FIRE_TIME ASC  , TRIGGER_STATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IDX_JOBID ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  JOB_NAME ASC  , JOB_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IDX_NEXTFIRE ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  NEXT_FIRE_TIME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IDX_TRIGSTATE ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  TRIGGER_STATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX1 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , JOB_NAME ASC  , JOB_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX10 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , MISFIRE_INSTR ASC  , NEXT_FIRE_TIME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX11 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , MISFIRE_INSTR ASC  , NEXT_FIRE_TIME ASC  , TRIGGER_STATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX12 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , MISFIRE_INSTR ASC  , NEXT_FIRE_TIME ASC  , TRIGGER_GROUP ASC  , TRIGGER_STATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX2 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , JOB_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX3 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , CALENDAR_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX4 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , TRIGGER_GROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX5 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , TRIGGER_STATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX6 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , TRIGGER_NAME ASC  , TRIGGER_GROUP ASC  , TRIGGER_STATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX7 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , TRIGGER_GROUP ASC  , TRIGGER_STATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX8 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , NEXT_FIRE_TIME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX QRTZ_TRIGGERS_IX9 ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  SCHED_NAME ASC  , TRIGGER_STATE ASC  , NEXT_FIRE_TIME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX QRTZ_TRIGGERS_PK ON nonEPR-DB.SBMO.QRTZ_TRIGGERS (  TRIGGER_NAME ASC  , TRIGGER_GROUP ASC  , SCHED_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX REGION_PK ON nonEPR-DB.SBMO.REGION (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX REGION_UK1 ON nonEPR-DB.SBMO.REGION (  TENANT_ID ASC  , NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

CREATE NONCLUSTERED INDEX REPORT_REQUEST_PARAMETER_IX1 ON nonEPR-DB.SBMO.REPORT_REQUEST_PARAMETER (  TENANT_ID ASC  , REPORT_REQUEST_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

;

;

;

;

;

;

;

;

;

;

CREATE NONCLUSTERED INDEX RX_CORES_IX1 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , ADDED_DATE ASC  , STATUS ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX10 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , LAST_UPDATE_DATE ASC  , STORE_NHINID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX11 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , STATUS ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX12 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , CREATED_DATE ASC  , COMPLETED_DATE ASC  , FILLED_VENDOR_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX13 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , FILLING_STATION_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX2 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , FILLED_VENDOR_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX3 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , ORDER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX4 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , HOLD_RX_AT_SBMO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX5 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , STATUS ASC  , DISPENSED_DATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX6 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , STATUS_LAST_UPDATE_DATE ASC  , STATUS ASC  , SPECIALTY ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX7 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , SHIPPING_PACKAGE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX8 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , STORE_CF_QUEUE_NUM ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_CORES_IX9 ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , STORE_NHINID ASC  , RXNUM ASC  , TXNUM ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX RX_CORES_PK ON nonEPR-DB.SBMO.RX_CORES (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX RX_CORES_UQ_CFQUEUENUM ON nonEPR-DB.SBMO.RX_CORES (  CF_QUEUE_NUM ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

CREATE UNIQUE NONCLUSTERED INDEX RX_CORES_MIN_DATE_UK1 ON nonEPR-DB.SBMO.RX_CORES_MIN_DATE (  TENANT_ID ASC  , FACILITY_ID ASC  , DATE_TYPE ASC  , STATUS ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_DETAILS_IX2 ON nonEPR-DB.SBMO.RX_DETAILS (  TENANT_ID ASC  , FILLED_DISPENSER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX RX_DETAILS_PK ON nonEPR-DB.SBMO.RX_DETAILS (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_DIGITAL_DOCUMENTS_IX1 ON nonEPR-DB.SBMO.RX_DIGITAL_DOCUMENTS (  RX_CORES_ID ASC  , TENANT_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE NONCLUSTERED INDEX RX_HOURS_OF_ADMINISTRATION_IX1 ON nonEPR-DB.SBMO.RX_HOURS_OF_ADMINISTRATION (  TENANT_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE UNIQUE NONCLUSTERED INDEX RX_HOURS_OF_ADMIN_DOSES_UK1 ON nonEPR-DB.SBMO.RX_HOURS_OF_ADMIN_DOSES (  RX_HOURS_OF_ADMINISTRATION_ID ASC  , TENANT_ID ASC  , DATE_OF_DOSE ASC  , TIME_OF_DOSE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_IMAGE_DATA_IX1 ON nonEPR-DB.SBMO.RX_IMAGE_DATA (  TENANT_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

CREATE NONCLUSTERED INDEX RX_LOTS_IX2 ON nonEPR-DB.SBMO.RX_LOTS (  RX_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

CREATE UNIQUE CLUSTERED INDEX RX_PATSTORES_PK ON nonEPR-DB.SBMO.RX_PATSTORES (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_PRINT_CHR_IX3 ON nonEPR-DB.SBMO.RX_PRINT_CHR (  TENANT_ID ASC  , RX_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

CREATE UNIQUE CLUSTERED INDEX RX_PRINT_INFO_PK ON nonEPR-DB.SBMO.RX_PRINT_INFO (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

;

;

;

CREATE UNIQUE CLUSTERED INDEX RX_SHIPPING_PACKAGES_PK ON nonEPR-DB.SBMO.RX_SHIPPING_PACKAGES (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX RX_STATE_TRANSITION_IX1 ON nonEPR-DB.SBMO.RX_STATE_TRANSITION (  TENANT_ID ASC  , RX_CORE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE NONCLUSTERED INDEX RX_TP_INFO_IX3 ON nonEPR-DB.SBMO.RX_TP_INFO (  TENANT_ID ASC  , RX_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE UNIQUE NONCLUSTERED INDEX RX_VIAL_INFOS_UK1 ON nonEPR-DB.SBMO.RX_VIAL_INFOS (  TENANT_ID ASC  , RX_ID ASC  , VIAL_NUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE UNIQUE CLUSTERED INDEX SBMO_LOCKS_PK ON nonEPR-DB.SBMO.SBMO_LOCKS (  LOCK_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX SBMO_PROPERTIES_PK ON nonEPR-DB.SBMO.SBMO_PROPERTIES (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX SBMO_PROPERTIES_UQ_KEY ON nonEPR-DB.SBMO.SBMO_PROPERTIES (  KEY ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE UNIQUE CLUSTERED INDEX SCHEMA_UPDATER_MANIFEST_PK ON nonEPR-DB.SBMO.SCHEMA_UPDATER_MANIFEST (  VERSION ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX SCHEMA_UPDATER_SQL_PK ON nonEPR-DB.SBMO.SCHEMA_UPDATER_SQL (  FILE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

CREATE NONCLUSTERED INDEX STORES_IX10 ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , MAIL_ORIG_INVENTORY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX STORES_IX11 ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , UNIT_DOSE_INVENTORY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX STORES_IX12 ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , UNIT_DOSE_ORIG_INVENTORY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX STORES_IX2 ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , CHAIN_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX STORES_IX3 ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , STORE_NUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX STORES_IX4 ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , MAIL_INVENTORY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX STORES_IX5 ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , STORE_INVENTORY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX STORES_IX6 ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , REGION_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX STORES_IX9 ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , STORE_ORIG_INVENTORY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX STORES_PK ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX STORES_UK1 ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , NCPDP ASC  , DEPARTMENT ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX STORES_UK2 ON nonEPR-DB.SBMO.STORES (  NPI_NUM ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX STORES_UQ_NHINID ON nonEPR-DB.SBMO.STORES (  TENANT_ID ASC  , NHINID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

;

;

;

;

;

;

CREATE UNIQUE NONCLUSTERED INDEX TENANTS_PK ON nonEPR-DB.SBMO.TENANTS (  ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX TENANTS_UK1 ON nonEPR-DB.SBMO.TENANTS (  NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX VENDOR_PK ON nonEPR-DB.SBMO.VENDOR (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE NONCLUSTERED INDEX VENDOR_UK1 ON nonEPR-DB.SBMO.VENDOR (  TENANT_ID ASC  , NHINVEN ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE UNIQUE NONCLUSTERED INDEX VENDOR_ITEM_PROP_UK1 ON nonEPR-DB.SBMO.VENDOR_ITEM_PROP (  TENANT_ID ASC  , VENDOR_ID ASC  , DRUG_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE UNIQUE NONCLUSTERED INDEX VENDOR_PO_CREATE_DAYS_UK1 ON nonEPR-DB.SBMO.VENDOR_PO_CREATE_DAYS (  TENANT_ID ASC  , VENDOR_ID ASC  , DAY_OF_WEEK ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX VENDOR_PROP_PK ON nonEPR-DB.SBMO.VENDOR_PROP (  TENANT_ID ASC  , ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX VISUALLY_IMPAIRED_DETAILS_IX1 ON nonEPR-DB.SBMO.VISUALLY_IMPAIRED_DETAILS (  TENANT_ID ASC  , RX_CORE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE NONCLUSTERED INDEX VISUALLY_IMPAIRED_DETAILS_IX2 ON nonEPR-DB.SBMO.VISUALLY_IMPAIRED_DETAILS (  TENANT_ID ASC  , RX_CORE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

;

;

CREATE UNIQUE CLUSTERED INDEX PK___PKG_Fil__9DF992D7A8C77666 ON nonEPR-DB.SBMO._PKG_FileToTaskMap (  session_id ASC  , FILE_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK___PKG_Pkg__C2E2A8206CA52954 ON nonEPR-DB.SBMO._PKG_PkgState (  session_id ASC  , property_name ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK___PKG_Tas__8297E8CE1142401A ON nonEPR-DB.SBMO._PKG_TaskToValueCache (  session_id ASC  , TASK_VERSION ASC  , SOURCE ASC  , META_TAG ASC  , VALUE_INDEX ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK___PKG_Val__F284A831C9BE7CE1 ON nonEPR-DB.SBMO._PKG_ValueToTaskCache (  session_id ASC  , VALUE_DATA ASC  , SOURCE ASC  , META_TAG ASC  , TASK_INDEX ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK__partitio__526422BD3819D0F4 ON nonEPR-DB.SBMO.partition_mapping (  table_name ASC  , partition_name ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK__pdx_sche__9ECDDCF8AFD0F2AF ON nonEPR-DB.SBMO.pdx_schema_updater_helper_coldata (  session_id ASC  , col_key ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];

CREATE UNIQUE CLUSTERED INDEX PK__pdx_sche__69B13FDC013473E6 ON nonEPR-DB.SBMO.pdx_schema_updater_helper_debug_context (  session_id ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ];