CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.ADDRESSES
	FOR SBMO_MEIJER.ADDRESSES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.ADJUSTMENT_CODES
	FOR SBMO_MEIJER.ADJUSTMENT_CODES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.ADJUSTMENT_GROUP
	FOR SBMO_MEIJER.ADJUSTMENT_GROUP
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.AUDIT_LOG
	FOR SBMO_MEIJER.AUDIT_LOG
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.BIN_UPC_LINK
	FOR SBMO_MEIJER.BIN_UPC_LINK
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.CARRIER
	FOR SBMO_MEIJER.CARRIER
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.CF_SEC_CHAIN
	FOR SBMO_MEIJER.CF_SEC_CHAIN
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.CF_SEC_STORE
	FOR SBMO_MEIJER.CF_SEC_STORE
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.CHAINS
	FOR SBMO_MEIJER.CHAINS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.CHARGE_PAYMENT_INFO
	FOR SBMO_MEIJER.CHARGE_PAYMENT_INFO
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.CONTACTS
	FOR SBMO_MEIJER.CONTACTS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.CUSTOM_SCHEDULED_TASK
	FOR SBMO_MEIJER.CUSTOM_SCHEDULED_TASK
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.DAILY_SCHEDULED_TASKS
	FOR SBMO_MEIJER.DAILY_SCHEDULED_TASKS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.DISPENSER_LOCATION
	FOR SBMO_MEIJER.DISPENSER_LOCATION
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.DISPENSERS
	FOR SBMO_MEIJER.DISPENSERS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.DRUG_ORDER_PRODUCT_VERIFY
	FOR SBMO_MEIJER.DRUG_ORDER_PRODUCT_VERIFY
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.DRUG_ORDERS
	FOR SBMO_MEIJER.DRUG_ORDERS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.DRUGS
	FOR SBMO_MEIJER.DRUGS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.ENTITIES
	FOR SBMO_MEIJER.ENTITIES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.FACILITIES
	FOR SBMO_MEIJER.FACILITIES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.FORMULARY
	FOR SBMO_MEIJER.FORMULARY
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.FORMULARY_REORDER
	FOR SBMO_MEIJER.FORMULARY_REORDER
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.INVENTORY
	FOR SBMO_MEIJER.INVENTORY
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.INVENTORY_AUDIT
	FOR SBMO_MEIJER.INVENTORY_AUDIT
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.INVENTORY_DATE
	FOR SBMO_MEIJER.INVENTORY_DATE
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.ITEM_LOCATION
	FOR SBMO_MEIJER.ITEM_LOCATION
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.LABEL_IMAGES
	FOR SBMO_MEIJER.LABEL_IMAGES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.LOCATION
	FOR SBMO_MEIJER.LOCATION
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.MASTER_PRODUCT_PO_VERIFY
	FOR SBMO_MEIJER.MASTER_PRODUCT_PO_VERIFY
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.MESSAGE_LOG
	FOR SBMO_MEIJER.MESSAGE_LOG
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.MONTHLY_SCHEDULED_TASKS
	FOR SBMO_MEIJER.MONTHLY_SCHEDULED_TASKS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.ONCE_SCHEDULED_TASKS
	FOR SBMO_MEIJER.ONCE_SCHEDULED_TASKS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.ORDERS
	FOR SBMO_MEIJER.ORDERS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.PHONE_ADDRESS_OWNERS
	FOR SBMO_MEIJER.PHONE_ADDRESS_OWNERS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.PHONES
	FOR SBMO_MEIJER.PHONES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.PRIORITY_CHANGE_ALERTS
	FOR SBMO_MEIJER.PRIORITY_CHANGE_ALERTS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.PURCHASE_ORDER
	FOR SBMO_MEIJER.PURCHASE_ORDER
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.PURCHASE_ORDER_GROUP
	FOR SBMO_MEIJER.PURCHASE_ORDER_GROUP
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.REGION
	FOR SBMO_MEIJER.REGION
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.REPORT_REQUEST
	FOR SBMO_MEIJER.REPORT_REQUEST
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.REPORT_REQUEST_PARAMETER
	FOR SBMO_MEIJER.REPORT_REQUEST_PARAMETER
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RETAIL_COST
	FOR SBMO_MEIJER.RETAIL_COST
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RETURN_AND_ADJUSTMENT
	FOR SBMO_MEIJER.RETURN_AND_ADJUSTMENT
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_CORES
	FOR SBMO_MEIJER.RX_CORES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_CORES_MIN_DATE
	FOR SBMO_MEIJER.RX_CORES_MIN_DATE
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_DETAILS
	FOR SBMO_MEIJER.RX_DETAILS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_DOCUMENTS
	FOR SBMO_MEIJER.RX_DOCUMENTS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_LOTS
	FOR SBMO_MEIJER.RX_LOTS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_PATSTORES
	FOR SBMO_MEIJER.RX_PATSTORES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_PRINT_CHR
	FOR SBMO_MEIJER.RX_PRINT_CHR
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_PRINT_INFO
	FOR SBMO_MEIJER.RX_PRINT_INFO
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_REQUEST_ERROR
	FOR SBMO_MEIJER.RX_REQUEST_ERROR
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_SHIPPING_PACKAGES
	FOR SBMO_MEIJER.RX_SHIPPING_PACKAGES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_STATE_TRANSITION
	FOR SBMO_MEIJER.RX_STATE_TRANSITION
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_TP_INFO
	FOR SBMO_MEIJER.RX_TP_INFO
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_VIAL_INFOS
	FOR SBMO_MEIJER.RX_VIAL_INFOS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_WARNING_LABEL_CODES
	FOR SBMO_MEIJER.RX_WARNING_LABEL_CODES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.RX_WARNING_LABELS
	FOR SBMO_MEIJER.RX_WARNING_LABELS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.SCHEDULED_TASKS
	FOR SBMO_MEIJER.SCHEDULED_TASKS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.SHIP_ITEMS
	FOR SBMO_MEIJER.SHIP_ITEMS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.SHIPMENT
	FOR SBMO_MEIJER.SHIPMENT
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.STORE_SHIP_VIA
	FOR SBMO_MEIJER.STORE_SHIP_VIA
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.STORE_VENDOR_ACCOUNT
	FOR SBMO_MEIJER.STORE_VENDOR_ACCOUNT
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.STORES
	FOR SBMO_MEIJER.STORES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.SYSTEM_MESSAGES
	FOR SBMO_MEIJER.SYSTEM_MESSAGES
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.TENANTS
	FOR SBMO_MEIJER.TENANTS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.VENDOR
	FOR SBMO_MEIJER.VENDOR
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.VENDOR_ITEM_PROP
	FOR SBMO_MEIJER.VENDOR_ITEM_PROP
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.VENDOR_PO_CREATE_DAYS
	FOR SBMO_MEIJER.VENDOR_PO_CREATE_DAYS
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.VENDOR_PROP
	FOR SBMO_MEIJER.VENDOR_PROP
/
CREATE OR REPLACE SYNONYM SBMO_MEIJER_RPT.WEEKLY_SCHEDULED_TASKS
	FOR SBMO_MEIJER.WEEKLY_SCHEDULED_TASKS
/
