-- BATCH 6 INDEXES
-- ----------------------------------------------------------------------------

CREATE INDEX [CHARGE_PAYMENT_INFO_IX1] ON [SBMO].[CHARGE_PAYMENT_INFO] ([TENANT_ID], [ORDER_ID]);
CREATE INDEX [DRUG_ORDER_PRODUCT_VERIFY_IX1] ON [SBMO].[DRUG_ORDER_PRODUCT_VERIFY] ([TENANT_ID], [DRUG_ORDERS_ID]);
CREATE INDEX [RETURN_AND_ADJUSTMENT_IX2] ON [SBMO].[RETURN_AND_ADJUSTMENT] ([TENANT_ID], [ADJUSTMENT_CODE_ID]);
CREATE INDEX [RX_CORES_IX1] ON [SBMO].[RX_CORES] ([TENANT_ID], [ADDED_DATE], [STATUS]);
