-- BATCH 5 INDEXES
-- ----------------------------------------------------------------------------

CREATE INDEX [CF_SEC_STORE_IX2] ON [SBMO].[CF_SEC_STORE] ([TENANT_ID], [CHAIN_ID]);
CREATE INDEX [DRUG_ORDERS_IX2] ON [SBMO].[DRUG_ORDERS] ([TENANT_ID], [FORMULARY_ID]);
CREATE INDEX [ITEM_LOCATION_IX2] ON [SBMO].[ITEM_LOCATION] ([TENANT_ID], [FORMULARY_ID]);
CREATE INDEX [MASTER_PRODUCT_PO_VERIFY_IX1] ON [SBMO].[MASTER_PRODUCT_PO_VERIFY] ([TENANT_ID], [PURCHASE_ORDER_ID]);
CREATE INDEX [MESSAGE_LOG_IX2] ON [SBMO].[MESSAGE_LOG] ([TENANT_ID], [STORE_ID]);
CREATE INDEX [ORDERS_IX1] ON [SBMO].[ORDERS] ([TENANT_ID], [GROUPING_CODE]);
CREATE INDEX [PRIORITY_CHANGE_ALERTS_IX1] ON [SBMO].[PRIORITY_CHANGE_ALERTS] ([TENANT_ID]);
CREATE INDEX [STORE_SHIP_VIA_IX2] ON [SBMO].[STORE_SHIP_VIA] ([TENANT_ID], [STORE_ID]);
CREATE INDEX [STORE_VENDOR_ACCOUNT_IX2] ON [SBMO].[STORE_VENDOR_ACCOUNT] ([TENANT_ID], [STORE_ID]);
