-- BATCH 0 INDEXES
-- ----------------------------------------------------------------------------

CREATE UNIQUE INDEX [ADJUSTMENT_CODES_PK] ON [SBMO].[ADJUSTMENT_CODES] ([ID]);
CREATE UNIQUE INDEX [AUDIT_DBU_LOG_PK] ON [SBMO].[AUDIT_DBU_LOG] ([ID]);
CREATE UNIQUE INDEX [DRUGS_PK] ON [SBMO].[DRUGS] ([ID]);
CREATE UNIQUE INDEX [MUTEX_PK] ON [SBMO].[MUTEX] ([NAME]);
CREATE UNIQUE INDEX [SQL_HISTORY_PK] ON [SBMO].[PARTITION_SQL_HISTORY] ([ID]);
CREATE UNIQUE INDEX [PDX_DBA_APPLIED_PK] ON [SBMO].[PDX_DBA_APPLIED] ([TASK_NAME]);
CREATE UNIQUE INDEX [PDX_SCHEMA_CONFIG_PK] ON [SBMO].[PDX_SCHEMA_CONFIG] ([KEY]);
CREATE UNIQUE INDEX [PDX_SCHEMA_FILE_HASH_PK] ON [SBMO].[PDX_SCHEMA_FILE_HASH] ([FILE_NAME], [FILE_SOURCE]);
CREATE UNIQUE INDEX [PDX_SCHEMA_FILE_TASKVER_PK] ON [SBMO].[PDX_SCHEMA_FILE_TASKVER] ([FILE_NAME]);
CREATE UNIQUE INDEX [PDX_SCHEMA_MAPPING_PK] ON [SBMO].[PDX_SCHEMA_MAPPING] ([SEARCH]);
CREATE UNIQUE INDEX [PDX_SCHEMA_PRIV_DEFAULT_PK] ON [SBMO].[PDX_SCHEMA_PRIV_DEFAULT] ([GRANTEE], [OBJECT_TYPE], [PRIVILEGE]);
CREATE UNIQUE INDEX [PDX_SCHEMA_PRIV_EXCEPTION_PK] ON [SBMO].[PDX_SCHEMA_PRIV_EXCEPTION] ([GRANTEE], [OBJECT_TYPE], [OBJECT_NAME], [PRIVILEGE]);
CREATE INDEX [PDX_SCHEMA_TASKVER_META_IX1] ON [SBMO].[PDX_SCHEMA_TASKVER_META] ([META_TAG], [TASK_SOURCE], [TASK_VERSION]);
CREATE UNIQUE INDEX [PDX_SCHEMA_UPDATER_MANIFEST_PK] ON [SBMO].[PDX_SCHEMA_UPDATER_MANIFEST] ([VERSION]);
CREATE UNIQUE INDEX [PDX_SCHEMA_UPDATER_SQL_PK] ON [SBMO].[PDX_SCHEMA_UPDATER_SQL] ([FILE_NAME]);
CREATE INDEX [PDX_SCHEMA_UPD_HLPR_DBG_H_IX1] ON [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_H] ([DEBUG_TIMESTAMP]);
CREATE UNIQUE INDEX [PDX_SCHEMA_UPD_PKGCALL_HIST_PK] ON [SBMO].[PDX_SCHEMA_UPD_PKGCALL_HIST] ([ID]);
CREATE INDEX [PRESTATS_INVENTORY] ON [SBMO].[PRESTATS_INVENTORY] ([STATID], [TYPE], [C5], [C1], [C2], [C3], [C4], [VERSION]);
CREATE INDEX [PRESTATS_ORDERS] ON [SBMO].[PRESTATS_ORDERS] ([STATID], [TYPE], [C5], [C1], [C2], [C3], [C4], [VERSION]);
CREATE INDEX [PRESTATS_RX_CORES] ON [SBMO].[PRESTATS_RX_CORES] ([STATID], [TYPE], [C5], [C1], [C2], [C3], [C4], [VERSION]);
CREATE UNIQUE INDEX [PURGE_CONFIG_SETTINGS_PK] ON [SBMO].[PURGE_CONFIG_SETTINGS] ([NAME]);
CREATE UNIQUE INDEX [PURGE_ERROR_LOG_PK] ON [SBMO].[PURGE_ERROR_LOG] ([ID]);
CREATE UNIQUE INDEX [PURGE_TABLES_PK] ON [SBMO].[PURGE_TABLES] ([TABLE_NAME]);
CREATE UNIQUE INDEX [QRTZ_CALENDARS_PK] ON [SBMO].[QRTZ_CALENDARS] ([SCHED_NAME], [CALENDAR_NAME]);
CREATE INDEX [IDX_QRTZ_FT_TRIG_NM_GP] ON [SBMO].[QRTZ_FIRED_TRIGGERS] ([TRIGGER_NAME], [TRIGGER_GROUP]);
CREATE INDEX [QRTZ_JOB_DETAILS_IX1] ON [SBMO].[QRTZ_JOB_DETAILS] ([SCHED_NAME], [REQUESTS_RECOVERY]);
CREATE UNIQUE INDEX [QRTZ_SCHEDULER_STATE_PK] ON [SBMO].[QRTZ_SCHEDULER_STATE] ([SCHED_NAME], [INSTANCE_NAME]);
CREATE UNIQUE INDEX [SBMO_PROPERTIES_PK] ON [SBMO].[SBMO_PROPERTIES] ([ID]);
CREATE UNIQUE INDEX [SCHEMA_UPDATER_MANIFEST_PK] ON [SBMO].[SCHEMA_UPDATER_MANIFEST] ([FILE_NAME]);
CREATE UNIQUE INDEX [SCHEMA_UPDATER_SQL_PK] ON [SBMO].[SCHEMA_UPDATER_SQL] ([FILE_NAME]);
CREATE INDEX [STAT_EXPORT] ON [SBMO].[STAT_EXPORT] ([STATID], [TYPE], [C5], [C1], [C2], [C3], [C4], [VERSION]);
CREATE UNIQUE INDEX [TENANTS_PK] ON [SBMO].[TENANTS] ([ID]);
CREATE UNIQUE INDEX [USER_AUDIT_LOG_PK] ON [SBMO].[USER_AUDIT_LOG] ([ID]);
