CREATE TABLE DIB.AGFILE
( 
	AG CHAR(3) NOT NULL,
	ACLASS VARCHAR2(25),
	CSC_0 CHAR(3),
	CSC_1 CHAR(3),
	CSC_2 CHAR(3),
	CSC_3 CHAR(3),
	CSC_4 CHAR(3),
	CSC_5 CHAR(3),
	CR CHAR(1)
)
/
CREATE TABLE DIB.MMW_ADE_COM
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	TEXTID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_ADE_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SEVERITYCODE VARCHAR2(2) NOT NULL,
	ONSETCODE VARCHAR2(2) NOT NULL,
	INCIDENCECODE VARCHAR2(2) NOT NULL,
	DOCLEVELCODE VARCHAR2(2) NOT NULL,
	TYPECODE VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB.MMW_ADE_SPECCOND
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SPECCONDID NUMBER(38, 0) NOT NULL,
	INCIDENCECODE VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB.MMW_CLS_AHFS
( 
	CLASSID VARCHAR2(6) NOT NULL,
	DESCDISPLAY VARCHAR2(65) NOT NULL,
	DESCSEARCH VARCHAR2(65) NOT NULL,
	DESCPHONETIC VARCHAR2(65) NOT NULL,
	PARENTCLASSID VARCHAR2(6),
	HASCHILDRENIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_CLS_AHFSDRUG
( 
	CLASSID VARCHAR2(6) NOT NULL,
	DRUGTYPE NUMBER(38, 0) NOT NULL,
	DRUGID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_CLS_GPI
( 
	CLASSID VARCHAR2(6) NOT NULL,
	DESCDISPLAY VARCHAR2(65) NOT NULL,
	DESCSEARCH VARCHAR2(65) NOT NULL,
	DESCPHONETIC VARCHAR2(65) NOT NULL,
	PARENTCLASSID VARCHAR2(6),
	HASCHILDRENIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_CLS_GPIDRUG
( 
	CLASSID VARCHAR2(6) NOT NULL,
	DRUGTYPE NUMBER(38, 0) NOT NULL,
	DRUGID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_CM_DISPLINK
( 
	DDID NUMBER(38, 0) NOT NULL,
	CMID VARCHAR2(3) NOT NULL,
	PRIORITY NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_CM_PACKLINK
( 
	PPID VARCHAR2(20) NOT NULL,
	CMID VARCHAR2(3) NOT NULL,
	PRIORITY NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_CM_TEXT
( 
	VERSIONCODE VARCHAR2(10) NOT NULL,
	CMID VARCHAR2(3) NOT NULL,
	PROFMSG1 VARCHAR2(34),
	PROFMSG2 VARCHAR2(34),
	PATMSG1 VARCHAR2(25),
	PATMSG2 VARCHAR2(25)
)
/
CREATE TABLE DIB.MMW_DCK_COM
( 
	GPI VARCHAR2(14) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	EFFECTCODE VARCHAR2(2) NOT NULL,
	COMMENTCODE VARCHAR2(3) NOT NULL
)
/
CREATE TABLE DIB.MMW_DCK_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	DOSEFORMLOW NUMBER(6, 2) NOT NULL,
	DOSEFORMHIGH NUMBER(6, 2) NOT NULL,
	DOSEFORMUSUAL NUMBER(6, 2),
	SINGLEDOSEHIGH NUMBER(6, 2),
	DURATIONLOW NUMBER(38, 0) NOT NULL,
	DURATIONHIGH NUMBER(38, 0),
	DURATIONUSUAL NUMBER(38, 0),
	REFERENCECODE VARCHAR2(3) NOT NULL
)
/
CREATE TABLE DIB.MMW_DDA_AUNIT
( 
	AUNITID NUMBER(38, 0) NOT NULL,
	UNITID NUMBER(38, 0) NOT NULL,
	ALTDESCRIPTION VARCHAR2(50) NOT NULL
)
/
CREATE TABLE DIB.MMW_DDA_DOSEFORGPI
( 
	GPI VARCHAR2(14) NOT NULL,
	DOSEID VARCHAR2(10) NOT NULL,
	PROFILEID VARCHAR2(10) NOT NULL,
	ROUTEID NUMBER(38, 0) NOT NULL,
	DOSETYPECODE VARCHAR2(2) NOT NULL,
	INDICATIONID NUMBER(38, 0) NOT NULL,
	SPECCONDID NUMBER(38, 0) NOT NULL,
	AGETYPECODE VARCHAR2(2) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	ADDAGETYPECODE VARCHAR2(2) NOT NULL,
	ADDAGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	ADDAGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	RENALFUNCTYPECODE VARCHAR2(2) NOT NULL,
	RENALFUNCLOW NUMBER(8, 4) NOT NULL,
	RENALFUNCHIGH NUMBER(8, 4) NOT NULL,
	RENALFUNCUNIT VARCHAR2(2) NOT NULL,
	WEIGHTCATLOW NUMBER(7, 2) NOT NULL,
	WEIGHTCATHIGH NUMBER(7, 2) NOT NULL,
	WEIGHTCATUNIT VARCHAR2(2) NOT NULL,
	HALFLIFELOW NUMBER(5, 2) NOT NULL,
	HALFLIFEHIGH NUMBER(5, 2) NOT NULL,
	HALFLIFEUNIT VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB.MMW_DDA_DOSEROUTECOMPATABILITY
( 
	RTID NUMBER(38, 0) NOT NULL,
	RTABBREV VARCHAR2(3) NOT NULL,
	RTDESCRIPTION VARCHAR2(20) NOT NULL,
	ROUTEID NUMBER(38, 0) NOT NULL,
	ROUTEABBREV VARCHAR2(3) NOT NULL,
	ROUTEDESCRIPTION VARCHAR2(20) NOT NULL
)
/
CREATE TABLE DIB.MMW_DDA_GPI_DOSE
( 
	DOSEID VARCHAR2(10) NOT NULL,
	PROFILEID VARCHAR2(10) NOT NULL,
	GPI VARCHAR2(14) NOT NULL,
	ROUTEID NUMBER(38, 0) NOT NULL,
	DOSETYPECODE VARCHAR2(2) NOT NULL,
	DAILYDOSELOW NUMBER(9, 4) NOT NULL,
	DAILYDOSELOWUNIT NUMBER(38, 0) NOT NULL,
	DAILYDOSEHIGH NUMBER(9, 4) NOT NULL,
	DAILYDOSEHIGHUNIT NUMBER(38, 0) NOT NULL,
	DAILYDOSEFORMLOW NUMBER(9, 4) NOT NULL,
	DAILYDOSEFORMLOWUNIT NUMBER(38, 0) NOT NULL,
	DAILYDOSEFORMHIGH NUMBER(9, 4) NOT NULL,
	DAILYDOSEFORMHIGHUNIT NUMBER(38, 0) NOT NULL,
	MAXDAILYDOSE NUMBER(9, 4) NOT NULL,
	MAXDAILYDOSEUNIT NUMBER(38, 0) NOT NULL,
	MAXDAILYDOSEFORM NUMBER(9, 4) NOT NULL,
	MAXDAILYDOSEFORMUNIT NUMBER(38, 0) NOT NULL,
	MAXSINGLEDOSE NUMBER(9, 4) NOT NULL,
	MAXSINGLEDOSEUNIT NUMBER(38, 0) NOT NULL,
	MAXSINGLEDOSEFORM NUMBER(9, 4) NOT NULL,
	MAXSINGLEDOSEFORMUNIT NUMBER(38, 0) NOT NULL,
	MAXLIFETIMEDOSE NUMBER(9, 4) NOT NULL,
	MAXLIFETIMEDOSEUNIT NUMBER(38, 0) NOT NULL,
	MAXLIFETIMEDOSEFORM NUMBER(9, 4) NOT NULL,
	MAXLIFETIMEDOSEFORMUNIT NUMBER(38, 0) NOT NULL,
	FREQUENCYLOW NUMBER(9, 4) NOT NULL,
	FREQUENCYHIGH NUMBER(9, 4) NOT NULL,
	FREQUENCYMAX NUMBER(9, 4) NOT NULL,
	DURATIONLOW NUMBER(9, 4) NOT NULL,
	DURATIONHIGH NUMBER(9, 4) NOT NULL,
	DURATIONMAX NUMBER(9, 4) NOT NULL,
	HALFLIFELOW NUMBER(5, 2) NOT NULL,
	HALFLIFEHIGH NUMBER(5, 2) NOT NULL,
	HALFLIFEUNIT VARCHAR2(2) NOT NULL,
	HASDOSERECTEXTIND NUMBER(38, 0) NOT NULL,
	HASQUALIFIERTEXTIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_DDA_GPI_DOSE_TEXT
( 
	DOSEID VARCHAR2(10) NOT NULL,
	TYPECODE VARCHAR2(3) NOT NULL,
	LEVELCODE VARCHAR2(2) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	TEXTID NUMBER(38, 0) NOT NULL,
	TEXTGROUPID NUMBER(38, 0)
)
/
CREATE TABLE DIB.MMW_DDA_PATIENT_PROFILE
( 
	PROFILEID VARCHAR2(10) NOT NULL,
	INDICATIONID NUMBER(38, 0) NOT NULL,
	SPECCONDID NUMBER(38, 0) NOT NULL,
	AGETYPECODE VARCHAR2(2) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	ADDAGETYPECODE VARCHAR2(2) NOT NULL,
	ADDAGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	ADDAGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	RENALFUNCTYPECODE VARCHAR2(2) NOT NULL,
	RENALFUNCLOW NUMBER(8, 4) NOT NULL,
	RENALFUNCHIGH NUMBER(8, 4) NOT NULL,
	RENALFUNCUNIT VARCHAR2(2) NOT NULL,
	WEIGHTCATLOW NUMBER(7, 2) NOT NULL,
	WEIGHTCATHIGH NUMBER(7, 2) NOT NULL,
	WEIGHTCATUNIT VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB.MMW_DDA_ROUTE
( 
	ROUTEID NUMBER(38, 0) NOT NULL,
	ABBREV VARCHAR2(3) NOT NULL,
	DESCRIPTION VARCHAR2(50) NOT NULL
)
/
CREATE TABLE DIB.MMW_DDA_TEXT
( 
	TEXTID NUMBER(38, 0) NOT NULL,
	LINENUMBER NUMBER(38, 0) NOT NULL,
	LINETEXT VARCHAR2(140) NOT NULL,
	FORMATCODE VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB.MMW_DDA_UNIT
( 
	UNITID NUMBER(38, 0) NOT NULL,
	UNITDESCRIPTION VARCHAR2(50) NOT NULL,
	TYPECODE VARCHAR2(10) NOT NULL,
	VALIDFORINPUTIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_DDA_UNIT_XREF
( 
	FROMUNITID NUMBER(38, 0) NOT NULL,
	FROMUNITDESCRIPTION VARCHAR2(50) NOT NULL,
	UNITID NUMBER(38, 0) NOT NULL,
	UNITDESCRIPTION VARCHAR2(50) NOT NULL,
	TYPECODE VARCHAR2(2) NOT NULL,
	VALIDFORINPUTIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_DDA_UNITCONVERSION
( 
	UNITTYPE VARCHAR2(2) NOT NULL,
	FROMUNITID NUMBER(38, 0) NOT NULL,
	FROMUNITABBREV VARCHAR2(20) NOT NULL,
	FROMUNITDESC VARCHAR2(80) NOT NULL,
	TOUNITID NUMBER(38, 0) NOT NULL,
	TOUNITABBREV VARCHAR2(20) NOT NULL,
	TOUNITDESC VARCHAR2(80) NOT NULL,
	BSAADJUST VARCHAR2(2),
	WEIGHTADJUST VARCHAR2(2),
	CONVERSIONFACTOR NUMBER(16, 9) NOT NULL,
	UNITTYPEDESC VARCHAR2(100) NOT NULL,
	BSAOPERATION VARCHAR2(1),
	WEIGHTOPERATION VARCHAR2(1)
)
/
CREATE TABLE DIB.MMW_DFA_INT
( 
	DRUGCLASSID VARCHAR2(5) NOT NULL,
	FOODCLASSID VARCHAR2(5) NOT NULL,
	DRUGACTCODE VARCHAR2(1) NOT NULL,
	DRUGDURATION NUMBER(38, 0) NOT NULL,
	FOODDURATION NUMBER(38, 0) NOT NULL,
	DRUGSCHREGIND NUMBER(38, 0) NOT NULL,
	DRUGSCHASNEEDIND NUMBER(38, 0) NOT NULL,
	DRUGSCHSINGLEIND NUMBER(38, 0) NOT NULL,
	FOODSCHREGIND NUMBER(38, 0) NOT NULL,
	FOODSCHASNEEDIND NUMBER(38, 0) NOT NULL,
	FOODSCHSINGLEIND NUMBER(38, 0) NOT NULL,
	ONSETCODE VARCHAR2(1) NOT NULL,
	SEVERITYCODE VARCHAR2(1) NOT NULL,
	DOCLEVELCODE VARCHAR2(1) NOT NULL,
	DRUGCLASSNAME VARCHAR2(75) NOT NULL,
	FOODCLASSNAME VARCHAR2(75) NOT NULL,
	MONOID VARCHAR2(20) NOT NULL,
	ALCOHOLIND NUMBER(38, 0) NOT NULL,
	CLASS1FOODIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_DFA_TEXT
( 
	VERSION VARCHAR2(10) NOT NULL,
	DRUGCLASSID VARCHAR2(5) NOT NULL,
	FOODCLASSID VARCHAR2(5) NOT NULL,
	LINENUMBER NUMBER(38, 0) NOT NULL,
	LINETEXT VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB.MMW_DI_CLASSLINK
( 
	KDC1 VARCHAR2(5) NOT NULL,
	CLASSID VARCHAR2(5) NOT NULL
)
/
CREATE TABLE DIB.MMW_DI_INT
( 
	CLASSID1 VARCHAR2(5) NOT NULL,
	CLASSID2 VARCHAR2(5) NOT NULL,
	ACTCODE1 VARCHAR2(1) NOT NULL,
	ACTCODE2 VARCHAR2(1) NOT NULL,
	DURATION1 NUMBER(38, 0) NOT NULL,
	DURATION2 NUMBER(38, 0) NOT NULL,
	SCHEDREG1IND NUMBER(38, 0) NOT NULL,
	SCHEDASNEEDED1IND NUMBER(38, 0) NOT NULL,
	SCHEDSINGLE1IND NUMBER(38, 0) NOT NULL,
	SCHEDREG2IND NUMBER(38, 0) NOT NULL,
	SCHEDASNEEDED2IND NUMBER(38, 0) NOT NULL,
	SCHEDSINGLE2IND NUMBER(38, 0) NOT NULL,
	ONSETCODE VARCHAR2(1) NOT NULL,
	SEVERITYCODE VARCHAR2(1) NOT NULL,
	DOCLEVELCODE VARCHAR2(1) NOT NULL,
	CLASS1NAME VARCHAR2(75) NOT NULL,
	CLASS2NAME VARCHAR2(75) NOT NULL,
	MONOID VARCHAR2(20) NOT NULL,
	SCREENINGIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_DI_RPIDLINK
( 
	KDC1 VARCHAR2(5) NOT NULL,
	NAMETYPECODE VARCHAR2(1) NOT NULL,
	RPID NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(65),
	ACTCODE VARCHAR2(1)
)
/
CREATE TABLE DIB.MMW_DI_TEXT
( 
	VERSION VARCHAR2(10) NOT NULL,
	CLASSID1 VARCHAR2(5) NOT NULL,
	CLASSID2 VARCHAR2(5) NOT NULL,
	LINENUMBER NUMBER(38, 0) NOT NULL,
	LINETEXT VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_DISP
( 
	DDID NUMBER(38, 0) NOT NULL,
	DESCDISPLAY VARCHAR2(125) NOT NULL,
	DESCSEARCH VARCHAR2(125) NOT NULL,
	DESCPHONETIC VARCHAR2(125) NOT NULL,
	RTID NUMBER(38, 0) NOT NULL,
	DFID NUMBER(38, 0) NOT NULL,
	STRENGTH VARCHAR2(15),
	STRENGTHUNIT VARCHAR2(10),
	RPID NUMBER(38, 0) NOT NULL,
	PNID NUMBER(38, 0) NOT NULL,
	BIOEQUIVCODE VARCHAR2(1) NOT NULL,
	CTRLSUBSTANCECODE VARCHAR2(1) NOT NULL,
	EFFICACYCODE VARCHAR2(1),
	RXOTCCODE VARCHAR2(1) NOT NULL,
	GENERICCODE VARCHAR2(1) NOT NULL,
	NAMETYPECODE VARCHAR2(1) NOT NULL,
	NAMESOURCECODE VARCHAR2(1) NOT NULL,
	GPI VARCHAR2(14),
	PARTIALGPIIND NUMBER(38, 0) NOT NULL,
	KDC VARCHAR2(10),
	KDCFLAG VARCHAR2(1),
	ACTCODE VARCHAR2(1),
	SINGLEINGRIND NUMBER(38, 0) NOT NULL,
	MEDDEVIND NUMBER(38, 0) NOT NULL,
	HASPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASEQVPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASIMAGEIND NUMBER(38, 0) NOT NULL,
	CMMULTIND NUMBER(38, 0) NOT NULL,
	DOSECHEKUNIT VARCHAR2(20),
	HISTORICALIND NUMBER(38, 0) NOT NULL,
	OBSOLETEDATE VARCHAR2(8),
	SCREENCLEANADE NUMBER(38, 0),
	SCREENCLEANPRC NUMBER(38, 0),
	SCREENCLEANDFA NUMBER(38, 0),
	SCREENCLEANDI NUMBER(38, 0),
	SCREENCLEANDC NUMBER(38, 0),
	SCREENCLEANDDA NUMBER(38, 0)
)
/
CREATE TABLE DIB.MMW_DRUG_DISP_IMG
( 
	DDID NUMBER(38, 0) NOT NULL,
	LABELERID VARCHAR2(5) NOT NULL,
	IMAGEFILENAME VARCHAR2(8) NOT NULL,
	REFREPACKCODE VARCHAR2(1) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_DISP_LBLR
( 
	DDID NUMBER(38, 0) NOT NULL,
	LABELERID VARCHAR2(5) NOT NULL,
	REFREPACKCODE VARCHAR2(1) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_DOSEFORM
( 
	DFID NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(30) NOT NULL,
	ABBREV VARCHAR2(4) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_GPI
( 
	GPI VARCHAR2(14) NOT NULL,
	DESCRIPTION VARCHAR2(60),
	GENERICDDID NUMBER(38, 0),
	DOSECHEKUNIT VARCHAR2(20),
	DDASINGLEROUTE NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_GPILINK
( 
	DRUGID VARCHAR2(16) NOT NULL,
	GPI VARCHAR2(14) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_KDC
( 
	KDC1 VARCHAR2(5) NOT NULL,
	DESCRIPTION VARCHAR2(50) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_KDCLINK
( 
	DRUGID VARCHAR2(12) NOT NULL,
	KDC1 VARCHAR2(5) NOT NULL,
	RPID NUMBER(38, 0)
)
/
CREATE TABLE DIB.MMW_DRUG_LABELER
( 
	LABELERID VARCHAR2(5) NOT NULL,
	NAMEFULL VARCHAR2(30) NOT NULL,
	NAMEABBREV VARCHAR2(10) NOT NULL,
	TYPECODE VARCHAR2(1) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_NAME
( 
	PNID NUMBER(38, 0) NOT NULL,
	DESCDISPLAY VARCHAR2(35) NOT NULL,
	DESCSEARCH VARCHAR2(35) NOT NULL,
	DESCPHONETIC VARCHAR2(35) NOT NULL,
	RPIDUNIQUE NUMBER(38, 0),
	DDIDUNIQUE NUMBER(38, 0),
	NAMETYPECODE VARCHAR2(1) NOT NULL,
	RXOTCCODE VARCHAR2(1),
	SINGLEINGRIND NUMBER(38, 0) NOT NULL,
	MEDDEVIND NUMBER(38, 0) NOT NULL,
	HASPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASEQVPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASKDCIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_PACK
( 
	PPID VARCHAR2(20) NOT NULL,
	DDID NUMBER(38, 0) NOT NULL,
	RTID NUMBER(38, 0) NOT NULL,
	DFID NUMBER(38, 0) NOT NULL,
	STRENGTH VARCHAR2(15),
	STRENGTHUNIT VARCHAR2(15),
	TEECODE VARCHAR2(2) NOT NULL,
	DEACLASSCODE VARCHAR2(1),
	DESICODE VARCHAR2(1),
	RXOTCCODE VARCHAR2(1) NOT NULL,
	GPPC VARCHAR2(8) NOT NULL,
	OLDPPID VARCHAR2(20),
	NEWPPID VARCHAR2(20),
	REPACKIND NUMBER(38, 0) NOT NULL,
	IDFORMATCODE VARCHAR2(1) NOT NULL,
	THIRDPRTYRESTRCODE VARCHAR2(1),
	KDC VARCHAR2(10),
	LABELERID VARCHAR2(5) NOT NULL,
	MULTISOURCECODE VARCHAR2(1) NOT NULL,
	NAMETYPECODE VARCHAR2(1) NOT NULL,
	INNERPACKIND NUMBER(38, 0) NOT NULL,
	CLINICPACKIND NUMBER(38, 0) NOT NULL,
	REIMBURSEMENTCODE VARCHAR2(1) NOT NULL,
	PRICESPREADCODE VARCHAR2(1) NOT NULL,
	GPI VARCHAR2(14) NOT NULL,
	PACKSIZE NUMBER(8, 3) NOT NULL,
	PACKSIZEUNITCODE VARCHAR2(2) NOT NULL,
	PACKQUANTITY NUMBER(38, 0) NOT NULL,
	UNITDOSECODE VARCHAR2(1),
	PACKDESCCODE VARCHAR2(2) NOT NULL,
	NDC VARCHAR2(13) NOT NULL,
	GENIDTYPECODE VARCHAR2(1) NOT NULL,
	GENIDNUMBER VARCHAR2(9) NOT NULL,
	AHFSTHERACLASSCODE VARCHAR2(6) NOT NULL,
	LOCALSYSTEMICCODE VARCHAR2(1) NOT NULL,
	MAINTDRUGIND NUMBER(38, 0) NOT NULL,
	FORMTYPECODE VARCHAR2(1) NOT NULL,
	DOLLARRANKCODE VARCHAR2(1) NOT NULL,
	RXRANKCODE VARCHAR2(1) NOT NULL,
	INTEXTCODE VARCHAR2(1) NOT NULL,
	SINGLECOMBCODE VARCHAR2(1) NOT NULL,
	STORAGECONDCODE VARCHAR2(1),
	OLDPPIDEFFDATE VARCHAR2(8),
	NEWPPIDEFFDATE VARCHAR2(8),
	PRODUCTNAME VARCHAR2(25) NOT NULL,
	PRODUCTNAMEEXT VARCHAR2(35),
	TOTALPACKAGEQTY NUMBER(12, 3) NOT NULL,
	CURRIMAGEFILENAME VARCHAR2(8),
	ACTCODE VARCHAR2(1),
	SINGLEINGRIND NUMBER(38, 0) NOT NULL,
	MEDDEVIND NUMBER(38, 0) NOT NULL,
	INACTIVEDATE VARCHAR2(8),
	PRODUCTDESCABBREV VARCHAR2(25) NOT NULL,
	DOSECHEKUNIT VARCHAR2(20),
	ITEMSTATUS VARCHAR2(1) NOT NULL,
	SCREENCLEANADE NUMBER(38, 0),
	SCREENCLEANPRC NUMBER(38, 0),
	SCREENCLEANDFA NUMBER(38, 0),
	SCREENCLEANDI NUMBER(38, 0),
	SCREENCLEANDC NUMBER(38, 0),
	SCREENCLEANDDA NUMBER(38, 0),
	PARTIALGPIIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_PACK_MOD
( 
	PPID VARCHAR2(20) NOT NULL,
	MODID VARCHAR2(6) NOT NULL,
	TYPECODE VARCHAR2(2) NOT NULL,
	CATCODE VARCHAR2(4) NOT NULL,
	DESCRIPTION VARCHAR2(25) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_ROUTE
( 
	RTID NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(30),
	ABBREV VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB.MMW_DRUG_ROUTED
( 
	RPID NUMBER(38, 0) NOT NULL,
	DESCDISPLAY VARCHAR2(65) NOT NULL,
	DESCSEARCH VARCHAR2(65) NOT NULL,
	DESCPHONETIC VARCHAR2(65) NOT NULL,
	RTID NUMBER(38, 0) NOT NULL,
	PNID NUMBER(38, 0) NOT NULL,
	DDIDUNIQUE NUMBER(38, 0),
	NAMETYPECODE VARCHAR2(1) NOT NULL,
	RXOTCCODE VARCHAR2(1),
	ACTCODE VARCHAR2(1),
	SINGLEINGRIND NUMBER(38, 0) NOT NULL,
	MEDDEVIND NUMBER(38, 0) NOT NULL,
	HASPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASEQVPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASGPIIND NUMBER(38, 0) NOT NULL,
	HASKDCIND NUMBER(38, 0) NOT NULL,
	SCREENCLEANDFA NUMBER(38, 0),
	SCREENCLEANDI NUMBER(38, 0)
)
/
CREATE TABLE DIB.MMW_DUP_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	DTCID VARCHAR2(8) NOT NULL
)
/
CREATE TABLE DIB.MMW_DUP_TEXT
( 
	DTCID VARCHAR2(8) NOT NULL,
	DESCRIPTION VARCHAR2(40) NOT NULL,
	POTENTIALABUSECODE VARCHAR2(1) NOT NULL,
	DUPALLOWANCE NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_FC_DRUGLINK
( 
	DRUGID VARCHAR2(20) NOT NULL,
	ELEMENTID NUMBER(38, 0) NOT NULL,
	DOCUMENTCODE VARCHAR2(10) NOT NULL
)
/
CREATE TABLE DIB.MMW_FC_ELEMENT
( 
	ELEMENTID NUMBER(38, 0) NOT NULL,
	DOCUMENTCODE VARCHAR2(10) NOT NULL,
	PARENTID NUMBER(38, 0) NOT NULL,
	CHILDSEQUENCE NUMBER(38, 0) NOT NULL,
	TAGTYPE VARCHAR2(40) NOT NULL,
	IDATTRIBUTE VARCHAR2(32),
	HASSECTIONSIND NUMBER(38, 0) NOT NULL,
	FILENAME VARCHAR2(30) NOT NULL,
	ELEMENTTITLE VARCHAR2(255) NOT NULL,
	XPATH VARCHAR2(255)
)
/
CREATE TABLE DIB.MMW_FC_SECTION
( 
	SECTIONID NUMBER(38, 0) NOT NULL,
	SECTIONTITLE VARCHAR2(40) NOT NULL,
	XPATH VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB.MMW_FC_SECTIONLINK
( 
	ELEMENTID NUMBER(38, 0) NOT NULL,
	SECTIONID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_IMG
( 
	PPID VARCHAR2(20) NOT NULL,
	STARTDATE VARCHAR2(8) NOT NULL,
	STOPDATE VARCHAR2(8),
	IMAGEFILENAME VARCHAR2(8) NOT NULL
)
/
CREATE TABLE DIB.MMW_IND_COM
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MICROORGANISMID NUMBER(38, 0) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	TEXTID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_IND_COTREAT
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MICROORGANISMID NUMBER(38, 0) NOT NULL,
	COTREATSETID NUMBER(38, 0) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(80) NOT NULL
)
/
CREATE TABLE DIB.MMW_IND_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MICROORGANISMID NUMBER(38, 0) NOT NULL,
	ROLEOFTHERAPYCODE VARCHAR2(2) NOT NULL,
	OUTCOMECODE VARCHAR2(2) NOT NULL,
	TREATMENTRANKCODE VARCHAR2(2) NOT NULL,
	ACCEPTANCELVLCODE VARCHAR2(2) NOT NULL,
	PROXYCODE VARCHAR2(1) NOT NULL,
	PROXYONLYIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_IND_RPID
( 
	MCID NUMBER(38, 0) NOT NULL,
	RPID NUMBER(38, 0) NOT NULL,
	OUTCOMECODE VARCHAR2(2) NOT NULL,
	ACCEPTANCELVLCODE VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB.MMW_IND_SOURCE
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MICROORGANISMID NUMBER(38, 0) NOT NULL,
	SOURCECODE VARCHAR2(2) NOT NULL,
	SOURCEACCEPTCODE VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB.MMW_IPT
( 
	PPID VARCHAR2(20) NOT NULL,
	STARTDATE VARCHAR2(8) NOT NULL,
	IMPRINT1 VARCHAR2(40),
	IMPRINT2 VARCHAR2(40),
	SHAPEID NUMBER(38, 0),
	FLAVORCODE VARCHAR2(4),
	FORMCODE VARCHAR2(4) NOT NULL,
	COATINGCODE VARCHAR2(4),
	SCORINGCODE VARCHAR2(4),
	CLARITYCODE VARCHAR2(4),
	DESCSEARCH VARCHAR2(85) NOT NULL,
	CURRENTIMPRINTIND NUMBER(38, 0) NOT NULL,
	COLORPALETTEIDLIST VARCHAR2(32)
)
/
CREATE TABLE DIB.MMW_IPT_COLOR
( 
	COLORID NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(30) NOT NULL,
	PALETTEID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_IPT_COLORPAL
( 
	PALETTEID NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(30) NOT NULL
)
/
CREATE TABLE DIB.MMW_IPT_DESC
( 
	PPID VARCHAR2(20) NOT NULL,
	STARTDATE VARCHAR2(8) NOT NULL,
	TEXTID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_IPT_DESCCLR
( 
	PPID VARCHAR2(20) NOT NULL,
	STARTDATE VARCHAR2(8) NOT NULL,
	COLORID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_IPT_DESCTEXT
( 
	TEXTID NUMBER(38, 0) NOT NULL,
	LINENUMBER NUMBER(38, 0) NOT NULL,
	LINETEXT VARCHAR2(70) NOT NULL
)
/
CREATE TABLE DIB.MMW_IPT_SHAPE
( 
	SHAPEID NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(30) NOT NULL,
	PALETTEID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_IPT_SHAPEPAL
( 
	PALETTEID NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(30) NOT NULL
)
/
CREATE TABLE DIB.MMW_LIB_CODEDEF
( 
	CODETYPE NUMBER(38, 0) NOT NULL,
	CODEVALUE VARCHAR2(10) NOT NULL,
	DESCRIPTION VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB.MMW_LIB_DISCLAIMER
( 
	VERSIONCODE VARCHAR2(10) NOT NULL,
	CATEGORYCODE VARCHAR2(10) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	SECTIONCODE VARCHAR2(1) NOT NULL,
	FORMATCODE VARCHAR2(1) NOT NULL,
	LINETEXT VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB.MMW_LIB_VERSION
( 
	VERSIONKEY NUMBER(38, 0) NOT NULL,
	DBVERSION VARCHAR2(5) NOT NULL,
	BUILDVERSION VARCHAR2(5) NOT NULL,
	FREQUENCY VARCHAR2(1) NOT NULL,
	ISSUEDATE VARCHAR2(8) NOT NULL,
	VERSIONCOMMENT VARCHAR2(80) NOT NULL
)
/
CREATE TABLE DIB.MMW_MED
( 
	MCID NUMBER(38, 0) NOT NULL,
	PRIMARYPROFNAME VARCHAR2(58) NOT NULL,
	PRIMARYPATNAME VARCHAR2(58) NOT NULL,
	TYPECODE VARCHAR2(2) NOT NULL,
	CLASSONLYIND NUMBER(38, 0) NOT NULL,
	GENDERCODE VARCHAR2(1) NOT NULL,
	PREGNANCYIND NUMBER(38, 0) NOT NULL,
	LACTATIONIND NUMBER(38, 0) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	DURATIONCODE VARCHAR2(2) NOT NULL,
	HASCHILDRENIND NUMBER(38, 0) NOT NULL,
	DRUGSTOTREATIND NUMBER(38, 0) NOT NULL,
	DRUGSTOAVOIDIND NUMBER(38, 0) NOT NULL,
	DRUGSTHATCAUSEIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_MED_CIT
( 
	CITATIONID NUMBER(38, 0) NOT NULL,
	CITATIONTEXT VARCHAR2(250) NOT NULL
)
/
CREATE TABLE DIB.MMW_MED_EXTVOCAB
( 
	VOCABTYPECODE VARCHAR2(1) NOT NULL,
	EXTVOCABID VARCHAR2(20) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_MED_HIER
( 
	MCID NUMBER(38, 0) NOT NULL,
	PARENTID NUMBER(38, 0) NOT NULL,
	RELATIONTYPECODE VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB.MMW_MED_INTVOCAB
( 
	VOCABTYPECODE VARCHAR2(1) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	EXTVOCABID VARCHAR2(20) NOT NULL
)
/
CREATE TABLE DIB.MMW_MED_LINK
( 
	MCID NUMBER(38, 0) NOT NULL,
	RELATEDMCID NUMBER(38, 0) NOT NULL,
	RELATIONTYPECODE VARCHAR2(2) NOT NULL,
	DIRECTIONCODE VARCHAR2(1) NOT NULL,
	DISTANCE NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_MED_NAME
( 
	MCID NUMBER(38, 0) NOT NULL,
	NAMETYPECODE VARCHAR2(2) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	NAMEDISPLAY VARCHAR2(60) NOT NULL,
	NAMESEARCH VARCHAR2(60) NOT NULL,
	NAMEPHONETIC VARCHAR2(60) NOT NULL
)
/
CREATE TABLE DIB.MMW_MED_TEXT
( 
	TEXTID NUMBER(38, 0) NOT NULL,
	LINENUMBER NUMBER(38, 0) NOT NULL,
	LINETEXT VARCHAR2(140) NOT NULL
)
/
CREATE TABLE DIB.MMW_MED_TEXT_CIT
( 
	TEXTID NUMBER(38, 0) NOT NULL,
	CITATIONID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_MONO_CLSNAME
( 
	CATEGORYCODE VARCHAR2(10) NOT NULL,
	MONOID VARCHAR2(20) NOT NULL,
	CLASS1NAME VARCHAR2(75) NOT NULL,
	CLASS2NAME VARCHAR2(75) NOT NULL,
	CLASS1FOODIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_MONO_TEXT
( 
	VERSIONCODE VARCHAR2(10) NOT NULL,
	CATEGORYCODE VARCHAR2(10) NOT NULL,
	MONOID VARCHAR2(20) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	SECTIONCODE VARCHAR2(1) NOT NULL,
	FORMATCODE VARCHAR2(1) NOT NULL,
	LINETEXT VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB.MMW_PAR_CLASS
( 
	CLASSID VARCHAR2(5) NOT NULL,
	DESCDISPLAY VARCHAR2(75) NOT NULL,
	DESCSEARCH VARCHAR2(75) NOT NULL,
	DESCPHONETIC VARCHAR2(75) NOT NULL,
	CROSSREACTIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_PAR_CLASSLINK
( 
	KDC1 VARCHAR2(5) NOT NULL,
	CLASSID VARCHAR2(5) NOT NULL
)
/
CREATE TABLE DIB.MMW_PAR_DRUGLINK
( 
	ALLERGYID VARCHAR2(12) NOT NULL,
	KDC1 VARCHAR2(5) NOT NULL
)
/
CREATE TABLE DIB.MMW_PAR_INGRLINK
( 
	KDC1 VARCHAR2(5) NOT NULL,
	INGREDKDC1 VARCHAR2(5) NOT NULL
)
/
CREATE TABLE DIB.MMW_PAR_INT
( 
	CLASSID1 VARCHAR2(5) NOT NULL,
	CLASSID2 VARCHAR2(5) NOT NULL,
	SYMPTOMCODE VARCHAR2(6) NOT NULL,
	MONOID VARCHAR2(20),
	SYMRASHIND NUMBER(38, 0) NOT NULL,
	SYMSHOCKIND NUMBER(38, 0) NOT NULL,
	SYMASTHMAIND NUMBER(38, 0) NOT NULL,
	SYMNAUSEAIND NUMBER(38, 0) NOT NULL,
	SYMANEMIAIND NUMBER(38, 0) NOT NULL,
	SYMUNSPECIFIEDIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_PDE_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	VERSIONCODE VARCHAR2(10) NOT NULL,
	MONOID VARCHAR2(20) NOT NULL
)
/
CREATE TABLE DIB.MMW_PRCA_COM
( 
	GPI VARCHAR2(14) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	TEXTID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_PRCA_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MGMTLEVELCODE VARCHAR2(1) NOT NULL,
	ORIGAGELOW NUMBER(38, 0) NOT NULL,
	ORIGAGEHIGH NUMBER(38, 0) NOT NULL,
	ORIGAGEUNITCODE VARCHAR2(1) NOT NULL
)
/
CREATE TABLE DIB.MMW_PRCA_SPECCOND
( 
	GPI VARCHAR2(14) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SPECCONDID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_PRCC_COM
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	TEXTID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_PRCC_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MGMTLEVELCODE VARCHAR2(1) NOT NULL,
	PLACENTTRANSCODE VARCHAR2(1),
	FDARISKFACTORCODE VARCHAR2(1),
	BRIGGSRATINGCODE VARCHAR2(1),
	BRSTFEEDEXCRETCODE VARCHAR2(1),
	BRSTFEEDRATINGCODE VARCHAR2(1),
	BRSTFEEDAAPCODE VARCHAR2(1)
)
/
CREATE TABLE DIB.MMW_PRCC_SPECCOND
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SPECCONDID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_PRI
( 
	PPID VARCHAR2(20) NOT NULL,
	PRICETYPECODE VARCHAR2(2) NOT NULL,
	EFFECTIVEDATE VARCHAR2(8) NOT NULL,
	PRICE NUMBER(12, 6) NOT NULL,
	CURRENTPRICEIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_WL_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	WLID VARCHAR2(6) NOT NULL,
	PRIORITY NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB.MMW_WL_TEXT
( 
	VERSIONCODE VARCHAR2(10) NOT NULL,
	WLID VARCHAR2(6) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	LINETEXT VARCHAR2(100) NOT NULL
)
/
CREATE TABLE DIB.MMW_WL_VENDCODE
( 
	VERSIONCODE VARCHAR2(10) NOT NULL,
	WLID VARCHAR2(6) NOT NULL,
	VENDVERSIONCODE VARCHAR2(3) NOT NULL,
	TEXTCODE VARCHAR2(6) NOT NULL,
	GRAPHICCODE VARCHAR2(6)
)
/
CREATE TABLE DIB.TOP_DRUGS
( 
	DESCSEARCH VARCHAR2(35)
)
/
ALTER TABLE DIB.MMW_ADE_COM ADD CONSTRAINT PKMMWADECOM
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, SEQUENCENUMBER)
/
ALTER TABLE DIB.MMW_ADE_DRUGLINK ADD CONSTRAINT PKMMWADEDRUGLINK
	PRIMARY KEY (GPI, MCID, RESTRICTIONID)
/
ALTER TABLE DIB.MMW_ADE_SPECCOND ADD CONSTRAINT PKMMWADESPECCOND
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, SPECCONDID)
/
ALTER TABLE DIB.MMW_CLS_AHFS ADD CONSTRAINT PKMMWCLSAHFS
	PRIMARY KEY (CLASSID)
/
ALTER TABLE DIB.MMW_CLS_AHFSDRUG ADD CONSTRAINT PKMMWCLSAHFSDRUG
	PRIMARY KEY (CLASSID, DRUGTYPE, DRUGID)
/
ALTER TABLE DIB.MMW_CLS_GPI ADD CONSTRAINT PKMMWCLSGPI
	PRIMARY KEY (CLASSID)
/
ALTER TABLE DIB.MMW_CLS_GPIDRUG ADD CONSTRAINT PKMMWCLSGPIDRUG
	PRIMARY KEY (CLASSID, DRUGTYPE, DRUGID)
/
ALTER TABLE DIB.MMW_CM_DISPLINK ADD CONSTRAINT PKMMWCMDISPLINK
	PRIMARY KEY (DDID, CMID)
/
ALTER TABLE DIB.MMW_CM_PACKLINK ADD CONSTRAINT PKMMWCMPACKLINK
	PRIMARY KEY (PPID, CMID)
/
ALTER TABLE DIB.MMW_CM_TEXT ADD CONSTRAINT PKMMWCMTEXT
	PRIMARY KEY (VERSIONCODE, CMID)
/
ALTER TABLE DIB.MMW_DCK_COM ADD CONSTRAINT PKMMWDCKCOM
	PRIMARY KEY (GPI, AGEINDAYSLOW, AGEINDAYSHIGH, EFFECTCODE, COMMENTCODE)
/
ALTER TABLE DIB.MMW_DCK_DRUGLINK ADD CONSTRAINT PKMMWDCKDRUGLINK
	PRIMARY KEY (GPI, AGEINDAYSLOW, AGEINDAYSHIGH)
/
ALTER TABLE DIB.MMW_DDA_AUNIT ADD CONSTRAINT PKMMWDDAAUNIT
	PRIMARY KEY (AUNITID)
/
ALTER TABLE DIB.MMW_DDA_DOSEFORGPI ADD CONSTRAINT PKMMWDDADOSEFORGPI
	PRIMARY KEY (GPI, DOSEID, PROFILEID)
/
ALTER TABLE DIB.MMW_DDA_DOSEROUTECOMPATABILITY ADD CONSTRAINT PKMMWDDADOSEROUTEC
	PRIMARY KEY (RTID, ROUTEID)
/
ALTER TABLE DIB.MMW_DDA_GPI_DOSE ADD CONSTRAINT PKMMWDDAGPIDOSE
	PRIMARY KEY (DOSEID)
/
ALTER TABLE DIB.MMW_DDA_GPI_DOSE_TEXT ADD CONSTRAINT PKMMWDDAGPIDOSETEX
	PRIMARY KEY (DOSEID, TYPECODE, LEVELCODE, SEQUENCENUMBER)
/
ALTER TABLE DIB.MMW_DDA_PATIENT_PROFILE ADD CONSTRAINT PKMMWDDAPATIENTPRO
	PRIMARY KEY (PROFILEID)
/
ALTER TABLE DIB.MMW_DDA_ROUTE ADD CONSTRAINT PKMMWDDAROUTE
	PRIMARY KEY (ROUTEID)
/
ALTER TABLE DIB.MMW_DDA_TEXT ADD CONSTRAINT PKMMWDDATEXT
	PRIMARY KEY (TEXTID, LINENUMBER)
/
ALTER TABLE DIB.MMW_DDA_UNIT ADD CONSTRAINT PKMMWDDAUNIT
	PRIMARY KEY (UNITID)
/
ALTER TABLE DIB.MMW_DDA_UNIT_XREF ADD CONSTRAINT PKMMWDDAUNITXREF
	PRIMARY KEY (FROMUNITID, UNITID)
/
ALTER TABLE DIB.MMW_DDA_UNITCONVERSION ADD CONSTRAINT PKMMWDDAUNITCONVER
	PRIMARY KEY (UNITTYPE, FROMUNITID, TOUNITID)
/
ALTER TABLE DIB.MMW_DFA_INT ADD CONSTRAINT PKMMWDFAINT
	PRIMARY KEY (DRUGCLASSID, FOODCLASSID)
/
ALTER TABLE DIB.MMW_DFA_TEXT ADD CONSTRAINT PKMMWDFATEXT
	PRIMARY KEY (VERSION, DRUGCLASSID, FOODCLASSID, LINENUMBER)
/
ALTER TABLE DIB.MMW_DI_CLASSLINK ADD CONSTRAINT PKMMWDICLASSLINK
	PRIMARY KEY (KDC1, CLASSID)
/
ALTER TABLE DIB.MMW_DI_INT ADD CONSTRAINT PKMMWDIINT
	PRIMARY KEY (CLASSID1, CLASSID2)
/
ALTER TABLE DIB.MMW_DI_RPIDLINK ADD CONSTRAINT PKMMWDIRPIDLINK
	PRIMARY KEY (KDC1, NAMETYPECODE, RPID)
/
ALTER TABLE DIB.MMW_DI_TEXT ADD CONSTRAINT PKMMWDITEXT
	PRIMARY KEY (VERSION, CLASSID1, CLASSID2, LINENUMBER)
/
ALTER TABLE DIB.MMW_DRUG_DISP ADD CONSTRAINT PKMMWDRUGDISP
	PRIMARY KEY (DDID)
/
ALTER TABLE DIB.MMW_DRUG_DISP_IMG ADD CONSTRAINT PKMMWDRUGDISPIMG
	PRIMARY KEY (DDID, LABELERID, IMAGEFILENAME)
/
ALTER TABLE DIB.MMW_DRUG_DISP_LBLR ADD CONSTRAINT PKMMWDRUGDISPLBLR
	PRIMARY KEY (DDID, LABELERID)
/
ALTER TABLE DIB.MMW_DRUG_DOSEFORM ADD CONSTRAINT PKMMWDRUGDOSEFORM
	PRIMARY KEY (DFID)
/
ALTER TABLE DIB.MMW_DRUG_GPI ADD CONSTRAINT PKMMWDRUGGPI
	PRIMARY KEY (GPI)
/
ALTER TABLE DIB.MMW_DRUG_GPILINK ADD CONSTRAINT PKMMWDRUGGPILINK
	PRIMARY KEY (DRUGID, GPI)
/
ALTER TABLE DIB.MMW_DRUG_KDC ADD CONSTRAINT PKMMWDRUGKDC
	PRIMARY KEY (KDC1)
/
ALTER TABLE DIB.MMW_DRUG_KDCLINK ADD CONSTRAINT PKMMWDRUGKDCLINK
	PRIMARY KEY (DRUGID, KDC1)
/
ALTER TABLE DIB.MMW_DRUG_LABELER ADD CONSTRAINT PKMMWDRUGLABELER
	PRIMARY KEY (LABELERID)
/
ALTER TABLE DIB.MMW_DRUG_NAME ADD CONSTRAINT PKMMWDRUGNAME
	PRIMARY KEY (PNID)
/
ALTER TABLE DIB.MMW_DRUG_PACK ADD CONSTRAINT PKMMWDRUGPACK
	PRIMARY KEY (PPID)
/
ALTER TABLE DIB.MMW_DRUG_PACK_MOD ADD CONSTRAINT PKMMWDRUGPACKMOD
	PRIMARY KEY (PPID, MODID)
/
ALTER TABLE DIB.MMW_DRUG_ROUTE ADD CONSTRAINT PKMMWDRUGROUTE
	PRIMARY KEY (RTID)
/
ALTER TABLE DIB.MMW_DRUG_ROUTED ADD CONSTRAINT PKMMWDRUGROUTED
	PRIMARY KEY (RPID)
/
ALTER TABLE DIB.MMW_DUP_DRUGLINK ADD CONSTRAINT PKMMWDUPDRUGLINK
	PRIMARY KEY (GPI, DTCID)
/
ALTER TABLE DIB.MMW_DUP_TEXT ADD CONSTRAINT PKMMWDUPTEXT
	PRIMARY KEY (DTCID)
/
ALTER TABLE DIB.MMW_FC_DRUGLINK ADD CONSTRAINT PKMMWFCDRUGLINK
	PRIMARY KEY (DRUGID, ELEMENTID, DOCUMENTCODE)
/
ALTER TABLE DIB.MMW_FC_ELEMENT ADD CONSTRAINT PKMMWFCELEMENT
	PRIMARY KEY (ELEMENTID)
/
ALTER TABLE DIB.MMW_FC_SECTION ADD CONSTRAINT PKMMWFCSECTION
	PRIMARY KEY (SECTIONID)
/
ALTER TABLE DIB.MMW_FC_SECTIONLINK ADD CONSTRAINT PKMMWFCSECTIONLINK
	PRIMARY KEY (ELEMENTID, SECTIONID)
/
ALTER TABLE DIB.MMW_IMG ADD CONSTRAINT PKMMWIMG
	PRIMARY KEY (PPID, STARTDATE)
/
ALTER TABLE DIB.MMW_IND_COM ADD CONSTRAINT PKMMWINDCOM
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, MICROORGANISMID, SEQUENCENUMBER)
/
ALTER TABLE DIB.MMW_IND_COTREAT ADD CONSTRAINT PKMMWINDCOTREAT
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, MICROORGANISMID, COTREATSETID, SEQUENCENUMBER)
/
ALTER TABLE DIB.MMW_IND_DRUGLINK ADD CONSTRAINT PKMMWINDDRUGLINK
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, MICROORGANISMID)
/
ALTER TABLE DIB.MMW_IND_RPID ADD CONSTRAINT PKMMWINDRPID
	PRIMARY KEY (MCID, RPID, OUTCOMECODE, ACCEPTANCELVLCODE)
/
ALTER TABLE DIB.MMW_IND_SOURCE ADD CONSTRAINT PKMMWINDSOURCE
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, MICROORGANISMID, SOURCECODE)
/
ALTER TABLE DIB.MMW_IPT ADD CONSTRAINT PKMMWIPT
	PRIMARY KEY (PPID, STARTDATE)
/
ALTER TABLE DIB.MMW_IPT_COLOR ADD CONSTRAINT PKMMWIPTCOLOR
	PRIMARY KEY (COLORID)
/
ALTER TABLE DIB.MMW_IPT_COLORPAL ADD CONSTRAINT PKMMWIPTCOLORPAL
	PRIMARY KEY (PALETTEID)
/
ALTER TABLE DIB.MMW_IPT_DESC ADD CONSTRAINT PKMMWIPTDESC
	PRIMARY KEY (PPID, STARTDATE, TEXTID)
/
ALTER TABLE DIB.MMW_IPT_DESCCLR ADD CONSTRAINT PKMMWIPTDESCCLR
	PRIMARY KEY (PPID, STARTDATE, COLORID)
/
ALTER TABLE DIB.MMW_IPT_DESCTEXT ADD CONSTRAINT PKMMWIPTDESCTEXT
	PRIMARY KEY (TEXTID, LINENUMBER)
/
ALTER TABLE DIB.MMW_IPT_SHAPE ADD CONSTRAINT PKMMWIPTSHAPE
	PRIMARY KEY (SHAPEID)
/
ALTER TABLE DIB.MMW_IPT_SHAPEPAL ADD CONSTRAINT PKMMWIPTSHAPEPAL
	PRIMARY KEY (PALETTEID)
/
ALTER TABLE DIB.MMW_LIB_CODEDEF ADD CONSTRAINT PKMMWLIBCODEDEF
	PRIMARY KEY (CODETYPE, CODEVALUE)
/
ALTER TABLE DIB.MMW_LIB_DISCLAIMER ADD CONSTRAINT PKMMWLIBDISCLAIMER
	PRIMARY KEY (VERSIONCODE, CATEGORYCODE, SEQUENCENUMBER)
/
ALTER TABLE DIB.MMW_LIB_VERSION ADD CONSTRAINT PKMMWLIBVERSION
	PRIMARY KEY (VERSIONKEY)
/
ALTER TABLE DIB.MMW_MED ADD CONSTRAINT PKMMWMED
	PRIMARY KEY (MCID)
/
ALTER TABLE DIB.MMW_MED_CIT ADD CONSTRAINT PKMMWMEDCIT
	PRIMARY KEY (CITATIONID)
/
ALTER TABLE DIB.MMW_MED_EXTVOCAB ADD CONSTRAINT PKMMWMEDEXTVOCAB
	PRIMARY KEY (VOCABTYPECODE, EXTVOCABID, MCID)
/
ALTER TABLE DIB.MMW_MED_HIER ADD CONSTRAINT PKMMWMEDHIER
	PRIMARY KEY (MCID, PARENTID)
/
ALTER TABLE DIB.MMW_MED_INTVOCAB ADD CONSTRAINT PKMMWMEDINTVOCAB
	PRIMARY KEY (VOCABTYPECODE, MCID, EXTVOCABID)
/
ALTER TABLE DIB.MMW_MED_LINK ADD CONSTRAINT PKMMWMEDLINK
	PRIMARY KEY (MCID, RELATEDMCID)
/
ALTER TABLE DIB.MMW_MED_NAME ADD CONSTRAINT PKMMWMEDNAME
	PRIMARY KEY (MCID, NAMETYPECODE, SEQUENCENUMBER)
/
ALTER TABLE DIB.MMW_MED_TEXT ADD CONSTRAINT PKMMWMEDTEXT
	PRIMARY KEY (TEXTID, LINENUMBER)
/
ALTER TABLE DIB.MMW_MED_TEXT_CIT ADD CONSTRAINT PKMMWMEDTEXTCIT
	PRIMARY KEY (TEXTID, CITATIONID)
/
ALTER TABLE DIB.MMW_MONO_CLSNAME ADD CONSTRAINT PKMMWMONOCLSNAME
	PRIMARY KEY (CATEGORYCODE, MONOID)
/
ALTER TABLE DIB.MMW_MONO_TEXT ADD CONSTRAINT PKMMWMONOTEXT
	PRIMARY KEY (VERSIONCODE, CATEGORYCODE, MONOID, SEQUENCENUMBER)
/
ALTER TABLE DIB.MMW_PAR_CLASS ADD CONSTRAINT PKMMWPARCLASS
	PRIMARY KEY (CLASSID)
/
ALTER TABLE DIB.MMW_PAR_CLASSLINK ADD CONSTRAINT PKMMWPARCLASSLINK
	PRIMARY KEY (KDC1, CLASSID)
/
ALTER TABLE DIB.MMW_PAR_DRUGLINK ADD CONSTRAINT PKMMWPARDRUGLINK
	PRIMARY KEY (ALLERGYID, KDC1)
/
ALTER TABLE DIB.MMW_PAR_INGRLINK ADD CONSTRAINT PKMMWPARINGRLINK
	PRIMARY KEY (KDC1, INGREDKDC1)
/
ALTER TABLE DIB.MMW_PAR_INT ADD CONSTRAINT PKMMWPARINT
	PRIMARY KEY (CLASSID1, CLASSID2, SYMPTOMCODE)
/
ALTER TABLE DIB.MMW_PDE_DRUGLINK ADD CONSTRAINT PKMMWPDEDRUGLINK
	PRIMARY KEY (GPI, VERSIONCODE, MONOID)
/
ALTER TABLE DIB.MMW_PRCA_COM ADD CONSTRAINT PKMMWPRCACOM
	PRIMARY KEY (GPI, AGEINDAYSLOW, AGEINDAYSHIGH, RESTRICTIONID, SEQUENCENUMBER)
/
ALTER TABLE DIB.MMW_PRCA_DRUGLINK ADD CONSTRAINT PKMMWPRCADRUGLINK
	PRIMARY KEY (GPI, AGEINDAYSLOW, AGEINDAYSHIGH, RESTRICTIONID)
/
ALTER TABLE DIB.MMW_PRCA_SPECCOND ADD CONSTRAINT PKMMWPRCASPECCOND
	PRIMARY KEY (GPI, AGEINDAYSLOW, AGEINDAYSHIGH, RESTRICTIONID, SPECCONDID)
/
ALTER TABLE DIB.MMW_PRCC_COM ADD CONSTRAINT PKMMWPRCCCOM
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, SEQUENCENUMBER)
/
ALTER TABLE DIB.MMW_PRCC_DRUGLINK ADD CONSTRAINT PKMMWPRCCDRUGLINK
	PRIMARY KEY (GPI, MCID, RESTRICTIONID)
/
ALTER TABLE DIB.MMW_PRCC_SPECCOND ADD CONSTRAINT PKMMWPRCCSPECCOND
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, SPECCONDID)
/
ALTER TABLE DIB.MMW_PRI ADD CONSTRAINT PKMMWPRI
	PRIMARY KEY (PPID, PRICETYPECODE, EFFECTIVEDATE)
/
ALTER TABLE DIB.MMW_WL_DRUGLINK ADD CONSTRAINT PKMMWWLDRUGLINK
	PRIMARY KEY (GPI, WLID)
/
ALTER TABLE DIB.MMW_WL_TEXT ADD CONSTRAINT PKMMWWLTEXT
	PRIMARY KEY (VERSIONCODE, WLID, SEQUENCENUMBER)
/
ALTER TABLE DIB.MMW_WL_VENDCODE ADD CONSTRAINT PKMMWWLVENDCODE
	PRIMARY KEY (VERSIONCODE, WLID, VENDVERSIONCODE)
/
CREATE INDEX DIB.DI_INT_IDX_AC_SC_DC ON DIB.MMW_DI_INT
(
	ACTCODE1,
	SEVERITYCODE,
	DOCLEVELCODE
)
/
CREATE INDEX DIB.DI_RPIDLINK_IDX_KDC1_RPID ON DIB.MMW_DI_RPIDLINK
(
	KDC1,
	RPID
)
/
CREATE UNIQUE INDEX DIB.DRUG_DISP_UQ_IDX_RPRTDFPNDD ON DIB.MMW_DRUG_DISP
(
	RPID,
	RTID,
	DFID,
	PNID,
	DDID
)
/
CREATE UNIQUE INDEX DIB.DRUG_NAME_UQ_IDX_DS_ME_PN ON DIB.MMW_DRUG_NAME
(
	DESCSEARCH,
	MEDDEVIND,
	PNID
)
/
CREATE UNIQUE INDEX DIB.DRUG_ROUTED_UQ_IDX_PN_RT_RP ON DIB.MMW_DRUG_ROUTED
(
	PNID,
	RTID,
	RPID
)
/
CREATE INDEX DIB.IXMMWADECOM1 ON DIB.MMW_ADE_COM
(
	MCID
)
/
CREATE INDEX DIB.IXMMWADEDRUGLINK1 ON DIB.MMW_ADE_DRUGLINK
(
	MCID
)
/
CREATE INDEX DIB.IXMMWADESPECCOND1 ON DIB.MMW_ADE_SPECCOND
(
	MCID
)
/
CREATE INDEX DIB.IXMMWCLSAHFS1 ON DIB.MMW_CLS_AHFS
(
	DESCPHONETIC
)
/
CREATE INDEX DIB.IXMMWCLSAHFS2 ON DIB.MMW_CLS_AHFS
(
	DESCSEARCH
)
/
CREATE INDEX DIB.IXMMWCLSAHFS3 ON DIB.MMW_CLS_AHFS
(
	PARENTCLASSID
)
/
CREATE INDEX DIB.IXMMWCLSAHFSDRUG1 ON DIB.MMW_CLS_AHFSDRUG
(
	DRUGID
)
/
CREATE INDEX DIB.IXMMWCLSGPI1 ON DIB.MMW_CLS_GPI
(
	DESCPHONETIC
)
/
CREATE INDEX DIB.IXMMWCLSGPI2 ON DIB.MMW_CLS_GPI
(
	DESCSEARCH
)
/
CREATE INDEX DIB.IXMMWCLSGPI3 ON DIB.MMW_CLS_GPI
(
	PARENTCLASSID
)
/
CREATE INDEX DIB.IXMMWCLSGPIDRUG1 ON DIB.MMW_CLS_GPIDRUG
(
	DRUGID
)
/
CREATE INDEX DIB.IXMMWDICLASSLINK1 ON DIB.MMW_DI_CLASSLINK
(
	CLASSID,
	KDC1
)
/
CREATE INDEX DIB.IXMMWDIINT1 ON DIB.MMW_DI_INT
(
	CLASSID1,
	ACTCODE1,
	CLASSID2
)
/
CREATE INDEX DIB.IXMMWDIINT2 ON DIB.MMW_DI_INT
(
	CLASSID2
)
/
CREATE INDEX DIB.IXMMWDRUGDISP1 ON DIB.MMW_DRUG_DISP
(
	PNID
)
/
CREATE INDEX DIB.IXMMWDRUGDISP2 ON DIB.MMW_DRUG_DISP
(
	DESCPHONETIC
)
/
CREATE INDEX DIB.IXMMWDRUGDISP3 ON DIB.MMW_DRUG_DISP
(
	DESCSEARCH
)
/
CREATE INDEX DIB.IXMMWDRUGDISP4 ON DIB.MMW_DRUG_DISP
(
	GPI
)
/
CREATE INDEX DIB.IXMMWDRUGNAME1 ON DIB.MMW_DRUG_NAME
(
	DESCPHONETIC
)
/
CREATE INDEX DIB.IXMMWDRUGNAME2 ON DIB.MMW_DRUG_NAME
(
	DESCSEARCH
)
/
CREATE INDEX DIB.IXMMWDRUGPACK1 ON DIB.MMW_DRUG_PACK
(
	DDID
)
/
CREATE INDEX DIB.IXMMWDRUGROUTED1 ON DIB.MMW_DRUG_ROUTED
(
	DESCPHONETIC
)
/
CREATE INDEX DIB.IXMMWDRUGROUTED2 ON DIB.MMW_DRUG_ROUTED
(
	DESCSEARCH
)
/
CREATE INDEX DIB.IXMMWDRUGROUTED3 ON DIB.MMW_DRUG_ROUTED
(
	PNID
)
/
CREATE INDEX DIB.IXMMWFCELEMENT1 ON DIB.MMW_FC_ELEMENT
(
	IDATTRIBUTE
)
/
CREATE INDEX DIB.IXMMWINDCOM1 ON DIB.MMW_IND_COM
(
	MCID
)
/
CREATE INDEX DIB.IXMMWINDCOTREAT1 ON DIB.MMW_IND_COTREAT
(
	MCID
)
/
CREATE INDEX DIB.IXMMWINDDRUGLINK1 ON DIB.MMW_IND_DRUGLINK
(
	MCID
)
/
CREATE INDEX DIB.IXMMWINDSOURCE1 ON DIB.MMW_IND_SOURCE
(
	MCID
)
/
CREATE INDEX DIB.IXMMWIPT1 ON DIB.MMW_IPT
(
	CLARITYCODE
)
/
CREATE INDEX DIB.IXMMWIPT2 ON DIB.MMW_IPT
(
	COATINGCODE
)
/
CREATE INDEX DIB.IXMMWIPT3 ON DIB.MMW_IPT
(
	COLORPALETTEIDLIST
)
/
CREATE INDEX DIB.IXMMWIPT4 ON DIB.MMW_IPT
(
	DESCSEARCH
)
/
CREATE INDEX DIB.IXMMWIPT5 ON DIB.MMW_IPT
(
	FLAVORCODE
)
/
CREATE INDEX DIB.IXMMWIPT6 ON DIB.MMW_IPT
(
	FORMCODE
)
/
CREATE INDEX DIB.IXMMWIPT7 ON DIB.MMW_IPT
(
	SCORINGCODE
)
/
CREATE INDEX DIB.IXMMWIPT8 ON DIB.MMW_IPT
(
	SHAPEID
)
/
CREATE INDEX DIB.IXMMWMEDEXTVOCAB1 ON DIB.MMW_MED_EXTVOCAB
(
	EXTVOCABID
)
/
CREATE INDEX DIB.IXMMWMEDINTVOCAB1 ON DIB.MMW_MED_INTVOCAB
(
	MCID
)
/
CREATE INDEX DIB.IXMMWMEDNAME1 ON DIB.MMW_MED_NAME
(
	NAMEPHONETIC
)
/
CREATE INDEX DIB.IXMMWMEDNAME2 ON DIB.MMW_MED_NAME
(
	NAMESEARCH
)
/
CREATE INDEX DIB.IXMMWPRCCCOM1 ON DIB.MMW_PRCC_COM
(
	MCID
)
/
CREATE INDEX DIB.IXMMWPRCCDRUGLINK1 ON DIB.MMW_PRCC_DRUGLINK
(
	MCID
)
/
CREATE INDEX DIB.IXMMWPRCCSPECCOND1 ON DIB.MMW_PRCC_SPECCOND
(
	MCID
)
/
