-- Azure SQL Compatible Foreign Key Constraints
-- Converted from Oracle DDL
-- Note: DEFERRABLE INITIALLY DEFERRED clauses removed (not supported in Azure SQL)
-- Note: ENABLE clause removed (default behavior in Azure SQL)

-- FK 1
ALTER TABLE "EPS"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 2
ALTER TABLE "EPS"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 3
ALTER TABLE "EPS"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 4
ALTER TABLE "EPS"."ADMIN_UNLOCK_LOG" ADD CONSTRAINT "ADMIN_UNLOCK_LOG_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 5
ALTER TABLE "EPS"."ADMIN_UNLOCK_LOG" ADD CONSTRAINT "ADMIN_UNLOCK_LOG_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 6
ALTER TABLE "EPS"."ALLERGY" ADD CONSTRAINT "ALLERGY_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 7
ALTER TABLE "EPS"."ALLERGY" ADD CONSTRAINT "ALLERGY_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 8
ALTER TABLE "EPS"."ALLERGY" ADD CONSTRAINT "ALLERGY_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 9
ALTER TABLE "EPS"."ALT_PRESCRIBER" ADD CONSTRAINT "ALT_PRESCRIBER_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 10
ALTER TABLE "EPS"."ALT_PRESCRIBER" ADD CONSTRAINT "ALT_PRESCRIBER_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 11
ALTER TABLE "EPS"."AUDIT_ACCESS_LOG" ADD CONSTRAINT "AAL_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 12
ALTER TABLE "EPS"."AUDIT_MESSAGE_CONTENT" ADD CONSTRAINT "AMC_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 13
ALTER TABLE "EPS"."AUDIT_PHI_EVENT_DETAIL" ADD CONSTRAINT "APED_FK_APE" FOREIGN KEY ("CHAIN_ID", "AUDIT_PHI_EVENT_ID") REFERENCES "EPS"."AUDIT_PHI_EVENT" ("CHAIN_ID", "ID");

-- FK 14
ALTER TABLE "EPS"."CARD" ADD CONSTRAINT "CARD_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 15
ALTER TABLE "EPS"."CARD" ADD CONSTRAINT "CARD_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 16
ALTER TABLE "EPS"."CHAIN_RX_TX_SHARING_LINK" ADD CONSTRAINT "CHN_RXTX_SHRG_LINK_FK2_ESCHAIN" FOREIGN KEY ("LINKED_CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 17
ALTER TABLE "EPS"."CHAIN_RX_TX_SHARING_LINK" ADD CONSTRAINT "CHN_RXTX_SHRG_LINK_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 18
ALTER TABLE "EPS"."COMPOUND_INGREDIENTS" ADD CONSTRAINT "COMPOUND_INGREDIENTS_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 19
ALTER TABLE "EPS"."COMPOUND_INGREDIENTS" ADD CONSTRAINT "COMPOUND_INGREDIENTS_FK2" FOREIGN KEY ("CHAIN_ID", "ID_RX_TX") REFERENCES "EPS"."RX_TX" ("CHAIN_ID", "ID");

-- FK 20
ALTER TABLE "EPS"."COMPOUND_INGREDIENT_LOT" ADD CONSTRAINT "COMPOUND_INGREDIENT_LOT_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 21
ALTER TABLE "EPS"."COMPOUND_INGREDIENT_LOT" ADD CONSTRAINT "COMPOUND_INGREDIENT_LOT_FK2" FOREIGN KEY ("CHAIN_ID", "ID") REFERENCES "EPS"."COMPOUND_INGREDIENTS" ("CHAIN_ID", "ID");

-- FK 22
ALTER TABLE "EPS"."COUNSELING_NOTES" ADD CONSTRAINT "COUNSELING_NOTES_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 23
ALTER TABLE "EPS"."COUNSELING_NOTES" ADD CONSTRAINT "COUNSELING_NOTES_FK2" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 24
ALTER TABLE "EPS"."CROSS_CHAIN_LAST_SELECTED" ADD CONSTRAINT "CCHN_LAST_SELECTED_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 25
ALTER TABLE "EPS"."CROSS_CHAIN_LAST_SELECTED" ADD CONSTRAINT "CCHN_LAST_SELECTED_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 26
ALTER TABLE "EPS"."CROSS_CHAIN_LAST_SELECTED" ADD CONSTRAINT "CCHN_LAST_SELECTED_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 27
ALTER TABLE "EPS"."CROSS_CHAIN_LINK" ADD CONSTRAINT "CROSS_CHAIN_LINK_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 28
ALTER TABLE "EPS"."CROSS_CHAIN_LINK" ADD CONSTRAINT "CROSS_CHAIN_LINK_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 29
ALTER TABLE "EPS"."CROSS_CHAIN_LINK" ADD CONSTRAINT "CROSS_CHAIN_LINK_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 30
ALTER TABLE "EPS"."DISEASE" ADD CONSTRAINT "DISEASE_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 31
ALTER TABLE "EPS"."DISEASE" ADD CONSTRAINT "DISEASE_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 32
ALTER TABLE "EPS"."DISEASE" ADD CONSTRAINT "DISEASE_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 33
ALTER TABLE "EPS"."EMAIL" ADD CONSTRAINT "EMAIL_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 34
ALTER TABLE "EPS"."EMAIL" ADD CONSTRAINT "EMAIL_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 35
ALTER TABLE "EPS"."EMAIL" ADD CONSTRAINT "EMAIL_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 36
ALTER TABLE "EPS"."FDB_PATIENT_ALLERGY" ADD CONSTRAINT "FDB_PATIENT_ALLERGY_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 37
ALTER TABLE "EPS"."FDB_PATIENT_ALLERGY" ADD CONSTRAINT "FDB_PATIENT_ALLERGY_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 38
ALTER TABLE "EPS"."FDB_PATIENT_ALLERGY" ADD CONSTRAINT "FDB_PAT_ALLERGY_FK_IDPATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 39
ALTER TABLE "EPS"."FDB_PATIENT_ALLERGY_REACTION" ADD CONSTRAINT "FDB_PAT_ALL_REA_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 40
ALTER TABLE "EPS"."FOLLOW_UP_PRESCRIBER" ADD CONSTRAINT "FOLLOW_UP_PRESCRIBER_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 41
ALTER TABLE "EPS"."FOLLOW_UP_PRESCRIBER" ADD CONSTRAINT "FOLLOW_UP_PRESCRIBER_FK2" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 42
ALTER TABLE "EPS"."FREE_FORM_ALLERGY" ADD CONSTRAINT "FREE_FORM_ALLERGY_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 43
ALTER TABLE "EPS"."FREE_FORM_ALLERGY" ADD CONSTRAINT "FREE_FORM_ALLERGY_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 44
ALTER TABLE "EPS"."FREE_FORM_ALLERGY" ADD CONSTRAINT "FREE_FORM_ALLERGY_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 45
ALTER TABLE "EPS"."IDGEN" ADD CONSTRAINT "IDGEN_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 46
ALTER TABLE "EPS"."INTAKE_SOURCES" ADD CONSTRAINT "INTAKE_SOURCES_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 47
ALTER TABLE "EPS"."INTAKE_SOURCES" ADD CONSTRAINT "INTAKE_SOURCES_FK2" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 48
ALTER TABLE "EPS"."KP_RXNUM_REF" ADD CONSTRAINT "KP_RXNUM_REF_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 49
ALTER TABLE "EPS"."KP_RXNUM_REF" ADD CONSTRAINT "KP_RXNUM_REF_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "ACTIVE_RX_NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 50
ALTER TABLE "EPS"."LINE_ITEM" ADD CONSTRAINT "LINE_ITEM_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 51
ALTER TABLE "EPS"."LINE_ITEM" ADD CONSTRAINT "LINE_ITEM_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 52
ALTER TABLE "EPS"."LINE_ITEM" ADD CONSTRAINT "LINE_ITEM_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 53
ALTER TABLE "EPS"."LINK_TOKENS" ADD CONSTRAINT "LINK_TOKENS_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 54
ALTER TABLE "EPS"."LINK_TOKENS" ADD CONSTRAINT "LINK_TOKENS_FK_ROOTID" FOREIGN KEY ("CHAIN_ID", "ROOT_ID") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 55
ALTER TABLE "EPS"."MATCH_KEY" ADD CONSTRAINT "MATCH_KEY_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 56
ALTER TABLE "EPS"."MATCH_KEY" ADD CONSTRAINT "MATCH_KEY_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 57
ALTER TABLE "EPS"."MEDICAL_CONDITION" ADD CONSTRAINT "MEDICAL_CONDITION_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 58
ALTER TABLE "EPS"."MEDICAL_CONDITION" ADD CONSTRAINT "MEDICAL_CONDITION_FK2" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 59
ALTER TABLE "EPS"."MOD_PCM" ADD CONSTRAINT "MOD_PCM_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 60
ALTER TABLE "EPS"."MOD_PCM" ADD CONSTRAINT "MOD_PCM_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 61
ALTER TABLE "EPS"."MRN" ADD CONSTRAINT "MRN_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 62
ALTER TABLE "EPS"."MRN" ADD CONSTRAINT "MRN_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 63
ALTER TABLE "EPS"."MRN" ADD CONSTRAINT "MRN_FK_ROOTID" FOREIGN KEY ("CHAIN_ID", "ROOT_ID") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 64
ALTER TABLE "EPS"."MTM_PATIENT_ANSWERS" ADD CONSTRAINT "MTM_PATIENT_ANSWERS_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 65
ALTER TABLE "EPS"."MTM_PATIENT_ANSWERS" ADD CONSTRAINT "MTM_PATIENT_ANSWERS_FK_SESS" FOREIGN KEY ("CHAIN_ID", "ID_MTM_PATIENT_SESSION") REFERENCES "EPS"."MTM_PATIENT_SESSION" ("CHAIN_ID", "ID");

-- FK 66
ALTER TABLE "EPS"."MTM_PATIENT_ELIGIBILITY" ADD CONSTRAINT "MTM_PATIENT_ELIGIBILITY_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 67
ALTER TABLE "EPS"."MTM_PATIENT_SESSION" ADD CONSTRAINT "MTM_PATIENT_SESSION_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 68
ALTER TABLE "EPS"."MTM_PATIENT_SESSION" ADD CONSTRAINT "MTM_PATIENT_SESSION_FK_SIGN" FOREIGN KEY ("CHAIN_ID", "ID_SIGNATURE") REFERENCES "EPS"."SIGNATURE" ("CHAIN_ID", "ID");

-- FK 69
ALTER TABLE "EPS"."PACKAGE_INFO" ADD CONSTRAINT "PACKAGE_INFO_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 70
ALTER TABLE "EPS"."PACKAGE_INFO" ADD CONSTRAINT "PACKAGE_INFO_FK_RX_TX" FOREIGN KEY ("CHAIN_ID", "ID_RX_TX") REFERENCES "EPS"."RX_TX" ("CHAIN_ID", "ID");

-- FK 71 -- issue the column RESPONSIBLE_PARTY_RXCOM_ID does not exist in the PATIENT table.
ALTER TABLE "EPS"."PATIENT" ADD CONSTRAINT "PATIENT_FK1" FOREIGN KEY ("CHAIN_ID", "RESPONSIBLE_PARTY_RXCOM_ID") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 72
ALTER TABLE "EPS"."PATIENT" ADD CONSTRAINT "PATIENT_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 73
ALTER TABLE "EPS"."PATIENT" ADD CONSTRAINT "PATIENT_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 74
ALTER TABLE "EPS"."PATIENT_AR_ACCOUNT" ADD CONSTRAINT "PATIENT_AR_AC_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 75
ALTER TABLE "EPS"."PATIENT_AR_ACCOUNT" ADD CONSTRAINT "PATIENT_AR_AC_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 76
ALTER TABLE "EPS"."PATIENT_AR_ACCOUNT" ADD CONSTRAINT "PATIENT_AR_AC_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 77
ALTER TABLE "EPS"."PATIENT_CARE_PROVIDER" ADD CONSTRAINT "PATIENT_CARE_PROVIDER_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 78
ALTER TABLE "EPS"."PATIENT_CARE_PROVIDER" ADD CONSTRAINT "PATIENT_CARE_PROVIDER_FK2" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 79
ALTER TABLE "EPS"."PATIENT_CREDIT_CARD" ADD CONSTRAINT "PATIENT_CC_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 80
ALTER TABLE "EPS"."PATIENT_CREDIT_CARD" ADD CONSTRAINT "PATIENT_CC_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 81
ALTER TABLE "EPS"."PATIENT_DOCUMENT" ADD CONSTRAINT "PATIENT_DOCUMENT_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 82
ALTER TABLE "EPS"."PATIENT_DOCUMENT" ADD CONSTRAINT "PATIENT_DOCUMENT_FK2" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 83
ALTER TABLE "EPS"."PATIENT_DOCUMENT" ADD CONSTRAINT "PATIENT_DOCUMENT_FK3" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 84
ALTER TABLE "EPS"."PATIENT_EMERGENCY_CONTACT" ADD CONSTRAINT "PATIENT_EMERGENCY_CONTACT_FK1" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 85
ALTER TABLE "EPS"."PATIENT_EMERGENCY_CONTACT" ADD CONSTRAINT "PATIENT_EMERGENCY_CONTACT_FK2" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 86
ALTER TABLE "EPS"."PATIENT_MO_CONSENT" ADD CONSTRAINT "PATIENT_MO_CONSENT_FK1" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 87
ALTER TABLE "EPS"."PATIENT_MO_CONSENT" ADD CONSTRAINT "PATIENT_MO_CONSENT_FK2" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 88
ALTER TABLE "EPS"."PATIENT_NOTES" ADD CONSTRAINT "PATIENT_NOTES_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 89
ALTER TABLE "EPS"."PATIENT_NOTES" ADD CONSTRAINT "PATIENT_NOTES_FK2" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 90
ALTER TABLE "EPS"."PATIENT_NOTIFY_SCHEDULE" ADD CONSTRAINT "PATIENT_NOTIFY_SCHEDULE_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 91
ALTER TABLE "EPS"."PATIENT_NOTIFY_SCHEDULE" ADD CONSTRAINT "PATIENT_NOTIFY_SCHEDULE_FK2" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 92
ALTER TABLE "EPS"."PATIENT_PROGRAM" ADD CONSTRAINT "PATIENT_PROGRAM_FK1" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 93
ALTER TABLE "EPS"."PATIENT_PROGRAM_CONTACT" ADD CONSTRAINT "PATIENT_PROGRAM_CONTACT_FK1" FOREIGN KEY ("CHAIN_ID", "PATIENT_PROGRAM_ID") REFERENCES "EPS"."PATIENT_PROGRAM" ("CHAIN_ID", "ID");

-- FK 94
ALTER TABLE "EPS"."PATIENT_SIGNATURES" ADD CONSTRAINT "PATIENT_SIGNATURES_FK1" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 95
ALTER TABLE "EPS"."PATIENT_SIGNATURES" ADD CONSTRAINT "PATIENT_SIGNATURES_FK2" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 96
ALTER TABLE "EPS"."PATIENT_SIGNATURES" ADD CONSTRAINT "PATIENT_SIGNATURES_FK3" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 97
ALTER TABLE "EPS"."PATIENT_SIGNATURES" ADD CONSTRAINT "PATIENT_SIGNATURES_FK4" FOREIGN KEY ("CHAIN_ID", "ACQUIRED_AT_STORE_NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 98
ALTER TABLE "EPS"."PATIENT_SIGNATURES" ADD CONSTRAINT "PATIENT_SIGNATURES_FK5" FOREIGN KEY ("CHAIN_ID", "REVOKED_AT_STORE_NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 99
ALTER TABLE "EPS"."PATIENT_UNMERGE_LOCK" ADD CONSTRAINT "PATIENT_UNMERGE_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 100
ALTER TABLE "EPS"."PATIENT_UNMERGE_LOCK" ADD CONSTRAINT "PATIENT_UNMERGE_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 101
ALTER TABLE "EPS"."PATIENT_UNMERGE_LOCK" ADD CONSTRAINT "PAT_UMMERGE_LOCK_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 102
ALTER TABLE "EPS"."PAYMENT" ADD CONSTRAINT "PAYMENT_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 103
ALTER TABLE "EPS"."PAYMENT" ADD CONSTRAINT "PAYMENT_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 104
ALTER TABLE "EPS"."PA_NUM" ADD CONSTRAINT "PA_NUM_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 105
ALTER TABLE "EPS"."PA_NUM" ADD CONSTRAINT "PA_NUM_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 106
ALTER TABLE "EPS"."PA_NUM" ADD CONSTRAINT "PA_NUM_FK_TX_TP" FOREIGN KEY ("CHAIN_ID", "ID_TX_TP") REFERENCES "EPS"."TX_TP" ("CHAIN_ID", "ID");

-- FK 107
ALTER TABLE "EPS"."PDX_SCHEMA_PROCESS_HISTORY" ADD CONSTRAINT "PDX_SCHEMA_PROCESS_HISTORY_FK1" FOREIGN KEY ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID") REFERENCES "EPS"."PDX_SCHEMA_UPD_PKGCALL_HIST" ("ID");

-- FK 108
ALTER TABLE "EPS"."PDX_SCHEMA_PROCESS_HISTORY" ADD CONSTRAINT "PDX_SCHEMA_PROCESS_HISTORY_FK2" FOREIGN KEY ("PDX_SCHEMA_VERSION_HISTORY_ID") REFERENCES "EPS"."PDX_SCHEMA_VERSION_HISTORY" ("ID");

-- FK 109
ALTER TABLE "EPS"."PDX_SCHEMA_TASK_ERROR_LOG" ADD CONSTRAINT "PDX_SCHEMA_TASK_ERROR_LOG_FK1" FOREIGN KEY ("ID") REFERENCES "EPS"."PDX_SCHEMA_TASK_HISTORY" ("ID");

-- FK 110
ALTER TABLE "EPS"."PDX_SCHEMA_TASK_HISTORY" ADD CONSTRAINT "PDX_SCHEMA_TASK_HISTORY_FK1" FOREIGN KEY ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID") REFERENCES "EPS"."PDX_SCHEMA_UPD_PKGCALL_HIST" ("ID");

-- FK 111
ALTER TABLE "EPS"."PDX_SCHEMA_TASK_HISTORY" ADD CONSTRAINT "PDX_SCHEMA_TASK_HISTORY_FK2" FOREIGN KEY ("PDX_SCHEMA_VERSION_HISTORY_ID") REFERENCES "EPS"."PDX_SCHEMA_VERSION_HISTORY" ("ID");

-- FK 112
ALTER TABLE "EPS"."PDX_SCHEMA_UPD_HELPER_DEBUG_D" ADD CONSTRAINT "PDX_SCHEMA_UPD_HLPR_DBG_D_FK1" FOREIGN KEY ("PDX_SCHEMA_UPD_HLPR_DBG_H_ID") REFERENCES "EPS"."PDX_SCHEMA_UPD_HELPER_DEBUG_H" ("ID");

-- FK 113
ALTER TABLE "EPS"."PDX_SCHEMA_UPD_PKGCALL_ERR_LOG" ADD CONSTRAINT "PDX_SCHEMA_UPD_PKGCALL_ELG_FK1" FOREIGN KEY ("ID") REFERENCES "EPS"."PDX_SCHEMA_UPD_PKGCALL_HIST" ("ID");

-- FK 114
ALTER TABLE "EPS"."PDX_SCHEMA_VERSION_ERROR_LOG" ADD CONSTRAINT "PDX_SCHEMA_VERSION_ERR_LOG_FK1" FOREIGN KEY ("ID") REFERENCES "EPS"."PDX_SCHEMA_VERSION_HISTORY" ("ID");

-- FK 115
ALTER TABLE "EPS"."PDX_SCHEMA_VERSION_HISTORY" ADD CONSTRAINT "PDX_SCHEMA_VERSION_HISTORY_FK1" FOREIGN KEY ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID") REFERENCES "EPS"."PDX_SCHEMA_UPD_PKGCALL_HIST" ("ID");

-- FK 116
ALTER TABLE "EPS"."PRESCRIBER" ADD CONSTRAINT "PRESCRIBER_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 117
ALTER TABLE "EPS"."PRESCRIBER" ADD CONSTRAINT "PRESCRIBER_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 118
ALTER TABLE "EPS"."PRIOR_ADVERSE_REACTION" ADD CONSTRAINT "PRIOR_ADVERSE_REACTION_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 119
ALTER TABLE "EPS"."PRIOR_ADVERSE_REACTION" ADD CONSTRAINT "PRIOR_ADVERSE_REACTION_FK2" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 120
ALTER TABLE "EPS"."PURGE_FLOW_MAP" ADD CONSTRAINT "PURGE_FLOW_MAP_FK1" FOREIGN KEY ("PURGE_RUN_DETAILS_ID") REFERENCES "EPS"."PURGE_RUN_DETAILS" ("ID");

-- FK 121
ALTER TABLE "EPS"."PURGE_FLOW_MAP" ADD CONSTRAINT "PURGE_FLOW_MAP_FK2" FOREIGN KEY ("PURGE_REC_RUN_DETAILS_ID") REFERENCES "EPS"."PURGE_RUN_DETAILS" ("ID");

-- FK 122
ALTER TABLE "EPS"."PURGE_INDEX_REBUILD_LOG" ADD CONSTRAINT "PURGE_INDEX_REBUILD_LOG_FK1" FOREIGN KEY ("PURGE_RUN_DETAILS_ID") REFERENCES "EPS"."PURGE_RUN_DETAILS" ("ID");

-- FK 123
ALTER TABLE "EPS"."PURGE_INDEX_REBUILD_LOG" ADD CONSTRAINT "PURGE_INDEX_REBUILD_LOG_FK2" FOREIGN KEY ("PURGE_ERROR_LOG_ID") REFERENCES "EPS"."PURGE_ERROR_LOG" ("ID");

-- FK 124
ALTER TABLE "EPS"."PURGE_RUN_DETAILS" ADD CONSTRAINT "PURGE_RUN_DETAILS_FK1" FOREIGN KEY ("PURGE_ERROR_LOG_ID") REFERENCES "EPS"."PURGE_ERROR_LOG" ("ID");

-- FK 125
ALTER TABLE "EPS"."QUEUECOMMAND" ADD CONSTRAINT "QUEUECMD_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 126
ALTER TABLE "EPS"."QUEUECOMMAND" ADD CONSTRAINT "QUEUECMD_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 127
ALTER TABLE "EPS"."QUEUECOMMAND" ADD CONSTRAINT "QUEUECMD_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 128
ALTER TABLE "EPS"."RENAL_MEASUREMENT" ADD CONSTRAINT "RENAL_MEASUREMENT_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 129
ALTER TABLE "EPS"."RENAL_MEASUREMENT" ADD CONSTRAINT "RENAL_MEASUREMENT_FK2" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 130
ALTER TABLE "EPS"."RX_TX" ADD CONSTRAINT "RX_TX_FK_ALT_PRESCRIBER" FOREIGN KEY ("CHAIN_ID", "ID_ALT_PRESCRIBER") REFERENCES "EPS"."ALT_PRESCRIBER" ("CHAIN_ID", "ID");

-- FK 131
ALTER TABLE "EPS"."RX_TX" ADD CONSTRAINT "RX_TX_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 132
ALTER TABLE "EPS"."RX_TX" ADD CONSTRAINT "RX_TX_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 133
ALTER TABLE "EPS"."RX_TX" ADD CONSTRAINT "RX_TX_FK_MOD_PCM" FOREIGN KEY ("CHAIN_ID", "ID_MODPCM") REFERENCES "EPS"."MOD_PCM" ("CHAIN_ID", "ID");

-- FK 134
ALTER TABLE "EPS"."RX_TX" ADD CONSTRAINT "RX_TX_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 135
ALTER TABLE "EPS"."RX_TX" ADD CONSTRAINT "RX_TX_FK_PRESCRIBER" FOREIGN KEY ("CHAIN_ID", "ID_PRESCRIBER") REFERENCES "EPS"."PRESCRIBER" ("CHAIN_ID", "ID");

-- FK 136
ALTER TABLE "EPS"."RX_TX_DIAGNOSIS_CODES" ADD CONSTRAINT "RX_TX_DIAGNOSIS_CODES_FK1" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 137
ALTER TABLE "EPS"."RX_TX_DIAGNOSIS_CODES" ADD CONSTRAINT "RX_TX_DIAGNOSIS_CODES_FK2" FOREIGN KEY ("CHAIN_ID", "ID_RX_TX") REFERENCES "EPS"."RX_TX" ("CHAIN_ID", "ID");

-- FK 138
ALTER TABLE "EPS"."RX_TX_DUR_LIST" ADD CONSTRAINT "RX_TX_DUR_LIST_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 139
ALTER TABLE "EPS"."RX_TX_DUR_LIST" ADD CONSTRAINT "RX_TX_DUR_LIST_FK_IDRXTX" FOREIGN KEY ("CHAIN_ID", "ID_RX_TX") REFERENCES "EPS"."RX_TX" ("CHAIN_ID", "ID");

-- FK 140
ALTER TABLE "EPS"."RX_TX_PAYMENT" ADD CONSTRAINT "RX_TX_PAYMENT_FK_CHAIN_PAYID" FOREIGN KEY ("CHAIN_ID", "ID_PAYMENT") REFERENCES "EPS"."PAYMENT" ("CHAIN_ID", "ID");

-- FK 141
ALTER TABLE "EPS"."RX_TX_PAYMENT" ADD CONSTRAINT "RX_TX_PAYMENT_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 142
ALTER TABLE "EPS"."RX_TX_PAYMENT" ADD CONSTRAINT "RX_TX_PAYMENT_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 143
ALTER TABLE "EPS"."RX_TX_SIG_STRUCTURED_PART" ADD CONSTRAINT "RX_TX_SIG_STR_PRT_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 144
ALTER TABLE "EPS"."RX_TX_SIG_STRUCTURED_PART" ADD CONSTRAINT "RX_TX_SIG_STR_PRT_FK_RX_TX" FOREIGN KEY ("CHAIN_ID", "ID_RX_TX") REFERENCES "EPS"."RX_TX" ("CHAIN_ID", "ID");

-- FK 145
ALTER TABLE "EPS"."SIGNATURE" ADD CONSTRAINT "SIGNATURE_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 146
ALTER TABLE "EPS"."SIGNATURE" ADD CONSTRAINT "SIGNATURE_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 147
ALTER TABLE "EPS"."TELEPHONE" ADD CONSTRAINT "TELEPHONE_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 148
ALTER TABLE "EPS"."TELEPHONE" ADD CONSTRAINT "TELEPHONE_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 149
ALTER TABLE "EPS"."TELEPHONE" ADD CONSTRAINT "TELEPHONE_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 150
ALTER TABLE "EPS"."TP_LINK" ADD CONSTRAINT "TP_LINK_FK_CARD" FOREIGN KEY ("CHAIN_ID", "ID_CARD") REFERENCES "EPS"."CARD" ("CHAIN_ID", "ID");

-- FK 151
ALTER TABLE "EPS"."TP_LINK" ADD CONSTRAINT "TP_LINK_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 152
ALTER TABLE "EPS"."TP_LINK" ADD CONSTRAINT "TP_LINK_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 153
ALTER TABLE "EPS"."TP_LINK" ADD CONSTRAINT "TP_LINK_FK_PATIENT" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 154
ALTER TABLE "EPS"."TX_CRED" ADD CONSTRAINT "TX_CRED_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 155
ALTER TABLE "EPS"."TX_CRED" ADD CONSTRAINT "TX_CRED_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 156
ALTER TABLE "EPS"."TX_CRED" ADD CONSTRAINT "TX_CRED_FK_RX_TX" FOREIGN KEY ("CHAIN_ID", "ID_RX_TX") REFERENCES "EPS"."RX_TX" ("CHAIN_ID", "ID");

-- FK 157
ALTER TABLE "EPS"."TX_LOT" ADD CONSTRAINT "TX_LOT_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 158
ALTER TABLE "EPS"."TX_LOT" ADD CONSTRAINT "TX_LOT_FK_RX_TX" FOREIGN KEY ("CHAIN_ID", "ID_RX_TX") REFERENCES "EPS"."RX_TX" ("CHAIN_ID", "ID");

-- FK 159
ALTER TABLE "EPS"."TX_TP" ADD CONSTRAINT "TX_TP_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 160
ALTER TABLE "EPS"."TX_TP" ADD CONSTRAINT "TX_TP_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

-- FK 161
ALTER TABLE "EPS"."TX_TP" ADD CONSTRAINT "TX_TP_FK_RX_TX" FOREIGN KEY ("CHAIN_ID", "ID_RX_TX") REFERENCES "EPS"."RX_TX" ("CHAIN_ID", "ID");

-- FK 162
ALTER TABLE "EPS"."VERSION" ADD CONSTRAINT "VERSION_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 163
ALTER TABLE "EPS"."VIAL_INFO" ADD CONSTRAINT "VIAL_INFO_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 164
ALTER TABLE "EPS"."VIAL_INFO" ADD CONSTRAINT "VIAL_INFO_FK_RX_TX" FOREIGN KEY ("CHAIN_ID", "ID_RX_TX") REFERENCES "EPS"."RX_TX" ("CHAIN_ID", "ID");

-- FK 165
ALTER TABLE "EPS"."VISUALLY_IMPAIRED_DETAIL" ADD CONSTRAINT "VISUALLY_IMPAIRED_DETAIL_FK1" FOREIGN KEY ("CHAIN_ID", "ID_PATIENT") REFERENCES "EPS"."PATIENT" ("CHAIN_ID", "ID");

-- FK 166
ALTER TABLE "EPS"."VISUALLY_IMPAIRED_DETAIL" ADD CONSTRAINT "VISUALLY_IMPAIRED_DETAIL_FK2" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 167
ALTER TABLE "EPS"."WORKMANS_COMP" ADD CONSTRAINT "WORKCOMP_FK_CARD" FOREIGN KEY ("CHAIN_ID", "ID_CARD") REFERENCES "EPS"."CARD" ("CHAIN_ID", "ID");

-- FK 168
ALTER TABLE "EPS"."WORKMANS_COMP" ADD CONSTRAINT "WORKCOMP_FK_ESCHAIN" FOREIGN KEY ("CHAIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_CHAIN" ("CHAIN_NHIN_ID");

-- FK 169
ALTER TABLE "EPS"."WORKMANS_COMP" ADD CONSTRAINT "WORKCOMP_FK_ESSTORE" FOREIGN KEY ("CHAIN_ID", "NHIN_ID") REFERENCES "SEC_ADMIN"."EPS_SEC_STORE" ("CHAIN_NHIN_ID", "STORE_NHIN_ID");

