INSERT INTO ALL_TRIGGERS (FILE_NAME,DDL_CLOB) VALUES
	 ('sbmo.trigger.adjustment_group_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."ADJUSTMENT_GROUP_TRIG_BIR" 

BEFORE INSERT ON ADJUSTMENT_GROUP

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."ADJUSTMENT_GROUP_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.audit_log_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."AUDIT_LOG_TRIG_BIR" 

BEFORE INSERT ON AUDIT_LOG

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."AUDIT_LOG_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.charge_payment_info_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."CHARGE_PAYMENT_INFO_TRIG_BIR" 

BEFORE INSERT ON CHARGE_PAYMENT_INFO

REFERENCING OLD AS OLD NEW AS NEW

FOR EACH ROW

BEGIN

:new.created_date := systimestamp;

END;

ALTER TRIGGER "SBMO"."CHARGE_PAYMENT_INFO_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.drug_orders_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."DRUG_ORDERS_TRIG_BIR" 

BEFORE INSERT ON DRUG_ORDERS

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."DRUG_ORDERS_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.inventory_audit_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."INVENTORY_AUDIT_TRIG_BIR" 

BEFORE INSERT ON INVENTORY_AUDIT

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."INVENTORY_AUDIT_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.message_log_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."MESSAGE_LOG_TRIG_BIR" 

	   BEFORE INSERT ON MESSAGE_LOG

	   REFERENCING NEW AS new

	   FOR EACH ROW

	   BEGIN

	     IF INSERTING THEN

	       :new.created_date := SYSTIMESTAMP;

	     END IF;

	   END;

ALTER TRIGGER "SBMO"."MESSAGE_LOG_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.orders_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."ORDERS_TRIG_BIR" 

BEFORE INSERT ON ORDERS

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."ORDERS_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.purchase_order_group_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."PURCHASE_ORDER_GROUP_TRIG_BIR" 

BEFORE INSERT ON PURCHASE_ORDER_GROUP

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."PURCHASE_ORDER_GROUP_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.purchase_order_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."PURCHASE_ORDER_TRIG_BIR" 

BEFORE INSERT ON PURCHASE_ORDER

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."PURCHASE_ORDER_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.retail_cost_biur.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RETAIL_COST_BIUR" 

BEFORE INSERT OR UPDATE ON retail_cost

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF :new.LAST_UPDATED_USER_ID is null then

:new.LAST_UPDATED_USER_ID := ''DRUG SERVICES'';

END IF;

:new.LAST_UPDATED_DATE := SYSTIMESTAMP;

END;

ALTER TRIGGER "SBMO"."RETAIL_COST_BIUR" ENABLE');
INSERT INTO ALL_TRIGGERS (FILE_NAME,DDL_CLOB) VALUES
	 ('sbmo.trigger.ret_and_adj_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RET_AND_ADJ_TRIG_BIR" 

BEFORE INSERT ON RETURN_AND_ADJUSTMENT

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."RET_AND_ADJ_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_cores_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_CORES_TRIG_BIR" 

BEFORE INSERT ON RX_CORES

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."RX_CORES_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_details_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_DETAILS_TRIG_BIR" 

BEFORE INSERT ON RX_DETAILS

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."RX_DETAILS_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_digital_documents_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_DIGITAL_DOCUMENTS_TRIG_BIR" 
before insert on rx_digital_documents
referencing new as new
for each row
BEGIN
IF INSERTING THEN
:new.created_date := SYSTIMESTAMP;
END IF;
END;

ALTER TRIGGER "SBMO"."RX_DIGITAL_DOCUMENTS_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_documents_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_DOCUMENTS_TRIG_BIR" 

before insert on rx_documents

referencing new as new

for each row

BEGIN

	IF INSERTING THEN

		:new.created_date := SYSTIMESTAMP;

	END IF;

END;

ALTER TRIGGER "SBMO"."RX_DOCUMENTS_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_image_data_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_IMAGE_DATA_TRIG_BIR" 
before insert on rx_image_data
referencing new as new
for each row
BEGIN
	IF INSERTING THEN
		:new.created_date := SYSTIMESTAMP;
	END IF;
END;

ALTER TRIGGER "SBMO"."RX_IMAGE_DATA_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_lots_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_LOTS_TRIG_BIR" 

BEFORE INSERT ON RX_LOTS

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;


ALTER TRIGGER "SBMO"."RX_LOTS_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_patstores_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_PATSTORES_TRIG_BIR" 

BEFORE INSERT ON RX_PATSTORES

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."RX_PATSTORES_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_print_chr_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_PRINT_CHR_TRIG_BIR" 

BEFORE INSERT ON RX_PRINT_CHR

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

	:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."RX_PRINT_CHR_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_print_info_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_PRINT_INFO_TRIG_BIR" 

BEFORE INSERT ON RX_PRINT_INFO

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."RX_PRINT_INFO_TRIG_BIR" ENABLE');
INSERT INTO ALL_TRIGGERS (FILE_NAME,DDL_CLOB) VALUES
	 ('sbmo.trigger.rx_req_err_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_REQ_ERR_TRIG_BIR" 

BEFORE INSERT ON RX_REQUEST_ERROR

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."RX_REQ_ERR_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_ship_pkg_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_SHIP_PKG_TRIG_BIR" 

BEFORE INSERT ON RX_SHIPPING_PACKAGES

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."RX_SHIP_PKG_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_tp_info_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_TP_INFO_TRIG_BIR" 

BEFORE INSERT ON RX_TP_INFO

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."RX_TP_INFO_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_vial_infos_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_VIAL_INFOS_TRIG_BIR" 

BEFORE INSERT ON RX_VIAL_INFOS

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."RX_VIAL_INFOS_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.rx_warning_labels_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."RX_WARNING_LABELS_TRIG_BIR" 

BEFORE INSERT ON RX_WARNING_LABELS

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."RX_WARNING_LABELS_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.system_messages_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."SYSTEM_MESSAGES_TRIG_BIR" 

BEFORE INSERT ON SYSTEM_MESSAGES

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."SYSTEM_MESSAGES_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.user_audit_log_trig_bir.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."USER_AUDIT_LOG_TRIG_BIR" 

BEFORE INSERT ON USER_AUDIT_LOG

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF INSERTING THEN

:new.created_date := SYSTIMESTAMP;

END IF;

END;

ALTER TRIGGER "SBMO"."USER_AUDIT_LOG_TRIG_BIR" ENABLE'),
	 ('sbmo.trigger.vendor_biur.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."VENDOR_BIUR" 

BEFORE INSERT OR UPDATE ON VENDOR

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF :new.LAST_UPDATED_USER_ID is null then

:new.LAST_UPDATED_USER_ID := ''UNKNOWN'';

END IF;

:new.LAST_UPDATED_DATE := SYSTIMESTAMP;

END;

ALTER TRIGGER "SBMO"."VENDOR_BIUR" ENABLE'),
	 ('sbmo.trigger.vendor_prop_biur.sql','
  CREATE OR REPLACE EDITIONABLE TRIGGER "SBMO"."VENDOR_PROP_BIUR" 

BEFORE INSERT OR UPDATE ON VENDOR_PROP

REFERENCING NEW AS new

FOR EACH ROW

BEGIN

IF :new.LAST_UPDATED_USER_ID is null then

:new.LAST_UPDATED_USER_ID := ''UNKNOWN'';

END IF;

:new.LAST_UPDATED_DATE := SYSTIMESTAMP;

END;

ALTER TRIGGER "SBMO"."VENDOR_PROP_BIUR" ENABLE');
