-- BATCH 6 CONSTRAINTS
-- Schema: SBMO

ALTER TABLE [SBMO].[RX_DETAILS]
ADD CONSTRAINT [RX_DETAILS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_DETAILS]
ADD CONSTRAINT [RX_DETAILS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_DETAILS]
ADD CONSTRAINT [RX_DETAILS_FK2] FOREIGN KEY ([TENANT_ID], [FILLED_DISPENSER_ID])
REFERENCES [SBMO].[DISPENSERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_DIGITAL_DOCUMENTS]
ADD CONSTRAINT [RX_DIGITAL_DOCUMENTS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_DIGITAL_DOCUMENTS]
ADD CONSTRAINT [RX_DIGITAL_DOCUMENTS_FK1] FOREIGN KEY ([TENANT_ID], [RX_CORES_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_DIGITAL_DOCUMENTS]
ADD CONSTRAINT [RX_DIGITAL_DOCUMENTS_FK2] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_DOCUMENTS]
ADD CONSTRAINT [RX_DOCUMENTS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_DOCUMENTS]
ADD CONSTRAINT [RX_DOCUMENTS_FK1] FOREIGN KEY ([TENANT_ID], [RX_CORES_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMIN_DOSES]
ADD CONSTRAINT [RX_HOURS_OF_ADMIN_DOSES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMIN_DOSES]
ADD CONSTRAINT [RX_HOURS_OF_ADMIN_DOSES_UK1] UNIQUE ([RX_HOURS_OF_ADMINISTRATION_ID], [TENANT_ID], [DATE_OF_DOSE], [TIME_OF_DOSE]);

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMIN_DOSES]
ADD CONSTRAINT [RX_HOURS_OF_ADMIN_DOSES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMIN_DOSES]
ADD CONSTRAINT [RX_HOURS_OF_ADMIN_DOSES_FK2] FOREIGN KEY ([TENANT_ID], [RX_HOURS_OF_ADMINISTRATION_ID])
REFERENCES [SBMO].[RX_HOURS_OF_ADMINISTRATION] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMINISTRATION]
ADD CONSTRAINT [RX_HOURS_OF_ADMINISTRATION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMINISTRATION]
ADD CONSTRAINT [RX_HOURS_OF_ADMINISTRATION_UK1] UNIQUE ([RX_CORES_ID], [TENANT_ID]);

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMINISTRATION]
ADD CONSTRAINT [RX_HOURS_OF_ADMINISTRATION_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMINISTRATION]
ADD CONSTRAINT [RX_HOURS_OF_ADMINISTRATION_FK2] FOREIGN KEY ([TENANT_ID], [RX_CORES_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_IMAGE_DATA]
ADD CONSTRAINT [RX_IMAGE_DATA_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_IMAGE_DATA]
ADD CONSTRAINT [RX_IMAGE_DATA_UK1] UNIQUE ([TENANT_ID], [RX_CORES_ID], [TYPE], [CREATED_DATE]);

ALTER TABLE [SBMO].[RX_IMAGE_DATA]
ADD CONSTRAINT [RX_IMAGE_DATA_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_IMAGE_DATA]
ADD CONSTRAINT [RX_IMAGE_DATA_FK2] FOREIGN KEY ([TENANT_ID], [RX_CORES_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_LOTS]
ADD CONSTRAINT [RX_LOTS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_LOTS]
ADD CONSTRAINT [RX_LOTS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_LOTS]
ADD CONSTRAINT [RX_LOTS_FK2] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_PATSTORES]
ADD CONSTRAINT [RX_PATSTORES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_PATSTORES]
ADD CONSTRAINT [RX_PATSTORES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_PRINT_CHR]
ADD CONSTRAINT [RX_PRINT_CHR_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_PRINT_CHR]
ADD CONSTRAINT [RX_PRINT_CHR_FK3] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_PRINT_CHR]
ADD CONSTRAINT [RX_PRINT_CHR_FK2] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_PRINT_INFO]
ADD CONSTRAINT [RX_PRINT_INFO_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_PRINT_INFO]
ADD CONSTRAINT [RX_PRINT_INFO_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_REQUEST_ERROR]
ADD CONSTRAINT [RX_REQUEST_ERROR_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_REQUEST_ERROR]
ADD CONSTRAINT [RX_REQUEST_ERROR_FK2] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_REQUEST_ERROR]
ADD CONSTRAINT [RX_REQUEST_ERROR_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_REQUEST_ERROR]
ADD CONSTRAINT [RX_REQUEST_ERROR_FK3] FOREIGN KEY ([TENANT_ID], [INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_REQUEST_ERROR]
ADD CONSTRAINT [RX_REQUEST_ERROR_FK4] FOREIGN KEY ([TENANT_ID], [VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_SHIPPING_PACKAGES]
ADD CONSTRAINT [RX_SHIPPING_PACKAGES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_SHIPPING_PACKAGES]
ADD CONSTRAINT [RX_SHIPPING_PACKAGES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_SHIPPING_PACKAGES]
ADD CONSTRAINT [RX_SHIPPING_PACKAGES_FK2] FOREIGN KEY ([TENANT_ID], [FILLED_DISPENSER_ID])
REFERENCES [SBMO].[DISPENSERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_SHIPPING_PACKAGES]
ADD CONSTRAINT [RX_SHIPPING_PACKAGES_FK3] FOREIGN KEY ([TENANT_ID], [PARENT_ID])
REFERENCES [SBMO].[RX_SHIPPING_PACKAGES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_STATE_TRANSITION]
ADD CONSTRAINT [RX_STATE_TRANSITION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_STATE_TRANSITION]
ADD CONSTRAINT [RX_STATE_TRANSITION_FK1] FOREIGN KEY ([TENANT_ID], [RX_CORE_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_TP_INFO]
ADD CONSTRAINT [RX_TP_INFO_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_TP_INFO]
ADD CONSTRAINT [RX_TP_INFO_FK2] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_TP_INFO]
ADD CONSTRAINT [RX_TP_INFO_FK3] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_VIAL_INFOS]
ADD CONSTRAINT [RX_VIAL_INFOS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_VIAL_INFOS]
ADD CONSTRAINT [RX_VIAL_INFOS_UK1] UNIQUE ([TENANT_ID], [RX_ID], [VIAL_NUMBER]);

ALTER TABLE [SBMO].[RX_VIAL_INFOS]
ADD CONSTRAINT [RX_VIAL_INFOS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_VIAL_INFOS]
ADD CONSTRAINT [RX_VIAL_INFOS_FK2] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_WARNING_LABEL_CODES]
ADD CONSTRAINT [RX_WARNING_LABEL_CODES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_WARNING_LABEL_CODES]
ADD CONSTRAINT [RX_WARNING_LABEL_CODES_FK2] FOREIGN KEY ([TENANT_ID], [RX_WARNING_LABEL_ID])
REFERENCES [SBMO].[RX_WARNING_LABELS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_WARNING_LABEL_CODES]
ADD CONSTRAINT [RX_WARNING_LABEL_CODES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_WARNING_LABELS]
ADD CONSTRAINT [RX_WARNING_LABELS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_WARNING_LABELS]
ADD CONSTRAINT [RX_WARNING_LABELS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_WARNING_LABELS]
ADD CONSTRAINT [RX_WARNING_LABELS_FK2] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SBMO_PROPERTIES]
ADD CONSTRAINT [SBMO_PROPERTIES_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[SBMO_PROPERTIES]
ADD CONSTRAINT [SBMO_PROPERTIES_UQ_KEY] UNIQUE ([KEY]);

ALTER TABLE [SBMO].[SCHEDULED_TASKS]
ADD CONSTRAINT [SCHEDULED_TASKS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SCHEDULED_TASKS]
ADD CONSTRAINT [SCHEDULED_TASKS_FK2] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SCHEDULED_TASKS]
ADD CONSTRAINT [SCHEDULED_TASKS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

