-- BATCH 8 FOREIGN KEY CONSTRAINTS
-- ----------------------------------------------------------------------------

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMIN_DOSES] ADD CONSTRAINT [RX_HOURS_OF_ADMIN_DOSES_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[RX_HOURS_OF_ADMIN_DOSES] ADD CONSTRAINT [RX_HOURS_OF_ADMIN_DOSES_FK2] FOREIGN KEY ([TENANT_ID], [RX_HOURS_OF_ADMINISTRATION_ID]) REFERENCES [SBMO].[RX_HOURS_OF_ADMINISTRATION] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[RX_WARNING_LABEL_CODES] ADD CONSTRAINT [RX_WARNING_LABEL_CODES_FK2] FOREIGN KEY ([TENANT_ID], [RX_WARNING_LABEL_ID]) REFERENCES [SBMO].[RX_WARNING_LABELS] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[RX_WARNING_LABEL_CODES] ADD CONSTRAINT [RX_WARNING_LABEL_CODES_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
