-- BATCH 7 FOREIGN KEY CONSTRAINTS
-- --------------------------------------------------------

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_FK2] FOREIGN KEY ([TENANT_ID], [DRUG_ORDER_ID])
REFERENCES [SBMO].[DRUG_ORDERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_FK3] FOREIGN KEY ([TENANT_ID], [FORMULARY_ID])
REFERENCES [SBMO].[FORMULARY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_FK4] FOREIGN KEY ([TENANT_ID], [RET_ADJ_ID])
REFERENCES [SBMO].[RETURN_AND_ADJUSTMENT] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_FK5] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_DOCUMENTS]
ADD CONSTRAINT [RX_DOCUMENTS_FK1] FOREIGN KEY ([TENANT_ID], [RX_CORES_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMINISTRATION]
ADD CONSTRAINT [RX_HOURS_OF_ADMINISTRATION_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMINISTRATION]
ADD CONSTRAINT [RX_HOURS_OF_ADMINISTRATION_FK2] FOREIGN KEY ([TENANT_ID], [RX_CORES_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_IMAGE_DATA]
ADD CONSTRAINT [RX_IMAGE_DATA_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_IMAGE_DATA]
ADD CONSTRAINT [RX_IMAGE_DATA_FK2] FOREIGN KEY ([TENANT_ID], [RX_CORES_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_LOTS]
ADD CONSTRAINT [RX_LOTS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_LOTS]
ADD CONSTRAINT [RX_LOTS_FK2] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_PRINT_CHR]
ADD CONSTRAINT [RX_PRINT_CHR_FK3] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_PRINT_CHR]
ADD CONSTRAINT [RX_PRINT_CHR_FK2] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_STATE_TRANSITION]
ADD CONSTRAINT [RX_STATE_TRANSITION_FK1] FOREIGN KEY ([TENANT_ID], [RX_CORE_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_TP_INFO]
ADD CONSTRAINT [RX_TP_INFO_FK2] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_TP_INFO]
ADD CONSTRAINT [RX_TP_INFO_FK3] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_VIAL_INFOS]
ADD CONSTRAINT [RX_VIAL_INFOS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_VIAL_INFOS]
ADD CONSTRAINT [RX_VIAL_INFOS_FK2] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_WARNING_LABELS]
ADD CONSTRAINT [RX_WARNING_LABELS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_WARNING_LABELS]
ADD CONSTRAINT [RX_WARNING_LABELS_FK2] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);
