-- BATCH 6 FOREIGN KEY CONSTRAINTS
-- --------------------------------------------------------

ALTER TABLE [SBMO].[CHARGE_PAYMENT_INFO]
ADD CONSTRAINT [CHARGE_PAYMENT_INFO_FK1] FOREIGN KEY ([TENANT_ID], [ORDER_ID])
REFERENCES [SBMO].[ORDERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DRUG_ORDER_PRODUCT_VERIFY]
ADD CONSTRAINT [DRUG_ORDER_PRODUCT_VERIFY_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[DRUG_ORDER_PRODUCT_VERIFY]
ADD CONSTRAINT [DRUG_ORDER_PRODUCT_VERIFY_FK2] FOREIGN KEY ([TENANT_ID], [DRUG_ORDERS_ID])
REFERENCES [SBMO].[DRUG_ORDERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DRUG_ORDER_PRODUCT_VERIFY]
ADD CONSTRAINT [DRUG_ORDER_PRODUCT_VERIFY_FK3] FOREIGN KEY ([TENANT_ID], [MASTER_PRODUCT_PO_VERIFY_ID])
REFERENCES [SBMO].[MASTER_PRODUCT_PO_VERIFY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_FK5] FOREIGN KEY ([TENANT_ID], [ITEM_LOCATION_ID])
REFERENCES [SBMO].[ITEM_LOCATION] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_FK6] FOREIGN KEY ([TENANT_ID], [ADJUSTMENT_GROUP_ID])
REFERENCES [SBMO].[ADJUSTMENT_GROUP] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURNADJUST_FK_ADJCODEID] FOREIGN KEY ([ADJUSTMENT_CODE_ID])
REFERENCES [SBMO].[ADJUSTMENT_CODES] ([ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_FK3] FOREIGN KEY ([TENANT_ID], [FORMULARY_ID])
REFERENCES [SBMO].[FORMULARY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_FK4] FOREIGN KEY ([TENANT_ID], [VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK8] FOREIGN KEY ([TENANT_ID], [FILLING_STATION_ID])
REFERENCES [SBMO].[FILLING_STATION] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK2] FOREIGN KEY ([TENANT_ID], [FILLED_VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK3] FOREIGN KEY ([TENANT_ID], [ORDER_ID])
REFERENCES [SBMO].[ORDERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK4] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[RX_DETAILS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK5] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[RX_PATSTORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK6] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[RX_PRINT_INFO] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK7] FOREIGN KEY ([TENANT_ID], [SHIPPING_PACKAGE_ID])
REFERENCES [SBMO].[RX_SHIPPING_PACKAGES] ([TENANT_ID], [ID]);
