-- BATCH 5 FOREIGN KEY CONSTRAINTS
-- ----------------------------------------------------------------------------

ALTER TABLE [SBMO].[CF_SEC_STORE] ADD CONSTRAINT [CF_SEC_STORE_FK2] FOREIGN KEY ([TENANT_ID], [CHAIN_ID]) REFERENCES [SBMO].[CF_SEC_CHAIN] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[CF_SEC_STORE] ADD CONSTRAINT [CF_SEC_STORE_FK3] FOREIGN KEY ([TENANT_ID], [ID]) REFERENCES [SBMO].[STORES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[CF_SEC_STORE] ADD CONSTRAINT [CF_SEC_STORE_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[DRUG_ORDERS] ADD CONSTRAINT [DRUG_ORDERS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[DRUG_ORDERS] ADD CONSTRAINT [DRUG_ORDERS_FK2] FOREIGN KEY ([TENANT_ID], [FORMULARY_ID]) REFERENCES [SBMO].[FORMULARY] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[DRUG_ORDERS] ADD CONSTRAINT [DRUG_ORDERS_FK3] FOREIGN KEY ([TENANT_ID], [PURCHASE_ORDER_ID]) REFERENCES [SBMO].[PURCHASE_ORDER] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[ITEM_LOCATION] ADD CONSTRAINT [ITEM_LOCATION_FK2] FOREIGN KEY ([TENANT_ID], [FORMULARY_ID]) REFERENCES [SBMO].[FORMULARY] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[ITEM_LOCATION] ADD CONSTRAINT [ITEM_LOCATION_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[MASTER_PRODUCT_PO_VERIFY] ADD CONSTRAINT [MASTER_PRODUCT_PO_VERIFY_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[MASTER_PRODUCT_PO_VERIFY] ADD CONSTRAINT [MASTER_PRODUCT_PO_VERIFY_FK2] FOREIGN KEY ([TENANT_ID], [PURCHASE_ORDER_ID]) REFERENCES [SBMO].[PURCHASE_ORDER] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[MASTER_PRODUCT_PO_VERIFY] ADD CONSTRAINT [MASTER_PRODUCT_PO_VERIFY_FK3] FOREIGN KEY ([TENANT_ID], [VENDOR_ID]) REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[MESSAGE_LOG] ADD CONSTRAINT [MESSAGE_LOG_FK2] FOREIGN KEY ([TENANT_ID], [STORE_ID]) REFERENCES [SBMO].[STORES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[MESSAGE_LOG] ADD CONSTRAINT [MESSAGE_LOG_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[ORDERS] ADD CONSTRAINT [ORDERS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[ORDERS] ADD CONSTRAINT [ORDERS_FK2] FOREIGN KEY ([TENANT_ID], [INVENTORY_ID]) REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[ORDERS] ADD CONSTRAINT [ORDERS_FK3] FOREIGN KEY ([TENANT_ID], [STORE_ID]) REFERENCES [SBMO].[STORES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[PRIORITY_CHANGE_ALERTS] ADD CONSTRAINT [PRIORITY_CHANGE_ALERTS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID]) REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[PRIORITY_CHANGE_ALERTS] ADD CONSTRAINT [PRIORITY_CHANGE_ALERTS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[PRIORITY_CHANGE_ALERTS] ADD CONSTRAINT [PRIORITY_CHANGE_ALERTS_FK2] FOREIGN KEY ([TENANT_ID], [FORMULARY_ID]) REFERENCES [SBMO].[FORMULARY] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[STORE_SHIP_VIA] ADD CONSTRAINT [STORE_SHIP_VIA_FK2] FOREIGN KEY ([TENANT_ID], [STORE_ID]) REFERENCES [SBMO].[STORES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[STORE_SHIP_VIA] ADD CONSTRAINT [STORE_SHIP_VIA_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[STORE_VENDOR_ACCOUNT] ADD CONSTRAINT [STORE_VENDOR_ACCOUNT_FK2] FOREIGN KEY ([TENANT_ID], [STORE_ID]) REFERENCES [SBMO].[STORES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[STORE_VENDOR_ACCOUNT] ADD CONSTRAINT [STORE_VENDOR_ACCOUNT_FK3] FOREIGN KEY ([TENANT_ID], [VENDOR_ID]) REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[STORE_VENDOR_ACCOUNT] ADD CONSTRAINT [STORE_VENDOR_ACCOUNT_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
