-- BATCH 3 FOREIGN KEY CONSTRAINTS
-- ----------------------------------------------------------------------------

ALTER TABLE [SBMO].[ADJUSTMENT_GROUP] ADD CONSTRAINT [ADJUSTMENT_GROUP_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[ADJUSTMENT_GROUP] ADD CONSTRAINT [ADJUSTMENT_GROUP_FK2] FOREIGN KEY ([TENANT_ID], [INVENTORY_ID]) REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[CHAINS] ADD CONSTRAINT [CHAINS_FK2] FOREIGN KEY ([TENANT_ID], [PARENT_ID]) REFERENCES [SBMO].[CHAINS] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[CHAINS] ADD CONSTRAINT [CHAINS_FK3] FOREIGN KEY ([TENANT_ID], [ID]) REFERENCES [SBMO].[ENTITIES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[CHAINS] ADD CONSTRAINT [CHAINS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[CONTACTS] ADD CONSTRAINT [CONTACTS_FK2] FOREIGN KEY ([TENANT_ID], [ENTITY_ID]) REFERENCES [SBMO].[ENTITIES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[CONTACTS] ADD CONSTRAINT [CONTACTS_FK3] FOREIGN KEY ([TENANT_ID], [ID]) REFERENCES [SBMO].[PHONE_ADDRESS_OWNERS] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[CONTACTS] ADD CONSTRAINT [CONTACTS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[CUSTOM_SCHEDULED_TASK] ADD CONSTRAINT [CUSTOM_SCHEDULED_TASK_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID]) REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[CUSTOM_SCHEDULED_TASK] ADD CONSTRAINT [CUSTOM_SCHEDULED_TASK_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[CUSTOM_SCHEDULED_TASK] ADD CONSTRAINT [CUSTOM_SCHEDULED_TASK_FK2] FOREIGN KEY ([TENANT_ID], [ID]) REFERENCES [SBMO].[SCHEDULED_TASKS] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[DAILY_SCHEDULED_TASKS] ADD CONSTRAINT [DAILY_SCHEDULED_TASKS_FK2] FOREIGN KEY ([TENANT_ID], [ID]) REFERENCES [SBMO].[SCHEDULED_TASKS] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[DAILY_SCHEDULED_TASKS] ADD CONSTRAINT [DAILY_SCHEDULED_TASKS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[DAILY_SCHEDULED_TASKS] ADD CONSTRAINT [DAILY_SCHEDULED_TASKS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID]) REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[DISPENSERS] ADD CONSTRAINT [DISPENSERS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID]) REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[DISPENSERS] ADD CONSTRAINT [DISPENSERS_FK2] FOREIGN KEY ([TENANT_ID], [INVENTORY_ID]) REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[DISPENSERS] ADD CONSTRAINT [DISPENSERS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[MONTHLY_SCHEDULED_TASKS] ADD CONSTRAINT [MONTHLY_SCHEDULED_TASKS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID]) REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[MONTHLY_SCHEDULED_TASKS] ADD CONSTRAINT [MONTHLY_SCHEDULED_TASKS_FK2] FOREIGN KEY ([TENANT_ID], [ID]) REFERENCES [SBMO].[SCHEDULED_TASKS] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[MONTHLY_SCHEDULED_TASKS] ADD CONSTRAINT [MONTHLY_SCHEDULED_TASKS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[ONCE_SCHEDULED_TASKS] ADD CONSTRAINT [ONCE_SCHEDULED_TASKS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID]) REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[ONCE_SCHEDULED_TASKS] ADD CONSTRAINT [ONCE_SCHEDULED_TASKS_FK2] FOREIGN KEY ([TENANT_ID], [ID]) REFERENCES [SBMO].[SCHEDULED_TASKS] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[ONCE_SCHEDULED_TASKS] ADD CONSTRAINT [ONCE_SCHEDULED_TASKS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[PDX_SCHEMA_TASK_ERROR_LOG] ADD CONSTRAINT [PDX_SCHEMA_TASK_ERROR_LOG_FK1] FOREIGN KEY ([ID]) REFERENCES [SBMO].[PDX_SCHEMA_TASK_HISTORY] ([ID]);
ALTER TABLE [SBMO].[PURCHASE_ORDER_GROUP] ADD CONSTRAINT [PURCHASE_ORDER_GROUP_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[PURCHASE_ORDER_GROUP] ADD CONSTRAINT [PURCHASE_ORDER_GROUP_FK2] FOREIGN KEY ([TENANT_ID], [INVENTORY_ID]) REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[PURGE_HISTORY_CHUNKS] ADD CONSTRAINT [PURGE_HISTORY_CHUNKS_FK1] FOREIGN KEY ([ID_PURGE_HISTORY_PARTITIONS]) REFERENCES [SBMO].[PURGE_HISTORY_PARTITIONS] ([ID]);
ALTER TABLE [SBMO].[REPORT_REQUEST_PARAMETER] ADD CONSTRAINT [REPORT_REQUEST_PARAMETER_FK1] FOREIGN KEY ([TENANT_ID], [REPORT_REQUEST_ID]) REFERENCES [SBMO].[REPORT_REQUEST] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[VENDOR] ADD CONSTRAINT [VENDOR_FK2] FOREIGN KEY ([TENANT_ID], [ID]) REFERENCES [SBMO].[ENTITIES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[VENDOR] ADD CONSTRAINT [VENDOR_FK3] FOREIGN KEY ([TENANT_ID], [ID]) REFERENCES [SBMO].[VENDOR_PROP] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[VENDOR] ADD CONSTRAINT [VENDOR_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[WEEKLY_SCHEDULED_TASKS] ADD CONSTRAINT [WEEKLY_SCHEDULED_TASKS_FK2] FOREIGN KEY ([TENANT_ID], [ID]) REFERENCES [SBMO].[SCHEDULED_TASKS] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[WEEKLY_SCHEDULED_TASKS] ADD CONSTRAINT [WEEKLY_SCHEDULED_TASKS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID]) REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[WEEKLY_SCHEDULED_TASKS] ADD CONSTRAINT [WEEKLY_SCHEDULED_TASKS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
