-- BATCH 2 INDEXES
-- ----------------------------------------------------------------------------

CREATE INDEX [ADDRESSES_IX2] ON [SBMO].[ADDRESSES] ([TENANT_ID], [OWNER_ID]);
CREATE INDEX [AUDIT_LOG_IX2] ON [SBMO].[AUDIT_LOG] ([TENANT_ID], [TIME_STAMP], [NEW_VALUE]);
CREATE INDEX [DASHBOARD_SETTINGS_IX1] ON [SBMO].[DASHBOARD_SETTINGS] ([TENANT_ID]);
CREATE INDEX [DASHBOARD_STATISTICS_IX1] ON [SBMO].[DASHBOARD_STATISTICS] ([TENANT_ID]);
CREATE INDEX [ENCRYPTION_KEYS_AUDIT_IX1] ON [SBMO].[ENCRYPTION_KEYS_AUDIT] ([TENANT_ID]);
CREATE UNIQUE INDEX [ENTITIES_PK] ON [SBMO].[ENTITIES] ([TENANT_ID], [ID]);
CREATE INDEX [FILLING_STATION_IX1] ON [SBMO].[FILLING_STATION] ([TENANT_ID]);
CREATE INDEX [INVENTORY_IX2] ON [SBMO].[INVENTORY] ([TENANT_ID], [FACILITY_ID]);
CREATE INDEX [PDX_SCHEMA_PROCESS_HISTORY_IX1] ON [SBMO].[PDX_SCHEMA_PROCESS_HISTORY] ([PDX_SCHEMA_UPD_PKGCALL_HIST_ID]);
CREATE INDEX [PDX_SCHEMA_TASK_HISTORY_IX2] ON [SBMO].[PDX_SCHEMA_TASK_HISTORY] ([PDX_SCHEMA_UPD_PKGCALL_HIST_ID]);
CREATE UNIQUE INDEX [PDX_SCHEMA_VERSION_ERR_LOG_PK] ON [SBMO].[PDX_SCHEMA_VERSION_ERROR_LOG] ([ID]);
CREATE INDEX [PHONES_IX2] ON [SBMO].[PHONES] ([TENANT_ID], [OWNER_ID]);
CREATE INDEX [PURGE_HISTORY_PARTITIONS_IX1] ON [SBMO].[PURGE_HISTORY_PARTITIONS] ([ID_PURGE_HISTORY]);
CREATE UNIQUE INDEX [QRTZ_BLOB_TRIGGERS_PK] ON [SBMO].[QRTZ_BLOB_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);
CREATE UNIQUE INDEX [QRTZ_CRON_TRIGGERS_PK] ON [SBMO].[QRTZ_CRON_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);
CREATE UNIQUE INDEX [QRTZ_SIMPLE_TRIGGERS_PK] ON [SBMO].[QRTZ_SIMPLE_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);
CREATE UNIQUE INDEX [QRTZ_SIMPROP_TRIGGERS_PK] ON [SBMO].[QRTZ_SIMPROP_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);
CREATE INDEX [REPORT_REQUEST_IX1] ON [SBMO].[REPORT_REQUEST] ([TENANT_ID], [FACILITY_ID]);
CREATE INDEX [RX_CORES_MIN_DATE_IX2] ON [SBMO].[RX_CORES_MIN_DATE] ([TENANT_ID], [FACILITY_ID]);
CREATE INDEX [SCHEDULED_TASKS_IX2] ON [SBMO].[SCHEDULED_TASKS] ([TENANT_ID], [FACILITY_ID]);
CREATE INDEX [SHIP_ITEMS_IX2] ON [SBMO].[SHIP_ITEMS] ([TENANT_ID], [SHIPMENT_ID]);
CREATE INDEX [SYSTEM_MESSAGES_IX1] ON [SBMO].[SYSTEM_MESSAGES] ([TENANT_ID], [REFERENCE_ID], [REFERENCE_TYPE]);
