-- BATCH 1 INDEXES
-- ----------------------------------------------------------------------------

CREATE UNIQUE INDEX [BIN_UPC_LINK_PK] ON [SBMO].[BIN_UPC_LINK] ([TENANT_ID], [ID]);
CREATE INDEX [CARRIER_IX1] ON [SBMO].[CARRIER] ([TENANT_ID]);
CREATE INDEX [ENCRYPTION_KEYS_IX1] ON [SBMO].[ENCRYPTION_KEYS] ([TENANT_ID]);
CREATE INDEX [FACILITIES_IX1] ON [SBMO].[FACILITIES] ([TENANT_ID]);
CREATE UNIQUE INDEX [FORMULARY_REORDER_PK] ON [SBMO].[FORMULARY_REORDER] ([TENANT_ID], [ID]);
CREATE UNIQUE INDEX [INVENTORY_DATE_PK] ON [SBMO].[INVENTORY_DATE] ([TENANT_ID], [ID]);
CREATE UNIQUE INDEX [LABEL_IMAGES_PK] ON [SBMO].[LABEL_IMAGES] ([TENANT_ID], [ID]);
CREATE INDEX [LOCATION_IX2] ON [SBMO].[LOCATION] ([TENANT_ID], [PARENT_ID]);
CREATE INDEX [PDX_SCHEMA_UPD_HLPR_DBG_D_IX1] ON [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_D] ([PDX_SCHEMA_UPD_HLPR_DBG_H_ID]);
CREATE UNIQUE INDEX [PDX_SCHEMA_UPD_PKGCALL_ELOG_PK] ON [SBMO].[PDX_SCHEMA_UPD_PKGCALL_ERR_LOG] ([ID]);
CREATE INDEX [PDX_SCHEMA_VERSION_HISTORY_IX1] ON [SBMO].[PDX_SCHEMA_VERSION_HISTORY] ([PDX_SCHEMA_UPD_PKGCALL_HIST_ID]);
CREATE UNIQUE INDEX [PHONE_ADDRESS_OWNERS_PK] ON [SBMO].[PHONE_ADDRESS_OWNERS] ([TENANT_ID], [ID]);
CREATE INDEX [PURGE_HISTORY_IX1] ON [SBMO].[PURGE_HISTORY] ([TABLE_NAME]);
CREATE INDEX [IDX_QRTZ_T_NFT_ST] ON [SBMO].[QRTZ_TRIGGERS] ([NEXT_FIRE_TIME], [TRIGGER_STATE]);
CREATE UNIQUE INDEX [REGION_PK] ON [SBMO].[REGION] ([TENANT_ID], [ID]);
CREATE UNIQUE INDEX [RX_PATSTORES_PK] ON [SBMO].[RX_PATSTORES] ([TENANT_ID], [ID]);
CREATE UNIQUE INDEX [RX_PRINT_INFO_PK] ON [SBMO].[RX_PRINT_INFO] ([TENANT_ID], [ID]);
CREATE UNIQUE INDEX [SHIPMENT_PK] ON [SBMO].[SHIPMENT] ([TENANT_ID], [ID]);
CREATE UNIQUE INDEX [VENDOR_PROP_PK] ON [SBMO].[VENDOR_PROP] ([TENANT_ID], [ID]);
