-- BATCH 7 INDEXES
-- ----------------------------------------------------------------------------

CREATE INDEX [INVENTORY_AUDIT_IX2] ON [SBMO].[INVENTORY_AUDIT] ([TENANT_ID], [DRUG_ORDER_ID]);
CREATE INDEX [MEDICAL_SUPPLIES_IX1] ON [SBMO].[MEDICAL_SUPPLIES] ([TENANT_ID]);
CREATE INDEX [RX_DIGITAL_DOCUMENTS_IX1] ON [SBMO].[RX_DIGITAL_DOCUMENTS] ([RX_CORES_ID], [TENANT_ID]);
CREATE INDEX [RX_DOCUMENTS_IX1] ON [SBMO].[RX_DOCUMENTS] ([TENANT_ID], [RX_CORES_ID]);
CREATE INDEX [RX_HOURS_OF_ADMINISTRATION_IX1] ON [SBMO].[RX_HOURS_OF_ADMINISTRATION] ([TENANT_ID]);
CREATE INDEX [RX_IMAGE_DATA_IX1] ON [SBMO].[RX_IMAGE_DATA] ([TENANT_ID]);
CREATE INDEX [RX_LOTS_IX2] ON [SBMO].[RX_LOTS] ([TENANT_ID], [RX_ID]);
CREATE INDEX [RX_PRINT_CHR_IX3] ON [SBMO].[RX_PRINT_CHR] ([TENANT_ID], [RX_ID]);
CREATE INDEX [RX_STATE_TRANSITION_IX1] ON [SBMO].[RX_STATE_TRANSITION] ([TENANT_ID], [RX_CORE_ID]);
CREATE INDEX [RX_TP_INFO_IX3] ON [SBMO].[RX_TP_INFO] ([TENANT_ID], [RX_ID]);
CREATE INDEX [RX_VIAL_INFOS_IX2] ON [SBMO].[RX_VIAL_INFOS] ([TENANT_ID], [RX_ID]);
CREATE INDEX [RX_WARNING_LABELS_IX3] ON [SBMO].[RX_WARNING_LABELS] ([TENANT_ID], [RX_ID], [ID], [IDX]);
