-- BATCH 4 INDEXES
-- ----------------------------------------------------------------------------

CREATE UNIQUE INDEX [CF_SEC_CHAIN_PK] ON [SBMO].[CF_SEC_CHAIN] ([TENANT_ID], [ID]);
CREATE INDEX [DISPENSER_LOCATION_IX2] ON [SBMO].[DISPENSER_LOCATION] ([TENANT_ID], [DISPENSER_ID]);
CREATE INDEX [FORMULARY_IX1] ON [SBMO].[FORMULARY] ([TENANT_ID], [DRUG_ID]);
CREATE INDEX [PURCHASE_ORDER_IX2] ON [SBMO].[PURCHASE_ORDER] ([TENANT_ID], [PO_GROUP_ID]);
CREATE INDEX [RETAIL_COST_IX1] ON [SBMO].[RETAIL_COST] ([TENANT_ID], [DRUG_ID]);
CREATE INDEX [RX_DETAILS_IX2] ON [SBMO].[RX_DETAILS] ([TENANT_ID], [FILLED_DISPENSER_ID]);
CREATE INDEX [RX_REQUEST_ERROR_IX1] ON [SBMO].[RX_REQUEST_ERROR] ([TENANT_ID], [ADDED_DATE]);
CREATE INDEX [RX_SHIPPING_PACKAGES_IX2] ON [SBMO].[RX_SHIPPING_PACKAGES] ([TENANT_ID], [FILLED_DISPENSER_ID]);
CREATE INDEX [STORES_IX10] ON [SBMO].[STORES] ([TENANT_ID], [MAIL_ORIG_INVENTORY_ID]);
CREATE INDEX [VENDOR_ITEM_PROP_IX1] ON [SBMO].[VENDOR_ITEM_PROP] ([TENANT_ID], [DRUG_ID]);
CREATE INDEX [VENDOR_PO_CREATE_DAYS_IX1] ON [SBMO].[VENDOR_PO_CREATE_DAYS] ([TENANT_ID]);
