-- BATCH 3 INDEXES
-- ----------------------------------------------------------------------------

CREATE INDEX [ADJUSTMENT_GROUP_IX2] ON [SBMO].[ADJUSTMENT_GROUP] ([TENANT_ID], [INVENTORY_ID]);
CREATE INDEX [CHAINS_IX2] ON [SBMO].[CHAINS] ([TENANT_ID], [PARENT_ID]);
CREATE INDEX [CONTACTS_IX2] ON [SBMO].[CONTACTS] ([TENANT_ID], [ENTITY_ID]);
CREATE INDEX [CUSTOM_SCHEDULED_TASK_IX1] ON [SBMO].[CUSTOM_SCHEDULED_TASK] ([TENANT_ID]);
CREATE INDEX [DAILY_SCHEDULED_TASKS_IX2] ON [SBMO].[DAILY_SCHEDULED_TASKS] ([TENANT_ID], [FACILITY_ID]);
CREATE INDEX [DISPENSERS_IX2] ON [SBMO].[DISPENSERS] ([TENANT_ID], [INVENTORY_ID]);
CREATE INDEX [MONTHLY_SCHEDULED_TASKS_IX2] ON [SBMO].[MONTHLY_SCHEDULED_TASKS] ([TENANT_ID], [FACILITY_ID]);
CREATE INDEX [ONCE_SCHEDULED_TASKS_IX2] ON [SBMO].[ONCE_SCHEDULED_TASKS] ([TENANT_ID], [FACILITY_ID]);
CREATE UNIQUE INDEX [PDX_SCHEMA_TASK_ERROR_LOG_PK] ON [SBMO].[PDX_SCHEMA_TASK_ERROR_LOG] ([ID]);
CREATE INDEX [PURCHASE_ORDER_GROUP_IX2] ON [SBMO].[PURCHASE_ORDER_GROUP] ([TENANT_ID], [INVENTORY_ID]);
CREATE INDEX [PURGE_HISTORY_CHUNKS_IX1] ON [SBMO].[PURGE_HISTORY_CHUNKS] ([ID_PURGE_HISTORY_PARTITIONS]);
CREATE INDEX [REPORT_REQUEST_PARAMETER_IX1] ON [SBMO].[REPORT_REQUEST_PARAMETER] ([TENANT_ID], [REPORT_REQUEST_ID]);
CREATE UNIQUE INDEX [VENDOR_PK] ON [SBMO].[VENDOR] ([TENANT_ID], [ID]);
CREATE INDEX [WEEKLY_SCHEDULED_TASKS_IX2] ON [SBMO].[WEEKLY_SCHEDULED_TASKS] ([TENANT_ID], [FACILITY_ID]);
