-- BATCH 7 PRIMARY KEY & UNIQUE CONSTRAINTS
-- --------------------------------------------------------

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_DOCUMENTS]
ADD CONSTRAINT [RX_DOCUMENTS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_HOURS_OF_ADMINISTRATION]
ADD CONSTRAINT [RX_HOURS_OF_ADMINISTRATION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_IMAGE_DATA]
ADD CONSTRAINT [RX_IMAGE_DATA_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_IMAGE_DATA]
ADD CONSTRAINT [RX_IMAGE_DATA_UK1] UNIQUE ([TENANT_ID], [RX_CORES_ID], [TYPE], [CREATED_DATE]);

ALTER TABLE [SBMO].[RX_LOTS]
ADD CONSTRAINT [RX_LOTS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_PRINT_CHR]
ADD CONSTRAINT [RX_PRINT_CHR_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_STATE_TRANSITION]
ADD CONSTRAINT [RX_STATE_TRANSITION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_TP_INFO]
ADD CONSTRAINT [RX_TP_INFO_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_VIAL_INFOS]
ADD CONSTRAINT [RX_VIAL_INFOS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_VIAL_INFOS]
ADD CONSTRAINT [RX_VIAL_INFOS_UK1] UNIQUE ([TENANT_ID], [RX_ID], [VIAL_NUMBER]);

ALTER TABLE [SBMO].[RX_WARNING_LABELS]
ADD CONSTRAINT [RX_WARNING_LABELS_PK] PRIMARY KEY ([TENANT_ID], [ID]);
