-- BATCH 8 PRIMARY KEY & UNIQUE CONSTRAINTS
-- --------------------------------------------------------

ALTER TABLE [SBMO].[RX_WARNING_LABEL_CODES]
ADD CONSTRAINT [RX_WARNING_LABEL_CODES_PK] PRIMARY KEY ([TENANT_ID], [ID]);
