-- BATCH 3 PRIMARY KEY & UNIQUE CONSTRAINTS
-- --------------------------------------------------------

ALTER TABLE [SBMO].[ADJUSTMENT_GROUP]
ADD CONSTRAINT [ADJUSTMENT_GROUP_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CHAINS]
ADD CONSTRAINT [CHAINS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CHAINS]
ADD CONSTRAINT [CHAINS_UQ_HQID] UNIQUE ([HQ_ID]);

ALTER TABLE [SBMO].[CHAINS]
ADD CONSTRAINT [CHAINS_UQ_NHINID] UNIQUE ([NHINID]);

ALTER TABLE [SBMO].[CONTACTS]
ADD CONSTRAINT [CONTACTS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CUSTOM_SCHEDULED_TASK]
ADD CONSTRAINT [CUSTOM_SCHEDULED_TASK_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CUSTOM_SCHEDULED_TASK]
ADD CONSTRAINT [CUSTOM_SCHEDULED_TASK_UK1] UNIQUE ([TENANT_ID], [TASK_DAY], [SCHEDULE_GROUPING]);

ALTER TABLE [SBMO].[DAILY_SCHEDULED_TASKS]
ADD CONSTRAINT [DAILY_SCHEDULED_TASKS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DISPENSERS]
ADD CONSTRAINT [DISPENSERS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MONTHLY_SCHEDULED_TASKS]
ADD CONSTRAINT [MONTHLY_SCHEDULED_TASKS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ONCE_SCHEDULED_TASKS]
ADD CONSTRAINT [ONCE_SCHEDULED_TASKS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PURCHASE_ORDER_GROUP]
ADD CONSTRAINT [PURCHASE_ORDER_GROUP_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[REPORT_REQUEST_PARAMETER]
ADD CONSTRAINT [REPORT_REQUEST_PARAMETER_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR]
ADD CONSTRAINT [VENDOR_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR]
ADD CONSTRAINT [VENDOR_UK1] UNIQUE ([TENANT_ID], [NHINVEN]);

ALTER TABLE [SBMO].[WEEKLY_SCHEDULED_TASKS]
ADD CONSTRAINT [WEEKLY_SCHEDULED_TASKS_PK] PRIMARY KEY ([TENANT_ID], [ID]);
