-- BATCH 2 PRIMARY KEY AND UNIQUE CONSTRAINTS
-- ------------------------------------------------------------------

ALTER TABLE [SBMO].[PDX_SCHEMA_PROCESS_HISTORY] ADD CONSTRAINT [PK_PDX_SCHEMA_PROCESS_HISTORY] PRIMARY KEY ([ID]);
ALTER TABLE [SBMO].[PDX_SCHEMA_TASK_HISTORY] ADD CONSTRAINT [PK_PDX_SCHEMA_TASK_HISTORY] PRIMARY KEY ([ID]);
ALTER TABLE [SBMO].[PDX_SCHEMA_VERSION_ERROR_LOG] ADD CONSTRAINT [PK_PDX_SCHEMA_VERSION_ERROR_LOG] PRIMARY KEY ([ID]);
ALTER TABLE [SBMO].[PURGE_HISTORY_PARTITIONS] ADD CONSTRAINT [PK_PURGE_HISTORY_PARTITIONS] PRIMARY KEY ([ID]);
