-- BATCH 1 PRIMARY KEY & UNIQUE CONSTRAINTS
-- --------------------------------------------------------

ALTER TABLE [SBMO].[BIN_UPC_LINK]
ADD CONSTRAINT [BIN_UPC_LINK_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CARRIER]
ADD CONSTRAINT [CARRIER_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CARRIER]
ADD CONSTRAINT [CARRIER_UK1] UNIQUE ([TENANT_ID], [NAME]);

ALTER TABLE [SBMO].[CARRIER]
ADD CONSTRAINT [CARRIER_UK2] UNIQUE ([TENANT_ID], [SHIP_IDENT]);

ALTER TABLE [SBMO].[CARRIER]
ADD CONSTRAINT [CARRIER_UK3] UNIQUE ([TENANT_ID], [SHIP_PRIORITY]);

ALTER TABLE [SBMO].[FACILITIES]
ADD CONSTRAINT [FACILITIES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FACILITIES]
ADD CONSTRAINT [FACILITIES_UK1] UNIQUE ([TENANT_ID], [SHORT_NAME], [NAME]);

ALTER TABLE [SBMO].[FORMULARY_REORDER]
ADD CONSTRAINT [FORMULARY_REORDER_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY_DATE]
ADD CONSTRAINT [INVENTORY_DATE_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[LABEL_IMAGES]
ADD CONSTRAINT [LABEL_IMAGES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[LABEL_IMAGES]
ADD CONSTRAINT [LABEL_IMAGES_UK1] UNIQUE ([TENANT_ID], [IMAGE_NAME]);

ALTER TABLE [SBMO].[LABEL_IMAGES]
ADD CONSTRAINT [LABEL_IMAGES_UQ_IMAGE_NAME] UNIQUE ([IMAGE_NAME]);

ALTER TABLE [SBMO].[LOCATION]
ADD CONSTRAINT [LOCATION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[LOCATION]
ADD CONSTRAINT [LOCATION_UK1] UNIQUE ([TENANT_ID], [DESCRIPTOR], [PARENT_ID], [LOCATION_TYPE]);

ALTER TABLE [SBMO].[PHONE_ADDRESS_OWNERS]
ADD CONSTRAINT [PHONE_ADDRESS_OWNERS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[REGION]
ADD CONSTRAINT [REGION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[REGION]
ADD CONSTRAINT [REGION_UK1] UNIQUE ([TENANT_ID], [NAME]);

ALTER TABLE [SBMO].[RX_PATSTORES]
ADD CONSTRAINT [RX_PATSTORES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_PRINT_INFO]
ADD CONSTRAINT [RX_PRINT_INFO_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SHIPMENT]
ADD CONSTRAINT [SHIPMENT_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR_PROP]
ADD CONSTRAINT [VENDOR_PROP_PK] PRIMARY KEY ([TENANT_ID], [ID]);
