-- BATCH 4 PRIMARY KEY AND UNIQUE CONSTRAINTS
-- ------------------------------------------------------------------

ALTER TABLE [SBMO].[STORES] ADD CONSTRAINT [STORES_UK2] UNIQUE ([NPI_NUM]);
ALTER TABLE [SBMO].[STORES] ADD CONSTRAINT [STORES_UQ_NHINID] UNIQUE ([NHINID]);
