-- BATCH 2 PRIMARY KEY & UNIQUE CONSTRAINTS
-- --------------------------------------------------------

ALTER TABLE [SBMO].[ADDRESSES]
ADD CONSTRAINT [ADDRESSES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[AUDIT_LOG]
ADD CONSTRAINT [AUDIT_LOG_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DASHBOARD_SETTINGS]
ADD CONSTRAINT [DASHBOARD_SETTINGS_PK] PRIMARY KEY ([TENANT_ID], [FACILITY_ID], [ID]);

ALTER TABLE [SBMO].[DASHBOARD_SETTINGS]
ADD CONSTRAINT [DASHBOARD_SETTINGS_UK1] UNIQUE ([TENANT_ID], [FACILITY_ID], [DAY_OF_WEEK]);

ALTER TABLE [SBMO].[DASHBOARD_STATISTICS]
ADD CONSTRAINT [DASHBOARD_STATISTICS_PK] PRIMARY KEY ([TENANT_ID], [FACILITY_ID], [ID]);

ALTER TABLE [SBMO].[ENTITIES]
ADD CONSTRAINT [ENTITIES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FILLING_STATION]
ADD CONSTRAINT [FILLING_STATION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FILLING_STATION]
ADD CONSTRAINT [FILLING_STATION_UK1] UNIQUE ([TENANT_ID], [FACILITY_ID], [DESCRIPTION]);

ALTER TABLE [SBMO].[INVENTORY]
ADD CONSTRAINT [INVENTORY_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY]
ADD CONSTRAINT [INVENTORY_UK1] UNIQUE ([TENANT_ID], [NAME]);

ALTER TABLE [SBMO].[PHONES]
ADD CONSTRAINT [PHONES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PHONES]
ADD CONSTRAINT [PHONES_UK1] UNIQUE ([TENANT_ID], [OWNER_ID], [IDX]);

ALTER TABLE [SBMO].[REPORT_REQUEST]
ADD CONSTRAINT [REPORT_REQUEST_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES_MIN_DATE]
ADD CONSTRAINT [RX_CORES_MIN_DATE_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES_MIN_DATE]
ADD CONSTRAINT [RX_CORES_MIN_DATE_UK1] UNIQUE ([TENANT_ID], [FACILITY_ID], [DATE_TYPE], [STATUS]);

ALTER TABLE [SBMO].[SCHEDULED_TASKS]
ADD CONSTRAINT [SCHEDULED_TASKS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SHIP_ITEMS]
ADD CONSTRAINT [SHIP_ITEMS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SYSTEM_MESSAGES]
ADD CONSTRAINT [SYSTEM_MESSAGES_PK] PRIMARY KEY ([TENANT_ID], [ID]);
