-- BATCH 0 PRIMARY KEY & UNIQUE CONSTRAINTS
-- --------------------------------------------------------

ALTER TABLE [SBMO].[ADJUSTMENT_CODES]
ADD CONSTRAINT [ADJUSTMENT_CODES_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[AUDIT_DBU_LOG]
ADD CONSTRAINT [AUDIT_DBU_LOG_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[DRUGS]
ADD CONSTRAINT [DRUGS_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[MUTEX]
ADD CONSTRAINT [MUTEX_PK] PRIMARY KEY ([NAME]);

ALTER TABLE [SBMO].[PARTITION_SQL_HISTORY]
ADD CONSTRAINT [SQL_HISTORY_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_DBA_APPLIED]
ADD CONSTRAINT [PDX_DBA_APPLIED_PK] PRIMARY KEY ([TASK_NAME]);

ALTER TABLE [SBMO].[PDX_SCHEMA_CONFIG]
ADD CONSTRAINT [PDX_SCHEMA_CONFIG_PK] PRIMARY KEY ([KEY]);

ALTER TABLE [SBMO].[PDX_SCHEMA_FILE_HASH]
ADD CONSTRAINT [PDX_SCHEMA_FILE_HASH_PK] PRIMARY KEY ([FILE_NAME], [FILE_SOURCE]);

ALTER TABLE [SBMO].[PDX_SCHEMA_FILE_TASKVER]
ADD CONSTRAINT [PDX_SCHEMA_FILE_TASKVER_PK] PRIMARY KEY ([FILE_NAME]);

ALTER TABLE [SBMO].[PDX_SCHEMA_MAPPING]
ADD CONSTRAINT [PDX_SCHEMA_MAPPING_PK] PRIMARY KEY ([SEARCH]);

ALTER TABLE [SBMO].[PDX_SCHEMA_PRIV_DEFAULT]
ADD CONSTRAINT [PDX_SCHEMA_PRIV_DEFAULT_PK] PRIMARY KEY ([GRANTEE], [OBJECT_TYPE], [PRIVILEGE]);

ALTER TABLE [SBMO].[PDX_SCHEMA_PRIV_EXCEPTION]
ADD CONSTRAINT [PDX_SCHEMA_PRIV_EXCEPTION_PK] PRIMARY KEY ([GRANTEE], [OBJECT_TYPE], [OBJECT_NAME], [PRIVILEGE]);

ALTER TABLE [SBMO].[PDX_SCHEMA_TASKVER_META]
ADD CONSTRAINT [PDX_SCHEMA_TASKVER_META_PK] PRIMARY KEY ([TASK_VERSION], [TASK_SOURCE], [META_TAG], [TASK_VERSION_VALUE]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPDATER_MANIFEST]
ADD CONSTRAINT [PDX_SCHEMA_UPDATER_MANIFEST_PK] PRIMARY KEY ([VERSION]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPDATER_SQL]
ADD CONSTRAINT [PDX_SCHEMA_UPDATER_SQL_PK] PRIMARY KEY ([FILE_NAME]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_H]
ADD CONSTRAINT [PDX_SCHEMA_UPD_HLPR_DBG_H_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_PKGCALL_HIST]
ADD CONSTRAINT [PDX_SCHEMA_UPD_PKGCALL_HIST_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PURGE_CONFIG_SETTINGS]
ADD CONSTRAINT [PURGE_CONFIG_SETTINGS_PK] PRIMARY KEY ([NAME]);

ALTER TABLE [SBMO].[PURGE_ERROR_LOG]
ADD CONSTRAINT [PURGE_ERROR_LOG_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PURGE_TABLES]
ADD CONSTRAINT [PURGE_TABLES_PK] PRIMARY KEY ([TABLE_NAME]);

ALTER TABLE [SBMO].[QRTZ_CALENDARS]
ADD CONSTRAINT [QRTZ_CALENDARS_PK] PRIMARY KEY ([SCHED_NAME], [CALENDAR_NAME]);

ALTER TABLE [SBMO].[QRTZ_FIRED_TRIGGERS]
ADD CONSTRAINT [QRTZ_FIRED_TRIGGERS_PK] PRIMARY KEY ([SCHED_NAME], [ENTRY_ID]);

ALTER TABLE [SBMO].[QRTZ_JOB_DETAILS]
ADD CONSTRAINT [QRTZ_JOB_DETAILS_PK] PRIMARY KEY ([SCHED_NAME], [JOB_NAME], [JOB_GROUP]);

ALTER TABLE [SBMO].[QRTZ_LOCKS]
ADD CONSTRAINT [QRTZ_LOCKS_PK] PRIMARY KEY ([SCHED_NAME], [LOCK_NAME]);

ALTER TABLE [SBMO].[QRTZ_PAUSED_TRIGGER_GRPS]
ADD CONSTRAINT [QRTZ_PAUSED_TRIGGER_GRPS_PK] PRIMARY KEY ([SCHED_NAME], [TRIGGER_GROUP]);

ALTER TABLE [SBMO].[QRTZ_SCHEDULER_STATE]
ADD CONSTRAINT [QRTZ_SCHEDULER_STATE_PK] PRIMARY KEY ([SCHED_NAME], [INSTANCE_NAME]);

ALTER TABLE [SBMO].[SBMO_PROPERTIES]
ADD CONSTRAINT [SBMO_PROPERTIES_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[SCHEMA_UPDATER_MANIFEST]
ADD CONSTRAINT [SCHEMA_UPDATER_MANIFEST_PK] PRIMARY KEY ([FILE_NAME]);

ALTER TABLE [SBMO].[SCHEMA_UPDATER_SQL]
ADD CONSTRAINT [SCHEMA_UPDATER_SQL_PK] PRIMARY KEY ([FILE_NAME]);

ALTER TABLE [SBMO].[TENANTS]
ADD CONSTRAINT [TENANTS_UK1] UNIQUE ([NAME]);

ALTER TABLE [SBMO].[USER_AUDIT_LOG]
ADD CONSTRAINT [USER_AUDIT_LOG_PK] PRIMARY KEY ([ID]);
