-- BATCH 3 PRIMARY KEY AND UNIQUE CONSTRAINTS
-- ------------------------------------------------------------------

ALTER TABLE [SBMO].[CHAINS] ADD CONSTRAINT [CHAINS_UQ_HQID] UNIQUE ([HQ_ID]);
ALTER TABLE [SBMO].[CHAINS] ADD CONSTRAINT [CHAINS_UQ_NHINID] UNIQUE ([NHINID]);
ALTER TABLE [SBMO].[PDX_SCHEMA_TASK_ERROR_LOG] ADD CONSTRAINT [PK_PDX_SCHEMA_TASK_ERROR_LOG] PRIMARY KEY ([ID]);
ALTER TABLE [SBMO].[PURGE_HISTORY_CHUNKS] ADD CONSTRAINT [PK_PURGE_HISTORY_CHUNKS] PRIMARY KEY ([ID]);
