-- BATCH 4 PRIMARY KEY & UNIQUE CONSTRAINTS
-- --------------------------------------------------------

ALTER TABLE [SBMO].[CF_SEC_CHAIN]
ADD CONSTRAINT [CF_SEC_CHAIN_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DISPENSER_LOCATION]
ADD CONSTRAINT [DISPENSER_LOCATION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DISPENSER_LOCATION]
ADD CONSTRAINT [DISPENSER_LOCATION_UK1] UNIQUE ([TENANT_ID], [CELLID], [STATIONID]);

ALTER TABLE [SBMO].[DISPENSER_LOCATION]
ADD CONSTRAINT [DISPENSER_LOCATION_UK2] UNIQUE ([TENANT_ID], [DISPENSER_ID], [LOCATION_ID]);

ALTER TABLE [SBMO].[DISPENSER_LOCATION]
ADD CONSTRAINT [DISP_LOC_UQ_DISP_CELL_STAT] UNIQUE ([DISPENSER_ID], [CELLID], [STATIONID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_UK1] UNIQUE ([TENANT_ID], [DRUG_ID], [INVENTORY_ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_UQ_DRUG_INV] UNIQUE ([DRUG_ID], [INVENTORY_ID]);

ALTER TABLE [SBMO].[PURCHASE_ORDER]
ADD CONSTRAINT [PURCHASE_ORDER_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PURCHASE_ORDER]
ADD CONSTRAINT [PURCHASE_ORDER_UK1] UNIQUE ([TENANT_ID], [PURCHASE_ORDER_NUMBER]);

ALTER TABLE [SBMO].[RETAIL_COST]
ADD CONSTRAINT [RETAIL_COST_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETAIL_COST]
ADD CONSTRAINT [RET_COST_UQ_VEND_CHAIN_DRUG] UNIQUE ([VENDOR_ID], [CHAIN_ID], [DRUG_ID]);

ALTER TABLE [SBMO].[RX_DETAILS]
ADD CONSTRAINT [RX_DETAILS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_REQUEST_ERROR]
ADD CONSTRAINT [RX_REQUEST_ERROR_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_SHIPPING_PACKAGES]
ADD CONSTRAINT [RX_SHIPPING_PACKAGES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_UK2] UNIQUE ([NPI_NUM]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_UK1] UNIQUE ([TENANT_ID], [NCPDP], [DEPARTMENT]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_UQ_NHINID] UNIQUE ([NHINID]);

ALTER TABLE [SBMO].[VENDOR_ITEM_PROP]
ADD CONSTRAINT [VENDOR_ITEM_PROP_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR_ITEM_PROP]
ADD CONSTRAINT [VENDOR_ITEM_PROP_UK1] UNIQUE ([TENANT_ID], [VENDOR_ID], [DRUG_ID]);

ALTER TABLE [SBMO].[VENDOR_PO_CREATE_DAYS]
ADD CONSTRAINT [VENDOR_PO_CREATE_DAYS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR_PO_CREATE_DAYS]
ADD CONSTRAINT [VENDOR_PO_CREATE_DAYS_UK1] UNIQUE ([TENANT_ID], [VENDOR_ID], [DAY_OF_WEEK]);
