-- BATCH 6 PRIMARY KEY & UNIQUE CONSTRAINTS
-- --------------------------------------------------------

ALTER TABLE [SBMO].[CHARGE_PAYMENT_INFO]
ADD CONSTRAINT [CHARGE_PAYMENT_INFO_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DRUG_ORDER_PRODUCT_VERIFY]
ADD CONSTRAINT [DRUG_ORDER_PRODUCT_VERIFY_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_UQ_CFQUEUENUM] UNIQUE ([CF_QUEUE_NUM]);
