-- BATCH 5 PRIMARY KEY & UNIQUE CONSTRAINTS
-- --------------------------------------------------------

ALTER TABLE [SBMO].[CF_SEC_STORE]
ADD CONSTRAINT [CF_SEC_STORE_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DRUG_ORDERS]
ADD CONSTRAINT [DRUG_ORDERS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ITEM_LOCATION]
ADD CONSTRAINT [ITEM_LOCATION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MASTER_PRODUCT_PO_VERIFY]
ADD CONSTRAINT [MASTER_PRODUCT_PO_VERIFY_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MESSAGE_LOG]
ADD CONSTRAINT [MESSAGE_LOG_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ORDERS]
ADD CONSTRAINT [ORDERS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ORDERS]
ADD CONSTRAINT [ORDERS_UQ_ORDER_NUMBER] UNIQUE ([ORDER_NUMBER]);

ALTER TABLE [SBMO].[PRIORITY_CHANGE_ALERTS]
ADD CONSTRAINT [PRIORITY_CHANGE_ALERTS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORE_SHIP_VIA]
ADD CONSTRAINT [STORE_SHIP_VIA_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORE_VENDOR_ACCOUNT]
ADD CONSTRAINT [STORE_VENDOR_ACCOUNT_PK] PRIMARY KEY ([TENANT_ID], [ID]);
