-- BATCH 8 TABLES
-- ------------------------------------------------------------------

CREATE TABLE [SBMO].[RX_HOURS_OF_ADMIN_DOSES] (
    [ID] DECIMAL(38,0) NULL,
    [TENANT_ID] DECIMAL(38,0) NULL,
    [RX_HOURS_OF_ADMINISTRATION_ID] DECIMAL(38,0) NULL,
    [DATE_OF_DOSE] DATETIME2 NULL,
    [TIME_OF_DOSE] VARCHAR(MAX) NULL,
    [QUANTITY] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[RX_WARNING_LABEL_CODES] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PARTITION_STAMP] DATETIME2 NULL,
    [LABEL_CODE] VARCHAR(MAX) NULL,
    [LABEL_LANGUAGE] VARCHAR(MAX) NULL,
    [SOURCE] VARCHAR(MAX) NULL,
    [IDX] DECIMAL(38,0) NULL,
    [RX_WARNING_LABEL_ID] DECIMAL(38,0) NULL,
    [WARNING_LABEL_GROUP] VARCHAR(MAX) NULL
);

