-- BATCH 7 TABLES
-- --------------------------------------------------------

CREATE TABLE [SBMO].[INVENTORY_AUDIT] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [ALLOCATED_CHANGE] FLOAT,
    [ONHAND_CHANGE] FLOAT,
    [UPDATED_DATE] DATETIME2 NOT NULL,
    [DRUG_ORDER_ID] DECIMAL(38,0),
    [FORMULARY_ID] DECIMAL(38,0) NOT NULL,
    [RET_ADJ_ID] DECIMAL(38,0),
    [RX_ID] DECIMAL(38,0),
    [CREATED_DATE] DATETIME2
);

CREATE TABLE [SBMO].[RX_DOCUMENTS] (
    [ID] DECIMAL(38,0),
    [TENANT_ID] DECIMAL(38,0),
    [PROGRAM_CODE] VARCHAR(45),
    [DOCUMENT_CODE] VARCHAR(75),
    [CHECK_SUM] VARCHAR(30) NOT NULL,
    [RX_CORES_ID] DECIMAL(38,0) NOT NULL,
    [FILE_CONTENTS] CLOB NOT NULL,
    [CREATED_DATE] DATETIME2 NOT NULL
);

CREATE TABLE [SBMO].[RX_HOURS_OF_ADMINISTRATION] (
    [ID] DECIMAL(38,0),
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [RX_CORES_ID] DECIMAL(38,0) NOT NULL,
    [ALL_DAYS_SAME] VARCHAR(1),
    [ALL_DAYS_START_DATE] DATETIME2,
    [ALL_DAYS_END_DATE] DATETIME2
);

CREATE TABLE [SBMO].[RX_IMAGE_DATA] (
    [ID] DECIMAL(38,0),
    [TENANT_ID] DECIMAL(38,0),
    [CREATED_DATE] DATETIME2 NOT NULL,
    [RX_CORES_ID] DECIMAL(38,0) NOT NULL,
    [IMAGE] BLOB NOT NULL,
    [TEXT] CLOB,
    [LANGUAGE] VARCHAR(10),
    [FORMAT] VARCHAR(10),
    [TYPE] DECIMAL(1,0) NOT NULL
);

CREATE TABLE [SBMO].[RX_LOTS] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [PARTITION_STAMP] DATETIME2 NOT NULL,
    [NUM] VARCHAR(30) NOT NULL,
    [RX_ID] DECIMAL(38,0) NOT NULL,
    [EXPIRE] DATETIME2 NOT NULL,
    [CREATED_DATE] DATETIME2,
    [SERIAL_NUMBER] VARCHAR(20),
    [BARCODE_TYPE] VARCHAR(1),
    [BARCODE_RAW_DATA] CLOB
);

CREATE TABLE [SBMO].[RX_PRINT_CHR] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [RX_ID] BIGINT NOT NULL,
    [CHR_CONTENT_CODE] DECIMAL(2,0),
    [CHR_CONTENT] CLOB,
    [CREATED_DATE] DATETIME2
);

CREATE TABLE [SBMO].[RX_STATE_TRANSITION] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [RX_CORE_ID] DECIMAL(38,0) NOT NULL,
    [TRANSITION_TYPE] DECIMAL(3,0) NOT NULL,
    [TRANSITION_TIME] DATETIME2 NOT NULL,
    [USER_ID] VARCHAR(255) NOT NULL,
    [NOTIFICATION_SENT] VARCHAR(1)
);

CREATE TABLE [SBMO].[RX_TP_INFO] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [RX_ID] DECIMAL(38,0) NOT NULL,
    [ORDINAL] DECIMAL(38,0) NOT NULL,
    [CARRIER_CODE] VARCHAR(10),
    [PLAN_CODE] VARCHAR(15),
    [PLAN_NAME] VARCHAR(28),
    [BIN] VARCHAR(10),
    [PCN] VARCHAR(10),
    [PLAN_GROUP_CODE] VARCHAR(15),
    [RELATIONSHIP_CODE] VARCHAR(1),
    [PLAN_TYPE] VARCHAR(2),
    [CARD_IDENTIFIER] VARCHAR(20),
    [TP_AUTH_NUM] VARCHAR(20),
    [CREATED_DATE] DATETIME2,
    [DISALLOW_INCENTIVES] VARCHAR(1) NOT NULL,
    [INSURANCE_PAID] FLOAT
);

CREATE TABLE [SBMO].[RX_VIAL_INFOS] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [PARTITION_STAMP] DATETIME2 NOT NULL,
    [QC_RPH_INIT] VARCHAR(10),
    [QC_RPH_ID] VARCHAR(38),
    [QC_RPH_LICENSE_NUMBER] VARCHAR(20),
    [RX_ID] DECIMAL(38,0) NOT NULL,
    [VIAL_NUMBER] DECIMAL(38,0),
    [VIAL_QUANTITY] DECIMAL(38,0),
    [CREATED_DATE] DATETIME2,
    [VIAL_DECIMAL_QTY] FLOAT,
    [QC_RPH_LAST_NAME] VARCHAR(25),
    [QC_RPH_FIRST_NAME] VARCHAR(20),
    [REPLENISH_RPH_FIRST_NAME] VARCHAR(20),
    [REPLENISH_RPH_LAST_NAME] VARCHAR(25),
    [REPLENISH_RPH_LICENSE_NUM] VARCHAR(20),
    [REPLENISH_RPH_EMPLOYEE_NUM] VARCHAR(255),
    [REPLENISH_TECH_FIRST_NAME] VARCHAR(20),
    [REPLENISH_TECH_LAST_NAME] VARCHAR(25),
    [REPLENISH_TECH_LICENSE_NUM] VARCHAR(20),
    [REPLENISH_TECH_EMPLOYEE_NUM] VARCHAR(255),
    [DISPENSER_STATION_IDENT] VARCHAR(3),
    [DISPENSER_CELL_IDENT] VARCHAR(6)
);

CREATE TABLE [SBMO].[RX_WARNING_LABELS] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [RX_ID] DECIMAL(38,0) NOT NULL,
    [IDX] DECIMAL(38,0) NOT NULL,
    [PARTITION_STAMP] DATETIME2 NOT NULL,
    [CREATED_DATE] DATETIME2
);
