-- BATCH 5 TABLES
-- --------------------------------------------------------

CREATE TABLE [SBMO].[CF_SEC_STORE] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [LOAD_DATE] DATETIME2,
    [PASS_PHRASE] VARCHAR2(255,
    [PRIVATE_KEY] VARCHAR2(4000,
    [REGISTRATION_DATE] DATETIME2,
    [SSL_CERTIFICATE] VARCHAR2(4000,
    [CHAIN_ID] BIGINT NOT NULL,
    [REG_STATUS] VARCHAR2(16 NOT NULL
);

CREATE TABLE [SBMO].[DRUG_ORDERS] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [PARTITION_STAMP] DATETIME2 NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [ACK_RECEIVED_QTY] FLOAT,
    [PACK] FLOAT NOT NULL,
    [COST] FLOAT,
    [COUNTER] DECIMAL(38,0),
    [ITEM_STATUS] VARCHAR(255),
    [SUB_ITEM_NUMBER] VARCHAR(15),
    [ITEM_NUMBER] VARCHAR(15) NOT NULL,
    [ORDER_QTY] FLOAT NOT NULL,
    [RECQTY] FLOAT,
    [CHECK_IN_DATE] DATETIME2,
    [APPLIED_TO_INVENTORY_DATE] DATETIME2,
    [FORMULARY_ID] DECIMAL(38,0) NOT NULL,
    [PURCHASE_ORDER_ID] DECIMAL(38,0) NOT NULL,
    [VENDOR_ORDER_QTY] FLOAT NOT NULL,
    [VENDOR_ACK_RECEIVED_QTY] FLOAT,
    [VENDOR_RECQTY] FLOAT,
    [APPLIED_QTY] DECIMAL(38,0),
    [CREATED_DATE] DATETIME2,
    [CONVERSION_FACTOR] FLOAT,
    [VENDOR_ORDER_CASE] DECIMAL(22,13)
);

CREATE TABLE [SBMO].[ITEM_LOCATION] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FORMULARY_ID] BIGINT NOT NULL,
    [QUANTITY] INT NOT NULL
);

CREATE TABLE [SBMO].[MASTER_PRODUCT_PO_VERIFY] (
    [TENANT_ID] DECIMAL(38,0),
    [ID] DECIMAL(38,0),
    [PURCHASE_ORDER_ID] DECIMAL(38,0) NOT NULL,
    [VENDOR_ID] DECIMAL(38,0) NOT NULL,
    [ORDER_DATE] DATETIME2 NOT NULL,
    [TOTAL_ITEMS] BIGINT NOT NULL,
    [PERCENT_SCANNED] BIGINT NOT NULL,
    [PERCENT_PASSED] BIGINT NOT NULL,
    [CREATED_DATE] DATETIME2 NOT NULL,
    [PURCHASE_ORDER_STATUS] DECIMAL(1,0)
);

CREATE TABLE [SBMO].[MESSAGE_LOG] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [MESSAGE_DATE] DATETIME2 NOT NULL,
    [MESSAGE] CLOB NOT NULL,
    [STORE_ID] BIGINT NOT NULL,
    [USER_INITS] VARCHAR2(255 NOT NULL,
    [CREATED_DATE] DATETIME2
);

CREATE TABLE [SBMO].[ORDERS] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [PARTITION_STAMP] DATETIME2 NOT NULL,
    [ORDER_NUMBER] DECIMAL(38,0) NOT NULL,
    [SHIP_ADDRESS] VARCHAR(30) NOT NULL,
    [SHIP_ADDRESS2] VARCHAR(30),
    [SHIP_CITY] VARCHAR(35) NOT NULL,
    [SHIP_FIRST_NAME] VARCHAR(20) NOT NULL,
    [SHIP_MIDDLE_NAME] VARCHAR(1),
    [SHIP_LAST_NAME] VARCHAR(25) NOT NULL,
    [SHIP_PHONE] VARCHAR(10),
    [SHIP_STATE] VARCHAR(2) NOT NULL,
    [ORDER_TYPE] DECIMAL(38,0) NOT NULL,
    [SHIP_TYPE] DECIMAL(38,0) NOT NULL,
    [SHIP_ZIP] VARCHAR(15) NOT NULL,
    [STORE_DEA] VARCHAR(12) NOT NULL,
    [STORE_LIC] VARCHAR(12),
    [STORE_EST_SHIP_AMT] FLOAT,
    [SIGNATURE_REQUIRED] DECIMAL(38,0) NOT NULL,
    [STORE_ID] DECIMAL(38,0) NOT NULL,
    [ORDER_PROCESSED] DECIMAL(38,0) NOT NULL,
    [INVENTORY_ID] DECIMAL(38,0) NOT NULL,
    [GROUPING_CODE] VARCHAR(15) NOT NULL,
    [ALLOW_GROUPING] DECIMAL(38,0) NOT NULL,
    [BATCH_IDENTIFIER] DECIMAL(38,0),
    [CREATED_DATE] DATETIME2,
    [PROMISED_DATE] DATETIME2,
    [PROMISE_DATE_OVERRIDE] VARCHAR(1),
    [REQUESTED_SHIP_DATE] DATETIME2,
    [SHIPPING_INSTRUCTIONS] VARCHAR(2000),
    [EXTERNAL_ORDER_IDENTIFIER] VARCHAR(35),
    [VENDOR_CARRIER_CODE_IDENT] VARCHAR(25),
    [VENDOR_CARRIER_CODE_DESC] VARCHAR(100),
    [VENDOR_SHIP_BOX_IDENT] VARCHAR(20)
);

CREATE TABLE [SBMO].[PRIORITY_CHANGE_ALERTS] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FORMULARY_ID] BIGINT NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [ACTION] DECIMAL(2,0) NOT NULL,
    [ADDED_DATE] DATETIME2 NOT NULL,
    [ACKNOWLEDGED] DATETIME2,
    [ACKNOWLEDGED_BY] VARCHAR(256),
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[STORE_SHIP_VIA] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ORDER_TYPE] INT NOT NULL,
    [SHIP_TYPE] INT NOT NULL,
    [SHIP_VIA] VARCHAR(64),
    [STORE_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[STORE_VENDOR_ACCOUNT] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [MAIL_ACCOUNT_NUM] VARCHAR2(255,
    [STORE_ID] BIGINT NOT NULL,
    [STORE_ACCOUNT_NUM] VARCHAR2(255,
    [VENDOR_ID] BIGINT NOT NULL
);
