-- BATCH 7 TABLES (FINAL)
-- Schema: SBMO
-- Count: 16

CREATE TABLE [SBMO].[SCHEMA_UPDATER_MANIFEST]
(
    [FILE_NAME] VARCHAR(100) NOT NULL,
    [VERSION] VARCHAR(20) NOT NULL,
    [APPLY_ORDER] INT NOT NULL
);

CREATE TABLE [SBMO].[SCHEMA_UPDATER_SQL]
(
    [FILE_NAME] VARCHAR(255) NOT NULL,
    [CHECKSUM] VARCHAR(64) NOT NULL,
    [SQL] VARCHAR(MAX) NOT NULL
);

CREATE TABLE [SBMO].[SHIP_ITEMS]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [PURCHASE_ORDER_NUMBER] VARCHAR(255) NOT NULL,
    [SHIPMENT_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[SHIPMENT]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [PARTITION_STAMP] DATETIME2(6) DEFAULT SYSDATE NOT NULL,
    [SIGNATURE] VARCHAR(MAX) NOT NULL,
    [RECEIVED_DATE] DATETIME2(6) NOT NULL,
    [PRINTED_NAME] VARCHAR(255) NOT NULL,
    [RECEIVE_USERID] VARCHAR(64) NOT NULL
);

CREATE TABLE [SBMO].[STAT_EXPORT]
(
    [STATID] VARCHAR(30),
    [TYPE] CHAR(1),
    [VERSION] DECIMAL(18,2),
    [FLAGS] DECIMAL(18,2),
    [C1] VARCHAR(30),
    [C2] VARCHAR(30),
    [C3] VARCHAR(30),
    [C4] VARCHAR(30),
    [C5] VARCHAR(30),
    [N1] DECIMAL(18,2),
    [N2] DECIMAL(18,2),
    [N3] DECIMAL(18,2),
    [N4] DECIMAL(18,2),
    [N5] DECIMAL(18,2),
    [N6] DECIMAL(18,2),
    [N7] DECIMAL(18,2),
    [N8] DECIMAL(18,2),
    [N9] DECIMAL(18,2),
    [N10] DECIMAL(18,2),
    [N11] DECIMAL(18,2),
    [N12] DECIMAL(18,2),
    [D1] DATETIME2,
    [R1] RAW(32),
    [R2] RAW(32),
    [CH1] VARCHAR(1000)
);

CREATE TABLE [SBMO].[STORE_SHIP_VIA]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ORDER_TYPE] INT NOT NULL,
    [SHIP_TYPE] INT NOT NULL,
    [SHIP_VIA] VARCHAR(64),
    [STORE_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[STORE_VENDOR_ACCOUNT]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [MAIL_ACCOUNT_NUM] VARCHAR(255),
    [STORE_ID] BIGINT NOT NULL,
    [STORE_ACCOUNT_NUM] VARCHAR(255),
    [VENDOR_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[STORES]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [MAIL_INVENTORY_ID] BIGINT NOT NULL,
    [STORE_INVENTORY_ID] BIGINT NOT NULL,
    [STATE_CONTROLLED_SUB_LIC_NUM] VARCHAR(255) NOT NULL,
    [DEA_EXPIRE_DATE] DATETIME2(6) NOT NULL,
    [DEA_NUMBER] VARCHAR(255) NOT NULL,
    [FEDERAL_TAX_NUMBER] VARCHAR(255),
    [STATE_LICENSE_NUMBER] VARCHAR(255) NOT NULL,
    [NAME] VARCHAR(60) NOT NULL,
    [NCPDP] VARCHAR(255) NOT NULL,
    [NHINID] BIGINT NOT NULL,
    [STORE_NUMBER] VARCHAR(255) NOT NULL,
    [DEACTIVATED_DATE] DATETIME2(6),
    [CHAIN_ID] BIGINT NOT NULL,
    [STORE_LOGO_FILENAME] VARCHAR(255) NOT NULL,
    [REGION_ID] BIGINT NOT NULL,
    [STORE_DELIVERY_SHIP_TYPE] INT NOT NULL,
    [DEPARTMENT] VARCHAR(255) NOT NULL,
    [SUPPRESS_DEA_PRINTING] VARCHAR(255),
    [NPI_NUM] VARCHAR(10),
    [LAST_STATUS_UPDATE_DATE] DATETIME2(6),
    [ENABLE_SU_ALERT_NOTIFICATION] DECIMAL(1,0) DEFAULT 1 NOT NULL,
    [FORCE_FORMULARY_DOWNLOAD] DECIMAL(1,0),
    [STORE_ORIG_INVENTORY_ID] BIGINT,
    [MAIL_ORIG_INVENTORY_ID] BIGINT,
    [UNIT_DOSE_INVENTORY_ID] DECIMAL(38,0),
    [UNIT_DOSE_ORIG_INVENTORY_ID] DECIMAL(38,0)
);

CREATE TABLE [SBMO].[SYSTEM_MESSAGES]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [MESSAGE] VARCHAR(255) NOT NULL,
    [ADDED_DATE] DATETIME2(6) NOT NULL,
    [MESSAGE_TYPE] DECIMAL(18,2),
    [ACKNOWLEDGED_BY] VARCHAR(255),
    [ACKNOWLEDGED] DATETIME2(6),
    [DATA] VARBINARY(MAX),
    [ERROR_TYPE] DECIMAL(18,2) NOT NULL,
    [RESOLUTION_TEXT] VARCHAR(MAX),
    [REFERENCE_ID] DECIMAL(18,2),
    [REFERENCE_TYPE] DECIMAL(18,2),
    [CREATED_DATE] DATETIME2(6),
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[TENANTS]
(
    [ID] BIGINT NOT NULL,
    [NAME] VARCHAR(15) NOT NULL,
    [ADDRESS_LINE_1] VARCHAR(30) NOT NULL,
    [ADDRESS_LINE_2] VARCHAR(30),
    [CITY] VARCHAR(35) NOT NULL,
    [STATE] VARCHAR(2) NOT NULL,
    [ZIP] VARCHAR(15) NOT NULL,
    [COUNTY] VARCHAR(15) NOT NULL,
    [NHINID] BIGINT NOT NULL,
    [TIME_ZONE] VARCHAR(50) NOT NULL,
    [TOLL_FREE_PHONE_NUMBER] VARCHAR(10) NOT NULL,
    [ALTERNATE_PHONE_NUMBER] VARCHAR(10),
    [ACTIVE_DIRECTORY_GROUP] VARCHAR(255) NOT NULL,
    [IS_RXCOM] VARCHAR(5) NOT NULL,
    [NHIN_NAME_ABBREVIATION] VARCHAR(3)
);

CREATE TABLE [SBMO].[USER_AUDIT_LOG]
(
    [ID] BIGINT NOT NULL,
    [ACTION] INT NOT NULL,
    [TIME_STAMP] DATETIME2(6) NOT NULL,
    [USER_ID] VARCHAR(255) NOT NULL,
    [MESSAGE] VARCHAR(255),
    [CREATED_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[VENDOR]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DEACTIVATE] DATETIME2(6),
    [NAME] VARCHAR(28) NOT NULL,
    [NHINVEN] VARCHAR(8) NOT NULL,
    [NHINVENLEV] INT,
    [DEFAULT_ITEM_NUMBER_QUALIFIER] VARCHAR(2) NOT NULL,
    [TRANSPORT_TYPE] INT,
    [TRANSPORT_PROPERTIES] VARCHAR(MAX),
    [BILLING_TEMPLATE_PATH] VARCHAR(255),
    [BILLING_TEMPLATE_PROPERTIES] VARCHAR(MAX),
    [DAY_SUPPLY_THRESHOLD] BIGINT NOT NULL,
    [BILLING_TRANSPORT_TYPE] INT,
    [FORMULARY_INVENTORY_TYPE] INT NOT NULL,
    [BILLING_TRANSPORT_PROPERTIES] VARCHAR(MAX),
    [THREE_DIGIT_VENDOR_CODE] VARCHAR(32) NOT NULL,
    [MINIMUM_PRICE_OVERRIDE] DECIMAL(1,0) NOT NULL,
    [ALLOW_MULTIPLE_INVENTORIES] DECIMAL(1,0),
    [EXCLUDE_FROM_BILLING] DECIMAL(1,0) NOT NULL,
    [INV_MGMT_TRANSPORT_TYPE] BIGINT,
    [INV_MGMT_TRANSPORT_PROP] VARCHAR(MAX),
    [INV_MGMT_TEMPLATE_PATH] VARCHAR(255),
    [LAST_UPDATED_DATE] DATETIME2(6) NOT NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(255) NOT NULL,
    [DISABLE_856] VARCHAR(1),
    [ALLOW_CSOS] VARCHAR(1),
    [DESCRIPTION] VARCHAR(255),
    [CII_RECEIVING] VARCHAR(1),
    [ENABLE_BAR_CODE_SCANNING] VARCHAR(1),
    [BAR_CODE_TYPE] DECIMAL(1,0),
    [PERCENTAGE_TO_SCAN_PO] DECIMAL(3,0),
    [TRANSPORT_855_PROPERTIES] VARCHAR(MAX),
    [TRANSPORT_855_TYPE] INT,
    [COST_UPDATE_NHIN_VENDOR] VARCHAR(8)
);

CREATE TABLE [SBMO].[VENDOR_ITEM_PROP]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ITEM_NUMBER] VARCHAR(15) NOT NULL,
    [UNIT_CODE] VARCHAR(2),
    [ITEM_NUMBER_QUALIFIER] VARCHAR(2),
    [ACQ_COST] FLOAT(126),
    [VENDOR_ID] BIGINT NOT NULL,
    [DRUG_ID] BIGINT NOT NULL,
    [CONVERSION_FACTOR] FLOAT(126)
);

CREATE TABLE [SBMO].[VENDOR_PO_CREATE_DAYS]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [VENDOR_ID] DECIMAL(38,0) NOT NULL,
    [DAY_OF_WEEK] DECIMAL(1,0) NOT NULL
);

CREATE TABLE [SBMO].[VENDOR_PROP]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [OWNED_ACCOUNT_NUMBER] VARCHAR(64),
    [AUTHORIZATION_INFORMATION] VARCHAR(64),
    [SECURITY_INFORMATION] VARCHAR(64),
    [INTERCHANGE_SENDER_ID_QLF] VARCHAR(64) NOT NULL,
    [INTERCHANGE_SENDER_ID] VARCHAR(64),
    [ICHANGE_RECEIVER_ID_QLF] VARCHAR(64) NOT NULL,
    [INTERCHANGE_RECEIVER_ID] VARCHAR(64) NOT NULL,
    [ICHANGE_CONTROL_STANDARDS_ID] VARCHAR(64) NOT NULL,
    [ICHANGE_CTRL_VERSION_NUM] VARCHAR(64) NOT NULL,
    [ACK_REQUESTED] VARCHAR(64) NOT NULL,
    [USAGE_INDICATOR] VARCHAR(64) NOT NULL,
    [COMPONENT_ELEMENT_SEPARATOR] VARCHAR(64) NOT NULL,
    [SEGMENT_TERMINATOR] VARCHAR(64) NOT NULL,
    [DATA_ELEMENT_SEPARATOR] VARCHAR(64) NOT NULL,
    [FUNCTIONAL_IDENTIFIER_CODE] VARCHAR(64) NOT NULL,
    [APPLICATION_SENDERS_CODE] VARCHAR(64),
    [APP_RECEIVERS_CODE] VARCHAR(64) NOT NULL,
    [RESPONSIBLE_AGENCY_CODE] VARCHAR(64) NOT NULL,
    [EDI_VERSION_SUPPORTED] VARCHAR(64) NOT NULL,
    [EDI_VERSION_TEXT] VARCHAR(64),
    [PURCHASE_ORDER_TYPE_CODE] VARCHAR(64) NOT NULL,
    [IDENTIFICATION_CODE_QLF] VARCHAR(64) NOT NULL,
    [IDENTIFICATION_CODE] VARCHAR(64),
    [OWNED_IDENTIFICATION_CODE] VARCHAR(64),
    [CONSIGNED_ACCOUNT_NUMBER] VARCHAR(64),
    [URL_STRING] VARCHAR(512),
    [OWNED_APPLICATION_SENDERS_CODE] VARCHAR(64),
    [OWNED_INTERCHANGE_SENDER_ID] VARCHAR(64),
    [LAST_UPDATED_DATE] DATETIME2(6) NOT NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(255) NOT NULL
);

CREATE TABLE [SBMO].[WEEKLY_SCHEDULED_TASKS]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FRIDAY] DECIMAL(1,0) NOT NULL,
    [MONDAY] DECIMAL(1,0) NOT NULL,
    [SATURDAY] DECIMAL(1,0) NOT NULL,
    [SUNDAY] DECIMAL(1,0) NOT NULL,
    [THURSDAY] DECIMAL(1,0) NOT NULL,
    [TUESDAY] DECIMAL(1,0) NOT NULL,
    [WEDNESDAY] DECIMAL(1,0) NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);

