-- BATCH 1 TABLES
-- Schema: SBMO
-- Count: 20

CREATE TABLE [SBMO].[ADDRESSES]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ADDRESS] VARCHAR(30) NOT NULL,
    [ADDRESS_LINE_2] VARCHAR(30),
    [CITY] VARCHAR(35) NOT NULL,
    [STATE] INT NOT NULL,
    [ZIP] VARCHAR(15) NOT NULL,
    [OWNER_ID] BIGINT NOT NULL,
    [IDX] INT NOT NULL,
    [COUNTRY] VARCHAR(4) NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2(6) NOT NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(255) NOT NULL
);

CREATE TABLE [SBMO].[ADJUSTMENT_CODES]
(
    [ID] BIGINT NOT NULL,
    [CODE] VARCHAR(3) NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2(6) NOT NULL,
    [DEACTIVATED_DATE] DATETIME2(6),
    [DESCRIPTION] VARCHAR(255) NOT NULL,
    [CREATED_DATE] DATETIME2(6) NOT NULL,
    [CHANGE_ON_HAND] VARCHAR(1) NOT NULL
);

CREATE TABLE [SBMO].[ADJUSTMENT_GROUP]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [APPLIED_DATE] DATETIME2(6),
    [CREATED_DATE] DATETIME2(6) NOT NULL,
    [INVENTORY_ID] DECIMAL(18,2) NOT NULL,
    [WS_CLIENT_CERT_IDENTIFIER] VARCHAR(255)
);

CREATE TABLE [SBMO].[AUDIT_DBU_LOG]
(
    [ID] DECIMAL(18,2),
    [EXEC_TIME_STAMP] DATETIME2(6),
    [USER_ID] VARCHAR(30),
    [DBU_TABLE] VARCHAR(30),
    [DBU_PARMS] VARCHAR(2000),
    [DBU_ROWS] DECIMAL(18,2),
    [SQL_TEXT] VARCHAR(2000),
    [ERROR_TEXT] VARCHAR(2000)
);

CREATE TABLE [SBMO].[AUDIT_LOG]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [ACTION] DECIMAL(18,2) NOT NULL,
    [NEW_VALUE] VARCHAR(1024),
    [OBJECT_NAME] VARCHAR(1024) NOT NULL,
    [OBJECT_ID] DECIMAL(18,2) NOT NULL,
    [OLD_VALUE] VARCHAR(1024),
    [PROPERTY] VARCHAR(1024) NOT NULL,
    [TIME_STAMP] DATETIME2(6) NOT NULL,
    [USER_ID] VARCHAR(255) NOT NULL,
    [CREATED_DATE] DATETIME2(6),
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[BIN_UPC_LINK]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [BIN_BARCODE] VARCHAR(16) NOT NULL,
    [DRUG_UPC] VARCHAR(16) NOT NULL,
    [DEVICE_NUMBER] VARCHAR(16) NOT NULL,
    [DRUG_NAME] VARCHAR(28) NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [NDC_FMT] INT
);

CREATE TABLE [SBMO].[CARRIER]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [NAME] VARCHAR(128) NOT NULL,
    [SHIP_IDENT] VARCHAR(128) NOT NULL,
    [SHIP_PRIORITY] DECIMAL(3,0)
);

CREATE TABLE [SBMO].[CF_SEC_CHAIN]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2(6) NOT NULL,
    [CHAIN_PASSWORD] VARCHAR(255)
);

CREATE TABLE [SBMO].[CF_SEC_STORE]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [LOAD_DATE] DATETIME2(6),
    [PASS_PHRASE] VARCHAR(255),
    [PRIVATE_KEY] VARCHAR(4000),
    [REGISTRATION_DATE] DATETIME2(6),
    [SSL_CERTIFICATE] VARCHAR(4000),
    [CHAIN_ID] BIGINT NOT NULL,
    [REG_STATUS] VARCHAR(16) NOT NULL
);

CREATE TABLE [SBMO].[CHAINS]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [NHINID] BIGINT NOT NULL,
    [NAME] VARCHAR(30) NOT NULL,
    [CHAIN_MARK_UP_PERCENT] FLOAT(126) NOT NULL,
    [CHAIN_DISCOUNT_PERCENT] FLOAT(126) NOT NULL,
    [PARENT_ID] BIGINT,
    [HQ_ID] VARCHAR(20) NOT NULL,
    [MINIMUM_PRICE_OVERRIDE] DECIMAL(1,0) NOT NULL,
    [LABEL_TEMPLATE] VARCHAR(32),
    [SHIPPING_ADD_ON_TYPE] VARCHAR(1) DEFAULT 'P' NOT NULL,
    [SHIPPING_ADD_ON_AMOUNT] FLOAT(126) DEFAULT 0 NOT NULL,
    [USE_ADHERIS] DECIMAL(1,0),
    [ADHERIS_URL] VARCHAR(255),
    [ADHERIS_TIMEOUT] DECIMAL(9,0),
    [ADHERIS_VERSION] VARCHAR(30),
    [DEACTIVATED_DATE] DATETIME2(6),
    [ADHERIS_RETRY_COUNT] DECIMAL(2,0) NOT NULL,
    [ADHERIS_RETRY_OPTION] DECIMAL(1,0) NOT NULL,
    [ADHERIS_THREAD_POOL_SIZE] INT NOT NULL,
    [ADHERIS_MAX_POOL_SIZE] INT NOT NULL,
    [USE_JMS] VARCHAR(1) NOT NULL,
    [ENABLE_DIGITAL] DECIMAL(1,0)
);

CREATE TABLE [SBMO].[CHARGE_PAYMENT_INFO]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ORDER_ID] BIGINT NOT NULL,
    [CHARGE_TYPE] VARCHAR(2) NOT NULL,
    [CHARGE_IDENT] VARCHAR(33) NOT NULL,
    [CHARGE_AMOUNT] FLOAT(126) NOT NULL,
    [CREATED_DATE] DATETIME2(6) NOT NULL
);

CREATE TABLE [SBMO].[CONTACTS]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FIRST_NAME] VARCHAR(20) NOT NULL,
    [LAST_NAME] VARCHAR(25) NOT NULL,
    [TITLE] VARCHAR(30),
    [ENTITY_ID] BIGINT NOT NULL,
    [IDX] INT NOT NULL
);

CREATE TABLE [SBMO].[CR18985_LOG]
(
    [OWNER] VARCHAR(35),
    [TABLE_NAME] VARCHAR(35),
    [OBJECT_NAME] VARCHAR(35),
    [OBJECT_TYPE] VARCHAR(35),
    [ERROR_CODE] VARCHAR(35),
    [ERROR_MSG] VARCHAR(210)
);

CREATE TABLE [SBMO].[CUSTOM_SCHEDULED_TASK]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [TASK_TYPE] VARCHAR(20) NOT NULL,
    [TASK_DAY] DECIMAL(3,0) NOT NULL,
    [TRIGGER_TIME] VARCHAR(100) NOT NULL,
    [SCHEDULE_GROUPING] BIGINT,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[DAILY_SCHEDULED_TASKS]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[DASHBOARD_SETTINGS]
(
    [TENANT_ID] DECIMAL(38,0),
    [FACILITY_ID] DECIMAL(38,0),
    [ID] DECIMAL(38,0),
    [REFRESH_MINUTES] DECIMAL(3,0) NOT NULL,
    [DAY_OF_WEEK] DECIMAL(1,0) NOT NULL,
    [START_TIME] DATETIME2(6) NOT NULL,
    [STOP_TIME] DATETIME2(6) NOT NULL
);

CREATE TABLE [SBMO].[DASHBOARD_STATISTICS]
(
    [TENANT_ID] DECIMAL(38,0),
    [FACILITY_ID] DECIMAL(38,0),
    [ID] DECIMAL(38,0),
    [PEND_STORE] DECIMAL(22,0) NOT NULL,
    [PEND_STORE_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [PEND_MAIL] DECIMAL(22,0) NOT NULL,
    [PEND_MAIL_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [PEND_SPECIALTY] DECIMAL(22,0) NOT NULL,
    [PEND_SPECIALTY_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [PEND_PROMISED_DATE] DECIMAL(22,0) NOT NULL,
    [PEND_PROMISED_DATE_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [PEND_INADEQ_INVENT] DECIMAL(22,0) NOT NULL,
    [PEND_INADEQ_INVENT_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [QUEUED] DECIMAL(22,0) NOT NULL,
    [QUEUED_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [ERROR_TO_DISPENSE] DECIMAL(22,0) NOT NULL,
    [ERROR_TO_DISPENSE_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [SENT_TO_DISPENSER] DECIMAL(22,0) NOT NULL,
    [CANCELLED_BY_DISPENSER] DECIMAL(22,0) NOT NULL,
    [PROCESSED] DECIMAL(22,0) NOT NULL,
    [REJECTED_INADEQUATE_INVENTORY] DECIMAL(22,0) NOT NULL,
    [CANCELLED_BY_FACILITY] DECIMAL(22,0) NOT NULL,
    [CANCELLED_BY_PHARMACY] DECIMAL(22,0) NOT NULL,
    [NON_FORMULARY] DECIMAL(22,0) NOT NULL,
    [DUPLICATE] DECIMAL(22,0) NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2(6) NOT NULL
);

CREATE TABLE [SBMO].[DISPENSER_LOCATION]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DISPENSER_ID] BIGINT NOT NULL,
    [LOCATION_ID] BIGINT NOT NULL,
    [CELLID] VARCHAR(6),
    [STATIONID] VARCHAR(3)
);

CREATE TABLE [SBMO].[DISPENSERS]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [WARNING_LABEL_CODE] VARCHAR(3) NOT NULL,
    [LOAD_BALANCE_FACTOR] FLOAT(126) NOT NULL,
    [MODULE] VARCHAR(255) NOT NULL,
    [PORT] INT NOT NULL,
    [TIMEOUT] INT NOT NULL,
    [HOST] VARCHAR(255) NOT NULL,
    [VERSION] VARCHAR(10) NOT NULL,
    [DISABLED] DECIMAL(1,0) NOT NULL,
    [INVENTORY_ID] BIGINT NOT NULL,
    [TRANSPORT_PROPERTIES] VARCHAR(MAX),
    [USES_BATCH_IDENTIFIER] DECIMAL(1,0) NOT NULL,
    [DESCRIPTION] VARCHAR(60),
    [FACILITY_ID] BIGINT NOT NULL,
    [DISPENSER_CERT_SUBJECT] VARCHAR(255),
    [ORDER_PULL_RETRY_COUNT] DECIMAL(1,0) NOT NULL,
    [LOG_DISPENSER_REQUEST] DECIMAL(1,0) NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2(6) NOT NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(255) NOT NULL,
    [MAX_RX_COUNT_FOR_GROUPING] DECIMAL(2,0) NOT NULL
);

CREATE TABLE [SBMO].[DRUG_ORDER_PRODUCT_VERIFY]
(
    [TENANT_ID] DECIMAL(38,0),
    [ID] DECIMAL(38,0),
    [DRUG_ORDERS_ID] DECIMAL(38,0) NOT NULL,
    [MASTER_PRODUCT_PO_VERIFY_ID] DECIMAL(38,0) NOT NULL,
    [ITEM_PASSED] VARCHAR(1) NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [GTIN] VARCHAR(15),
    [EXPIRATION_DATE] DATETIME2(6) NOT NULL,
    [SERIAL_NUMBER] VARCHAR(30),
    [LOT_NUMBER] VARCHAR(30),
    [NOTES] VARCHAR(255),
    [DATE_SCANNED] DATETIME2(6) NOT NULL,
    [BAR_LINE] VARCHAR(148),
    [SCANNED_BY_USER] VARCHAR(255) NOT NULL,
    [CREATED_DATE] DATETIME2(6) NOT NULL
);

