-- BATCH 3 TABLES
-- Schema: SBMO
-- Count: 20

CREATE TABLE [SBMO].[MONTHLY_SCHEDULED_TASKS]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [APRIL] DECIMAL(1,0) NOT NULL,
    [AUGUST] DECIMAL(1,0) NOT NULL,
    [DECEMBER] DECIMAL(1,0) NOT NULL,
    [FEBRUARY] DECIMAL(1,0) NOT NULL,
    [JANUARY] DECIMAL(1,0) NOT NULL,
    [JULY] DECIMAL(1,0) NOT NULL,
    [JUNE] DECIMAL(1,0) NOT NULL,
    [MARCH] DECIMAL(1,0) NOT NULL,
    [MAY] DECIMAL(1,0) NOT NULL,
    [NOVEMBER] DECIMAL(1,0) NOT NULL,
    [OCTOBER] DECIMAL(1,0) NOT NULL,
    [SEPTEMBER] DECIMAL(1,0) NOT NULL,
    [TYPE] INT NOT NULL,
    [DATE_OF_MONTH] INT NOT NULL,
    [DAY_OF_MONTH] INT NOT NULL,
    [FIRST_LAST] INT NOT NULL,
    [DAY_TYPE] INT NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[MUTEX]
(
    [NAME] VARCHAR(25) NOT NULL,
    [STATUS] VARCHAR(25) NOT NULL,
    [LAST_RUN_TIME] DATETIME2(6) NOT NULL
);

CREATE TABLE [SBMO].[MV_FORMULARY]
(
    [VENDOR_ID] BIGINT NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [ITEM_NUMBER] VARCHAR(15) NOT NULL,
    [ONHAND_QTY] BIGINT NOT NULL,
    [ALLOCATED_QTY] BIGINT NOT NULL,
    [REFRESH_DATE] DATETIME2
);

CREATE TABLE [SBMO].[OBJECT_MAPPING]
(
    [OBJECT_OWNER] VARCHAR(30),
    [OBJECT_NAME] VARCHAR(30),
    [OBJECT_TYPE] VARCHAR(30),
    [SOURCE_TABLE] VARCHAR(30),
    [REDEF_OWNER] VARCHAR(30),
    [REDEF_OBJECT_NAME] VARCHAR(35),
    [REDEF_TABLE] VARCHAR(30),
    [REDEF_SQL] VARCHAR(MAX),
    [REDEF_STATUS] VARCHAR(10),
    [RENAME_STATUS] VARCHAR(10)
);

CREATE TABLE [SBMO].[ONCE_SCHEDULED_TASKS]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [START_DATE] DATETIME2(6) NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[ORDERS]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [ORDER_NUMBER] DECIMAL(18,2) NOT NULL,
    [SHIP_ADDRESS] VARCHAR(30) NOT NULL,
    [SHIP_ADDRESS2] VARCHAR(30),
    [SHIP_CITY] VARCHAR(35) NOT NULL,
    [SHIP_FIRST_NAME] VARCHAR(20) NOT NULL,
    [SHIP_MIDDLE_NAME] VARCHAR(1),
    [SHIP_LAST_NAME] VARCHAR(25) NOT NULL,
    [SHIP_PHONE] VARCHAR(10),
    [SHIP_STATE] VARCHAR(2) NOT NULL,
    [ORDER_TYPE] DECIMAL(18,2) NOT NULL,
    [SHIP_TYPE] DECIMAL(18,2) NOT NULL,
    [SHIP_ZIP] VARCHAR(15) NOT NULL,
    [STORE_DEA] VARCHAR(12) NOT NULL,
    [STORE_LIC] VARCHAR(12),
    [STORE_EST_SHIP_AMT] FLOAT(126),
    [SIGNATURE_REQUIRED] DECIMAL(18,2) NOT NULL,
    [STORE_ID] DECIMAL(18,2) NOT NULL,
    [ORDER_PROCESSED] DECIMAL(18,2) NOT NULL,
    [INVENTORY_ID] DECIMAL(18,2) NOT NULL,
    [GROUPING_CODE] VARCHAR(15) NOT NULL,
    [ALLOW_GROUPING] DECIMAL(18,2) NOT NULL,
    [BATCH_IDENTIFIER] DECIMAL(18,2),
    [CREATED_DATE] DATETIME2(6),
    [PROMISED_DATE] DATETIME2(6),
    [PROMISE_DATE_OVERRIDE] VARCHAR(1),
    [REQUESTED_SHIP_DATE] DATETIME2(6),
    [SHIPPING_INSTRUCTIONS] VARCHAR(2000),
    [EXTERNAL_ORDER_IDENTIFIER] VARCHAR(35),
    [VENDOR_CARRIER_CODE_IDENT] VARCHAR(25),
    [VENDOR_CARRIER_CODE_DESC] VARCHAR(100),
    [VENDOR_SHIP_BOX_IDENT] VARCHAR(20)
);

CREATE TABLE [SBMO].[PARTITION_SQL_HISTORY]
(
    [ID] DECIMAL(18,2),
    [SQL_TIMESTAMP] DATETIME2(6),
    [SQL_TEXT] VARCHAR(MAX),
    [SQL_ERROR] VARCHAR(4000),
    [REPORT_ERROR] VARCHAR(1)
);

CREATE TABLE [SBMO].[PARTITION_TABLE_LIST]
(
    [TABLE_RANK] DECIMAL(18,2),
    [TABLE_NAME] VARCHAR(30) NOT NULL
);

CREATE TABLE [SBMO].[PDX_DBA_APPLIED]
(
    [TASK_NAME] VARCHAR(25),
    [ACTION_CODE] VARCHAR(25),
    [ACTIVITY_DATE] DATETIME2(6),
    [ACTIVITY_USER] VARCHAR(30)
);

CREATE TABLE [SBMO].[PDX_SCHEMA_CONFIG]
(
    [KEY] VARCHAR(256) NOT NULL,
    [VALUE] VARCHAR(1000) NOT NULL,
    [SOURCE] VARCHAR(1) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_FILE_HASH]
(
    [FILE_NAME] VARCHAR(255) NOT NULL,
    [FILE_SOURCE] VARCHAR(1) NOT NULL,
    [FILE_HASH] VARCHAR(32) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_FILE_TASKVER]
(
    [FILE_NAME] VARCHAR(255) NOT NULL,
    [TASK_VERSION] VARCHAR(255) NOT NULL,
    [FILE_TYPE] VARCHAR(1) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_MAPPING]
(
    [MAPPING_TYPE] VARCHAR(19) NOT NULL,
    [SEARCH] VARCHAR(40) NOT NULL,
    [REPLACE] VARCHAR(30) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_PRIV_DEFAULT]
(
    [OBJECT_TYPE] VARCHAR(19) NOT NULL,
    [PRIVILEGE] VARCHAR(40) NOT NULL,
    [GRANTEE] VARCHAR(30) NOT NULL,
    [SOURCE] VARCHAR(1)
);

CREATE TABLE [SBMO].[PDX_SCHEMA_PRIV_EXCEPTION]
(
    [OBJECT_TYPE] VARCHAR(19) NOT NULL,
    [OBJECT_NAME] VARCHAR(30) NOT NULL,
    [PRIVILEGE] VARCHAR(40) NOT NULL,
    [GRANTEE] VARCHAR(30) NOT NULL,
    [SOURCE] VARCHAR(1)
);

CREATE TABLE [SBMO].[PDX_SCHEMA_PROCESS_HISTORY]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [PDX_SCHEMA_UPD_PKGCALL_HIST_ID] DECIMAL(38,0),
    [PDX_SCHEMA_VERSION_HISTORY_ID] DECIMAL(38,0),
    [PROCESS] VARCHAR(50),
    [START_DATE] DATETIME2(6),
    [END_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[PDX_SCHEMA_TASK_ERROR_LOG]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [ERROR_MESSAGE] VARCHAR(200),
    [SQL_ERROR_CODE] VARCHAR(20),
    [SQL_ERROR_MESSAGE] VARCHAR(4000),
    [STATEMENT_INDEX] DECIMAL(38,0),
    [SQL_TEXT] VARCHAR(MAX)
);

CREATE TABLE [SBMO].[PDX_SCHEMA_TASK_HISTORY]
(
    [ID] DECIMAL(38,0),
    [FILE_NAME] VARCHAR(255),
    [PDX_SCHEMA_UPD_PKGCALL_HIST_ID] DECIMAL(38,0),
    [PDX_SCHEMA_VERSION_HISTORY_ID] DECIMAL(38,0),
    [TASK_TYPE] VARCHAR(20),
    [ACTION_CODE] VARCHAR(2),
    [STATUS_CODE] VARCHAR(1),
    [START_DATE] DATETIME2(6),
    [END_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[PDX_SCHEMA_TASKVER_META]
(
    [TASK_VERSION] VARCHAR(255) NOT NULL,
    [TASK_SOURCE] VARCHAR(1) NOT NULL,
    [META_TAG] VARCHAR(20) NOT NULL,
    [TASK_VERSION_VALUE] VARCHAR(255) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_D]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [PDX_SCHEMA_UPD_HLPR_DBG_H_ID] DECIMAL(38,0) NOT NULL,
    [START_TIMESTAMP] DATETIME2(6) NOT NULL,
    [END_TIMESTAMP] DATETIME2(6),
    [MESSAGE] VARCHAR(1000),
    [SQL_ERROR] VARCHAR(MAX),
    [SQL] VARCHAR(MAX)
);

