-- BATCH 3 TABLES
-- --------------------------------------------------------

CREATE TABLE [SBMO].[ADJUSTMENT_GROUP] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [APPLIED_DATE] DATETIME2,
    [CREATED_DATE] DATETIME2 NOT NULL,
    [INVENTORY_ID] DECIMAL(38,0) NOT NULL,
    [WS_CLIENT_CERT_IDENTIFIER] VARCHAR(255)
);

CREATE TABLE [SBMO].[CHAINS] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [NHINID] BIGINT NOT NULL,
    [NAME] VARCHAR2(30 NOT NULL,
    [CHAIN_MARK_UP_PERCENT] FLOAT NOT NULL,
    [CHAIN_DISCOUNT_PERCENT] FLOAT NOT NULL,
    [PARENT_ID] BIGINT,
    [HQ_ID] VARCHAR2(20 NOT NULL,
    [MINIMUM_PRICE_OVERRIDE] DECIMAL(1,0) NOT NULL,
    [LABEL_TEMPLATE] VARCHAR(32),
    [SHIPPING_ADD_ON_TYPE] VARCHAR(1) NOT NULL,
    [SHIPPING_ADD_ON_AMOUNT] FLOAT NOT NULL,
    [USE_ADHERIS] DECIMAL(1,0),
    [ADHERIS_URL] VARCHAR(255),
    [ADHERIS_TIMEOUT] DECIMAL(9,0),
    [ADHERIS_VERSION] VARCHAR(30),
    [DEACTIVATED_DATE] DATETIME2,
    [ADHERIS_RETRY_COUNT] DECIMAL(2,0) NOT NULL,
    [ADHERIS_RETRY_OPTION] DECIMAL(1,0) NOT NULL,
    [ADHERIS_THREAD_POOL_SIZE] INT NOT NULL,
    [ADHERIS_MAX_POOL_SIZE] INT NOT NULL,
    [USE_JMS] VARCHAR(1) NOT NULL,
    [ENABLE_DIGITAL] DECIMAL(1,0)
);

CREATE TABLE [SBMO].[CONTACTS] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FIRST_NAME] VARCHAR2(20 NOT NULL,
    [LAST_NAME] VARCHAR2(25 NOT NULL,
    [TITLE] VARCHAR2(30,
    [ENTITY_ID] BIGINT NOT NULL,
    [IDX] INT NOT NULL
);

CREATE TABLE [SBMO].[CUSTOM_SCHEDULED_TASK] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [TASK_TYPE] VARCHAR(20) NOT NULL,
    [TASK_DAY] DECIMAL(3,0) NOT NULL,
    [TRIGGER_TIME] VARCHAR(100) NOT NULL,
    [SCHEDULE_GROUPING] BIGINT,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[DAILY_SCHEDULED_TASKS] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[DISPENSERS] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [WARNING_LABEL_CODE] VARCHAR2(3 NOT NULL,
    [LOAD_BALANCE_FACTOR] FLOAT NOT NULL,
    [MODULE] VARCHAR2(255 NOT NULL,
    [PORT] INT NOT NULL,
    [TIMEOUT] INT NOT NULL,
    [HOST] VARCHAR(255) NOT NULL,
    [VERSION] VARCHAR2(10 NOT NULL,
    [DISABLED] DECIMAL(1,0) NOT NULL,
    [INVENTORY_ID] BIGINT NOT NULL,
    [TRANSPORT_PROPERTIES] CLOB,
    [USES_BATCH_IDENTIFIER] DECIMAL(1,0) NOT NULL,
    [DESCRIPTION] VARCHAR(60),
    [FACILITY_ID] BIGINT NOT NULL,
    [DISPENSER_CERT_SUBJECT] VARCHAR(255),
    [ORDER_PULL_RETRY_COUNT] DECIMAL(1,0) NOT NULL,
    [LOG_DISPENSER_REQUEST] DECIMAL(1,0) NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2 NOT NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(255) NOT NULL,
    [MAX_RX_COUNT_FOR_GROUPING] DECIMAL(2,0) NOT NULL
);

CREATE TABLE [SBMO].[MONTHLY_SCHEDULED_TASKS] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [APRIL] DECIMAL(1,0) NOT NULL,
    [AUGUST] DECIMAL(1,0) NOT NULL,
    [DECEMBER] DECIMAL(1,0) NOT NULL,
    [FEBRUARY] DECIMAL(1,0) NOT NULL,
    [JANUARY] DECIMAL(1,0) NOT NULL,
    [JULY] DECIMAL(1,0) NOT NULL,
    [JUNE] DECIMAL(1,0) NOT NULL,
    [MARCH] DECIMAL(1,0) NOT NULL,
    [MAY] DECIMAL(1,0) NOT NULL,
    [NOVEMBER] DECIMAL(1,0) NOT NULL,
    [OCTOBER] DECIMAL(1,0) NOT NULL,
    [SEPTEMBER] DECIMAL(1,0) NOT NULL,
    [TYPE] INT NOT NULL,
    [DATE_OF_MONTH] INT NOT NULL,
    [DAY_OF_MONTH] INT NOT NULL,
    [FIRST_LAST] INT NOT NULL,
    [DAY_TYPE] INT NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[ONCE_SCHEDULED_TASKS] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [START_DATE] DATETIME2 NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[PURCHASE_ORDER_GROUP] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [CREATED_DATE] DATETIME2 NOT NULL,
    [INVENTORY_ID] DECIMAL(38,0) NOT NULL
);

CREATE TABLE [SBMO].[REPORT_REQUEST_PARAMETER] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [REPORT_REQUEST_ID] BIGINT NOT NULL,
    [PARAMETER_NAME] VARCHAR(60) NOT NULL,
    [PARAMETER_VALUE] VARCHAR(1020) NOT NULL
);

CREATE TABLE [SBMO].[VENDOR] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DEACTIVATE] DATETIME2,
    [NAME] VARCHAR2(28 NOT NULL,
    [NHINVEN] VARCHAR2(8 NOT NULL,
    [NHINVENLEV] INT,
    [DEFAULT_ITEM_NUMBER_QUALIFIER] VARCHAR2(2 NOT NULL,
    [TRANSPORT_TYPE] INT,
    [TRANSPORT_PROPERTIES] CLOB,
    [BILLING_TEMPLATE_PATH] VARCHAR2(255,
    [BILLING_TEMPLATE_PROPERTIES] CLOB,
    [DAY_SUPPLY_THRESHOLD] BIGINT NOT NULL,
    [BILLING_TRANSPORT_TYPE] INT,
    [FORMULARY_INVENTORY_TYPE] INT NOT NULL,
    [BILLING_TRANSPORT_PROPERTIES] CLOB,
    [THREE_DIGIT_VENDOR_CODE] VARCHAR2(32 NOT NULL,
    [MINIMUM_PRICE_OVERRIDE] DECIMAL(1,0) NOT NULL,
    [ALLOW_MULTIPLE_INVENTORIES] DECIMAL(1,0),
    [EXCLUDE_FROM_BILLING] DECIMAL(1,0) NOT NULL,
    [INV_MGMT_TRANSPORT_TYPE] BIGINT,
    [INV_MGMT_TRANSPORT_PROP] CLOB,
    [INV_MGMT_TEMPLATE_PATH] VARCHAR(255),
    [LAST_UPDATED_DATE] DATETIME2 NOT NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(255) NOT NULL,
    [DISABLE_856] VARCHAR(1),
    [ALLOW_CSOS] VARCHAR(1),
    [DESCRIPTION] VARCHAR(255),
    [CII_RECEIVING] VARCHAR(1),
    [ENABLE_BAR_CODE_SCANNING] VARCHAR(1),
    [BAR_CODE_TYPE] DECIMAL(1,0),
    [PERCENTAGE_TO_SCAN_PO] DECIMAL(3,0),
    [TRANSPORT_855_PROPERTIES] CLOB,
    [TRANSPORT_855_TYPE] INT,
    [COST_UPDATE_NHIN_VENDOR] VARCHAR(8)
);

CREATE TABLE [SBMO].[WEEKLY_SCHEDULED_TASKS] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FRIDAY] DECIMAL(1,0) NOT NULL,
    [MONDAY] DECIMAL(1,0) NOT NULL,
    [SATURDAY] DECIMAL(1,0) NOT NULL,
    [SUNDAY] DECIMAL(1,0) NOT NULL,
    [THURSDAY] DECIMAL(1,0) NOT NULL,
    [TUESDAY] DECIMAL(1,0) NOT NULL,
    [WEDNESDAY] DECIMAL(1,0) NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);
