-- BATCH 4 TABLES
-- Schema: SBMO
-- Count: 20

CREATE TABLE [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_H]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [PROC] VARCHAR(30) NOT NULL,
    [PARMS] VARCHAR(4000),
    [DEBUG_TIMESTAMP] DATETIME2(6),
    [SQL_ERROR] VARCHAR(MAX)
);

CREATE TABLE [SBMO].[PDX_SCHEMA_UPD_PKGCALL_ERR_LOG]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [ERROR_MESSAGE] VARCHAR(200),
    [SQL_ERROR_CODE] VARCHAR(20),
    [SQL_ERROR_MESSAGE] VARCHAR(4000)
);

CREATE TABLE [SBMO].[PDX_SCHEMA_UPD_PKGCALL_HIST]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [TARGET_VERSION] VARCHAR(20),
    [STATUS_CODE] VARCHAR(1),
    [RETURN_CODE] DECIMAL(2,0),
    [START_DATE] DATETIME2(6),
    [END_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[PDX_SCHEMA_UPDATER_MANIFEST]
(
    [VERSION] VARCHAR(20) NOT NULL,
    [FILE_NAME] VARCHAR(100) NOT NULL,
    [APPLY_ORDER] INT NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_UPDATER_SQL]
(
    [FILE_NAME] VARCHAR(255) NOT NULL,
    [VERSION] VARCHAR(20),
    [ACTION_CODE] VARCHAR(1),
    [ACTION_DATE] DATETIME2(6),
    [STATUS_CODE] VARCHAR(1),
    [STATEMENT_INDEX] DECIMAL(38,0),
    [SQL] VARCHAR(MAX) NOT NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_VERSION_ERROR_LOG]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [ERROR_MESSAGE] VARCHAR(200),
    [SQL_ERROR_CODE] VARCHAR(20),
    [SQL_ERROR_MESSAGE] VARCHAR(4000)
);

CREATE TABLE [SBMO].[PDX_SCHEMA_VERSION_HISTORY]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [PDX_SCHEMA_UPD_PKGCALL_HIST_ID] DECIMAL(38,0),
    [CURRENT_VERSION] VARCHAR(20),
    [TARGET_VERSION] VARCHAR(20),
    [STATUS_CODE] VARCHAR(1),
    [START_DATE] DATETIME2(6),
    [END_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[PHONE_ADDRESS_OWNERS]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[PHONES]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [PHONE_NUMBER] VARCHAR(10) NOT NULL,
    [OWNER_ID] BIGINT NOT NULL,
    [IDX] INT NOT NULL
);

CREATE TABLE [SBMO].[PRESTATS_INVENTORY]
(
    [STATID] VARCHAR(128),
    [TYPE] CHAR(1),
    [VERSION] DECIMAL(18,2),
    [FLAGS] DECIMAL(18,2),
    [C1] VARCHAR(128),
    [C2] VARCHAR(128),
    [C3] VARCHAR(128),
    [C4] VARCHAR(128),
    [C5] VARCHAR(128),
    [C6] VARCHAR(128),
    [N1] DECIMAL(18,2),
    [N2] DECIMAL(18,2),
    [N3] DECIMAL(18,2),
    [N4] DECIMAL(18,2),
    [N5] DECIMAL(18,2),
    [N6] DECIMAL(18,2),
    [N7] DECIMAL(18,2),
    [N8] DECIMAL(18,2),
    [N9] DECIMAL(18,2),
    [N10] DECIMAL(18,2),
    [N11] DECIMAL(18,2),
    [N12] DECIMAL(18,2),
    [N13] DECIMAL(18,2),
    [D1] DATETIME2,
    [T1] DATETIME2(6) WITH TIME ZONE,
    [R1] RAW(1000),
    [R2] RAW(1000),
    [R3] RAW(1000),
    [CH1] VARCHAR(1000),
    [CL1] VARCHAR(MAX)
);

CREATE TABLE [SBMO].[PRESTATS_ORDERS]
(
    [STATID] VARCHAR(128),
    [TYPE] CHAR(1),
    [VERSION] DECIMAL(18,2),
    [FLAGS] DECIMAL(18,2),
    [C1] VARCHAR(128),
    [C2] VARCHAR(128),
    [C3] VARCHAR(128),
    [C4] VARCHAR(128),
    [C5] VARCHAR(128),
    [C6] VARCHAR(128),
    [N1] DECIMAL(18,2),
    [N2] DECIMAL(18,2),
    [N3] DECIMAL(18,2),
    [N4] DECIMAL(18,2),
    [N5] DECIMAL(18,2),
    [N6] DECIMAL(18,2),
    [N7] DECIMAL(18,2),
    [N8] DECIMAL(18,2),
    [N9] DECIMAL(18,2),
    [N10] DECIMAL(18,2),
    [N11] DECIMAL(18,2),
    [N12] DECIMAL(18,2),
    [N13] DECIMAL(18,2),
    [D1] DATETIME2,
    [T1] DATETIME2(6) WITH TIME ZONE,
    [R1] RAW(1000),
    [R2] RAW(1000),
    [R3] RAW(1000),
    [CH1] VARCHAR(1000),
    [CL1] VARCHAR(MAX)
);

CREATE TABLE [SBMO].[PRESTATS_RX_CORES]
(
    [STATID] VARCHAR(128),
    [TYPE] CHAR(1),
    [VERSION] DECIMAL(18,2),
    [FLAGS] DECIMAL(18,2),
    [C1] VARCHAR(128),
    [C2] VARCHAR(128),
    [C3] VARCHAR(128),
    [C4] VARCHAR(128),
    [C5] VARCHAR(128),
    [C6] VARCHAR(128),
    [N1] DECIMAL(18,2),
    [N2] DECIMAL(18,2),
    [N3] DECIMAL(18,2),
    [N4] DECIMAL(18,2),
    [N5] DECIMAL(18,2),
    [N6] DECIMAL(18,2),
    [N7] DECIMAL(18,2),
    [N8] DECIMAL(18,2),
    [N9] DECIMAL(18,2),
    [N10] DECIMAL(18,2),
    [N11] DECIMAL(18,2),
    [N12] DECIMAL(18,2),
    [N13] DECIMAL(18,2),
    [D1] DATETIME2,
    [T1] DATETIME2(6) WITH TIME ZONE,
    [R1] RAW(1000),
    [R2] RAW(1000),
    [R3] RAW(1000),
    [CH1] VARCHAR(1000),
    [CL1] VARCHAR(MAX)
);

CREATE TABLE [SBMO].[PRIORITY_CHANGE_ALERTS]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FORMULARY_ID] BIGINT NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [ACTION] DECIMAL(2,0) NOT NULL,
    [ADDED_DATE] DATETIME2(6) NOT NULL,
    [ACKNOWLEDGED] DATETIME2(6),
    [ACKNOWLEDGED_BY] VARCHAR(256),
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[PURCHASE_ORDER]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [PO_GROUP_ID] DECIMAL(18,2) NOT NULL,
    [CONSIGNED] DECIMAL(18,2) NOT NULL,
    [VENDOR_ID] DECIMAL(18,2) NOT NULL,
    [PURCHASE_ORDER_NUMBER] DECIMAL(18,2) NOT NULL,
    [ACK_RECEIVED_USER_ID] VARCHAR(255),
    [CREATED_USER_ID] VARCHAR(255) NOT NULL,
    [APPLIED_TO_INVENTORY_DATE] DATETIME2(6),
    [ACK_RECEIVED_DATE] DATETIME2(6),
    [APPLIED_TO_INVENTORY_USER_ID] VARCHAR(255),
    [ORDER_TRANSMIT_DATE] DATETIME2(6),
    [ORDER_TRANSMIT_USER_ID] VARCHAR(255),
    [CREATED_DATE] DATETIME2(6) NOT NULL,
    [CHECK_IN_DATE] DATETIME2(6),
    [SUBMIT_DATE] DATETIME2(6),
    [CONTROL_NUMBER] DECIMAL(18,2),
    [INVOICE_NUMBER] VARCHAR(255),
    [FACILITY_ID] DECIMAL(38,0) NOT NULL,
    [TRANSMIT_STATUS_855] VARCHAR(1),
    [TRANSMIT_DATE_855] DATETIME2(6)
);

CREATE TABLE [SBMO].[PURCHASE_ORDER_GROUP]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [CREATED_DATE] DATETIME2(6) NOT NULL,
    [INVENTORY_ID] DECIMAL(18,2) NOT NULL
);

CREATE TABLE [SBMO].[PURGE_CONFIG_SETTINGS]
(
    [NAME] VARCHAR(30) NOT NULL,
    [VALUE] VARCHAR(4000) NOT NULL,
    [COMMENTS] VARCHAR(4000)
);

CREATE TABLE [SBMO].[PURGE_ERROR_LOG]
(
    [ID] DECIMAL(18,2) NOT NULL,
    [ERROR_TIME] DATETIME2(6) NOT NULL,
    [CODE_BLOCK] VARCHAR(30) NOT NULL,
    [SQL_CODE] DECIMAL(18,2),
    [SQL_ERRM] VARCHAR(250),
    [EXCEPTION_MESSAGE] VARCHAR(4000) NOT NULL,
    [PARAMETER_VALUES] VARCHAR(4000)
);

CREATE TABLE [SBMO].[PURGE_HISTORY]
(
    [ID] DECIMAL(18,2) NOT NULL,
    [TABLE_NAME] VARCHAR(30) NOT NULL,
    [START_DATE] DATETIME2 NOT NULL,
    [PURGE_DATE] DATETIME2 NOT NULL,
    [END_DATE] DATETIME2,
    [TOT_ELAPSED_SECS] DECIMAL(18,2),
    [TOT_INDEX_SECS] DECIMAL(18,2),
    [TOT_NBR_CHUNKS] DECIMAL(18,2),
    [NBR_ROWS_PURGED] DECIMAL(18,2),
    [NBR_ROWS_DELETED_FK] DECIMAL(18,2),
    [TOT_ELAPSED_FK_SECS] DECIMAL(18,2),
    [NBR_SUBPARTS_DROPPED] DECIMAL(18,2),
    [TOT_ELAPSED_DROP_SECS] DECIMAL(18,2),
    [STATUS] VARCHAR(100) NOT NULL,
    [INDEX_SQL] VARCHAR(4000)
);

CREATE TABLE [SBMO].[PURGE_HISTORY_CHUNKS]
(
    [ID] DECIMAL(18,2) NOT NULL,
    [ID_PURGE_HISTORY_PARTITIONS] DECIMAL(18,2) NOT NULL,
    [TABLE_NAME] VARCHAR(30) NOT NULL,
    [PART_NAME] VARCHAR(30) NOT NULL,
    [TASK_NAME] VARCHAR(128) NOT NULL,
    [START_TIME] DATETIME2 NOT NULL,
    [END_TIME] DATETIME2 NOT NULL,
    [ROW_COUNT] DECIMAL(18,2) NOT NULL
);

CREATE TABLE [SBMO].[PURGE_HISTORY_PARTITIONS]
(
    [ID] DECIMAL(18,2) NOT NULL,
    [ID_PURGE_HISTORY] DECIMAL(18,2) NOT NULL,
    [TABLE_NAME] VARCHAR(30) NOT NULL,
    [PARTITION_NAME] VARCHAR(30) NOT NULL,
    [TASK_NAME] VARCHAR(128) NOT NULL,
    [START_DATE] DATETIME2 NOT NULL,
    [END_DATE] DATETIME2,
    [TOT_ELAPSED_SECS] DECIMAL(18,2),
    [TOT_INDEX_SECS] DECIMAL(18,2),
    [TOT_NBR_CHUNKS] DECIMAL(18,2),
    [NBR_ROWS_PURGED] DECIMAL(18,2),
    [NBR_ROWS_DELETED_FK] DECIMAL(18,2),
    [NBR_ROWS_DELETED_CHILD_FK] DECIMAL(18,2),
    [NBR_ROWS_DELETED_GRANDCHILD_FK] DECIMAL(18,2),
    [TOT_ELAPSED_FK_SECS] DECIMAL(18,2),
    [NBR_SUBPARTS_DROPPED] DECIMAL(18,2),
    [TOT_ELAPSED_DROP_SECS] DECIMAL(18,2),
    [STATUS] VARCHAR(100) NOT NULL,
    [CHUNK_SQL] VARCHAR(4000),
    [TASK_SQL] VARCHAR(4000),
    [FK_SQL] VARCHAR(MAX),
    [CHILD_FK_SQL] VARCHAR(MAX),
    [GRANDCHILD_FK_SQL] VARCHAR(MAX),
    [INDEX_SQL] VARCHAR(4000)
);

