-- BATCH 2 TABLES
-- --------------------------------------------------------

CREATE TABLE [SBMO].[ADDRESSES] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ADDRESS] VARCHAR2(30 NOT NULL,
    [ADDRESS_LINE_2] VARCHAR2(30,
    [CITY] VARCHAR(35) NOT NULL,
    [STATE] INT NOT NULL,
    [ZIP] VARCHAR(15) NOT NULL,
    [OWNER_ID] BIGINT NOT NULL,
    [IDX] INT NOT NULL,
    [COUNTRY] VARCHAR2(4 NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2 NOT NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(255) NOT NULL
);

CREATE TABLE [SBMO].[AUDIT_LOG] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [ACTION] DECIMAL(38,0) NOT NULL,
    [NEW_VALUE] VARCHAR(1024),
    [OBJECT_NAME] VARCHAR(1024) NOT NULL,
    [OBJECT_ID] DECIMAL(38,0) NOT NULL,
    [OLD_VALUE] VARCHAR(1024),
    [PROPERTY] VARCHAR(1024) NOT NULL,
    [TIME_STAMP] DATETIME2 NOT NULL,
    [USER_ID] VARCHAR(255) NOT NULL,
    [CREATED_DATE] DATETIME2,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[DASHBOARD_SETTINGS] (
    [TENANT_ID] DECIMAL(38,0),
    [FACILITY_ID] DECIMAL(38,0),
    [ID] DECIMAL(38,0),
    [REFRESH_MINUTES] DECIMAL(3,0) NOT NULL,
    [DAY_OF_WEEK] DECIMAL(1,0) NOT NULL,
    [START_TIME] DATETIME2 NOT NULL,
    [STOP_TIME] DATETIME2 NOT NULL
);

CREATE TABLE [SBMO].[DASHBOARD_STATISTICS] (
    [TENANT_ID] DECIMAL(38,0),
    [FACILITY_ID] DECIMAL(38,0),
    [ID] DECIMAL(38,0),
    [PEND_STORE] DECIMAL(22,0) NOT NULL,
    [PEND_STORE_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [PEND_MAIL] DECIMAL(22,0) NOT NULL,
    [PEND_MAIL_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [PEND_SPECIALTY] DECIMAL(22,0) NOT NULL,
    [PEND_SPECIALTY_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [PEND_PROMISED_DATE] DECIMAL(22,0) NOT NULL,
    [PEND_PROMISED_DATE_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [PEND_INADEQ_INVENT] DECIMAL(22,0) NOT NULL,
    [PEND_INADEQ_INVENT_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [QUEUED] DECIMAL(22,0) NOT NULL,
    [QUEUED_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [ERROR_TO_DISPENSE] DECIMAL(22,0) NOT NULL,
    [ERROR_TO_DISPENSE_OUTSTANDING] DECIMAL(22,0) NOT NULL,
    [SENT_TO_DISPENSER] DECIMAL(22,0) NOT NULL,
    [CANCELLED_BY_DISPENSER] DECIMAL(22,0) NOT NULL,
    [PROCESSED] DECIMAL(22,0) NOT NULL,
    [REJECTED_INADEQUATE_INVENTORY] DECIMAL(22,0) NOT NULL,
    [CANCELLED_BY_FACILITY] DECIMAL(22,0) NOT NULL,
    [CANCELLED_BY_PHARMACY] DECIMAL(22,0) NOT NULL,
    [NON_FORMULARY] DECIMAL(22,0) NOT NULL,
    [DUPLICATE] DECIMAL(22,0) NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2 NOT NULL
);

CREATE TABLE [SBMO].[ENTITIES] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[FILLING_STATION] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL,
    [TYPE] VARCHAR(30) NOT NULL,
    [DESCRIPTION] VARCHAR(30) NOT NULL
);

CREATE TABLE [SBMO].[INVENTORY] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [NAME] VARCHAR2(255 NOT NULL,
    [DATE_OF_LAST_PHYSICAL_COUNT] DATETIME2,
    [FACILITY_ID] BIGINT NOT NULL,
    [AVAILABLE_FOR_TYPE] DECIMAL(1,0) NOT NULL,
    [IGNORE_NDC_FORMULARY_STORE_DEL] VARCHAR(1) NOT NULL,
    [IGNORE_NDC_FORMULARY_MAIL_DEL] VARCHAR(1) NOT NULL,
    [IGNORE_NDC_FORMULARY_SPECIALTY] VARCHAR(1) NOT NULL,
    [CATEGORY] DECIMAL(1,0) NOT NULL
);

CREATE TABLE [SBMO].[PHONES] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [PHONE_NUMBER] VARCHAR2(10 NOT NULL,
    [OWNER_ID] BIGINT NOT NULL,
    [IDX] INT NOT NULL
);

CREATE TABLE [SBMO].[REPORT_REQUEST] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [REPORT_NAME] VARCHAR(50) NOT NULL,
    [USER_ID] VARCHAR(255) NOT NULL,
    [FORMAT] VARCHAR(32) NOT NULL,
    [SUBMISSION_DATE] DATETIME2 NOT NULL,
    [START_DATE] DATETIME2,
    [COMPLETION_DATE] DATETIME2,
    [STATUS] VARCHAR(12) NOT NULL,
    [DOWNLOAD_LINK] VARCHAR(256),
    [HASH] DECIMAL(16,0) NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[RX_CORES_MIN_DATE] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [STATUS] INT NOT NULL,
    [MIN_DATE] DATETIME2 NOT NULL,
    [DATE_TYPE] INT NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[SCHEDULED_TASKS] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [JOB_NAME] VARCHAR2(255 NOT NULL,
    [REPEAT] DECIMAL(1,0) NOT NULL,
    [REPEAT_INTERVAL] INT,
    [REPEAT_INTERVAL_UNIT] INT,
    [TASK_NAME] VARCHAR2(255 NOT NULL,
    [START_TIME] DATETIME2 NOT NULL,
    [ENABLED] DECIMAL(1,0) NOT NULL,
    [LAST_EXECUTION_DATE] DATETIME2,
    [LAST_EXECUTION_RESULT] VARCHAR2(255,
    [PROPS] BLOB,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[SHIP_ITEMS] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [PARTITION_STAMP] DATETIME2 NOT NULL,
    [PURCHASE_ORDER_NUMBER] VARCHAR2(255 NOT NULL,
    [SHIPMENT_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[SYSTEM_MESSAGES] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [PARTITION_STAMP] DATETIME2 NOT NULL,
    [MESSAGE] VARCHAR(255) NOT NULL,
    [ADDED_DATE] DATETIME2 NOT NULL,
    [MESSAGE_TYPE] DECIMAL(38,0),
    [ACKNOWLEDGED_BY] VARCHAR(255),
    [ACKNOWLEDGED] DATETIME2,
    [DATA] BLOB,
    [ERROR_TYPE] DECIMAL(38,0) NOT NULL,
    [RESOLUTION_TEXT] CLOB,
    [REFERENCE_ID] DECIMAL(38,0),
    [REFERENCE_TYPE] DECIMAL(38,0),
    [CREATED_DATE] DATETIME2,
    [FACILITY_ID] BIGINT NOT NULL
);
