-- BATCH 7 TABLES
-- ------------------------------------------------------------------

CREATE TABLE [SBMO].[INVENTORY_AUDIT] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [ALLOCATED_CHANGE] FLOAT NULL,
    [ONHAND_CHANGE] FLOAT NULL,
    [UPDATED_DATE] DATETIME2 NULL,
    [DRUG_ORDER_ID] DECIMAL(38,0) NULL,
    [FORMULARY_ID] DECIMAL(38,0) NULL,
    [RET_ADJ_ID] DECIMAL(38,0) NULL,
    [RX_ID] DECIMAL(38,0) NULL,
    [CREATED_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[MEDICAL_SUPPLIES] (
    [ID] DECIMAL(38,0) NULL,
    [TENANT_ID] DECIMAL(38,0) NULL,
    [RX_CORE_ID] DECIMAL(38,0) NULL,
    [NAME] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[RX_DIGITAL_DOCUMENTS] (
    [ID] DECIMAL(38,0) NULL,
    [TENANT_ID] DECIMAL(38,0) NULL,
    [RX_CORES_ID] DECIMAL(38,0) NULL,
    [QR_CODE_IMAGE] VARBINARY(MAX) NULL,
    [QR_CODE_LINK] VARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[RX_DOCUMENTS] (
    [ID] DECIMAL(38,0) NULL,
    [TENANT_ID] DECIMAL(38,0) NULL,
    [PROGRAM_CODE] VARCHAR(MAX) NULL,
    [DOCUMENT_CODE] VARCHAR(MAX) NULL,
    [CHECK_SUM] VARCHAR(MAX) NULL,
    [RX_CORES_ID] DECIMAL(38,0) NULL,
    [FILE_CONTENTS] VARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[RX_HOURS_OF_ADMINISTRATION] (
    [ID] DECIMAL(38,0) NULL,
    [TENANT_ID] DECIMAL(38,0) NULL,
    [RX_CORES_ID] DECIMAL(38,0) NULL,
    [ALL_DAYS_SAME] VARCHAR(MAX) NULL,
    [ALL_DAYS_START_DATE] DATETIME2 NULL,
    [ALL_DAYS_END_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[RX_IMAGE_DATA] (
    [ID] DECIMAL(38,0) NULL,
    [TENANT_ID] DECIMAL(38,0) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [RX_CORES_ID] DECIMAL(38,0) NULL,
    [IMAGE] VARBINARY(MAX) NULL,
    [TEXT] VARCHAR(MAX) NULL,
    [LANGUAGE] VARCHAR(MAX) NULL,
    [FORMAT] VARCHAR(MAX) NULL,
    [TYPE] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[RX_LOTS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PARTITION_STAMP] DATETIME2 NULL,
    [NUM] VARCHAR(MAX) NULL,
    [RX_ID] DECIMAL(38,0) NULL,
    [EXPIRE] DATETIME2 NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [SERIAL_NUMBER] VARCHAR(MAX) NULL,
    [BARCODE_TYPE] VARCHAR(MAX) NULL,
    [BARCODE_RAW_DATA] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[RX_PRINT_CHR] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [RX_ID] DECIMAL(38,0) NULL,
    [CHR_CONTENT_CODE] DECIMAL(38,0) NULL,
    [CHR_CONTENT] VARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NULL
);

CREATE TABLE [SBMO].[RX_STATE_TRANSITION] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [RX_CORE_ID] DECIMAL(38,0) NULL,
    [TRANSITION_TYPE] DECIMAL(38,0) NULL,
    [TRANSITION_TIME] DATETIME2 NULL,
    [USER_ID] VARCHAR(MAX) NULL,
    [NOTIFICATION_SENT] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[RX_TP_INFO] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [RX_ID] DECIMAL(38,0) NULL,
    [ORDINAL] DECIMAL(38,0) NULL,
    [CARRIER_CODE] VARCHAR(MAX) NULL,
    [PLAN_CODE] VARCHAR(MAX) NULL,
    [PLAN_NAME] VARCHAR(MAX) NULL,
    [BIN] VARCHAR(MAX) NULL,
    [PCN] VARCHAR(MAX) NULL,
    [PLAN_GROUP_CODE] VARCHAR(MAX) NULL,
    [RELATIONSHIP_CODE] VARCHAR(MAX) NULL,
    [PLAN_TYPE] VARCHAR(MAX) NULL,
    [CARD_IDENTIFIER] VARCHAR(MAX) NULL,
    [TP_AUTH_NUM] VARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [DISALLOW_INCENTIVES] VARCHAR(MAX) NULL,
    [INSURANCE_PAID] FLOAT NULL
);

CREATE TABLE [SBMO].[RX_VIAL_INFOS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [PARTITION_STAMP] DATETIME2 NULL,
    [QC_RPH_INIT] VARCHAR(MAX) NULL,
    [QC_RPH_ID] VARCHAR(MAX) NULL,
    [QC_RPH_LICENSE_NUMBER] VARCHAR(MAX) NULL,
    [RX_ID] DECIMAL(38,0) NULL,
    [VIAL_NUMBER] DECIMAL(38,0) NULL,
    [VIAL_QUANTITY] DECIMAL(38,0) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [VIAL_DECIMAL_QTY] FLOAT NULL,
    [QC_RPH_LAST_NAME] VARCHAR(MAX) NULL,
    [QC_RPH_FIRST_NAME] VARCHAR(MAX) NULL,
    [REPLENISH_RPH_FIRST_NAME] VARCHAR(MAX) NULL,
    [REPLENISH_RPH_LAST_NAME] VARCHAR(MAX) NULL,
    [REPLENISH_RPH_LICENSE_NUM] VARCHAR(MAX) NULL,
    [REPLENISH_RPH_EMPLOYEE_NUM] VARCHAR(MAX) NULL,
    [REPLENISH_TECH_FIRST_NAME] VARCHAR(MAX) NULL,
    [REPLENISH_TECH_LAST_NAME] VARCHAR(MAX) NULL,
    [REPLENISH_TECH_LICENSE_NUM] VARCHAR(MAX) NULL,
    [REPLENISH_TECH_EMPLOYEE_NUM] VARCHAR(MAX) NULL,
    [DISPENSER_STATION_IDENT] VARCHAR(MAX) NULL,
    [DISPENSER_CELL_IDENT] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[RX_WARNING_LABELS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [RX_ID] DECIMAL(38,0) NULL,
    [IDX] DECIMAL(38,0) NULL,
    [PARTITION_STAMP] DATETIME2 NULL,
    [CREATED_DATE] DATETIME2 NULL
);

