-- BATCH 8 TABLES
-- --------------------------------------------------------

CREATE TABLE [SBMO].[RX_WARNING_LABEL_CODES] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [PARTITION_STAMP] DATETIME2 NOT NULL,
    [LABEL_CODE] VARCHAR2(8 NOT NULL,
    [LABEL_LANGUAGE] VARCHAR2(8,
    [SOURCE] VARCHAR2(255,
    [IDX] INT NOT NULL,
    [RX_WARNING_LABEL_ID] BIGINT NOT NULL,
    [WARNING_LABEL_GROUP] VARCHAR(10)
);
