-- BATCH 6 TABLES
-- Schema: SBMO
-- Count: 20

CREATE TABLE [SBMO].[RX_DETAILS]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [CONSIGNED] DECIMAL(18,2) NOT NULL,
    [STORE_ACQCOST] FLOAT(126) NOT NULL,
    [ALT_PRESCRIBER_NAME] VARCHAR(28),
    [PRESCRIBER_DEA] VARCHAR(35),
    [PRESCRIBER_FIRST_NAME] VARCHAR(20),
    [PRESCRIBER_MIDDLE_NAME] VARCHAR(1),
    [PRESCRIBER_LAST_NAME] VARCHAR(25) NOT NULL,
    [PRESCRIBER_PHONE] VARCHAR(10),
    [PRESCRIBER_TYPE] VARCHAR(15),
    [DRUG_NAME] VARCHAR(28) NOT NULL,
    [DRUG_FULL_NAME] VARCHAR(60),
    [FILL_DATE] DATETIME2(6) NOT NULL,
    [PATIENT_ALLOWS_GENERIC] DECIMAL(18,2) NOT NULL,
    [GENERIC_NAME] VARCHAR(28) NOT NULL,
    [REFILL_NUM] DECIMAL(18,2) NOT NULL,
    [REFILLS_REMAIN] VARCHAR(5),
    [RX_WRITTEN_DATE] DATETIME2(6) NOT NULL,
    [RX_EXPIRES] DATETIME2(6) NOT NULL,
    [RX_FIRST_FILLED] DATETIME2(6) NOT NULL,
    [SAFETY_CAP] DECIMAL(18,2) NOT NULL,
    [SIG_TEXT] VARCHAR(515) NOT NULL,
    [SUBSTITUTED_FOR_NAME] VARCHAR(32),
    [TX_MESSAGE] VARCHAR(28),
    [DRUG_UNIT] VARCHAR(3),
    [DRUG_MANUFACTURER] VARCHAR(28),
    [NET_DUE] FLOAT(126),
    [DRUG_IMPRINT] VARCHAR(710),
    [DIF_DRUG_LAST_FILL] DECIMAL(18,2) NOT NULL,
    [GENERIC_FULL_NAME] VARCHAR(60),
    [PRINT_FILLED_DATE] VARCHAR(8),
    [TX_COST] FLOAT(126),
    [FILLED_DISPENSER_ID] DECIMAL(18,2),
    [TX_VIA_AUTO_FILL] VARCHAR(255),
    [TOTAL_TP_BALANCE] FLOAT(126),
    [TP_AUTH_NUM] VARCHAR(20),
    [TX_PRICE] FLOAT(126),
    [PRESCRIBER_NPI] VARCHAR(10),
    [UC_PRICE] DECIMAL(18,2),
    [PARTIAL_FILL_STATUS] VARCHAR(1),
    [RX_SOURCE] DECIMAL(18,2),
    [PREVIOUS_PHARMACY] VARCHAR(60),
    [ALT_PRESCRIBER_TYPE] VARCHAR(15),
    [USER_DEFINED_DRUG_NAME] VARCHAR(60),
    [AUTOFILL_ENABLED] VARCHAR(5),
    [AUTOPAY_ENABLED] VARCHAR(5),
    [OVERRIDDEN_PRICE_AMOUNT] DECIMAL(18,2),
    [CIM_CORRECTION_WRITTEN] DECIMAL(18,2),
    [CREATED_DATE] DATETIME2(6),
    [CIM_CANCEL_WRITTEN] DECIMAL(18,2),
    [CIM_LAST_UPDATE_DATE] DATETIME2(6),
    [PRESCRIBER_ADDRESS] VARCHAR(255),
    [PRESCRIBER_ADDRESS_LINE_2] VARCHAR(255),
    [PRESCRIBER_CITY] VARCHAR(35),
    [PRESCRIBER_STATE] VARCHAR(2),
    [PRESCRIBER_ZIP] VARCHAR(15),
    [TAXABLE_OTC] VARCHAR(1),
    [DRUG_SCHEDULE] VARCHAR(1),
    [DAW] VARCHAR(1),
    [REFILLS_AUTHORIZED] VARCHAR(3),
    [DRUG_DOSAGE_FORM] VARCHAR(30),
    [DRUG_COLOR] VARCHAR(180),
    [DRUG_CLARITY] VARCHAR(180),
    [DRUG_SCORE] VARCHAR(180),
    [DRUG_SHAPE] VARCHAR(180),
    [DRUG_FLAVOR] VARCHAR(180),
    [DRUG_IMPRINT_SIDE1] VARCHAR(240),
    [DRUG_IMPRINT_SIDE2] VARCHAR(240),
    [DRUG_COATING] VARCHAR(180),
    [GENERIC] VARCHAR(1),
    [RX_MATCH_KEY] VARCHAR(12),
    [RX_IMAGE_IDENT] VARCHAR(36),
    [OLD_RX_NUMBER] VARCHAR(16),
    [FILL_NOTE] VARCHAR(2000),
    [REQUIRE_UNIT_DOSE] VARCHAR(1),
    [COPAY_AMOUNT] FLOAT(126),
    [ALT_NHIN_DRUG_NAME] VARCHAR(45),
    [NARCOTIC_INDICATOR] VARCHAR(2),
    [BIN_CODE] VARCHAR(10),
    [HAZARDOUS_DRUG] VARCHAR(1)
);

CREATE TABLE [SBMO].[RX_DIGITAL_DOCUMENTS]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [RX_CORES_ID] DECIMAL(38,0) NOT NULL,
    [QR_CODE_IMAGE] VARBINARY(MAX),
    [QR_CODE_LINK] VARCHAR(255),
    [CREATED_DATE] DATETIME2(6) NOT NULL
);

CREATE TABLE [SBMO].[RX_DOCUMENTS]
(
    [ID] DECIMAL(38,0),
    [TENANT_ID] DECIMAL(38,0),
    [PROGRAM_CODE] VARCHAR(45),
    [DOCUMENT_CODE] VARCHAR(75),
    [CHECK_SUM] VARCHAR(30) NOT NULL,
    [RX_CORES_ID] DECIMAL(38,0) NOT NULL,
    [FILE_CONTENTS] VARCHAR(MAX) NOT NULL,
    [CREATED_DATE] DATETIME2(6) NOT NULL
);

CREATE TABLE [SBMO].[RX_HOURS_OF_ADMIN_DOSES]
(
    [ID] DECIMAL(38,0),
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [RX_HOURS_OF_ADMINISTRATION_ID] DECIMAL(38,0) NOT NULL,
    [DATE_OF_DOSE] DATETIME2(6),
    [TIME_OF_DOSE] VARCHAR(28) NOT NULL,
    [QUANTITY] DECIMAL(13,0) NOT NULL
);

CREATE TABLE [SBMO].[RX_HOURS_OF_ADMINISTRATION]
(
    [ID] DECIMAL(38,0),
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [RX_CORES_ID] DECIMAL(38,0) NOT NULL,
    [ALL_DAYS_SAME] VARCHAR(1),
    [ALL_DAYS_START_DATE] DATETIME2(6),
    [ALL_DAYS_END_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[RX_IMAGE_DATA]
(
    [ID] DECIMAL(38,0),
    [TENANT_ID] DECIMAL(38,0),
    [CREATED_DATE] DATETIME2(6) NOT NULL,
    [RX_CORES_ID] DECIMAL(38,0) NOT NULL,
    [IMAGE] VARBINARY(MAX) NOT NULL,
    [TEXT] VARCHAR(MAX),
    [LANGUAGE] VARCHAR(10),
    [FORMAT] VARCHAR(10),
    [TYPE] DECIMAL(1,0) NOT NULL
);

CREATE TABLE [SBMO].[RX_LOTS]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [NUM] VARCHAR(30) NOT NULL,
    [RX_ID] DECIMAL(18,2) NOT NULL,
    [EXPIRE] DATETIME2(6) NOT NULL,
    [CREATED_DATE] DATETIME2(6),
    [SERIAL_NUMBER] VARCHAR(20),
    [BARCODE_TYPE] VARCHAR(1),
    [BARCODE_RAW_DATA] VARCHAR(MAX)
);

CREATE TABLE [SBMO].[RX_PATSTORES]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [FIRST_NAME] VARCHAR(20) NOT NULL,
    [LAST_NAME] VARCHAR(25) NOT NULL,
    [MIDDLE_NAME] VARCHAR(20),
    [PATIENT_ID] VARCHAR(8) NOT NULL,
    [STORE_RPH_INITS] VARCHAR(3) NOT NULL,
    [STORE_RPH_NAME] VARCHAR(65) NOT NULL,
    [STORE_USER_INITS] VARCHAR(3) NOT NULL,
    [STORE_USER_ID] VARCHAR(38) NOT NULL,
    [STORE_TECH_INITS] VARCHAR(3),
    [STORE_RPH_LICENSE_NUM] VARCHAR(20) NOT NULL,
    [ADDRESS] VARCHAR(30) NOT NULL,
    [ADDRESS2] VARCHAR(30),
    [CITY] VARCHAR(35) NOT NULL,
    [STATE] VARCHAR(2) NOT NULL,
    [ZIP] VARCHAR(15) NOT NULL,
    [BIRTH_DATE] DATETIME2(6) NOT NULL,
    [PHONE] VARCHAR(10),
    [PATIENT_RXCOM_ID] VARCHAR(255),
    [STORE_RPH_ID] VARCHAR(38),
    [STORE_TECH_ID] VARCHAR(38),
    [CARDHOLDERID] VARCHAR(20),
    [DRUG_UPC] VARCHAR(25),
    [PATIENT_DL_NUM] VARCHAR(15),
    [STORE_PATIENT_CODE] VARCHAR(10),
    [MEDICAL_RECORD_NUMBER] VARCHAR(35),
    [LANGUAGE] VARCHAR(2),
    [GENDER] VARCHAR(1),
    [PATIENT_EMAIL_ADDRESS] VARCHAR(120),
    [LOYALTY_CARD_NUMBER] VARCHAR(50),
    [IS_NEW_PATIENT] DECIMAL(18,2),
    [PATIENT_RECORD_TYPE] VARCHAR(1),
    [ANIMAL_TYPE] VARCHAR(15),
    [CARRIER_CODE] VARCHAR(10),
    [PLAN_CODE] VARCHAR(15),
    [PLAN_NAME] VARCHAR(28),
    [BIN] VARCHAR(10),
    [PCN] VARCHAR(10),
    [CREATED_DATE] DATETIME2(6),
    [RESPONSIBLE_PARTY_LAST_NAME] VARCHAR(25),
    [RESPONSIBLE_PARTY_FIRST_NAME] VARCHAR(20),
    [VISUALLY_IMPAIRED] VARCHAR(1),
    [PATIENT_DIGITAL_DOC_STATUS] VARCHAR(1)
);

CREATE TABLE [SBMO].[RX_PRINT_CHR]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [RX_ID] BIGINT NOT NULL,
    [CHR_CONTENT_CODE] DECIMAL(2,0),
    [CHR_CONTENT] VARCHAR(MAX),
    [CREATED_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[RX_PRINT_INFO]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [LABEL] VARCHAR(MAX) NOT NULL,
    [PATIENT_ED] VARCHAR(MAX),
    [CREATED_DATE] DATETIME2(6),
    [FREE_FORM_REPORT_FORMAT] VARCHAR(10),
    [FREE_FORM_REPORT_MESSAGE] VARCHAR(MAX),
    [FREE_FORM_LABEL_FORMAT] VARCHAR(10),
    [FREE_FORM_LABEL_MESSAGE] VARCHAR(MAX)
);

CREATE TABLE [SBMO].[RX_REQUEST_ERROR]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [DRUG_NAME] VARCHAR(28) NOT NULL,
    [ORDER_TYPE] DECIMAL(18,2) NOT NULL,
    [STORE_NHINID] DECIMAL(18,2) NOT NULL,
    [ADDED_DATE] DATETIME2(6) NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [STATUS] DECIMAL(18,2),
    [INVENTORY_NAME] VARCHAR(255),
    [ERROR_CODE] VARCHAR(255),
    [ERROR_MESSAGE] VARCHAR(255),
    [REQUEST_DECIMAL_QTY] FLOAT(126),
    [REQUEST_QTY] DECIMAL(18,2),
    [RXNUM] VARCHAR(16),
    [STORE_CF_QUEUE_NUM] VARCHAR(255),
    [CREATED_DATE] DATETIME2(6),
    [TXNUM] VARCHAR(12),
    [SPECIALTY] VARCHAR(1),
    [FACILITY_ID] BIGINT NOT NULL,
    [INVENTORY_ID] DECIMAL(38,0),
    [VENDOR_ID] DECIMAL(38,0)
);

CREATE TABLE [SBMO].[RX_SHIPPING_PACKAGES]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [SHIPPED_DATE] DATETIME2(6),
    [OUNCES] FLOAT(126),
    [TRACKING_NUMBER] VARCHAR(255),
    [PACKER_ID] VARCHAR(38),
    [MANIFEST_ID] VARCHAR(38),
    [TRUE_SHIP_AMT] FLOAT(126),
    [FILLED_DISPENSER_ID] DECIMAL(18,2) NOT NULL,
    [PARENT_ID] DECIMAL(18,2),
    [BARCODE] VARCHAR(25) NOT NULL,
    [SHIP_SYS_SHPT_IDENTIFIER] VARCHAR(32),
    [SHIP_SYS_PKG_IDENTIFIER] VARCHAR(50),
    [RETURN_ADDRESS] VARCHAR(30) NOT NULL,
    [RETURN_ADDRESS2] VARCHAR(30),
    [RETURN_CITY] VARCHAR(35) NOT NULL,
    [RETURN_NAME] VARCHAR(60),
    [RETURN_PHONE] VARCHAR(10) NOT NULL,
    [RETURN_STATE] VARCHAR(2) NOT NULL,
    [SHIP_TO_ADDRESS] VARCHAR(30) NOT NULL,
    [SHIP_TO_ADDRESS2] VARCHAR(30),
    [SHIP_TO_CITY] VARCHAR(35) NOT NULL,
    [SHIP_TO_NAME] VARCHAR(60) NOT NULL,
    [SHIP_TO_PHONE] VARCHAR(10),
    [SHIP_TO_STATE] VARCHAR(2) NOT NULL,
    [RETURN_ZIP] VARCHAR(15) NOT NULL,
    [SHIP_TO_ZIP] VARCHAR(15) NOT NULL,
    [RETURN_COUNTRY] VARCHAR(30),
    [SHIP_TO_COUNTRY] VARCHAR(30),
    [CARRIER] VARCHAR(64) NOT NULL,
    [SHIP_ADDON_AMOUNT] FLOAT(126),
    [CREATED_DATE] DATETIME2(6),
    [TRACKING_URL] VARCHAR(255)
);

CREATE TABLE [SBMO].[RX_STATE_TRANSITION]
(
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [RX_CORE_ID] DECIMAL(38,0) NOT NULL,
    [TRANSITION_TYPE] DECIMAL(3,0) NOT NULL,
    [TRANSITION_TIME] DATETIME2(6) NOT NULL,
    [USER_ID] VARCHAR(255) NOT NULL,
    [NOTIFICATION_SENT] VARCHAR(1)
);

CREATE TABLE [SBMO].[RX_TP_INFO]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [RX_ID] DECIMAL(18,2) NOT NULL,
    [ORDINAL] DECIMAL(18,2) NOT NULL,
    [CARRIER_CODE] VARCHAR(10),
    [PLAN_CODE] VARCHAR(15),
    [PLAN_NAME] VARCHAR(28),
    [BIN] VARCHAR(10),
    [PCN] VARCHAR(10),
    [PLAN_GROUP_CODE] VARCHAR(15),
    [RELATIONSHIP_CODE] VARCHAR(1),
    [PLAN_TYPE] VARCHAR(2),
    [CARD_IDENTIFIER] VARCHAR(20),
    [TP_AUTH_NUM] VARCHAR(20),
    [CREATED_DATE] DATETIME2(6),
    [DISALLOW_INCENTIVES] VARCHAR(1) DEFAULT 'N' NOT NULL,
    [INSURANCE_PAID] FLOAT(126)
);

CREATE TABLE [SBMO].[RX_VIAL_INFOS]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [QC_RPH_INIT] VARCHAR(10),
    [QC_RPH_ID] VARCHAR(38),
    [QC_RPH_LICENSE_NUMBER] VARCHAR(20),
    [RX_ID] DECIMAL(18,2) NOT NULL,
    [VIAL_NUMBER] DECIMAL(18,2),
    [VIAL_QUANTITY] DECIMAL(18,2),
    [CREATED_DATE] DATETIME2(6),
    [VIAL_DECIMAL_QTY] FLOAT(126),
    [QC_RPH_LAST_NAME] VARCHAR(25),
    [QC_RPH_FIRST_NAME] VARCHAR(20),
    [REPLENISH_RPH_FIRST_NAME] VARCHAR(20),
    [REPLENISH_RPH_LAST_NAME] VARCHAR(25),
    [REPLENISH_RPH_LICENSE_NUM] VARCHAR(20),
    [REPLENISH_RPH_EMPLOYEE_NUM] VARCHAR(255),
    [REPLENISH_TECH_FIRST_NAME] VARCHAR(20),
    [REPLENISH_TECH_LAST_NAME] VARCHAR(25),
    [REPLENISH_TECH_LICENSE_NUM] VARCHAR(20),
    [REPLENISH_TECH_EMPLOYEE_NUM] VARCHAR(255),
    [DISPENSER_STATION_IDENT] VARCHAR(3),
    [DISPENSER_CELL_IDENT] VARCHAR(6)
);

CREATE TABLE [SBMO].[RX_WARNING_LABEL_CODES]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [LABEL_CODE] VARCHAR(8) NOT NULL,
    [LABEL_LANGUAGE] VARCHAR(8),
    [SOURCE] VARCHAR(255),
    [IDX] INT NOT NULL,
    [RX_WARNING_LABEL_ID] BIGINT NOT NULL,
    [WARNING_LABEL_GROUP] VARCHAR(10)
);

CREATE TABLE [SBMO].[RX_WARNING_LABELS]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [RX_ID] DECIMAL(18,2) NOT NULL,
    [IDX] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT SYSDATE NOT NULL,
    [CREATED_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[SBMO_LOCKS]
(
    [LOCK_NAME] VARCHAR(40) NOT NULL
);

CREATE TABLE [SBMO].[SBMO_PROPERTIES]
(
    [ID] BIGINT NOT NULL,
    [KEY] VARCHAR(255) NOT NULL,
    [VALUE] VARCHAR(MAX)
);

CREATE TABLE [SBMO].[SCHEDULED_TASKS]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [JOB_NAME] VARCHAR(255) NOT NULL,
    [REPEAT] DECIMAL(1,0) NOT NULL,
    [REPEAT_INTERVAL] INT,
    [REPEAT_INTERVAL_UNIT] INT,
    [TASK_NAME] VARCHAR(255) NOT NULL,
    [START_TIME] DATETIME2(6) NOT NULL,
    [ENABLED] DECIMAL(1,0) NOT NULL,
    [LAST_EXECUTION_DATE] DATETIME2(6),
    [LAST_EXECUTION_RESULT] VARCHAR(255),
    [PROPS] VARBINARY(MAX),
    [FACILITY_ID] BIGINT NOT NULL
);

