-- BATCH 2 TABLES
-- Schema: SBMO
-- Count: 20

CREATE TABLE [SBMO].[DRUG_ORDERS]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [ACK_RECEIVED_QTY] FLOAT(126),
    [PACK] FLOAT(126) NOT NULL,
    [COST] FLOAT(126),
    [COUNTER] DECIMAL(18,2),
    [ITEM_STATUS] VARCHAR(255),
    [SUB_ITEM_NUMBER] VARCHAR(15),
    [ITEM_NUMBER] VARCHAR(15) NOT NULL,
    [ORDER_QTY] FLOAT(126) NOT NULL,
    [RECQTY] FLOAT(126),
    [CHECK_IN_DATE] DATETIME2(6),
    [APPLIED_TO_INVENTORY_DATE] DATETIME2(6),
    [FORMULARY_ID] DECIMAL(18,2) NOT NULL,
    [PURCHASE_ORDER_ID] DECIMAL(18,2) NOT NULL,
    [VENDOR_ORDER_QTY] FLOAT(126) NOT NULL,
    [VENDOR_ACK_RECEIVED_QTY] FLOAT(126),
    [VENDOR_RECQTY] FLOAT(126),
    [APPLIED_QTY] DECIMAL(18,2),
    [CREATED_DATE] DATETIME2(6),
    [CONVERSION_FACTOR] FLOAT(126),
    [VENDOR_ORDER_CASE] DECIMAL(22,13)
);

CREATE TABLE [SBMO].[DRUGS]
(
    [ID] BIGINT NOT NULL,
    [DECIMAL_PACK] FLOAT(126) NOT NULL,
    [GENERIC_FULL_NAME] VARCHAR(60) NOT NULL,
    [DRUG_FULL_NAME] VARCHAR(60) NOT NULL,
    [GENERIC_NAME] VARCHAR(28) NOT NULL,
    [GPI] VARCHAR(14),
    [INJECT] DECIMAL(1,0) NOT NULL,
    [DRUG_NOTE] VARCHAR(255),
    [MFG] VARCHAR(10) NOT NULL,
    [NAME] VARCHAR(28) NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [PACK] BIGINT NOT NULL,
    [PREVIOUS_NDC] VARCHAR(11),
    [REPLACEMENT_NDC] VARCHAR(11),
    [SCHEDULE] VARCHAR(1) NOT NULL,
    [STRENGTH] VARCHAR(8),
    [TRIPLIC] DECIMAL(1,0) NOT NULL,
    [UNIT] VARCHAR(3) NOT NULL,
    [MFG_DISCONTINUE_DATE] DATETIME2(6),
    [LAST_UPDATED_DATE] DATETIME2(6) NOT NULL,
    [SIGNATURE_REQUIRED] DECIMAL(1,0) NOT NULL,
    [AWP] FLOAT(126) NOT NULL,
    [AWP_LAST_UPDATED] DATETIME2(6) NOT NULL,
    [BARCODE] VARCHAR(16),
    [NDCFMT] INT,
    [PACKAGE_QTY] FLOAT(126),
    [IND_PACK] FLOAT(126),
    [MULTI_SOURCE] VARCHAR(1),
    [DDID] INT,
    [NARCOTIC_INDICATOR] VARCHAR(2),
    [DEEP_FROZEN] DECIMAL(1,0) NOT NULL,
    [HAZARDOUS_DRUG] VARCHAR(1),
    [INNER_PACK_INDICATOR] VARCHAR(1)
);

CREATE TABLE [SBMO].[ENCRYPTION_KEYS]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [VALUE] VARCHAR(255) NOT NULL,
    [CREATED_DATE] DATETIME2(6) NOT NULL,
    [DEACTIVATED_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[ENCRYPTION_KEYS_AUDIT]
(
    [ID] DECIMAL(38,0),
    [TENANT_ID] DECIMAL(38,0),
    [ENCRYPTION_KEYS_ID] DECIMAL(38,0) NOT NULL,
    [USER_IDENTIFIER] VARCHAR(255),
    [ACTION] DECIMAL(1,0) NOT NULL,
    [OLD_VALUE] VARCHAR(255),
    [NEW_VALUE] VARCHAR(255),
    [CREATED_DATE] DATETIME2(6) NOT NULL,
    [DEACTIVATED_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[ENTITIES]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[EXT_DRUG_LOAD]
(
    [NAME] VARCHAR(255),
    [DRUG_FULL_NAME] VARCHAR(255),
    [NDC] VARCHAR(255),
    [GENERIC_NAME] VARCHAR(255),
    [GENERIC_FULL_NAME] VARCHAR(255),
    [MFG] VARCHAR(255),
    [UNIT] VARCHAR(255),
    [STRENGTH] VARCHAR(255),
    [SCHEDULE] VARCHAR(255),
    [PACK] VARCHAR(255),
    [DECIMAL_PACK] VARCHAR(255),
    [PACKAGE_QTY] VARCHAR(255),
    [IND_PACK] VARCHAR(255),
    [AWP] VARCHAR(255),
    [AWP_LAST_UPDATED] VARCHAR(255),
    [MULTI_SOURCE] VARCHAR(255),
    [TRIPLIC] VARCHAR(255),
    [INJECT] VARCHAR(255),
    [REFRIGERATED] VARCHAR(255),
    [SIGNATURE_REQUIRED] VARCHAR(255),
    [HAZMAT] VARCHAR(255),
    [LAST_UPDATED_DATE] VARCHAR(255),
    [BARCODE] VARCHAR(255),
    [DRUG_NOTE] VARCHAR(255),
    [GPI] VARCHAR(255),
    [ID] VARCHAR(255),
    [MFG_DISCONTINUE_DATE] VARCHAR(255),
    [NDCFMT] VARCHAR(255),
    [PREVIOUS_NDC] VARCHAR(255),
    [REPLACEMENT_NDC] VARCHAR(255) ) ORGANIZATION EXTERNAL ( TYPE ORACLE_LOADER DEFAULT DIRECTORY EXT_TABLES ACCESS PARAMETERS ( records delimited by newline fields terminated by '	' ) LOCATION ( 'sbmo_meijer_veterinary_drug_file.txt' ) ) REJECT LIMIT 0
);

CREATE TABLE [SBMO].[FACILITIES]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [SHORT_NAME] VARCHAR(20) NOT NULL,
    [NAME] VARCHAR(60) NOT NULL,
    [ADDRESS_LINE_1] VARCHAR(30) NOT NULL,
    [ADDRESS_LINE_2] VARCHAR(30),
    [CITY] VARCHAR(35) NOT NULL,
    [STATE] VARCHAR(2) NOT NULL,
    [ZIP] VARCHAR(15) NOT NULL,
    [COUNTY] VARCHAR(15) NOT NULL,
    [DEA_NUMBER] VARCHAR(15) NOT NULL,
    [FEDERAL_TAX_IDENTIFIER] INT NOT NULL,
    [NCPDP_NUMBER] VARCHAR(15) NOT NULL,
    [NHINID] BIGINT NOT NULL,
    [DEA_EXPIRATION_DATE] DATETIME2(6) NOT NULL,
    [TIME_ZONE] VARCHAR(50) NOT NULL,
    [TOLL_FREE_PHONE_NUMBER] VARCHAR(10) NOT NULL,
    [ALTERNATE_PHONE_NUMBER] VARCHAR(10),
    [EXPORT_ORDER_DISPENSER_MODULE] VARCHAR(255),
    [DISPENSER_COMM_ENABLED] VARCHAR(5) NOT NULL,
    [CHECK_INV_FOR_HOME_DELIVERY] VARCHAR(5) NOT NULL,
    [DRUG_LOT_NOT_REQUIRED] VARCHAR(5),
    [ORDER_PULL_DELAY] DECIMAL(8,0) NOT NULL,
    [ENABLE_ITEM_LOCATIONS] VARCHAR(5) NOT NULL,
    [RED_HOURS] DECIMAL(2,0) NOT NULL,
    [YELLOW_HOURS] DECIMAL(2,0) NOT NULL,
    [ACTIVE_DIRECTORY_GROUP] VARCHAR(255) NOT NULL,
    [PAUSE_ORDER_PROCESSING_DATE] DATETIME2(6),
    [DOC_ERROR_RESET_DATE] DATETIME2(6),
    [DOC_CON_ERROR_RESET_DATE] DATETIME2(6),
    [DISPLAY_TX_COST_ERROR] VARCHAR(1) DEFAULT 1 NOT NULL,
    [LANDING_PAGE] DECIMAL(1,0) NOT NULL,
    [STATUS_ALERT_THRESHOLD] DECIMAL(18,2),
    [PROMISED_DATE_ALERT_THRESHOLD] INT,
    [ORDER_PULL_JOB_FREQUENCY] BIGINT,
    [CHECK_INV_FOR_SPECIALTY] DECIMAL(2,0) NOT NULL,
    [TRANSITION_POLLTIME] DECIMAL(8,0) NOT NULL,
    [TRANSITION_ALERT_THRESHOLD] DECIMAL(8,0) NOT NULL,
    [TRANSITION_AUTO_TASK_DISABLED] VARCHAR(1) NOT NULL,
    [TRANSITION_ALERT_EMAIL] VARCHAR(120) NOT NULL,
    [PROMISE_DATE_ENABLED] VARCHAR(1) NOT NULL,
    [PROMISE_DATE_SUN] DECIMAL(2,0),
    [PROMISE_DATE_MON] DECIMAL(2,0),
    [PROMISE_DATE_TUE] DECIMAL(2,0),
    [PROMISE_DATE_WED] DECIMAL(2,0),
    [PROMISE_DATE_THU] DECIMAL(2,0),
    [PROMISE_DATE_FRI] DECIMAL(2,0),
    [PROMISE_DATE_SAT] DECIMAL(2,0),
    [AUTO_CANCEL_TO_STORE] VARCHAR(1),
    [QUEUE_MAX_DAYS_BACK] DECIMAL(5,0) NOT NULL,
    [CHECK_INV_FOR_STORE_DELIVERY] DECIMAL(1,0) NOT NULL,
    [MAINTAIN_INVENTORY_QUANTITIES] VARCHAR(1) NOT NULL,
    [PO_EMAIL] VARCHAR(255),
    [ORDER_PULL_THREAD_CNT] DECIMAL(2,0) NOT NULL,
    [ORDER_PULL_MAX_CNT] DECIMAL(4,0) NOT NULL,
    [ENABLE_HOLD_SPECIALTY_ORDERS] VARCHAR(5) NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2(6) NOT NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(255) NOT NULL,
    [ENABLE_ORDER_CANCEL_REASON] VARCHAR(1) NOT NULL,
    [DASHBOARD_JOB_ENABLED] VARCHAR(5) NOT NULL,
    [STATUS_UPDATE_MAX_DAYS_BACK] DECIMAL(3,0) NOT NULL,
    [IGNORE_PROM_DATE_HOME_DELIVERY] VARCHAR(1) NOT NULL,
    [IGNORE_PROM_DATE_SPECIALTY] VARCHAR(1) NOT NULL,
    [CHECK_INV_FOR_UNIT_DOSE] DECIMAL(1,0),
    [START_OF_DAY_TIME] DATETIME2(6),
    [ADHERIS_DOCUMENT_SIZE] VARCHAR(9),
    [ALLOW_SINGLE_RX_CANCELLATION] VARCHAR(1),
    [SEND_ALT_NHIN_DRUG_NAME] VARCHAR(1)
);

CREATE TABLE [SBMO].[FILLING_STATION]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL,
    [TYPE] VARCHAR(30) NOT NULL,
    [DESCRIPTION] VARCHAR(30) NOT NULL
);

CREATE TABLE [SBMO].[FORMULARY]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DEACTIVATED_DATE] DATETIME2(6),
    [EFFECTIVE_DATE] DATETIME2(6) NOT NULL,
    [CONSIGNED] DECIMAL(1,0) NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2(6) NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [ALLOCATED_QTY] BIGINT NOT NULL,
    [ONHAND_QTY] BIGINT NOT NULL,
    [DRUG_ID] BIGINT NOT NULL,
    [VENDOR_ID] BIGINT NOT NULL,
    [INVENTORY_ID] BIGINT NOT NULL,
    [LAST_DISPENSED_DATE] DATETIME2(6),
    [AVAILABLE_FOR_TYPE] INT NOT NULL,
    [ONHAND_ORIG_QTY] BIGINT,
    [OVERRIDE_SHIP_ID] BIGINT,
    [PRIORITY] DECIMAL(2,0),
    [OVERRIDE_INVENTORY] VARCHAR(1),
    [FILLING_STATION_ID] BIGINT,
    [DISPENSED_INCREMENT] FLOAT(126),
    [NOTE] VARCHAR(255),
    [OVERRIDE_ORDER_GROUPING] VARCHAR(1)
);

CREATE TABLE [SBMO].[FORMULARY_REORDER]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ORDER_POINT] FLOAT(126) NOT NULL,
    [ORDER_QTY] FLOAT(126) NOT NULL,
    [MINIMUM_QTY] FLOAT(126) NOT NULL,
    [LAST_ORDER_DATE] DATETIME2(6),
    [HOLD_UNTIL_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[INVENTORY]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [NAME] VARCHAR(255) NOT NULL,
    [DATE_OF_LAST_PHYSICAL_COUNT] DATETIME2(6),
    [FACILITY_ID] BIGINT NOT NULL,
    [AVAILABLE_FOR_TYPE] DECIMAL(1,0) NOT NULL,
    [IGNORE_NDC_FORMULARY_STORE_DEL] VARCHAR(1) NOT NULL,
    [IGNORE_NDC_FORMULARY_MAIL_DEL] VARCHAR(1) NOT NULL,
    [IGNORE_NDC_FORMULARY_SPECIALTY] VARCHAR(1) NOT NULL,
    [CATEGORY] DECIMAL(1,0) NOT NULL
);

CREATE TABLE [SBMO].[INVENTORY_AUDIT]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [ALLOCATED_CHANGE] FLOAT(126),
    [ONHAND_CHANGE] FLOAT(126),
    [UPDATED_DATE] DATETIME2(6) NOT NULL,
    [DRUG_ORDER_ID] DECIMAL(18,2),
    [FORMULARY_ID] DECIMAL(18,2) NOT NULL,
    [RET_ADJ_ID] DECIMAL(18,2),
    [RX_ID] DECIMAL(18,2),
    [CREATED_DATE] DATETIME2(6)
);

CREATE TABLE [SBMO].[INVENTORY_DATE]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [INVENTORY_LAST_UPDATED_DATE] DATETIME2(6) NOT NULL
);

CREATE TABLE [SBMO].[ITEM_LOCATION]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FORMULARY_ID] BIGINT NOT NULL,
    [QUANTITY] INT NOT NULL
);

CREATE TABLE [SBMO].[LABEL_IMAGES]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [IMAGE_DATA] VARBINARY(MAX) NOT NULL,
    [IMAGE_FORMAT] VARCHAR(255) NOT NULL,
    [IMAGE_NAME] VARCHAR(255) NOT NULL,
    [IMAGE_SOURCE] VARCHAR(255)
);

CREATE TABLE [SBMO].[LOCATION]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [LOCATION_TYPE] INT NOT NULL,
    [PARENT_ID] BIGINT,
    [USE_TYPE] INT NOT NULL,
    [DESCRIPTOR] VARCHAR(255) NOT NULL,
    [LOCATION_STATUS] INT NOT NULL
);

CREATE TABLE [SBMO].[MASTER_PRODUCT_PO_VERIFY]
(
    [TENANT_ID] DECIMAL(38,0),
    [ID] DECIMAL(38,0),
    [PURCHASE_ORDER_ID] DECIMAL(38,0) NOT NULL,
    [VENDOR_ID] DECIMAL(38,0) NOT NULL,
    [ORDER_DATE] DATETIME2(6) NOT NULL,
    [TOTAL_ITEMS] BIGINT NOT NULL,
    [PERCENT_SCANNED] BIGINT NOT NULL,
    [PERCENT_PASSED] BIGINT NOT NULL,
    [CREATED_DATE] DATETIME2(6) NOT NULL,
    [PURCHASE_ORDER_STATUS] DECIMAL(1,0)
);

CREATE TABLE [SBMO].[MEDICAL_SUPPLIES]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [RX_CORE_ID] DECIMAL(38,0) NOT NULL,
    [NAME] VARCHAR(60) NOT NULL
);

CREATE TABLE [SBMO].[MEDICAL_SUPPLIES_28MAY26]
(
    [ID] DECIMAL(38,0) NOT NULL,
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [RX_CORE_ID] DECIMAL(38,0) NOT NULL,
    [NAME] VARCHAR(60) NOT NULL ) SEGMENT CREATION IMMEDIATE
);

CREATE TABLE [SBMO].[MESSAGE_LOG]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [MESSAGE_DATE] DATETIME2(6) NOT NULL,
    [MESSAGE] VARCHAR(MAX) NOT NULL,
    [STORE_ID] BIGINT NOT NULL,
    [USER_INITS] VARCHAR(255) NOT NULL,
    [CREATED_DATE] DATETIME2(6)
);

