-- BATCH 3 TABLES
-- ------------------------------------------------------------------

CREATE TABLE [SBMO].[ADJUSTMENT_GROUP] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [APPLIED_DATE] DATETIME2 NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [INVENTORY_ID] DECIMAL(38,0) NULL,
    [WS_CLIENT_CERT_IDENTIFIER] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[CHAINS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [NHINID] DECIMAL(38,0) NULL,
    [NAME] VARCHAR(MAX) NULL,
    [CHAIN_MARK_UP_PERCENT] FLOAT NULL,
    [CHAIN_DISCOUNT_PERCENT] FLOAT NULL,
    [PARENT_ID] DECIMAL(38,0) NULL,
    [HQ_ID] VARCHAR(MAX) NULL,
    [MINIMUM_PRICE_OVERRIDE] DECIMAL(38,0) NULL,
    [LABEL_TEMPLATE] VARCHAR(MAX) NULL,
    [SHIPPING_ADD_ON_TYPE] VARCHAR(MAX) NULL,
    [SHIPPING_ADD_ON_AMOUNT] FLOAT NULL,
    [USE_ADHERIS] DECIMAL(38,0) NULL,
    [ADHERIS_URL] VARCHAR(MAX) NULL,
    [ADHERIS_TIMEOUT] DECIMAL(38,0) NULL,
    [ADHERIS_VERSION] VARCHAR(MAX) NULL,
    [DEACTIVATED_DATE] DATETIME2 NULL,
    [ADHERIS_RETRY_COUNT] DECIMAL(38,0) NULL,
    [ADHERIS_RETRY_OPTION] DECIMAL(38,0) NULL,
    [ADHERIS_THREAD_POOL_SIZE] DECIMAL(38,0) NULL,
    [ADHERIS_MAX_POOL_SIZE] DECIMAL(38,0) NULL,
    [USE_JMS] VARCHAR(MAX) NULL,
    [ENABLE_DIGITAL] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[CONTACTS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [FIRST_NAME] VARCHAR(MAX) NULL,
    [LAST_NAME] VARCHAR(MAX) NULL,
    [TITLE] VARCHAR(MAX) NULL,
    [ENTITY_ID] DECIMAL(38,0) NULL,
    [IDX] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[CUSTOM_SCHEDULED_TASK] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [TASK_TYPE] VARCHAR(MAX) NULL,
    [TASK_DAY] DECIMAL(38,0) NULL,
    [TRIGGER_TIME] VARCHAR(MAX) NULL,
    [SCHEDULE_GROUPING] DECIMAL(38,0) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[DAILY_SCHEDULED_TASKS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[DISPENSERS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [WARNING_LABEL_CODE] VARCHAR(MAX) NULL,
    [LOAD_BALANCE_FACTOR] FLOAT NULL,
    [MODULE] VARCHAR(MAX) NULL,
    [PORT] DECIMAL(38,0) NULL,
    [TIMEOUT] DECIMAL(38,0) NULL,
    [HOST] VARCHAR(MAX) NULL,
    [VERSION] VARCHAR(MAX) NULL,
    [DISABLED] DECIMAL(38,0) NULL,
    [INVENTORY_ID] DECIMAL(38,0) NULL,
    [TRANSPORT_PROPERTIES] VARCHAR(MAX) NULL,
    [USES_BATCH_IDENTIFIER] DECIMAL(38,0) NULL,
    [DESCRIPTION] VARCHAR(MAX) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL,
    [DISPENSER_CERT_SUBJECT] VARCHAR(MAX) NULL,
    [ORDER_PULL_RETRY_COUNT] DECIMAL(38,0) NULL,
    [LOG_DISPENSER_REQUEST] DECIMAL(38,0) NULL,
    [LAST_UPDATED_DATE] DATETIME2 NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(MAX) NULL,
    [MAX_RX_COUNT_FOR_GROUPING] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[MONTHLY_SCHEDULED_TASKS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [APRIL] DECIMAL(38,0) NULL,
    [AUGUST] DECIMAL(38,0) NULL,
    [DECEMBER] DECIMAL(38,0) NULL,
    [FEBRUARY] DECIMAL(38,0) NULL,
    [JANUARY] DECIMAL(38,0) NULL,
    [JULY] DECIMAL(38,0) NULL,
    [JUNE] DECIMAL(38,0) NULL,
    [MARCH] DECIMAL(38,0) NULL,
    [MAY] DECIMAL(38,0) NULL,
    [NOVEMBER] DECIMAL(38,0) NULL,
    [OCTOBER] DECIMAL(38,0) NULL,
    [SEPTEMBER] DECIMAL(38,0) NULL,
    [TYPE] DECIMAL(38,0) NULL,
    [DATE_OF_MONTH] DECIMAL(38,0) NULL,
    [DAY_OF_MONTH] DECIMAL(38,0) NULL,
    [FIRST_LAST] DECIMAL(38,0) NULL,
    [DAY_TYPE] DECIMAL(38,0) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[ONCE_SCHEDULED_TASKS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [START_DATE] DATETIME2 NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[PDX_SCHEMA_TASK_ERROR_LOG] (
    [ID] DECIMAL(38,0) NULL,
    [ERROR_MESSAGE] VARCHAR(MAX) NULL,
    [SQL_ERROR_CODE] VARCHAR(MAX) NULL,
    [SQL_ERROR_MESSAGE] VARCHAR(MAX) NULL,
    [STATEMENT_INDEX] DECIMAL(38,0) NULL,
    [SQL_TEXT] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[PURCHASE_ORDER_GROUP] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [CREATED_DATE] DATETIME2 NULL,
    [INVENTORY_ID] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[PURGE_HISTORY_CHUNKS] (
    [ID] DECIMAL(38,0) NULL,
    [ID_PURGE_HISTORY_PARTITIONS] DECIMAL(38,0) NULL,
    [TABLE_NAME] VARCHAR(MAX) NULL,
    [PART_NAME] VARCHAR(MAX) NULL,
    [TASK_NAME] VARCHAR(MAX) NULL,
    [START_TIME] DATETIME2 NULL,
    [END_TIME] DATETIME2 NULL,
    [ROW_COUNT] DECIMAL(38,0) NULL
);

CREATE TABLE [SBMO].[REPORT_REQUEST_PARAMETER] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [REPORT_REQUEST_ID] DECIMAL(38,0) NULL,
    [PARAMETER_NAME] VARCHAR(MAX) NULL,
    [PARAMETER_VALUE] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[VENDOR] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [DEACTIVATE] DATETIME2 NULL,
    [NAME] VARCHAR(MAX) NULL,
    [NHINVEN] VARCHAR(MAX) NULL,
    [NHINVENLEV] DECIMAL(38,0) NULL,
    [DEFAULT_ITEM_NUMBER_QUALIFIER] VARCHAR(MAX) NULL,
    [TRANSPORT_TYPE] DECIMAL(38,0) NULL,
    [TRANSPORT_PROPERTIES] VARCHAR(MAX) NULL,
    [BILLING_TEMPLATE_PATH] VARCHAR(MAX) NULL,
    [BILLING_TEMPLATE_PROPERTIES] VARCHAR(MAX) NULL,
    [DAY_SUPPLY_THRESHOLD] DECIMAL(38,0) NULL,
    [BILLING_TRANSPORT_TYPE] DECIMAL(38,0) NULL,
    [FORMULARY_INVENTORY_TYPE] DECIMAL(38,0) NULL,
    [BILLING_TRANSPORT_PROPERTIES] VARCHAR(MAX) NULL,
    [THREE_DIGIT_VENDOR_CODE] VARCHAR(MAX) NULL,
    [MINIMUM_PRICE_OVERRIDE] DECIMAL(38,0) NULL,
    [ALLOW_MULTIPLE_INVENTORIES] DECIMAL(38,0) NULL,
    [EXCLUDE_FROM_BILLING] DECIMAL(38,0) NULL,
    [INV_MGMT_TRANSPORT_TYPE] DECIMAL(38,0) NULL,
    [INV_MGMT_TRANSPORT_PROP] VARCHAR(MAX) NULL,
    [INV_MGMT_TEMPLATE_PATH] VARCHAR(MAX) NULL,
    [LAST_UPDATED_DATE] DATETIME2 NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(MAX) NULL,
    [DISABLE_856] VARCHAR(MAX) NULL,
    [ALLOW_CSOS] VARCHAR(MAX) NULL,
    [DESCRIPTION] VARCHAR(MAX) NULL,
    [CII_RECEIVING] VARCHAR(MAX) NULL,
    [ENABLE_BAR_CODE_SCANNING] VARCHAR(MAX) NULL,
    [BAR_CODE_TYPE] DECIMAL(38,0) NULL,
    [PERCENTAGE_TO_SCAN_PO] DECIMAL(38,0) NULL,
    [TRANSPORT_855_PROPERTIES] VARCHAR(MAX) NULL,
    [TRANSPORT_855_TYPE] DECIMAL(38,0) NULL,
    [COST_UPDATE_NHIN_VENDOR] VARCHAR(MAX) NULL
);

CREATE TABLE [SBMO].[WEEKLY_SCHEDULED_TASKS] (
    [TENANT_ID] DECIMAL(38,0) NULL,
    [ID] DECIMAL(38,0) NULL,
    [FRIDAY] DECIMAL(38,0) NULL,
    [MONDAY] DECIMAL(38,0) NULL,
    [SATURDAY] DECIMAL(38,0) NULL,
    [SUNDAY] DECIMAL(38,0) NULL,
    [THURSDAY] DECIMAL(38,0) NULL,
    [TUESDAY] DECIMAL(38,0) NULL,
    [WEDNESDAY] DECIMAL(38,0) NULL,
    [FACILITY_ID] DECIMAL(38,0) NULL
);

