-- BATCH 1 TABLES
-- --------------------------------------------------------

CREATE TABLE [SBMO].[BIN_UPC_LINK] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [BIN_BARCODE] VARCHAR(16) NOT NULL,
    [DRUG_UPC] VARCHAR(16) NOT NULL,
    [DEVICE_NUMBER] VARCHAR(16) NOT NULL,
    [DRUG_NAME] VARCHAR(28) NOT NULL,
    [NDC] VARCHAR(11) NOT NULL,
    [NDC_FMT] INT
);

CREATE TABLE [SBMO].[CARRIER] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [NAME] VARCHAR(128) NOT NULL,
    [SHIP_IDENT] VARCHAR(128) NOT NULL,
    [SHIP_PRIORITY] DECIMAL(3,0)
);

CREATE TABLE [SBMO].[FACILITIES] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [SHORT_NAME] VARCHAR(20) NOT NULL,
    [NAME] VARCHAR(60) NOT NULL,
    [ADDRESS_LINE_1] VARCHAR(30) NOT NULL,
    [ADDRESS_LINE_2] VARCHAR(30),
    [CITY] VARCHAR(35) NOT NULL,
    [STATE] VARCHAR(2) NOT NULL,
    [ZIP] VARCHAR(15) NOT NULL,
    [COUNTY] VARCHAR(15) NOT NULL,
    [DEA_NUMBER] VARCHAR(15) NOT NULL,
    [FEDERAL_TAX_IDENTIFIER] INT NOT NULL,
    [NCPDP_NUMBER] VARCHAR(15) NOT NULL,
    [NHINID] BIGINT NOT NULL,
    [DEA_EXPIRATION_DATE] DATETIME2 NOT NULL,
    [TIME_ZONE] VARCHAR(50) NOT NULL,
    [LOCAL_PHONE_NUMBER] VARCHAR(10) NOT NULL,
    [TOLL_FREE_PHONE_NUMBER] VARCHAR(10) NOT NULL,
    [ALTERNATE_PHONE_NUMBER] VARCHAR(10),
    [EXPORT_ORDER_DISPENSER_MODULE] VARCHAR(255),
    [DISPENSER_COMM_ENABLED] VARCHAR(5) NOT NULL,
    [CHECK_INV_FOR_HOME_DELIVERY] VARCHAR(5) NOT NULL,
    [DRUG_LOT_NOT_REQUIRED] VARCHAR(5),
    [ORDER_PULL_DELAY] DECIMAL(8,0) NOT NULL,
    [ENABLE_ITEM_LOCATIONS] VARCHAR(5) NOT NULL,
    [RED_HOURS] DECIMAL(2,0) NOT NULL,
    [YELLOW_HOURS] DECIMAL(2,0) NOT NULL,
    [ACTIVE_DIRECTORY_GROUP] VARCHAR(255) NOT NULL,
    [PAUSE_ORDER_PROCESSING_DATE] DATETIME2,
    [DOC_ERROR_RESET_DATE] DATETIME2,
    [DOC_CON_ERROR_RESET_DATE] DATETIME2,
    [DISPLAY_TX_COST_ERROR] VARCHAR(1) NOT NULL,
    [LANDING_PAGE] DECIMAL(1,0) NOT NULL,
    [STATUS_ALERT_THRESHOLD] DECIMAL(38,0),
    [PROMISED_DATE_ALERT_THRESHOLD] INT,
    [ORDER_PULL_JOB_FREQUENCY] BIGINT,
    [CHECK_INV_FOR_SPECIALTY] DECIMAL(2,0) NOT NULL,
    [TRANSITION_POLLTIME] DECIMAL(8,0) NOT NULL,
    [TRANSITION_ALERT_THRESHOLD] DECIMAL(8,0) NOT NULL,
    [TRANSITION_AUTO_TASK_DISABLED] VARCHAR(1) NOT NULL,
    [TRANSITION_ALERT_EMAIL] VARCHAR(120) NOT NULL,
    [PROMISE_DATE_ENABLED] VARCHAR(1) NOT NULL,
    [PROMISE_DATE_SUN] DECIMAL(2,0),
    [PROMISE_DATE_MON] DECIMAL(2,0),
    [PROMISE_DATE_TUE] DECIMAL(2,0),
    [PROMISE_DATE_WED] DECIMAL(2,0),
    [PROMISE_DATE_THU] DECIMAL(2,0),
    [PROMISE_DATE_FRI] DECIMAL(2,0),
    [PROMISE_DATE_SAT] DECIMAL(2,0),
    [AUTO_CANCEL_TO_STORE] VARCHAR(1),
    [QUEUE_MAX_DAYS_BACK] DECIMAL(5,0) NOT NULL,
    [CHECK_INV_FOR_STORE_DELIVERY] DECIMAL(1,0) NOT NULL,
    [MAINTAIN_INVENTORY_QUANTITIES] VARCHAR(1) NOT NULL,
    [PO_EMAIL] VARCHAR(255),
    [ORDER_PULL_THREAD_CNT] DECIMAL(2,0) NOT NULL,
    [ORDER_PULL_MAX_CNT] DECIMAL(4,0) NOT NULL,
    [ENABLE_HOLD_SPECIALTY_ORDERS] VARCHAR(5) NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2 NOT NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(255) NOT NULL,
    [ENABLE_ORDER_CANCEL_REASON] VARCHAR(1) NOT NULL,
    [DASHBOARD_JOB_ENABLED] VARCHAR(5) NOT NULL,
    [STATUS_UPDATE_MAX_DAYS_BACK] DECIMAL(3,0) NOT NULL,
    [IGNORE_PROM_DATE_HOME_DELIVERY] VARCHAR(1) NOT NULL,
    [IGNORE_PROM_DATE_SPECIALTY] VARCHAR(1) NOT NULL,
    [CHECK_INV_FOR_UNIT_DOSE] DECIMAL(1,0),
    [START_OF_DAY_TIME] DATETIME2,
    [ADHERIS_DOCUMENT_SIZE] VARCHAR(9),
    [ALLOW_SINGLE_RX_CANCELLATION] VARCHAR(1),
    [SEND_ALT_NHIN_DRUG_NAME] VARCHAR(1)
);

CREATE TABLE [SBMO].[FORMULARY_REORDER] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ORDER_POINT] FLOAT NOT NULL,
    [ORDER_QTY] FLOAT NOT NULL,
    [MINIMUM_QTY] FLOAT NOT NULL,
    [LAST_ORDER_DATE] DATETIME2,
    [HOLD_UNTIL_DATE] DATETIME2
);

CREATE TABLE [SBMO].[INVENTORY_DATE] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [INVENTORY_LAST_UPDATED_DATE] DATETIME2 NOT NULL
);

CREATE TABLE [SBMO].[LABEL_IMAGES] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [IMAGE_DATA] BLOB NOT NULL,
    [IMAGE_FORMAT] VARCHAR2(255 NOT NULL,
    [IMAGE_NAME] VARCHAR2(255 NOT NULL,
    [IMAGE_SOURCE] VARCHAR2(255
);

CREATE TABLE [SBMO].[LOCATION] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [LOCATION_TYPE] INT NOT NULL,
    [PARENT_ID] BIGINT,
    [USE_TYPE] INT NOT NULL,
    [DESCRIPTOR] VARCHAR2(255 NOT NULL,
    [LOCATION_STATUS] INT NOT NULL
);

CREATE TABLE [SBMO].[PHONE_ADDRESS_OWNERS] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[REGION] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [NAME] VARCHAR2(255 NOT NULL,
    [SUN_START_TIME] DATETIME2,
    [SUN_STOP_TIME] DATETIME2,
    [MON_START_TIME] DATETIME2,
    [MON_STOP_TIME] DATETIME2,
    [TUE_START_TIME] DATETIME2,
    [TUE_STOP_TIME] DATETIME2,
    [WED_START_TIME] DATETIME2,
    [WED_STOP_TIME] DATETIME2,
    [THU_START_TIME] DATETIME2,
    [THU_STOP_TIME] DATETIME2,
    [FRI_START_TIME] DATETIME2,
    [FRI_STOP_TIME] DATETIME2,
    [SAT_START_TIME] DATETIME2,
    [SAT_STOP_TIME] DATETIME2
);

CREATE TABLE [SBMO].[RX_PATSTORES] (
    [TENANT_ID] DECIMAL(38,0) NOT NULL,
    [ID] DECIMAL(38,0) NOT NULL,
    [PARTITION_STAMP] DATETIME2 NOT NULL,
    [FIRST_NAME] VARCHAR(20) NOT NULL,
    [LAST_NAME] VARCHAR(25) NOT NULL,
    [MIDDLE_NAME] VARCHAR(20),
    [PATIENT_ID] VARCHAR(8) NOT NULL,
    [STORE_RPH_INITS] VARCHAR(3) NOT NULL,
    [STORE_RPH_NAME] VARCHAR(65) NOT NULL,
    [STORE_USER_INITS] VARCHAR(3) NOT NULL,
    [STORE_USER_ID] VARCHAR(38) NOT NULL,
    [STORE_TECH_INITS] VARCHAR(3),
    [STORE_RPH_LICENSE_NUM] VARCHAR(20) NOT NULL,
    [ADDRESS] VARCHAR(30) NOT NULL,
    [ADDRESS2] VARCHAR(30),
    [CITY] VARCHAR(35) NOT NULL,
    [STATE] VARCHAR(2) NOT NULL,
    [ZIP] VARCHAR(15) NOT NULL,
    [BIRTH_DATE] DATETIME2 NOT NULL,
    [PHONE] VARCHAR(10),
    [PATIENT_RXCOM_ID] VARCHAR(255),
    [STORE_RPH_ID] VARCHAR(38),
    [STORE_TECH_ID] VARCHAR(38),
    [CARDHOLDERID] VARCHAR(20),
    [DRUG_UPC] VARCHAR(25),
    [PATIENT_DL_NUM] VARCHAR(15),
    [STORE_PATIENT_CODE] VARCHAR(10),
    [MEDICAL_RECORD_NUMBER] VARCHAR(35),
    [LANGUAGE] VARCHAR(2),
    [GENDER] VARCHAR(1),
    [PATIENT_EMAIL_ADDRESS] VARCHAR(120),
    [LOYALTY_CARD_NUMBER] VARCHAR(50),
    [IS_NEW_PATIENT] DECIMAL(38,0),
    [PATIENT_RECORD_TYPE] VARCHAR(1),
    [ANIMAL_TYPE] VARCHAR(15),
    [CARRIER_CODE] VARCHAR(10),
    [PLAN_CODE] VARCHAR(15),
    [PLAN_NAME] VARCHAR(28),
    [BIN] VARCHAR(10),
    [PCN] VARCHAR(10),
    [CREATED_DATE] DATETIME2,
    [RESPONSIBLE_PARTY_LAST_NAME] VARCHAR(25),
    [RESPONSIBLE_PARTY_FIRST_NAME] VARCHAR(20),
    [VISUALLY_IMPAIRED] VARCHAR(1),
    [PATIENT_DIGITAL_DOC_STATUS] VARCHAR(1)
);

CREATE TABLE [SBMO].[RX_PRINT_INFO] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [PARTITION_STAMP] DATETIME2 NOT NULL,
    [LABEL] CLOB NOT NULL,
    [PATIENT_ED] CLOB,
    [CREATED_DATE] DATETIME2,
    [FREE_FORM_REPORT_FORMAT] VARCHAR(10),
    [FREE_FORM_REPORT_MESSAGE] CLOB,
    [FREE_FORM_LABEL_FORMAT] VARCHAR(10),
    [FREE_FORM_LABEL_MESSAGE] CLOB
);

CREATE TABLE [SBMO].[SHIPMENT] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [PARTITION_STAMP] DATETIME2 NOT NULL,
    [SIGNATURE] CLOB NOT NULL,
    [RECEIVED_DATE] DATETIME2 NOT NULL,
    [PRINTED_NAME] VARCHAR2(255 NOT NULL,
    [RECEIVE_USERID] VARCHAR(64) NOT NULL
);

CREATE TABLE [SBMO].[VENDOR_PROP] (
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [OWNED_ACCOUNT_NUMBER] VARCHAR2(64,
    [AUTHORIZATION_INFORMATION] VARCHAR2(64,
    [SECURITY_INFORMATION] VARCHAR2(64,
    [INTERCHANGE_SENDER_ID_QLF] VARCHAR2(64 NOT NULL,
    [INTERCHANGE_SENDER_ID] VARCHAR2(64,
    [ICHANGE_RECEIVER_ID_QLF] VARCHAR2(64 NOT NULL,
    [INTERCHANGE_RECEIVER_ID] VARCHAR2(64 NOT NULL,
    [ICHANGE_CONTROL_STANDARDS_ID] VARCHAR2(64 NOT NULL,
    [ICHANGE_CTRL_VERSION_NUM] VARCHAR2(64 NOT NULL,
    [ACK_REQUESTED] VARCHAR2(64 NOT NULL,
    [USAGE_INDICATOR] VARCHAR2(64 NOT NULL,
    [COMPONENT_ELEMENT_SEPARATOR] VARCHAR2(64 NOT NULL,
    [SEGMENT_TERMINATOR] VARCHAR2(64 NOT NULL,
    [DATA_ELEMENT_SEPARATOR] VARCHAR2(64 NOT NULL,
    [FUNCTIONAL_IDENTIFIER_CODE] VARCHAR2(64 NOT NULL,
    [APPLICATION_SENDERS_CODE] VARCHAR2(64,
    [APP_RECEIVERS_CODE] VARCHAR2(64 NOT NULL,
    [RESPONSIBLE_AGENCY_CODE] VARCHAR2(64 NOT NULL,
    [EDI_VERSION_SUPPORTED] VARCHAR2(64 NOT NULL,
    [EDI_VERSION_TEXT] VARCHAR2(64,
    [PURCHASE_ORDER_TYPE_CODE] VARCHAR2(64 NOT NULL,
    [IDENTIFICATION_CODE_QLF] VARCHAR2(64 NOT NULL,
    [IDENTIFICATION_CODE] VARCHAR2(64,
    [OWNED_IDENTIFICATION_CODE] VARCHAR2(64,
    [CONSIGNED_ACCOUNT_NUMBER] VARCHAR2(64,
    [URL_STRING] VARCHAR2(512,
    [OWNED_APPLICATION_SENDERS_CODE] VARCHAR2(64,
    [OWNED_INTERCHANGE_SENDER_ID] VARCHAR2(64,
    [LAST_UPDATED_DATE] DATETIME2 NOT NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(255) NOT NULL
);
