-- BATCH 5 TABLES
-- Schema: SBMO
-- Count: 20

CREATE TABLE [SBMO].[PURGE_RUN_CHECK]
(
    [ACTIVITY_DATE] DATETIME2(6) NOT NULL,
    [PURGE_RUNNING] CHAR(1) NOT NULL
);

CREATE TABLE [SBMO].[PURGE_TABLES]
(
    [TABLE_NAME] VARCHAR(30) NOT NULL,
    [PURGE_POSITION] DECIMAL(18,2) NOT NULL,
    [PURGE_COLUMN] VARCHAR(30) NOT NULL,
    [PARALLEL_COUNT] DECIMAL(18,2)
);

CREATE TABLE [SBMO].[QRTZ_BLOB_TRIGGERS]
(
    [TRIGGER_NAME] VARCHAR(200) NOT NULL,
    [TRIGGER_GROUP] VARCHAR(200) NOT NULL,
    [BLOB_DATA] VARBINARY(MAX),
    [SCHED_NAME] VARCHAR(120) DEFAULT 'TestScheduler' NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_CALENDARS]
(
    [CALENDAR_NAME] VARCHAR(200) NOT NULL,
    [CALENDAR] VARBINARY(MAX) NOT NULL,
    [SCHED_NAME] VARCHAR(120) DEFAULT 'TestScheduler' NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_CRON_TRIGGERS]
(
    [TRIGGER_NAME] VARCHAR(200) NOT NULL,
    [TRIGGER_GROUP] VARCHAR(200) NOT NULL,
    [CRON_EXPRESSION] VARCHAR(120) NOT NULL,
    [TIME_ZONE_ID] VARCHAR(80),
    [SCHED_NAME] VARCHAR(120) DEFAULT 'TestScheduler' NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_FIRED_TRIGGERS]
(
    [ENTRY_ID] VARCHAR(95) NOT NULL,
    [TRIGGER_NAME] VARCHAR(200) NOT NULL,
    [TRIGGER_GROUP] VARCHAR(200) NOT NULL,
    [INSTANCE_NAME] VARCHAR(200) NOT NULL,
    [FIRED_TIME] DECIMAL(13,0) NOT NULL,
    [STATE] VARCHAR(16) NOT NULL,
    [JOB_NAME] VARCHAR(200),
    [JOB_GROUP] VARCHAR(200),
    [REQUESTS_RECOVERY] VARCHAR(1),
    [PRIORITY] DECIMAL(13,0),
    [IS_NONCONCURRENT] VARCHAR(11),
    [IS_UPDATE_DATA] VARCHAR(11),
    [SCHED_NAME] VARCHAR(120) DEFAULT 'TestScheduler' NOT NULL,
    [SCHED_TIME] DECIMAL(13,0)
);

CREATE TABLE [SBMO].[QRTZ_JOB_DETAILS]
(
    [JOB_NAME] VARCHAR(200) NOT NULL,
    [JOB_GROUP] VARCHAR(200) NOT NULL,
    [DESCRIPTION] VARCHAR(250),
    [JOB_CLASS_NAME] VARCHAR(250) NOT NULL,
    [IS_DURABLE] VARCHAR(1) NOT NULL,
    [REQUESTS_RECOVERY] VARCHAR(1) NOT NULL,
    [JOB_DATA] VARBINARY(MAX),
    [IS_NONCONCURRENT] VARCHAR(11),
    [IS_UPDATE_DATA] VARCHAR(11),
    [SCHED_NAME] VARCHAR(120) DEFAULT 'TestScheduler' NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_LOCKS]
(
    [LOCK_NAME] VARCHAR(40) NOT NULL,
    [SCHED_NAME] VARCHAR(120) DEFAULT 'TestScheduler' NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_PAUSED_TRIGGER_GRPS]
(
    [TRIGGER_GROUP] VARCHAR(80) NOT NULL,
    [SCHED_NAME] VARCHAR(120) DEFAULT 'TestScheduler' NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_SCHEDULER_STATE]
(
    [INSTANCE_NAME] VARCHAR(200) NOT NULL,
    [LAST_CHECKIN_TIME] DECIMAL(13,0) NOT NULL,
    [CHECKIN_INTERVAL] DECIMAL(13,0) NOT NULL,
    [SCHED_NAME] VARCHAR(120) DEFAULT 'TestScheduler' NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_SIMPLE_TRIGGERS]
(
    [TRIGGER_NAME] VARCHAR(200) NOT NULL,
    [TRIGGER_GROUP] VARCHAR(200) NOT NULL,
    [REPEAT_COUNT] DECIMAL(7,0) NOT NULL,
    [REPEAT_INTERVAL] DECIMAL(12,0) NOT NULL,
    [TIMES_TRIGGERED] DECIMAL(7,0) NOT NULL,
    [SCHED_NAME] VARCHAR(120) DEFAULT 'TestScheduler' NOT NULL
);

CREATE TABLE [SBMO].[QRTZ_SIMPROP_TRIGGERS]
(
    [SCHED_NAME] VARCHAR(120) NOT NULL,
    [TRIGGER_NAME] VARCHAR(200) NOT NULL,
    [TRIGGER_GROUP] VARCHAR(200) NOT NULL,
    [STR_PROP_1] VARCHAR(512),
    [STR_PROP_2] VARCHAR(512),
    [STR_PROP_3] VARCHAR(512),
    [INT_PROP_1] DECIMAL(18,2),
    [INT_PROP_2] DECIMAL(18,2),
    [LONG_PROP_1] DECIMAL(18,2),
    [LONG_PROP_2] DECIMAL(18,2),
    [DEC_PROP_1] DECIMAL(13,4),
    [DEC_PROP_2] DECIMAL(13,4),
    [BOOL_PROP_1] VARCHAR(1),
    [BOOL_PROP_2] VARCHAR(1)
);

CREATE TABLE [SBMO].[QRTZ_TRIGGERS]
(
    [TRIGGER_NAME] VARCHAR(200) NOT NULL,
    [TRIGGER_GROUP] VARCHAR(200) NOT NULL,
    [JOB_NAME] VARCHAR(200) NOT NULL,
    [JOB_GROUP] VARCHAR(200) NOT NULL,
    [DESCRIPTION] VARCHAR(250),
    [PREV_FIRE_TIME] DECIMAL(13,0),
    [TRIGGER_STATE] VARCHAR(16) NOT NULL,
    [TRIGGER_TYPE] VARCHAR(8) NOT NULL,
    [START_TIME] DECIMAL(13,0) NOT NULL,
    [END_TIME] DECIMAL(13,0),
    [CALENDAR_NAME] VARCHAR(200),
    [MISFIRE_INSTR] DECIMAL(2,0),
    [PRIORITY] DECIMAL(13,0),
    [JOB_DATA] VARBINARY(MAX),
    [SCHED_NAME] VARCHAR(120) DEFAULT 'TestScheduler' NOT NULL
);

CREATE TABLE [SBMO].[REGION]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [NAME] VARCHAR(255) NOT NULL,
    [SUN_START_TIME] DATETIME2(6),
    [SUN_STOP_TIME] DATETIME2(6),
    [MON_START_TIME] DATETIME2(6),
    [MON_STOP_TIME] DATETIME2(6),
    [TUE_START_TIME] DATETIME2(6),
    [TUE_STOP_TIME] DATETIME2(6),
    [WED_START_TIME] DATETIME2(6),
    [WED_STOP_TIME] DATETIME2(6),
    [THU_START_TIME] DATETIME2(6),
    [THU_STOP_TIME] DATETIME2(6),
    [FRI_START_TIME] DATETIME2(6),
    [FRI_STOP_TIME] DATETIME2(6),
    [SAT_START_TIME] DATETIME2(6),
    [SAT_STOP_TIME] DATETIME2(6)
);

CREATE TABLE [SBMO].[REPORT_REQUEST]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [REPORT_NAME] VARCHAR(50) NOT NULL,
    [USER_ID] VARCHAR(255) NOT NULL,
    [FORMAT] VARCHAR(32) NOT NULL,
    [SUBMISSION_DATE] DATETIME2(6) NOT NULL,
    [START_DATE] DATETIME2(6),
    [COMPLETION_DATE] DATETIME2(6),
    [STATUS] VARCHAR(12) NOT NULL,
    [DOWNLOAD_LINK] VARCHAR(256),
    [HASH] DECIMAL(16,0) NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);

CREATE TABLE [SBMO].[REPORT_REQUEST_PARAMETER]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [REPORT_REQUEST_ID] BIGINT NOT NULL,
    [PARAMETER_NAME] VARCHAR(60) NOT NULL,
    [PARAMETER_VALUE] VARCHAR(1020) NOT NULL
);

CREATE TABLE [SBMO].[RETAIL_COST]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [MAIL_ACQ_LAST_UPDATED] DATETIME2(6) NOT NULL,
    [MAIL_ACQ] FLOAT(126),
    [STORE_ACQ_LAST_UPDATED] DATETIME2(6) NOT NULL,
    [STORE_ACQ] FLOAT(126),
    [VENDOR_ID] BIGINT NOT NULL,
    [CHAIN_ID] BIGINT NOT NULL,
    [DRUG_ID] BIGINT NOT NULL,
    [LAST_UPDATED_DATE] DATETIME2(6) NOT NULL,
    [LAST_UPDATED_USER_ID] VARCHAR(255) NOT NULL
);

CREATE TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [FORMULARY_ID] DECIMAL(18,2) NOT NULL,
    [VENDOR_ID] DECIMAL(18,2) NOT NULL,
    [ITEM_DESCRIPTION] VARCHAR(255) NOT NULL,
    [ADJUSTMENT_CODE_ID] DECIMAL(18,2) NOT NULL,
    [ADDED_BY_INVENTORY_COUNT] VARCHAR(255),
    [INVENTORY_AMOUNT] FLOAT(126) NOT NULL,
    [APPLIED_DATE] DATETIME2(6),
    [CREATED_DATE] DATETIME2(6) NOT NULL,
    [ADDED_BY_USER] VARCHAR(255) NOT NULL,
    [DESCRIPTION] VARCHAR(255),
    [ITEM_NUMBER] VARCHAR(255) NOT NULL,
    [ADJUSTMENT_GROUP_ID] DECIMAL(18,2) NOT NULL,
    [ITEM_LOCATION_ID] DECIMAL(18,2),
    [APPLY_ONLY_TO_ITEM_LOCATION] DECIMAL(18,2)
);

CREATE TABLE [SBMO].[RX_CORES]
(
    [TENANT_ID] DECIMAL(18,2) NOT NULL,
    [ID] DECIMAL(18,2) NOT NULL,
    [PARTITION_STAMP] DATETIME2 DEFAULT sysdate NOT NULL,
    [DISPENSED_QTY] DECIMAL(18,2),
    [DAYS_SUPPLY] DECIMAL(18,2) NOT NULL,
    [PRIORITY] DECIMAL(18,2),
    [RXNUM] VARCHAR(16) NOT NULL,
    [STORE_CF_QUEUE_NUM] VARCHAR(255) NOT NULL,
    [CF_QUEUE_NUM] DECIMAL(18,2) NOT NULL,
    [TXNUM] VARCHAR(12) NOT NULL,
    [ORDER_ID] DECIMAL(18,2) NOT NULL,
    [SHIPPING_PACKAGE_ID] DECIMAL(18,2),
    [FILLED_VENDOR_ID] DECIMAL(18,2),
    [DISPENSED_NDC] VARCHAR(11),
    [REQUEST_NDC] VARCHAR(11) NOT NULL,
    [ADDED_DATE] DATETIME2(6) NOT NULL,
    [CANCELLED_DATE] DATETIME2(6),
    [LAST_UPDATE_DATE] DATETIME2(6) NOT NULL,
    [STATUS] DECIMAL(18,2) NOT NULL,
    [REQUEST_QTY] DECIMAL(18,2) NOT NULL,
    [REQUEST_DECIMAL_QTY] FLOAT(126),
    [STORE_NHINID] DECIMAL(18,2) NOT NULL,
    [ERROR_TEXT] VARCHAR(255),
    [FILL_OPERATOR_ID] VARCHAR(38),
    [POS_BARCODE_ID] VARCHAR(30),
    [AUTO_DISPENSED] DECIMAL(18,2),
    [CANCEL_ID] VARCHAR(38),
    [MISSING_ID] VARCHAR(38),
    [DISPENSED_DATE] DATETIME2(6),
    [FOUND_ID] VARCHAR(38),
    [COMPLETED_DATE] DATETIME2(6),
    [STATUS_LAST_UPDATE_DATE] DATETIME2(6) NOT NULL,
    [HOLD_RX_AT_SBMO] DECIMAL(18,2) NOT NULL,
    [STORE_REQUESTED_CANCEL] VARCHAR(5) NOT NULL,
    [DOCUMENT_QUEUE_COMPLETE] DECIMAL(18,2),
    [EXPEDITE] DECIMAL(18,2),
    [CREATED_DATE] DATETIME2(6),
    [SPECIALTY] VARCHAR(1),
    [DISPENSED_DECIMAL_QTY] FLOAT(126),
    [HOLD_RX_DUE_INV] VARCHAR(1),
    [PRESCRIBED_QTY] FLOAT(126),
    [QTY_LEFT] FLOAT(126),
    [FILLING_STATION_ID] BIGINT,
    [ORDER_PULL_RETRY_COUNT] DECIMAL(2,0),
    [ACCEPTED_DATE] DATETIME2(6),
    [ADHERIS_RETRY_COUNT] DECIMAL(2,0) NOT NULL
);

CREATE TABLE [SBMO].[RX_CORES_MIN_DATE]
(
    [TENANT_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [STATUS] INT NOT NULL,
    [MIN_DATE] DATETIME2(6) NOT NULL,
    [DATE_TYPE] INT NOT NULL,
    [FACILITY_ID] BIGINT NOT NULL
);

