-- ARS.RXCOM_CERTIFICATES definition
-- Converted from Oracle to Azure SQL Server
-- Generated conversion from DBeaver DDL

-- Drop table
-- DROP TABLE ARS.RXCOM_CERTIFICATES;

CREATE TABLE ARS.RXCOM_CERTIFICATES (
	ID BIGINT NOT NULL,
	CERTIFICATE NVARCHAR(MAX) NOT NULL,
	PASS_PHRASE NVARCHAR(MAX),
	PRIVATE_KEY NVARCHAR(MAX),
	REVOCATION_DATE DATETIME2(6),
	SERIAL_NUMBER DECIMAL(19,2) NOT NULL,
	VALID_FROM DATETIME2(6) NOT NULL,
	VALID_TO DATETIME2(6) NOT NULL,
	SHA1_THUMBPRINT VARCHAR(40),
	STORE_ID BIGINT,
	CERT_TYPE VARCHAR(1),
	CONSTRAINT RXCOM_CERTIFICATES_PK PRIMARY KEY (ID),
	CONSTRAINT RXCOM_CERTIFICATES_UK1 UNIQUE (SHA1_THUMBPRINT)
);

-- Create indexes
CREATE UNIQUE NONCLUSTERED INDEX RXCOM_CERTIFICATES_PK ON ARS.RXCOM_CERTIFICATES (ID);
CREATE NONCLUSTERED INDEX RXCOM_CERTIFICATES_IX1 ON ARS.RXCOM_CERTIFICATES (STORE_ID);
CREATE UNIQUE NONCLUSTERED INDEX RXCOM_CERTIFICATES_UK1 ON ARS.RXCOM_CERTIFICATES (SHA1_THUMBPRINT);

-- ARS.RXCOM_CERTIFICATES foreign keys
ALTER TABLE ARS.RXCOM_CERTIFICATES ADD CONSTRAINT RXCOM_CERTIFICATES_FK1 FOREIGN KEY (STORE_ID) REFERENCES ARS.STORES(ID);

