-- ============================================================================
-- BATCH_CREATE_TABLES_BATCH8.sql
-- Purpose: Create 12 tables (Batch 8)
-- Tables: PATIENT_PROGRAM_AUDIT_CSD_23800, PATIENT_PROGRAM_CONTACT, 
--         PATIENT_PROGRAM_CONTACT_AUDIT, PATIENT_PROGRAM_CONTACT_AUDIT_CSD_23800,
--         PATIENT_RING_DBU_WK, PATIENT_SIGNATURES, PATIENT_SIGNATURES_AUDIT,
--         PATIENT_UNMERGE_LOCK, PAYMENT, PAYMENT_AUDIT, PA_NUM, PA_NUM_AUDIT
-- ============================================================================

-- EXTERNAL FK DEPENDENCIES:
--   - PATIENT_PROGRAM_AUDIT_CSD_23800: 2 FKs removed (ID_PATIENT→PATIENT, NHIN_ID→EPS_SEC_CHAIN)
--   - PATIENT_PROGRAM_CONTACT: 1 FK removed (PATIENT_PROGRAM_ID→PATIENT_PROGRAM)
--   - PATIENT_PROGRAM_CONTACT_AUDIT: 1 FK removed (PATIENT_PROGRAM_ID→PATIENT_PROGRAM)
--   - PATIENT_PROGRAM_CONTACT_AUDIT_CSD_23800: 1 FK removed (PATIENT_PROGRAM_ID→PATIENT_PROGRAM)
--   - PATIENT_SIGNATURES: 2 FKs removed (ID_PATIENT→PATIENT, NHIN_ID→EPS_SEC_CHAIN)
--   - PATIENT_SIGNATURES_AUDIT: 2 FKs removed (ID_PATIENT→PATIENT, NHIN_ID→EPS_SEC_CHAIN)
--   - PATIENT_UNMERGE_LOCK: 3 FKs removed (ID_PATIENT→PATIENT, CHAIN_ID→EPS_SEC_CHAIN, CHAIN_ID,NHIN_ID→EPS_SEC_STORE)
--   - PA_NUM: 3 FKs removed (CHAIN_ID→EPS_SEC_CHAIN, CHAIN_ID,NHIN_ID→EPS_SEC_STORE, CHAIN_ID,ID_TX_TP→TX_TP)
--   - PA_NUM_AUDIT: Same 3 FKs as PA_NUM
--   See REMOVED_FK_RESTORATION_SCRIPTS.sql Section 4 for post-prerequisite restoration

-- PROACTIVE DATA TYPE FIXES APPLIED:
--   - NUMBER → BIGINT (for all ID, ID_PATIENT, NHIN_ID, PATIENT_PROGRAM_ID columns)
--   - NUMBER(38,0) → BIGINT (E001 prevention: ID consistency)
--   - All DATETIME2 scales verified (all TIMESTAMP(6) → DATETIME2(6))
--   - All PK columns verified NOT NULL (E006 prevention)
--   - All CHAIN_ID in PKs set to NOT NULL (E006 prevention)

-- INTERNAL FK DEPENDENCY ORDERING:
--   - PATIENT_PROGRAM_CONTACT depends on PATIENT_PROGRAM (same batch)
--   - Created PATIENT_PROGRAM (Batch 7) first, then PATIENT_PROGRAM_CONTACT

-- ============================================================================

CREATE TABLE [EPS].[PATIENT_PROGRAM_AUDIT_CSD_23800] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [NHIN_ID] BIGINT NOT NULL,
    [ECC_PROGRAM_IDENTIFIER] BIGINT NOT NULL,
    [PROGRAM_ADDED_DATE] DATETIME2(6) NOT NULL,
    [OPT_OUT] VARCHAR(1) NULL,
    [DELETED] VARCHAR(1) NULL,
    [DEACTIVATED_DATE] DATETIME2(6) NULL,
    [LAST_UPDATED] DATETIME2(6) NOT NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NULL
);

CREATE TABLE [EPS].[PATIENT_PROGRAM_CONTACT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [PATIENT_PROGRAM_ID] BIGINT NOT NULL,
    [SEQUENCE_NUMBER] NUMERIC(2, 0) NOT NULL,
    [CONTACT_PREF] VARCHAR(2) NOT NULL,
    [ID_AAL] BIGINT NULL,
    CONSTRAINT [PATIENT_PROGRAM_CONTACT_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [PATIENT_PROGRAM_ID], [SEQUENCE_NUMBER])
);

CREATE TABLE [EPS].[PATIENT_PROGRAM_CONTACT_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [PATIENT_PROGRAM_ID] BIGINT NOT NULL,
    [SEQUENCE_NUMBER] NUMERIC(2, 0) NOT NULL,
    [CONTACT_PREF] VARCHAR(2) NOT NULL,
    [ID_AAL] BIGINT NULL,
    [DML_TYPE] VARCHAR(1) NOT NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL
);

CREATE TABLE [EPS].[PATIENT_PROGRAM_CONTACT_AUDIT_CSD_23800] (
    [CHAIN_ID] BIGINT NOT NULL,
    [PATIENT_PROGRAM_ID] BIGINT NOT NULL,
    [SEQUENCE_NUMBER] NUMERIC(2, 0) NOT NULL,
    [CONTACT_PREF] VARCHAR(2) NOT NULL,
    [ID_AAL] BIGINT NULL,
    [DML_TYPE] VARCHAR(1) NOT NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NULL
);

CREATE TABLE [EPS].[PATIENT_RING_DBU_WK] (
    [CHAIN_ID] BIGINT NOT NULL,
    [NHIN_ID] BIGINT NOT NULL,
    [PROCESSED_DATE] DATETIME2(6) NULL,
    CONSTRAINT [PATIENT_RING_DBU_WK_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [NHIN_ID])
);

CREATE TABLE [EPS].[PATIENT_SIGNATURES] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [ID_AAL] BIGINT NOT NULL,
    [LAST_UPDATED] DATETIME2(6) NOT NULL,
    [NHIN_ID] BIGINT NOT NULL,
    [DOC_SPEED_CODE] VARCHAR(24) NOT NULL,
    [DOC_NAME] VARCHAR(50) NOT NULL,
    [DOC_VERSION] NUMERIC(10, 0) NOT NULL,
    [DOC_STATE] VARCHAR(2) NOT NULL,
    [DOC_LANG] VARCHAR(2) NULL,
    [IMMUTABLE] VARCHAR(1) NULL,
    [DELETED] VARCHAR(1) NULL,
    [STATUS] VARCHAR(1) NULL,
    [STATUS_UPDATE_DATE] DATETIME2(6) NULL,
    [SIGNATURE_HASH] VARCHAR(256) NULL,
    [SIGNATURE_CAPTURE_MODE] NUMERIC(1, 0) NULL,
    [ACQUIRED_BY_USER] VARCHAR(255) NULL,
    [ACQUIRED_AT_STORE_NHIN_ID] BIGINT NULL,
    [ACQUIRED_DATE] DATETIME2(6) NULL,
    [REVOKED_BY_USER] VARCHAR(255) NULL,
    [REVOKED_AT_STORE_NHIN_ID] BIGINT NULL,
    [REVOKED_DATE] DATETIME2(6) NULL,
    [REFUSED_DATE] DATETIME2(6) NULL,
    [EXPIRY_DATE] DATETIME2(6) NULL,
    CONSTRAINT [PATIENT_SIGNATURES_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[PATIENT_SIGNATURES_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [ID_AAL] BIGINT NOT NULL,
    [LAST_UPDATED] DATETIME2(6) NOT NULL,
    [NHIN_ID] BIGINT NOT NULL,
    [DOC_SPEED_CODE] VARCHAR(24) NOT NULL,
    [DOC_NAME] VARCHAR(50) NOT NULL,
    [DOC_VERSION] NUMERIC(10, 0) NOT NULL,
    [DOC_STATE] VARCHAR(2) NOT NULL,
    [DOC_LANG] VARCHAR(2) NULL,
    [IMMUTABLE] VARCHAR(1) NULL,
    [DELETED] VARCHAR(1) NULL,
    [STATUS] VARCHAR(1) NULL,
    [STATUS_UPDATE_DATE] DATETIME2(6) NULL,
    [SIGNATURE_HASH] VARCHAR(256) NULL,
    [SIGNATURE_CAPTURE_MODE] NUMERIC(1, 0) NULL,
    [ACQUIRED_BY_USER] VARCHAR(255) NULL,
    [ACQUIRED_AT_STORE_NHIN_ID] BIGINT NULL,
    [ACQUIRED_DATE] DATETIME2(6) NULL,
    [REVOKED_BY_USER] VARCHAR(255) NULL,
    [REVOKED_AT_STORE_NHIN_ID] BIGINT NULL,
    [REVOKED_DATE] DATETIME2(6) NULL,
    [REFUSED_DATE] DATETIME2(6) NULL,
    [EXPIRY_DATE] DATETIME2(6) NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL
);

CREATE TABLE [EPS].[PATIENT_UNMERGE_LOCK] (
    [CHAIN_ID] BIGINT NOT NULL,
    [NHIN_ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [LAST_UPDATED] DATE NULL,
    [ID_AAL] BIGINT NOT NULL
);

CREATE TABLE [EPS].[PAYMENT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [NHIN_ID] BIGINT NOT NULL,
    [PAYMENT_ID] BIGINT NOT NULL,
    [ID_AAL] BIGINT NULL,
    [PAYMENT_AMOUNT] NUMERIC(13, 2) NULL,
    [PAYMENT_TYPE] VARCHAR(100) NULL,
    [AUTHORIZED_AMOUNT] NUMERIC(13, 2) NULL,
    [PRE_AUTH_DATE] DATE NULL,
    [SETTLE_DATE] DATE NULL,
    [CHECK_NUMBER] VARCHAR(20) NULL,
    [CARD_TYPE] BIGINT NULL,
    [CARD_EXPIRES] VARCHAR(4) NULL,
    [RESPONSE_CODE] VARCHAR(2) NULL,
    [RESPONSE_MESSAGE] VARCHAR(255) NULL,
    [SETTLE_RESPONSE_CODE] VARCHAR(2) NULL,
    [SETTLE_RESPONSE_MESSAGE] VARCHAR(255) NULL,
    [SETTLE_REQUEST_TO_POS_DATE] DATE NULL,
    [MAX_AMOUNT] NUMERIC(13, 2) NULL,
    [CANCEL_AUTHORIZATION_DATE] DATE NULL,
    [LAST_FOUR_DIGITS] VARCHAR(4) NULL,
    [LAST_UPDATED] DATE NULL,
    CONSTRAINT [PAYMENT_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[PAYMENT_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [NHIN_ID] BIGINT NOT NULL,
    [PAYMENT_ID] BIGINT NOT NULL,
    [ID_AAL] BIGINT NULL,
    [PAYMENT_AMOUNT] NUMERIC(13, 2) NULL,
    [PAYMENT_TYPE] VARCHAR(100) NULL,
    [AUTHORIZED_AMOUNT] NUMERIC(13, 2) NULL,
    [PRE_AUTH_DATE] DATE NULL,
    [SETTLE_DATE] DATE NULL,
    [CHECK_NUMBER] VARCHAR(20) NULL,
    [CARD_TYPE] BIGINT NULL,
    [CARD_EXPIRES] VARCHAR(4) NULL,
    [RESPONSE_CODE] VARCHAR(2) NULL,
    [RESPONSE_MESSAGE] VARCHAR(255) NULL,
    [SETTLE_RESPONSE_CODE] VARCHAR(2) NULL,
    [SETTLE_RESPONSE_MESSAGE] VARCHAR(255) NULL,
    [SETTLE_REQUEST_TO_POS_DATE] DATE NULL,
    [MAX_AMOUNT] NUMERIC(13, 2) NULL,
    [CANCEL_AUTHORIZATION_DATE] DATE NULL,
    [LAST_FOUR_DIGITS] VARCHAR(4) NULL,
    [LAST_UPDATED] DATE NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL
);

CREATE TABLE [EPS].[PA_NUM] (
    [CHAIN_ID] BIGINT NULL,
    [ID] BIGINT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [COUNTER] BIGINT NULL,
    [DOLLAR_RX] NUMERIC(13, 4) NULL,
    [DOLLARS] NUMERIC(13, 4) NULL,
    [EFFECTIVE] DATE NULL,
    [EXPIRATION] DATE NULL,
    [FILLS] BIGINT NULL,
    [NUMBER_RX] BIGINT NULL,
    [PA_NUMBER] VARCHAR(28) NULL,
    [PROCESSED] DATE NULL,
    [QUANTITY] BIGINT NULL,
    [REPEAT] BIGINT NULL,
    [TOTAL_QUANTITY] BIGINT NULL,
    [TX_NUMBER] BIGINT NULL,
    [PA_NUM_TYPE] VARCHAR(1) NULL,
    [ID_TX_TP] BIGINT NULL,
    [ID_AAL] BIGINT NULL
);

CREATE TABLE [EPS].[PA_NUM_AUDIT] (
    [CHAIN_ID] BIGINT NULL,
    [ID] BIGINT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [COUNTER] BIGINT NULL,
    [DOLLAR_RX] NUMERIC(13, 4) NULL,
    [DOLLARS] NUMERIC(13, 4) NULL,
    [EFFECTIVE] DATE NULL,
    [EXPIRATION] DATE NULL,
    [FILLS] BIGINT NULL,
    [NUMBER_RX] BIGINT NULL,
    [PA_NUMBER] VARCHAR(28) NULL,
    [PROCESSED] DATE NULL,
    [QUANTITY] BIGINT NULL,
    [REPEAT] BIGINT NULL,
    [TOTAL_QUANTITY] BIGINT NULL,
    [TX_NUMBER] BIGINT NULL,
    [PA_NUM_TYPE] VARCHAR(1) NULL,
    [ID_TX_TP] BIGINT NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL
);
