-- ============================================================================
-- BATCH_CREATE_TABLES_BATCH9.sql
-- Purpose: Create 11 tables (Batch 9)
-- Tables: PRESCRIBER, PRESCRIBER_AUDIT, PRIOR_ADVERSE_REACTION,
--         PRIOR_ADVERSE_REACTION_AUDIT, PRIOR_ADVERSE_REACTION_AUDIT_CSD_23800,
--         PURGE_ERROR_LOG, PURGE_FLOW_MAP_CR15426, PURGE_FLOW_PATH,
--         PURGE_LEDGER, PURGE_RECORDS
-- ============================================================================

-- EXTERNAL FK DEPENDENCIES:
--   - PRIOR_ADVERSE_REACTION: 1 FK removed (ID_PATIENT→PATIENT)
--   - PRIOR_ADVERSE_REACTION_AUDIT: 1 FK removed (ID_PATIENT→PATIENT)
--   - PRIOR_ADVERSE_REACTION_AUDIT_CSD_23800: 1 FK removed (ID_PATIENT→PATIENT)
--   See REMOVED_FK_RESTORATION_SCRIPTS.sql Section 5 for post-prerequisite restoration

-- PROACTIVE DATA TYPE FIXES APPLIED:
--   - NUMBER → BIGINT (for all ID, ID_PATIENT, NHIN_ID columns)
--   - All DATETIME2 scales verified (all TIMESTAMP(6) → DATETIME2(6))
--   - All PK columns verified NOT NULL (E006 prevention)
--   - UROWID → VARBINARY (Azure SQL compatibility)

-- INTERNAL FK DEPENDENCY ORDERING:
--   - No internal FK dependencies in this batch
--   - PRESCRIBER FKs to SEC_ADMIN tables (both exist)

-- ============================================================================

CREATE TABLE [EPS].[PRESCRIBER] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [ADDRESS] VARCHAR(255) NULL,
    [ADDRESS1] VARCHAR(255) NULL,
    [AREA_CODE] VARCHAR(3) NULL,
    [CITY] VARCHAR(35) NULL,
    [COUNTRY] VARCHAR(4) NULL,
    [DEA] VARCHAR(35) NULL,
    [FAX_AREA_CODE] VARCHAR(3) NULL,
    [FAX_PHONE] VARCHAR(7) NULL,
    [FIRST_NAME] VARCHAR(20) NULL,
    [LAST_NAME] VARCHAR(25) NULL,
    [MIDDLE_NAME] VARCHAR(20) NULL,
    [NAME] VARCHAR(28) NULL,
    [PHONE] VARCHAR(7) NULL,
    [STATE] VARCHAR(2) NULL,
    [STATE_ID] VARCHAR(15) NULL,
    [ZIP] VARCHAR(15) NULL,
    [ID_AAL] BIGINT NULL,
    [ARCHIVE_DATE] DATE NULL,
    [NPI_NUM] VARCHAR(10) NULL,
    [HCID] VARCHAR(10) NULL,
    [HMS_IDENTIFIER] VARCHAR(10) NULL,
    [CPM_IDENTIFIER] VARCHAR(7) NULL,
    CONSTRAINT [PRESCRIBER_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [PRESCRIBER_FK_CHAIN] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID]),
    CONSTRAINT [PRESCRIBER_FK_STORE] FOREIGN KEY ([CHAIN_ID], [NHIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_STORE] ([CHAIN_NHIN_ID], [STORE_NHIN_ID])
);

CREATE TABLE [EPS].[PRESCRIBER_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [ADDRESS] VARCHAR(255) NULL,
    [ADDRESS1] VARCHAR(255) NULL,
    [AREA_CODE] VARCHAR(3) NULL,
    [CITY] VARCHAR(35) NULL,
    [COUNTRY] VARCHAR(4) NULL,
    [DEA] VARCHAR(35) NULL,
    [FAX_AREA_CODE] VARCHAR(3) NULL,
    [FAX_PHONE] VARCHAR(7) NULL,
    [FIRST_NAME] VARCHAR(20) NULL,
    [LAST_NAME] VARCHAR(25) NULL,
    [MIDDLE_NAME] VARCHAR(20) NULL,
    [NAME] VARCHAR(28) NULL,
    [PHONE] VARCHAR(7) NULL,
    [STATE] VARCHAR(2) NULL,
    [STATE_ID] VARCHAR(15) NULL,
    [ZIP] VARCHAR(15) NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [ARCHIVE_DATE] DATE NULL,
    [NPI_NUM] VARCHAR(10) NULL,
    [HCID] VARCHAR(10) NULL,
    [HMS_IDENTIFIER] VARCHAR(10) NULL,
    [CPM_IDENTIFIER] VARCHAR(7) NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL
);

CREATE TABLE [EPS].[PRIOR_ADVERSE_REACTION] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [NHIN_ID] BIGINT NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    [CLASS_NUMBER] NUMERIC(5, 0) NULL,
    [KDC5] NUMERIC(5, 0) NULL,
    [RASH] VARCHAR(1) NULL,
    [SHOCK] VARCHAR(1) NULL,
    [BREATH] VARCHAR(1) NULL,
    [GI_TRACT] VARCHAR(1) NULL,
    [BLOOD] VARCHAR(1) NULL,
    [UNSPEC] VARCHAR(1) NULL,
    [START_DATE] DATETIME2(6) NULL,
    [ADDED] DATETIME2(6) NULL,
    [REPORT_BY] VARCHAR(2) NULL,
    [DELETED] VARCHAR(1) NULL,
    [ID_AAL] BIGINT NULL,
    CONSTRAINT [PRIOR_ADVERSE_REACTION_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[PRIOR_ADVERSE_REACTION_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [NHIN_ID] BIGINT NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    [CLASS_NUMBER] NUMERIC(5, 0) NULL,
    [KDC5] NUMERIC(5, 0) NULL,
    [RASH] VARCHAR(1) NULL,
    [SHOCK] VARCHAR(1) NULL,
    [BREATH] VARCHAR(1) NULL,
    [GI_TRACT] VARCHAR(1) NULL,
    [BLOOD] VARCHAR(1) NULL,
    [UNSPEC] VARCHAR(1) NULL,
    [START_DATE] DATETIME2(6) NULL,
    [ADDED] DATETIME2(6) NULL,
    [REPORT_BY] VARCHAR(2) NULL,
    [DELETED] VARCHAR(1) NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    [ID_AAL] BIGINT NULL,
    CONSTRAINT [PK_PRIOR_ADVERSE_REACTION_AUDIT] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[PRIOR_ADVERSE_REACTION_AUDIT_CSD_23800] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [NHIN_ID] BIGINT NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    [CLASS_NUMBER] NUMERIC(5, 0) NULL,
    [KDC5] NUMERIC(5, 0) NULL,
    [RASH] VARCHAR(1) NULL,
    [SHOCK] VARCHAR(1) NULL,
    [BREATH] VARCHAR(1) NULL,
    [GI_TRACT] VARCHAR(1) NULL,
    [BLOOD] VARCHAR(1) NULL,
    [UNSPEC] VARCHAR(1) NULL,
    [START_DATE] DATETIME2(6) NULL,
    [ADDED] DATETIME2(6) NULL,
    [REPORT_BY] VARCHAR(2) NULL,
    [DELETED] VARCHAR(1) NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    [ID_AAL] BIGINT NULL,
    CONSTRAINT [PK_PRIOR_ADVERSE_REACTION_AUDIT_CSD_23800] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[PURGE_ERROR_LOG] (
    [ID] BIGINT NOT NULL,
    [FAILED_STATEMENT] VARCHAR(4000) NULL,
    [ERROR_TEXT] VARCHAR(4000) NULL,
    [ERROR_DATE] DATE NULL,
    CONSTRAINT [PURGE_ERROR_LOG_PK] PRIMARY KEY CLUSTERED ([ID])
);

CREATE TABLE [EPS].[PURGE_FLOW_MAP_CR15426] (
    [TABLE_NAME] VARCHAR(100) NULL,
    [CONSTRAINT_NAME] VARCHAR(100) NULL,
    [PART_NAME] VARCHAR(100) NULL,
    [PART_KEY] VARCHAR(100) NULL,
    [PART_POSITION] BIGINT NULL,
    [HIERARCHY_LEVEL] BIGINT NULL,
    [NUMBER_OF_CHILD] VARCHAR(1) NULL,
    [PURGE_RUN_DETAILS_ID] BIGINT NULL,
    [PURGE_REC_RUN_DETAILS_ID] BIGINT NULL,
    [ADDITIONAL_INFO] VARCHAR(4000) NULL
);

CREATE TABLE [EPS].[PURGE_FLOW_PATH] (
    [TABLE_NAME] VARCHAR(100) NULL,
    [CONSTRAINT_NAME] VARCHAR(100) NULL,
    [HIERARCHY_LEVEL] BIGINT NULL,
    [NUMBER_OF_CHILD] VARCHAR(1) NULL,
    [EXEC_ORDER] BIGINT NULL
);

CREATE TABLE [EPS].[PURGE_LEDGER] (
    [ID] BIGINT NOT NULL,
    [TABLE_NAME] VARCHAR(30) NULL,
    [SUBOBJECT_NAME] VARCHAR(30) NULL,
    [ACTION_DETAIL] VARCHAR(4000) NULL,
    [ACTION_STATUS] VARCHAR(100) NULL,
    [SQL_TEXT] VARCHAR(4000) NULL,
    [ROWS_AFFECTED] BIGINT NULL,
    [START_DATE] DATE NULL,
    [END_DATE] DATE NULL,
    [ERROR_TEXT] VARCHAR(4000) NULL
);

CREATE TABLE [EPS].[PURGE_RECORDS] (
    [TABLE_NAME] VARCHAR(100) NULL,
    [PART_NAME] VARCHAR(100) NULL,
    [CHAIN_ID] BIGINT NULL,
    [ID] BIGINT NULL,
    [ROW_ID] VARBINARY(4000) NULL
);
