CREATE OR REPLACE SYNONYM WL_SBMO.ADDRESSES
	FOR SBMO.ADDRESSES
/
CREATE OR REPLACE SYNONYM WL_SBMO.ADJUSTMENT_CODES
	FOR SBMO.ADJUSTMENT_CODES
/
CREATE OR REPLACE SYNONYM WL_SBMO.ADJUSTMENT_GROUP
	FOR SBMO.ADJUSTMENT_GROUP
/
CREATE OR REPLACE SYNONYM WL_SBMO.AUDIT_LOG
	FOR SBMO.AUDIT_LOG
/
CREATE OR REPLACE SYNONYM WL_SBMO.BIN_UPC_LINK
	FOR SBMO.BIN_UPC_LINK
/
CREATE OR REPLACE SYNONYM WL_SBMO.CARRIER
	FOR SBMO.CARRIER
/
CREATE OR REPLACE SYNONYM WL_SBMO.CF_SEC_CHAIN
	FOR SBMO.CF_SEC_CHAIN
/
CREATE OR REPLACE SYNONYM WL_SBMO.CF_SEC_STORE
	FOR SBMO.CF_SEC_STORE
/
CREATE OR REPLACE SYNONYM WL_SBMO.CHAINS
	FOR SBMO.CHAINS
/
CREATE OR REPLACE SYNONYM WL_SBMO.CHARGE_PAYMENT_INFO
	FOR SBMO.CHARGE_PAYMENT_INFO
/
CREATE OR REPLACE SYNONYM WL_SBMO.CONTACTS
	FOR SBMO.CONTACTS
/
CREATE OR REPLACE SYNONYM WL_SBMO.CUSTOM_SCHEDULED_TASK
	FOR SBMO.CUSTOM_SCHEDULED_TASK
/
CREATE OR REPLACE SYNONYM WL_SBMO.DAILY_SCHEDULED_TASKS
	FOR SBMO.DAILY_SCHEDULED_TASKS
/
CREATE OR REPLACE SYNONYM WL_SBMO.DASHBOARD_SETTINGS
	FOR SBMO.DASHBOARD_SETTINGS
/
CREATE OR REPLACE SYNONYM WL_SBMO.DASHBOARD_STATISTICS
	FOR SBMO.DASHBOARD_STATISTICS
/
CREATE OR REPLACE SYNONYM WL_SBMO.DISPENSER_LOCATION
	FOR SBMO.DISPENSER_LOCATION
/
CREATE OR REPLACE SYNONYM WL_SBMO.DISPENSERS
	FOR SBMO.DISPENSERS
/
CREATE OR REPLACE SYNONYM WL_SBMO.DRUG_ORDER_PRODUCT_VERIFY
	FOR SBMO.DRUG_ORDER_PRODUCT_VERIFY
/
CREATE OR REPLACE SYNONYM WL_SBMO.DRUG_ORDERS
	FOR SBMO.DRUG_ORDERS
/
CREATE OR REPLACE SYNONYM WL_SBMO.DRUGS
	FOR SBMO.DRUGS
/
CREATE OR REPLACE SYNONYM WL_SBMO.ENCRYPTION_KEYS
	FOR SBMO.ENCRYPTION_KEYS
/
CREATE OR REPLACE SYNONYM WL_SBMO.ENCRYPTION_KEYS_AUDIT
	FOR SBMO.ENCRYPTION_KEYS_AUDIT
/
CREATE OR REPLACE SYNONYM WL_SBMO.ENTITIES
	FOR SBMO.ENTITIES
/
CREATE OR REPLACE SYNONYM WL_SBMO.FACILITIES
	FOR SBMO.FACILITIES
/
CREATE OR REPLACE SYNONYM WL_SBMO.FILLING_STATION
	FOR SBMO.FILLING_STATION
/
CREATE OR REPLACE SYNONYM WL_SBMO.FORMULARY
	FOR SBMO.FORMULARY
/
CREATE OR REPLACE SYNONYM WL_SBMO.FORMULARY_REORDER
	FOR SBMO.FORMULARY_REORDER
/
CREATE OR REPLACE SYNONYM WL_SBMO.ICN_SEQ
	FOR SBMO.ICN_SEQ
/
CREATE OR REPLACE SYNONYM WL_SBMO.INVENTORY
	FOR SBMO.INVENTORY
/
CREATE OR REPLACE SYNONYM WL_SBMO.INVENTORY_AUDIT
	FOR SBMO.INVENTORY_AUDIT
/
CREATE OR REPLACE SYNONYM WL_SBMO.INVENTORY_DATE
	FOR SBMO.INVENTORY_DATE
/
CREATE OR REPLACE SYNONYM WL_SBMO.ITEM_LOCATION
	FOR SBMO.ITEM_LOCATION
/
CREATE OR REPLACE SYNONYM WL_SBMO.LABEL_IMAGES
	FOR SBMO.LABEL_IMAGES
/
CREATE OR REPLACE SYNONYM WL_SBMO.LOCATION
	FOR SBMO.LOCATION
/
CREATE OR REPLACE SYNONYM WL_SBMO.MASTER_PRODUCT_PO_VERIFY
	FOR SBMO.MASTER_PRODUCT_PO_VERIFY
/
CREATE OR REPLACE SYNONYM WL_SBMO.MASTER_SEQ
	FOR SBMO.MASTER_SEQ
/
CREATE OR REPLACE SYNONYM WL_SBMO.MEDICAL_SUPPLIES
	FOR SBMO.MEDICAL_SUPPLIES
/
CREATE OR REPLACE SYNONYM WL_SBMO.MESSAGE_LOG
	FOR SBMO.MESSAGE_LOG
/
CREATE OR REPLACE SYNONYM WL_SBMO.MONTHLY_SCHEDULED_TASKS
	FOR SBMO.MONTHLY_SCHEDULED_TASKS
/
CREATE OR REPLACE SYNONYM WL_SBMO.MUTEX
	FOR SBMO.MUTEX
/
CREATE OR REPLACE SYNONYM WL_SBMO.MV_FORMULARY
	FOR SBMO.MV_FORMULARY
/
CREATE OR REPLACE SYNONYM WL_SBMO.NHIN_BATCH_SEQ
	FOR SBMO.NHIN_BATCH_SEQ
/
CREATE OR REPLACE SYNONYM WL_SBMO.ONCE_SCHEDULED_TASKS
	FOR SBMO.ONCE_SCHEDULED_TASKS
/
CREATE OR REPLACE SYNONYM WL_SBMO.ORDER_SEQ
	FOR SBMO.ORDER_SEQ
/
CREATE OR REPLACE SYNONYM WL_SBMO.ORDERS
	FOR SBMO.ORDERS
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_CONFIG
	FOR SBMO.PDX_SCHEMA_CONFIG
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_MAPPING
	FOR SBMO.PDX_SCHEMA_MAPPING
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_PRIV_DEFAULT
	FOR SBMO.PDX_SCHEMA_PRIV_DEFAULT
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_PRIV_EXCEPTION
	FOR SBMO.PDX_SCHEMA_PRIV_EXCEPTION
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_PROCESS_HISTORY
	FOR SBMO.PDX_SCHEMA_PROCESS_HISTORY
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_TASK_ERROR_LOG
	FOR SBMO.PDX_SCHEMA_TASK_ERROR_LOG
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_TASK_HISTORY
	FOR SBMO.PDX_SCHEMA_TASK_HISTORY
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG
	FOR SBMO.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_UPD_PKGCALL_HIST
	FOR SBMO.PDX_SCHEMA_UPD_PKGCALL_HIST
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_UPDATER_MANIFEST
	FOR SBMO.PDX_SCHEMA_UPDATER_MANIFEST
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_UPDATER_SQL
	FOR SBMO.PDX_SCHEMA_UPDATER_SQL
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_VERSION_ERROR_LOG
	FOR SBMO.PDX_SCHEMA_VERSION_ERROR_LOG
/
CREATE OR REPLACE SYNONYM WL_SBMO.PDX_SCHEMA_VERSION_HISTORY
	FOR SBMO.PDX_SCHEMA_VERSION_HISTORY
/
CREATE OR REPLACE SYNONYM WL_SBMO.PHONE_ADDRESS_OWNERS
	FOR SBMO.PHONE_ADDRESS_OWNERS
/
CREATE OR REPLACE SYNONYM WL_SBMO.PHONES
	FOR SBMO.PHONES
/
CREATE OR REPLACE SYNONYM WL_SBMO.PKG_PDX_SCHEMA_UPDATER
	FOR SBMO.PKG_PDX_SCHEMA_UPDATER
/
CREATE OR REPLACE SYNONYM WL_SBMO.PKG_PDX_SCHEMA_UPDATER_RPT
	FOR SBMO.PKG_PDX_SCHEMA_UPDATER_RPT
/
CREATE OR REPLACE SYNONYM WL_SBMO.PO_SEQ
	FOR SBMO.PO_SEQ
/
CREATE OR REPLACE SYNONYM WL_SBMO.PRIORITY_CHANGE_ALERTS
	FOR SBMO.PRIORITY_CHANGE_ALERTS
/
CREATE OR REPLACE SYNONYM WL_SBMO.PURCHASE_ORDER
	FOR SBMO.PURCHASE_ORDER
/
CREATE OR REPLACE SYNONYM WL_SBMO.PURCHASE_ORDER_GROUP
	FOR SBMO.PURCHASE_ORDER_GROUP
/
CREATE OR REPLACE SYNONYM WL_SBMO.QRTZ_BLOB_TRIGGERS
	FOR SBMO.QRTZ_BLOB_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_SBMO.QRTZ_CALENDARS
	FOR SBMO.QRTZ_CALENDARS
/
CREATE OR REPLACE SYNONYM WL_SBMO.QRTZ_CRON_TRIGGERS
	FOR SBMO.QRTZ_CRON_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_SBMO.QRTZ_FIRED_TRIGGERS
	FOR SBMO.QRTZ_FIRED_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_SBMO.QRTZ_JOB_DETAILS
	FOR SBMO.QRTZ_JOB_DETAILS
/
CREATE OR REPLACE SYNONYM WL_SBMO.QRTZ_LOCKS
	FOR SBMO.QRTZ_LOCKS
/
CREATE OR REPLACE SYNONYM WL_SBMO.QRTZ_PAUSED_TRIGGER_GRPS
	FOR SBMO.QRTZ_PAUSED_TRIGGER_GRPS
/
CREATE OR REPLACE SYNONYM WL_SBMO.QRTZ_SCHEDULER_STATE
	FOR SBMO.QRTZ_SCHEDULER_STATE
/
CREATE OR REPLACE SYNONYM WL_SBMO.QRTZ_SIMPLE_TRIGGERS
	FOR SBMO.QRTZ_SIMPLE_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_SBMO.QRTZ_SIMPROP_TRIGGERS
	FOR SBMO.QRTZ_SIMPROP_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_SBMO.QRTZ_TRIGGERS
	FOR SBMO.QRTZ_TRIGGERS
/
CREATE OR REPLACE SYNONYM WL_SBMO.QUEUE_SEQ
	FOR SBMO.QUEUE_SEQ
/
CREATE OR REPLACE SYNONYM WL_SBMO.REGION
	FOR SBMO.REGION
/
CREATE OR REPLACE SYNONYM WL_SBMO.REPORT_REQUEST
	FOR SBMO.REPORT_REQUEST
/
CREATE OR REPLACE SYNONYM WL_SBMO.REPORT_REQUEST_PARAMETER
	FOR SBMO.REPORT_REQUEST_PARAMETER
/
CREATE OR REPLACE SYNONYM WL_SBMO.RETAIL_COST
	FOR SBMO.RETAIL_COST
/
CREATE OR REPLACE SYNONYM WL_SBMO.RETURN_AND_ADJUSTMENT
	FOR SBMO.RETURN_AND_ADJUSTMENT
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_CORES
	FOR SBMO.RX_CORES
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_CORES_MIN_DATE
	FOR SBMO.RX_CORES_MIN_DATE
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_DETAILS
	FOR SBMO.RX_DETAILS
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_DIGITAL_DOCUMENTS
	FOR SBMO.RX_DIGITAL_DOCUMENTS
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_DOCUMENTS
	FOR SBMO.RX_DOCUMENTS
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_HOURS_OF_ADMIN_DOSES
	FOR SBMO.RX_HOURS_OF_ADMIN_DOSES
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_HOURS_OF_ADMINISTRATION
	FOR SBMO.RX_HOURS_OF_ADMINISTRATION
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_IMAGE_DATA
	FOR SBMO.RX_IMAGE_DATA
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_LOTS
	FOR SBMO.RX_LOTS
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_PATSTORES
	FOR SBMO.RX_PATSTORES
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_PRINT_CHR
	FOR SBMO.RX_PRINT_CHR
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_PRINT_INFO
	FOR SBMO.RX_PRINT_INFO
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_REQUEST_ERROR
	FOR SBMO.RX_REQUEST_ERROR
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_SHIPPING_PACKAGES
	FOR SBMO.RX_SHIPPING_PACKAGES
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_STATE_TRANSITION
	FOR SBMO.RX_STATE_TRANSITION
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_TP_INFO
	FOR SBMO.RX_TP_INFO
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_VIAL_INFOS
	FOR SBMO.RX_VIAL_INFOS
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_WARNING_LABEL_CODES
	FOR SBMO.RX_WARNING_LABEL_CODES
/
CREATE OR REPLACE SYNONYM WL_SBMO.RX_WARNING_LABELS
	FOR SBMO.RX_WARNING_LABELS
/
CREATE OR REPLACE SYNONYM WL_SBMO.SBMO_LOCKS
	FOR SBMO.SBMO_LOCKS
/
CREATE OR REPLACE SYNONYM WL_SBMO.SBMO_PROPERTIES
	FOR SBMO.SBMO_PROPERTIES
/
CREATE OR REPLACE SYNONYM WL_SBMO.SCHEDULED_TASKS
	FOR SBMO.SCHEDULED_TASKS
/
CREATE OR REPLACE SYNONYM WL_SBMO.SCHEMA_UPDATER_MANIFEST
	FOR SBMO.SCHEMA_UPDATER_MANIFEST
/
CREATE OR REPLACE SYNONYM WL_SBMO.SCHEMA_UPDATER_SQL
	FOR SBMO.SCHEMA_UPDATER_SQL
/
CREATE OR REPLACE SYNONYM WL_SBMO.SHIP_ITEMS
	FOR SBMO.SHIP_ITEMS
/
CREATE OR REPLACE SYNONYM WL_SBMO.SHIPMENT
	FOR SBMO.SHIPMENT
/
CREATE OR REPLACE SYNONYM WL_SBMO.STORE_SHIP_VIA
	FOR SBMO.STORE_SHIP_VIA
/
CREATE OR REPLACE SYNONYM WL_SBMO.STORE_VENDOR_ACCOUNT
	FOR SBMO.STORE_VENDOR_ACCOUNT
/
CREATE OR REPLACE SYNONYM WL_SBMO.STORES
	FOR SBMO.STORES
/
CREATE OR REPLACE SYNONYM WL_SBMO.SYSTEM_MESSAGES
	FOR SBMO.SYSTEM_MESSAGES
/
CREATE OR REPLACE SYNONYM WL_SBMO.TENANTS
	FOR SBMO.TENANTS
/
CREATE OR REPLACE SYNONYM WL_SBMO.USER_AUDIT_LOG
	FOR SBMO.USER_AUDIT_LOG
/
CREATE OR REPLACE SYNONYM WL_SBMO.VENDOR
	FOR SBMO.VENDOR
/
CREATE OR REPLACE SYNONYM WL_SBMO.VENDOR_ITEM_PROP
	FOR SBMO.VENDOR_ITEM_PROP
/
CREATE OR REPLACE SYNONYM WL_SBMO.VENDOR_PO_CREATE_DAYS
	FOR SBMO.VENDOR_PO_CREATE_DAYS
/
CREATE OR REPLACE SYNONYM WL_SBMO.VENDOR_PROP
	FOR SBMO.VENDOR_PROP
/
CREATE OR REPLACE SYNONYM WL_SBMO.VISUALLY_IMPAIRED_DETAILS
	FOR SBMO.VISUALLY_IMPAIRED_DETAILS
/
CREATE OR REPLACE SYNONYM WL_SBMO.WEEKLY_SCHEDULED_TASKS
	FOR SBMO.WEEKLY_SCHEDULED_TASKS
/
