CREATE TABLE ESCRIBE.ADDRESS
( 
	ID NUMBER(38, 0) NOT NULL,
	ADDRESS_LINE_1 VARCHAR2(55) NOT NULL,
	CITY VARCHAR2(30) NOT NULL,
	STATE VARCHAR2(2) NOT NULL,
	ZIP_CODE VARCHAR2(9) NOT NULL,
	COUNTRY VARCHAR2(3),
	ADDRESS_LINE_2 VARCHAR2(55),
	DEPARTMENT_MAIL_STOP VARCHAR2(40),
	SYS_NC00009$ VARCHAR2(5) GENERATED ALWAYS AS (SUBSTR("ZIP_CODE",1,5)) VIRTUAL 
)
/
CREATE TABLE ESCRIBE.ADDRESS_UPD_ERR
( 
	ID NUMBER(38, 0),
	ADDRESS_LINE_1 VARCHAR2(55),
	CITY VARCHAR2(30),
	STATE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	COUNTRY VARCHAR2(3),
	ADDRESS_LINE_2 VARCHAR2(55),
	DEPARTMENT_MAIL_STOP VARCHAR2(40)
)
/
CREATE TABLE ESCRIBE.APP_ROLE
( 
	ID NUMBER(38, 0) NOT NULL,
	ROLE VARCHAR2(20) NOT NULL,
	DESCRIPTION VARCHAR2(100)
)
/
CREATE TABLE ESCRIBE.APP_USER
( 
	ID NUMBER(38, 0) NOT NULL,
	USERNAME VARCHAR2(20) NOT NULL,
	LAST_NAME VARCHAR2(25) NOT NULL,
	FIRST_NAME VARCHAR2(25) NOT NULL,
	ID_NHIN_PRESCRIBER NUMBER(38, 0) NOT NULL,
	MIDDLE_NAME VARCHAR2(20),
	INACTIVE NUMBER(1, 0),
	EMAIL_ADDRESS VARCHAR2(120),
	LOCKOUT_DATE DATE,
	INVALID_ATTEMPTS NUMBER(2, 0),
	PASSWORD VARCHAR2(32),
	PASSWORD_DATE_CREATED DATE,
	LAST_FAILED_LOGIN DATE,
	LAST_SUCCESSFUL_LOGIN DATE
)
/
CREATE TABLE ESCRIBE.APP_USER_ROLE
( 
	ID_APP_USER NUMBER(38, 0) NOT NULL,
	ID_APP_ROLE NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE ESCRIBE.AUDIT_DATES
( 
	ID NUMBER(38, 0) NOT NULL,
	TABLE_CLASS_NAME VARCHAR2(30) NOT NULL,
	TABLE_ROW_ID NUMBER(38, 0) NOT NULL,
	USER_CREATE_LOGIN VARCHAR2(255),
	USER_CREATE_DATE DATE,
	SYSTEM_CREATE_DATE DATE,
	USER_UPDATE_LOGIN VARCHAR2(255),
	USER_UPDATE_DATE DATE,
	SYSTEM_UPDATE_DATE DATE
)
/
CREATE TABLE ESCRIBE.AUDIT_DATES_UPD_ERR
( 
	ID NUMBER(38, 0),
	TABLE_CLASS_NAME VARCHAR2(30),
	TABLE_ROW_ID NUMBER(38, 0),
	USER_CREATE_LOGIN VARCHAR2(255),
	USER_CREATE_DATE DATE,
	SYSTEM_CREATE_DATE DATE,
	USER_UPDATE_LOGIN VARCHAR2(255),
	USER_UPDATE_DATE DATE,
	SYSTEM_UPDATE_DATE DATE
)
/
CREATE TABLE ESCRIBE.BILLING_SERVICES
( 
	ID NUMBER(38, 0) NOT NULL,
	NCPDP_BILLING_NUMBER NUMBER(7, 0),
	SERVICE_PHONE_NUMBER NUMBER(10, 0),
	SERVICE_NAME VARCHAR2(120),
	SERVICE_WEB_SITE VARCHAR2(120),
	SERVICE_EMAIL_ADDRESS VARCHAR2(120),
	SERVICE_CONTACT_NAME VARCHAR2(120)
)
/
CREATE TABLE ESCRIBE.CLAIM_HISTORY
( 
	ID NUMBER(38, 0) NOT NULL,
	RX_NUMBER NUMBER(10, 0) NOT NULL,
	ID_DRUG NUMBER(38, 0) NOT NULL,
	ID_NHIN_PRESCRIBER NUMBER(38, 0) NOT NULL,
	ID_INSURANCE_PLAN NUMBER(38, 0) NOT NULL,
	ID_NCPDP_MESSAGE_CLAIM NUMBER(38, 0),
	ID_NCPDP_MESSAGE_CLAIM_RESP NUMBER(38, 0),
	ID_NCPDP_MESSAGE_REVERSE NUMBER(38, 0),
	ID_NCPDP_MESSAGE_REVERSE_RESP NUMBER(38, 0),
	USER_ENTERED_QUANTITY NUMBER(13, 3),
	SUBMIT_AMOUNT NUMBER(13, 2),
	RECEIVED_AMOUNT NUMBER(13, 2),
	RECEIVED_COPAY NUMBER(13, 2),
	PATIENT_DATE_OF_BIRTH DATE,
	DATE_OF_SERVICE DATE,
	REVERSAL_DATE DATE,
	SUBMIT_TIME DATE,
	PATIENT_LAST_NAME VARCHAR2(35),
	PATIENT_FIRST_NAME VARCHAR2(35),
	PRIOR_AUTHORIZATION_NUMBER VARCHAR2(28),
	REFERENCE_NUMBER VARCHAR2(20),
	CARDHOLDER_ID VARCHAR2(15),
	GROUP_NUMBER VARCHAR2(15),
	PCN VARCHAR2(10),
	BIN VARCHAR2(6),
	REVERSAL_PAID_STATUS VARCHAR2(1),
	PAID_STATUS VARCHAR2(1),
	SUBMITTED_QUANTITY NUMBER(16, 3)
)
/
CREATE TABLE ESCRIBE.CLAIM_PROCESSOR
( 
	ID NUMBER(38, 0) NOT NULL,
	CLAIM_PROCESSOR_CODE VARCHAR2(10) NOT NULL,
	SOFTWARE_VENDOR_ID VARCHAR2(10)
)
/
CREATE TABLE ESCRIBE.CPR_LINK_AUDIT
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_PRESCRIPTIONS_WRITTEN NUMBER(38, 0) NOT NULL,
	OLD_RXCOM_ID NUMBER(38, 0) NOT NULL,
	NEW_RXCOM_ID NUMBER(38, 0) NOT NULL,
	DATE_UPDATED DATE NOT NULL,
	MESSAGE_ID NUMBER(38, 0) NOT NULL,
	RECORD_UPDATED_BY VARCHAR2(20) NOT NULL
)
/
CREATE TABLE ESCRIBE.CUSTOM_SIGS
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_NHIN_PRESCRIBER NUMBER(38, 0) NOT NULL,
	SIG_CODE VARCHAR2(10) NOT NULL,
	SIG_TEXT VARCHAR2(255) NOT NULL
)
/
CREATE TABLE ESCRIBE.DRUG
( 
	ID NUMBER(38, 0) NOT NULL,
	NDC NUMBER(11, 0) NOT NULL,
	DRUG_NAME VARCHAR2(255) NOT NULL,
	PACK_SIZE NUMBER(13, 2),
	AWP NUMBER(13, 2),
	MANUFACTURER VARCHAR2(10),
	CONVERSION_FACTOR NUMBER(8, 3)
)
/
CREATE TABLE ESCRIBE.ENROLLMENT_FORMS
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_PRESCRIPTIONS_WRITTEN NUMBER(38, 0) NOT NULL,
	PATIENT_MIDDLE_INITIAL VARCHAR2(1),
	PATIENT_CELL_PHONE NUMBER(10, 0),
	PATIENT_EMAIL VARCHAR2(255),
	CREDIT_CARD_TYPE VARCHAR2(1),
	CREDIT_CARD_NUMBER VARCHAR2(33),
	CREDIT_CARD_EXP_DATE VARCHAR2(17),
	CREDIT_CARD_POSTAL_CODE VARCHAR2(24),
	CREDIT_CARD_SIG_ON_FILE VARCHAR2(1),
	PATIENT_RELATIONSHIP VARCHAR2(1),
	CONTACT_METHOD VARCHAR2(1),
	AUTOSHIP VARCHAR2(1),
	INITIAL_SHIPMENT VARCHAR2(1),
	INITIAL_SHIPMENT_DATE DATE,
	PRICING_LEVEL VARCHAR2(1),
	SHIPPING_PREFERENCE VARCHAR2(1),
	PATIENT_SIG_ON_FILE VARCHAR2(1),
	OTHER_HEALTH_CONDITION VARCHAR2(255),
	OTHER_ALLERGY VARCHAR2(255),
	PROMOTION_CODE VARCHAR2(20),
	DAYS_SUPPLY_INDICATED NUMBER(3, 0)
)
/
CREATE TABLE ESCRIBE.ENROLLMENT_FORMS_ALLERGIES
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_ENROLLMENT_FORMS NUMBER(38, 0) NOT NULL,
	ALLERGY_INDICATED VARCHAR2(6) NOT NULL
)
/
CREATE TABLE ESCRIBE.ENROLLMENT_FORMS_HEALTH_COND
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_ENROLLMENT_FORMS NUMBER(38, 0) NOT NULL,
	HEALTH_COND_INDICATED VARCHAR2(6) NOT NULL
)
/
CREATE TABLE ESCRIBE.ERX_EDI_PHARMACIES_XT
( 
	NCPDP_NUMBER VARCHAR2(7)
)
/
CREATE TABLE ESCRIBE.FAILED_MESSAGES
( 
	ID NUMBER(38, 0) NOT NULL,
	FAILURE_TYPE NUMBER(1, 0),
	DATE_FAILED DATE,
	FAILED_MESSAGE BLOB,
	RETRY_ATTEMPTS NUMBER(2, 0)
)
/
CREATE TABLE ESCRIBE.HCI_PRESCRIBER_SOURCE_DATA_XT
( 
	COMM_GROUP_ID VARCHAR2(10),
	DEA_REGISTRATION_NUM VARCHAR2(13),
	DEA_NUM_RENEWAL_DATE NUMBER(8, 0),
	LAST_NAME VARCHAR2(25),
	PREVIOUS_LAST_NAME VARCHAR2(40),
	FIRST_NAME VARCHAR2(25),
	MIDDLE_NAME_INITIAL VARCHAR2(1),
	NAME_SUFFIX VARCHAR2(3),
	GENDER_CODE VARCHAR2(1),
	ORGANIZATION_NAME VARCHAR2(60),
	DEPARTMENT_MAIL_STOP VARCHAR2(40),
	PHYS_ADDRESS_LINE_1 VARCHAR2(30),
	PHYS_ADDRESS_LINE_2 VARCHAR2(30),
	PHYS_SUITE_APARTMENT_NUM VARCHAR2(8),
	PHYS_CITY_NAME VARCHAR2(20),
	PHYS_STATE_PROVINCE_CODE VARCHAR2(2),
	PHYS_ZIP_POSTAL_ZONE VARCHAR2(9),
	PHYS_COUNTRY_CODE VARCHAR2(3),
	PRIME_PHONE_NUM NUMBER(10, 0),
	SECOND_PHONE_NUM NUMBER(10, 0),
	REFILL_PHONE_NUM NUMBER(10, 0),
	FAX_NUM NUMBER(10, 0),
	EMAIL_ADDRESS VARCHAR2(25),
	PRIME_DEGREE VARCHAR2(5),
	PRIME_TAXONOMY_CODE VARCHAR2(10),
	SECOND_DEGREE VARCHAR2(5),
	SECOND_TAXONOMY_CODE VARCHAR2(10),
	STATE_CODE_PRIME_MEDICAID_ID VARCHAR2(2),
	PRIME_MEDICAID_ID VARCHAR2(15),
	STATE_CODE_SECOND_MEDICAID_ID VARCHAR2(2),
	SECOND_MEDICAID_ID VARCHAR2(15),
	STATE_CODE_THIRD_MEDICAID_ID VARCHAR2(2),
	THIRD_MEDICAID_ID VARCHAR2(15),
	UPIN_NUM VARCHAR2(6),
	HIN_NUM VARCHAR2(15),
	HCID_LOCATION_CODE NUMBER(2, 0),
	DEA_STATUS_CODE VARCHAR2(1),
	RETIRE_DATE NUMBER(8, 0),
	DATA_SUPPLIER_REF_KEY_1 VARCHAR2(20),
	DATA_SUPPLIER_REF_KEY_2 VARCHAR2(20),
	DATA_SUPPLIER_REF_KEY_3 VARCHAR2(20),
	DATA_SUPPLIER_SITE_NUM VARCHAR2(15),
	NPI VARCHAR2(30),
	HCID_IDENTIFIER VARCHAR2(30),
	NHIN_PROVIDER_ID VARCHAR2(30),
	PHYS_LOCATION_TYPE_CODE VARCHAR2(2),
	DUPE_DEA_FLAG CHAR(1),
	DUPE_DATA_SUPPLIER_REF_KEY_1 VARCHAR2(20),
	COMM_SUB_GROUP_ID VARCHAR2(10),
	UPDATE_RECORD_TYPE_CODE VARCHAR2(1),
	DATE_LAST_CHANGE NUMBER(8, 0),
	DEA_REGISTRATION_NUM_SUFFIX VARCHAR2(7),
	DEA_DRUG_SCHEDULE VARCHAR2(12),
	NCPDP_PROVIDER_ID_NUM VARCHAR2(15),
	DUPE_DATA_SUPPLIER_REF_KEY_2 VARCHAR2(20),
	DUPE_DATA_SUPPLIER_REF_KEY_3 VARCHAR2(20),
	ORIGIN VARCHAR2(1),
	RESERVE_1 VARCHAR2(1),
	PREVIOUS_HCID VARCHAR2(15),
	REPLACEMENT_HCID VARCHAR2(15),
	HCID_DC_DATE NUMBER(8, 0),
	NHIN_DECEASED_FLAG VARCHAR2(1),
	NHIN_DECEASED_DATE NUMBER(8, 0),
	REPLACEMENT_DEA_NUM VARCHAR2(13),
	PREVIOUS_DEA_NUM VARCHAR2(13),
	DATA_ELEMENT_CHANGE_TYPE VARCHAR2(3),
	RESERVED VARCHAR2(4),
	STATE_LICENSE_1 VARCHAR2(20),
	LICENSING_STATE_1 VARCHAR2(3),
	STATE_LICENSE_2 VARCHAR2(20),
	LICENSING_STATE_2 VARCHAR2(3),
	STATE_LICENSE_3 VARCHAR2(20),
	LICENSING_STATE_3 VARCHAR2(3),
	FILLER VARCHAR2(149)
)
/
CREATE TABLE ESCRIBE.INSURANCE_PLAN
( 
	ID NUMBER(38, 0) NOT NULL,
	BIN VARCHAR2(6) NOT NULL,
	PCN VARCHAR2(10),
	PLAN_NAME VARCHAR2(120),
	PHONE_NUMBER NUMBER(10, 0),
	GROUP_NUMBER VARCHAR2(15),
	PDX_CARRIER_CODE VARCHAR2(10) NOT NULL,
	CLAIM_PROCESSOR NUMBER(38, 0)
)
/
CREATE TABLE ESCRIBE.MANUFACTURER_PROGRAM
( 
	ID NUMBER(38, 0) NOT NULL,
	PROGRAM_NAME VARCHAR2(120) NOT NULL,
	PROGRAM_PHONE NUMBER(10, 0),
	PROGRAM_CONTACT_NAME VARCHAR2(60),
	PROGRAM_FORM_URL VARCHAR2(120),
	PROGRAM_LOGO_IMAGE VARCHAR2(120)
)
/
CREATE TABLE ESCRIBE.MFR_PROGRAM_NDC_LINK
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_MANUFACTURER_PROGRAM NUMBER(38, 0) NOT NULL,
	PROGRAM_FORM_URL VARCHAR2(120),
	NDC VARCHAR2(13),
	DRUG_NAME VARCHAR2(120),
	DDID NUMBER(10, 0)
)
/
CREATE TABLE ESCRIBE.MFR_PROGRAM_PHARMACY_LINK
( 
	ID NUMBER(38, 0) NOT NULL,
	NCPDP_NUMBER VARCHAR2(7) NOT NULL,
	ID_MANUFACTURER_PROGRAM NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE ESCRIBE.NCPDP_MESSAGES
( 
	ID NUMBER(38, 0) NOT NULL,
	NCPDP_MESSAGE BLOB NOT NULL
)
/
CREATE TABLE ESCRIBE.NCPDP_PHARMACY_MEDICAID_IDS_XT
( 
	NCPDP_PROVIDER_NUM VARCHAR2(7),
	STATE_CODE VARCHAR2(2),
	MEDICAID_ID VARCHAR2(20),
	DELETE_DATE VARCHAR2(8),
	FILLER VARCHAR2(113)
)
/
CREATE TABLE ESCRIBE.NCPDP_PHARMACY_SOURCE_DATA_XT
( 
	NCPDP_PROVIDER_NUM VARCHAR2(7),
	LEGAL_BUS_NAME VARCHAR2(60),
	"NAME" VARCHAR2(60),
	STORE_NUM VARCHAR2(10),
	ADDRESS_1 VARCHAR2(55),
	ADDRESS_2 VARCHAR2(55),
	CITY VARCHAR2(30),
	STATE_CODE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	PHONE_NUM VARCHAR2(10),
	FAX_NUM VARCHAR2(10),
	E_MAIL_ADDRESS VARCHAR2(50),
	CROSS_STREET_DIRECTIONS VARCHAR2(50),
	FIPS_COUNTY_PARISH_CODE VARCHAR2(5),
	FIPS_MSA_CODE VARCHAR2(4),
	FIPS_PMSA_CODE VARCHAR2(4),
	OPEN_24_HOUR VARCHAR2(1),
	PROVIDER_HOURS VARCHAR2(35),
	ACCEPTS_ESCRIPTS VARCHAR2(1),
	DELIVERY_SERVICE VARCHAR2(1),
	COMPOUNDING_SERVICE VARCHAR2(1),
	DRIVE_UP_WINDOW VARCHAR2(1),
	SELLS_DME_EQUIPMENT VARCHAR2(1),
	CONGRESSIONAL_VOTING_DIST VARCHAR2(4),
	LANGUAGE_CODE_1 VARCHAR2(2),
	LANGUAGE_CODE_2 VARCHAR2(2),
	LANGUAGE_CODE_3 VARCHAR2(2),
	LANGUAGE_CODE_4 VARCHAR2(2),
	LANGUAGE_CODE_5 VARCHAR2(2),
	HANDICAP_ACCESSIBLE VARCHAR2(1),
	STORE_OPEN_DATE VARCHAR2(8),
	STORE_CLOSURE_DATE VARCHAR2(8),
	MAILING_ADDRESS_1 VARCHAR2(55),
	MAILING_ADDRESS_2 VARCHAR2(55),
	MAILING_ADDRESS_CITY VARCHAR2(30),
	MAILING_ADDRESS_STATE_CODE VARCHAR2(2),
	MAILING_ADDRESS_ZIP_CODE VARCHAR2(9),
	CONTACT_LAST_NAME VARCHAR2(20),
	CONTACT_FIRST_NAME VARCHAR2(20),
	CONTACT_MIDDLE_INITIAL VARCHAR2(1),
	CONTACT_TITLE VARCHAR2(30),
	CONTACT_PHONE_NUM VARCHAR2(10),
	CONTACT_EXTENSION VARCHAR2(5),
	CONTACT_E_MAIL_ADDRESS VARCHAR2(50),
	DISPENSER_CLASS_CODE VARCHAR2(2),
	PRIMARY_DISPENSER_TYPE_CODE VARCHAR2(2),
	SECONDARY_DISPENSER_TYPE_CODE VARCHAR2(2),
	TERTIARY_DISPENSER_TYPE_CODE VARCHAR2(2),
	MEDICARE_ID VARCHAR2(10),
	NPI_ID VARCHAR2(10),
	DEA_REGISTRATION_ID VARCHAR2(12),
	FEDERAL_TAX_ID VARCHAR2(15),
	STATE_LICENSE_NUM VARCHAR2(20),
	STATE_TAX_ID VARCHAR2(15),
	DELETE_DATE VARCHAR2(8),
	TRANSACTION_CODE VARCHAR2(1),
	TRANSACTION_DATE VARCHAR2(8),
	FILLER VARCHAR2(108)
)
/
CREATE TABLE ESCRIBE.NHIN_CLINIC
( 
	ID NUMBER(38, 0) NOT NULL,
	NHIN_COM_CLINIC_ID NUMBER(38, 0) NOT NULL,
	ID_ADDRESS NUMBER(38, 0) NOT NULL,
	OFFICE_PHONE_1 NUMBER(10, 0),
	OFFICE_PHONE_2 NUMBER(10, 0),
	FAX_PHONE NUMBER(10, 0),
	REFILL_PHONE NUMBER(10, 0),
	CONTACT_PREF NUMBER(2, 0),
	SCRIPT_VERSION VARCHAR2(6),
	HIN VARCHAR2(9),
	FEDERAL_TAX_ID VARCHAR2(10),
	NPI VARCHAR2(30),
	DEPARTMENT_MAIL_STOP VARCHAR2(40),
	CLINIC_NAME VARCHAR2(60),
	CONTACT_NAME VARCHAR2(60),
	DEPARTMENT VARCHAR2(60),
	DEACTIVATION_DATE DATE
)
/
CREATE TABLE ESCRIBE.NHIN_CLINIC_UPD_ERR
( 
	ID NUMBER(38, 0),
	NHIN_COM_CLINIC_ID NUMBER(38, 0),
	ID_ADDRESS NUMBER(38, 0),
	OFFICE_PHONE_1 NUMBER(10, 0),
	OFFICE_PHONE_2 NUMBER(10, 0),
	FAX_PHONE NUMBER(10, 0),
	REFILL_PHONE NUMBER(10, 0),
	CONTACT_PREF NUMBER(2, 0),
	SCRIPT_VERSION VARCHAR2(6),
	HIN VARCHAR2(9),
	FEDERAL_TAX_ID VARCHAR2(10),
	NPI VARCHAR2(30),
	DEPARTMENT_MAIL_STOP VARCHAR2(40),
	CLINIC_NAME VARCHAR2(60),
	CONTACT_NAME VARCHAR2(60),
	DEPARTMENT VARCHAR2(60),
	DEACTIVATION_DATE DATE
)
/
CREATE TABLE ESCRIBE.NHIN_PRESCR_CLINIC_LNK_UPD_ERR
( 
	ID NUMBER(38, 0),
	ID_NHIN_CLINIC NUMBER(38, 0),
	ID_NHIN_PRESCRIBER NUMBER(38, 0),
	DEACTIVATION_DATE DATE,
	SUPERVISING_PRES_ID NUMBER(38, 0),
	OFFICE_PHONE NUMBER(10, 0),
	FAX_PHONE NUMBER(10, 0),
	REFILL_PHONE NUMBER(10, 0),
	HCID VARCHAR2(30),
	HCIDEA_LOCATION VARCHAR2(3),
	HIN VARCHAR2(9),
	FEDERAL_TAX_ID VARCHAR2(10),
	DEA_ID VARCHAR2(15)
)
/
CREATE TABLE ESCRIBE.NHIN_PRESCRIBER
( 
	ID NUMBER(38, 0) NOT NULL,
	NHIN_COM_ID NUMBER(22, 0) NOT NULL,
	LAST_NAME VARCHAR2(25) NOT NULL,
	FIRST_NAME VARCHAR2(25) NOT NULL,
	MIDDLE_NAME VARCHAR2(20),
	NAME_SUFFIX VARCHAR2(5),
	NAME_PREFIX VARCHAR2(5),
	HCID VARCHAR2(30),
	NPI VARCHAR2(30),
	DEA_ID VARCHAR2(15),
	DEA_STATUS_CODE CHAR(1),
	DAW CHAR(1),
	GENDER CHAR(1),
	BIRTH_DATE DATE,
	DEACTIVATION_DATE DATE,
	NHIN_RETIRE DATE,
	NHIN_DECEASED DATE,
	MOBILE_PHONE NUMBER(10, 0),
	PAGER NUMBER(10, 0),
	HOME_PHONE NUMBER(10, 0),
	PROBATION VARCHAR2(1),
	SPECIALTY VARCHAR2(3),
	DEGREE_1 VARCHAR2(5),
	DEGREE_2 VARCHAR2(5),
	UPIN VARCHAR2(6),
	TAXONOMY_CODE_1 VARCHAR2(10),
	TAXONOMY_CODE_2 VARCHAR2(10),
	FEDERAL_TAX_ID VARCHAR2(10),
	NCPDP_ID VARCHAR2(15),
	PREVIOUS_HCID VARCHAR2(15),
	MEDICARE_ID VARCHAR2(20),
	BLUE_CROSS_ID VARCHAR2(20),
	BLUE_SHIELD_ID VARCHAR2(20),
	CHAMPUS_ID VARCHAR2(20),
	NHIN_ID VARCHAR2(30),
	EMAIL_ADDRESS VARCHAR2(120),
	VERIFIED VARCHAR2(1),
	ID_PRIMARY_CLINIC_LINK NUMBER(38, 0),
	NEW_RX_EMAIL_ADDRESS VARCHAR2(120),
	REGISTRATION_DATE DATE,
	REGISTRATION_PIN VARCHAR2(10),
	VERIFICATION_DATE DATE,
	ID_REGISTRATION_ADDRESS NUMBER(38, 0),
	ID_BILLING_SERVICE NUMBER(38, 0),
	TERMS_OF_USE_ACCEPTED VARCHAR2(10)
)
/
CREATE TABLE ESCRIBE.NHIN_PRESCRIBER_CLINIC_LINK
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_NHIN_CLINIC NUMBER(38, 0) NOT NULL,
	ID_NHIN_PRESCRIBER NUMBER(38, 0) NOT NULL,
	DEACTIVATION_DATE DATE,
	SUPERVISING_PRES_ID NUMBER(38, 0),
	OFFICE_PHONE NUMBER(10, 0),
	FAX_PHONE NUMBER(10, 0),
	REFILL_PHONE NUMBER(10, 0),
	HCID VARCHAR2(30),
	HCIDEA_LOCATION VARCHAR2(3),
	HIN VARCHAR2(9),
	FEDERAL_TAX_ID VARCHAR2(10),
	DEA_ID VARCHAR2(15)
)
/
CREATE TABLE ESCRIBE.NHIN_PRESCRIBER_UPD_ERR
( 
	ID NUMBER(38, 0),
	NHIN_COM_ID NUMBER(22, 0),
	LAST_NAME VARCHAR2(25),
	FIRST_NAME VARCHAR2(25),
	MIDDLE_NAME VARCHAR2(20),
	NAME_SUFFIX VARCHAR2(5),
	NAME_PREFIX VARCHAR2(5),
	HCID VARCHAR2(30),
	NPI VARCHAR2(30),
	DEA_ID VARCHAR2(15),
	DEA_STATUS_CODE CHAR(1),
	DAW CHAR(1),
	GENDER CHAR(1),
	BIRTH_DATE DATE,
	DEACTIVATION_DATE DATE,
	NHIN_RETIRE DATE,
	NHIN_DECEASED DATE,
	MOBILE_PHONE NUMBER(10, 0),
	PAGER NUMBER(10, 0),
	HOME_PHONE NUMBER(10, 0),
	PROBATION VARCHAR2(1),
	SPECIALTY VARCHAR2(3),
	DEGREE_1 VARCHAR2(5),
	DEGREE_2 VARCHAR2(5),
	UPIN VARCHAR2(6),
	TAXONOMY_CODE_1 VARCHAR2(10),
	TAXONOMY_CODE_2 VARCHAR2(10),
	FEDERAL_TAX_ID VARCHAR2(10),
	NCPDP_ID VARCHAR2(15),
	PREVIOUS_HCID VARCHAR2(15),
	MEDICARE_ID VARCHAR2(20),
	BLUE_CROSS_ID VARCHAR2(20),
	BLUE_SHIELD_ID VARCHAR2(20),
	CHAMPUS_ID VARCHAR2(20),
	NHIN_ID VARCHAR2(30),
	EMAIL_ADDRESS VARCHAR2(120),
	VERIFIED VARCHAR2(1),
	ID_PRIMARY_CLINIC_LINK NUMBER(38, 0),
	NEW_RX_EMAIL_ADDRESS VARCHAR2(120),
	REGISTRATION_DATE DATE,
	REGISTRATION_PIN VARCHAR2(10),
	VERIFICATION_DATE DATE,
	ID_REGISTRATION_ADDRESS NUMBER(38, 0),
	ID_BILLING_SERVICE NUMBER(38, 0),
	TERMS_OF_USE_ACCEPTED VARCHAR2(10)
)
/
CREATE TABLE ESCRIBE.ORDER_INFO
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_PRESCRIPTIONS_WRITTEN NUMBER(38, 0) NOT NULL,
	SHIPPED_DATE DATE,
	ORDER_STATUS NUMBER(2, 0),
	LAST_STATUS_DATE DATE
)
/
CREATE TABLE ESCRIBE.ORDER_INFO_20071101
( 
	ID NUMBER(38, 0),
	ID_PRESCRIPTIONS_WRITTEN NUMBER(38, 0) NOT NULL,
	SHIPPED_DATE DATE,
	ORDER_STATUS NUMBER(2, 0),
	LAST_STATUS_DATE DATE
)
/
CREATE TABLE ESCRIBE.ORDER_INFO_BK
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_PRESCRIPTIONS_WRITTEN NUMBER(38, 0) NOT NULL,
	SHIPPED_DATE DATE,
	ORDER_STATUS NUMBER(2, 0),
	LAST_STATUS_DATE DATE
)
/
CREATE TABLE ESCRIBE.PASSWORD_HISTORY
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_APP_USER NUMBER(38, 0) NOT NULL,
	PASSWORD VARCHAR2(32) NOT NULL,
	DATE_CREATED DATE NOT NULL
)
/
CREATE TABLE ESCRIBE.PHARM_MEDI_UPD_XT
( 
	NCPDP_PROVIDER_NUM VARCHAR2(7),
	STATE_CODE VARCHAR2(2),
	MEDICAID_ID VARCHAR2(20),
	DELETE_DATE VARCHAR2(8),
	FILLER VARCHAR2(113)
)
/
CREATE TABLE ESCRIBE.PHARM_UPD_XT
( 
	NCPDP_PROVIDER_NUM VARCHAR2(7),
	LEGAL_BUS_NAME VARCHAR2(60),
	"NAME" VARCHAR2(60),
	STORE_NUM VARCHAR2(10),
	ADDRESS_1 VARCHAR2(55),
	ADDRESS_2 VARCHAR2(55),
	CITY VARCHAR2(30),
	STATE_CODE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	PHONE_NUM VARCHAR2(10),
	FAX_NUM VARCHAR2(10),
	E_MAIL_ADDRESS VARCHAR2(50),
	CROSS_STREET_DIRECTIONS VARCHAR2(50),
	FIPS_COUNTY_PARISH_CODE VARCHAR2(5),
	FIPS_MSA_CODE VARCHAR2(4),
	FIPS_PMSA_CODE VARCHAR2(4),
	OPEN_24_HOUR VARCHAR2(1),
	PROVIDER_HOURS VARCHAR2(35),
	ACCEPTS_ESCRIPTS VARCHAR2(1),
	DELIVERY_SERVICE VARCHAR2(1),
	COMPOUNDING_SERVICE VARCHAR2(1),
	DRIVE_UP_WINDOW VARCHAR2(1),
	SELLS_DME_EQUIPMENT VARCHAR2(1),
	CONGRESSIONAL_VOTING_DIST VARCHAR2(4),
	LANGUAGE_CODE_1 VARCHAR2(2),
	LANGUAGE_CODE_2 VARCHAR2(2),
	LANGUAGE_CODE_3 VARCHAR2(2),
	LANGUAGE_CODE_4 VARCHAR2(2),
	LANGUAGE_CODE_5 VARCHAR2(2),
	HANDICAP_ACCESSIBLE VARCHAR2(1),
	STORE_OPEN_DATE VARCHAR2(8),
	STORE_CLOSURE_DATE VARCHAR2(8),
	MAILING_ADDRESS_1 VARCHAR2(55),
	MAILING_ADDRESS_2 VARCHAR2(55),
	MAILING_ADDRESS_CITY VARCHAR2(30),
	MAILING_ADDRESS_STATE_CODE VARCHAR2(2),
	MAILING_ADDRESS_ZIP_CODE VARCHAR2(9),
	CONTACT_LAST_NAME VARCHAR2(20),
	CONTACT_FIRST_NAME VARCHAR2(20),
	CONTACT_MIDDLE_INITIAL VARCHAR2(1),
	CONTACT_TITLE VARCHAR2(30),
	CONTACT_PHONE_NUM VARCHAR2(10),
	CONTACT_EXTENSION VARCHAR2(5),
	CONTACT_E_MAIL_ADDRESS VARCHAR2(50),
	DISPENSER_CLASS_CODE VARCHAR2(2),
	PRIMARY_DISPENSER_TYPE_CODE VARCHAR2(2),
	SECONDARY_DISPENSER_TYPE_CODE VARCHAR2(2),
	TERTIARY_DISPENSER_TYPE_CODE VARCHAR2(2),
	MEDICARE_ID VARCHAR2(10),
	NPI_ID VARCHAR2(10),
	DEA_REGISTRATION_ID VARCHAR2(12),
	FEDERAL_TAX_ID VARCHAR2(15),
	STATE_LICENSE_NUM VARCHAR2(20),
	STATE_TAX_ID VARCHAR2(15),
	DELETE_DATE VARCHAR2(8),
	TRANSACTION_CODE VARCHAR2(1),
	TRANSACTION_DATE VARCHAR2(8),
	FILLER VARCHAR2(108)
)
/
CREATE TABLE ESCRIBE.PHARMACY
( 
	ID NUMBER(38, 0) NOT NULL,
	NCPDP_NUMBER VARCHAR2(7) NOT NULL,
	ID_ADDRESS NUMBER(38, 0) NOT NULL,
	PHARMACY_NAME VARCHAR2(60) NOT NULL,
	NHIN_STORE_ID NUMBER(10, 0),
	STORE_NUMBER VARCHAR2(10),
	PHARMACY_DBA_NAME VARCHAR2(60),
	DEA_ID VARCHAR2(15),
	ID_MAILING_ADDRESS NUMBER(38, 0),
	PHONE_NUMBER NUMBER(10, 0),
	FAX_PHONE NUMBER(10, 0),
	DATE_OPENED DATE,
	DATE_CLOSED DATE,
	DEACTIVATED DATE,
	ACCEPTS_ESCRIPTS CHAR(1),
	DELIVERY_SERVICE CHAR(1),
	COMPOUNDING_SERVICE CHAR(1),
	DRIVE_UP_WINDOW CHAR(1),
	SELLS_DME_EQUIPMENT CHAR(1),
	HANDICAP_ACCESSIBLE CHAR(1),
	OPEN_24_HOUR CHAR(1),
	STATE_TAX_ID VARCHAR2(15),
	FEDERAL_TAX_ID VARCHAR2(15),
	STATE_LICENSE_NUMBER VARCHAR2(20),
	DISPENSER_CLASS_CODE VARCHAR2(2),
	DISPENSER_TYPE_CODE_1 VARCHAR2(2),
	DISPENSER_TYPE_CODE_2 VARCHAR2(2),
	DISPENSER_TYPE_CODE_3 VARCHAR2(2),
	LANGUAGE_CODE_1 VARCHAR2(2),
	LANGUAGE_CODE_2 VARCHAR2(2),
	LANGUAGE_CODE_3 VARCHAR2(2),
	LANGUAGE_CODE_4 VARCHAR2(2),
	LANGUAGE_CODE_5 VARCHAR2(2),
	CONGRESSIONAL_VOTING_DISTRICT VARCHAR2(4),
	FIPS_MSA_CODE VARCHAR2(4),
	FIPS_PMSA_CODE VARCHAR2(4),
	FIPS_COUNTY_CODE VARCHAR2(5),
	CONTACT_FIRST_NAME VARCHAR2(20),
	CONTACT_MIDDLE_INITIAL VARCHAR2(1),
	CONTACT_LAST_NAME VARCHAR2(20),
	CONTACT_TITLE VARCHAR2(30),
	CONTACT_PHONE_NUMBER VARCHAR2(10),
	CONTACT_PHONE_EXT VARCHAR2(5),
	UPIN VARCHAR2(10),
	NPI VARCHAR2(15),
	PHARMACY_HOURS VARCHAR2(35),
	CROSS_STREET_DIRECTIONS VARCHAR2(50),
	EMAIL_ADDRESS VARCHAR2(50),
	CONTACT_EMAIL_ADDRESS VARCHAR2(50),
	VENDOR_ID VARCHAR2(60),
	FAXABLE VARCHAR2(1)
)
/
CREATE TABLE ESCRIBE.PHARMACY_MEDICAID_IDS
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_PHARMACY NUMBER(38, 0) NOT NULL,
	STATE_CODE VARCHAR2(2) NOT NULL,
	MEDICAID_ID VARCHAR2(20) NOT NULL
)
/
CREATE TABLE ESCRIBE.PHARMACY_UPD_ERR
( 
	ID NUMBER(38, 0),
	NCPDP_NUMBER VARCHAR2(7),
	ID_ADDRESS NUMBER(38, 0),
	PHARMACY_NAME VARCHAR2(35),
	NHIN_STORE_ID NUMBER(10, 0),
	STORE_NUMBER VARCHAR2(10),
	PHARMACY_DBA_NAME VARCHAR2(35),
	DEA_ID VARCHAR2(15),
	ID_MAILING_ADDRESS NUMBER(38, 0),
	PHONE_NUMBER NUMBER(10, 0),
	FAX_PHONE NUMBER(10, 0),
	DATE_OPENED DATE,
	DATE_CLOSED DATE,
	DEACTIVATED DATE,
	ACCEPTS_ESCRIPTS CHAR(1),
	DELIVERY_SERVICE CHAR(1),
	COMPOUNDING_SERVICE CHAR(1),
	DRIVE_UP_WINDOW CHAR(1),
	SELLS_DME_EQUIPMENT CHAR(1),
	HANDICAP_ACCESSIBLE CHAR(1),
	OPEN_24_HOUR CHAR(1),
	STATE_TAX_ID VARCHAR2(15),
	FEDERAL_TAX_ID VARCHAR2(15),
	STATE_LICENSE_NUMBER VARCHAR2(20),
	DISPENSER_CLASS_CODE VARCHAR2(2),
	DISPENSER_TYPE_CODE_1 VARCHAR2(2),
	DISPENSER_TYPE_CODE_2 VARCHAR2(2),
	DISPENSER_TYPE_CODE_3 VARCHAR2(2),
	LANGUAGE_CODE_1 VARCHAR2(2),
	LANGUAGE_CODE_2 VARCHAR2(2),
	LANGUAGE_CODE_3 VARCHAR2(2),
	LANGUAGE_CODE_4 VARCHAR2(2),
	LANGUAGE_CODE_5 VARCHAR2(2),
	CONGRESSIONAL_VOTING_DISTRICT VARCHAR2(4),
	FIPS_MSA_CODE VARCHAR2(4),
	FIPS_PMSA_CODE VARCHAR2(4),
	FIPS_COUNTY_CODE VARCHAR2(5),
	CONTACT_FIRST_NAME VARCHAR2(20),
	CONTACT_MIDDLE_INITIAL VARCHAR2(1),
	CONTACT_LAST_NAME VARCHAR2(20),
	CONTACT_TITLE VARCHAR2(30),
	CONTACT_PHONE_NUMBER VARCHAR2(10),
	CONTACT_PHONE_EXT VARCHAR2(5),
	UPIN VARCHAR2(10),
	NPI VARCHAR2(15),
	PHARMACY_HOURS VARCHAR2(35),
	CROSS_STREET_DIRECTIONS VARCHAR2(50),
	EMAIL_ADDRESS VARCHAR2(50),
	CONTACT_EMAIL_ADDRESS VARCHAR2(50),
	VENDOR_ID VARCHAR2(60),
	FAXABLE VARCHAR2(1)
)
/
CREATE TABLE ESCRIBE.PRESCR_UPD_XT
( 
	COMM_GROUP_ID VARCHAR2(10),
	DEA_REGISTRATION_NUM VARCHAR2(13),
	DEA_NUM_RENEWAL_DATE NUMBER(8, 0),
	LAST_NAME VARCHAR2(25),
	PREVIOUS_LAST_NAME VARCHAR2(40),
	FIRST_NAME VARCHAR2(25),
	MIDDLE_NAME_INITIAL VARCHAR2(1),
	NAME_SUFFIX VARCHAR2(3),
	GENDER_CODE VARCHAR2(1),
	ORGANIZATION_NAME VARCHAR2(60),
	DEPARTMENT_MAIL_STOP VARCHAR2(40),
	PHYS_ADDRESS_LINE_1 VARCHAR2(30),
	PHYS_ADDRESS_LINE_2 VARCHAR2(30),
	PHYS_SUITE_APARTMENT_NUM VARCHAR2(8),
	PHYS_CITY_NAME VARCHAR2(20),
	PHYS_STATE_PROVINCE_CODE VARCHAR2(2),
	PHYS_ZIP_POSTAL_ZONE VARCHAR2(9),
	PHYS_COUNTRY_CODE VARCHAR2(3),
	PRIME_PHONE_NUM NUMBER(10, 0),
	SECOND_PHONE_NUM NUMBER(10, 0),
	REFILL_PHONE_NUM NUMBER(10, 0),
	FAX_NUM NUMBER(10, 0),
	EMAIL_IGNORED VARCHAR2(25),
	PRIME_DEGREE VARCHAR2(5),
	PRIME_TAXONOMY_CODE VARCHAR2(10),
	SECOND_DEGREE VARCHAR2(5),
	SECOND_TAXONOMY_CODE VARCHAR2(10),
	STATE_CODE_PRIME_MEDICAID_ID VARCHAR2(2),
	PRIME_MEDICAID_ID VARCHAR2(15),
	STATE_CODE_SECOND_MEDICAID_ID VARCHAR2(2),
	SECOND_MEDICAID_ID VARCHAR2(15),
	STATE_CODE_THIRD_MEDICAID_ID VARCHAR2(2),
	THIRD_MEDICAID_ID VARCHAR2(15),
	UPIN_NUM VARCHAR2(6),
	HIN_NUM VARCHAR2(15),
	HCID_LOCATION_CODE NUMBER(2, 0),
	DEA_STATUS_CODE VARCHAR2(1),
	RETIRE_DATE NUMBER(8, 0),
	DATA_SUPPLIER_REF_KEY_1 VARCHAR2(20),
	DATA_SUPPLIER_REF_KEY_2 VARCHAR2(20),
	DATA_SUPPLIER_REF_KEY_3 VARCHAR2(20),
	DATA_SUPPLIER_SITE_NUM VARCHAR2(15),
	NPI VARCHAR2(30),
	HCID_IDENTIFIER VARCHAR2(30),
	NHIN_PROVIDER_ID VARCHAR2(30),
	PHYS_LOCATION_TYPE_CODE VARCHAR2(2),
	DUPE_DEA_FLAG CHAR(1),
	DUPE_DATA_SUPPLIER_REF_KEY_1 VARCHAR2(20),
	COMM_SUB_GROUP_ID VARCHAR2(10),
	UPDATE_RECORD_TYPE_CODE VARCHAR2(1),
	DATE_LAST_CHANGE NUMBER(8, 0),
	DEA_REGISTRATION_NUM_SUFFIX VARCHAR2(7),
	DEA_DRUG_SCHEDULE VARCHAR2(12),
	NCPDP_PROVIDER_ID_NUM VARCHAR2(15),
	DUPE_DATA_SUPPLIER_REF_KEY_2 VARCHAR2(20),
	DUPE_DATA_SUPPLIER_REF_KEY_3 VARCHAR2(20),
	ORIGIN VARCHAR2(1),
	RESERVE_1 VARCHAR2(1),
	PREVIOUS_HCID VARCHAR2(15),
	REPLACEMENT_HCID VARCHAR2(15),
	HCID_DC_DATE NUMBER(8, 0),
	NHIN_DECEASED_FLAG VARCHAR2(1),
	NHIN_DECEASED_DATE NUMBER(8, 0),
	REPLACEMENT_DEA_NUM VARCHAR2(13),
	PREVIOUS_DEA_NUM VARCHAR2(13),
	DATA_ELEMENT_CHANGE_TYPE VARCHAR2(3),
	EMAIL_ADDRESS VARCHAR2(60),
	FILLER_1 VARCHAR2(60),
	PDX_RESERVE VARCHAR2(9),
	RESERVED VARCHAR2(4),
	STATE_LICENSE_1 VARCHAR2(20),
	LICENSING_STATE_1 VARCHAR2(2),
	STATE_LICENSE_2 VARCHAR2(20),
	LICENSING_STATE_2 VARCHAR2(2),
	STATE_LICENSE_3 VARCHAR2(20),
	LICENSING_STATE_3 VARCHAR2(2),
	NHIN_USE VARCHAR2(4),
	FILLER VARCHAR2(19)
)
/
CREATE TABLE ESCRIBE.PRESCR_UPD_XT_ORIG
( 
	COMM_GROUP_ID VARCHAR2(10),
	DEA_REGISTRATION_NUM VARCHAR2(13),
	DEA_NUM_RENEWAL_DATE NUMBER(8, 0),
	LAST_NAME VARCHAR2(25),
	PREVIOUS_LAST_NAME VARCHAR2(40),
	FIRST_NAME VARCHAR2(25),
	MIDDLE_NAME_INITIAL VARCHAR2(1),
	NAME_SUFFIX VARCHAR2(3),
	GENDER_CODE VARCHAR2(1),
	ORGANIZATION_NAME VARCHAR2(60),
	DEPARTMENT_MAIL_STOP VARCHAR2(40),
	PHYS_ADDRESS_LINE_1 VARCHAR2(30),
	PHYS_ADDRESS_LINE_2 VARCHAR2(30),
	PHYS_SUITE_APARTMENT_NUM VARCHAR2(8),
	PHYS_CITY_NAME VARCHAR2(20),
	PHYS_STATE_PROVINCE_CODE VARCHAR2(2),
	PHYS_ZIP_POSTAL_ZONE VARCHAR2(9),
	PHYS_COUNTRY_CODE VARCHAR2(3),
	PRIME_PHONE_NUM NUMBER(10, 0),
	SECOND_PHONE_NUM NUMBER(10, 0),
	REFILL_PHONE_NUM NUMBER(10, 0),
	FAX_NUM NUMBER(10, 0),
	EMAIL_ADDRESS VARCHAR2(25),
	PRIME_DEGREE VARCHAR2(5),
	PRIME_TAXONOMY_CODE VARCHAR2(10),
	SECOND_DEGREE VARCHAR2(5),
	SECOND_TAXONOMY_CODE VARCHAR2(10),
	STATE_CODE_PRIME_MEDICAID_ID VARCHAR2(2),
	PRIME_MEDICAID_ID VARCHAR2(15),
	STATE_CODE_SECOND_MEDICAID_ID VARCHAR2(2),
	SECOND_MEDICAID_ID VARCHAR2(15),
	STATE_CODE_THIRD_MEDICAID_ID VARCHAR2(2),
	THIRD_MEDICAID_ID VARCHAR2(15),
	UPIN_NUM VARCHAR2(6),
	HIN_NUM VARCHAR2(15),
	HCID_LOCATION_CODE NUMBER(2, 0),
	DEA_STATUS_CODE VARCHAR2(1),
	RETIRE_DATE NUMBER(8, 0),
	DATA_SUPPLIER_REF_KEY_1 VARCHAR2(20),
	DATA_SUPPLIER_REF_KEY_2 VARCHAR2(20),
	DATA_SUPPLIER_REF_KEY_3 VARCHAR2(20),
	DATA_SUPPLIER_SITE_NUM VARCHAR2(15),
	NPI VARCHAR2(30),
	HCID_IDENTIFIER VARCHAR2(30),
	NHIN_PROVIDER_ID VARCHAR2(30),
	PHYS_LOCATION_TYPE_CODE VARCHAR2(2),
	DUPE_DEA_FLAG CHAR(1),
	DUPE_DATA_SUPPLIER_REF_KEY_1 VARCHAR2(20),
	COMM_SUB_GROUP_ID VARCHAR2(10),
	UPDATE_RECORD_TYPE_CODE VARCHAR2(1),
	DATE_LAST_CHANGE NUMBER(8, 0),
	DEA_REGISTRATION_NUM_SUFFIX VARCHAR2(7),
	DEA_DRUG_SCHEDULE VARCHAR2(12),
	NCPDP_PROVIDER_ID_NUM VARCHAR2(15),
	DUPE_DATA_SUPPLIER_REF_KEY_2 VARCHAR2(20),
	DUPE_DATA_SUPPLIER_REF_KEY_3 VARCHAR2(20),
	ORIGIN VARCHAR2(1),
	RESERVE_1 VARCHAR2(1),
	PREVIOUS_HCID VARCHAR2(15),
	REPLACEMENT_HCID VARCHAR2(15),
	HCID_DC_DATE NUMBER(8, 0),
	NHIN_DECEASED_FLAG VARCHAR2(1),
	NHIN_DECEASED_DATE NUMBER(8, 0),
	REPLACEMENT_DEA_NUM VARCHAR2(13),
	PREVIOUS_DEA_NUM VARCHAR2(13),
	DATA_ELEMENT_CHANGE_TYPE VARCHAR2(3),
	RESERVED VARCHAR2(4),
	STATE_LICENSE_1 VARCHAR2(20),
	LICENSING_STATE_1 VARCHAR2(3),
	STATE_LICENSE_2 VARCHAR2(20),
	LICENSING_STATE_2 VARCHAR2(3),
	STATE_LICENSE_3 VARCHAR2(20),
	LICENSING_STATE_3 VARCHAR2(3),
	FILLER VARCHAR2(149)
)
/
CREATE TABLE ESCRIBE.PRESCRIBER_DRUG_USAGE
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_NHIN_PRESCRIBER NUMBER(38, 0) NOT NULL,
	DDID NUMBER(38, 0) NOT NULL,
	DATE_USED DATE,
	DRUG_NAME VARCHAR2(70) NOT NULL,
	STRENGTH VARCHAR2(15),
	STRENGTH_UNIT VARCHAR2(10),
	DOSING_UNIT VARCHAR2(20),
	SIG_VERB VARCHAR2(60),
	SIG_UNIT VARCHAR2(60),
	SIG_UNITS VARCHAR2(60),
	SIG_ROUTE VARCHAR2(60)
)
/
CREATE TABLE ESCRIBE.PRESCRIBER_MEDICAID
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_NHIN_PRESCRIBER NUMBER(38, 0) NOT NULL,
	STATE VARCHAR2(2) NOT NULL,
	MEDICAID_ID VARCHAR2(15) NOT NULL,
	DEACTIVATE_DATE DATE
)
/
CREATE TABLE ESCRIBE.PRESCRIBER_MEDICAID_UPD_ERR
( 
	ID NUMBER(38, 0),
	ID_NHIN_PRESCRIBER NUMBER(38, 0),
	STATE VARCHAR2(2),
	MEDICAID_ID VARCHAR2(15),
	DEACTIVATE_DATE DATE
)
/
CREATE TABLE ESCRIBE.PRESCRIBER_PHARMACY_USAGE
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_NHIN_PRESCRIBER NUMBER(38, 0) NOT NULL,
	ID_PHARMACY NUMBER(38, 0) NOT NULL,
	DATE_USED DATE,
	PHARMACY_NAME VARCHAR2(150) NOT NULL
)
/
CREATE TABLE ESCRIBE.PRESCRIBER_PIN_MAILING
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_NHIN_PRESCRIBER NUMBER(38, 0) NOT NULL,
	LAST_DATE_PRINTED DATE,
	NUMBER_OF_PRINTS NUMBER(2, 0)
)
/
CREATE TABLE ESCRIBE.PRESCRIBER_STATE
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_NHIN_PRESCRIBER NUMBER(38, 0) NOT NULL,
	STATE VARCHAR2(2) NOT NULL,
	STATE_LICENSE_ID VARCHAR2(15),
	OTHER_STATE_ID_TYPE NUMBER(1, 0),
	OTHER_STATE_ID VARCHAR2(20),
	DEACTIVATION_DATE DATE
)
/
CREATE TABLE ESCRIBE.PRESCRIBER_STATE_UPD_ERR
( 
	ID NUMBER(38, 0),
	ID_NHIN_PRESCRIBER NUMBER(38, 0),
	STATE VARCHAR2(2),
	STATE_LICENSE_ID VARCHAR2(15),
	OTHER_STATE_ID_TYPE NUMBER(1, 0),
	OTHER_STATE_ID VARCHAR2(20),
	DEACTIVATION_DATE DATE
)
/
CREATE TABLE ESCRIBE.PRESCRIBER_UPDATE_ERROR
( 
	COMM_GROUP_ID VARCHAR2(10),
	DEA_REGISTRATION_NUM VARCHAR2(13),
	DEA_NUM_RENEWAL_DATE NUMBER(8, 0),
	LAST_NAME VARCHAR2(25),
	PREVIOUS_LAST_NAME VARCHAR2(40),
	FIRST_NAME VARCHAR2(25),
	MIDDLE_NAME_INITIAL VARCHAR2(1),
	NAME_SUFFIX VARCHAR2(3),
	GENDER_CODE VARCHAR2(1),
	ORGANIZATION_NAME VARCHAR2(60),
	DEPARTMENT_MAIL_STOP VARCHAR2(40),
	PHYS_ADDRESS_LINE_1 VARCHAR2(30),
	PHYS_ADDRESS_LINE_2 VARCHAR2(30),
	PHYS_SUITE_APARTMENT_NUM VARCHAR2(8),
	PHYS_CITY_NAME VARCHAR2(20),
	PHYS_STATE_PROVINCE_CODE VARCHAR2(2),
	PHYS_ZIP_POSTAL_ZONE VARCHAR2(9),
	PHYS_COUNTRY_CODE VARCHAR2(3),
	PRIME_PHONE_NUM NUMBER(10, 0),
	SECOND_PHONE_NUM NUMBER(10, 0),
	REFILL_PHONE_NUM NUMBER(10, 0),
	FAX_NUM NUMBER(10, 0),
	EMAIL_IGNORED VARCHAR2(25),
	PRIME_DEGREE VARCHAR2(5),
	PRIME_TAXONOMY_CODE VARCHAR2(10),
	SECOND_DEGREE VARCHAR2(5),
	SECOND_TAXONOMY_CODE VARCHAR2(10),
	STATE_CODE_PRIME_MEDICAID_ID VARCHAR2(2),
	PRIME_MEDICAID_ID VARCHAR2(15),
	STATE_CODE_SECOND_MEDICAID_ID VARCHAR2(2),
	SECOND_MEDICAID_ID VARCHAR2(15),
	STATE_CODE_THIRD_MEDICAID_ID VARCHAR2(2),
	THIRD_MEDICAID_ID VARCHAR2(15),
	UPIN_NUM VARCHAR2(6),
	HIN_NUM VARCHAR2(15),
	HCID_LOCATION_CODE NUMBER(2, 0),
	DEA_STATUS_CODE VARCHAR2(1),
	RETIRE_DATE NUMBER(8, 0),
	DATA_SUPPLIER_REF_KEY_1 VARCHAR2(20),
	DATA_SUPPLIER_REF_KEY_2 VARCHAR2(20),
	DATA_SUPPLIER_REF_KEY_3 VARCHAR2(20),
	DATA_SUPPLIER_SITE_NUM VARCHAR2(15),
	NPI VARCHAR2(30),
	HCID_IDENTIFIER VARCHAR2(30),
	NHIN_PROVIDER_ID VARCHAR2(30),
	PHYS_LOCATION_TYPE_CODE VARCHAR2(2),
	DUPE_DEA_FLAG CHAR(1),
	DUPE_DATA_SUPPLIER_REF_KEY_1 VARCHAR2(20),
	COMM_SUB_GROUP_ID VARCHAR2(10),
	UPDATE_RECORD_TYPE_CODE VARCHAR2(1),
	DATE_LAST_CHANGE NUMBER(8, 0),
	DEA_REGISTRATION_NUM_SUFFIX VARCHAR2(7),
	DEA_DRUG_SCHEDULE VARCHAR2(12),
	NCPDP_PROVIDER_ID_NUM VARCHAR2(15),
	DUPE_DATA_SUPPLIER_REF_KEY_2 VARCHAR2(20),
	DUPE_DATA_SUPPLIER_REF_KEY_3 VARCHAR2(20),
	ORIGIN VARCHAR2(1),
	RESERVE_1 VARCHAR2(1),
	PREVIOUS_HCID VARCHAR2(15),
	REPLACEMENT_HCID VARCHAR2(15),
	HCID_DC_DATE NUMBER(8, 0),
	NHIN_DECEASED_FLAG VARCHAR2(1),
	NHIN_DECEASED_DATE NUMBER(8, 0),
	REPLACEMENT_DEA_NUM VARCHAR2(13),
	PREVIOUS_DEA_NUM VARCHAR2(13),
	DATA_ELEMENT_CHANGE_TYPE VARCHAR2(3),
	EMAIL_ADDRESS VARCHAR2(60),
	FILLER_1 VARCHAR2(60),
	PDX_RESERVE VARCHAR2(9),
	RESERVED VARCHAR2(4),
	STATE_LICENSE_1 VARCHAR2(20),
	LICENSING_STATE_1 VARCHAR2(2),
	STATE_LICENSE_2 VARCHAR2(20),
	LICENSING_STATE_2 VARCHAR2(2),
	STATE_LICENSE_3 VARCHAR2(20),
	LICENSING_STATE_3 VARCHAR2(2),
	NHIN_USE VARCHAR2(4),
	FILLER VARCHAR2(19)
)
/
CREATE TABLE ESCRIBE.PRESCRIBER_UPDATE_ERROR_ORIG
( 
	COMM_GROUP_ID VARCHAR2(10),
	DEA_REGISTRATION_NUM VARCHAR2(13),
	DEA_NUM_RENEWAL_DATE NUMBER(8, 0),
	LAST_NAME VARCHAR2(25),
	PREVIOUS_LAST_NAME VARCHAR2(40),
	FIRST_NAME VARCHAR2(25),
	MIDDLE_NAME_INITIAL VARCHAR2(1),
	NAME_SUFFIX VARCHAR2(3),
	GENDER_CODE VARCHAR2(1),
	ORGANIZATION_NAME VARCHAR2(60),
	DEPARTMENT_MAIL_STOP VARCHAR2(40),
	PHYS_ADDRESS_LINE_1 VARCHAR2(30),
	PHYS_ADDRESS_LINE_2 VARCHAR2(30),
	PHYS_SUITE_APARTMENT_NUM VARCHAR2(8),
	PHYS_CITY_NAME VARCHAR2(20),
	PHYS_STATE_PROVINCE_CODE VARCHAR2(2),
	PHYS_ZIP_POSTAL_ZONE VARCHAR2(9),
	PHYS_COUNTRY_CODE VARCHAR2(3),
	PRIME_PHONE_NUM NUMBER(10, 0),
	SECOND_PHONE_NUM NUMBER(10, 0),
	REFILL_PHONE_NUM NUMBER(10, 0),
	FAX_NUM NUMBER(10, 0),
	EMAIL_ADDRESS VARCHAR2(25),
	PRIME_DEGREE VARCHAR2(5),
	PRIME_TAXONOMY_CODE VARCHAR2(10),
	SECOND_DEGREE VARCHAR2(5),
	SECOND_TAXONOMY_CODE VARCHAR2(10),
	STATE_CODE_PRIME_MEDICAID_ID VARCHAR2(2),
	PRIME_MEDICAID_ID VARCHAR2(15),
	STATE_CODE_SECOND_MEDICAID_ID VARCHAR2(2),
	SECOND_MEDICAID_ID VARCHAR2(15),
	STATE_CODE_THIRD_MEDICAID_ID VARCHAR2(2),
	THIRD_MEDICAID_ID VARCHAR2(15),
	UPIN_NUM VARCHAR2(6),
	HIN_NUM VARCHAR2(15),
	HCID_LOCATION_CODE NUMBER(2, 0),
	DEA_STATUS_CODE VARCHAR2(1),
	RETIRE_DATE NUMBER(8, 0),
	DATA_SUPPLIER_REF_KEY_1 VARCHAR2(20),
	DATA_SUPPLIER_REF_KEY_2 VARCHAR2(20),
	DATA_SUPPLIER_REF_KEY_3 VARCHAR2(20),
	DATA_SUPPLIER_SITE_NUM VARCHAR2(15),
	NPI VARCHAR2(30),
	HCID_IDENTIFIER VARCHAR2(30),
	NHIN_PROVIDER_ID VARCHAR2(30),
	PHYS_LOCATION_TYPE_CODE VARCHAR2(2),
	DUPE_DEA_FLAG CHAR(1),
	DUPE_DATA_SUPPLIER_REF_KEY_1 VARCHAR2(20),
	COMM_SUB_GROUP_ID VARCHAR2(10),
	UPDATE_RECORD_TYPE_CODE VARCHAR2(1),
	DATE_LAST_CHANGE NUMBER(8, 0),
	DEA_REGISTRATION_NUM_SUFFIX VARCHAR2(7),
	DEA_DRUG_SCHEDULE VARCHAR2(12),
	NCPDP_PROVIDER_ID_NUM VARCHAR2(15),
	DUPE_DATA_SUPPLIER_REF_KEY_2 VARCHAR2(20),
	DUPE_DATA_SUPPLIER_REF_KEY_3 VARCHAR2(20),
	ORIGIN VARCHAR2(1),
	RESERVE_1 VARCHAR2(1),
	PREVIOUS_HCID VARCHAR2(15),
	REPLACEMENT_HCID VARCHAR2(15),
	HCID_DC_DATE NUMBER(8, 0),
	NHIN_DECEASED_FLAG VARCHAR2(1),
	NHIN_DECEASED_DATE NUMBER(8, 0),
	REPLACEMENT_DEA_NUM VARCHAR2(13),
	PREVIOUS_DEA_NUM VARCHAR2(13),
	DATA_ELEMENT_CHANGE_TYPE VARCHAR2(3),
	RESERVED VARCHAR2(4),
	STATE_LICENSE_1 VARCHAR2(20),
	LICENSING_STATE_1 VARCHAR2(3),
	STATE_LICENSE_2 VARCHAR2(20),
	LICENSING_STATE_2 VARCHAR2(3),
	STATE_LICENSE_3 VARCHAR2(20),
	LICENSING_STATE_3 VARCHAR2(3),
	FILLER VARCHAR2(149)
)
/
CREATE TABLE ESCRIBE.PRESCRIPTIONS_WRITTEN
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_NHIN_PRESCRIBER_CLINIC_LINK NUMBER(38, 0) NOT NULL,
	ID_PHARMACY NUMBER(38, 0),
	RX_COM_ID NUMBER(38, 0),
	TRANSACTION_NUMBER NUMBER(15, 0) NOT NULL,
	SCRIPT_MESSAGE BLOB,
	PATIENT_LAST_NAME VARCHAR2(35) NOT NULL,
	PATIENT_FIRST_NAME VARCHAR2(35) NOT NULL,
	PRESCRIPTION_WRITTEN_BY VARCHAR2(20) NOT NULL,
	DATE_SENT DATE NOT NULL,
	PATIENT_DATE_OF_BIRTH DATE NOT NULL,
	PATIENT_PHONE NUMBER(10, 0) NOT NULL,
	PATIENT_ADDRESS VARCHAR2(35) NOT NULL,
	PATIENT_CITY VARCHAR2(35) NOT NULL,
	PATIENT_STATE VARCHAR2(2) NOT NULL,
	PATIENT_ZIP VARCHAR2(15) NOT NULL,
	PRESCRIBED_QUANTITY NUMBER(13, 2) NOT NULL,
	SIG_TEXT VARCHAR2(255) NOT NULL,
	DISPENSE_AS_WRITTEN VARCHAR2(1) NOT NULL,
	PRESCRIBED_DRUG_NAME VARCHAR2(255),
	DELIVERY_METHOD VARCHAR2(1),
	EMAIL_NOTIFICATION_STATUS VARCHAR2(1),
	REFILLS_AUTHORIZED VARCHAR2(5),
	DDID NUMBER(10, 0) NOT NULL,
	DELIVERY_STATUS VARCHAR2(1),
	PATIENT_GENDER VARCHAR2(1),
	ID_MANUFACTURER_PROGRAM NUMBER(38, 0),
	PATIENT_ADDRESS_LINE_2 VARCHAR2(35),
	SOFTWARE_USED VARCHAR2(20),
	SOFTWARE_VERSION VARCHAR2(10),
	SYS_NC00031$ DATE GENERATED ALWAYS AS (TRUNC("DATE_SENT")) VIRTUAL 
)
/
CREATE TABLE ESCRIBE.PROGRAM_NDC_SHIP_OPTION_LINK
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_SHIPPING_OPTION NUMBER(38, 0) NOT NULL,
	ID_MFR_PROGRAM_NDC_LINK NUMBER(38, 0) NOT NULL,
	SHIPPING_RATE NUMBER(13, 2) NOT NULL
)
/
CREATE TABLE ESCRIBE.PROGRAM_SHIPPING_OPTION_LINK
( 
	ID NUMBER(38, 0) NOT NULL,
	ID_SHIPPING_OPTION NUMBER(38, 0) NOT NULL,
	ID_MANUFACTURER_PROGRAM NUMBER(38, 0) NOT NULL,
	SHIPPING_RATE NUMBER(13, 2) NOT NULL
)
/
CREATE TABLE ESCRIBE.REJECT_CODES
( 
	ID NUMBER(38, 0) NOT NULL,
	REJECT_CODE VARCHAR2(3) NOT NULL,
	REJECT_DESCRIPTION VARCHAR2(255) NOT NULL
)
/
CREATE TABLE ESCRIBE.SHIPPING_OPTION
( 
	ID NUMBER(38, 0) NOT NULL,
	SHIPPING_TYPE NUMBER(1, 0) NOT NULL,
	DESCRIPTION VARCHAR2(120),
	SHIPPING_OPTION_NOTE VARCHAR2(120)
)
/
CREATE TABLE ESCRIBE.SIG_TEXT_MASTER
( 
	ID NUMBER(38, 0) NOT NULL,
	DOSAGE_FORM VARCHAR2(10),
	ROUTE_CODE VARCHAR2(10),
	SIG_VERB VARCHAR2(60),
	SIG_UNIT VARCHAR2(60),
	SIG_UNITS VARCHAR2(60),
	SIG_ROUTE VARCHAR2(60),
	LANG VARCHAR2(2) NOT NULL
)
/
CREATE TABLE ESCRIBE.STANDARD_SIGS
( 
	ID NUMBER(38, 0) NOT NULL,
	SIG_CODE VARCHAR2(10) NOT NULL,
	SIG_TEXT VARCHAR2(255) NOT NULL,
	DISPLAY_ORDER NUMBER(2, 0)
)
/
CREATE TABLE ESCRIBE.SUPPORT_USER
( 
	ID NUMBER(38, 0) NOT NULL,
	USERNAME VARCHAR2(20) NOT NULL,
	LAST_NAME VARCHAR2(25) NOT NULL,
	FIRST_NAME VARCHAR2(25) NOT NULL,
	EMPLOYEE_ID VARCHAR2(10),
	EMAIL_ADDRESS VARCHAR2(120),
	PASSWORD VARCHAR2(32),
	INACTIVE NUMBER(1, 0)
)
/
CREATE TABLE ESCRIBE.TEMP_PHARMACY
( 
	ID NUMBER(38, 0) NOT NULL,
	NCPDP_NUMBER VARCHAR2(7) NOT NULL,
	ID_ADDRESS NUMBER(38, 0) NOT NULL,
	PHARMACY_NAME VARCHAR2(60) NOT NULL,
	NHIN_STORE_ID NUMBER(10, 0),
	STORE_NUMBER VARCHAR2(10),
	PHARMACY_DBA_NAME VARCHAR2(60),
	DEA_ID VARCHAR2(15),
	ID_MAILING_ADDRESS NUMBER(38, 0),
	PHONE_NUMBER NUMBER(10, 0),
	FAX_PHONE NUMBER(10, 0),
	DATE_OPENED DATE,
	DATE_CLOSED DATE,
	DEACTIVATED DATE,
	ACCEPTS_ESCRIPTS CHAR(1),
	DELIVERY_SERVICE CHAR(1),
	COMPOUNDING_SERVICE CHAR(1),
	DRIVE_UP_WINDOW CHAR(1),
	SELLS_DME_EQUIPMENT CHAR(1),
	HANDICAP_ACCESSIBLE CHAR(1),
	OPEN_24_HOUR CHAR(1),
	STATE_TAX_ID VARCHAR2(15),
	FEDERAL_TAX_ID VARCHAR2(15),
	STATE_LICENSE_NUMBER VARCHAR2(20),
	DISPENSER_CLASS_CODE VARCHAR2(2),
	DISPENSER_TYPE_CODE_1 VARCHAR2(2),
	DISPENSER_TYPE_CODE_2 VARCHAR2(2),
	DISPENSER_TYPE_CODE_3 VARCHAR2(2),
	LANGUAGE_CODE_1 VARCHAR2(2),
	LANGUAGE_CODE_2 VARCHAR2(2),
	LANGUAGE_CODE_3 VARCHAR2(2),
	LANGUAGE_CODE_4 VARCHAR2(2),
	LANGUAGE_CODE_5 VARCHAR2(2),
	CONGRESSIONAL_VOTING_DISTRICT VARCHAR2(4),
	FIPS_MSA_CODE VARCHAR2(4),
	FIPS_PMSA_CODE VARCHAR2(4),
	FIPS_COUNTY_CODE VARCHAR2(5),
	CONTACT_FIRST_NAME VARCHAR2(20),
	CONTACT_MIDDLE_INITIAL VARCHAR2(1),
	CONTACT_LAST_NAME VARCHAR2(20),
	CONTACT_TITLE VARCHAR2(30),
	CONTACT_PHONE_NUMBER VARCHAR2(10),
	CONTACT_PHONE_EXT VARCHAR2(5),
	UPIN VARCHAR2(10),
	NPI VARCHAR2(15),
	PHARMACY_HOURS VARCHAR2(35),
	CROSS_STREET_DIRECTIONS VARCHAR2(50),
	EMAIL_ADDRESS VARCHAR2(50),
	CONTACT_EMAIL_ADDRESS VARCHAR2(50),
	VENDOR_ID VARCHAR2(60),
	FAXABLE VARCHAR2(1)
)
/
ALTER TABLE ESCRIBE.ADDRESS ADD CONSTRAINT ADDRESS_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.APP_ROLE ADD CONSTRAINT APP_ROLE_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.APP_USER ADD CONSTRAINT AP_USER_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.APP_USER ADD CONSTRAINT AP_USER_USERNAME_UNIQUE
	UNIQUE (USERNAME)
/
ALTER TABLE ESCRIBE.AUDIT_DATES ADD CONSTRAINT AUDIT_DATES_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.BILLING_SERVICES ADD CONSTRAINT BILLING_SERVICES_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.CLAIM_HISTORY ADD CONSTRAINT CLAIM_HISTORY_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.CLAIM_PROCESSOR ADD CONSTRAINT CLAIM_PROCESSOR_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.CLAIM_PROCESSOR ADD CONSTRAINT CLAIM_PROC_UNQ_CLAIM_PROC_CODE
	UNIQUE (CLAIM_PROCESSOR_CODE)
/
ALTER TABLE ESCRIBE.CPR_LINK_AUDIT ADD CONSTRAINT CPR_LINK_AUDIT_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.CUSTOM_SIGS ADD CONSTRAINT CUSTOMER_SIGS_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.DRUG ADD CONSTRAINT DRUG_NDC_UNQ
	UNIQUE (NDC)
/
ALTER TABLE ESCRIBE.DRUG ADD CONSTRAINT DRUG_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.FAILED_MESSAGES ADD CONSTRAINT FAILED_MESSAGES_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.INSURANCE_PLAN ADD CONSTRAINT INSURANCE_PLAN_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.MANUFACTURER_PROGRAM ADD CONSTRAINT MANUFACTURER_PROGRAM_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.MFR_PROGRAM_NDC_LINK ADD CONSTRAINT MFR_PROGRAM_NDC_LINK_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.MFR_PROGRAM_PHARMACY_LINK ADD CONSTRAINT MFR_PROGRAM_PHARMACY_LINK_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.NCPDP_MESSAGES ADD CONSTRAINT NCPDP_MESSAGES_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.NHIN_CLINIC ADD CONSTRAINT NHIN_CLINIC_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.NHIN_PRESCRIBER ADD CONSTRAINT NHIN_PRESCRIBER_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.NHIN_PRESCRIBER_CLINIC_LINK ADD CONSTRAINT NHIN_PRESCR_CLINIC_LINK_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.ORDER_INFO ADD CONSTRAINT ORDER_INFO_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.ORDER_INFO_BK ADD CONSTRAINT ORDER_INFO_BK_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.PHARMACY ADD CONSTRAINT PHARMACY_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.PHARMACY_MEDICAID_IDS ADD CONSTRAINT PHARM_MEDICAID_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.PRESCRIBER_DRUG_USAGE ADD CONSTRAINT PRESCRIBER_DRUG_USAGE_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.PRESCRIBER_MEDICAID ADD CONSTRAINT PRESCRIBER_MEDICAID_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.PRESCRIBER_PHARMACY_USAGE ADD CONSTRAINT PRESRIBER_PHARMACY_USAGE_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.PRESCRIBER_PIN_MAILING ADD CONSTRAINT PRESCRIBER_PIN_MAILING_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.PRESCRIBER_STATE ADD CONSTRAINT PRESCRIBER_STATE_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.PRESCRIPTIONS_WRITTEN ADD CONSTRAINT PRESCRIPTIONS_WRITTEN_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.PROGRAM_NDC_SHIP_OPTION_LINK ADD CONSTRAINT PROGRAM_NDC_SHIP_OPTION_LNK_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.PROGRAM_SHIPPING_OPTION_LINK ADD CONSTRAINT PROGRAM_SHIPPING_OPTION_LNK_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.REJECT_CODES ADD CONSTRAINT REJECT_CODES_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.REJECT_CODES ADD CONSTRAINT REJECT_CODES_UNQ_REJECT_CODE
	UNIQUE (REJECT_CODE)
/
ALTER TABLE ESCRIBE.SHIPPING_OPTION ADD CONSTRAINT SHIPPING_OPTION_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.SIG_TEXT_MASTER ADD CONSTRAINT SIG_TEXT_MASTER_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.STANDARD_SIGS ADD CONSTRAINT STANDARD_SIGS_ID_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.SUPPORT_USER ADD CONSTRAINT SUPPORT_USER_PK
	PRIMARY KEY (ID)
/
ALTER TABLE ESCRIBE.APP_USER ADD CONSTRAINT AP_USER_ID_NHIN_PRESRIBER_FK
	FOREIGN KEY (ID_NHIN_PRESCRIBER)
		REFERENCES ESCRIBE.NHIN_PRESCRIBER (ID)
/
ALTER TABLE ESCRIBE.APP_USER_ROLE ADD CONSTRAINT APP_USER_ROLE_ID_APP_ROLE_FK
	FOREIGN KEY (ID_APP_ROLE)
		REFERENCES ESCRIBE.APP_ROLE (ID)
/
ALTER TABLE ESCRIBE.APP_USER_ROLE ADD CONSTRAINT APP_USER_ROLE_ID_APP_USER_FK
	FOREIGN KEY (ID_APP_USER)
		REFERENCES ESCRIBE.APP_USER (ID)
/
ALTER TABLE ESCRIBE.CLAIM_HISTORY ADD CONSTRAINT CLAIN_HST_NHIN_PRESCRIBER_FK
	FOREIGN KEY (ID_NHIN_PRESCRIBER)
		REFERENCES ESCRIBE.NHIN_PRESCRIBER (ID)
/
ALTER TABLE ESCRIBE.CLAIM_HISTORY ADD CONSTRAINT CLAIM_HST_NCPDP_MSG_FK
	FOREIGN KEY (ID_NCPDP_MESSAGE_CLAIM)
		REFERENCES ESCRIBE.NCPDP_MESSAGES (ID)
/
ALTER TABLE ESCRIBE.CLAIM_HISTORY ADD CONSTRAINT CLAIM_HST_NCPDP_MSG_RESP_FK
	FOREIGN KEY (ID_NCPDP_MESSAGE_CLAIM_RESP)
		REFERENCES ESCRIBE.NCPDP_MESSAGES (ID)
/
ALTER TABLE ESCRIBE.CLAIM_HISTORY ADD CONSTRAINT CLAIM_HST_NCPDP_MSG_REV_FK
	FOREIGN KEY (ID_NCPDP_MESSAGE_REVERSE)
		REFERENCES ESCRIBE.NCPDP_MESSAGES (ID)
/
ALTER TABLE ESCRIBE.CLAIM_HISTORY ADD CONSTRAINT CLAIM_HST_NCPDP_MSG_REV_RES_FK
	FOREIGN KEY (ID_NCPDP_MESSAGE_REVERSE_RESP)
		REFERENCES ESCRIBE.NCPDP_MESSAGES (ID)
/
ALTER TABLE ESCRIBE.CUSTOM_SIGS ADD CONSTRAINT CUSTOM_SIGS_ID_NHIN_PRESCR_FK
	FOREIGN KEY (ID_NHIN_PRESCRIBER)
		REFERENCES ESCRIBE.NHIN_PRESCRIBER (ID)
/
ALTER TABLE ESCRIBE.MFR_PROGRAM_NDC_LINK ADD CONSTRAINT MFR_PROG_NDC_LNK_MFR_PROG_FK
	FOREIGN KEY (ID_MANUFACTURER_PROGRAM)
		REFERENCES ESCRIBE.MANUFACTURER_PROGRAM (ID)
/
ALTER TABLE ESCRIBE.MFR_PROGRAM_PHARMACY_LINK ADD CONSTRAINT MFR_PROG_PHARM_LNK_MFR_PROG_FK
	FOREIGN KEY (ID_MANUFACTURER_PROGRAM)
		REFERENCES ESCRIBE.MANUFACTURER_PROGRAM (ID)
/
ALTER TABLE ESCRIBE.NHIN_CLINIC ADD CONSTRAINT NHIN_CLINIC_ID_ADDRESS_FK
	FOREIGN KEY (ID_ADDRESS)
		REFERENCES ESCRIBE.ADDRESS (ID)
/
ALTER TABLE ESCRIBE.NHIN_PRESCRIBER ADD CONSTRAINT NHIN_PRESCR_REGISTR_ADDRESS_FK
	FOREIGN KEY (ID_REGISTRATION_ADDRESS)
		REFERENCES ESCRIBE.ADDRESS (ID)
/
ALTER TABLE ESCRIBE.NHIN_PRESCRIBER_CLINIC_LINK ADD CONSTRAINT NHIN_PRE_CLN_LK_ID_NHIN_CLN_FK
	FOREIGN KEY (ID_NHIN_CLINIC)
		REFERENCES ESCRIBE.NHIN_CLINIC (ID)
/
ALTER TABLE ESCRIBE.NHIN_PRESCRIBER_CLINIC_LINK ADD CONSTRAINT NHIN_PRE_CLN_LK_ID_PRESCR_FK
	FOREIGN KEY (ID_NHIN_PRESCRIBER)
		REFERENCES ESCRIBE.NHIN_PRESCRIBER (ID)
/
ALTER TABLE ESCRIBE.ORDER_INFO ADD CONSTRAINT ORDER_INFO_FK_PRESCWRT
	FOREIGN KEY (ID_PRESCRIPTIONS_WRITTEN)
		REFERENCES ESCRIBE.PRESCRIPTIONS_WRITTEN (ID)
/
ALTER TABLE ESCRIBE.PASSWORD_HISTORY ADD CONSTRAINT PASSWRD_HISTORY_ID_APP_USER_FK
	FOREIGN KEY (ID_APP_USER)
		REFERENCES ESCRIBE.APP_USER (ID)
/
ALTER TABLE ESCRIBE.PHARMACY ADD CONSTRAINT PHARMACY_ID_ADDRESS_FK
	FOREIGN KEY (ID_ADDRESS)
		REFERENCES ESCRIBE.ADDRESS (ID)
/
ALTER TABLE ESCRIBE.PHARMACY_MEDICAID_IDS ADD CONSTRAINT PHARM_MEDICAID_ID_ID_PHARM_FK
	FOREIGN KEY (ID_PHARMACY)
		REFERENCES ESCRIBE.PHARMACY (ID)
/
ALTER TABLE ESCRIBE.PRESCRIBER_DRUG_USAGE ADD CONSTRAINT PRES_DRUG_USE_ID_NHIN_PRES_FK
	FOREIGN KEY (ID_NHIN_PRESCRIBER)
		REFERENCES ESCRIBE.NHIN_PRESCRIBER (ID)
/
ALTER TABLE ESCRIBE.PRESCRIBER_PHARMACY_USAGE ADD CONSTRAINT PRES_PHARM_USE_ID_NHIN_PRES_FK
	FOREIGN KEY (ID_NHIN_PRESCRIBER)
		REFERENCES ESCRIBE.NHIN_PRESCRIBER (ID)
/
ALTER TABLE ESCRIBE.PRESCRIBER_PHARMACY_USAGE ADD CONSTRAINT PRES_PHARM_USE_ID_PHARMACY_FK
	FOREIGN KEY (ID_PHARMACY)
		REFERENCES ESCRIBE.PHARMACY (ID)
/
ALTER TABLE ESCRIBE.PRESCRIBER_STATE ADD CONSTRAINT PRESCR_STATE_ID_NHIN_PRESCR_FK
	FOREIGN KEY (ID_NHIN_PRESCRIBER)
		REFERENCES ESCRIBE.NHIN_PRESCRIBER (ID)
/
ALTER TABLE ESCRIBE.PRESCRIPTIONS_WRITTEN ADD CONSTRAINT PRESC_WRIT_ID_PRESC_CLN_LNK_FK
	FOREIGN KEY (ID_NHIN_PRESCRIBER_CLINIC_LINK)
		REFERENCES ESCRIBE.NHIN_PRESCRIBER_CLINIC_LINK (ID)
/
ALTER TABLE ESCRIBE.PRESCRIPTIONS_WRITTEN ADD CONSTRAINT PRESC_WRIT_ID_PHARMACY_FK
	FOREIGN KEY (ID_PHARMACY)
		REFERENCES ESCRIBE.PHARMACY (ID)
/
ALTER TABLE ESCRIBE.PROGRAM_NDC_SHIP_OPTION_LINK ADD CONSTRAINT PRG_NDC_SHP_OPT_MFR_PRG_NDC_FK
	FOREIGN KEY (ID_MFR_PROGRAM_NDC_LINK)
		REFERENCES ESCRIBE.MFR_PROGRAM_NDC_LINK (ID)
/
ALTER TABLE ESCRIBE.PROGRAM_NDC_SHIP_OPTION_LINK ADD CONSTRAINT PRG_NDC_SHP_OPT_LNK_MFR_PRG_FK
	FOREIGN KEY (ID_SHIPPING_OPTION)
		REFERENCES ESCRIBE.MANUFACTURER_PROGRAM (ID)
/
ALTER TABLE ESCRIBE.PROGRAM_SHIPPING_OPTION_LINK ADD CONSTRAINT PROG_SHIP_OPT_LNK_MFR_PROG_FK
	FOREIGN KEY (ID_MANUFACTURER_PROGRAM)
		REFERENCES ESCRIBE.MANUFACTURER_PROGRAM (ID)
/
ALTER TABLE ESCRIBE.PROGRAM_SHIPPING_OPTION_LINK ADD CONSTRAINT PROG_SHIP_OPT_LNK_SHIP_OPT_FK
	FOREIGN KEY (ID_SHIPPING_OPTION)
		REFERENCES ESCRIBE.SHIPPING_OPTION (ID)
/
CREATE INDEX ESCRIBE.ADDRESS_CITY_STATE_ZIP_INDX ON ESCRIBE.ADDRESS
(
	CITY,
	STATE,
	ZIP_CODE
)
/
CREATE INDEX ESCRIBE.ADDRESS_INDX1 ON ESCRIBE.ADDRESS
(
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	DEPARTMENT_MAIL_STOP,
	CITY,
	STATE,
	ZIP_CODE,
	COUNTRY
)
/
CREATE INDEX ESCRIBE.ADDRESS_INDX2 ON ESCRIBE.ADDRESS
(
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	SUBSTR("ZIP_CODE",1,5)
)
/
CREATE INDEX ESCRIBE.ADDRESS_STATE_ZIP_INDX ON ESCRIBE.ADDRESS
(
	STATE,
	ZIP_CODE
)
/
CREATE INDEX ESCRIBE.ADDRESS_ZIP_INDX ON ESCRIBE.ADDRESS
(
	ZIP_CODE
)
/
CREATE INDEX ESCRIBE.APP_USER_PRESCRIBER_NDX ON ESCRIBE.APP_USER
(
	ID_NHIN_PRESCRIBER
)
/
CREATE INDEX ESCRIBE.APP_USER_ROLE_ID_APP_USER_INDX ON ESCRIBE.APP_USER_ROLE
(
	ID_APP_USER
)
/
CREATE INDEX ESCRIBE.APP_USER_ROLE_IX1 ON ESCRIBE.APP_USER_ROLE
(
	ID_APP_ROLE
)
/
CREATE INDEX ESCRIBE.AUDIT_DATES_NDX1 ON ESCRIBE.AUDIT_DATES
(
	TABLE_CLASS_NAME,
	TABLE_ROW_ID
)
/
CREATE INDEX ESCRIBE.CLAIM_HISTORY_IX1 ON ESCRIBE.CLAIM_HISTORY
(
	ID_NCPDP_MESSAGE_REVERSE
)
/
CREATE INDEX ESCRIBE.CLAIM_HISTORY_IX2 ON ESCRIBE.CLAIM_HISTORY
(
	ID_NCPDP_MESSAGE_CLAIM
)
/
CREATE INDEX ESCRIBE.CLAIM_HISTORY_IX3 ON ESCRIBE.CLAIM_HISTORY
(
	ID_NCPDP_MESSAGE_CLAIM_RESP
)
/
CREATE INDEX ESCRIBE.CLAIM_HISTORY_IX4 ON ESCRIBE.CLAIM_HISTORY
(
	ID_NCPDP_MESSAGE_REVERSE_RESP
)
/
CREATE INDEX ESCRIBE.CLAIM_HST_NHIN_PRES_CLN_LNK_FK ON ESCRIBE.CLAIM_HISTORY
(
	ID_NHIN_PRESCRIBER
)
/
CREATE INDEX ESCRIBE.CPR_LINK_AUDIT_OLD_RXCOM_NDX ON ESCRIBE.CPR_LINK_AUDIT
(
	OLD_RXCOM_ID
)
/
CREATE INDEX ESCRIBE.CUSTOM_SIGS_ID_NHIN_PRESCR_NDX ON ESCRIBE.CUSTOM_SIGS
(
	ID_NHIN_PRESCRIBER
)
/
CREATE INDEX ESCRIBE.INS_PLAN_BIN_PCN_GROUP_NUM_IDX ON ESCRIBE.INSURANCE_PLAN
(
	BIN,
	PCN,
	GROUP_NUMBER
)
/
CREATE INDEX ESCRIBE.INS_PLAN_PDX_CARRIER_CODE_IDX ON ESCRIBE.INSURANCE_PLAN
(
	PDX_CARRIER_CODE
)
/
CREATE INDEX ESCRIBE.MFR_PROGRAM_NDC_LINK_IX1 ON ESCRIBE.MFR_PROGRAM_NDC_LINK
(
	ID_MANUFACTURER_PROGRAM
)
/
CREATE INDEX ESCRIBE.MFR_PROGRAM_PHARMACY_LINK_IX1 ON ESCRIBE.MFR_PROGRAM_PHARMACY_LINK
(
	ID_MANUFACTURER_PROGRAM
)
/
CREATE INDEX ESCRIBE.NHIN_CLINIC_CLINIC_NAME_INDX ON ESCRIBE.NHIN_CLINIC
(
	CLINIC_NAME
)
/
CREATE INDEX ESCRIBE.NHIN_CLINIC_ID_ADDRESS_IDX ON ESCRIBE.NHIN_CLINIC
(
	ID_ADDRESS
)
/
CREATE INDEX ESCRIBE.NHIN_PRESCR_CLN_LNK_DEA_ID_NDX ON ESCRIBE.NHIN_PRESCRIBER_CLINIC_LINK
(
	DEA_ID
)
/
CREATE INDEX ESCRIBE.NHIN_PRESCRIBER_CLINIC_LK_IX1 ON ESCRIBE.NHIN_PRESCRIBER_CLINIC_LINK
(
	ID_NHIN_CLINIC
)
/
CREATE INDEX ESCRIBE.NHIN_PRESCRIBER_DEA_ID_INDX ON ESCRIBE.NHIN_PRESCRIBER
(
	DEA_ID
)
/
CREATE INDEX ESCRIBE.NHIN_PRESCRIBER_EMAIL_NDX ON ESCRIBE.NHIN_PRESCRIBER
(
	EMAIL_ADDRESS,
	REGISTRATION_PIN
)
/
CREATE INDEX ESCRIBE.NHIN_PRESCRIBER_FIRST_NAME_NDX ON ESCRIBE.NHIN_PRESCRIBER
(
	FIRST_NAME
)
/
CREATE INDEX ESCRIBE.NHIN_PRESCRIBER_HCID_NDX ON ESCRIBE.NHIN_PRESCRIBER
(
	HCID
)
/
CREATE INDEX ESCRIBE.NHIN_PRESCRIBER_IX1 ON ESCRIBE.NHIN_PRESCRIBER
(
	ID_REGISTRATION_ADDRESS
)
/
CREATE INDEX ESCRIBE.NHIN_PRESCRIBER_NAME_NDX ON ESCRIBE.NHIN_PRESCRIBER
(
	LAST_NAME,
	FIRST_NAME
)
/
CREATE INDEX ESCRIBE.NHIN_PRESCRIBER_REG_DATE_NDX ON ESCRIBE.NHIN_PRESCRIBER
(
	REGISTRATION_DATE
)
/
CREATE INDEX ESCRIBE.ORDER_INFO_IDX_IDPRESCWRT ON ESCRIBE.ORDER_INFO
(
	ID_PRESCRIPTIONS_WRITTEN
)
/
CREATE INDEX ESCRIBE.PASSWORD_HISTORY_APP_USER_NDX ON ESCRIBE.PASSWORD_HISTORY
(
	ID_APP_USER
)
/
CREATE INDEX ESCRIBE.PHARMACY_IX1 ON ESCRIBE.PHARMACY
(
	ID_ADDRESS
)
/
CREATE INDEX ESCRIBE.PHARMACY_MEDICAID_IDS_IX1 ON ESCRIBE.PHARMACY_MEDICAID_IDS
(
	ID_PHARMACY
)
/
CREATE UNIQUE INDEX ESCRIBE.PHARMACY_NCPDP_NUMBER_INDX ON ESCRIBE.PHARMACY
(
	NCPDP_NUMBER
)
/
CREATE INDEX ESCRIBE.PHARMACY_PHARMACY_NAME_INDX ON ESCRIBE.PHARMACY
(
	PHARMACY_NAME
)
/
CREATE UNIQUE INDEX ESCRIBE.PRES_PIN_MAIL_ID_NHIN_PRES_NDX ON ESCRIBE.PRESCRIBER_PIN_MAILING
(
	ID_NHIN_PRESCRIBER
)
/
CREATE INDEX ESCRIBE.PRESCR_CLN_LNK_ID_PRESCR_INDX ON ESCRIBE.NHIN_PRESCRIBER_CLINIC_LINK
(
	ID_NHIN_PRESCRIBER
)
/
CREATE INDEX ESCRIBE.PRESCR_DRUG_ID_NHIN_PRESCR_NDX ON ESCRIBE.PRESCRIBER_DRUG_USAGE
(
	ID_NHIN_PRESCRIBER
)
/
CREATE INDEX ESCRIBE.PRESCR_MEDI_ID_NHIN_PRESCR_NDX ON ESCRIBE.PRESCRIBER_MEDICAID
(
	ID_NHIN_PRESCRIBER
)
/
CREATE INDEX ESCRIBE.PRESCR_MEDICAID_ST_MEDI_ID_NDX ON ESCRIBE.PRESCRIBER_MEDICAID
(
	STATE,
	MEDICAID_ID
)
/
CREATE INDEX ESCRIBE.PRESCR_PHRM_ID_NHIN_PRESCR_NDX ON ESCRIBE.PRESCRIBER_PHARMACY_USAGE
(
	ID_NHIN_PRESCRIBER
)
/
CREATE INDEX ESCRIBE.PRESCR_STAT_ID_NHIN_PRESCR_NDX ON ESCRIBE.PRESCRIBER_STATE
(
	ID_NHIN_PRESCRIBER
)
/
CREATE INDEX ESCRIBE.PRESCRIBER_PHARMACY_USAGE_IX1 ON ESCRIBE.PRESCRIBER_PHARMACY_USAGE
(
	ID_PHARMACY
)
/
CREATE INDEX ESCRIBE.PRESCRIBER_STATE_ST_LIC_ID_NDX ON ESCRIBE.PRESCRIBER_STATE
(
	STATE,
	STATE_LICENSE_ID
)
/
CREATE INDEX ESCRIBE.PRESCRIPTIONS_WRITTEN_IX1 ON ESCRIBE.PRESCRIPTIONS_WRITTEN
(
	ID_PHARMACY
)
/
CREATE INDEX ESCRIBE.PRESCRIPTIONS_WRITTEN_NDX1 ON ESCRIBE.PRESCRIPTIONS_WRITTEN
(
	ID_NHIN_PRESCRIBER_CLINIC_LINK,
	PATIENT_LAST_NAME
)
/
CREATE INDEX ESCRIBE.PRESCRIPTIONS_WRITTEN_NDX2 ON ESCRIBE.PRESCRIPTIONS_WRITTEN
(
	ID_NHIN_PRESCRIBER_CLINIC_LINK,
	TRUNC("DATE_SENT"),
	PATIENT_LAST_NAME
)
/
CREATE INDEX ESCRIBE.PRESCRIPTIONS_WRITTEN_NDX3 ON ESCRIBE.PRESCRIPTIONS_WRITTEN
(
	RX_COM_ID
)
/
CREATE UNIQUE INDEX ESCRIBE.PRESCRIPTIONS_WRITTEN_NDX4 ON ESCRIBE.PRESCRIPTIONS_WRITTEN
(
	TRANSACTION_NUMBER
)
/
CREATE INDEX ESCRIBE.PROG_NDC_SHIP_OPT_LNK_MFR_NDX ON ESCRIBE.PROGRAM_NDC_SHIP_OPTION_LINK
(
	ID_MFR_PROGRAM_NDC_LINK
)
/
CREATE INDEX ESCRIBE.PROG_SHIP_OPT_LNK_MFR_NDX ON ESCRIBE.PROGRAM_SHIPPING_OPTION_LINK
(
	ID_MANUFACTURER_PROGRAM
)
/
CREATE INDEX ESCRIBE.PROGRAM_NDC_SHIP_OPT_LINK_IX1 ON ESCRIBE.PROGRAM_NDC_SHIP_OPTION_LINK
(
	ID_SHIPPING_OPTION
)
/
CREATE INDEX ESCRIBE.PROGRAM_SHIPPING_OPT_LINK_IX1 ON ESCRIBE.PROGRAM_SHIPPING_OPTION_LINK
(
	ID_SHIPPING_OPTION
)
/
CREATE INDEX ESCRIBE.SIG_TEXT_MASTER_DOSAGE_NDX ON ESCRIBE.SIG_TEXT_MASTER
(
	DOSAGE_FORM,
	ROUTE_CODE
)
/
