CREATE TABLE DIB3_1.IMGIPT_BASIC
( 
	CATEGORYID NUMBER(5, 0) NOT NULL,
	BASICDESCID NUMBER(5, 0) NOT NULL,
	BASICDESC VARCHAR2(30) NOT NULL
)
/
CREATE TABLE DIB3_1.IMGIPT_CATEGORY
( 
	CATEGORYID NUMBER(5, 0) NOT NULL,
	CATEGORYDESC VARCHAR2(30) NOT NULL
)
/
CREATE TABLE DIB3_1.IMGIPT_DESC
( 
	CATEGORYID NUMBER(5, 0) NOT NULL,
	DESCRIPTORID NUMBER(5, 0) NOT NULL,
	BASICDESCID NUMBER(5, 0) NOT NULL,
	DESCRIPTION VARCHAR2(30) NOT NULL
)
/
CREATE TABLE DIB3_1.IMGIPT_DOSE_FORM
( 
	DOSAGEFORMID NUMBER(5, 0) NOT NULL,
	DOSAGEFORMDESC VARCHAR2(30) NOT NULL
)
/
CREATE TABLE DIB3_1.IMGIPT_IMAGE
( 
	IMAGEID NUMBER(10, 0) NOT NULL,
	IMAGEFILE VARCHAR2(20) NOT NULL
)
/
CREATE TABLE DIB3_1.IMGIPT_IMPRINT
( 
	PROPERTYID NUMBER(10, 0) NOT NULL,
	IMPRINTSIDE1 VARCHAR2(40) NOT NULL,
	IMPRINTSIDE2 VARCHAR2(40)
)
/
CREATE TABLE DIB3_1.IMGIPT_JOURNAL
( 
	UNIQUEDRUGID NUMBER(10, 0) NOT NULL,
	STARTDATE NUMBER(8, 0) NOT NULL,
	STOPDATE NUMBER(8, 0),
	PROPERTYID NUMBER(10, 0),
	IMAGEID NUMBER(10, 0)
)
/
CREATE TABLE DIB3_1.IMGIPT_LIB_VERSION
( 
	VERSIONKEY NUMBER(5, 0) NOT NULL,
	DBVERSION VARCHAR2(5),
	BUILDVERSION VARCHAR2(5),
	FREQUENCY VARCHAR2(1),
	ISSUEDATE VARCHAR2(8),
	VERSIONCOMMENT VARCHAR2(80)
)
/
CREATE TABLE DIB3_1.IMGIPT_MANUFACT
( 
	MANUFACTURERID NUMBER(10, 0) NOT NULL,
	MANUFACTURERNAME VARCHAR2(30) NOT NULL
)
/
CREATE TABLE DIB3_1.IMGIPT_PROP_DESC
( 
	PROPERTYID NUMBER(10, 0) NOT NULL,
	CATEGORYID NUMBER(5, 0) NOT NULL,
	DESCRIPTORID NUMBER(5, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.IMGIPT_PROP_TEXT
( 
	PROPERTYID NUMBER(10, 0) NOT NULL,
	TEXTID NUMBER(10, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.IMGIPT_PROPERTY
( 
	PROPERTYID NUMBER(10, 0) NOT NULL,
	IMPRINTSIDE1 VARCHAR2(40),
	IMPRINTSIDE2 VARCHAR2(40),
	COLOR1ID NUMBER(5, 0),
	COLOR2ID NUMBER(5, 0),
	COLOR3ID NUMBER(5, 0),
	BASICCOLOR1ID NUMBER(5, 0),
	BASICCOLOR2ID NUMBER(5, 0),
	BASICCOLOR3ID NUMBER(5, 0),
	COATINGID NUMBER(5, 0),
	CLARITYID NUMBER(5, 0),
	FLAVORID NUMBER(5, 0),
	SHAPEID NUMBER(5, 0),
	BASICSHAPEID NUMBER(5, 0),
	SCOREID NUMBER(5, 0)
)
/
CREATE TABLE DIB3_1.IMGIPT_TEXT
( 
	TEXTID NUMBER(10, 0) NOT NULL,
	LINENUMBER NUMBER(3, 0) NOT NULL,
	TEXT VARCHAR2(70) NOT NULL
)
/
CREATE TABLE DIB3_1.IMGIPT_UNIQUE
( 
	UNIQUEDRUGID NUMBER(10, 0) NOT NULL,
	DOSAGEFORMID NUMBER(5, 0) NOT NULL,
	EXTERNALDRUGID VARCHAR2(20) NOT NULL,
	MANUFACTURERID NUMBER(10, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_ADE_COM
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	TEXTID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_ADE_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SEVERITYCODE VARCHAR2(2) NOT NULL,
	ONSETCODE VARCHAR2(2) NOT NULL,
	INCIDENCECODE VARCHAR2(2) NOT NULL,
	DOCLEVELCODE VARCHAR2(2) NOT NULL,
	TYPECODE VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_ADE_SPECCOND
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SPECCONDID NUMBER(38, 0) NOT NULL,
	INCIDENCECODE VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_CLS_AHFS
( 
	CLASSID VARCHAR2(6) NOT NULL,
	DESCDISPLAY VARCHAR2(65) NOT NULL,
	DESCSEARCH VARCHAR2(65) NOT NULL,
	DESCPHONETIC VARCHAR2(65) NOT NULL,
	PARENTCLASSID VARCHAR2(6),
	HASCHILDRENIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_CLS_AHFSDRUG
( 
	CLASSID VARCHAR2(6) NOT NULL,
	DRUGTYPE NUMBER(38, 0) NOT NULL,
	DRUGID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_CLS_GPI
( 
	CLASSID VARCHAR2(6) NOT NULL,
	DESCDISPLAY VARCHAR2(65) NOT NULL,
	DESCSEARCH VARCHAR2(65) NOT NULL,
	DESCPHONETIC VARCHAR2(65) NOT NULL,
	PARENTCLASSID VARCHAR2(6),
	HASCHILDRENIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_CLS_GPIDRUG
( 
	CLASSID VARCHAR2(6) NOT NULL,
	DRUGTYPE NUMBER(38, 0) NOT NULL,
	DRUGID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_CM_DISPLINK
( 
	DDID NUMBER(38, 0) NOT NULL,
	CMID VARCHAR2(3) NOT NULL,
	PRIORITY NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_CM_PACKLINK
( 
	PPID VARCHAR2(20) NOT NULL,
	CMID VARCHAR2(3) NOT NULL,
	PRIORITY NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_CM_TEXT
( 
	VERSIONCODE VARCHAR2(10) NOT NULL,
	CMID VARCHAR2(3) NOT NULL,
	PROFMSG1 VARCHAR2(34),
	PROFMSG2 VARCHAR2(34),
	PATMSG1 VARCHAR2(25),
	PATMSG2 VARCHAR2(25)
)
/
CREATE TABLE DIB3_1.MMW_DCK_COM
( 
	GPI VARCHAR2(14) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	EFFECTCODE VARCHAR2(2) NOT NULL,
	COMMENTCODE VARCHAR2(3) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DCK_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	DOSEFORMLOW NUMBER(6, 2) NOT NULL,
	DOSEFORMHIGH NUMBER(6, 2) NOT NULL,
	DOSEFORMUSUAL NUMBER(6, 2),
	SINGLEDOSEHIGH NUMBER(6, 2),
	DURATIONLOW NUMBER(38, 0) NOT NULL,
	DURATIONHIGH NUMBER(38, 0),
	DURATIONUSUAL NUMBER(38, 0),
	REFERENCECODE VARCHAR2(3) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DFA_INT
( 
	DRUGCLASSID VARCHAR2(5) NOT NULL,
	FOODCLASSID VARCHAR2(5) NOT NULL,
	DRUGACTCODE VARCHAR2(1) NOT NULL,
	DRUGDURATION NUMBER(38, 0) NOT NULL,
	FOODDURATION NUMBER(38, 0) NOT NULL,
	DRUGSCHREGIND NUMBER(38, 0) NOT NULL,
	DRUGSCHASNEEDIND NUMBER(38, 0) NOT NULL,
	DRUGSCHSINGLEIND NUMBER(38, 0) NOT NULL,
	FOODSCHREGIND NUMBER(38, 0) NOT NULL,
	FOODSCHASNEEDIND NUMBER(38, 0) NOT NULL,
	FOODSCHSINGLEIND NUMBER(38, 0) NOT NULL,
	ONSETCODE VARCHAR2(1) NOT NULL,
	SEVERITYCODE VARCHAR2(1) NOT NULL,
	DOCLEVELCODE VARCHAR2(1) NOT NULL,
	DRUGCLASSNAME VARCHAR2(75) NOT NULL,
	FOODCLASSNAME VARCHAR2(75) NOT NULL,
	MONOID VARCHAR2(20) NOT NULL,
	ALCOHOLIND NUMBER(38, 0) NOT NULL,
	CLASS1FOODIND NUMBER(38, 0) NOT NULL,
	MGMTCODE VARCHAR2(1) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DFA_TEXT
( 
	VERSION VARCHAR2(10) NOT NULL,
	DRUGCLASSID VARCHAR2(5) NOT NULL,
	FOODCLASSID VARCHAR2(5) NOT NULL,
	LINENUMBER NUMBER(38, 0) NOT NULL,
	LINETEXT VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DI_CLASSLINK
( 
	KDC1 VARCHAR2(5) NOT NULL,
	CLASSID VARCHAR2(5) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DI_INT
( 
	CLASSID1 VARCHAR2(5) NOT NULL,
	CLASSID2 VARCHAR2(5) NOT NULL,
	ACTCODE1 VARCHAR2(1) NOT NULL,
	ACTCODE2 VARCHAR2(1) NOT NULL,
	DURATION1 NUMBER(38, 0) NOT NULL,
	DURATION2 NUMBER(38, 0) NOT NULL,
	SCHEDREG1IND NUMBER(38, 0) NOT NULL,
	SCHEDASNEEDED1IND NUMBER(38, 0) NOT NULL,
	SCHEDSINGLE1IND NUMBER(38, 0) NOT NULL,
	SCHEDREG2IND NUMBER(38, 0) NOT NULL,
	SCHEDASNEEDED2IND NUMBER(38, 0) NOT NULL,
	SCHEDSINGLE2IND NUMBER(38, 0) NOT NULL,
	ONSETCODE VARCHAR2(1) NOT NULL,
	SEVERITYCODE VARCHAR2(1) NOT NULL,
	DOCLEVELCODE VARCHAR2(1) NOT NULL,
	CLASS1NAME VARCHAR2(75) NOT NULL,
	CLASS2NAME VARCHAR2(75) NOT NULL,
	MONOID VARCHAR2(20) NOT NULL,
	SCREENINGIND NUMBER(38, 0) NOT NULL,
	MGMTCODE VARCHAR2(1) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DI_RPIDLINK
( 
	KDC1 VARCHAR2(5) NOT NULL,
	NAMETYPECODE VARCHAR2(1) NOT NULL,
	RPID NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(65),
	ACTCODE VARCHAR2(1)
)
/
CREATE TABLE DIB3_1.MMW_DI_TEXT
( 
	VERSION VARCHAR2(10) NOT NULL,
	CLASSID1 VARCHAR2(5) NOT NULL,
	CLASSID2 VARCHAR2(5) NOT NULL,
	LINENUMBER NUMBER(38, 0) NOT NULL,
	LINETEXT VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DRUG_DISP
( 
	DDID NUMBER(38, 0) NOT NULL,
	DESCDISPLAY VARCHAR2(125) NOT NULL,
	DESCSEARCH VARCHAR2(125) NOT NULL,
	DESCPHONETIC VARCHAR2(125) NOT NULL,
	RTID NUMBER(38, 0) NOT NULL,
	DFID NUMBER(38, 0) NOT NULL,
	STRENGTH VARCHAR2(15),
	STRENGTHUNIT VARCHAR2(10),
	RPID NUMBER(38, 0) NOT NULL,
	PNID NUMBER(38, 0) NOT NULL,
	BIOEQUIVCODE VARCHAR2(1) NOT NULL,
	CTRLSUBSTANCECODE VARCHAR2(1) NOT NULL,
	EFFICACYCODE VARCHAR2(1),
	RXOTCCODE VARCHAR2(1) NOT NULL,
	GENERICCODE VARCHAR2(1) NOT NULL,
	NAMETYPECODE VARCHAR2(1) NOT NULL,
	NAMESOURCECODE VARCHAR2(1) NOT NULL,
	GPI VARCHAR2(14),
	PARTIALGPIIND NUMBER(38, 0) NOT NULL,
	KDC VARCHAR2(10),
	KDCFLAG VARCHAR2(1),
	ACTCODE VARCHAR2(1),
	SINGLEINGRIND NUMBER(38, 0) NOT NULL,
	MEDDEVIND NUMBER(38, 0) NOT NULL,
	HASPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASEQVPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASIMAGEIND NUMBER(38, 0) NOT NULL,
	CMMULTIND NUMBER(38, 0) NOT NULL,
	DOSECHEKUNIT VARCHAR2(20),
	HISTORICALIND NUMBER(38, 0) NOT NULL,
	OBSOLETEDATE VARCHAR2(8),
	SCREENCLEANADE NUMBER(38, 0),
	SCREENCLEANPRC NUMBER(38, 0),
	SCREENCLEANDFA NUMBER(38, 0),
	SCREENCLEANDI NUMBER(38, 0),
	SCREENCLEANDC NUMBER(38, 0),
	SCREENCLEANDDA NUMBER(38, 0),
	REPACKCODE NUMBER(38, 0),
	PRIVATELABELERCODE NUMBER(38, 0)
)
/
CREATE TABLE DIB3_1.MMW_DRUG_DISP_LBLR
( 
	DDID NUMBER(38, 0) NOT NULL,
	LABELERID VARCHAR2(5) NOT NULL,
	REFREPACKCODE VARCHAR2(1) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DRUG_DOSEFORM
( 
	DFID NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(40) NOT NULL,
	ABBREV VARCHAR2(4) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DRUG_GPI
( 
	GPI VARCHAR2(14) NOT NULL,
	DESCRIPTION VARCHAR2(60),
	GENERICDDID NUMBER(38, 0),
	DOSECHEKUNIT VARCHAR2(20),
	DDASINGLEROUTE NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DRUG_GPILINK
( 
	DRUGID VARCHAR2(16) NOT NULL,
	GPI VARCHAR2(14) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DRUG_KDC
( 
	KDC1 VARCHAR2(5) NOT NULL,
	DESCRIPTION VARCHAR2(50) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DRUG_KDCLINK
( 
	DRUGID VARCHAR2(12) NOT NULL,
	KDC1 VARCHAR2(5) NOT NULL,
	RPID NUMBER(38, 0)
)
/
CREATE TABLE DIB3_1.MMW_DRUG_LABELER
( 
	LABELERID VARCHAR2(5) NOT NULL,
	NAMEFULL VARCHAR2(30) NOT NULL,
	NAMEABBREV VARCHAR2(10) NOT NULL,
	TYPECODE VARCHAR2(1) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DRUG_NAME
( 
	PNID NUMBER(38, 0) NOT NULL,
	DESCDISPLAY VARCHAR2(35) NOT NULL,
	DESCSEARCH VARCHAR2(35) NOT NULL,
	DESCPHONETIC VARCHAR2(35) NOT NULL,
	RPIDUNIQUE NUMBER(38, 0),
	DDIDUNIQUE NUMBER(38, 0),
	NAMETYPECODE VARCHAR2(1) NOT NULL,
	RXOTCCODE VARCHAR2(1),
	SINGLEINGRIND NUMBER(38, 0) NOT NULL,
	MEDDEVIND NUMBER(38, 0) NOT NULL,
	HASPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASEQVPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASKDCIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DRUG_PACK
( 
	PPID VARCHAR2(20) NOT NULL,
	DDID NUMBER(38, 0) NOT NULL,
	RTID NUMBER(38, 0) NOT NULL,
	DFID NUMBER(38, 0) NOT NULL,
	STRENGTH VARCHAR2(15),
	STRENGTHUNIT VARCHAR2(15),
	TEECODE VARCHAR2(2) NOT NULL,
	DEACLASSCODE VARCHAR2(1),
	DESICODE VARCHAR2(1),
	RXOTCCODE VARCHAR2(1) NOT NULL,
	GPPC VARCHAR2(8) NOT NULL,
	OLDPPID VARCHAR2(20),
	NEWPPID VARCHAR2(20),
	REPACKIND NUMBER(38, 0) NOT NULL,
	IDFORMATCODE VARCHAR2(1) NOT NULL,
	THIRDPRTYRESTRCODE VARCHAR2(1),
	KDC VARCHAR2(10),
	LABELERID VARCHAR2(5) NOT NULL,
	MULTISOURCECODE VARCHAR2(1) NOT NULL,
	NAMETYPECODE VARCHAR2(1) NOT NULL,
	INNERPACKIND NUMBER(38, 0) NOT NULL,
	CLINICPACKIND NUMBER(38, 0) NOT NULL,
	REIMBURSEMENTCODE VARCHAR2(1) NOT NULL,
	PRICESPREADCODE VARCHAR2(1) NOT NULL,
	GPI VARCHAR2(14) NOT NULL,
	PACKSIZE NUMBER(8, 3) NOT NULL,
	PACKSIZEUNITCODE VARCHAR2(2) NOT NULL,
	PACKQUANTITY NUMBER(38, 0) NOT NULL,
	UNITDOSECODE VARCHAR2(1),
	PACKDESCCODE VARCHAR2(2) NOT NULL,
	NDC VARCHAR2(13) NOT NULL,
	GENIDTYPECODE VARCHAR2(1) NOT NULL,
	GENIDNUMBER VARCHAR2(9) NOT NULL,
	AHFSTHERACLASSCODE VARCHAR2(6) NOT NULL,
	LOCALSYSTEMICCODE VARCHAR2(1) NOT NULL,
	MAINTDRUGIND NUMBER(38, 0) NOT NULL,
	FORMTYPECODE VARCHAR2(1) NOT NULL,
	DOLLARRANKCODE VARCHAR2(1) NOT NULL,
	RXRANKCODE VARCHAR2(1) NOT NULL,
	INTEXTCODE VARCHAR2(1) NOT NULL,
	SINGLECOMBCODE VARCHAR2(1) NOT NULL,
	STORAGECONDCODE VARCHAR2(1),
	OLDPPIDEFFDATE VARCHAR2(8),
	NEWPPIDEFFDATE VARCHAR2(8),
	PRODUCTNAME VARCHAR2(25) NOT NULL,
	PRODUCTNAMEEXT VARCHAR2(35),
	TOTALPACKAGEQTY NUMBER(12, 3) NOT NULL,
	CURRIMAGEFILENAME VARCHAR2(8),
	ACTCODE VARCHAR2(1),
	SINGLEINGRIND NUMBER(38, 0) NOT NULL,
	MEDDEVIND NUMBER(38, 0) NOT NULL,
	INACTIVEDATE VARCHAR2(8),
	PRODUCTDESCABBREV VARCHAR2(25) NOT NULL,
	DOSECHEKUNIT VARCHAR2(20),
	ITEMSTATUS VARCHAR2(1) NOT NULL,
	SCREENCLEANADE NUMBER(38, 0),
	SCREENCLEANPRC NUMBER(38, 0),
	SCREENCLEANDFA NUMBER(38, 0),
	SCREENCLEANDI NUMBER(38, 0),
	SCREENCLEANDC NUMBER(38, 0),
	SCREENCLEANDDA NUMBER(38, 0),
	PARTIALGPIIND NUMBER(38, 0) NOT NULL,
	PRIVATELABELERIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DRUG_PACK_MOD
( 
	PPID VARCHAR2(20) NOT NULL,
	MODID VARCHAR2(6) NOT NULL,
	TYPECODE VARCHAR2(2) NOT NULL,
	CATCODE VARCHAR2(4) NOT NULL,
	DESCRIPTION VARCHAR2(25) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DRUG_ROUTE
( 
	RTID NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(40),
	ABBREV VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DRUG_ROUTED
( 
	RPID NUMBER(38, 0) NOT NULL,
	DESCDISPLAY VARCHAR2(65) NOT NULL,
	DESCSEARCH VARCHAR2(65) NOT NULL,
	DESCPHONETIC VARCHAR2(65) NOT NULL,
	RTID NUMBER(38, 0) NOT NULL,
	PNID NUMBER(38, 0) NOT NULL,
	DDIDUNIQUE NUMBER(38, 0),
	NAMETYPECODE VARCHAR2(1) NOT NULL,
	RXOTCCODE VARCHAR2(1),
	ACTCODE VARCHAR2(1),
	SINGLEINGRIND NUMBER(38, 0) NOT NULL,
	MEDDEVIND NUMBER(38, 0) NOT NULL,
	HASPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASEQVPACKDRUGIND NUMBER(38, 0) NOT NULL,
	HASGPIIND NUMBER(38, 0) NOT NULL,
	HASKDCIND NUMBER(38, 0) NOT NULL,
	SCREENCLEANDFA NUMBER(38, 0),
	SCREENCLEANDI NUMBER(38, 0)
)
/
CREATE TABLE DIB3_1.MMW_DUP_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	DTCID VARCHAR2(8) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_DUP_TEXT
( 
	DTCID VARCHAR2(8) NOT NULL,
	DESCRIPTION VARCHAR2(40) NOT NULL,
	POTENTIALABUSECODE VARCHAR2(1) NOT NULL,
	DUPALLOWANCE NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_IND_COM
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MICROORGANISMID NUMBER(38, 0) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	TEXTID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_IND_COTREAT
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MICROORGANISMID NUMBER(38, 0) NOT NULL,
	COTREATSETID NUMBER(38, 0) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	DESCRIPTION VARCHAR2(80) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_IND_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MICROORGANISMID NUMBER(38, 0) NOT NULL,
	ROLEOFTHERAPYCODE VARCHAR2(2) NOT NULL,
	OUTCOMECODE VARCHAR2(2) NOT NULL,
	TREATMENTRANKCODE VARCHAR2(2) NOT NULL,
	ACCEPTANCELVLCODE VARCHAR2(2) NOT NULL,
	PROXYCODE VARCHAR2(1) NOT NULL,
	PROXYONLYIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_IND_RPID
( 
	MCID NUMBER(38, 0) NOT NULL,
	RPID NUMBER(38, 0) NOT NULL,
	OUTCOMECODE VARCHAR2(2) NOT NULL,
	ACCEPTANCELVLCODE VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_IND_SOURCE
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MICROORGANISMID NUMBER(38, 0) NOT NULL,
	SOURCECODE VARCHAR2(2) NOT NULL,
	SOURCEACCEPTCODE VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_LIB_CODEDEF
( 
	CODETYPE NUMBER(38, 0) NOT NULL,
	CODEVALUE VARCHAR2(10) NOT NULL,
	DESCRIPTION VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_LIB_DISCLAIMER
( 
	VERSIONCODE VARCHAR2(10) NOT NULL,
	CATEGORYCODE VARCHAR2(10) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	SECTIONCODE VARCHAR2(1) NOT NULL,
	FORMATCODE VARCHAR2(1) NOT NULL,
	LINETEXT VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_LIB_VERSION
( 
	VERSIONKEY NUMBER(38, 0) NOT NULL,
	DBVERSION VARCHAR2(5) NOT NULL,
	BUILDVERSION VARCHAR2(5) NOT NULL,
	FREQUENCY VARCHAR2(1) NOT NULL,
	ISSUEDATE VARCHAR2(8) NOT NULL,
	VERSIONCOMMENT VARCHAR2(80) NOT NULL,
	LASTUPDATE VARCHAR2(20)
)
/
CREATE TABLE DIB3_1.MMW_MED
( 
	MCID NUMBER(38, 0) NOT NULL,
	PRIMARYPROFNAME VARCHAR2(58) NOT NULL,
	PRIMARYPATNAME VARCHAR2(58) NOT NULL,
	TYPECODE VARCHAR2(2) NOT NULL,
	CLASSONLYIND NUMBER(38, 0) NOT NULL,
	GENDERCODE VARCHAR2(1) NOT NULL,
	PREGNANCYIND NUMBER(38, 0) NOT NULL,
	LACTATIONIND NUMBER(38, 0) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	DURATIONCODE VARCHAR2(2) NOT NULL,
	HASCHILDRENIND NUMBER(38, 0) NOT NULL,
	DRUGSTOTREATIND NUMBER(38, 0) NOT NULL,
	DRUGSTOAVOIDIND NUMBER(38, 0) NOT NULL,
	DRUGSTHATCAUSEIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_MED_CIT
( 
	CITATIONID NUMBER(38, 0) NOT NULL,
	CITATIONTEXT VARCHAR2(250) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_MED_EXTVOCAB
( 
	VOCABTYPECODE VARCHAR2(1) NOT NULL,
	EXTVOCABID VARCHAR2(20) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_MED_HIER
( 
	MCID NUMBER(38, 0) NOT NULL,
	PARENTID NUMBER(38, 0) NOT NULL,
	RELATIONTYPECODE VARCHAR2(2) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_MED_INTVOCAB
( 
	VOCABTYPECODE VARCHAR2(1) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	EXTVOCABID VARCHAR2(20) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_MED_LINK
( 
	MCID NUMBER(38, 0) NOT NULL,
	RELATEDMCID NUMBER(38, 0) NOT NULL,
	RELATIONTYPECODE VARCHAR2(2) NOT NULL,
	DIRECTIONCODE VARCHAR2(1) NOT NULL,
	DISTANCE NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_MED_NAME
( 
	MCID NUMBER(38, 0) NOT NULL,
	NAMETYPECODE VARCHAR2(2) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	NAMEDISPLAY VARCHAR2(60) NOT NULL,
	NAMESEARCH VARCHAR2(60) NOT NULL,
	NAMEPHONETIC VARCHAR2(60) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_MED_TEXT
( 
	TEXTID NUMBER(38, 0) NOT NULL,
	LINENUMBER NUMBER(38, 0) NOT NULL,
	LINETEXT VARCHAR2(140) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_MED_TEXT_CIT
( 
	TEXTID NUMBER(38, 0) NOT NULL,
	CITATIONID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_MONO_CLSNAME
( 
	CATEGORYCODE VARCHAR2(10) NOT NULL,
	MONOID VARCHAR2(20) NOT NULL,
	CLASS1NAME VARCHAR2(75) NOT NULL,
	CLASS2NAME VARCHAR2(75) NOT NULL,
	CLASS1FOODIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_MONO_TEXT
( 
	VERSIONCODE VARCHAR2(10) NOT NULL,
	CATEGORYCODE VARCHAR2(10) NOT NULL,
	MONOID VARCHAR2(20) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	SECTIONCODE VARCHAR2(1) NOT NULL,
	FORMATCODE VARCHAR2(1) NOT NULL,
	LINETEXT VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_PAR_CLASS
( 
	CLASSID VARCHAR2(5) NOT NULL,
	DESCDISPLAY VARCHAR2(75) NOT NULL,
	DESCSEARCH VARCHAR2(75) NOT NULL,
	DESCPHONETIC VARCHAR2(75) NOT NULL,
	CROSSREACTIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_PAR_CLASSLINK
( 
	KDC1 VARCHAR2(5) NOT NULL,
	CLASSID VARCHAR2(5) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_PAR_DRUGLINK
( 
	ALLERGYID VARCHAR2(12) NOT NULL,
	KDC1 VARCHAR2(5) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_PAR_INGRLINK
( 
	KDC1 VARCHAR2(5) NOT NULL,
	INGREDKDC1 VARCHAR2(5) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_PAR_INT
( 
	CLASSID1 VARCHAR2(5) NOT NULL,
	CLASSID2 VARCHAR2(5) NOT NULL,
	SYMPTOMCODE VARCHAR2(6) NOT NULL,
	MONOID VARCHAR2(20),
	SYMRASHIND NUMBER(38, 0) NOT NULL,
	SYMSHOCKIND NUMBER(38, 0) NOT NULL,
	SYMASTHMAIND NUMBER(38, 0) NOT NULL,
	SYMNAUSEAIND NUMBER(38, 0) NOT NULL,
	SYMANEMIAIND NUMBER(38, 0) NOT NULL,
	SYMUNSPECIFIEDIND NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_PDE_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	VERSIONCODE VARCHAR2(10) NOT NULL,
	MONOID VARCHAR2(20) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_PRCA_COM
( 
	GPI VARCHAR2(14) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	TEXTID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_PRCA_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MGMTLEVELCODE VARCHAR2(1) NOT NULL,
	ORIGAGELOW NUMBER(38, 0) NOT NULL,
	ORIGAGEHIGH NUMBER(38, 0) NOT NULL,
	ORIGAGEUNITCODE VARCHAR2(1) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_PRCA_SPECCOND
( 
	GPI VARCHAR2(14) NOT NULL,
	AGEINDAYSLOW NUMBER(38, 0) NOT NULL,
	AGEINDAYSHIGH NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SPECCONDID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_PRCC_COM
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	TEXTID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_PRCC_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	MGMTLEVELCODE VARCHAR2(1) NOT NULL,
	PLACENTTRANSCODE VARCHAR2(1),
	FDARISKFACTORCODE VARCHAR2(1),
	BRIGGSRATINGCODE VARCHAR2(1),
	BRSTFEEDEXCRETCODE VARCHAR2(1),
	BRSTFEEDRATINGCODE VARCHAR2(1),
	BRSTFEEDAAPCODE VARCHAR2(1)
)
/
CREATE TABLE DIB3_1.MMW_PRCC_SPECCOND
( 
	GPI VARCHAR2(14) NOT NULL,
	MCID NUMBER(38, 0) NOT NULL,
	RESTRICTIONID NUMBER(38, 0) NOT NULL,
	SPECCONDID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_SNOMED_MC_LINK
( 
	MCID NUMBER(38, 0) NOT NULL,
	SNOMEDID VARCHAR2(18) NOT NULL,
	RELATIONTYPE NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_WL_DRUGLINK
( 
	GPI VARCHAR2(14) NOT NULL,
	WLID VARCHAR2(6) NOT NULL,
	PRIORITY NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_WL_TEXT
( 
	VERSIONCODE VARCHAR2(10) NOT NULL,
	WLID VARCHAR2(6) NOT NULL,
	SEQUENCENUMBER NUMBER(38, 0) NOT NULL,
	LINETEXT VARCHAR2(100) NOT NULL
)
/
CREATE TABLE DIB3_1.MMW_WL_VENDCODE
( 
	VERSIONCODE VARCHAR2(10) NOT NULL,
	WLID VARCHAR2(6) NOT NULL,
	VENDVERSIONCODE VARCHAR2(3) NOT NULL,
	TEXTCODE VARCHAR2(6) NOT NULL,
	GRAPHICCODE VARCHAR2(6)
)
/
ALTER TABLE DIB3_1.IMGIPT_BASIC ADD CONSTRAINT IGPIBCPK
	PRIMARY KEY (CATEGORYID, BASICDESCID)
/
ALTER TABLE DIB3_1.IMGIPT_CATEGORY ADD CONSTRAINT IGPIDTPK
	PRIMARY KEY (CATEGORYID)
/
ALTER TABLE DIB3_1.IMGIPT_DESC ADD CONSTRAINT IGPIDCPK
	PRIMARY KEY (CATEGORYID, DESCRIPTORID)
/
ALTER TABLE DIB3_1.IMGIPT_DOSE_FORM ADD CONSTRAINT IGPIDMPK
	PRIMARY KEY (DOSAGEFORMID)
/
ALTER TABLE DIB3_1.IMGIPT_IMAGE ADD CONSTRAINT IGPIIGPK
	PRIMARY KEY (IMAGEID)
/
ALTER TABLE DIB3_1.IMGIPT_IMPRINT ADD CONSTRAINT IGPIPPPK
	PRIMARY KEY (PROPERTYID)
/
ALTER TABLE DIB3_1.IMGIPT_JOURNAL ADD CONSTRAINT IGPIUJPK
	PRIMARY KEY (UNIQUEDRUGID, STARTDATE)
/
ALTER TABLE DIB3_1.IMGIPT_LIB_VERSION ADD CONSTRAINT IMGIPTIMTPK
	PRIMARY KEY (VERSIONKEY)
/
ALTER TABLE DIB3_1.IMGIPT_MANUFACT ADD CONSTRAINT IGPIDGPK
	PRIMARY KEY (MANUFACTURERID)
/
ALTER TABLE DIB3_1.IMGIPT_PROP_DESC ADD CONSTRAINT IGPIPCPK
	PRIMARY KEY (PROPERTYID, CATEGORYID, DESCRIPTORID)
/
ALTER TABLE DIB3_1.IMGIPT_PROP_TEXT ADD CONSTRAINT IGPIPTPK
	PRIMARY KEY (PROPERTYID, TEXTID)
/
ALTER TABLE DIB3_1.IMGIPT_PROPERTY ADD CONSTRAINT IGPPRPPK
	PRIMARY KEY (PROPERTYID)
/
ALTER TABLE DIB3_1.IMGIPT_TEXT ADD CONSTRAINT IGPITTPK
	PRIMARY KEY (TEXTID, LINENUMBER)
/
ALTER TABLE DIB3_1.IMGIPT_UNIQUE ADD CONSTRAINT IGPIUGPK
	PRIMARY KEY (UNIQUEDRUGID)
/
ALTER TABLE DIB3_1.MMW_ADE_COM ADD CONSTRAINT PKMMWADECOM
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, SEQUENCENUMBER)
/
ALTER TABLE DIB3_1.MMW_ADE_DRUGLINK ADD CONSTRAINT PKMMWADEDRUGLINK
	PRIMARY KEY (GPI, MCID, RESTRICTIONID)
/
ALTER TABLE DIB3_1.MMW_ADE_SPECCOND ADD CONSTRAINT PKMMWADESPECCOND
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, SPECCONDID)
/
ALTER TABLE DIB3_1.MMW_CLS_AHFS ADD CONSTRAINT PKMMWCLSAHFS
	PRIMARY KEY (CLASSID)
/
ALTER TABLE DIB3_1.MMW_CLS_AHFSDRUG ADD CONSTRAINT PKMMWCLSAHFSDRUG
	PRIMARY KEY (CLASSID, DRUGTYPE, DRUGID)
/
ALTER TABLE DIB3_1.MMW_CLS_GPI ADD CONSTRAINT PKMMWCLSGPI
	PRIMARY KEY (CLASSID)
/
ALTER TABLE DIB3_1.MMW_CLS_GPIDRUG ADD CONSTRAINT PKMMWCLSGPIDRUG
	PRIMARY KEY (CLASSID, DRUGTYPE, DRUGID)
/
ALTER TABLE DIB3_1.MMW_CM_DISPLINK ADD CONSTRAINT PKMMWCMDISPLINK
	PRIMARY KEY (DDID, CMID)
/
ALTER TABLE DIB3_1.MMW_CM_PACKLINK ADD CONSTRAINT PKMMWCMPACKLINK
	PRIMARY KEY (PPID, CMID)
/
ALTER TABLE DIB3_1.MMW_CM_TEXT ADD CONSTRAINT PKMMWCMTEXT
	PRIMARY KEY (VERSIONCODE, CMID)
/
ALTER TABLE DIB3_1.MMW_DCK_COM ADD CONSTRAINT PKMMWDCKCOM
	PRIMARY KEY (GPI, AGEINDAYSLOW, AGEINDAYSHIGH, EFFECTCODE, COMMENTCODE)
/
ALTER TABLE DIB3_1.MMW_DCK_DRUGLINK ADD CONSTRAINT PKMMWDCKDRUGLINK
	PRIMARY KEY (GPI, AGEINDAYSLOW, AGEINDAYSHIGH)
/
ALTER TABLE DIB3_1.MMW_DFA_INT ADD CONSTRAINT PKMMWDFAINT
	PRIMARY KEY (DRUGCLASSID, FOODCLASSID)
/
ALTER TABLE DIB3_1.MMW_DFA_TEXT ADD CONSTRAINT PKMMWDFATEXT
	PRIMARY KEY (VERSION, DRUGCLASSID, FOODCLASSID, LINENUMBER)
/
ALTER TABLE DIB3_1.MMW_DI_CLASSLINK ADD CONSTRAINT PKMMWDICLASSLINK
	PRIMARY KEY (KDC1, CLASSID)
/
ALTER TABLE DIB3_1.MMW_DI_INT ADD CONSTRAINT PKMMWDIINT
	PRIMARY KEY (CLASSID1, CLASSID2)
/
ALTER TABLE DIB3_1.MMW_DI_RPIDLINK ADD CONSTRAINT PKMMWDIRPIDLINK
	PRIMARY KEY (KDC1, NAMETYPECODE, RPID)
/
ALTER TABLE DIB3_1.MMW_DI_TEXT ADD CONSTRAINT PKMMWDITEXT
	PRIMARY KEY (VERSION, CLASSID1, CLASSID2, LINENUMBER)
/
ALTER TABLE DIB3_1.MMW_DRUG_DISP ADD CONSTRAINT PKMMWDRUGDISP
	PRIMARY KEY (DDID)
/
ALTER TABLE DIB3_1.MMW_DRUG_DISP_LBLR ADD CONSTRAINT PKMMWDRUGDISPLBLR
	PRIMARY KEY (DDID, LABELERID)
/
ALTER TABLE DIB3_1.MMW_DRUG_DOSEFORM ADD CONSTRAINT PKMMWDRUGDOSEFORM
	PRIMARY KEY (DFID)
/
ALTER TABLE DIB3_1.MMW_DRUG_GPI ADD CONSTRAINT PKMMWDRUGGPI
	PRIMARY KEY (GPI)
/
ALTER TABLE DIB3_1.MMW_DRUG_GPILINK ADD CONSTRAINT PKMMWDRUGGPILINK
	PRIMARY KEY (DRUGID, GPI)
/
ALTER TABLE DIB3_1.MMW_DRUG_KDC ADD CONSTRAINT PKMMWDRUGKDC
	PRIMARY KEY (KDC1)
/
ALTER TABLE DIB3_1.MMW_DRUG_KDCLINK ADD CONSTRAINT PKMMWDRUGKDCLINK
	PRIMARY KEY (DRUGID, KDC1)
/
ALTER TABLE DIB3_1.MMW_DRUG_LABELER ADD CONSTRAINT PKMMWDRUGLABELER
	PRIMARY KEY (LABELERID)
/
ALTER TABLE DIB3_1.MMW_DRUG_NAME ADD CONSTRAINT PKMMWDRUGNAME
	PRIMARY KEY (PNID)
/
ALTER TABLE DIB3_1.MMW_DRUG_PACK ADD CONSTRAINT PKMMWDRUGPACK
	PRIMARY KEY (PPID)
/
ALTER TABLE DIB3_1.MMW_DRUG_PACK_MOD ADD CONSTRAINT PKMMWDRUGPACKMOD
	PRIMARY KEY (PPID, MODID)
/
ALTER TABLE DIB3_1.MMW_DRUG_ROUTE ADD CONSTRAINT PKMMWDRUGROUTE
	PRIMARY KEY (RTID)
/
ALTER TABLE DIB3_1.MMW_DRUG_ROUTED ADD CONSTRAINT PKMMWDRUGROUTED
	PRIMARY KEY (RPID)
/
ALTER TABLE DIB3_1.MMW_DUP_DRUGLINK ADD CONSTRAINT PKMMWDUPDRUGLINK
	PRIMARY KEY (GPI, DTCID)
/
ALTER TABLE DIB3_1.MMW_DUP_TEXT ADD CONSTRAINT PKMMWDUPTEXT
	PRIMARY KEY (DTCID)
/
ALTER TABLE DIB3_1.MMW_IND_COM ADD CONSTRAINT PKMMWINDCOM
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, MICROORGANISMID, SEQUENCENUMBER)
/
ALTER TABLE DIB3_1.MMW_IND_COTREAT ADD CONSTRAINT PKMMWINDCOTREAT
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, MICROORGANISMID, COTREATSETID, SEQUENCENUMBER)
/
ALTER TABLE DIB3_1.MMW_IND_DRUGLINK ADD CONSTRAINT PKMMWINDDRUGLINK
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, MICROORGANISMID)
/
ALTER TABLE DIB3_1.MMW_IND_RPID ADD CONSTRAINT PKMMWINDRPID
	PRIMARY KEY (MCID, RPID, OUTCOMECODE, ACCEPTANCELVLCODE)
/
ALTER TABLE DIB3_1.MMW_IND_SOURCE ADD CONSTRAINT PKMMWINDSOURCE
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, MICROORGANISMID, SOURCECODE)
/
ALTER TABLE DIB3_1.MMW_LIB_CODEDEF ADD CONSTRAINT PKMMWLIBCODEDEF
	PRIMARY KEY (CODETYPE, CODEVALUE)
/
ALTER TABLE DIB3_1.MMW_LIB_DISCLAIMER ADD CONSTRAINT PKMMWLIBDISCLAIMER
	PRIMARY KEY (VERSIONCODE, CATEGORYCODE, SEQUENCENUMBER)
/
ALTER TABLE DIB3_1.MMW_LIB_VERSION ADD CONSTRAINT PKMMWLIBVERSION
	PRIMARY KEY (VERSIONKEY)
/
ALTER TABLE DIB3_1.MMW_MED ADD CONSTRAINT PKMMWMED
	PRIMARY KEY (MCID)
/
ALTER TABLE DIB3_1.MMW_MED_CIT ADD CONSTRAINT PKMMWMEDCIT
	PRIMARY KEY (CITATIONID)
/
ALTER TABLE DIB3_1.MMW_MED_EXTVOCAB ADD CONSTRAINT PKMMWMEDEXTVOCAB
	PRIMARY KEY (VOCABTYPECODE, EXTVOCABID, MCID)
/
ALTER TABLE DIB3_1.MMW_MED_HIER ADD CONSTRAINT PKMMWMEDHIER
	PRIMARY KEY (MCID, PARENTID)
/
ALTER TABLE DIB3_1.MMW_MED_INTVOCAB ADD CONSTRAINT PKMMWMEDINTVOCAB
	PRIMARY KEY (VOCABTYPECODE, MCID, EXTVOCABID)
/
ALTER TABLE DIB3_1.MMW_MED_LINK ADD CONSTRAINT PKMMWMEDLINK
	PRIMARY KEY (MCID, RELATEDMCID)
/
ALTER TABLE DIB3_1.MMW_MED_NAME ADD CONSTRAINT PKMMWMEDNAME
	PRIMARY KEY (MCID, NAMETYPECODE, SEQUENCENUMBER)
/
ALTER TABLE DIB3_1.MMW_MED_TEXT ADD CONSTRAINT PKMMWMEDTEXT
	PRIMARY KEY (TEXTID, LINENUMBER)
/
ALTER TABLE DIB3_1.MMW_MED_TEXT_CIT ADD CONSTRAINT PKMMWMEDTEXTCIT
	PRIMARY KEY (TEXTID, CITATIONID)
/
ALTER TABLE DIB3_1.MMW_MONO_CLSNAME ADD CONSTRAINT PKMMWMONOCLSNAME
	PRIMARY KEY (CATEGORYCODE, MONOID)
/
ALTER TABLE DIB3_1.MMW_MONO_TEXT ADD CONSTRAINT PKMMWMONOTEXT
	PRIMARY KEY (VERSIONCODE, CATEGORYCODE, MONOID, SEQUENCENUMBER)
/
ALTER TABLE DIB3_1.MMW_PAR_CLASS ADD CONSTRAINT PKMMWPARCLASS
	PRIMARY KEY (CLASSID)
/
ALTER TABLE DIB3_1.MMW_PAR_CLASSLINK ADD CONSTRAINT PKMMWPARCLASSLINK
	PRIMARY KEY (KDC1, CLASSID)
/
ALTER TABLE DIB3_1.MMW_PAR_DRUGLINK ADD CONSTRAINT PKMMWPARDRUGLINK
	PRIMARY KEY (ALLERGYID, KDC1)
/
ALTER TABLE DIB3_1.MMW_PAR_INGRLINK ADD CONSTRAINT PKMMWPARINGRLINK
	PRIMARY KEY (KDC1, INGREDKDC1)
/
ALTER TABLE DIB3_1.MMW_PAR_INT ADD CONSTRAINT PKMMWPARINT
	PRIMARY KEY (CLASSID1, CLASSID2, SYMPTOMCODE)
/
ALTER TABLE DIB3_1.MMW_PDE_DRUGLINK ADD CONSTRAINT PKMMWPDEDRUGLINK
	PRIMARY KEY (GPI, VERSIONCODE, MONOID)
/
ALTER TABLE DIB3_1.MMW_PRCA_COM ADD CONSTRAINT PKMMWPRCACOM
	PRIMARY KEY (GPI, AGEINDAYSLOW, AGEINDAYSHIGH, RESTRICTIONID, SEQUENCENUMBER)
/
ALTER TABLE DIB3_1.MMW_PRCA_DRUGLINK ADD CONSTRAINT PKMMWPRCADRUGLINK
	PRIMARY KEY (GPI, AGEINDAYSLOW, AGEINDAYSHIGH, RESTRICTIONID)
/
ALTER TABLE DIB3_1.MMW_PRCA_SPECCOND ADD CONSTRAINT PKMMWPRCASPECCOND
	PRIMARY KEY (GPI, AGEINDAYSLOW, AGEINDAYSHIGH, RESTRICTIONID, SPECCONDID)
/
ALTER TABLE DIB3_1.MMW_PRCC_COM ADD CONSTRAINT PKMMWPRCCCOM
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, SEQUENCENUMBER)
/
ALTER TABLE DIB3_1.MMW_PRCC_DRUGLINK ADD CONSTRAINT PKMMWPRCCDRUGLINK
	PRIMARY KEY (GPI, MCID, RESTRICTIONID)
/
ALTER TABLE DIB3_1.MMW_PRCC_SPECCOND ADD CONSTRAINT PKMMWPRCCSPECCOND
	PRIMARY KEY (GPI, MCID, RESTRICTIONID, SPECCONDID)
/
ALTER TABLE DIB3_1.MMW_SNOMED_MC_LINK ADD CONSTRAINT PKMMWSNOMEDMCLINK
	PRIMARY KEY (MCID, SNOMEDID, RELATIONTYPE)
/
ALTER TABLE DIB3_1.MMW_WL_DRUGLINK ADD CONSTRAINT PKMMWWLDRUGLINK
	PRIMARY KEY (GPI, WLID)
/
ALTER TABLE DIB3_1.MMW_WL_TEXT ADD CONSTRAINT PKMMWWLTEXT
	PRIMARY KEY (VERSIONCODE, WLID, SEQUENCENUMBER)
/
ALTER TABLE DIB3_1.MMW_WL_VENDCODE ADD CONSTRAINT PKMMWWLVENDCODE
	PRIMARY KEY (VERSIONCODE, WLID, VENDVERSIONCODE)
/
CREATE INDEX DIB3_1.IGPIDCI1 ON DIB3_1.IMGIPT_DESC
(
	CATEGORYID,
	BASICDESCID
)
/
CREATE INDEX DIB3_1.IGPIPCI1 ON DIB3_1.IMGIPT_PROP_DESC
(
	CATEGORYID,
	DESCRIPTORID
)
/
CREATE INDEX DIB3_1.IGPIPTI1 ON DIB3_1.IMGIPT_PROP_TEXT
(
	TEXTID
)
/
CREATE INDEX DIB3_1.IGPIUGI1 ON DIB3_1.IMGIPT_UNIQUE
(
	MANUFACTURERID
)
/
CREATE INDEX DIB3_1.IGPIUGI2 ON DIB3_1.IMGIPT_UNIQUE
(
	DOSAGEFORMID
)
/
CREATE INDEX DIB3_1.IGPIUJI1 ON DIB3_1.IMGIPT_JOURNAL
(
	PROPERTYID
)
/
CREATE INDEX DIB3_1.IGPIUJI2 ON DIB3_1.IMGIPT_JOURNAL
(
	IMAGEID
)
/
CREATE INDEX DIB3_1.IGPPRPI1 ON DIB3_1.IMGIPT_PROPERTY
(
	BASICCOLOR1ID,
	BASICCOLOR2ID,
	BASICCOLOR3ID
)
/
CREATE INDEX DIB3_1.IGPPRPI2 ON DIB3_1.IMGIPT_PROPERTY
(
	BASICSHAPEID
)
/
CREATE INDEX DIB3_1.IGPPRPI3 ON DIB3_1.IMGIPT_PROPERTY
(
	COLOR1ID,
	COLOR2ID,
	COLOR3ID
)
/
CREATE INDEX DIB3_1.IGPPRPI4 ON DIB3_1.IMGIPT_PROPERTY
(
	COATINGID
)
/
CREATE INDEX DIB3_1.IGPPRPI5 ON DIB3_1.IMGIPT_PROPERTY
(
	CLARITYID
)
/
CREATE INDEX DIB3_1.IGPPRPI6 ON DIB3_1.IMGIPT_PROPERTY
(
	FLAVORID
)
/
CREATE INDEX DIB3_1.IGPPRPI7 ON DIB3_1.IMGIPT_PROPERTY
(
	SHAPEID
)
/
CREATE INDEX DIB3_1.IGPPRPI8 ON DIB3_1.IMGIPT_PROPERTY
(
	IMPRINTSIDE1
)
/
CREATE INDEX DIB3_1.IGPPRPI9 ON DIB3_1.IMGIPT_PROPERTY
(
	IMPRINTSIDE2
)
/
CREATE INDEX DIB3_1.IXMMWADECOM1 ON DIB3_1.MMW_ADE_COM
(
	MCID
)
/
CREATE INDEX DIB3_1.IXMMWADEDRUGLINK1 ON DIB3_1.MMW_ADE_DRUGLINK
(
	MCID
)
/
CREATE INDEX DIB3_1.IXMMWADESPECCOND1 ON DIB3_1.MMW_ADE_SPECCOND
(
	MCID
)
/
CREATE INDEX DIB3_1.IXMMWCLSAHFS1 ON DIB3_1.MMW_CLS_AHFS
(
	DESCPHONETIC
)
/
CREATE INDEX DIB3_1.IXMMWCLSAHFS2 ON DIB3_1.MMW_CLS_AHFS
(
	DESCSEARCH
)
/
CREATE INDEX DIB3_1.IXMMWCLSAHFS3 ON DIB3_1.MMW_CLS_AHFS
(
	PARENTCLASSID
)
/
CREATE INDEX DIB3_1.IXMMWCLSAHFSDRUG1 ON DIB3_1.MMW_CLS_AHFSDRUG
(
	DRUGID
)
/
CREATE INDEX DIB3_1.IXMMWCLSGPI1 ON DIB3_1.MMW_CLS_GPI
(
	DESCPHONETIC
)
/
CREATE INDEX DIB3_1.IXMMWCLSGPI2 ON DIB3_1.MMW_CLS_GPI
(
	DESCSEARCH
)
/
CREATE INDEX DIB3_1.IXMMWCLSGPI3 ON DIB3_1.MMW_CLS_GPI
(
	PARENTCLASSID
)
/
CREATE INDEX DIB3_1.IXMMWCLSGPIDRUG1 ON DIB3_1.MMW_CLS_GPIDRUG
(
	DRUGID
)
/
CREATE INDEX DIB3_1.IXMMWDICLASSLINK1 ON DIB3_1.MMW_DI_CLASSLINK
(
	CLASSID,
	KDC1
)
/
CREATE INDEX DIB3_1.IXMMWDIINT1 ON DIB3_1.MMW_DI_INT
(
	CLASSID1,
	ACTCODE1,
	CLASSID2
)
/
CREATE INDEX DIB3_1.IXMMWDIINT2 ON DIB3_1.MMW_DI_INT
(
	CLASSID2
)
/
CREATE INDEX DIB3_1.IXMMWDRUGDISP1 ON DIB3_1.MMW_DRUG_DISP
(
	PNID
)
/
CREATE INDEX DIB3_1.IXMMWDRUGDISP2 ON DIB3_1.MMW_DRUG_DISP
(
	DESCPHONETIC
)
/
CREATE INDEX DIB3_1.IXMMWDRUGDISP3 ON DIB3_1.MMW_DRUG_DISP
(
	DESCSEARCH
)
/
CREATE INDEX DIB3_1.IXMMWDRUGDISP4 ON DIB3_1.MMW_DRUG_DISP
(
	GPI
)
/
CREATE INDEX DIB3_1.IXMMWDRUGDISP5 ON DIB3_1.MMW_DRUG_DISP
(
	RPID
)
/
CREATE INDEX DIB3_1.IXMMWDRUGNAME1 ON DIB3_1.MMW_DRUG_NAME
(
	DESCPHONETIC
)
/
CREATE INDEX DIB3_1.IXMMWDRUGNAME2 ON DIB3_1.MMW_DRUG_NAME
(
	DESCSEARCH
)
/
CREATE INDEX DIB3_1.IXMMWDRUGPACK1 ON DIB3_1.MMW_DRUG_PACK
(
	DDID
)
/
CREATE INDEX DIB3_1.IXMMWDRUGROUTED1 ON DIB3_1.MMW_DRUG_ROUTED
(
	DESCPHONETIC
)
/
CREATE INDEX DIB3_1.IXMMWDRUGROUTED2 ON DIB3_1.MMW_DRUG_ROUTED
(
	DESCSEARCH
)
/
CREATE INDEX DIB3_1.IXMMWDRUGROUTED3 ON DIB3_1.MMW_DRUG_ROUTED
(
	PNID
)
/
CREATE INDEX DIB3_1.IXMMWINDCOM1 ON DIB3_1.MMW_IND_COM
(
	MCID
)
/
CREATE INDEX DIB3_1.IXMMWINDCOTREAT1 ON DIB3_1.MMW_IND_COTREAT
(
	MCID
)
/
CREATE INDEX DIB3_1.IXMMWINDDRUGLINK1 ON DIB3_1.MMW_IND_DRUGLINK
(
	MCID
)
/
CREATE INDEX DIB3_1.IXMMWINDSOURCE1 ON DIB3_1.MMW_IND_SOURCE
(
	MCID
)
/
CREATE INDEX DIB3_1.IXMMWMEDEXTVOCAB1 ON DIB3_1.MMW_MED_EXTVOCAB
(
	EXTVOCABID
)
/
CREATE INDEX DIB3_1.IXMMWMEDINTVOCAB1 ON DIB3_1.MMW_MED_INTVOCAB
(
	MCID
)
/
CREATE INDEX DIB3_1.IXMMWMEDNAME1 ON DIB3_1.MMW_MED_NAME
(
	NAMEPHONETIC
)
/
CREATE INDEX DIB3_1.IXMMWMEDNAME2 ON DIB3_1.MMW_MED_NAME
(
	NAMESEARCH
)
/
CREATE INDEX DIB3_1.IXMMWPRCCCOM1 ON DIB3_1.MMW_PRCC_COM
(
	MCID
)
/
CREATE INDEX DIB3_1.IXMMWPRCCDRUGLINK1 ON DIB3_1.MMW_PRCC_DRUGLINK
(
	MCID
)
/
CREATE INDEX DIB3_1.IXMMWPRCCSPECCOND1 ON DIB3_1.MMW_PRCC_SPECCOND
(
	MCID
)
/
CREATE INDEX DIB3_1.IXMMWSNOMEDMCLINK1 ON DIB3_1.MMW_SNOMED_MC_LINK
(
	MCID
)
/
