 IF NOT EXISTS(SELECT * FROM sys.schemas WHERE [name] = N'WL_SBMO')      
     EXEC (N'CREATE SCHEMA WL_SBMO')                                   
 GO                                                               
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ADDRESSES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.ADDRESSES
GO
CREATE SYNONYM WL_SBMO.ADDRESSES FOR SBMO.ADDRESSES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.ADDRESSES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'ADDRESSES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ADJUSTMENT_CODES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.ADJUSTMENT_CODES
GO
CREATE SYNONYM WL_SBMO.ADJUSTMENT_CODES FOR SBMO.ADJUSTMENT_CODES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.ADJUSTMENT_CODES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'ADJUSTMENT_CODES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ADJUSTMENT_GROUP'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.ADJUSTMENT_GROUP
GO
CREATE SYNONYM WL_SBMO.ADJUSTMENT_GROUP FOR SBMO.ADJUSTMENT_GROUP
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.ADJUSTMENT_GROUP',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'ADJUSTMENT_GROUP'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'AUDIT_LOG'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.AUDIT_LOG
GO
CREATE SYNONYM WL_SBMO.AUDIT_LOG FOR SBMO.AUDIT_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.AUDIT_LOG',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'AUDIT_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'BIN_UPC_LINK'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.BIN_UPC_LINK
GO
CREATE SYNONYM WL_SBMO.BIN_UPC_LINK FOR SBMO.BIN_UPC_LINK
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.BIN_UPC_LINK',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'BIN_UPC_LINK'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CARRIER'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.CARRIER
GO
CREATE SYNONYM WL_SBMO.CARRIER FOR SBMO.CARRIER
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.CARRIER',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'CARRIER'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CF_SEC_CHAIN'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.CF_SEC_CHAIN
GO
CREATE SYNONYM WL_SBMO.CF_SEC_CHAIN FOR SBMO.CF_SEC_CHAIN
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.CF_SEC_CHAIN',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'CF_SEC_CHAIN'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CF_SEC_STORE'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.CF_SEC_STORE
GO
CREATE SYNONYM WL_SBMO.CF_SEC_STORE FOR SBMO.CF_SEC_STORE
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.CF_SEC_STORE',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'CF_SEC_STORE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CHAINS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.CHAINS
GO
CREATE SYNONYM WL_SBMO.CHAINS FOR SBMO.CHAINS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.CHAINS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'CHAINS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CHARGE_PAYMENT_INFO'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.CHARGE_PAYMENT_INFO
GO
CREATE SYNONYM WL_SBMO.CHARGE_PAYMENT_INFO FOR SBMO.CHARGE_PAYMENT_INFO
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.CHARGE_PAYMENT_INFO',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'CHARGE_PAYMENT_INFO'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CONTACTS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.CONTACTS
GO
CREATE SYNONYM WL_SBMO.CONTACTS FOR SBMO.CONTACTS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.CONTACTS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'CONTACTS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CUSTOM_SCHEDULED_TASK'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.CUSTOM_SCHEDULED_TASK
GO
CREATE SYNONYM WL_SBMO.CUSTOM_SCHEDULED_TASK FOR SBMO.CUSTOM_SCHEDULED_TASK
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.CUSTOM_SCHEDULED_TASK',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'CUSTOM_SCHEDULED_TASK'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DAILY_SCHEDULED_TASKS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.DAILY_SCHEDULED_TASKS
GO
CREATE SYNONYM WL_SBMO.DAILY_SCHEDULED_TASKS FOR SBMO.DAILY_SCHEDULED_TASKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.DAILY_SCHEDULED_TASKS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'DAILY_SCHEDULED_TASKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DASHBOARD_SETTINGS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.DASHBOARD_SETTINGS
GO
CREATE SYNONYM WL_SBMO.DASHBOARD_SETTINGS FOR SBMO.DASHBOARD_SETTINGS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.DASHBOARD_SETTINGS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'DASHBOARD_SETTINGS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DASHBOARD_STATISTICS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.DASHBOARD_STATISTICS
GO
CREATE SYNONYM WL_SBMO.DASHBOARD_STATISTICS FOR SBMO.DASHBOARD_STATISTICS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.DASHBOARD_STATISTICS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'DASHBOARD_STATISTICS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DISPENSER_LOCATION'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.DISPENSER_LOCATION
GO
CREATE SYNONYM WL_SBMO.DISPENSER_LOCATION FOR SBMO.DISPENSER_LOCATION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.DISPENSER_LOCATION',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'DISPENSER_LOCATION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DISPENSERS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.DISPENSERS
GO
CREATE SYNONYM WL_SBMO.DISPENSERS FOR SBMO.DISPENSERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.DISPENSERS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'DISPENSERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DRUG_ORDER_PRODUCT_VERIFY'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.DRUG_ORDER_PRODUCT_VERIFY
GO
CREATE SYNONYM WL_SBMO.DRUG_ORDER_PRODUCT_VERIFY FOR SBMO.DRUG_ORDER_PRODUCT_VERIFY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.DRUG_ORDER_PRODUCT_VERIFY',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'DRUG_ORDER_PRODUCT_VERIFY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DRUG_ORDERS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.DRUG_ORDERS
GO
CREATE SYNONYM WL_SBMO.DRUG_ORDERS FOR SBMO.DRUG_ORDERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.DRUG_ORDERS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'DRUG_ORDERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DRUGS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.DRUGS
GO
CREATE SYNONYM WL_SBMO.DRUGS FOR SBMO.DRUGS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.DRUGS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'DRUGS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ENCRYPTION_KEYS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.ENCRYPTION_KEYS
GO
CREATE SYNONYM WL_SBMO.ENCRYPTION_KEYS FOR SBMO.ENCRYPTION_KEYS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.ENCRYPTION_KEYS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'ENCRYPTION_KEYS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ENCRYPTION_KEYS_AUDIT'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.ENCRYPTION_KEYS_AUDIT
GO
CREATE SYNONYM WL_SBMO.ENCRYPTION_KEYS_AUDIT FOR SBMO.ENCRYPTION_KEYS_AUDIT
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.ENCRYPTION_KEYS_AUDIT',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'ENCRYPTION_KEYS_AUDIT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ENTITIES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.ENTITIES
GO
CREATE SYNONYM WL_SBMO.ENTITIES FOR SBMO.ENTITIES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.ENTITIES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'ENTITIES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'FACILITIES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.FACILITIES
GO
CREATE SYNONYM WL_SBMO.FACILITIES FOR SBMO.FACILITIES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.FACILITIES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'FACILITIES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'FILLING_STATION'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.FILLING_STATION
GO
CREATE SYNONYM WL_SBMO.FILLING_STATION FOR SBMO.FILLING_STATION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.FILLING_STATION',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'FILLING_STATION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'FORMULARY'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.FORMULARY
GO
CREATE SYNONYM WL_SBMO.FORMULARY FOR SBMO.FORMULARY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.FORMULARY',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'FORMULARY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'FORMULARY_REORDER'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.FORMULARY_REORDER
GO
CREATE SYNONYM WL_SBMO.FORMULARY_REORDER FOR SBMO.FORMULARY_REORDER
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.FORMULARY_REORDER',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'FORMULARY_REORDER'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'INVENTORY'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.INVENTORY
GO
CREATE SYNONYM WL_SBMO.INVENTORY FOR SBMO.INVENTORY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.INVENTORY',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'INVENTORY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'INVENTORY_AUDIT'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.INVENTORY_AUDIT
GO
CREATE SYNONYM WL_SBMO.INVENTORY_AUDIT FOR SBMO.INVENTORY_AUDIT
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.INVENTORY_AUDIT',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'INVENTORY_AUDIT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'INVENTORY_DATE'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.INVENTORY_DATE
GO
CREATE SYNONYM WL_SBMO.INVENTORY_DATE FOR SBMO.INVENTORY_DATE
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.INVENTORY_DATE',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'INVENTORY_DATE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ITEM_LOCATION'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.ITEM_LOCATION
GO
CREATE SYNONYM WL_SBMO.ITEM_LOCATION FOR SBMO.ITEM_LOCATION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.ITEM_LOCATION',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'ITEM_LOCATION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'LABEL_IMAGES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.LABEL_IMAGES
GO
CREATE SYNONYM WL_SBMO.LABEL_IMAGES FOR SBMO.LABEL_IMAGES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.LABEL_IMAGES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'LABEL_IMAGES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'LOCATION'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.LOCATION
GO
CREATE SYNONYM WL_SBMO.LOCATION FOR SBMO.LOCATION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.LOCATION',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'LOCATION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MASTER_PRODUCT_PO_VERIFY'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.MASTER_PRODUCT_PO_VERIFY
GO
CREATE SYNONYM WL_SBMO.MASTER_PRODUCT_PO_VERIFY FOR SBMO.MASTER_PRODUCT_PO_VERIFY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.MASTER_PRODUCT_PO_VERIFY',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'MASTER_PRODUCT_PO_VERIFY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MEDICAL_SUPPLIES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.MEDICAL_SUPPLIES
GO
CREATE SYNONYM WL_SBMO.MEDICAL_SUPPLIES FOR SBMO.MEDICAL_SUPPLIES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.MEDICAL_SUPPLIES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'MEDICAL_SUPPLIES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MESSAGE_LOG'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.MESSAGE_LOG
GO
CREATE SYNONYM WL_SBMO.MESSAGE_LOG FOR SBMO.MESSAGE_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.MESSAGE_LOG',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'MESSAGE_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MONTHLY_SCHEDULED_TASKS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.MONTHLY_SCHEDULED_TASKS
GO
CREATE SYNONYM WL_SBMO.MONTHLY_SCHEDULED_TASKS FOR SBMO.MONTHLY_SCHEDULED_TASKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.MONTHLY_SCHEDULED_TASKS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'MONTHLY_SCHEDULED_TASKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MUTEX'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.MUTEX
GO
CREATE SYNONYM WL_SBMO.MUTEX FOR SBMO.MUTEX
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.MUTEX',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'MUTEX'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MV_FORMULARY'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.MV_FORMULARY
GO
CREATE SYNONYM WL_SBMO.MV_FORMULARY FOR SBMO.MV_FORMULARY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.MV_FORMULARY',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'MV_FORMULARY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ONCE_SCHEDULED_TASKS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.ONCE_SCHEDULED_TASKS
GO
CREATE SYNONYM WL_SBMO.ONCE_SCHEDULED_TASKS FOR SBMO.ONCE_SCHEDULED_TASKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.ONCE_SCHEDULED_TASKS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'ONCE_SCHEDULED_TASKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ORDERS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.ORDERS
GO
CREATE SYNONYM WL_SBMO.ORDERS FOR SBMO.ORDERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.ORDERS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'ORDERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_CONFIG'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_CONFIG
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_CONFIG FOR SBMO.PDX_SCHEMA_CONFIG
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_CONFIG',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_CONFIG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_MAPPING'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_MAPPING
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_MAPPING FOR SBMO.PDX_SCHEMA_MAPPING
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_MAPPING',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_MAPPING'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_PRIV_DEFAULT'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_PRIV_DEFAULT
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_PRIV_DEFAULT FOR SBMO.PDX_SCHEMA_PRIV_DEFAULT
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_PRIV_DEFAULT',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_PRIV_DEFAULT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_PRIV_EXCEPTION'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_PRIV_EXCEPTION
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_PRIV_EXCEPTION FOR SBMO.PDX_SCHEMA_PRIV_EXCEPTION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_PRIV_EXCEPTION',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_PRIV_EXCEPTION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_PROCESS_HISTORY'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_PROCESS_HISTORY
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_PROCESS_HISTORY FOR SBMO.PDX_SCHEMA_PROCESS_HISTORY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_PROCESS_HISTORY',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_PROCESS_HISTORY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_TASK_ERROR_LOG'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_TASK_ERROR_LOG
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_TASK_ERROR_LOG FOR SBMO.PDX_SCHEMA_TASK_ERROR_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_TASK_ERROR_LOG',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_TASK_ERROR_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_TASK_HISTORY'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_TASK_HISTORY
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_TASK_HISTORY FOR SBMO.PDX_SCHEMA_TASK_HISTORY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_TASK_HISTORY',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_TASK_HISTORY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_UPD_PKGCALL_ERR_LOG'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG FOR SBMO.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_UPD_PKGCALL_ERR_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_UPD_PKGCALL_HIST'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_UPD_PKGCALL_HIST
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_UPD_PKGCALL_HIST FOR SBMO.PDX_SCHEMA_UPD_PKGCALL_HIST
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_UPD_PKGCALL_HIST',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_UPD_PKGCALL_HIST'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_UPDATER_MANIFEST'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_UPDATER_MANIFEST
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_UPDATER_MANIFEST FOR SBMO.PDX_SCHEMA_UPDATER_MANIFEST
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_UPDATER_MANIFEST',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_UPDATER_MANIFEST'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_UPDATER_SQL'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_UPDATER_SQL
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_UPDATER_SQL FOR SBMO.PDX_SCHEMA_UPDATER_SQL
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_UPDATER_SQL',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_UPDATER_SQL'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_VERSION_ERROR_LOG'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_VERSION_ERROR_LOG
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_VERSION_ERROR_LOG FOR SBMO.PDX_SCHEMA_VERSION_ERROR_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_VERSION_ERROR_LOG',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_VERSION_ERROR_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_VERSION_HISTORY'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PDX_SCHEMA_VERSION_HISTORY
GO
CREATE SYNONYM WL_SBMO.PDX_SCHEMA_VERSION_HISTORY FOR SBMO.PDX_SCHEMA_VERSION_HISTORY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PDX_SCHEMA_VERSION_HISTORY',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PDX_SCHEMA_VERSION_HISTORY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PHONE_ADDRESS_OWNERS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PHONE_ADDRESS_OWNERS
GO
CREATE SYNONYM WL_SBMO.PHONE_ADDRESS_OWNERS FOR SBMO.PHONE_ADDRESS_OWNERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PHONE_ADDRESS_OWNERS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PHONE_ADDRESS_OWNERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PHONES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PHONES
GO
CREATE SYNONYM WL_SBMO.PHONES FOR SBMO.PHONES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PHONES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PHONES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PRIORITY_CHANGE_ALERTS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PRIORITY_CHANGE_ALERTS
GO
CREATE SYNONYM WL_SBMO.PRIORITY_CHANGE_ALERTS FOR SBMO.PRIORITY_CHANGE_ALERTS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PRIORITY_CHANGE_ALERTS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PRIORITY_CHANGE_ALERTS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PURCHASE_ORDER'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PURCHASE_ORDER
GO
CREATE SYNONYM WL_SBMO.PURCHASE_ORDER FOR SBMO.PURCHASE_ORDER
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PURCHASE_ORDER',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PURCHASE_ORDER'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PURCHASE_ORDER_GROUP'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.PURCHASE_ORDER_GROUP
GO
CREATE SYNONYM WL_SBMO.PURCHASE_ORDER_GROUP FOR SBMO.PURCHASE_ORDER_GROUP
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.PURCHASE_ORDER_GROUP',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'PURCHASE_ORDER_GROUP'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_BLOB_TRIGGERS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.QRTZ_BLOB_TRIGGERS
GO
CREATE SYNONYM WL_SBMO.QRTZ_BLOB_TRIGGERS FOR SBMO.QRTZ_BLOB_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.QRTZ_BLOB_TRIGGERS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'QRTZ_BLOB_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_CALENDARS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.QRTZ_CALENDARS
GO
CREATE SYNONYM WL_SBMO.QRTZ_CALENDARS FOR SBMO.QRTZ_CALENDARS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.QRTZ_CALENDARS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'QRTZ_CALENDARS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_CRON_TRIGGERS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.QRTZ_CRON_TRIGGERS
GO
CREATE SYNONYM WL_SBMO.QRTZ_CRON_TRIGGERS FOR SBMO.QRTZ_CRON_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.QRTZ_CRON_TRIGGERS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'QRTZ_CRON_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_FIRED_TRIGGERS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.QRTZ_FIRED_TRIGGERS
GO
CREATE SYNONYM WL_SBMO.QRTZ_FIRED_TRIGGERS FOR SBMO.QRTZ_FIRED_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.QRTZ_FIRED_TRIGGERS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'QRTZ_FIRED_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_JOB_DETAILS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.QRTZ_JOB_DETAILS
GO
CREATE SYNONYM WL_SBMO.QRTZ_JOB_DETAILS FOR SBMO.QRTZ_JOB_DETAILS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.QRTZ_JOB_DETAILS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'QRTZ_JOB_DETAILS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_LOCKS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.QRTZ_LOCKS
GO
CREATE SYNONYM WL_SBMO.QRTZ_LOCKS FOR SBMO.QRTZ_LOCKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.QRTZ_LOCKS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'QRTZ_LOCKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_PAUSED_TRIGGER_GRPS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.QRTZ_PAUSED_TRIGGER_GRPS
GO
CREATE SYNONYM WL_SBMO.QRTZ_PAUSED_TRIGGER_GRPS FOR SBMO.QRTZ_PAUSED_TRIGGER_GRPS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.QRTZ_PAUSED_TRIGGER_GRPS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'QRTZ_PAUSED_TRIGGER_GRPS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_SCHEDULER_STATE'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.QRTZ_SCHEDULER_STATE
GO
CREATE SYNONYM WL_SBMO.QRTZ_SCHEDULER_STATE FOR SBMO.QRTZ_SCHEDULER_STATE
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.QRTZ_SCHEDULER_STATE',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'QRTZ_SCHEDULER_STATE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_SIMPLE_TRIGGERS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.QRTZ_SIMPLE_TRIGGERS
GO
CREATE SYNONYM WL_SBMO.QRTZ_SIMPLE_TRIGGERS FOR SBMO.QRTZ_SIMPLE_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.QRTZ_SIMPLE_TRIGGERS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'QRTZ_SIMPLE_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_SIMPROP_TRIGGERS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.QRTZ_SIMPROP_TRIGGERS
GO
CREATE SYNONYM WL_SBMO.QRTZ_SIMPROP_TRIGGERS FOR SBMO.QRTZ_SIMPROP_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.QRTZ_SIMPROP_TRIGGERS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'QRTZ_SIMPROP_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_TRIGGERS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.QRTZ_TRIGGERS
GO
CREATE SYNONYM WL_SBMO.QRTZ_TRIGGERS FOR SBMO.QRTZ_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.QRTZ_TRIGGERS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'QRTZ_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'REGION'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.REGION
GO
CREATE SYNONYM WL_SBMO.REGION FOR SBMO.REGION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.REGION',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'REGION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'REPORT_REQUEST'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.REPORT_REQUEST
GO
CREATE SYNONYM WL_SBMO.REPORT_REQUEST FOR SBMO.REPORT_REQUEST
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.REPORT_REQUEST',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'REPORT_REQUEST'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'REPORT_REQUEST_PARAMETER'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.REPORT_REQUEST_PARAMETER
GO
CREATE SYNONYM WL_SBMO.REPORT_REQUEST_PARAMETER FOR SBMO.REPORT_REQUEST_PARAMETER
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.REPORT_REQUEST_PARAMETER',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'REPORT_REQUEST_PARAMETER'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RETAIL_COST'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RETAIL_COST
GO
CREATE SYNONYM WL_SBMO.RETAIL_COST FOR SBMO.RETAIL_COST
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RETAIL_COST',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RETAIL_COST'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RETURN_AND_ADJUSTMENT'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RETURN_AND_ADJUSTMENT
GO
CREATE SYNONYM WL_SBMO.RETURN_AND_ADJUSTMENT FOR SBMO.RETURN_AND_ADJUSTMENT
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RETURN_AND_ADJUSTMENT',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RETURN_AND_ADJUSTMENT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_CORES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_CORES
GO
CREATE SYNONYM WL_SBMO.RX_CORES FOR SBMO.RX_CORES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_CORES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_CORES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_CORES_MIN_DATE'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_CORES_MIN_DATE
GO
CREATE SYNONYM WL_SBMO.RX_CORES_MIN_DATE FOR SBMO.RX_CORES_MIN_DATE
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_CORES_MIN_DATE',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_CORES_MIN_DATE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_DETAILS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_DETAILS
GO
CREATE SYNONYM WL_SBMO.RX_DETAILS FOR SBMO.RX_DETAILS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_DETAILS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_DETAILS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_DIGITAL_DOCUMENTS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_DIGITAL_DOCUMENTS
GO
CREATE SYNONYM WL_SBMO.RX_DIGITAL_DOCUMENTS FOR SBMO.RX_DIGITAL_DOCUMENTS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_DIGITAL_DOCUMENTS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_DIGITAL_DOCUMENTS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_DOCUMENTS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_DOCUMENTS
GO
CREATE SYNONYM WL_SBMO.RX_DOCUMENTS FOR SBMO.RX_DOCUMENTS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_DOCUMENTS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_DOCUMENTS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_HOURS_OF_ADMIN_DOSES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_HOURS_OF_ADMIN_DOSES
GO
CREATE SYNONYM WL_SBMO.RX_HOURS_OF_ADMIN_DOSES FOR SBMO.RX_HOURS_OF_ADMIN_DOSES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_HOURS_OF_ADMIN_DOSES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_HOURS_OF_ADMIN_DOSES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_HOURS_OF_ADMINISTRATION'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_HOURS_OF_ADMINISTRATION
GO
CREATE SYNONYM WL_SBMO.RX_HOURS_OF_ADMINISTRATION FOR SBMO.RX_HOURS_OF_ADMINISTRATION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_HOURS_OF_ADMINISTRATION',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_HOURS_OF_ADMINISTRATION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_IMAGE_DATA'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_IMAGE_DATA
GO
CREATE SYNONYM WL_SBMO.RX_IMAGE_DATA FOR SBMO.RX_IMAGE_DATA
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_IMAGE_DATA',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_IMAGE_DATA'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_LOTS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_LOTS
GO
CREATE SYNONYM WL_SBMO.RX_LOTS FOR SBMO.RX_LOTS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_LOTS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_LOTS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_PATSTORES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_PATSTORES
GO
CREATE SYNONYM WL_SBMO.RX_PATSTORES FOR SBMO.RX_PATSTORES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_PATSTORES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_PATSTORES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_PRINT_CHR'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_PRINT_CHR
GO
CREATE SYNONYM WL_SBMO.RX_PRINT_CHR FOR SBMO.RX_PRINT_CHR
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_PRINT_CHR',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_PRINT_CHR'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_PRINT_INFO'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_PRINT_INFO
GO
CREATE SYNONYM WL_SBMO.RX_PRINT_INFO FOR SBMO.RX_PRINT_INFO
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_PRINT_INFO',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_PRINT_INFO'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_REQUEST_ERROR'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_REQUEST_ERROR
GO
CREATE SYNONYM WL_SBMO.RX_REQUEST_ERROR FOR SBMO.RX_REQUEST_ERROR
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_REQUEST_ERROR',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_REQUEST_ERROR'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_SHIPPING_PACKAGES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_SHIPPING_PACKAGES
GO
CREATE SYNONYM WL_SBMO.RX_SHIPPING_PACKAGES FOR SBMO.RX_SHIPPING_PACKAGES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_SHIPPING_PACKAGES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_SHIPPING_PACKAGES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_STATE_TRANSITION'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_STATE_TRANSITION
GO
CREATE SYNONYM WL_SBMO.RX_STATE_TRANSITION FOR SBMO.RX_STATE_TRANSITION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_STATE_TRANSITION',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_STATE_TRANSITION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_TP_INFO'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_TP_INFO
GO
CREATE SYNONYM WL_SBMO.RX_TP_INFO FOR SBMO.RX_TP_INFO
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_TP_INFO',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_TP_INFO'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_VIAL_INFOS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_VIAL_INFOS
GO
CREATE SYNONYM WL_SBMO.RX_VIAL_INFOS FOR SBMO.RX_VIAL_INFOS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_VIAL_INFOS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_VIAL_INFOS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_WARNING_LABEL_CODES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_WARNING_LABEL_CODES
GO
CREATE SYNONYM WL_SBMO.RX_WARNING_LABEL_CODES FOR SBMO.RX_WARNING_LABEL_CODES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_WARNING_LABEL_CODES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_WARNING_LABEL_CODES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_WARNING_LABELS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.RX_WARNING_LABELS
GO
CREATE SYNONYM WL_SBMO.RX_WARNING_LABELS FOR SBMO.RX_WARNING_LABELS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.RX_WARNING_LABELS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'RX_WARNING_LABELS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SBMO_LOCKS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.SBMO_LOCKS
GO
CREATE SYNONYM WL_SBMO.SBMO_LOCKS FOR SBMO.SBMO_LOCKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.SBMO_LOCKS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'SBMO_LOCKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SBMO_PROPERTIES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.SBMO_PROPERTIES
GO
CREATE SYNONYM WL_SBMO.SBMO_PROPERTIES FOR SBMO.SBMO_PROPERTIES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.SBMO_PROPERTIES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'SBMO_PROPERTIES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SCHEDULED_TASKS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.SCHEDULED_TASKS
GO
CREATE SYNONYM WL_SBMO.SCHEDULED_TASKS FOR SBMO.SCHEDULED_TASKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.SCHEDULED_TASKS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'SCHEDULED_TASKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SCHEMA_UPDATER_MANIFEST'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.SCHEMA_UPDATER_MANIFEST
GO
CREATE SYNONYM WL_SBMO.SCHEMA_UPDATER_MANIFEST FOR SBMO.SCHEMA_UPDATER_MANIFEST
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.SCHEMA_UPDATER_MANIFEST',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'SCHEMA_UPDATER_MANIFEST'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SCHEMA_UPDATER_SQL'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.SCHEMA_UPDATER_SQL
GO
CREATE SYNONYM WL_SBMO.SCHEMA_UPDATER_SQL FOR SBMO.SCHEMA_UPDATER_SQL
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.SCHEMA_UPDATER_SQL',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'SCHEMA_UPDATER_SQL'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SHIP_ITEMS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.SHIP_ITEMS
GO
CREATE SYNONYM WL_SBMO.SHIP_ITEMS FOR SBMO.SHIP_ITEMS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.SHIP_ITEMS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'SHIP_ITEMS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SHIPMENT'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.SHIPMENT
GO
CREATE SYNONYM WL_SBMO.SHIPMENT FOR SBMO.SHIPMENT
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.SHIPMENT',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'SHIPMENT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORE_SHIP_VIA'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.STORE_SHIP_VIA
GO
CREATE SYNONYM WL_SBMO.STORE_SHIP_VIA FOR SBMO.STORE_SHIP_VIA
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.STORE_SHIP_VIA',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'STORE_SHIP_VIA'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORE_VENDOR_ACCOUNT'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.STORE_VENDOR_ACCOUNT
GO
CREATE SYNONYM WL_SBMO.STORE_VENDOR_ACCOUNT FOR SBMO.STORE_VENDOR_ACCOUNT
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.STORE_VENDOR_ACCOUNT',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'STORE_VENDOR_ACCOUNT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.STORES
GO
CREATE SYNONYM WL_SBMO.STORES FOR SBMO.STORES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.STORES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'STORES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SYSTEM_MESSAGES'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.SYSTEM_MESSAGES
GO
CREATE SYNONYM WL_SBMO.SYSTEM_MESSAGES FOR SBMO.SYSTEM_MESSAGES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.SYSTEM_MESSAGES',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'SYSTEM_MESSAGES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'TENANTS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.TENANTS
GO
CREATE SYNONYM WL_SBMO.TENANTS FOR SBMO.TENANTS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.TENANTS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'TENANTS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'USER_AUDIT_LOG'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.USER_AUDIT_LOG
GO
CREATE SYNONYM WL_SBMO.USER_AUDIT_LOG FOR SBMO.USER_AUDIT_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.USER_AUDIT_LOG',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'USER_AUDIT_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'VENDOR'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.VENDOR
GO
CREATE SYNONYM WL_SBMO.VENDOR FOR SBMO.VENDOR
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.VENDOR',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'VENDOR'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'VENDOR_ITEM_PROP'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.VENDOR_ITEM_PROP
GO
CREATE SYNONYM WL_SBMO.VENDOR_ITEM_PROP FOR SBMO.VENDOR_ITEM_PROP
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.VENDOR_ITEM_PROP',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'VENDOR_ITEM_PROP'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'VENDOR_PO_CREATE_DAYS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.VENDOR_PO_CREATE_DAYS
GO
CREATE SYNONYM WL_SBMO.VENDOR_PO_CREATE_DAYS FOR SBMO.VENDOR_PO_CREATE_DAYS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.VENDOR_PO_CREATE_DAYS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'VENDOR_PO_CREATE_DAYS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'VENDOR_PROP'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.VENDOR_PROP
GO
CREATE SYNONYM WL_SBMO.VENDOR_PROP FOR SBMO.VENDOR_PROP
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.VENDOR_PROP',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'VENDOR_PROP'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'VISUALLY_IMPAIRED_DETAILS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.VISUALLY_IMPAIRED_DETAILS
GO
CREATE SYNONYM WL_SBMO.VISUALLY_IMPAIRED_DETAILS FOR SBMO.VISUALLY_IMPAIRED_DETAILS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.VISUALLY_IMPAIRED_DETAILS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'VISUALLY_IMPAIRED_DETAILS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'WEEKLY_SCHEDULED_TASKS'  AND sc.name=N'WL_SBMO'  AND type in (N'SN'))
 DROP SYNONYM WL_SBMO.WEEKLY_SCHEDULED_TASKS
GO
CREATE SYNONYM WL_SBMO.WEEKLY_SCHEDULED_TASKS FOR SBMO.WEEKLY_SCHEDULED_TASKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'WL_SBMO.WEEKLY_SCHEDULED_TASKS',
        N'SCHEMA', N'WL_SBMO',
        N'SYNONYM', N'WEEKLY_SCHEDULED_TASKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
