CREATE TABLE DIB3_AUX.AGFILE
( 
	AG CHAR(3) NOT NULL,
	ACLASS VARCHAR2(25),
	CSC_0 CHAR(3),
	CSC_1 CHAR(3),
	CSC_2 CHAR(3),
	CSC_3 CHAR(3),
	CSC_4 CHAR(3),
	CSC_5 CHAR(3),
	CR CHAR(1)
)
/
CREATE TABLE DIB3_AUX.DISFILE
( 
	CODE VARCHAR2(10) NOT NULL,
	DESCRIPTION VARCHAR2(25) NOT NULL,
	MNEMONIC VARCHAR2(10) NOT NULL,
	DURATION VARCHAR2(1) NOT NULL,
	DEACTIVATE_DATE TIMESTAMP(6)
)
/
CREATE TABLE DIB3_AUX.MMW_FC_CONTENT
( 
	ID NUMBER(6, 0) NOT NULL,
	CONTENT CLOB
)
/
CREATE TABLE DIB3_AUX.MMW_FC_DRUGLINK
( 
	DRUGID VARCHAR2(20) NOT NULL,
	ELEMENTID NUMBER(38, 0) NOT NULL,
	DOCUMENTCODE VARCHAR2(10) NOT NULL
)
/
CREATE TABLE DIB3_AUX.MMW_FC_ELEMENT
( 
	ELEMENTID NUMBER(38, 0) NOT NULL,
	DOCUMENTCODE VARCHAR2(10) NOT NULL,
	PARENTID NUMBER(38, 0) NOT NULL,
	CHILDSEQUENCE NUMBER(38, 0) NOT NULL,
	TAGTYPE VARCHAR2(40) NOT NULL,
	IDATTRIBUTE VARCHAR2(32),
	HASSECTIONSIND NUMBER(38, 0) NOT NULL,
	FILENAME VARCHAR2(30) NOT NULL,
	ELEMENTTITLE VARCHAR2(255) NOT NULL,
	XPATH VARCHAR2(255)
)
/
CREATE TABLE DIB3_AUX.MMW_FC_SECTION
( 
	SECTIONID NUMBER(38, 0) NOT NULL,
	SECTIONTITLE VARCHAR2(40) NOT NULL,
	XPATH VARCHAR2(255) NOT NULL
)
/
CREATE TABLE DIB3_AUX.MMW_FC_SECTION_CONTENT
( 
	MONOGRAPH_ID NUMBER(6, 0) NOT NULL,
	SECTION_ID NUMBER(22, 0) NOT NULL,
	CONTENT CLOB
)
/
CREATE TABLE DIB3_AUX.MMW_FC_SECTIONLINK
( 
	ELEMENTID NUMBER(38, 0) NOT NULL,
	SECTIONID NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE DIB3_AUX.TOP_DRUGS
( 
	DESCSEARCH VARCHAR2(35)
)
/
ALTER TABLE DIB3_AUX.MMW_FC_CONTENT ADD CONSTRAINT MMW_FC_CONTENT_ID_PK_1
	PRIMARY KEY (ID)
/
ALTER TABLE DIB3_AUX.MMW_FC_DRUGLINK ADD CONSTRAINT PKMMWFCDRUGLINK
	PRIMARY KEY (DRUGID, ELEMENTID, DOCUMENTCODE)
/
ALTER TABLE DIB3_AUX.MMW_FC_ELEMENT ADD CONSTRAINT PKMMWFCELEMENT
	PRIMARY KEY (ELEMENTID)
/
ALTER TABLE DIB3_AUX.MMW_FC_SECTION ADD CONSTRAINT PKMMWFCSECTION
	PRIMARY KEY (SECTIONID)
/
ALTER TABLE DIB3_AUX.MMW_FC_SECTION_CONTENT ADD CONSTRAINT MMW_FC_SECTION_CONTENT_PK
	PRIMARY KEY (MONOGRAPH_ID, SECTION_ID)
/
ALTER TABLE DIB3_AUX.MMW_FC_SECTIONLINK ADD CONSTRAINT PKMMWFCSECTIONLINK
	PRIMARY KEY (ELEMENTID, SECTIONID)
/
CREATE INDEX DIB3_AUX.IXMMWFCELEMENT1 ON DIB3_AUX.MMW_FC_ELEMENT
(
	IDATTRIBUTE
)
/
