-- ============================================================================
-- BATCH_CREATE_TABLES_BATCH11.sql
-- Purpose: Create 17 tables (Batch 11)
-- Tables: SIGNATURE, SIGNATURE_AUDIT, STAT_EXP, TELEPHONE, TELEPHONE_AUDIT,
--         TEMP_BAD_PHONE_NUMBERS, TEMP_PURGE, TEMP_STATS, TP_CSD5570_DROPAFTER20181011,
--         TP_LINK, TP_LINK_AUDIT, TX_CRED, TX_CRED_AUDIT, TX_LOT, TX_LOT_AUDIT, TX_TP, TX_TP_AUDIT
-- ============================================================================

-- DROP EXISTING TABLES (in reverse dependency order)
IF OBJECT_ID('[EPS].[TX_TP_AUDIT]', 'U') IS NOT NULL DROP TABLE [EPS].[TX_TP_AUDIT];
IF OBJECT_ID('[EPS].[TX_TP]', 'U') IS NOT NULL DROP TABLE [EPS].[TX_TP];
IF OBJECT_ID('[EPS].[TX_LOT_AUDIT]', 'U') IS NOT NULL DROP TABLE [EPS].[TX_LOT_AUDIT];
IF OBJECT_ID('[EPS].[TX_LOT]', 'U') IS NOT NULL DROP TABLE [EPS].[TX_LOT];
IF OBJECT_ID('[EPS].[TX_CRED_AUDIT]', 'U') IS NOT NULL DROP TABLE [EPS].[TX_CRED_AUDIT];
IF OBJECT_ID('[EPS].[TX_CRED]', 'U') IS NOT NULL DROP TABLE [EPS].[TX_CRED];
IF OBJECT_ID('[EPS].[TP_LINK_AUDIT]', 'U') IS NOT NULL DROP TABLE [EPS].[TP_LINK_AUDIT];
IF OBJECT_ID('[EPS].[TP_LINK]', 'U') IS NOT NULL DROP TABLE [EPS].[TP_LINK];
IF OBJECT_ID('[EPS].[TP_CSD5570_DROPAFTER20181011]', 'U') IS NOT NULL DROP TABLE [EPS].[TP_CSD5570_DROPAFTER20181011];
IF OBJECT_ID('[EPS].[TEMP_STATS]', 'U') IS NOT NULL DROP TABLE [EPS].[TEMP_STATS];
IF OBJECT_ID('[EPS].[TEMP_PURGE]', 'U') IS NOT NULL DROP TABLE [EPS].[TEMP_PURGE];
IF OBJECT_ID('[EPS].[TEMP_BAD_PHONE_NUMBERS]', 'U') IS NOT NULL DROP TABLE [EPS].[TEMP_BAD_PHONE_NUMBERS];
IF OBJECT_ID('[EPS].[TELEPHONE_AUDIT]', 'U') IS NOT NULL DROP TABLE [EPS].[TELEPHONE_AUDIT];
IF OBJECT_ID('[EPS].[TELEPHONE]', 'U') IS NOT NULL DROP TABLE [EPS].[TELEPHONE];
IF OBJECT_ID('[EPS].[STAT_EXP]', 'U') IS NOT NULL DROP TABLE [EPS].[STAT_EXP];
IF OBJECT_ID('[EPS].[SIGNATURE_AUDIT]', 'U') IS NOT NULL DROP TABLE [EPS].[SIGNATURE_AUDIT];
IF OBJECT_ID('[EPS].[SIGNATURE]', 'U') IS NOT NULL DROP TABLE [EPS].[SIGNATURE];

-- ============================================================================

-- EXTERNAL FK DEPENDENCIES:
--   - SIGNATURE: 1 FK removed (CHAIN_ID, ID_PATIENT→PATIENT)
--   - SIGNATURE_AUDIT: 1 FK removed (same as SIGNATURE)
--   - TELEPHONE: 1 FK removed (CHAIN_ID, ID_PATIENT→PATIENT)
--   - TELEPHONE_AUDIT: 1 FK removed (same as TELEPHONE)
--   - TP_LINK: 2 FKs removed (CHAIN_ID, ID_CARD→CARD; CHAIN_ID, ID_PATIENT→PATIENT)
--   - TP_LINK_AUDIT: 2 FKs removed (same as TP_LINK)
--   See REMOVED_FK_RESTORATION_SCRIPTS.sql Section 7 for post-prerequisite restoration

-- INTERNAL FK DEPENDENCIES (SAME BATCH OR EXISTING):
--   - SIGNATURE: FK to SEC_ADMIN.EPS_SEC_CHAIN - INTERNAL, KEEP
--   - TELEPHONE: FK to SEC_ADMIN.EPS_SEC_CHAIN - INTERNAL, KEEP
--   - TELEPHONE: FK to SEC_ADMIN.EPS_SEC_STORE - INTERNAL, KEEP
--   - TP_LINK: FK to SEC_ADMIN.EPS_SEC_CHAIN - INTERNAL, KEEP
--   - TP_LINK: FK to SEC_ADMIN.EPS_SEC_STORE - INTERNAL, KEEP
--   - TX_CRED: FK to SEC_ADMIN.EPS_SEC_CHAIN - INTERNAL, KEEP
--   - TX_CRED: FK to SEC_ADMIN.EPS_SEC_STORE - INTERNAL, KEEP
--   - TX_CRED: FK to RX_TX (CHAIN_ID, ID_RX_TX) - INTERNAL (from Batch 10), KEEP
--   - TX_LOT: FK to RX_TX (CHAIN_ID, ID_RX_TX) - INTERNAL (from Batch 10), ADD
--   - TX_TP: FK to SEC_ADMIN.EPS_SEC_CHAIN - INTERNAL, KEEP
--   - TX_TP: FK to SEC_ADMIN.EPS_SEC_STORE - INTERNAL, KEEP
--   - TX_TP: FK to RX_TX (CHAIN_ID, ID_RX_TX) - INTERNAL (from Batch 10), KEEP

-- PROACTIVE DATA TYPE FIXES APPLIED:
--   - NUMBER → BIGINT (for all ID, ID_PATIENT, NHIN_ID, ID_RX_TX, ID_CARD columns)
--   - NUMBER(22,0) → BIGINT (for CHAIN_ID, ID, ID_RX_TX in TX_LOT)
--   - NUMBER(13,4) → NUMERIC(13,4) (for currency fields)
--   - All DATETIME2 scales verified (all TIMESTAMP(6) → DATETIME2(6))
--   - All PK columns verified NOT NULL (E006 prevention)
--   - All RAW types → VARBINARY

-- CREATION ORDER:
--   1. Utility tables (no dependencies): STAT_EXP, TEMP_BAD_PHONE_NUMBERS, TEMP_PURGE, TEMP_STATS, TP_CSD5570_DROPAFTER20181011
--   2. Main reference tables: SIGNATURE, TELEPHONE, TP_LINK, TX_CRED, TX_LOT, TX_TP
--   3. Audit variants: SIGNATURE_AUDIT, TELEPHONE_AUDIT, TP_LINK_AUDIT, TX_CRED_AUDIT, TX_LOT_AUDIT, TX_TP_AUDIT

-- ============================================================================

-- UTILITY TABLES (no dependencies)

CREATE TABLE [EPS].[STAT_EXP] (
    [STATID] VARCHAR(30) NULL,
    [TYPE] CHAR(1) NULL,
    [VERSION] BIGINT NULL,
    [FLAGS] BIGINT NULL,
    [C1] VARCHAR(30) NULL,
    [C2] VARCHAR(30) NULL,
    [C3] VARCHAR(30) NULL,
    [C4] VARCHAR(30) NULL,
    [C5] VARCHAR(30) NULL,
    [N1] BIGINT NULL,
    [N2] BIGINT NULL,
    [N3] BIGINT NULL,
    [N4] BIGINT NULL,
    [N5] BIGINT NULL,
    [N6] BIGINT NULL,
    [N7] BIGINT NULL,
    [N8] BIGINT NULL,
    [N9] BIGINT NULL,
    [N10] BIGINT NULL,
    [N11] BIGINT NULL,
    [N12] BIGINT NULL,
    [D1] DATE NULL,
    [R1] VARBINARY(32) NULL,
    [R2] VARBINARY(32) NULL,
    [CH1] VARCHAR(1000) NULL
);

CREATE TABLE [EPS].[TEMP_BAD_PHONE_NUMBERS] (
    [STORE_ID] BIGINT NOT NULL,
    [NHIN_ID] BIGINT NOT NULL,
    [AREA_CODE] VARCHAR(3) NOT NULL,
    [PHONE_NUMBER] VARCHAR(7) NOT NULL
);

CREATE TABLE [EPS].[TEMP_PURGE] (
    [TABLE_NAME] VARCHAR(100) NULL,
    [PART_NAME] VARCHAR(100) NULL,
    [CHAIN_ID] BIGINT NULL,
    [ID] BIGINT NULL
);

CREATE TABLE [EPS].[TEMP_STATS] (
    [STATID] VARCHAR(30) NULL,
    [TYPE] CHAR(1) NULL,
    [VERSION] BIGINT NULL,
    [FLAGS] BIGINT NULL,
    [C1] VARCHAR(30) NULL,
    [C2] VARCHAR(30) NULL,
    [C3] VARCHAR(30) NULL,
    [C4] VARCHAR(30) NULL,
    [C5] VARCHAR(30) NULL,
    [N1] BIGINT NULL,
    [N2] BIGINT NULL,
    [N3] BIGINT NULL,
    [N4] BIGINT NULL,
    [N5] BIGINT NULL,
    [N6] BIGINT NULL,
    [N7] BIGINT NULL,
    [N8] BIGINT NULL,
    [N9] BIGINT NULL,
    [N10] BIGINT NULL,
    [N11] BIGINT NULL,
    [N12] BIGINT NULL,
    [D1] DATE NULL,
    [R1] VARBINARY(32) NULL,
    [R2] VARBINARY(32) NULL,
    [CH1] VARCHAR(1000) NULL
);

CREATE TABLE [EPS].[TP_CSD5570_DROPAFTER20181011] (
    [CHAIN_ID] BIGINT NULL,
    [ID] BIGINT NULL,
    [EMPLOYER_NAME] VARCHAR(30) NULL
);

-- MAIN REFERENCE TABLES

CREATE TABLE [EPS].[SIGNATURE] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [SIGNATURE_NUMBER] BIGINT NOT NULL,
    [STORE_LAST_UPDATED] DATE NULL,
    [ORIGINAL_NHIN_ID] BIGINT NOT NULL,
    [DOCUMENT_CODE] VARCHAR(10) NOT NULL,
    [DOCUMENT_VERSION] BIGINT NOT NULL,
    [STATE] VARCHAR(2) NULL,
    [LANG] VARCHAR(2) NULL,
    [DOCUMENT_NAME] VARCHAR(25) NULL,
    [ACQUIRED_STORE_ID] VARCHAR(10) NULL,
    [ACQUIRED_DATE] DATE NULL,
    [REVOKED_AT_STORE] VARCHAR(10) NULL,
    [REVOKE_DATE] DATE NULL,
    [EXPIRATION_DATE] DATE NULL,
    [STATUS] VARCHAR(1) NULL,
    [LOCATION] VARCHAR(60) NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [ID_AAL] BIGINT NOT NULL,
    [LAST_UPDATED] DATE NULL,
    [DELETED] VARCHAR(1) NULL,
    CONSTRAINT [PK_SIGNATURE] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [FK_SIGNATURE_ESCHAIN] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID])
);

CREATE TABLE [EPS].[SIGNATURE_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [SIGNATURE_NUMBER] BIGINT NOT NULL,
    [STORE_LAST_UPDATED] DATE NULL,
    [ORIGINAL_NHIN_ID] BIGINT NOT NULL,
    [DOCUMENT_CODE] VARCHAR(10) NOT NULL,
    [DOCUMENT_VERSION] BIGINT NOT NULL,
    [STATE] VARCHAR(2) NULL,
    [LANG] VARCHAR(2) NULL,
    [DOCUMENT_NAME] VARCHAR(25) NULL,
    [ACQUIRED_STORE_ID] VARCHAR(10) NULL,
    [ACQUIRED_DATE] DATE NULL,
    [REVOKED_AT_STORE] VARCHAR(10) NULL,
    [REVOKE_DATE] DATE NULL,
    [EXPIRATION_DATE] DATE NULL,
    [STATUS] VARCHAR(1) NULL,
    [LOCATION] VARCHAR(60) NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [ID_AAL] BIGINT NOT NULL,
    [LAST_UPDATED] DATE NULL,
    [DELETED] VARCHAR(1) NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    CONSTRAINT [PK_SIGNATURE_AUDIT] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[TELEPHONE] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [ADDRESS_KEY] BIGINT NULL,
    [AREA_CODE] VARCHAR(3) NULL,
    [COUNTRY_CODE] VARCHAR(4) NULL,
    [LOCATION_TYPE] VARCHAR(3) NULL,
    [PHONE_NUMBER] VARCHAR(7) NULL,
    [ID_PATIENT] BIGINT NULL,
    [ID_AAL] BIGINT NULL,
    [PHONE_NUMBER_UPDATED_DATE] DATETIME2(6) NULL,
    CONSTRAINT [PK_TELEPHONE] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [FK_TELEPHONE_ESCHAIN] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID]),
    CONSTRAINT [FK_TELEPHONE_ESSTORE] FOREIGN KEY ([CHAIN_ID], [NHIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_STORE] ([CHAIN_NHIN_ID], [STORE_NHIN_ID])
);

CREATE TABLE [EPS].[TELEPHONE_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [ADDRESS_KEY] BIGINT NULL,
    [AREA_CODE] VARCHAR(3) NULL,
    [COUNTRY_CODE] VARCHAR(4) NULL,
    [LOCATION_TYPE] VARCHAR(3) NULL,
    [PHONE_NUMBER] VARCHAR(7) NULL,
    [ID_PATIENT] BIGINT NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    [PHONE_NUMBER_UPDATED_DATE] DATETIME2(6) NULL,
    CONSTRAINT [PK_TELEPHONE_AUDIT] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[TP_LINK] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [LAST] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [ADC] CHAR(1) NULL,
    [ALT_CARD] VARCHAR(20) NULL,
    [BC_HOME] VARCHAR(20) NULL,
    [CARD_NUMBER] VARCHAR(20) NULL,
    [CARRIER_ID] VARCHAR(10) NULL,
    [CLINIC_ID] VARCHAR(30) NULL,
    [DEPENDENT_NUMBER] VARCHAR(3) NULL,
    [ELIGIBILITY_OVERRIDE] CHAR(1) NULL,
    [ELIGIBLE] CHAR(1) NULL,
    [ELIGIBLE_ENDING] DATE NULL,
    [ELIGIBLE_STARTING] DATE NULL,
    [EMPLOYER_NAME] VARCHAR(30) NULL,
    [GROUP_NUMBER] VARCHAR(15) NULL,
    [LEVEL_OF] VARCHAR(3) NULL,
    [LOCATION] VARCHAR(2) NULL,
    [NURSING_HOME] CHAR(1) NULL,
    [OTHER] CHAR(1) NULL,
    [PLAN_NUMBER] VARCHAR(15) NULL,
    [RELATION] CHAR(1) NULL,
    [SENIOR_CITIZEN] CHAR(1) NULL,
    [SERIES_CODE] CHAR(1) NULL,
    [SPECIAL] CHAR(1) NULL,
    [STUDENT] CHAR(1) NULL,
    [ID_PATIENT] BIGINT NULL,
    [ID_CARD] BIGINT NULL,
    [ID_AAL] BIGINT NULL,
    [TP_SOURCE] VARCHAR(1) NULL,
    [OTHER_INSURANCE_FEE] VARCHAR(1) NULL,
    [TP_ESCRIPT_PLAN] VARCHAR(1) NULL,
    [RESIDENCE] VARCHAR(2) NULL,
    [CMS_PART_D_QUALIFIED_FACILITY] VARCHAR(1) NULL,
    [BENEFITS_NOT_ASSIGNED] VARCHAR(1) NULL,
    [MEDICAID_IDENTIFIER] VARCHAR(20) NULL,
    [MEDICAID_INDICATOR] VARCHAR(2) NULL,
    [DISCOUNT_FLAG] VARCHAR(1) NULL,
    [CARD_DESCRIPTION] VARCHAR(30) NULL,
    [ADDED_DATE] DATETIME2(6) NULL,
    [ADDED_BY_USER] VARCHAR(255) NULL,
    CONSTRAINT [PK_TP_LINK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [FK_TP_LINK_ESCHAIN] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID]),
    CONSTRAINT [FK_TP_LINK_ESSTORE] FOREIGN KEY ([CHAIN_ID], [NHIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_STORE] ([CHAIN_NHIN_ID], [STORE_NHIN_ID])
);

CREATE TABLE [EPS].[TP_LINK_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [LAST] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [ADC] CHAR(1) NULL,
    [ALT_CARD] VARCHAR(20) NULL,
    [BC_HOME] VARCHAR(20) NULL,
    [CARD_NUMBER] VARCHAR(20) NULL,
    [CARRIER_ID] VARCHAR(10) NULL,
    [CLINIC_ID] VARCHAR(30) NULL,
    [DEPENDENT_NUMBER] VARCHAR(3) NULL,
    [ELIGIBILITY_OVERRIDE] CHAR(1) NULL,
    [ELIGIBLE] CHAR(1) NULL,
    [ELIGIBLE_ENDING] DATE NULL,
    [ELIGIBLE_STARTING] DATE NULL,
    [EMPLOYER_NAME] VARCHAR(30) NULL,
    [GROUP_NUMBER] VARCHAR(15) NULL,
    [LEVEL_OF] VARCHAR(3) NULL,
    [LOCATION] VARCHAR(2) NULL,
    [NURSING_HOME] CHAR(1) NULL,
    [OTHER] CHAR(1) NULL,
    [PLAN_NUMBER] VARCHAR(15) NULL,
    [RELATION] CHAR(1) NULL,
    [SENIOR_CITIZEN] CHAR(1) NULL,
    [SERIES_CODE] CHAR(1) NULL,
    [SPECIAL] CHAR(1) NULL,
    [STUDENT] CHAR(1) NULL,
    [ID_PATIENT] BIGINT NULL,
    [ID_CARD] BIGINT NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [TP_SOURCE] VARCHAR(1) NULL,
    [OTHER_INSURANCE_FEE] VARCHAR(1) NULL,
    [TP_ESCRIPT_PLAN] VARCHAR(1) NULL,
    [RESIDENCE] VARCHAR(2) NULL,
    [CMS_PART_D_QUALIFIED_FACILITY] VARCHAR(1) NULL,
    [BENEFITS_NOT_ASSIGNED] VARCHAR(1) NULL,
    [MEDICAID_IDENTIFIER] VARCHAR(20) NULL,
    [MEDICAID_INDICATOR] VARCHAR(2) NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    [DISCOUNT_FLAG] VARCHAR(1) NULL,
    [CARD_DESCRIPTION] VARCHAR(30) NULL,
    [ADDED_DATE] DATETIME2(6) NULL,
    [ADDED_BY_USER] VARCHAR(255) NULL,
    CONSTRAINT [PK_TP_LINK_AUDIT] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[TX_CRED] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [INITIALS] VARCHAR(3) NULL,
    [ORG_PRICE] NUMERIC(13, 4) NULL,
    [ORG_QTY] BIGINT NULL,
    [ORG_TX_NUM] BIGINT NULL,
    [RETURNED] DATE NULL,
    [REVERSED] DATE NULL,
    [RX_CREDIT] CHAR(1) NULL,
    [ID_RX_TX] BIGINT NULL,
    [ID_AAL] BIGINT NULL,
    [ORG_QTY_DEC] NUMERIC(13, 4) NULL,
    CONSTRAINT [PK_TX_CRED] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [FK_TX_CRED_ESCHAIN] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID]),
    CONSTRAINT [FK_TX_CRED_ESSTORE] FOREIGN KEY ([CHAIN_ID], [NHIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_STORE] ([CHAIN_NHIN_ID], [STORE_NHIN_ID]),
    CONSTRAINT [FK_TX_CRED_RX_TX] FOREIGN KEY ([CHAIN_ID], [ID_RX_TX])
        REFERENCES [EPS].[RX_TX] ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[TX_CRED_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [INITIALS] VARCHAR(3) NULL,
    [ORG_PRICE] NUMERIC(13, 4) NULL,
    [ORG_QTY] BIGINT NULL,
    [ORG_TX_NUM] BIGINT NULL,
    [RETURNED] DATE NULL,
    [REVERSED] DATE NULL,
    [RX_CREDIT] CHAR(1) NULL,
    [ID_RX_TX] BIGINT NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [ORG_QTY_DEC] NUMERIC(13, 4) NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    CONSTRAINT [PK_TX_CRED_AUDIT] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[TX_LOT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_RX_TX] BIGINT NOT NULL,
    [LOT_NUMBER] VARCHAR(30) NULL,
    [COUNTER] NUMERIC(2, 0) NOT NULL,
    [DRUG_EXPIRE_DATE] DATE NULL,
    [ID_AAL] BIGINT NULL,
    [LAST_UPDATED] DATE NULL,
    CONSTRAINT [TX_LOT_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [FK_TX_LOT_RX_TX] FOREIGN KEY ([CHAIN_ID], [ID_RX_TX])
        REFERENCES [EPS].[RX_TX] ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[TX_LOT_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_RX_TX] BIGINT NOT NULL,
    [LOT_NUMBER] VARCHAR(30) NULL,
    [COUNTER] NUMERIC(2, 0) NOT NULL,
    [DRUG_EXPIRE_DATE] DATE NULL,
    [ID_AAL] BIGINT NULL,
    [LAST_UPDATED] DATE NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL
);

CREATE TABLE [EPS].[TX_TP] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [BALANCE] NUMERIC(13, 4) NULL,
    [CARD_NUMBER] VARCHAR(20) NULL,
    [CARRIER_ID] VARCHAR(10) NULL,
    [COLLECT] NUMERIC(13, 4) NULL,
    [COMP_FEE] NUMERIC(13, 4) NULL,
    [COPAY] NUMERIC(13, 4) NULL,
    [COPAY_OVERRIDE] CHAR(1) NULL,
    [COST] NUMERIC(13, 4) NULL,
    [COUNTER] BIGINT NULL,
    [DAW] CHAR(1) NULL,
    [DENIAL_CLARIFICATION] VARCHAR(2) NULL,
    [DENIAL_DATE] DATE NULL,
    [DUR_CONFLICT_CODE] VARCHAR(2) NULL,
    [DUR_INTERVENTION_CODE] VARCHAR(2) NULL,
    [DUR_OUTCOME_CODE] VARCHAR(2) NULL,
    [GROUP_NUMBER] VARCHAR(15) NULL,
    [HOW_SUBMITTED] CHAR(1) NULL,
    [INCENTIVE_FEE] NUMERIC(13, 4) NULL,
    [ORIG_TYPE] CHAR(1) NULL,
    [OTHER_AMOUNT] NUMERIC(13, 4) NULL,
    [PLAN_NUMBER] VARCHAR(15) NULL,
    [PLAN_BIN] VARCHAR(10) NULL,
    [PLAN_NAME] VARCHAR(28) NULL,
    [PLAN_PCN] VARCHAR(10) NULL,
    [PRICE] NUMERIC(13, 4) NULL,
    [REVERSE] CHAR(1) NULL,
    [SAVE_DUR] CHAR(1) NULL,
    [SERVICE_LEVEL] VARCHAR(2) NULL,
    [SPLIT] CHAR(1) NULL,
    [STATUS] CHAR(1) NULL,
    [SUB_AMOUNT] NUMERIC(13, 4) NULL,
    [SUBMITTED] CHAR(1) NULL,
    [SUB_STATUS] CHAR(1) NULL,
    [SUB_TYPE] CHAR(1) NULL,
    [TAR] CHAR(1) NULL,
    [TAX] NUMERIC(13, 4) NULL,
    [TP_FLAG1] CHAR(1) NULL,
    [TP_FLAG2] CHAR(1) NULL,
    [TP_QUEUE_NUM] BIGINT NULL,
    [TQ_REF_NUM] VARCHAR(20) NULL,
    [UP_CHARGE] NUMERIC(13, 4) NULL,
    [USE_NDC] CHAR(1) NULL,
    [WRITE_OFF] NUMERIC(13, 4) NULL,
    [TX_DELETED] CHAR(1) NULL,
    [RX_DELETED] CHAR(1) NULL,
    [ID_RX_TX] BIGINT NULL,
    [ID_AAL] BIGINT NULL,
    [PAID_STATUS] NUMERIC(1, 0) NULL,
    [TP_PAID_AMOUNT] NUMERIC(13, 4) NULL,
    [TX_TYPE] VARCHAR(1) NULL,
    [CLAIM_VIA_TX_CORRECTION] VARCHAR(1) NULL,
    [RPH_DUR_INITIALS] VARCHAR(3) NULL,
    [TP_DAYS_SUPPLY] NUMERIC(10, 0) NULL,
    [SUBMIT_PRICE] NUMERIC(14, 4) NULL,
    CONSTRAINT [PK_TX_TP] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [FK_TX_TP_ESCHAIN] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID]),
    CONSTRAINT [FK_TX_TP_ESSTORE] FOREIGN KEY ([CHAIN_ID], [NHIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_STORE] ([CHAIN_NHIN_ID], [STORE_NHIN_ID]),
    CONSTRAINT [FK_TX_TP_RX_TX] FOREIGN KEY ([CHAIN_ID], [ID_RX_TX])
        REFERENCES [EPS].[RX_TX] ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[TX_TP_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [BALANCE] NUMERIC(13, 4) NULL,
    [CARD_NUMBER] VARCHAR(20) NULL,
    [CARRIER_ID] VARCHAR(10) NULL,
    [COLLECT] NUMERIC(13, 4) NULL,
    [COMP_FEE] NUMERIC(13, 4) NULL,
    [COPAY] NUMERIC(13, 4) NULL,
    [COPAY_OVERRIDE] CHAR(1) NULL,
    [COST] NUMERIC(13, 4) NULL,
    [COUNTER] BIGINT NULL,
    [DAW] CHAR(1) NULL,
    [DENIAL_CLARIFICATION] VARCHAR(2) NULL,
    [DENIAL_DATE] DATE NULL,
    [DUR_CONFLICT_CODE] VARCHAR(2) NULL,
    [DUR_INTERVENTION_CODE] VARCHAR(2) NULL,
    [DUR_OUTCOME_CODE] VARCHAR(2) NULL,
    [GROUP_NUMBER] VARCHAR(15) NULL,
    [HOW_SUBMITTED] CHAR(1) NULL,
    [INCENTIVE_FEE] NUMERIC(13, 4) NULL,
    [ORIG_TYPE] CHAR(1) NULL,
    [OTHER_AMOUNT] NUMERIC(13, 4) NULL,
    [PLAN_NUMBER] VARCHAR(15) NULL,
    [PLAN_BIN] VARCHAR(10) NULL,
    [PLAN_NAME] VARCHAR(28) NULL,
    [PLAN_PCN] VARCHAR(10) NULL,
    [PRICE] NUMERIC(13, 4) NULL,
    [REVERSE] CHAR(1) NULL,
    [SAVE_DUR] CHAR(1) NULL,
    [SERVICE_LEVEL] VARCHAR(2) NULL,
    [SPLIT] CHAR(1) NULL,
    [STATUS] CHAR(1) NULL,
    [SUB_AMOUNT] NUMERIC(13, 4) NULL,
    [SUBMITTED] CHAR(1) NULL,
    [SUB_STATUS] CHAR(1) NULL,
    [SUB_TYPE] CHAR(1) NULL,
    [TAR] CHAR(1) NULL,
    [TAX] NUMERIC(13, 4) NULL,
    [TP_FLAG1] CHAR(1) NULL,
    [TP_FLAG2] CHAR(1) NULL,
    [TP_QUEUE_NUM] BIGINT NULL,
    [TQ_REF_NUM] VARCHAR(20) NULL,
    [UP_CHARGE] NUMERIC(13, 4) NULL,
    [USE_NDC] CHAR(1) NULL,
    [WRITE_OFF] NUMERIC(13, 4) NULL,
    [TX_DELETED] CHAR(1) NULL,
    [RX_DELETED] CHAR(1) NULL,
    [ID_RX_TX] BIGINT NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [PAID_STATUS] NUMERIC(1, 0) NULL,
    [TP_PAID_AMOUNT] NUMERIC(13, 4) NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    [TX_TYPE] VARCHAR(1) NULL,
    [CLAIM_VIA_TX_CORRECTION] VARCHAR(1) NULL,
    [RPH_DUR_INITIALS] VARCHAR(3) NULL,
    [SUBMIT_PRICE] NUMERIC(14, 4) NULL,
    [TP_DAYS_SUPPLY] NUMERIC(10, 0) NULL,
    CONSTRAINT [PK_TX_TP_AUDIT] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);
