-- ============================================================================
-- BATCH_CREATE_TABLES_BATCH7.sql
-- Purpose: Create 10 PATIENT-related tables (Batch 7)
-- Tables: PATIENT_EMERGENCY_CONTACT, PATIENT_EMERGENCY_CONT_AUDIT, 
--         PATIENT_EMERGENCY_CONT_AUDIT_CSD_23800, PATIENT_EXTRACT, 
--         PATIENT_NOTES, PATIENT_NOTES_AUDIT, PATIENT_NOTIFY_SCHEDULE, 
--         PATIENT_NOTIFY_SCHEDULE_AUDIT, PATIENT_PROGRAM, PATIENT_PROGRAM_AUDIT
-- ============================================================================

-- EXTERNAL FK DEPENDENCIES:
--   - 8 tables reference EPS.PATIENT (ID_PATIENT column) - FK REMOVED
--   - 2 tables (PATIENT_PROGRAM*) reference SEC_ADMIN.EPS_SEC_CHAIN (NHIN_ID) - FK REMOVED
--   See REMOVED_FK_RESTORATION_SCRIPTS.sql Section 3 for post-prerequisite restoration

-- PROACTIVE DATA TYPE FIXES APPLIED:
--   - NUMBER → BIGINT (for ID, ID_PATIENT, NHIN_ID, ECC_PROGRAM_IDENTIFIER)
--   - NUMBER(38,0) → BIGINT (E001 prevention: ID consistency)
--   - NUMBER(22,0) → BIGINT (E001 prevention: ID consistency)
--   - All DATETIME2 scales verified (max 6, all valid)
--   - All PK columns verified NOT NULL (E006 prevention)
--   - All CHAIN_ID set to NOT NULL (E006 prevention)

-- ============================================================================

CREATE TABLE [EPS].[PATIENT_EMERGENCY_CONTACT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [PHONE_TYPE] NUMERIC(3, 0) NULL,
    [PHONE_NUMBER] VARCHAR(10) NULL,
    [FIRST_NAME] VARCHAR(20) NULL,
    [LAST_NAME] VARCHAR(25) NULL,
    [RELATION] VARCHAR(20) NULL,
    [CONTACT_ORDER] NUMERIC(2, 0) NULL,
    [ID_AAL] BIGINT NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    [DELETED] VARCHAR(1) NULL,
    [CONTACT_LAST_UPDATED] DATETIME2(6) NULL,
    CONSTRAINT [PATIENT_EMERGENCY_CONTACT_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[PATIENT_EMERGENCY_CONT_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [PHONE_TYPE] NUMERIC(3, 0) NULL,
    [PHONE_NUMBER] VARCHAR(10) NULL,
    [FIRST_NAME] VARCHAR(20) NULL,
    [LAST_NAME] VARCHAR(25) NULL,
    [RELATION] VARCHAR(20) NULL,
    [CONTACT_ORDER] NUMERIC(2, 0) NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    [DELETED] VARCHAR(1) NULL,
    [CONTACT_LAST_UPDATED] DATETIME2(6) NULL
);

CREATE TABLE [EPS].[PATIENT_EMERGENCY_CONT_AUDIT_CSD_23800] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [PHONE_TYPE] NUMERIC(3, 0) NULL,
    [PHONE_NUMBER] VARCHAR(10) NULL,
    [FIRST_NAME] VARCHAR(20) NULL,
    [LAST_NAME] VARCHAR(25) NULL,
    [RELATION] VARCHAR(20) NULL,
    [CONTACT_ORDER] NUMERIC(2, 0) NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    [DELETED] VARCHAR(1) NULL,
    [CONTACT_LAST_UPDATED] DATETIME2(6) NULL
);

CREATE TABLE [EPS].[PATIENT_EXTRACT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [LAST_CHANGE_TIME] DATETIME2(6) NOT NULL,
    CONSTRAINT [PATIENT_EXTRACT_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID], [LAST_CHANGE_TIME])
);

CREATE TABLE [EPS].[PATIENT_NOTES] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_AAL] BIGINT NOT NULL,
    [LAST_UPDATED] DATE NOT NULL,
    [DEACTIVATE_DATE] DATETIME2(6) NULL,
    [DEACTIVATE_USER] VARCHAR(255) NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [GUID] VARCHAR(36) NOT NULL,
    [NOTE] VARCHAR(2000) NULL,
    [DISPLAY_DE] VARCHAR(1) NULL,
    [DISPLAY_DE_QA] VARCHAR(1) NULL,
    [DISPLAY_FILL] VARCHAR(1) NULL,
    [DISPLAY_OE] VARCHAR(1) NULL,
    [DISPLAY_QA] VARCHAR(1) NULL,
    [DISPLAY_WC] VARCHAR(1) NULL,
    [DISPLAY_NEW_RX] VARCHAR(1) NULL,
    [DISPLAY_CALL] VARCHAR(1) NULL,
    [CREATE_DATE] DATETIME2(6) NULL,
    [USER_ID] VARCHAR(255) NULL,
    [ELIGIBLE_TO_PRINT] VARCHAR(1) NULL,
    [EXPIRATION_DATE] DATETIME2(6) NULL,
    [CREATED_STORE_NHINID] BIGINT NULL,
    [DISPLAY_PAE] VARCHAR(1) NULL,
    [DISPLAY_RPH_PATIENT_NOTE_IN_DV] VARCHAR(1) NULL,
    CONSTRAINT [PATIENT_NOTES_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[PATIENT_NOTES_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_AAL] BIGINT NOT NULL,
    [LAST_UPDATED] DATE NOT NULL,
    [DEACTIVATE_DATE] DATETIME2(6) NULL,
    [DEACTIVATE_USER] VARCHAR(255) NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [GUID] VARCHAR(36) NOT NULL,
    [NOTE] VARCHAR(2000) NULL,
    [DISPLAY_DE] VARCHAR(1) NULL,
    [DISPLAY_DE_QA] VARCHAR(1) NULL,
    [DISPLAY_FILL] VARCHAR(1) NULL,
    [DISPLAY_OE] VARCHAR(1) NULL,
    [DISPLAY_QA] VARCHAR(1) NULL,
    [DISPLAY_WC] VARCHAR(1) NULL,
    [DISPLAY_NEW_RX] VARCHAR(1) NULL,
    [DISPLAY_CALL] VARCHAR(1) NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    [CREATE_DATE] DATETIME2(6) NULL,
    [USER_ID] VARCHAR(255) NULL,
    [ELIGIBLE_TO_PRINT] VARCHAR(1) NULL,
    [EXPIRATION_DATE] DATETIME2(6) NULL,
    [CREATED_STORE_NHINID] BIGINT NULL,
    [DISPLAY_PAE] VARCHAR(1) NULL,
    [DISPLAY_RPH_PATIENT_NOTE_IN_DV] VARCHAR(1) NULL
);

CREATE TABLE [EPS].[PATIENT_NOTIFY_SCHEDULE] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [MESSAGE_TYPE] VARCHAR(1) NULL,
    [DAY_OF_WEEK] VARCHAR(9) NOT NULL,
    [START_TIME] VARCHAR(5) NULL,
    [END_TIME] VARCHAR(5) NULL,
    [PATIENT_TIME_ZONE] VARCHAR(40) NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    [ID_AAL] BIGINT NULL,
    CONSTRAINT [PATIENT_NOTIFY_SCHEDULE_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[PATIENT_NOTIFY_SCHEDULE_AUDIT] (
    [CHAIN_ID] BIGINT NULL,
    [ID] BIGINT NULL,
    [ID_PATIENT] BIGINT NULL,
    [MESSAGE_TYPE] VARCHAR(1) NULL,
    [DAY_OF_WEEK] VARCHAR(9) NULL,
    [START_TIME] VARCHAR(5) NULL,
    [END_TIME] VARCHAR(5) NULL,
    [PATIENT_TIME_ZONE] VARCHAR(40) NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL
);

CREATE TABLE [EPS].[PATIENT_PROGRAM] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [NHIN_ID] BIGINT NOT NULL,
    [ECC_PROGRAM_IDENTIFIER] BIGINT NOT NULL,
    [PROGRAM_ADDED_DATE] DATETIME2(6) NOT NULL,
    [OPT_OUT] VARCHAR(1) NULL,
    [DELETED] VARCHAR(1) NULL,
    [DEACTIVATED_DATE] DATETIME2(6) NULL,
    [LAST_UPDATED] DATETIME2(6) NOT NULL,
    [ID_AAL] BIGINT NULL,
    CONSTRAINT [PATIENT_PROGRAM_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[PATIENT_PROGRAM_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_PATIENT] BIGINT NOT NULL,
    [NHIN_ID] BIGINT NOT NULL,
    [ECC_PROGRAM_IDENTIFIER] BIGINT NOT NULL,
    [PROGRAM_ADDED_DATE] DATETIME2(6) NOT NULL,
    [OPT_OUT] VARCHAR(1) NULL,
    [DELETED] VARCHAR(1) NULL,
    [DEACTIVATED_DATE] DATETIME2(6) NULL,
    [LAST_UPDATED] DATETIME2(6) NOT NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL
);
