-- =====================================================================
-- BATCH_CREATE_TABLES_BATCH14.sql
-- Purpose: Create missing tables identified in Azure migration
-- Generated: 2026-06-24 16:30:13
-- Tables: 9 (from validation comparison)
-- Missing from Azure: CARD_AUDIT, FDB_PAT_ALLERGY_REACTION_AUDIT,
--   RX_TX_DIAGNOSIS_CODES, RX_TX_DIAGNOSIS_CODES_AUDIT, RX_TX_DUR_LIST,
--   RX_TX_DUR_LIST_AUDIT, RX_TX_PAYMENT, RX_TX_PAYMENT_AUDIT,
--   RX_TX_SIG_STRUCTURED_PART
-- =====================================================================

-- Set NOCOUNT ON to avoid noise in execution results
SET NOCOUNT ON;
GO

-- =====================================================================
-- TABLES TO CREATE
-- =====================================================================

-- =====================================================================
-- Table 1: CARD_AUDIT
-- =====================================================================
CREATE TABLE [EPS].[CARD_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [DELETED] CHAR(1),
    [LAST_UPDATED] DATETIME,
    [NHIN_ID] BIGINT,
    [BEGINNING_COVERAGE_DATE] DATETIME,
    [BENEFIT] VARCHAR(5),
    [CARD_NUMBER] VARCHAR(20),
    [CARD_NUMBER_QUALIFIER] VARCHAR(2),
    [COVERAGE_CODE] VARCHAR(6),
    [ELIGIBLE] CHAR(1),
    [ENDING_COVERAGE_DATE] DATETIME,
    [FIRST_NAME] VARCHAR(20),
    [LAST_NAME] VARCHAR(25),
    [MIDDLE_NAME] VARCHAR(20),
    [WORKMANS_COMP_FLAG] CHAR(1),
    [CARRIER_ID] VARCHAR(10),
    [PLAN_DATE] DATETIME,
    [PLAN_NUMBER] VARCHAR(15),
    [GROUP_NUMBER] VARCHAR(15),
    [CARD_HOLDER_NAME] VARCHAR(47),
    [ALT_CARD] VARCHAR(20),
    [ID_AAL] BIGINT,
    [ID_AUDIT] BIGINT,
    [DISPENSABLE_IDENTIFIER] BIGINT,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    [CONTRACT_IDENTIFIER] VARCHAR(10)
);
GO

CREATE NONCLUSTERED INDEX [IDX_CARD_AUDIT_CHAIN_ID] ON [EPS].[CARD_AUDIT]([CHAIN_ID]);
CREATE NONCLUSTERED INDEX [IDX_CARD_AUDIT_TIMESTAMP] ON [EPS].[CARD_AUDIT]([AUDIT_TIMESTAMP]);
CREATE NONCLUSTERED INDEX [IDX_CARD_AUDIT_LAST_NAME] ON [EPS].[CARD_AUDIT]([LAST_NAME], [FIRST_NAME]);

-- PAGE compression enabled in Azure SQL for optimization
ALTER TABLE [EPS].[CARD_AUDIT] WITH (DATA_COMPRESSION = PAGE);
GO

ALTER TABLE [EPS].[CARD_AUDIT] WITH (DATA_COMPRESSION = PAGE);
GO

-- =====================================================================
-- Table 2: FDB_PAT_ALLERGY_REACTION_AUDIT
-- =====================================================================
CREATE TABLE [EPS].[FDB_PAT_ALLERGY_REACTION_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [FDB_ALLERGY_ID] BIGINT NOT NULL,
    [REACTION_DESCRIPTION] VARCHAR(255) NOT NULL,
    [LAST_UPDATED] DATETIME,
    [DELETED] VARCHAR(1),
    [ID_AAL] BIGINT,
    [ID_AUDIT] BIGINT,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    CONSTRAINT [PK_FDB_PAT_ALLERGY_REACTION_AUDIT] PRIMARY KEY ([CHAIN_ID], [ID], [AUDIT_TIMESTAMP])
);
GO

CREATE NONCLUSTERED INDEX [IDX_FDB_PAT_ALLERGY_REACTION_AUDIT_CHAIN_ID] 
    ON [EPS].[FDB_PAT_ALLERGY_REACTION_AUDIT]([CHAIN_ID])
    INCLUDE ([ID], [FDB_ALLERGY_ID])
    WITH (FILLFACTOR = 90);
GO

CREATE NONCLUSTERED INDEX [IDX_FDB_PAT_ALLERGY_REACTION_AUDIT_TIMESTAMP] 
    ON [EPS].[FDB_PAT_ALLERGY_REACTION_AUDIT]([AUDIT_TIMESTAMP])
    INCLUDE ([CHAIN_ID], [ID])
    WITH (FILLFACTOR = 90);
GO

ALTER TABLE [EPS].[FDB_PAT_ALLERGY_REACTION_AUDIT] 
    WITH (DATA_COMPRESSION = PAGE);
GO

-- =====================================================================
-- Table 3: RX_TX_DIAGNOSIS_CODES
-- =====================================================================
CREATE TABLE [EPS].[RX_TX_DIAGNOSIS_CODES] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_RX_TX] BIGINT NOT NULL,
    [DIAGNOSIS_CODE] VARCHAR(20) NOT NULL,
    [DIAGNOSIS_DESC] VARCHAR(200) NULL,
    [CODE_TYPE] VARCHAR(10) NULL,
    [CREATED_DATE] DATETIME2(6) NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    CONSTRAINT [RX_TX_DIAGNOSIS_CODES_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [RX_TX_DIAGNOSIS_CODES_FK_RX_TX] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID])
);
GO

CREATE NONCLUSTERED INDEX [IX_RX_TX_DIAGNOSIS_CODES_CHAIN]
ON [EPS].[RX_TX_DIAGNOSIS_CODES] ([CHAIN_ID], [ID_RX_TX])
;
GO

-- =====================================================================
-- Table 4: RX_TX_DIAGNOSIS_CODES_AUDIT
-- =====================================================================
CREATE TABLE [EPS].[RX_TX_DIAGNOSIS_CODES_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_RX_TX] BIGINT NOT NULL,
    [DIAGNOSIS_CODE] VARCHAR(20) NULL,
    [DIAGNOSIS_DESC] VARCHAR(200) NULL,
    [CREATED_DATE] DATETIME2(6) NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    CONSTRAINT [RX_TX_DIAGNOSIS_CODES_AUDIT_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);
GO

CREATE NONCLUSTERED INDEX [IX_RX_TX_DIAGNOSIS_CODES_AUDIT_TS]
ON [EPS].[RX_TX_DIAGNOSIS_CODES_AUDIT] ([AUDIT_TIMESTAMP])
;
GO

-- =====================================================================
-- Table 5: RX_TX_DUR_LIST
-- =====================================================================
CREATE TABLE [EPS].[RX_TX_DUR_LIST] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_RX_TX] BIGINT NOT NULL,
    [DUR_CODE] VARCHAR(20) NOT NULL,
    [DUR_DESCRIPTION] VARCHAR(200) NULL,
    [SEVERITY] VARCHAR(10) NULL,
    [CREATED_DATE] DATETIME2(6) NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    CONSTRAINT [RX_TX_DUR_LIST_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [RX_TX_DUR_LIST_FK_RX_TX] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID])
);
GO

CREATE NONCLUSTERED INDEX [IX_RX_TX_DUR_LIST_CHAIN]
ON [EPS].[RX_TX_DUR_LIST] ([CHAIN_ID], [ID_RX_TX])
;
GO

-- =====================================================================
-- Table 6: RX_TX_DUR_LIST_AUDIT
-- =====================================================================
CREATE TABLE [EPS].[RX_TX_DUR_LIST_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_RX_TX] BIGINT NOT NULL,
    [DUR_CODE] VARCHAR(20) NULL,
    [DUR_DESCRIPTION] VARCHAR(200) NULL,
    [CREATED_DATE] DATETIME2(6) NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    CONSTRAINT [RX_TX_DUR_LIST_AUDIT_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);
GO

CREATE NONCLUSTERED INDEX [IX_RX_TX_DUR_LIST_AUDIT_TS]
ON [EPS].[RX_TX_DUR_LIST_AUDIT] ([AUDIT_TIMESTAMP])
;
GO

-- =====================================================================
-- Table 7: RX_TX_PAYMENT
-- =====================================================================
CREATE TABLE [EPS].[RX_TX_PAYMENT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_RX_TX] BIGINT NOT NULL,
    [PAYMENT_AMOUNT] DECIMAL(12,2) NOT NULL,
    [PAYMENT_DATE] DATETIME2(6) NOT NULL,
    [PAYMENT_METHOD] VARCHAR(20) NULL,
    [REFERENCE_NUMBER] VARCHAR(50) NULL,
    [STATUS] VARCHAR(1) NULL,
    [CREATED_DATE] DATETIME2(6) NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    CONSTRAINT [RX_TX_PAYMENT_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [RX_TX_PAYMENT_FK_RX_TX] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID])
);
GO

CREATE NONCLUSTERED INDEX [IX_RX_TX_PAYMENT_CHAIN_DATE]
ON [EPS].[RX_TX_PAYMENT] ([CHAIN_ID], [PAYMENT_DATE])
;
GO

-- =====================================================================
-- Table 8: RX_TX_PAYMENT_AUDIT
-- =====================================================================
CREATE TABLE [EPS].[RX_TX_PAYMENT_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_RX_TX] BIGINT NOT NULL,
    [PAYMENT_AMOUNT] DECIMAL(12,2) NULL,
    [PAYMENT_DATE] DATETIME2(6) NULL,
    [PAYMENT_METHOD] VARCHAR(20) NULL,
    [CREATED_DATE] DATETIME2(6) NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    CONSTRAINT [RX_TX_PAYMENT_AUDIT_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);
GO

CREATE NONCLUSTERED INDEX [IX_RX_TX_PAYMENT_AUDIT_TS]
ON [EPS].[RX_TX_PAYMENT_AUDIT] ([AUDIT_TIMESTAMP], [PAYMENT_DATE])
;
GO

-- =====================================================================
-- Table 9: RX_TX_SIG_STRUCTURED_PART
-- =====================================================================
CREATE TABLE [EPS].[RX_TX_SIG_STRUCTURED_PART] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [ID_RX_TX] BIGINT NOT NULL,
    [PART_SEQUENCE] BIGINT NULL,
    [PART_TYPE] VARCHAR(50) NULL,
    [PART_VALUE] VARCHAR(MAX) NULL,
    [UNIT_CODE] VARCHAR(20) NULL,
    [CREATED_DATE] DATETIME2(6) NULL,
    [LAST_UPDATED] DATETIME2(6) NULL,
    CONSTRAINT [RX_TX_SIG_STRUCTURED_PART_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [RX_TX_SIG_STRUCTURED_PART_FK_RX_TX] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID])
);
GO

CREATE NONCLUSTERED INDEX [IX_RX_TX_SIG_STRUCTURED_PART_RX_TX]
ON [EPS].[RX_TX_SIG_STRUCTURED_PART] ([CHAIN_ID], [ID_RX_TX], [PART_SEQUENCE])
;
GO

-- =====================================================================
-- SUMMARY: 9 tables created successfully
-- =====================================================================

PRINT 'BATCH_CREATE_TABLES_BATCH14.sql completed successfully!';
PRINT 'Tables created: 9';
GO