-- ============================================================================
-- BATCH_CREATE_TABLES_BATCH12.sql
-- Purpose: Create 12 tables (Batch 12)
-- Tables: UNMERGE_DELETE_LIST, VERSION, VIAL_INFO, VIAL_INFO_AUDIT,
--         WC_CSD5570_DROPAFTER20181011, WORKMANS_COMP, WORKMANS_COMP_AUDIT,
--         WORK_WINN_DIXIE, AUDIT_PHI_EVENT_DETAIL, PURGE_RUN_DETAILS,
--         PURGE_FLOW_MAP, PURGE_INDEX_REBUILD_LOG
-- NOTE: XT_TARGET_NDC and PDX_SCHEMA_TASK_ERROR_LOG source files not found in workspace
-- ============================================================================

-- DROP EXISTING TABLES (in reverse dependency order)
IF OBJECT_ID('[EPS].[PURGE_INDEX_REBUILD_LOG]', 'U') IS NOT NULL DROP TABLE [EPS].[PURGE_INDEX_REBUILD_LOG];
IF OBJECT_ID('[EPS].[PURGE_FLOW_MAP]', 'U') IS NOT NULL DROP TABLE [EPS].[PURGE_FLOW_MAP];
IF OBJECT_ID('[EPS].[PURGE_RUN_DETAILS]', 'U') IS NOT NULL DROP TABLE [EPS].[PURGE_RUN_DETAILS];
IF OBJECT_ID('[EPS].[AUDIT_PHI_EVENT_DETAIL]', 'U') IS NOT NULL DROP TABLE [EPS].[AUDIT_PHI_EVENT_DETAIL];
IF OBJECT_ID('[EPS].[WORK_WINN_DIXIE]', 'U') IS NOT NULL DROP TABLE [EPS].[WORK_WINN_DIXIE];
IF OBJECT_ID('[EPS].[WORKMANS_COMP_AUDIT]', 'U') IS NOT NULL DROP TABLE [EPS].[WORKMANS_COMP_AUDIT];
IF OBJECT_ID('[EPS].[WORKMANS_COMP]', 'U') IS NOT NULL DROP TABLE [EPS].[WORKMANS_COMP];
IF OBJECT_ID('[EPS].[WC_CSD5570_DROPAFTER20181011]', 'U') IS NOT NULL DROP TABLE [EPS].[WC_CSD5570_DROPAFTER20181011];
IF OBJECT_ID('[EPS].[VIAL_INFO_AUDIT]', 'U') IS NOT NULL DROP TABLE [EPS].[VIAL_INFO_AUDIT];
IF OBJECT_ID('[EPS].[VIAL_INFO]', 'U') IS NOT NULL DROP TABLE [EPS].[VIAL_INFO];
IF OBJECT_ID('[EPS].[VERSION]', 'U') IS NOT NULL DROP TABLE [EPS].[VERSION];
IF OBJECT_ID('[EPS].[UNMERGE_DELETE_LIST]', 'U') IS NOT NULL DROP TABLE [EPS].[UNMERGE_DELETE_LIST];

-- ============================================================================

-- EXTERNAL FK DEPENDENCIES:
--   - WORKMANS_COMP: 1 FK removed (CHAIN_ID, ID_CARD→CARD)
--   - WORKMANS_COMP_AUDIT: 1 FK removed (same as WORKMANS_COMP)
--   - AUDIT_PHI_EVENT_DETAIL: 1 FK removed (CHAIN_ID, AUDIT_PHI_EVENT_ID→AUDIT_PHI_EVENT)
--   - PURGE_RUN_DETAILS: 1 FK removed (PURGE_ERROR_LOG_ID→PURGE_ERROR_LOG)
--   - PURGE_INDEX_REBUILD_LOG: 1 FK removed (PURGE_ERROR_LOG_ID→PURGE_ERROR_LOG)
--   See REMOVED_FK_RESTORATION_SCRIPTS.sql Section 8 for post-prerequisite restoration

-- INTERNAL FK DEPENDENCIES (SAME BATCH OR EXISTING):
--   - VERSION: FK to SEC_ADMIN.EPS_SEC_CHAIN - INTERNAL (exists), KEEP
--   - VIAL_INFO: FK to RX_TX (CHAIN_ID, ID_RX_TX) - INTERNAL (from Batch 10), KEEP
--   - VIAL_INFO: FK to SEC_ADMIN.EPS_SEC_CHAIN - INTERNAL (exists), KEEP
--   - VIAL_INFO_AUDIT: FK to RX_TX (CHAIN_ID, ID_RX_TX) - INTERNAL (from Batch 10), KEEP
--   - VIAL_INFO_AUDIT: FK to SEC_ADMIN.EPS_SEC_CHAIN - INTERNAL (exists), KEEP
--   - WORKMANS_COMP: FK to SEC_ADMIN.EPS_SEC_CHAIN - INTERNAL (exists), KEEP
--   - WORKMANS_COMP: FK to SEC_ADMIN.EPS_SEC_STORE - INTERNAL (exists), KEEP
--   - WORKMANS_COMP_AUDIT: FK to SEC_ADMIN.EPS_SEC_CHAIN - INTERNAL (exists), KEEP
--   - WORKMANS_COMP_AUDIT: FK to SEC_ADMIN.EPS_SEC_STORE - INTERNAL (exists), KEEP
--   - PURGE_FLOW_MAP: FK to PURGE_RUN_DETAILS (2x) - INTERNAL (same batch), KEEP
--   - PURGE_INDEX_REBUILD_LOG: FK to PURGE_RUN_DETAILS - INTERNAL (same batch), KEEP

-- PROACTIVE DATA TYPE FIXES APPLIED:
--   - NUMBER → BIGINT (for all ID, ID_CARD, ID_AAL columns)
--   - NUMBER(22,0) → BIGINT (for CHAIN_ID, ID, ID_RX_TX in VIAL_INFO/AUDIT)
--   - NUMBER(13,4) → NUMERIC(13,4) (for VIAL_QTY in VIAL_INFO/AUDIT)
--   - All DATETIME2 scales verified (TIMESTAMP(6) → DATETIME2(6))
--   - All PK columns verified NOT NULL
--   - All CHAR/VARCHAR2 → CHAR/VARCHAR with preserved lengths

-- CREATION ORDER:
--   1. Simple tables (no dependencies): UNMERGE_DELETE_LIST, WORK_WINN_DIXIE
--   2. Reference tables: VERSION, VIAL_INFO, WORKMANS_COMP, AUDIT_PHI_EVENT_DETAIL, PURGE_RUN_DETAILS
--   3. Dependent tables: VIAL_INFO_AUDIT, WC_CSD5570_DROPAFTER20181011, WORKMANS_COMP_AUDIT
--   4. Internal FK tables: PURGE_FLOW_MAP, PURGE_INDEX_REBUILD_LOG

-- ============================================================================

-- SIMPLE TABLES (no dependencies)

CREATE TABLE [EPS].[UNMERGE_DELETE_LIST] (
    [CHAIN_ID] BIGINT NULL,
    [ID_PATIENT] BIGINT NULL
);

CREATE TABLE [EPS].[WORK_WINN_DIXIE] (
    [STORE_NAME] VARCHAR(255) NOT NULL,
    [COMP_DATE] DATE NULL,
    [COMP_FILL_C] BIGINT NULL,
    [COMP_FILL_H] BIGINT NULL,
    [COMP_FILL_Y] BIGINT NULL,
    [CURR_DATE] DATE NULL,
    [CURR_FILL_C] BIGINT NULL,
    [CURR_FILL_H] BIGINT NULL,
    [CURR_FILL_Y] BIGINT NULL
);

-- REFERENCE TABLES

CREATE TABLE [EPS].[VERSION] (
    [CHAIN_ID] BIGINT NULL,
    [ID] BIGINT NULL,
    [VERSION_NUMBER] VARCHAR(40) NULL,
    [UPDATES] VARCHAR(2000) NULL,
    CONSTRAINT [FK_VERSION_ESCHAIN] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID])
);

CREATE TABLE [EPS].[VIAL_INFO] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [VIAL_SEQUENCE] NUMERIC(3, 0) NOT NULL,
    [VIAL_QTY] NUMERIC(13, 4) NULL,
    [QC_RPH_ID] VARCHAR(10) NULL,
    [QC_RPH_INITIALS] VARCHAR(10) NULL,
    [QC_RPH_LICENSE_NUMBER] VARCHAR(20) NULL,
    [ID_AAL] BIGINT NULL,
    [LAST_UPDATED] DATE NULL,
    [ID_RX_TX] BIGINT NOT NULL,
    CONSTRAINT [VIAL_INFO_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID]),
    CONSTRAINT [FK_VIAL_INFO_RX_TX] FOREIGN KEY ([CHAIN_ID], [ID_RX_TX])
        REFERENCES [EPS].[RX_TX] ([CHAIN_ID], [ID]),
    CONSTRAINT [FK_VIAL_INFO_ESCHAIN] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID])
);

CREATE TABLE [EPS].[VIAL_INFO_AUDIT] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [VIAL_SEQUENCE] NUMERIC(3, 0) NOT NULL,
    [VIAL_QTY] NUMERIC(13, 4) NULL,
    [QC_RPH_ID] VARCHAR(10) NULL,
    [QC_RPH_INITIALS] VARCHAR(10) NULL,
    [QC_RPH_LICENSE_NUMBER] VARCHAR(20) NULL,
    [ID_AAL] BIGINT NULL,
    [LAST_UPDATED] DATE NULL,
    [ID_RX_TX] BIGINT NOT NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    CONSTRAINT [FK_VIAL_INFO_AUDIT_RX_TX] FOREIGN KEY ([CHAIN_ID], [ID_RX_TX])
        REFERENCES [EPS].[RX_TX] ([CHAIN_ID], [ID]),
    CONSTRAINT [FK_VIAL_INFO_AUDIT_ESCHAIN] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID])
);

CREATE TABLE [EPS].[WC_CSD5570_DROPAFTER20181011] (
    [CHAIN_ID] BIGINT NULL,
    [ID] BIGINT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [ACCIDENT_INDICATOR] CHAR(1) NULL,
    [ACCIDENT_STATE] VARCHAR(2) NULL,
    [CARD_NUMBER] VARCHAR(20) NULL,
    [CARRIER_ADDRESS] VARCHAR(30) NULL,
    [CARRIER_AREA_CODE] VARCHAR(3) NULL,
    [CARRIER_CITY] VARCHAR(20) NULL,
    [CARRIER_CODE] VARCHAR(20) NULL,
    [CARRIER_COUNTRY] VARCHAR(4) NULL,
    [CARRIER_ID] VARCHAR(10) NULL,
    [CARRIER_NAME] VARCHAR(28) NULL,
    [CARRIER_PHONE] VARCHAR(7) NULL,
    [CARRIER_STATE] VARCHAR(2) NULL,
    [CARRIER_ZIP_CODE] VARCHAR(15) NULL,
    [EMPLOYER_ADDRESS] VARCHAR(30) NULL,
    [EMPLOYER_AREA_CODE] VARCHAR(3) NULL,
    [EMPLOYER_CITY] VARCHAR(20) NULL,
    [EMPLOYER_COUNTRY] VARCHAR(4) NULL,
    [EMPLOYER_ID] VARCHAR(15) NULL,
    [EMPLOYER_NAME] VARCHAR(30) NULL,
    [EMPLOYER_PHONE] VARCHAR(7) NULL,
    [EMPLOYER_PRIMARY_CONTACT] VARCHAR(30) NULL,
    [EMPLOYER_STATE] VARCHAR(2) NULL,
    [EMPLOYER_ZIP_CODE] VARCHAR(15) NULL,
    [END_HOSPITALIZATION] DATE NULL,
    [END_UNABLE_TO_WORK] DATE NULL,
    [GROUP_NUMBER] VARCHAR(15) NULL,
    [INJURY] DATE NULL,
    [LAST] DATE NULL,
    [OTHER_INFO] VARCHAR(28) NULL,
    [PLAN_NUMBER] VARCHAR(15) NULL,
    [REF_ID] VARCHAR(30) NULL,
    [SIMILAR] DATE NULL,
    [START_HOSPITALIZATION] DATE NULL,
    [START_UNABLE_TO_WORK] DATE NULL,
    [ID_CARD] BIGINT NULL,
    [ID_AAL] BIGINT NULL
);

CREATE TABLE [EPS].[WORKMANS_COMP] (
    [CHAIN_ID] BIGINT NULL,
    [ID] BIGINT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [ACCIDENT_INDICATOR] CHAR(1) NULL,
    [ACCIDENT_STATE] VARCHAR(2) NULL,
    [CARD_NUMBER] VARCHAR(20) NULL,
    [CARRIER_ADDRESS] VARCHAR(30) NULL,
    [CARRIER_AREA_CODE] VARCHAR(3) NULL,
    [CARRIER_CITY] VARCHAR(35) NULL,
    [CARRIER_CODE] VARCHAR(20) NULL,
    [CARRIER_COUNTRY] VARCHAR(4) NULL,
    [CARRIER_ID] VARCHAR(10) NULL,
    [CARRIER_NAME] VARCHAR(28) NULL,
    [CARRIER_PHONE] VARCHAR(7) NULL,
    [CARRIER_STATE] VARCHAR(2) NULL,
    [CARRIER_ZIP_CODE] VARCHAR(15) NULL,
    [EMPLOYER_ADDRESS] VARCHAR(30) NULL,
    [EMPLOYER_AREA_CODE] VARCHAR(3) NULL,
    [EMPLOYER_CITY] VARCHAR(35) NULL,
    [EMPLOYER_COUNTRY] VARCHAR(4) NULL,
    [EMPLOYER_ID] VARCHAR(15) NULL,
    [EMPLOYER_NAME] VARCHAR(30) NULL,
    [EMPLOYER_PHONE] VARCHAR(7) NULL,
    [EMPLOYER_PRIMARY_CONTACT] VARCHAR(30) NULL,
    [EMPLOYER_STATE] VARCHAR(2) NULL,
    [EMPLOYER_ZIP_CODE] VARCHAR(15) NULL,
    [END_HOSPITALIZATION] DATE NULL,
    [END_UNABLE_TO_WORK] DATE NULL,
    [GROUP_NUMBER] VARCHAR(15) NULL,
    [INJURY] DATE NULL,
    [LAST] DATE NULL,
    [OTHER_INFO] VARCHAR(28) NULL,
    [PLAN_NUMBER] VARCHAR(15) NULL,
    [REF_ID] VARCHAR(30) NULL,
    [SIMILAR] DATE NULL,
    [START_HOSPITALIZATION] DATE NULL,
    [START_UNABLE_TO_WORK] DATE NULL,
    [ID_CARD] BIGINT NULL,
    [ID_AAL] BIGINT NULL,
    CONSTRAINT [FK_WORKCOMP_ESCHAIN] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID]),
    CONSTRAINT [FK_WORKCOMP_ESSTORE] FOREIGN KEY ([CHAIN_ID], [NHIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_STORE] ([CHAIN_NHIN_ID], [STORE_NHIN_ID])
);

CREATE TABLE [EPS].[WORKMANS_COMP_AUDIT] (
    [CHAIN_ID] BIGINT NULL,
    [ID] BIGINT NULL,
    [DELETED] CHAR(1) NULL,
    [LAST_UPDATED] DATE NULL,
    [NHIN_ID] BIGINT NULL,
    [ACCIDENT_INDICATOR] CHAR(1) NULL,
    [ACCIDENT_STATE] VARCHAR(2) NULL,
    [CARD_NUMBER] VARCHAR(20) NULL,
    [CARRIER_ADDRESS] VARCHAR(30) NULL,
    [CARRIER_AREA_CODE] VARCHAR(3) NULL,
    [CARRIER_CITY] VARCHAR(35) NULL,
    [CARRIER_CODE] VARCHAR(20) NULL,
    [CARRIER_COUNTRY] VARCHAR(4) NULL,
    [CARRIER_ID] VARCHAR(10) NULL,
    [CARRIER_NAME] VARCHAR(28) NULL,
    [CARRIER_PHONE] VARCHAR(7) NULL,
    [CARRIER_STATE] VARCHAR(2) NULL,
    [CARRIER_ZIP_CODE] VARCHAR(15) NULL,
    [EMPLOYER_ADDRESS] VARCHAR(30) NULL,
    [EMPLOYER_AREA_CODE] VARCHAR(3) NULL,
    [EMPLOYER_CITY] VARCHAR(35) NULL,
    [EMPLOYER_COUNTRY] VARCHAR(4) NULL,
    [EMPLOYER_ID] VARCHAR(15) NULL,
    [EMPLOYER_NAME] VARCHAR(30) NULL,
    [EMPLOYER_PHONE] VARCHAR(7) NULL,
    [EMPLOYER_PRIMARY_CONTACT] VARCHAR(30) NULL,
    [EMPLOYER_STATE] VARCHAR(2) NULL,
    [EMPLOYER_ZIP_CODE] VARCHAR(15) NULL,
    [END_HOSPITALIZATION] DATE NULL,
    [END_UNABLE_TO_WORK] DATE NULL,
    [GROUP_NUMBER] VARCHAR(15) NULL,
    [INJURY] DATE NULL,
    [LAST] DATE NULL,
    [OTHER_INFO] VARCHAR(28) NULL,
    [PLAN_NUMBER] VARCHAR(15) NULL,
    [REF_ID] VARCHAR(30) NULL,
    [SIMILAR] DATE NULL,
    [START_HOSPITALIZATION] DATE NULL,
    [START_UNABLE_TO_WORK] DATE NULL,
    [ID_CARD] BIGINT NULL,
    [ID_AAL] BIGINT NULL,
    [ID_AUDIT] BIGINT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(6) NOT NULL,
    CONSTRAINT [FK_WORKCOMP_AUDIT_ESCHAIN] FOREIGN KEY ([CHAIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_CHAIN] ([CHAIN_NHIN_ID]),
    CONSTRAINT [FK_WORKCOMP_AUDIT_ESSTORE] FOREIGN KEY ([CHAIN_ID], [NHIN_ID])
        REFERENCES [SEC_ADMIN].[EPS_SEC_STORE] ([CHAIN_NHIN_ID], [STORE_NHIN_ID])
);

CREATE TABLE [EPS].[AUDIT_PHI_EVENT_DETAIL] (
    [CHAIN_ID] BIGINT NOT NULL,
    [ID] BIGINT NOT NULL,
    [AUDIT_PHI_EVENT_ID] BIGINT NOT NULL,
    [GEO_REGION] VARCHAR(20) NULL,
    [MRN] VARCHAR(40) NULL,
    [RX_COM_ID] BIGINT NULL,
    CONSTRAINT [APED_PK] PRIMARY KEY CLUSTERED ([CHAIN_ID], [ID])
);

CREATE TABLE [EPS].[PURGE_RUN_DETAILS] (
    [ID] BIGINT NOT NULL,
    [OBJECT_NAME] VARCHAR(100) NULL,
    [START_DATE] DATE NULL,
    [END_DATE] DATE NULL,
    [STATUS] VARCHAR(100) NULL,
    [AFFECTED_ROW_COUNT] BIGINT NULL,
    [PURGE_ERROR_LOG_ID] BIGINT NULL,
    [SQL_STATEMENT] VARCHAR(4000) NULL,
    [COMMENTS] VARCHAR(4000) NULL,
    CONSTRAINT [PURGE_RUN_DETAILS_PK] PRIMARY KEY CLUSTERED ([ID])
);

-- INTERNAL FK DEPENDENT TABLES

CREATE TABLE [EPS].[PURGE_FLOW_MAP] (
    [TABLE_NAME] VARCHAR(100) NULL,
    [CONSTRAINT_NAME] VARCHAR(100) NULL,
    [PART_NAME] VARCHAR(100) NULL,
    [PART_KEY] VARCHAR(100) NULL,
    [PART_POSITION] BIGINT NULL,
    [HIERARCHY_LEVEL] BIGINT NULL,
    [NUMBER_OF_CHILD] VARCHAR(1) NULL,
    [PURGE_RUN_DETAILS_ID] BIGINT NULL,
    [PURGE_REC_RUN_DETAILS_ID] BIGINT NULL,
    [ADDITIONAL_INFO] VARCHAR(4000) NULL,
    CONSTRAINT [PURGE_FLOW_MAP_UK1] UNIQUE ([TABLE_NAME], [CONSTRAINT_NAME], [PART_NAME]),
    CONSTRAINT [FK_PURGE_FLOW_MAP_FK1] FOREIGN KEY ([PURGE_RUN_DETAILS_ID])
        REFERENCES [EPS].[PURGE_RUN_DETAILS] ([ID]),
    CONSTRAINT [FK_PURGE_FLOW_MAP_FK2] FOREIGN KEY ([PURGE_REC_RUN_DETAILS_ID])
        REFERENCES [EPS].[PURGE_RUN_DETAILS] ([ID])
);

CREATE TABLE [EPS].[PURGE_INDEX_REBUILD_LOG] (
    [ID] BIGINT NOT NULL,
    [PURGE_RUN_DETAILS_ID] BIGINT NULL,
    [TABLE_NAME] VARCHAR(100) NULL,
    [PARTITION_NAME] VARCHAR(100) NULL,
    [INDEX_NAME] VARCHAR(100) NULL,
    [SQL_STATEMENT] VARCHAR(4000) NULL,
    [START_DATE] DATE NULL,
    [END_DATE] DATE NULL,
    [STATUS] VARCHAR(100) NULL,
    [PURGE_ERROR_LOG_ID] BIGINT NULL,
    CONSTRAINT [PURGE_INDEX_REBUILD_LOG_PK] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [FK_PURGE_INDEX_REBUILD_LOG_FK1] FOREIGN KEY ([PURGE_RUN_DETAILS_ID])
        REFERENCES [EPS].[PURGE_RUN_DETAILS] ([ID])
);
