-- TRIGGER: [EPS].[TP_LINK_AUR] - Oracle to Azure SQL conversion
-- Converted: AFTER UPDATE trigger with set-based INSERT...SELECT

IF OBJECT_ID('[EPS].[TP_LINK_AUR]', 'TR') IS NOT NULL
    DROP TRIGGER [EPS].[TP_LINK_AUR];
GO

CREATE TRIGGER [EPS].[TP_LINK_AUR]
ON [EPS].[TP_LINK]
AFTER UPDATE
AS
BEGIN
    INSERT INTO [EPS].[TP_LINK_AUDIT] (
        [CHAIN_ID],
        [ID],
        [DELETED],
        [LAST_UPDATED],
        [LAST],
        [NHIN_ID],
        [ADC],
        [ALT_CARD],
        [BC_HOME],
        [CARD_NUMBER],
        [CARRIER_ID],
        [CLINIC_ID],
        [DEPENDENT_NUMBER],
        [ELIGIBILITY_OVERRIDE],
        [ELIGIBLE],
        [ELIGIBLE_ENDING],
        [ELIGIBLE_STARTING],
        [EMPLOYER_NAME],
        [GROUP_NUMBER],
        [LEVEL_OF],
        [LOCATION],
        [NURSING_HOME],
        [OTHER],
        [PLAN_NUMBER],
        [RELATION],
        [SENIOR_CITIZEN],
        [SERIES_CODE],
        [SPECIAL],
        [STUDENT],
        [ID_PATIENT],
        [ID_CARD],
        [ID_AAL],
        [TP_SOURCE],
        [OTHER_INSURANCE_FEE],
        [TP_ESCRIPT_PLAN],
        [RESIDENCE],
        [CMS_PART_D_QUALIFIED_FACILITY],
        [BENEFITS_NOT_ASSIGNED],
        [MEDICAID_IDENTIFIER],
        [MEDICAID_INDICATOR],
        [DISCOUNT_FLAG],
        [CARD_DESCRIPTION],
        [ADDED_DATE],
        [ADDED_BY_USER],
        [ID_AUDIT],
        [AUDIT_TIMESTAMP]
    )
    SELECT
        [CHAIN_ID],
        [ID],
        [DELETED],
        [LAST_UPDATED],
        [LAST],
        [NHIN_ID],
        [ADC],
        [ALT_CARD],
        [BC_HOME],
        [CARD_NUMBER],
        [CARRIER_ID],
        [CLINIC_ID],
        [DEPENDENT_NUMBER],
        [ELIGIBILITY_OVERRIDE],
        [ELIGIBLE],
        [ELIGIBLE_ENDING],
        [ELIGIBLE_STARTING],
        [EMPLOYER_NAME],
        [GROUP_NUMBER],
        [LEVEL_OF],
        [LOCATION],
        [NURSING_HOME],
        [OTHER],
        [PLAN_NUMBER],
        [RELATION],
        [SENIOR_CITIZEN],
        [SERIES_CODE],
        [SPECIAL],
        [STUDENT],
        [ID_PATIENT],
        [ID_CARD],
        [ID_AAL],
        [TP_SOURCE],
        [OTHER_INSURANCE_FEE],
        [TP_ESCRIPT_PLAN],
        [RESIDENCE],
        [CMS_PART_D_QUALIFIED_FACILITY],
        [BENEFITS_NOT_ASSIGNED],
        [MEDICAID_IDENTIFIER],
        [MEDICAID_INDICATOR],
        [DISCOUNT_FLAG],
        [CARD_DESCRIPTION],
        [ADDED_DATE],
        [ADDED_BY_USER],
        NEXT VALUE FOR [EPS].[AUDIT_SEQ],
        SYSDATETIME()
    FROM deleted;
END;
GO
