-- TRIGGER: [EPS].[AUDIT_MESSAGE_CONTENT_BIUR] - Oracle to Azure SQL conversion
-- Converted: BEFORE INSERT OR UPDATE trigger that sets timestamp

IF OBJECT_ID('[EPS].[AUDIT_MESSAGE_CONTENT_BIUR]', 'TR') IS NOT NULL
    DROP TRIGGER [EPS].[AUDIT_MESSAGE_CONTENT_BIUR];
GO

CREATE TRIGGER [EPS].[AUDIT_MESSAGE_CONTENT_BIUR]
ON [EPS].[AUDIT_MESSAGE_CONTENT]
INSTEAD OF INSERT, UPDATE
AS
BEGIN
    INSERT INTO [EPS].[AUDIT_MESSAGE_CONTENT]
    SELECT *, SYSDATETIME()
    FROM inserted
    WHERE [AUDIT_TIMESTAMP] IS NULL;
END;
GO
