-- TRIGGER: [SEC_ADMIN].[ESSIA_BIR] - Oracle to Azure SQL conversion
-- Converted: BEFORE INSERT trigger with sequence generation

IF OBJECT_ID('[SEC_ADMIN].[ESSIA_BIR]', 'TR') IS NOT NULL
    DROP TRIGGER [SEC_ADMIN].[ESSIA_BIR];
GO

CREATE TRIGGER [SEC_ADMIN].[ESSIA_BIR]
ON [SEC_ADMIN].[EPS_SEC_STORE_IP_ADDRESS]
INSTEAD OF INSERT
AS
BEGIN
    INSERT INTO [SEC_ADMIN].[EPS_SEC_STORE_IP_ADDRESS] (
        [ID]
    )
    SELECT
        NEXT VALUE FOR [SEC_ADMIN].[ESSIA_SEQ]
    FROM inserted;
END;
GO
