CREATE TABLE PBC.MEMBER_ACCT
( 
	ID NUMBER NOT NULL,
	FIRST_NAME VARCHAR2(20) NOT NULL,
	LAST_NAME VARCHAR2(25) NOT NULL,
	CARDHOLDER_ID VARCHAR2(20) NOT NULL,
	MEMBER_GROUP VARCHAR2(15) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	EMAIL VARCHAR2(120) NOT NULL,
	PASSWORD VARCHAR2(40) NOT NULL,
	CREATE_DATE TIMESTAMP(6) DEFAULT sysdate NOT NULL,
	UPDATE_DATE TIMESTAMP(6) DEFAULT sysdate NOT NULL
)
/
CREATE TABLE PBC.MEMBER_ACCT_04182011
( 
	ID NUMBER NOT NULL,
	FIRST_NAME VARCHAR2(20) NOT NULL,
	LAST_NAME VARCHAR2(25) NOT NULL,
	CARDHOLDER_ID VARCHAR2(20) NOT NULL,
	MEMBER_GROUP VARCHAR2(15) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	EMAIL VARCHAR2(120) NOT NULL,
	PASSWORD VARCHAR2(40) NOT NULL
)
/
CREATE TABLE PBC.MEMBER_INFO
( 
	ID NUMBER NOT NULL,
	CARRIER_CODE VARCHAR2(3) NOT NULL,
	MEMBER_GROUP VARCHAR2(15) NOT NULL,
	CARDHOLDER_ID VARCHAR2(20) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR2(12) NOT NULL,
	LAST_NAME VARCHAR2(15) NOT NULL,
	MIDDLE_INITIAL CHAR(1),
	SUFFIX VARCHAR2(3),
	PERSON_CODE VARCHAR2(3),
	ADDRESS VARCHAR2(35),
	ADDRESS_LINE2 VARCHAR2(35),
	CITY VARCHAR2(18),
	STATE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	EFFECTIVE_DATE DATE,
	TERM_DATE DATE,
	GENDER CHAR(1),
	RELAT_CODE CHAR(1),
	COV_CODE CHAR(1),
	CREATE_DATE TIMESTAMP(6) DEFAULT sysdate NOT NULL,
	UPDATE_DATE TIMESTAMP(6) DEFAULT sysdate NOT NULL
)
/
CREATE TABLE PBC.MEMBER_INFO_031011
( 
	ID NUMBER NOT NULL,
	CARRIER_CODE VARCHAR2(3) NOT NULL,
	MEMBER_GROUP VARCHAR2(15) NOT NULL,
	CARDHOLDER_ID VARCHAR2(20) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR2(12) NOT NULL,
	LAST_NAME VARCHAR2(15) NOT NULL,
	MIDDLE_INITIAL CHAR(1),
	SUFFIX VARCHAR2(3),
	PERSON_CODE VARCHAR2(3),
	ADDRESS VARCHAR2(35),
	ADDRESS_LINE2 VARCHAR2(35),
	CITY VARCHAR2(18),
	STATE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	EFFECTIVE_DATE DATE,
	TERM_DATE DATE,
	GENDER CHAR(1),
	RELAT_CODE CHAR(1),
	COV_CODE CHAR(1)
)
/
CREATE TABLE PBC.MEMBER_INFO_04182011
( 
	ID NUMBER NOT NULL,
	CARRIER_CODE VARCHAR2(3) NOT NULL,
	MEMBER_GROUP VARCHAR2(15) NOT NULL,
	CARDHOLDER_ID VARCHAR2(20) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR2(12) NOT NULL,
	LAST_NAME VARCHAR2(15) NOT NULL,
	MIDDLE_INITIAL CHAR(1),
	SUFFIX VARCHAR2(3),
	PERSON_CODE VARCHAR2(3),
	ADDRESS VARCHAR2(35),
	ADDRESS_LINE2 VARCHAR2(35),
	CITY VARCHAR2(18),
	STATE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	EFFECTIVE_DATE DATE,
	TERM_DATE DATE,
	GENDER CHAR(1),
	RELAT_CODE CHAR(1),
	COV_CODE CHAR(1)
)
/
CREATE TABLE PBC.MEMBER_INFO_05122011
( 
	ID NUMBER NOT NULL,
	CARRIER_CODE VARCHAR2(3) NOT NULL,
	MEMBER_GROUP VARCHAR2(15) NOT NULL,
	CARDHOLDER_ID VARCHAR2(20) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR2(12) NOT NULL,
	LAST_NAME VARCHAR2(15) NOT NULL,
	MIDDLE_INITIAL CHAR(1),
	SUFFIX VARCHAR2(3),
	PERSON_CODE VARCHAR2(3),
	ADDRESS VARCHAR2(35),
	ADDRESS_LINE2 VARCHAR2(35),
	CITY VARCHAR2(18),
	STATE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	EFFECTIVE_DATE DATE,
	TERM_DATE DATE,
	GENDER CHAR(1),
	RELAT_CODE CHAR(1),
	COV_CODE CHAR(1)
)
/
CREATE TABLE PBC.MEMBER_INFO_05172011
( 
	ID NUMBER NOT NULL,
	CARRIER_CODE VARCHAR2(3) NOT NULL,
	MEMBER_GROUP VARCHAR2(15) NOT NULL,
	CARDHOLDER_ID VARCHAR2(20) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR2(12) NOT NULL,
	LAST_NAME VARCHAR2(15) NOT NULL,
	MIDDLE_INITIAL CHAR(1),
	SUFFIX VARCHAR2(3),
	PERSON_CODE VARCHAR2(3),
	ADDRESS VARCHAR2(35),
	ADDRESS_LINE2 VARCHAR2(35),
	CITY VARCHAR2(18),
	STATE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	EFFECTIVE_DATE DATE,
	TERM_DATE DATE,
	GENDER CHAR(1),
	RELAT_CODE CHAR(1),
	COV_CODE CHAR(1)
)
/
CREATE TABLE PBC.MEMBER_INFO_08012011
( 
	ID NUMBER NOT NULL,
	CARRIER_CODE VARCHAR2(3) NOT NULL,
	MEMBER_GROUP VARCHAR2(15) NOT NULL,
	CARDHOLDER_ID VARCHAR2(20) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR2(12) NOT NULL,
	LAST_NAME VARCHAR2(15) NOT NULL,
	MIDDLE_INITIAL CHAR(1),
	SUFFIX VARCHAR2(3),
	PERSON_CODE VARCHAR2(3),
	ADDRESS VARCHAR2(35),
	ADDRESS_LINE2 VARCHAR2(35),
	CITY VARCHAR2(18),
	STATE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	EFFECTIVE_DATE DATE,
	TERM_DATE DATE,
	GENDER CHAR(1),
	RELAT_CODE CHAR(1),
	COV_CODE CHAR(1)
)
/
CREATE TABLE PBC.MEMBER_INFO_14072011
( 
	ID NUMBER NOT NULL,
	CARRIER_CODE VARCHAR2(3) NOT NULL,
	MEMBER_GROUP VARCHAR2(15) NOT NULL,
	CARDHOLDER_ID VARCHAR2(20) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR2(12) NOT NULL,
	LAST_NAME VARCHAR2(15) NOT NULL,
	MIDDLE_INITIAL CHAR(1),
	SUFFIX VARCHAR2(3),
	PERSON_CODE VARCHAR2(3),
	ADDRESS VARCHAR2(35),
	ADDRESS_LINE2 VARCHAR2(35),
	CITY VARCHAR2(18),
	STATE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	EFFECTIVE_DATE DATE,
	TERM_DATE DATE,
	GENDER CHAR(1),
	RELAT_CODE CHAR(1),
	COV_CODE CHAR(1)
)
/
CREATE TABLE PBC.MEMBER_INFO_26052011
( 
	ID NUMBER NOT NULL,
	CARRIER_CODE VARCHAR2(3) NOT NULL,
	MEMBER_GROUP VARCHAR2(15) NOT NULL,
	CARDHOLDER_ID VARCHAR2(20) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR2(12) NOT NULL,
	LAST_NAME VARCHAR2(15) NOT NULL,
	MIDDLE_INITIAL CHAR(1),
	SUFFIX VARCHAR2(3),
	PERSON_CODE VARCHAR2(3),
	ADDRESS VARCHAR2(35),
	ADDRESS_LINE2 VARCHAR2(35),
	CITY VARCHAR2(18),
	STATE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	EFFECTIVE_DATE DATE,
	TERM_DATE DATE,
	GENDER CHAR(1),
	RELAT_CODE CHAR(1),
	COV_CODE CHAR(1)
)
/
CREATE TABLE PBC.MEMBER_INFO_29062011
( 
	ID NUMBER NOT NULL,
	CARRIER_CODE VARCHAR2(3) NOT NULL,
	MEMBER_GROUP VARCHAR2(15) NOT NULL,
	CARDHOLDER_ID VARCHAR2(20) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR2(12) NOT NULL,
	LAST_NAME VARCHAR2(15) NOT NULL,
	MIDDLE_INITIAL CHAR(1),
	SUFFIX VARCHAR2(3),
	PERSON_CODE VARCHAR2(3),
	ADDRESS VARCHAR2(35),
	ADDRESS_LINE2 VARCHAR2(35),
	CITY VARCHAR2(18),
	STATE VARCHAR2(2),
	ZIP_CODE VARCHAR2(9),
	EFFECTIVE_DATE DATE,
	TERM_DATE DATE,
	GENDER CHAR(1),
	RELAT_CODE CHAR(1),
	COV_CODE CHAR(1)
)
/
ALTER TABLE PBC.MEMBER_ACCT ADD CONSTRAINT MEMBER_ACCT_PK
	PRIMARY KEY (ID)
/
ALTER TABLE PBC.MEMBER_INFO ADD CONSTRAINT MBR_INFO_UQ_GRP_CARD_NAMES_DOB
	UNIQUE (MEMBER_GROUP, CARDHOLDER_ID, FIRST_NAME, LAST_NAME, BIRTH_DATE)
/
ALTER TABLE PBC.MEMBER_INFO ADD CONSTRAINT MEMBER_INFO_PK
	PRIMARY KEY (ID)
/
