CREATE OR REPLACE SYNONYM WL_DIB3.AGFILE
	FOR DIB3_AUX.AGFILE
/
CREATE OR REPLACE SYNONYM WL_DIB3.DISFILE
	FOR DIB3_AUX.DISFILE
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_BASIC
	FOR DIB3_AUX.IMGIPT_BASIC
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_CATEGORY
	FOR DIB3_AUX.IMGIPT_CATEGORY
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_DESC
	FOR DIB3_AUX.IMGIPT_DESC
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_DOSE_FORM
	FOR DIB3_AUX.IMGIPT_DOSE_FORM
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_IMAGE
	FOR DIB3_AUX.IMGIPT_IMAGE
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_IMPRINT
	FOR DIB3_AUX.IMGIPT_IMPRINT
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_JOURNAL
	FOR DIB3_AUX.IMGIPT_JOURNAL
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_LIB_VERSION
	FOR DIB3_AUX.IMGIPT_LIB_VERSION
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_MANUFACT
	FOR DIB3_AUX.IMGIPT_MANUFACT
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_PROP_DESC
	FOR DIB3_AUX.IMGIPT_PROP_DESC
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_PROP_TEXT
	FOR DIB3_AUX.IMGIPT_PROP_TEXT
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_PROPERTY
	FOR DIB3_AUX.IMGIPT_PROPERTY
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_TEXT
	FOR DIB3_AUX.IMGIPT_TEXT
/
CREATE OR REPLACE SYNONYM WL_DIB3.IMGIPT_UNIQUE
	FOR DIB3_AUX.IMGIPT_UNIQUE
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_ADE_COM
	FOR DIB3_AUX.MMW_ADE_COM
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_ADE_DRUGLINK
	FOR DIB3_AUX.MMW_ADE_DRUGLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_ADE_SPECCOND
	FOR DIB3_AUX.MMW_ADE_SPECCOND
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_CLS_AHFS
	FOR DIB3_AUX.MMW_CLS_AHFS
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_CLS_AHFSDRUG
	FOR DIB3_AUX.MMW_CLS_AHFSDRUG
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_CLS_GPI
	FOR DIB3_AUX.MMW_CLS_GPI
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_CLS_GPIDRUG
	FOR DIB3_AUX.MMW_CLS_GPIDRUG
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_CM_DISPLINK
	FOR DIB3_AUX.MMW_CM_DISPLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_CM_PACKLINK
	FOR DIB3_AUX.MMW_CM_PACKLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_CM_TEXT
	FOR DIB3_AUX.MMW_CM_TEXT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DCK_COM
	FOR DIB3_AUX.MMW_DCK_COM
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DCK_DRUGLINK
	FOR DIB3_AUX.MMW_DCK_DRUGLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DFA_INT
	FOR DIB3_AUX.MMW_DFA_INT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DFA_TEXT
	FOR DIB3_AUX.MMW_DFA_TEXT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DI_CLASSLINK
	FOR DIB3_AUX.MMW_DI_CLASSLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DI_INT
	FOR DIB3_AUX.MMW_DI_INT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DI_RPIDLINK
	FOR DIB3_AUX.MMW_DI_RPIDLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DI_TEXT
	FOR DIB3_AUX.MMW_DI_TEXT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_DISP
	FOR DIB3_AUX.MMW_DRUG_DISP
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_DISP_LBLR
	FOR DIB3_AUX.MMW_DRUG_DISP_LBLR
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_DOSEFORM
	FOR DIB3_AUX.MMW_DRUG_DOSEFORM
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_GPI
	FOR DIB3_AUX.MMW_DRUG_GPI
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_GPILINK
	FOR DIB3_AUX.MMW_DRUG_GPILINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_KDC
	FOR DIB3_AUX.MMW_DRUG_KDC
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_KDCLINK
	FOR DIB3_AUX.MMW_DRUG_KDCLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_LABELER
	FOR DIB3_AUX.MMW_DRUG_LABELER
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_NAME
	FOR DIB3_AUX.MMW_DRUG_NAME
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_PACK
	FOR DIB3_AUX.MMW_DRUG_PACK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_PACK_MOD
	FOR DIB3_AUX.MMW_DRUG_PACK_MOD
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_ROUTE
	FOR DIB3_AUX.MMW_DRUG_ROUTE
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DRUG_ROUTED
	FOR DIB3_AUX.MMW_DRUG_ROUTED
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DUP_DRUGLINK
	FOR DIB3_AUX.MMW_DUP_DRUGLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_DUP_TEXT
	FOR DIB3_AUX.MMW_DUP_TEXT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_FC_CONTENT
	FOR DIB3_AUX.MMW_FC_CONTENT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_FC_DRUGLINK
	FOR DIB3_AUX.MMW_FC_DRUGLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_FC_ELEMENT
	FOR DIB3_AUX.MMW_FC_ELEMENT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_FC_SECTION
	FOR DIB3_AUX.MMW_FC_SECTION
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_FC_SECTION_CONTENT
	FOR DIB3_AUX.MMW_FC_SECTION_CONTENT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_FC_SECTIONLINK
	FOR DIB3_AUX.MMW_FC_SECTIONLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_IND_COM
	FOR DIB3_AUX.MMW_IND_COM
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_IND_COTREAT
	FOR DIB3_AUX.MMW_IND_COTREAT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_IND_DRUGLINK
	FOR DIB3_AUX.MMW_IND_DRUGLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_IND_RPID
	FOR DIB3_AUX.MMW_IND_RPID
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_IND_SOURCE
	FOR DIB3_AUX.MMW_IND_SOURCE
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_LIB_CODEDEF
	FOR DIB3_AUX.MMW_LIB_CODEDEF
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_LIB_DISCLAIMER
	FOR DIB3_AUX.MMW_LIB_DISCLAIMER
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_LIB_VERSION
	FOR DIB3_AUX.MMW_LIB_VERSION
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_MED
	FOR DIB3_AUX.MMW_MED
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_MED_CIT
	FOR DIB3_AUX.MMW_MED_CIT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_MED_EXTVOCAB
	FOR DIB3_AUX.MMW_MED_EXTVOCAB
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_MED_HIER
	FOR DIB3_AUX.MMW_MED_HIER
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_MED_INTVOCAB
	FOR DIB3_AUX.MMW_MED_INTVOCAB
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_MED_LINK
	FOR DIB3_AUX.MMW_MED_LINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_MED_NAME
	FOR DIB3_AUX.MMW_MED_NAME
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_MED_TEXT
	FOR DIB3_AUX.MMW_MED_TEXT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_MED_TEXT_CIT
	FOR DIB3_AUX.MMW_MED_TEXT_CIT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_MONO_CLSNAME
	FOR DIB3_AUX.MMW_MONO_CLSNAME
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_MONO_TEXT
	FOR DIB3_AUX.MMW_MONO_TEXT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PAR_CLASS
	FOR DIB3_AUX.MMW_PAR_CLASS
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PAR_CLASSLINK
	FOR DIB3_AUX.MMW_PAR_CLASSLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PAR_DRUGLINK
	FOR DIB3_AUX.MMW_PAR_DRUGLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PAR_INGRLINK
	FOR DIB3_AUX.MMW_PAR_INGRLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PAR_INT
	FOR DIB3_AUX.MMW_PAR_INT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PDE_DRUGLINK
	FOR DIB3_AUX.MMW_PDE_DRUGLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PRCA_COM
	FOR DIB3_AUX.MMW_PRCA_COM
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PRCA_DRUGLINK
	FOR DIB3_AUX.MMW_PRCA_DRUGLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PRCA_SPECCOND
	FOR DIB3_AUX.MMW_PRCA_SPECCOND
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PRCC_COM
	FOR DIB3_AUX.MMW_PRCC_COM
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PRCC_DRUGLINK
	FOR DIB3_AUX.MMW_PRCC_DRUGLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_PRCC_SPECCOND
	FOR DIB3_AUX.MMW_PRCC_SPECCOND
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_SNOMED_MC_LINK
	FOR DIB3_AUX.MMW_SNOMED_MC_LINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_WL_DRUGLINK
	FOR DIB3_AUX.MMW_WL_DRUGLINK
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_WL_TEXT
	FOR DIB3_AUX.MMW_WL_TEXT
/
CREATE OR REPLACE SYNONYM WL_DIB3.MMW_WL_VENDCODE
	FOR DIB3_AUX.MMW_WL_VENDCODE
/
CREATE OR REPLACE SYNONYM WL_DIB3.TOP_DRUGS
	FOR DIB3_AUX.TOP_DRUGS
/
