INSERT INTO ALL_CONSTRAINTS ("DBMS_METADATA.GET_DDL('CONSTRAINT',CONSTRAINT_NAME,OWNER)") VALUES
	 (TO_CLOB('
  ALTER TABLE "ARS"."ARS_PROPERTIES" ADD CONSTRAINT "ARS_PROPERTIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."ARS_PROPERTIES" ADD CONSTRAINT "ARS_PROP_UQ_KEY" UNIQUE ("KEY")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILLABLE_PRODUCT" ADD CONSTRAINT "BILLABLE_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILLABLE_PRODUCT" ADD CONSTRAINT "BILLABLE_PRODUCT_UK1" UNIQUE ("NAME")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILLABLE_VENDOR" ADD CONSTRAINT "BILLABLE_VENDOR_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILLABLE_VENDOR_PRODUCT" ADD CONSTRAINT "BILLABLE_VENDOR_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILLABLE_VENDOR_PRODUCT" ADD CONSTRAINT "BILLABLE_VENDOR_PRODUCT_UK1" UNIQUE ("BILLABLE_VENDOR_ID", "BILLABLE_PRODUCT_ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILLABLE_VENDOR" ADD CONSTRAINT "BILLABLE_VENDOR_UK1" UNIQUE ("VENDOR_SHORT_NAME")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILLABLE_VENDOR" ADD CONSTRAINT "BILLABLE_VENDOR_UK2" UNIQUE ("VENDOR_NPI")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILLABLE_VENDOR" ADD CONSTRAINT "BILLABLE_VENDOR_UK3" UNIQUE ("VENDOR_NCPDP")
  USING INDEX  ENABLE'));
INSERT INTO ALL_CONSTRAINTS ("DBMS_METADATA.GET_DDL('CONSTRAINT',CONSTRAINT_NAME,OWNER)") VALUES
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILLABLE_VENDOR" ADD CONSTRAINT "BILLABLE_VENDOR_UK4" UNIQUE ("VENDOR_NHIN")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILLABLE_VEND_PROD_STORE" ADD CONSTRAINT "BILLABLE_VEND_PROD_STORE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILLABLE_VEND_PROD_STORE" ADD CONSTRAINT "BILLABLE_VEND_PROD_STORE_UK1" UNIQUE ("BILLABLE_VENDOR_ID", "BILLABLE_PRODUCT_ID", "STORE_ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."BILL_VEND_PROD_STORE_AUDIT" ADD CONSTRAINT "BILL_VEND_PROD_STORE_AUDIT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."CHAINS" ADD CONSTRAINT "CHAINS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."CHAINS" ADD CONSTRAINT "CHAINS_UQ_HQ_ID" UNIQUE ("HQ_ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."CHAINS" ADD CONSTRAINT "CHAINS_UQ_NHINID" UNIQUE ("NHINID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."CHAIN_PRODUCT_AUDIT" ADD CONSTRAINT "CHAIN_PRODUCT_AUDIT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."CHAIN_PRODUCT" ADD CONSTRAINT "CHAIN_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."CHAIN_PRODUCT" ADD CONSTRAINT "CHAIN_PRODUCT_UK1" UNIQUE ("CHAINS_ID", "PRODUCTS_ID")
  USING INDEX  ENABLE'));
INSERT INTO ALL_CONSTRAINTS ("DBMS_METADATA.GET_DDL('CONSTRAINT',CONSTRAINT_NAME,OWNER)") VALUES
	 (TO_CLOB('
  ALTER TABLE "ARS"."COMM_RESTRICTIONS" ADD CONSTRAINT "COMM_RESTRICTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."CONTACT_INFO" ADD CONSTRAINT "CONTACT_INFO_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."DIVISIONS" ADD CONSTRAINT "DIVISIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."DIVISIONS" ADD CONSTRAINT "DIVISIONS_UK1" UNIQUE ("CHAIN_ID", "NAME")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."INTERFACES" ADD CONSTRAINT "INTERFACES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."INTERFACES" ADD CONSTRAINT "INTERFACES_UK1" UNIQUE ("NAME", "STORE_ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."INTERFACE_VERSION_MAP" ADD CONSTRAINT "INTERFACE_VERSION_MAP_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."INTERFACE_VERSION_MAP" ADD CONSTRAINT "INTERFACE_VERSION_MAP_UK1" UNIQUE ("STORE_ID", "SERVICE_NAME")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_CONFIG" ADD CONSTRAINT "PDX_SCHEMA_CONFIG_PK" PRIMARY KEY ("KEY")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_FILE_HASH" ADD CONSTRAINT "PDX_SCHEMA_FILE_HASH_PK" PRIMARY KEY ("FILE_NAME", "FILE_SOURCE")
  USING INDEX  ENABLE'));
INSERT INTO ALL_CONSTRAINTS ("DBMS_METADATA.GET_DDL('CONSTRAINT',CONSTRAINT_NAME,OWNER)") VALUES
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_FILE_TASKVER" ADD CONSTRAINT "PDX_SCHEMA_FILE_TASKVER_PK" PRIMARY KEY ("FILE_NAME")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_FILE_TASKVER" ADD CONSTRAINT "PDX_SCHEMA_FILE_TASKVER_UK1" UNIQUE ("TASK_VERSION")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_MAPPING" ADD CONSTRAINT "PDX_SCHEMA_MAPPING_PK" PRIMARY KEY ("SEARCH")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_PRIV_DEFAULT" ADD CONSTRAINT "PDX_SCHEMA_PRIV_DEFAULT_PK" PRIMARY KEY ("GRANTEE", "OBJECT_TYPE", "PRIVILEGE")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_PRIV_EXCEPTION" ADD CONSTRAINT "PDX_SCHEMA_PRIV_EXCEPTION_PK" PRIMARY KEY ("GRANTEE", "OBJECT_TYPE", "OBJECT_NAME", "PRIVILEGE")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_PROCESS_HISTORY" ADD CONSTRAINT "PDX_SCHEMA_PROCESS_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_PROCESS_HISTORY" ADD CONSTRAINT "PDX_SCHEMA_PROCESS_HISTORY_UK1" UNIQUE ("PDX_SCHEMA_UPD_PKGCALL_HIST_ID", "PDX_SCHEMA_VERSION_HISTORY_ID", "PROCESS")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_TASKVER_META" ADD CONSTRAINT "PDX_SCHEMA_TASKVER_META_PK" PRIMARY KEY ("TASK_VERSION", "TASK_SOURCE", "META_TAG", "TASK_VERSION_VALUE")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_TASK_ERROR_LOG" ADD CONSTRAINT "PDX_SCHEMA_TASK_ERROR_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_TASK_HISTORY" ADD CONSTRAINT "PDX_SCHEMA_TASK_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE'));
INSERT INTO ALL_CONSTRAINTS ("DBMS_METADATA.GET_DDL('CONSTRAINT',CONSTRAINT_NAME,OWNER)") VALUES
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_UPDATER_MANIFEST" ADD CONSTRAINT "PDX_SCHEMA_UPDATER_MANIFEST_PK" PRIMARY KEY ("VERSION")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_UPDATER_MANIFEST" ADD CONSTRAINT "PDX_SCHEMA_UPDATER_MANIFST_UK1" UNIQUE ("FILE_NAME")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_UPDATER_MANIFEST" ADD CONSTRAINT "PDX_SCHEMA_UPDATER_MANIFST_UK2" UNIQUE ("APPLY_ORDER")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_UPDATER_SQL" ADD CONSTRAINT "PDX_SCHEMA_UPDATER_SQL_PK" PRIMARY KEY ("FILE_NAME")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_UPD_HELPER_DEBUG_D" ADD CONSTRAINT "PDX_SCHEMA_UPD_HLPR_DBG_D_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_UPD_HELPER_DEBUG_H" ADD CONSTRAINT "PDX_SCHEMA_UPD_HLPR_DBG_H_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_UPD_PKGCALL_ERR_LOG" ADD CONSTRAINT "PDX_SCHEMA_UPD_PKGCALL_ELOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_UPD_PKGCALL_HIST" ADD CONSTRAINT "PDX_SCHEMA_UPD_PKGCALL_HIST_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_VERSION_ERROR_LOG" ADD CONSTRAINT "PDX_SCHEMA_VERSION_ERR_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PDX_SCHEMA_VERSION_HISTORY" ADD CONSTRAINT "PDX_SCHEMA_VERSION_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE'));
INSERT INTO ALL_CONSTRAINTS ("DBMS_METADATA.GET_DDL('CONSTRAINT',CONSTRAINT_NAME,OWNER)") VALUES
	 (TO_CLOB('
  ALTER TABLE "ARS"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_UQ_NAME" UNIQUE ("NAME")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."PUSH_UPDATES" ADD CONSTRAINT "PUSH_UPDATES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."RXCOM_CA_CERT" ADD CONSTRAINT "RXCOM_CA_CERT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."RXCOM_CERTIFICATES" ADD CONSTRAINT "RXCOM_CERTIFICATES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."RXCOM_CERTIFICATES" ADD CONSTRAINT "RXCOM_CERTIFICATES_UK1" UNIQUE ("SHA1_THUMBPRINT")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."SCHEMA_UPDATER_MANIFEST" ADD CONSTRAINT "SCHEMA_UPDATER_MANIFEST_PK" PRIMARY KEY ("FILE_NAME")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."SCHEMA_UPDATER_MANIFEST" ADD CONSTRAINT "SCHEMA_UPDATER_MANIFEST_UK1" UNIQUE ("VERSION")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."SCHEMA_UPDATER_MANIFEST" ADD CONSTRAINT "SCHEMA_UPDATER_MANIFST_UK2" UNIQUE ("APPLY_ORDER")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."SCHEMA_UPDATER_SQL" ADD CONSTRAINT "SCHEMA_UPDATER_SQL_PK" PRIMARY KEY ("FILE_NAME")
  USING INDEX  ENABLE'));
INSERT INTO ALL_CONSTRAINTS ("DBMS_METADATA.GET_DDL('CONSTRAINT',CONSTRAINT_NAME,OWNER)") VALUES
	 (TO_CLOB('
  ALTER TABLE "ARS"."STORES" ADD CONSTRAINT "STORES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."STORES" ADD CONSTRAINT "STORES_UQ_NCPDP" UNIQUE ("NCPDP")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."STORES" ADD CONSTRAINT "STORES_UQ_NHINID" UNIQUE ("NHINID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."STORES" ADD CONSTRAINT "STORES_UQ_NPI" UNIQUE ("NPI")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."STORE_HOURS" ADD CONSTRAINT "STORE_HOURS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."STORE_PRODUCT_VENDOR_AUDIT" ADD CONSTRAINT "STORE_PRODUCT_VENDOR_AUDIT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."STORE_PRODUCT_VENDOR" ADD CONSTRAINT "STORE_PRODUCT_VENDOR_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."STORE_PRODUCT_VENDOR" ADD CONSTRAINT "STORE_PRODUCT_VENDOR_UK1" UNIQUE ("STORE_ID", "VENDOR_ID", "PRODUCT_ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."USER_AUDIT_LOG" ADD CONSTRAINT "USER_AUDIT_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR_CERT" ADD CONSTRAINT "VENDOR_CERT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE'));
INSERT INTO ALL_CONSTRAINTS ("DBMS_METADATA.GET_DDL('CONSTRAINT',CONSTRAINT_NAME,OWNER)") VALUES
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR_CERT" ADD CONSTRAINT "VENDOR_CERT_UQ_VNDR_CERT_THUMB" UNIQUE ("VENDOR_CERT_THUMBPRINT")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR" ADD CONSTRAINT "VENDOR_PK" PRIMARY KEY ("ID")
  USING INDEX REVERSE  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR_PRODUCT_INFO" ADD CONSTRAINT "VENDOR_PRODUCT_INFO_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR_PRODUCT_INFO" ADD CONSTRAINT "VENDOR_PRODUCT_INFO_UK" UNIQUE ("VENDOR_ID", "PRODUCT_ID", "CHAIN_ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR_PRODUCT" ADD CONSTRAINT "VENDOR_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR_PRODUCT" ADD CONSTRAINT "VENDOR_PRODUCT_UK1" UNIQUE ("VENDOR_ID", "PRODUCT_ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR" ADD CONSTRAINT "VENDOR_UQ_SHORTNAME" UNIQUE ("VENDOR_SHORT_NAME")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR" ADD CONSTRAINT "VENDOR_UQ_VENDOR_NCPDP" UNIQUE ("VENDOR_NCPDP")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR" ADD CONSTRAINT "VENDOR_UQ_VENDOR_NHIN" UNIQUE ("VENDOR_NHIN")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR" ADD CONSTRAINT "VENDOR_UQ_VENDOR_NPI" UNIQUE ("VENDOR_NPI")
  USING INDEX  ENABLE'));
INSERT INTO ALL_CONSTRAINTS ("DBMS_METADATA.GET_DDL('CONSTRAINT',CONSTRAINT_NAME,OWNER)") VALUES
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR_CERT_REQUEST" ADD CONSTRAINT "VNDR_CERT_REQUEST_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE')),
	 (TO_CLOB('
  ALTER TABLE "ARS"."VENDOR_CERT_REQUEST" ADD CONSTRAINT "VNDR_CERT_REQUEST_UQ_ACCESSKEY" UNIQUE ("ACCESS_KEY")
  USING INDEX  ENABLE'));
