-- SBMO_MEIJER_RPT Synonyms - Corrected for DEV MI Local References
-- Target: SBMO_MEIJER views in same database (nonEPR-DB)
-- Changed from: FOR [sqldb-epr-qa].SBMO_MEIJER.[ObjectName]
-- Changed to:   FOR SBMO_MEIJER.[ObjectName]

IF NOT EXISTS(SELECT * FROM sys.schemas WHERE [name] = N'SBMO_MEIJER_RPT')      
     EXEC (N'CREATE SCHEMA SBMO_MEIJER_RPT')                                   
 GO                                                               
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ADDRESSES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.ADDRESSES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.ADDRESSES FOR SBMO_MEIJER.ADDRESSES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.ADDRESSES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'ADDRESSES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ADJUSTMENT_CODES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.ADJUSTMENT_CODES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.ADJUSTMENT_CODES FOR SBMO_MEIJER.ADJUSTMENT_CODES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.ADJUSTMENT_CODES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'ADJUSTMENT_CODES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ADJUSTMENT_GROUP'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.ADJUSTMENT_GROUP
GO
CREATE SYNONYM SBMO_MEIJER_RPT.ADJUSTMENT_GROUP FOR SBMO_MEIJER.ADJUSTMENT_GROUP
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.ADJUSTMENT_GROUP',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'ADJUSTMENT_GROUP'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'AUDIT_LOG'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.AUDIT_LOG
GO
CREATE SYNONYM SBMO_MEIJER_RPT.AUDIT_LOG FOR SBMO_MEIJER.AUDIT_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.AUDIT_LOG',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'AUDIT_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'BIN_UPC_LINK'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.BIN_UPC_LINK
GO
CREATE SYNONYM SBMO_MEIJER_RPT.BIN_UPC_LINK FOR SBMO_MEIJER.BIN_UPC_LINK
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.BIN_UPC_LINK',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'BIN_UPC_LINK'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CARRIER'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.CARRIER
GO
CREATE SYNONYM SBMO_MEIJER_RPT.CARRIER FOR SBMO_MEIJER.CARRIER
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.CARRIER',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'CARRIER'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CF_SEC_CHAIN'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.CF_SEC_CHAIN
GO
CREATE SYNONYM SBMO_MEIJER_RPT.CF_SEC_CHAIN FOR SBMO_MEIJER.CF_SEC_CHAIN
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.CF_SEC_CHAIN',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'CF_SEC_CHAIN'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CF_SEC_STORE'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.CF_SEC_STORE
GO
CREATE SYNONYM SBMO_MEIJER_RPT.CF_SEC_STORE FOR SBMO_MEIJER.CF_SEC_STORE
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.CF_SEC_STORE',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'CF_SEC_STORE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CHAINS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.CHAINS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.CHAINS FOR SBMO_MEIJER.CHAINS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.CHAINS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'CHAINS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CHARGE_PAYMENT_INFO'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.CHARGE_PAYMENT_INFO
GO
CREATE SYNONYM SBMO_MEIJER_RPT.CHARGE_PAYMENT_INFO FOR SBMO_MEIJER.CHARGE_PAYMENT_INFO
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.CHARGE_PAYMENT_INFO',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'CHARGE_PAYMENT_INFO'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CONTACTS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.CONTACTS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.CONTACTS FOR SBMO_MEIJER.CONTACTS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.CONTACTS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'CONTACTS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CUSTOM_SCHEDULED_TASK'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.CUSTOM_SCHEDULED_TASK
GO
CREATE SYNONYM SBMO_MEIJER_RPT.CUSTOM_SCHEDULED_TASK FOR SBMO_MEIJER.CUSTOM_SCHEDULED_TASK
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.CUSTOM_SCHEDULED_TASK',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'CUSTOM_SCHEDULED_TASK'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DAILY_SCHEDULED_TASKS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.DAILY_SCHEDULED_TASKS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.DAILY_SCHEDULED_TASKS FOR SBMO_MEIJER.DAILY_SCHEDULED_TASKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.DAILY_SCHEDULED_TASKS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'DAILY_SCHEDULED_TASKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DISPENSER_LOCATION'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.DISPENSER_LOCATION
GO
CREATE SYNONYM SBMO_MEIJER_RPT.DISPENSER_LOCATION FOR SBMO_MEIJER.DISPENSER_LOCATION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.DISPENSER_LOCATION',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'DISPENSER_LOCATION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DISPENSERS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.DISPENSERS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.DISPENSERS FOR SBMO_MEIJER.DISPENSERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.DISPENSERS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'DISPENSERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DRUG_ORDER_PRODUCT_VERIFY'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.DRUG_ORDER_PRODUCT_VERIFY
GO
CREATE SYNONYM SBMO_MEIJER_RPT.DRUG_ORDER_PRODUCT_VERIFY FOR SBMO_MEIJER.DRUG_ORDER_PRODUCT_VERIFY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.DRUG_ORDER_PRODUCT_VERIFY',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'DRUG_ORDER_PRODUCT_VERIFY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DRUG_ORDERS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.DRUG_ORDERS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.DRUG_ORDERS FOR SBMO_MEIJER.DRUG_ORDERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.DRUG_ORDERS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'DRUG_ORDERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'DRUGS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.DRUGS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.DRUGS FOR SBMO_MEIJER.DRUGS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.DRUGS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'DRUGS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ENTITIES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.ENTITIES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.ENTITIES FOR SBMO_MEIJER.ENTITIES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.ENTITIES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'ENTITIES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'FACILITIES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.FACILITIES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.FACILITIES FOR SBMO_MEIJER.FACILITIES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.FACILITIES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'FACILITIES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'FORMULARY'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.FORMULARY
GO
CREATE SYNONYM SBMO_MEIJER_RPT.FORMULARY FOR SBMO_MEIJER.FORMULARY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.FORMULARY',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'FORMULARY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'FORMULARY_REORDER'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.FORMULARY_REORDER
GO
CREATE SYNONYM SBMO_MEIJER_RPT.FORMULARY_REORDER FOR SBMO_MEIJER.FORMULARY_REORDER
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.FORMULARY_REORDER',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'FORMULARY_REORDER'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'INVENTORY'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.INVENTORY
GO
CREATE SYNONYM SBMO_MEIJER_RPT.INVENTORY FOR SBMO_MEIJER.INVENTORY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.INVENTORY',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'INVENTORY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'INVENTORY_AUDIT'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.INVENTORY_AUDIT
GO
CREATE SYNONYM SBMO_MEIJER_RPT.INVENTORY_AUDIT FOR SBMO_MEIJER.INVENTORY_AUDIT
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.INVENTORY_AUDIT',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'INVENTORY_AUDIT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'INVENTORY_DATE'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.INVENTORY_DATE
GO
CREATE SYNONYM SBMO_MEIJER_RPT.INVENTORY_DATE FOR SBMO_MEIJER.INVENTORY_DATE
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.INVENTORY_DATE',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'INVENTORY_DATE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ITEM_LOCATION'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.ITEM_LOCATION
GO
CREATE SYNONYM SBMO_MEIJER_RPT.ITEM_LOCATION FOR SBMO_MEIJER.ITEM_LOCATION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.ITEM_LOCATION',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'ITEM_LOCATION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'LABEL_IMAGES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.LABEL_IMAGES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.LABEL_IMAGES FOR SBMO_MEIJER.LABEL_IMAGES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.LABEL_IMAGES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'LABEL_IMAGES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'LOCATION'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.LOCATION
GO
CREATE SYNONYM SBMO_MEIJER_RPT.LOCATION FOR SBMO_MEIJER.LOCATION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.LOCATION',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'LOCATION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MASTER_PRODUCT_PO_VERIFY'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.MASTER_PRODUCT_PO_VERIFY
GO
CREATE SYNONYM SBMO_MEIJER_RPT.MASTER_PRODUCT_PO_VERIFY FOR SBMO_MEIJER.MASTER_PRODUCT_PO_VERIFY
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.MASTER_PRODUCT_PO_VERIFY',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'MASTER_PRODUCT_PO_VERIFY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MESSAGE_LOG'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.MESSAGE_LOG
GO
CREATE SYNONYM SBMO_MEIJER_RPT.MESSAGE_LOG FOR SBMO_MEIJER.MESSAGE_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.MESSAGE_LOG',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'MESSAGE_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MONTHLY_SCHEDULED_TASKS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.MONTHLY_SCHEDULED_TASKS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.MONTHLY_SCHEDULED_TASKS FOR SBMO_MEIJER.MONTHLY_SCHEDULED_TASKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.MONTHLY_SCHEDULED_TASKS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'MONTHLY_SCHEDULED_TASKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ONCE_SCHEDULED_TASKS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.ONCE_SCHEDULED_TASKS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.ONCE_SCHEDULED_TASKS FOR SBMO_MEIJER.ONCE_SCHEDULED_TASKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.ONCE_SCHEDULED_TASKS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'ONCE_SCHEDULED_TASKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ORDERS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.ORDERS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.ORDERS FOR SBMO_MEIJER.ORDERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.ORDERS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'ORDERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PHONE_ADDRESS_OWNERS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.PHONE_ADDRESS_OWNERS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.PHONE_ADDRESS_OWNERS FOR SBMO_MEIJER.PHONE_ADDRESS_OWNERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.PHONE_ADDRESS_OWNERS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'PHONE_ADDRESS_OWNERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PHONES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.PHONES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.PHONES FOR SBMO_MEIJER.PHONES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.PHONES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'PHONES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PRIORITY_CHANGE_ALERTS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.PRIORITY_CHANGE_ALERTS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.PRIORITY_CHANGE_ALERTS FOR SBMO_MEIJER.PRIORITY_CHANGE_ALERTS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.PRIORITY_CHANGE_ALERTS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'PRIORITY_CHANGE_ALERTS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PURCHASE_ORDER'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.PURCHASE_ORDER
GO
CREATE SYNONYM SBMO_MEIJER_RPT.PURCHASE_ORDER FOR SBMO_MEIJER.PURCHASE_ORDER
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.PURCHASE_ORDER',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'PURCHASE_ORDER'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PURCHASE_ORDER_GROUP'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.PURCHASE_ORDER_GROUP
GO
CREATE SYNONYM SBMO_MEIJER_RPT.PURCHASE_ORDER_GROUP FOR SBMO_MEIJER.PURCHASE_ORDER_GROUP
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.PURCHASE_ORDER_GROUP',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'PURCHASE_ORDER_GROUP'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'REGION'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.REGION
GO
CREATE SYNONYM SBMO_MEIJER_RPT.REGION FOR SBMO_MEIJER.REGION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.REGION',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'REGION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'REPORT_REQUEST'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.REPORT_REQUEST
GO
CREATE SYNONYM SBMO_MEIJER_RPT.REPORT_REQUEST FOR SBMO_MEIJER.REPORT_REQUEST
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.REPORT_REQUEST',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'REPORT_REQUEST'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'REPORT_REQUEST_PARAMETER'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.REPORT_REQUEST_PARAMETER
GO
CREATE SYNONYM SBMO_MEIJER_RPT.REPORT_REQUEST_PARAMETER FOR SBMO_MEIJER.REPORT_REQUEST_PARAMETER
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.REPORT_REQUEST_PARAMETER',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'REPORT_REQUEST_PARAMETER'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RETAIL_COST'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RETAIL_COST
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RETAIL_COST FOR SBMO_MEIJER.RETAIL_COST
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RETAIL_COST',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RETAIL_COST'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RETURN_AND_ADJUSTMENT'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RETURN_AND_ADJUSTMENT
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RETURN_AND_ADJUSTMENT FOR SBMO_MEIJER.RETURN_AND_ADJUSTMENT
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RETURN_AND_ADJUSTMENT',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RETURN_AND_ADJUSTMENT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_CORES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_CORES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_CORES FOR SBMO_MEIJER.RX_CORES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_CORES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_CORES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_CORES_MIN_DATE'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_CORES_MIN_DATE
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_CORES_MIN_DATE FOR SBMO_MEIJER.RX_CORES_MIN_DATE
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_CORES_MIN_DATE',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_CORES_MIN_DATE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_DETAILS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_DETAILS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_DETAILS FOR SBMO_MEIJER.RX_DETAILS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_DETAILS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_DETAILS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_DOCUMENTS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_DOCUMENTS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_DOCUMENTS FOR SBMO_MEIJER.RX_DOCUMENTS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_DOCUMENTS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_DOCUMENTS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_LOTS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_LOTS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_LOTS FOR SBMO_MEIJER.RX_LOTS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_LOTS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_LOTS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_PATSTORES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_PATSTORES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_PATSTORES FOR SBMO_MEIJER.RX_PATSTORES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_PATSTORES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_PATSTORES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_PRINT_CHR'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_PRINT_CHR
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_PRINT_CHR FOR SBMO_MEIJER.RX_PRINT_CHR
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_PRINT_CHR',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_PRINT_CHR'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_PRINT_INFO'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_PRINT_INFO
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_PRINT_INFO FOR SBMO_MEIJER.RX_PRINT_INFO
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_PRINT_INFO',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_PRINT_INFO'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_REQUEST_ERROR'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_REQUEST_ERROR
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_REQUEST_ERROR FOR SBMO_MEIJER.RX_REQUEST_ERROR
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_REQUEST_ERROR',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_REQUEST_ERROR'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_SHIPPING_PACKAGES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_SHIPPING_PACKAGES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_SHIPPING_PACKAGES FOR SBMO_MEIJER.RX_SHIPPING_PACKAGES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_SHIPPING_PACKAGES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_SHIPPING_PACKAGES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_STATE_TRANSITION'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_STATE_TRANSITION
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_STATE_TRANSITION FOR SBMO_MEIJER.RX_STATE_TRANSITION
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_STATE_TRANSITION',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_STATE_TRANSITION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_TP_INFO'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_TP_INFO
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_TP_INFO FOR SBMO_MEIJER.RX_TP_INFO
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_TP_INFO',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_TP_INFO'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_VIAL_INFOS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_VIAL_INFOS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_VIAL_INFOS FOR SBMO_MEIJER.RX_VIAL_INFOS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_VIAL_INFOS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_VIAL_INFOS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_WARNING_LABEL_CODES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_WARNING_LABEL_CODES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_WARNING_LABEL_CODES FOR SBMO_MEIJER.RX_WARNING_LABEL_CODES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_WARNING_LABEL_CODES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_WARNING_LABEL_CODES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'RX_WARNING_LABELS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.RX_WARNING_LABELS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.RX_WARNING_LABELS FOR SBMO_MEIJER.RX_WARNING_LABELS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.RX_WARNING_LABELS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'RX_WARNING_LABELS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SCHEDULED_TASKS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.SCHEDULED_TASKS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.SCHEDULED_TASKS FOR SBMO_MEIJER.SCHEDULED_TASKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.SCHEDULED_TASKS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'SCHEDULED_TASKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SHIP_ITEMS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.SHIP_ITEMS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.SHIP_ITEMS FOR SBMO_MEIJER.SHIP_ITEMS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.SHIP_ITEMS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'SHIP_ITEMS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SHIPMENT'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.SHIPMENT
GO
CREATE SYNONYM SBMO_MEIJER_RPT.SHIPMENT FOR SBMO_MEIJER.SHIPMENT
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.SHIPMENT',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'SHIPMENT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORE_SHIP_VIA'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.STORE_SHIP_VIA
GO
CREATE SYNONYM SBMO_MEIJER_RPT.STORE_SHIP_VIA FOR SBMO_MEIJER.STORE_SHIP_VIA
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.STORE_SHIP_VIA',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'STORE_SHIP_VIA'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORE_VENDOR_ACCOUNT'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.STORE_VENDOR_ACCOUNT
GO
CREATE SYNONYM SBMO_MEIJER_RPT.STORE_VENDOR_ACCOUNT FOR SBMO_MEIJER.STORE_VENDOR_ACCOUNT
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.STORE_VENDOR_ACCOUNT',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'STORE_VENDOR_ACCOUNT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.STORES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.STORES FOR SBMO_MEIJER.STORES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.STORES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'STORES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SYSTEM_MESSAGES'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.SYSTEM_MESSAGES
GO
CREATE SYNONYM SBMO_MEIJER_RPT.SYSTEM_MESSAGES FOR SBMO_MEIJER.SYSTEM_MESSAGES
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.SYSTEM_MESSAGES',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'SYSTEM_MESSAGES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'TENANTS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.TENANTS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.TENANTS FOR SBMO_MEIJER.TENANTS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.TENANTS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'TENANTS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'VENDOR'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.VENDOR
GO
CREATE SYNONYM SBMO_MEIJER_RPT.VENDOR FOR SBMO_MEIJER.VENDOR
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.VENDOR',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'VENDOR'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'VENDOR_ITEM_PROP'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.VENDOR_ITEM_PROP
GO
CREATE SYNONYM SBMO_MEIJER_RPT.VENDOR_ITEM_PROP FOR SBMO_MEIJER.VENDOR_ITEM_PROP
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.VENDOR_ITEM_PROP',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'VENDOR_ITEM_PROP'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'VENDOR_PO_CREATE_DAYS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.VENDOR_PO_CREATE_DAYS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.VENDOR_PO_CREATE_DAYS FOR SBMO_MEIJER.VENDOR_PO_CREATE_DAYS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.VENDOR_PO_CREATE_DAYS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'VENDOR_PO_CREATE_DAYS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'VENDOR_PROP'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.VENDOR_PROP
GO
CREATE SYNONYM SBMO_MEIJER_RPT.VENDOR_PROP FOR SBMO_MEIJER.VENDOR_PROP
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.VENDOR_PROP',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'VENDOR_PROP'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'WEEKLY_SCHEDULED_TASKS'  AND sc.name=N'SBMO_MEIJER_RPT'  AND type in (N'SN'))
 DROP SYNONYM SBMO_MEIJER_RPT.WEEKLY_SCHEDULED_TASKS
GO
CREATE SYNONYM SBMO_MEIJER_RPT.WEEKLY_SCHEDULED_TASKS FOR SBMO_MEIJER.WEEKLY_SCHEDULED_TASKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty
        N'MS_SSMA_SOURCE', N'SBMO_MEIJER_RPT.WEEKLY_SCHEDULED_TASKS',
        N'SCHEMA', N'SBMO_MEIJER_RPT',
        N'SYNONYM', N'WEEKLY_SCHEDULED_TASKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO
