
  CREATE TABLE "SBMO"."PARTITION_TABLE_LIST" 
   (	"TABLE_RANK" NUMBER, 
	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "TABLE_LIST_C1" CHECK (table_name = upper(TABLE_NAME)
    ) ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 