
  CREATE TABLE "SBMO"."PDX_SCHEMA_UPD_PKGCALL_ERR_LOG" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(200), 
	"SQL_ERROR_CODE" VARCHAR2(20), 
	"SQL_ERROR_MESSAGE" VARCHAR2(4000), 
	 CONSTRAINT "PDX_SCHEMA_UPD_PKGCALL_ELOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PDX_SCHEMA_UPD_PKGCALL_ELG_FK1" FOREIGN KEY ("ID")
	  REFERENCES "SBMO"."PDX_SCHEMA_UPD_PKGCALL_HIST" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 