
  CREATE TABLE "SBMO"."QRTZ_PAUSED_TRIGGER_GRPS" 
   (	"TRIGGER_GROUP" VARCHAR2(80) NOT NULL ENABLE, 
	"SCHED_NAME" VARCHAR2(120) DEFAULT 'TestScheduler' NOT NULL ENABLE, 
	 CONSTRAINT "QRTZ_PAUSED_TRIGGER_GRPS_PK" PRIMARY KEY ("SCHED_NAME", "TRIGGER_GROUP") ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION DEFERRED 
  ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 
 PCTTHRESHOLD 50