
  CREATE TABLE "SBMO"."DRUGS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"DECIMAL_PACK" FLOAT(126) NOT NULL ENABLE, 
	"GENERIC_FULL_NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"DRUG_FULL_NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"GENERIC_NAME" VARCHAR2(28 CHAR) NOT NULL ENABLE, 
	"GPI" VARCHAR2(14 CHAR), 
	"INJECT" NUMBER(1,0) NOT NULL ENABLE, 
	"DRUG_NOTE" VARCHAR2(255 CHAR), 
	"MFG" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(28 CHAR) NOT NULL ENABLE, 
	"NDC" VARCHAR2(11 CHAR) NOT NULL ENABLE, 
	"PACK" NUMBER(19,0) NOT NULL ENABLE, 
	"PREVIOUS_NDC" VARCHAR2(11 CHAR), 
	"REPLACEMENT_NDC" VARCHAR2(11 CHAR), 
	"SCHEDULE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"STRENGTH" VARCHAR2(8 CHAR), 
	"TRIPLIC" NUMBER(1,0) NOT NULL ENABLE, 
	"UNIT" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"MFG_DISCONTINUE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"SIGNATURE_REQUIRED" NUMBER(1,0) NOT NULL ENABLE, 
	"AWP" FLOAT(126) NOT NULL ENABLE, 
	"AWP_LAST_UPDATED" TIMESTAMP (6) NOT NULL ENABLE, 
	"BARCODE" VARCHAR2(16 CHAR), 
	"NDCFMT" NUMBER(10,0), 
	"PACKAGE_QTY" FLOAT(126), 
	"IND_PACK" FLOAT(126), 
	"MULTI_SOURCE" VARCHAR2(1), 
	"DDID" NUMBER(10,0), 
	"NARCOTIC_INDICATOR" VARCHAR2(2), 
	"DEEP_FROZEN" NUMBER(1,0) NOT NULL ENABLE, 
	"BIN_STORAGE_TYPE" NUMBER(1,0), 
	"HAZARDOUS_DRUG" VARCHAR2(1), 
	"INNER_PACK_INDICATOR" VARCHAR2(1), 
	 CONSTRAINT "DRUGS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 CONSTRAINT "DRUGS_UQ_NDC" UNIQUE ("NDC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 