
  CREATE TABLE "SBMO"."PDX_SCHEMA_TASKVER_META" 
   (	"TASK_VERSION" VARCHAR2(255) NOT NULL ENABLE, 
	"TASK_SOURCE" VARCHAR2(1) NOT NULL ENABLE, 
	"META_TAG" VARCHAR2(20) NOT NULL ENABLE, 
	"TASK_VERSION_VALUE" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "PDX_SCHEMA_TASKVER_META_PK" PRIMARY KEY ("TASK_VERSION", "TASK_SOURCE", "META_TAG", "TASK_VERSION_VALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 