
  CREATE TABLE "SBMO"."PDX_SCHEMA_VERSION_ERROR_LOG" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(200), 
	"SQL_ERROR_CODE" VARCHAR2(20), 
	"SQL_ERROR_MESSAGE" VARCHAR2(4000), 
	 CONSTRAINT "PDX_SCHEMA_VERSION_ERR_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PDX_SCHEMA_VERSION_ERR_LOG_FK1" FOREIGN KEY ("ID")
	  REFERENCES "SBMO"."PDX_SCHEMA_VERSION_HISTORY" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SBMO_MULTITENANT_D" 