
  CREATE TABLE "SBMO"."QRTZ_SIMPROP_TRIGGERS" 
   (	"SCHED_NAME" VARCHAR2(120) NOT NULL ENABLE, 
	"TRIGGER_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"TRIGGER_GROUP" VARCHAR2(200) NOT NULL ENABLE, 
	"STR_PROP_1" VARCHAR2(512), 
	"STR_PROP_2" VARCHAR2(512), 
	"STR_PROP_3" VARCHAR2(512), 
	"INT_PROP_1" NUMBER, 
	"INT_PROP_2" NUMBER, 
	"LONG_PROP_1" NUMBER, 
	"LONG_PROP_2" NUMBER, 
	"DEC_PROP_1" NUMBER(13,4), 
	"DEC_PROP_2" NUMBER(13,4), 
	"BOOL_PROP_1" VARCHAR2(1), 
	"BOOL_PROP_2" VARCHAR2(1), 
	 CONSTRAINT "QRTZ_SIMPROP_TRIGGERS_PK" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "QRTZ_SIMPROP_TRIGGERS_FK1" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
	  REFERENCES "SBMO"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SBMO_MULTITENANT_D" 