
  CREATE TABLE "SBMO"."DASHBOARD_STATISTICS" 
   (	"TENANT_ID" NUMBER(38,0), 
	"FACILITY_ID" NUMBER(38,0), 
	"ID" NUMBER(38,0), 
	"PEND_STORE" NUMBER(22,0) NOT NULL ENABLE, 
	"PEND_STORE_OUTSTANDING" NUMBER(22,0) NOT NULL ENABLE, 
	"PEND_MAIL" NUMBER(22,0) NOT NULL ENABLE, 
	"PEND_MAIL_OUTSTANDING" NUMBER(22,0) NOT NULL ENABLE, 
	"PEND_SPECIALTY" NUMBER(22,0) NOT NULL ENABLE, 
	"PEND_SPECIALTY_OUTSTANDING" NUMBER(22,0) NOT NULL ENABLE, 
	"PEND_PROMISED_DATE" NUMBER(22,0) NOT NULL ENABLE, 
	"PEND_PROMISED_DATE_OUTSTANDING" NUMBER(22,0) NOT NULL ENABLE, 
	"PEND_INADEQ_INVENT" NUMBER(22,0) NOT NULL ENABLE, 
	"PEND_INADEQ_INVENT_OUTSTANDING" NUMBER(22,0) NOT NULL ENABLE, 
	"QUEUED" NUMBER(22,0) NOT NULL ENABLE, 
	"QUEUED_OUTSTANDING" NUMBER(22,0) NOT NULL ENABLE, 
	"ERROR_TO_DISPENSE" NUMBER(22,0) NOT NULL ENABLE, 
	"ERROR_TO_DISPENSE_OUTSTANDING" NUMBER(22,0) NOT NULL ENABLE, 
	"SENT_TO_DISPENSER" NUMBER(22,0) NOT NULL ENABLE, 
	"CANCELLED_BY_DISPENSER" NUMBER(22,0) NOT NULL ENABLE, 
	"PROCESSED" NUMBER(22,0) NOT NULL ENABLE, 
	"REJECTED_INADEQUATE_INVENTORY" NUMBER(22,0) NOT NULL ENABLE, 
	"CANCELLED_BY_FACILITY" NUMBER(22,0) NOT NULL ENABLE, 
	"CANCELLED_BY_PHARMACY" NUMBER(22,0) NOT NULL ENABLE, 
	"NON_FORMULARY" NUMBER(22,0) NOT NULL ENABLE, 
	"DUPLICATE" NUMBER(22,0) NOT NULL ENABLE, 
	"LAST_UPDATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "DASHBOARD_STATISTICS_PK" PRIMARY KEY ("TENANT_ID", "FACILITY_ID", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
 (PARTITION "RXCOM" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "MEIJER" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "FRUTH" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "COSTCO" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "GIANTEAGLE" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "SAFEWAY" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "AVELLA" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "MOBIMEDS" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "GUNDERSEN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "MEDICALCENTER" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "CUBPHARMACY" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "WEISSBMO" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "OTHER" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" )  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "DASHBOARD_STATISTICS_FK1" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "SBMO"."TENANTS" ("ID") ENABLE, 
	 CONSTRAINT "DASHBOARD_STATISTICS_FK2" FOREIGN KEY ("TENANT_ID", "FACILITY_ID")
	  REFERENCES "SBMO"."FACILITIES" ("TENANT_ID", "ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 
  PARTITION BY LIST ("TENANT_ID") 
 (PARTITION "RXCOM"  VALUES (1) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "MEIJER"  VALUES (3) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "FRUTH"  VALUES (5) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "COSTCO"  VALUES (6) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "GIANTEAGLE"  VALUES (7) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "SAFEWAY"  VALUES (8) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "AVELLA"  VALUES (9) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "MOBIMEDS"  VALUES (10) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "GUNDERSEN"  VALUES (11) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "MEDICALCENTER"  VALUES (12) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "CUBPHARMACY"  VALUES (13) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "WEISSBMO"  VALUES (14) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" , 
 PARTITION "OTHER"  VALUES (DEFAULT) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" ) 