
  CREATE TABLE "SBMO"."USER_AUDIT_LOG" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACTION" NUMBER(10,0) NOT NULL ENABLE, 
	"TIME_STAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(255 CHAR), 
	"CREATED_DATE" TIMESTAMP (6), 
	 CONSTRAINT "USER_AUDIT_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 