
  CREATE TABLE "SBMO"."CR18985_LOG" 
   (	"OWNER" VARCHAR2(35), 
	"TABLE_NAME" VARCHAR2(35), 
	"OBJECT_NAME" VARCHAR2(35), 
	"OBJECT_TYPE" VARCHAR2(35), 
	"ERROR_CODE" VARCHAR2(35), 
	"ERROR_MSG" VARCHAR2(210), 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SBMO_MULTITENANT_D" 