
  CREATE TABLE "SBMO"."PURGE_HISTORY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"PURGE_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE, 
	"TOT_ELAPSED_SECS" NUMBER, 
	"TOT_INDEX_SECS" NUMBER, 
	"TOT_NBR_CHUNKS" NUMBER, 
	"NBR_ROWS_PURGED" NUMBER, 
	"NBR_ROWS_DELETED_FK" NUMBER, 
	"TOT_ELAPSED_FK_SECS" NUMBER, 
	"NBR_SUBPARTS_DROPPED" NUMBER, 
	"TOT_ELAPSED_DROP_SECS" NUMBER, 
	"STATUS" VARCHAR2(100) NOT NULL ENABLE, 
	"INDEX_SQL" VARCHAR2(4000), 
	 CONSTRAINT "PURGE_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS, 
	 CONSTRAINT "PURGE_HISTORY_FK1" FOREIGN KEY ("TABLE_NAME")
	  REFERENCES "SBMO"."PURGE_TABLES" ("TABLE_NAME") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 