
  CREATE TABLE "SBMO"."PRESTATS_ORDERS" 
   (	"STATID" VARCHAR2(128), 
	"TYPE" CHAR(1), 
	"VERSION" NUMBER, 
	"FLAGS" NUMBER, 
	"C1" VARCHAR2(128), 
	"C2" VARCHAR2(128), 
	"C3" VARCHAR2(128), 
	"C4" VARCHAR2(128), 
	"C5" VARCHAR2(128), 
	"C6" VARCHAR2(128), 
	"N1" NUMBER, 
	"N2" NUMBER, 
	"N3" NUMBER, 
	"N4" NUMBER, 
	"N5" NUMBER, 
	"N6" NUMBER, 
	"N7" NUMBER, 
	"N8" NUMBER, 
	"N9" NUMBER, 
	"N10" NUMBER, 
	"N11" NUMBER, 
	"N12" NUMBER, 
	"N13" NUMBER, 
	"D1" DATE, 
	"T1" TIMESTAMP (6) WITH TIME ZONE, 
	"R1" RAW(1000), 
	"R2" RAW(1000), 
	"R3" RAW(1000), 
	"CH1" VARCHAR2(1000), 
	"CL1" CLOB, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SBMO_MULTITENANT_D" 
 LOB ("CL1") STORE AS SECUREFILE (
  TABLESPACE "SBMO_MULTITENANT_D" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 