
  CREATE TABLE "SBMO"."PDX_SCHEMA_PRIV_DEFAULT" 
   (	"OBJECT_TYPE" VARCHAR2(19) NOT NULL ENABLE, 
	"PRIVILEGE" VARCHAR2(40) NOT NULL ENABLE, 
	"GRANTEE" VARCHAR2(30) NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(1), 
	 CONSTRAINT "PDX_SCHEMA_PRIV_DEFAULT_PK" PRIMARY KEY ("GRANTEE", "OBJECT_TYPE", "PRIVILEGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SBMO_MULTITENANT_D"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SBMO_MULTITENANT_D" 