
  CREATE TABLE "SBMO"."RX_HOURS_OF_ADMINISTRATION" 
   (	"ID" NUMBER(38,0), 
	"TENANT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RX_CORES_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ALL_DAYS_SAME" VARCHAR2(1), 
	"ALL_DAYS_START_DATE" TIMESTAMP (6), 
	"ALL_DAYS_END_DATE" TIMESTAMP (6), 
	 CONSTRAINT "RX_HOURS_OF_ADMINISTRATION_PK" PRIMARY KEY ("TENANT_ID", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_X"  ENABLE, 
	 CONSTRAINT "RX_HOURS_OF_ADMINISTRATION_FK1" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "SBMO"."TENANTS" ("ID") ENABLE, 
	 CONSTRAINT "RX_HOURS_OF_ADMINISTRATION_FK2" FOREIGN KEY ("TENANT_ID", "RX_CORES_ID")
	  REFERENCES "SBMO"."RX_CORES" ("TENANT_ID", "ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 
  CREATE INDEX "SBMO"."RX_HOURS_OF_ADMINISTRATION_IX2" ON "SBMO"."RX_HOURS_OF_ADMINISTRATION" ("TENANT_ID", "RX_CORES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_X" 
ALTER TABLE "SBMO"."RX_HOURS_OF_ADMINISTRATION" ADD CONSTRAINT "RX_HOURS_OF_ADMINISTRATION_UK1" UNIQUE ("RX_CORES_ID", "TENANT_ID")
  USING INDEX "SBMO"."RX_HOURS_OF_ADMINISTRATION_IX2"  ENABLE