
  CREATE TABLE "SBMO"."ENCRYPTION_KEYS_AUDIT" 
   (	"ID" NUMBER(38,0), 
	"TENANT_ID" NUMBER(38,0), 
	"ENCRYPTION_KEYS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"USER_IDENTIFIER" VARCHAR2(255), 
	"ACTION" NUMBER(1,0) NOT NULL ENABLE, 
	"OLD_VALUE" VARCHAR2(255), 
	"NEW_VALUE" VARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DEACTIVATED_DATE" TIMESTAMP (6), 
	 CONSTRAINT "ENCRYPTION_KEYS_AUDIT_PK" PRIMARY KEY ("TENANT_ID", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_X"  ENABLE, 
	 CONSTRAINT "ENCRYPTION_KEYS_AUDIT_FK1" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "SBMO"."TENANTS" ("ID") ENABLE, 
	 CONSTRAINT "ENCRYPTION_KEYS_AUDIT_FK2" FOREIGN KEY ("TENANT_ID", "ENCRYPTION_KEYS_ID")
	  REFERENCES "SBMO"."ENCRYPTION_KEYS" ("TENANT_ID", "ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBMO_MULTITENANT_D" 