
  CREATE TABLE "SBMO"."MV_FORMULARY" 
   (	"VENDOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NDC" VARCHAR2(11 CHAR) NOT NULL ENABLE, 
	"ITEM_NUMBER" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"ONHAND_QTY" NUMBER(19,0) NOT NULL ENABLE, 
	"ALLOCATED_QTY" NUMBER(19,0) NOT NULL ENABLE, 
	"REFRESH_DATE" DATE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SBMO_MULTITENANT_D" 