-- Generated Azure SQL Synonyms for WL_EPHARMACY
-- Source: Oracle WL_EPHARMACY synonyms
-- Generated: 2026-09-09
-- Total Synonyms: 76

USE noneprdb
GO
 IF NOT EXISTS(SELECT * FROM sys.schemas WHERE [name] = N'WL_EPHARMACY')
     EXEC sp_executesql N'CREATE SCHEMA [WL_EPHARMACY]'
 GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'APP_INFO'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.APP_INFO
GO
CREATE SYNONYM WL_EPHARMACY.APP_INFO FOR noneprdb.EPHARM.APP_INFO
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.APP_INFO', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'APP_INFO'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ATTR_DESC'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.ATTR_DESC
GO
CREATE SYNONYM WL_EPHARMACY.ATTR_DESC FOR noneprdb.EPHARM.ATTR_DESC
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.ATTR_DESC', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'ATTR_DESC'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CHAIN_RULE_GROUP'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.CHAIN_RULE_GROUP
GO
CREATE SYNONYM WL_EPHARMACY.CHAIN_RULE_GROUP FOR noneprdb.EPHARM.CHAIN_RULE_GROUP
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.CHAIN_RULE_GROUP', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'CHAIN_RULE_GROUP'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CREDIT_CARD'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.CREDIT_CARD
GO
CREATE SYNONYM WL_EPHARMACY.CREDIT_CARD FOR noneprdb.EPHARM.CREDIT_CARD
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.CREDIT_CARD', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'CREDIT_CARD'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CREDIT_CARD_DESC'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.CREDIT_CARD_DESC
GO
CREATE SYNONYM WL_EPHARMACY.CREDIT_CARD_DESC FOR noneprdb.EPHARM.CREDIT_CARD_DESC
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.CREDIT_CARD_DESC', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'CREDIT_CARD_DESC'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CUSTOMER'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.CUSTOMER
GO
CREATE SYNONYM WL_EPHARMACY.CUSTOMER FOR noneprdb.EPHARM.CUSTOMER
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.CUSTOMER', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'CUSTOMER'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CUSTOMER_AUDIT'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.CUSTOMER_AUDIT
GO
CREATE SYNONYM WL_EPHARMACY.CUSTOMER_AUDIT FOR noneprdb.EPHARM.CUSTOMER_AUDIT
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.CUSTOMER_AUDIT', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'CUSTOMER_AUDIT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CUSTOMER_ECOMMERCE_SERVICE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.CUSTOMER_ECOMMERCE_SERVICE
GO
CREATE SYNONYM WL_EPHARMACY.CUSTOMER_ECOMMERCE_SERVICE FOR noneprdb.EPHARM.CUSTOMER_ECOMMERCE_SERVICE
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.CUSTOMER_ECOMMERCE_SERVICE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'CUSTOMER_ECOMMERCE_SERVICE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CUSTOMER_EMAIL_SETTINGS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.CUSTOMER_EMAIL_SETTINGS
GO
CREATE SYNONYM WL_EPHARMACY.CUSTOMER_EMAIL_SETTINGS FOR noneprdb.EPHARM.CUSTOMER_EMAIL_SETTINGS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.CUSTOMER_EMAIL_SETTINGS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'CUSTOMER_EMAIL_SETTINGS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CUSTOMER_PIN_BATCH'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.CUSTOMER_PIN_BATCH
GO
CREATE SYNONYM WL_EPHARMACY.CUSTOMER_PIN_BATCH FOR noneprdb.EPHARM.CUSTOMER_PIN_BATCH
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.CUSTOMER_PIN_BATCH', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'CUSTOMER_PIN_BATCH'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'CUSTOMER_REFILL_PRINTING'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.CUSTOMER_REFILL_PRINTING
GO
CREATE SYNONYM WL_EPHARMACY.CUSTOMER_REFILL_PRINTING FOR noneprdb.EPHARM.CUSTOMER_REFILL_PRINTING
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.CUSTOMER_REFILL_PRINTING', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'CUSTOMER_REFILL_PRINTING'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'EVENT_QUESTION_LOG'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.EVENT_QUESTION_LOG
GO
CREATE SYNONYM WL_EPHARMACY.EVENT_QUESTION_LOG FOR noneprdb.EPHARM.EVENT_QUESTION_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.EVENT_QUESTION_LOG', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'EVENT_QUESTION_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'EVENT_RX_BILLING_LOG'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.EVENT_RX_BILLING_LOG
GO
CREATE SYNONYM WL_EPHARMACY.EVENT_RX_BILLING_LOG FOR noneprdb.EPHARM.EVENT_RX_BILLING_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.EVENT_RX_BILLING_LOG', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'EVENT_RX_BILLING_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'FAX_JOB'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.FAX_JOB
GO
CREATE SYNONYM WL_EPHARMACY.FAX_JOB FOR noneprdb.EPHARM.FAX_JOB
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.FAX_JOB', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'FAX_JOB'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'FLOW_ACTION'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.FLOW_ACTION
GO
CREATE SYNONYM WL_EPHARMACY.FLOW_ACTION FOR noneprdb.EPHARM.FLOW_ACTION
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.FLOW_ACTION', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'FLOW_ACTION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'FLOW_ACTION_TYPE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.FLOW_ACTION_TYPE
GO
CREATE SYNONYM WL_EPHARMACY.FLOW_ACTION_TYPE FOR noneprdb.EPHARM.FLOW_ACTION_TYPE
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.FLOW_ACTION_TYPE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'FLOW_ACTION_TYPE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'FLOW_CONTROL'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.FLOW_CONTROL
GO
CREATE SYNONYM WL_EPHARMACY.FLOW_CONTROL FOR noneprdb.EPHARM.FLOW_CONTROL
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.FLOW_CONTROL', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'FLOW_CONTROL'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'ID_GEN'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.ID_GEN
GO
CREATE SYNONYM WL_EPHARMACY.ID_GEN FOR noneprdb.EPHARM.ID_GEN
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.ID_GEN', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'ID_GEN'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MAIL_ORDER_DELIVERY'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.MAIL_ORDER_DELIVERY
GO
CREATE SYNONYM WL_EPHARMACY.MAIL_ORDER_DELIVERY FOR noneprdb.EPHARM.MAIL_ORDER_DELIVERY
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.MAIL_ORDER_DELIVERY', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'MAIL_ORDER_DELIVERY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MAIL_ORDER_DELIVERY_DESC'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.MAIL_ORDER_DELIVERY_DESC
GO
CREATE SYNONYM WL_EPHARMACY.MAIL_ORDER_DELIVERY_DESC FOR noneprdb.EPHARM.MAIL_ORDER_DELIVERY_DESC
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.MAIL_ORDER_DELIVERY_DESC', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'MAIL_ORDER_DELIVERY_DESC'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MASTER_SEQ'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.MASTER_SEQ
GO
CREATE SYNONYM WL_EPHARMACY.MASTER_SEQ FOR noneprdb.EPHARM.MASTER_SEQ
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.MASTER_SEQ', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'MASTER_SEQ'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MEMBER_ACCOUNT'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.MEMBER_ACCOUNT
GO
CREATE SYNONYM WL_EPHARMACY.MEMBER_ACCOUNT FOR noneprdb.EPHARM.MEMBER_ACCOUNT
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.MEMBER_ACCOUNT', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'MEMBER_ACCOUNT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MEMBER_EXTERNAL_LINK'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.MEMBER_EXTERNAL_LINK
GO
CREATE SYNONYM WL_EPHARMACY.MEMBER_EXTERNAL_LINK FOR noneprdb.EPHARM.MEMBER_EXTERNAL_LINK
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.MEMBER_EXTERNAL_LINK', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'MEMBER_EXTERNAL_LINK'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MEMBER_NOTIFY'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.MEMBER_NOTIFY
GO
CREATE SYNONYM WL_EPHARMACY.MEMBER_NOTIFY FOR noneprdb.EPHARM.MEMBER_NOTIFY
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.MEMBER_NOTIFY', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'MEMBER_NOTIFY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MEMBER_PIN_BATCH'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.MEMBER_PIN_BATCH
GO
CREATE SYNONYM WL_EPHARMACY.MEMBER_PIN_BATCH FOR noneprdb.EPHARM.MEMBER_PIN_BATCH
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.MEMBER_PIN_BATCH', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'MEMBER_PIN_BATCH'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MEMBER_PROFILE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.MEMBER_PROFILE
GO
CREATE SYNONYM WL_EPHARMACY.MEMBER_PROFILE FOR noneprdb.EPHARM.MEMBER_PROFILE
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.MEMBER_PROFILE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'MEMBER_PROFILE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MEMBER_RX'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.MEMBER_RX
GO
CREATE SYNONYM WL_EPHARMACY.MEMBER_RX FOR noneprdb.EPHARM.MEMBER_RX
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.MEMBER_RX', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'MEMBER_RX'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'MONITOR_TIMES'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.MONITOR_TIMES
GO
CREATE SYNONYM WL_EPHARMACY.MONITOR_TIMES FOR noneprdb.EPHARM.MONITOR_TIMES
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.MONITOR_TIMES', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'MONITOR_TIMES'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'NOTIFICATIONS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.NOTIFICATIONS
GO
CREATE SYNONYM WL_EPHARMACY.NOTIFICATIONS FOR noneprdb.EPHARM.NOTIFICATIONS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.NOTIFICATIONS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'NOTIFICATIONS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'NOTIFICATION_TYPE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.NOTIFICATION_TYPE
GO
CREATE SYNONYM WL_EPHARMACY.NOTIFICATION_TYPE FOR noneprdb.EPHARM.NOTIFICATION_TYPE
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.NOTIFICATION_TYPE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'NOTIFICATION_TYPE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'OPEN_CLOSE_TIME'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.OPEN_CLOSE_TIME
GO
CREATE SYNONYM WL_EPHARMACY.OPEN_CLOSE_TIME FOR noneprdb.EPHARM.OPEN_CLOSE_TIME
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.OPEN_CLOSE_TIME', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'OPEN_CLOSE_TIME'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PARENT_CHILD'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PARENT_CHILD
GO
CREATE SYNONYM WL_EPHARMACY.PARENT_CHILD FOR noneprdb.EPHARM.PARENT_CHILD
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PARENT_CHILD', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PARENT_CHILD'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_CONFIG'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_CONFIG
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_CONFIG FOR noneprdb.EPHARM.PDX_SCHEMA_CONFIG
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_CONFIG', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_CONFIG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_MAPPING'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_MAPPING
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_MAPPING FOR noneprdb.EPHARM.PDX_SCHEMA_MAPPING
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_MAPPING', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_MAPPING'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_PRIV_DEFAULT'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_PRIV_DEFAULT
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_PRIV_DEFAULT FOR noneprdb.EPHARM.PDX_SCHEMA_PRIV_DEFAULT
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_PRIV_DEFAULT', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_PRIV_DEFAULT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_PRIV_EXCEPTION'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_PRIV_EXCEPTION
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_PRIV_EXCEPTION FOR noneprdb.EPHARM.PDX_SCHEMA_PRIV_EXCEPTION
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_PRIV_EXCEPTION', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_PRIV_EXCEPTION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_PROCESS_HISTORY'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_PROCESS_HISTORY
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_PROCESS_HISTORY FOR noneprdb.EPHARM.PDX_SCHEMA_PROCESS_HISTORY
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_PROCESS_HISTORY', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_PROCESS_HISTORY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_TASK_ERROR_LOG'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_TASK_ERROR_LOG
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_TASK_ERROR_LOG FOR noneprdb.EPHARM.PDX_SCHEMA_TASK_ERROR_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_TASK_ERROR_LOG', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_TASK_ERROR_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_TASK_HISTORY'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_TASK_HISTORY
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_TASK_HISTORY FOR noneprdb.EPHARM.PDX_SCHEMA_TASK_HISTORY
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_TASK_HISTORY', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_TASK_HISTORY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_UPDATER_MANIFEST'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPDATER_MANIFEST
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPDATER_MANIFEST FOR noneprdb.EPHARM.PDX_SCHEMA_UPDATER_MANIFEST
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_UPDATER_MANIFEST', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_UPDATER_MANIFEST'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_UPDATER_SQL'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPDATER_SQL
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPDATER_SQL FOR noneprdb.EPHARM.PDX_SCHEMA_UPDATER_SQL
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_UPDATER_SQL', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_UPDATER_SQL'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_UPD_PKGCALL_ERR_LOG'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG FOR noneprdb.EPHARM.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_UPD_PKGCALL_ERR_LOG', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_UPD_PKGCALL_ERR_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_UPD_PKGCALL_HIST'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPD_PKGCALL_HIST
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_UPD_PKGCALL_HIST FOR noneprdb.EPHARM.PDX_SCHEMA_UPD_PKGCALL_HIST
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_UPD_PKGCALL_HIST', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_UPD_PKGCALL_HIST'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_VERSION_ERROR_LOG'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_VERSION_ERROR_LOG
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_VERSION_ERROR_LOG FOR noneprdb.EPHARM.PDX_SCHEMA_VERSION_ERROR_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_VERSION_ERROR_LOG', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_VERSION_ERROR_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PDX_SCHEMA_VERSION_HISTORY'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PDX_SCHEMA_VERSION_HISTORY
GO
CREATE SYNONYM WL_EPHARMACY.PDX_SCHEMA_VERSION_HISTORY FOR noneprdb.EPHARM.PDX_SCHEMA_VERSION_HISTORY
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PDX_SCHEMA_VERSION_HISTORY', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PDX_SCHEMA_VERSION_HISTORY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PIN_BATCH_LOG'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PIN_BATCH_LOG
GO
CREATE SYNONYM WL_EPHARMACY.PIN_BATCH_LOG FOR noneprdb.EPHARM.PIN_BATCH_LOG
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PIN_BATCH_LOG', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PIN_BATCH_LOG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PKG_PDX_SCHEMA_UPDATER'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PKG_PDX_SCHEMA_UPDATER
GO
CREATE SYNONYM WL_EPHARMACY.PKG_PDX_SCHEMA_UPDATER FOR noneprdb.EPHARM.PKG_PDX_SCHEMA_UPDATER
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PKG_PDX_SCHEMA_UPDATER', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PKG_PDX_SCHEMA_UPDATER'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'PKG_PDX_SCHEMA_UPDATER_RPT'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.PKG_PDX_SCHEMA_UPDATER_RPT
GO
CREATE SYNONYM WL_EPHARMACY.PKG_PDX_SCHEMA_UPDATER_RPT FOR noneprdb.EPHARM.PKG_PDX_SCHEMA_UPDATER_RPT
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.PKG_PDX_SCHEMA_UPDATER_RPT', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'PKG_PDX_SCHEMA_UPDATER_RPT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_BLOB_TRIGGERS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.QRTZ_BLOB_TRIGGERS
GO
CREATE SYNONYM WL_EPHARMACY.QRTZ_BLOB_TRIGGERS FOR noneprdb.EPHARM.QRTZ_BLOB_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.QRTZ_BLOB_TRIGGERS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'QRTZ_BLOB_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_CALENDARS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.QRTZ_CALENDARS
GO
CREATE SYNONYM WL_EPHARMACY.QRTZ_CALENDARS FOR noneprdb.EPHARM.QRTZ_CALENDARS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.QRTZ_CALENDARS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'QRTZ_CALENDARS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_CRON_TRIGGERS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.QRTZ_CRON_TRIGGERS
GO
CREATE SYNONYM WL_EPHARMACY.QRTZ_CRON_TRIGGERS FOR noneprdb.EPHARM.QRTZ_CRON_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.QRTZ_CRON_TRIGGERS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'QRTZ_CRON_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_FIRED_TRIGGERS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.QRTZ_FIRED_TRIGGERS
GO
CREATE SYNONYM WL_EPHARMACY.QRTZ_FIRED_TRIGGERS FOR noneprdb.EPHARM.QRTZ_FIRED_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.QRTZ_FIRED_TRIGGERS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'QRTZ_FIRED_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_JOB_DETAILS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.QRTZ_JOB_DETAILS
GO
CREATE SYNONYM WL_EPHARMACY.QRTZ_JOB_DETAILS FOR noneprdb.EPHARM.QRTZ_JOB_DETAILS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.QRTZ_JOB_DETAILS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'QRTZ_JOB_DETAILS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_LOCKS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.QRTZ_LOCKS
GO
CREATE SYNONYM WL_EPHARMACY.QRTZ_LOCKS FOR noneprdb.EPHARM.QRTZ_LOCKS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.QRTZ_LOCKS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'QRTZ_LOCKS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_PAUSED_TRIGGER_GRPS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.QRTZ_PAUSED_TRIGGER_GRPS
GO
CREATE SYNONYM WL_EPHARMACY.QRTZ_PAUSED_TRIGGER_GRPS FOR noneprdb.EPHARM.QRTZ_PAUSED_TRIGGER_GRPS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.QRTZ_PAUSED_TRIGGER_GRPS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'QRTZ_PAUSED_TRIGGER_GRPS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_SCHEDULER_STATE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.QRTZ_SCHEDULER_STATE
GO
CREATE SYNONYM WL_EPHARMACY.QRTZ_SCHEDULER_STATE FOR noneprdb.EPHARM.QRTZ_SCHEDULER_STATE
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.QRTZ_SCHEDULER_STATE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'QRTZ_SCHEDULER_STATE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_SIMPLE_TRIGGERS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.QRTZ_SIMPLE_TRIGGERS
GO
CREATE SYNONYM WL_EPHARMACY.QRTZ_SIMPLE_TRIGGERS FOR noneprdb.EPHARM.QRTZ_SIMPLE_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.QRTZ_SIMPLE_TRIGGERS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'QRTZ_SIMPLE_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_SIMPROP_TRIGGERS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.QRTZ_SIMPROP_TRIGGERS
GO
CREATE SYNONYM WL_EPHARMACY.QRTZ_SIMPROP_TRIGGERS FOR noneprdb.EPHARM.QRTZ_SIMPROP_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.QRTZ_SIMPROP_TRIGGERS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'QRTZ_SIMPROP_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'QRTZ_TRIGGERS'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.QRTZ_TRIGGERS
GO
CREATE SYNONYM WL_EPHARMACY.QRTZ_TRIGGERS FOR noneprdb.EPHARM.QRTZ_TRIGGERS
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.QRTZ_TRIGGERS', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'QRTZ_TRIGGERS'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SCHEMA_UPDATER_MANIFEST'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.SCHEMA_UPDATER_MANIFEST
GO
CREATE SYNONYM WL_EPHARMACY.SCHEMA_UPDATER_MANIFEST FOR noneprdb.EPHARM.SCHEMA_UPDATER_MANIFEST
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.SCHEMA_UPDATER_MANIFEST', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'SCHEMA_UPDATER_MANIFEST'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SCHEMA_UPDATER_SQL'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.SCHEMA_UPDATER_SQL
GO
CREATE SYNONYM WL_EPHARMACY.SCHEMA_UPDATER_SQL FOR noneprdb.EPHARM.SCHEMA_UPDATER_SQL
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.SCHEMA_UPDATER_SQL', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'SCHEMA_UPDATER_SQL'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SERVICE_MODIFY'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.SERVICE_MODIFY
GO
CREATE SYNONYM WL_EPHARMACY.SERVICE_MODIFY FOR noneprdb.EPHARM.SERVICE_MODIFY
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.SERVICE_MODIFY', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'SERVICE_MODIFY'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SHR_DAY_OF_WEEK'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.SHR_DAY_OF_WEEK
GO
CREATE SYNONYM WL_EPHARMACY.SHR_DAY_OF_WEEK FOR noneprdb.EPHARM.SHR_DAY_OF_WEEK
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.SHR_DAY_OF_WEEK', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'SHR_DAY_OF_WEEK'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SHR_GROUP'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.SHR_GROUP
GO
CREATE SYNONYM WL_EPHARMACY.SHR_GROUP FOR noneprdb.EPHARM.SHR_GROUP
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.SHR_GROUP', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'SHR_GROUP'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SHR_NTH_WEEKDAY_OF_MONTH'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.SHR_NTH_WEEKDAY_OF_MONTH
GO
CREATE SYNONYM WL_EPHARMACY.SHR_NTH_WEEKDAY_OF_MONTH FOR noneprdb.EPHARM.SHR_NTH_WEEKDAY_OF_MONTH
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.SHR_NTH_WEEKDAY_OF_MONTH', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'SHR_NTH_WEEKDAY_OF_MONTH'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SHR_SPECIFIC_DATE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.SHR_SPECIFIC_DATE
GO
CREATE SYNONYM WL_EPHARMACY.SHR_SPECIFIC_DATE FOR noneprdb.EPHARM.SHR_SPECIFIC_DATE
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.SHR_SPECIFIC_DATE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'SHR_SPECIFIC_DATE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STATE_MAJORITY_AGE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.STATE_MAJORITY_AGE
GO
CREATE SYNONYM WL_EPHARMACY.STATE_MAJORITY_AGE FOR noneprdb.EPHARM.STATE_MAJORITY_AGE
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.STATE_MAJORITY_AGE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'STATE_MAJORITY_AGE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM [WL_EPHARMACY].[STORE]
GO
CREATE SYNONYM [WL_EPHARMACY].[STORE] FOR noneprdb.EPHARM.[STORE]
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.STORE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'STORE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORE_ATTR'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.STORE_ATTR
GO
CREATE SYNONYM WL_EPHARMACY.STORE_ATTR FOR noneprdb.EPHARM.STORE_ATTR
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.STORE_ATTR', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'STORE_ATTR'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORE_AUDIT'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.STORE_AUDIT
GO
CREATE SYNONYM WL_EPHARMACY.STORE_AUDIT FOR noneprdb.EPHARM.STORE_AUDIT
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.STORE_AUDIT', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'STORE_AUDIT'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORE_ECOMMERCE_SERVICE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.STORE_ECOMMERCE_SERVICE
GO
CREATE SYNONYM WL_EPHARMACY.STORE_ECOMMERCE_SERVICE FOR noneprdb.EPHARM.STORE_ECOMMERCE_SERVICE
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.STORE_ECOMMERCE_SERVICE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'STORE_ECOMMERCE_SERVICE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORE_HOUR_RULE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.STORE_HOUR_RULE
GO
CREATE SYNONYM WL_EPHARMACY.STORE_HOUR_RULE FOR noneprdb.EPHARM.STORE_HOUR_RULE
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.STORE_HOUR_RULE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'STORE_HOUR_RULE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'STORE_VERSION'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.STORE_VERSION
GO
CREATE SYNONYM WL_EPHARMACY.STORE_VERSION FOR noneprdb.EPHARM.STORE_VERSION
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.STORE_VERSION', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'STORE_VERSION'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'SYS_MSG'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.SYS_MSG
GO
CREATE SYNONYM WL_EPHARMACY.SYS_MSG FOR noneprdb.EPHARM.SYS_MSG
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.SYS_MSG', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'SYS_MSG'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'TERMS_OF_USE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.TERMS_OF_USE
GO
CREATE SYNONYM WL_EPHARMACY.TERMS_OF_USE FOR noneprdb.EPHARM.TERMS_OF_USE
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.TERMS_OF_USE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'TERMS_OF_USE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

USE noneprdb
GO
IF  EXISTS (SELECT * FROM sys.objects so JOIN sys.schemas sc ON so.schema_id = sc.schema_id WHERE so.name = N'USAGE'  AND sc.name=N'WL_EPHARMACY'  AND type in (N'SN'))
 DROP SYNONYM WL_EPHARMACY.USAGE
GO
CREATE SYNONYM WL_EPHARMACY.USAGE FOR noneprdb.EPHARM.USAGE
GO
BEGIN TRY
    EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'WL_EPHARMACY.USAGE', N'SCHEMA', N'WL_EPHARMACY', N'SYNONYM', N'USAGE'
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0) ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
GO

