CREATE OR REPLACE VIEW SBMO_MEIJER.ADDRESSES (TENANT_ID, ID, ADDRESS, ADDRESS_LINE_2, CITY, STATE, ZIP, OWNER_ID, IDX, COUNTRY, LAST_UPDATED_DATE, LAST_UPDATED_USER_ID) AS
select "TENANT_ID","ID","ADDRESS","ADDRESS_LINE_2","CITY","STATE","ZIP","OWNER_ID","IDX","COUNTRY","LAST_UPDATED_DATE","LAST_UPDATED_USER_ID" from SBMO.addresses WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.ADJUSTMENT_CODES (ID, CODE, LAST_UPDATED_DATE, DEACTIVATED_DATE, DESCRIPTION, CREATED_DATE, CHANGE_ON_HAND) AS
select "ID","CODE","LAST_UPDATED_DATE","DEACTIVATED_DATE","DESCRIPTION","CREATED_DATE","CHANGE_ON_HAND" from SBMO.ADJUSTMENT_CODES 
/
CREATE OR REPLACE VIEW SBMO_MEIJER.ADJUSTMENT_GROUP (TENANT_ID, ID, APPLIED_DATE, CREATED_DATE, INVENTORY_ID, WS_CLIENT_CERT_IDENTIFIER) AS
select "TENANT_ID","ID","APPLIED_DATE","CREATED_DATE","INVENTORY_ID","WS_CLIENT_CERT_IDENTIFIER" from SBMO.ADJUSTMENT_GROUP where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.AUDIT_LOG (TENANT_ID, ID, ACTION, NEW_VALUE, OBJECT_NAME, OBJECT_ID, OLD_VALUE, PROPERTY, TIME_STAMP, USER_ID, CREATED_DATE, FACILITY_ID) AS
select "TENANT_ID","ID","ACTION","NEW_VALUE","OBJECT_NAME","OBJECT_ID","OLD_VALUE","PROPERTY","TIME_STAMP","USER_ID","CREATED_DATE","FACILITY_ID" from SBMO.AUDIT_LOG where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.BIN_UPC_LINK (TENANT_ID, ID, BIN_BARCODE, DRUG_UPC, DEVICE_NUMBER, DRUG_NAME, NDC, NDC_FMT) AS
select "TENANT_ID","ID","BIN_BARCODE","DRUG_UPC","DEVICE_NUMBER","DRUG_NAME","NDC","NDC_FMT" from SBMO.BIN_UPC_LINK where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.CARRIER (TENANT_ID, ID, "NAME", SHIP_IDENT, SHIP_PRIORITY) AS
select "TENANT_ID","ID","NAME","SHIP_IDENT","SHIP_PRIORITY" from SBMO.CARRIER where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.CF_SEC_CHAIN (TENANT_ID, ID, LAST_UPDATED_DATE, CHAIN_PASSWORD) AS
select "TENANT_ID","ID","LAST_UPDATED_DATE","CHAIN_PASSWORD" from SBMO.CF_SEC_CHAIN where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.CF_SEC_STORE (TENANT_ID, ID, LOAD_DATE, PASS_PHRASE, PRIVATE_KEY, REGISTRATION_DATE, SSL_CERTIFICATE, CHAIN_ID, REG_STATUS) AS
select "TENANT_ID","ID","LOAD_DATE","PASS_PHRASE","PRIVATE_KEY","REGISTRATION_DATE","SSL_CERTIFICATE","CHAIN_ID","REG_STATUS" from SBMO.CF_SEC_STORE where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.CHAINS (TENANT_ID, ID, NHINID, "NAME", CHAIN_MARK_UP_PERCENT, CHAIN_DISCOUNT_PERCENT, PARENT_ID, HQ_ID, MINIMUM_PRICE_OVERRIDE, LABEL_TEMPLATE, SHIPPING_ADD_ON_TYPE, SHIPPING_ADD_ON_AMOUNT, USE_ADHERIS, ADHERIS_URL, ADHERIS_TIMEOUT, ADHERIS_VERSION, DEACTIVATED_DATE, ADHERIS_RETRY_COUNT, ADHERIS_RETRY_OPTION) AS
select "TENANT_ID","ID","NHINID","NAME","CHAIN_MARK_UP_PERCENT","CHAIN_DISCOUNT_PERCENT","PARENT_ID","HQ_ID","MINIMUM_PRICE_OVERRIDE","LABEL_TEMPLATE","SHIPPING_ADD_ON_TYPE","SHIPPING_ADD_ON_AMOUNT","USE_ADHERIS","ADHERIS_URL","ADHERIS_TIMEOUT","ADHERIS_VERSION","DEACTIVATED_DATE","ADHERIS_RETRY_COUNT","ADHERIS_RETRY_OPTION" from SBMO.CHAINS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.CHARGE_PAYMENT_INFO (TENANT_ID, ID, ORDER_ID, CHARGE_TYPE, CHARGE_IDENT, CHARGE_AMOUNT, CREATED_DATE) AS
select "TENANT_ID","ID","ORDER_ID","CHARGE_TYPE","CHARGE_IDENT","CHARGE_AMOUNT","CREATED_DATE" from SBMO.CHARGE_PAYMENT_INFO where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.CONTACTS (TENANT_ID, ID, FIRST_NAME, LAST_NAME, TITLE, ENTITY_ID, IDX) AS
select "TENANT_ID","ID","FIRST_NAME","LAST_NAME","TITLE","ENTITY_ID","IDX" from SBMO.CONTACTS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.CUSTOM_SCHEDULED_TASK (TENANT_ID, ID, TASK_TYPE, TASK_DAY, TRIGGER_TIME, SCHEDULE_GROUPING, FACILITY_ID) AS
select "TENANT_ID","ID","TASK_TYPE","TASK_DAY","TRIGGER_TIME","SCHEDULE_GROUPING","FACILITY_ID" from SBMO.CUSTOM_SCHEDULED_TASK where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.DAILY_SCHEDULED_TASKS (TENANT_ID, ID, FACILITY_ID) AS
select "TENANT_ID","ID","FACILITY_ID" from SBMO.DAILY_SCHEDULED_TASKS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.DISPENSER_LOCATION (TENANT_ID, ID, DISPENSER_ID, LOCATION_ID, CELLID, STATIONID) AS
select "TENANT_ID","ID","DISPENSER_ID","LOCATION_ID","CELLID","STATIONID" from SBMO.DISPENSER_LOCATION where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.DISPENSERS (TENANT_ID, ID, WARNING_LABEL_CODE, LOAD_BALANCE_FACTOR, MODULE, PORT, TIMEOUT, HOST, VERSION, DISABLED, INVENTORY_ID, TRANSPORT_PROPERTIES, USES_BATCH_IDENTIFIER, DESCRIPTION, FACILITY_ID, DISPENSER_CERT_SUBJECT, ORDER_PULL_RETRY_COUNT, LOG_DISPENSER_REQUEST, LAST_UPDATED_DATE, LAST_UPDATED_USER_ID) AS
select "TENANT_ID","ID","WARNING_LABEL_CODE","LOAD_BALANCE_FACTOR","MODULE","PORT","TIMEOUT","HOST","VERSION","DISABLED","INVENTORY_ID","TRANSPORT_PROPERTIES","USES_BATCH_IDENTIFIER","DESCRIPTION","FACILITY_ID","DISPENSER_CERT_SUBJECT","ORDER_PULL_RETRY_COUNT","LOG_DISPENSER_REQUEST","LAST_UPDATED_DATE","LAST_UPDATED_USER_ID" from SBMO.DISPENSERS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.DRUG_ORDER_PRODUCT_VERIFY (TENANT_ID, ID, DRUG_ORDERS_ID, MASTER_PRODUCT_PO_VERIFY_ID, ITEM_PASSED, NDC, GTIN, EXPIRATION_DATE, SERIAL_NUMBER, LOT_NUMBER, NOTES, DATE_SCANNED, BAR_LINE, SCANNED_BY_USER, CREATED_DATE) AS
select "TENANT_ID","ID","DRUG_ORDERS_ID","MASTER_PRODUCT_PO_VERIFY_ID","ITEM_PASSED","NDC","GTIN","EXPIRATION_DATE","SERIAL_NUMBER","LOT_NUMBER","NOTES","DATE_SCANNED","BAR_LINE","SCANNED_BY_USER","CREATED_DATE" from SBMO.drug_order_product_verify WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.DRUG_ORDERS (TENANT_ID, ID, PARTITION_STAMP, NDC, ACK_RECEIVED_QTY, PACK, COST, COUNTER, ITEM_STATUS, SUB_ITEM_NUMBER, ITEM_NUMBER, ORDER_QTY, RECQTY, CHECK_IN_DATE, APPLIED_TO_INVENTORY_DATE, FORMULARY_ID, PURCHASE_ORDER_ID, VENDOR_ORDER_QTY, VENDOR_ACK_RECEIVED_QTY, VENDOR_RECQTY, APPLIED_QTY, CREATED_DATE, CONVERSION_FACTOR, VENDOR_ORDER_CASE) AS
select "TENANT_ID","ID","PARTITION_STAMP","NDC","ACK_RECEIVED_QTY","PACK","COST","COUNTER","ITEM_STATUS","SUB_ITEM_NUMBER","ITEM_NUMBER","ORDER_QTY","RECQTY","CHECK_IN_DATE","APPLIED_TO_INVENTORY_DATE","FORMULARY_ID","PURCHASE_ORDER_ID","VENDOR_ORDER_QTY","VENDOR_ACK_RECEIVED_QTY","VENDOR_RECQTY","APPLIED_QTY","CREATED_DATE","CONVERSION_FACTOR","VENDOR_ORDER_CASE" from SBMO.drug_orders WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.DRUGS (ID, DECIMAL_PACK, GENERIC_FULL_NAME, DRUG_FULL_NAME, GENERIC_NAME, GPI, INJECT, DRUG_NOTE, MFG, "NAME", NDC, PACK, PREVIOUS_NDC, REPLACEMENT_NDC, SCHEDULE, STRENGTH, TRIPLIC, UNIT, MFG_DISCONTINUE_DATE, LAST_UPDATED_DATE, SIGNATURE_REQUIRED, AWP, AWP_LAST_UPDATED, BARCODE, NDCFMT, PACKAGE_QTY, IND_PACK, MULTI_SOURCE, DDID, NARCOTIC_INDICATOR, DEEP_FROZEN, BIN_STORAGE_TYPE, HAZARDOUS_DRUG, INNER_PACK_INDICATOR) AS
select "ID","DECIMAL_PACK","GENERIC_FULL_NAME","DRUG_FULL_NAME","GENERIC_NAME","GPI","INJECT","DRUG_NOTE","MFG","NAME","NDC","PACK","PREVIOUS_NDC","REPLACEMENT_NDC","SCHEDULE","STRENGTH","TRIPLIC","UNIT","MFG_DISCONTINUE_DATE","LAST_UPDATED_DATE","SIGNATURE_REQUIRED","AWP","AWP_LAST_UPDATED","BARCODE","NDCFMT","PACKAGE_QTY","IND_PACK","MULTI_SOURCE","DDID","NARCOTIC_INDICATOR","DEEP_FROZEN","BIN_STORAGE_TYPE","HAZARDOUS_DRUG","INNER_PACK_INDICATOR" from SBMO.drugs
/
CREATE OR REPLACE VIEW SBMO_MEIJER.ENTITIES (TENANT_ID, ID) AS
select "TENANT_ID","ID" from SBMO.ENTITIES where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.FACILITIES (TENANT_ID, ID, SHORT_NAME, "NAME", ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP, COUNTY, DEA_NUMBER, FEDERAL_TAX_IDENTIFIER, NCPDP_NUMBER, NHINID, DEA_EXPIRATION_DATE, TIME_ZONE, LOCAL_PHONE_NUMBER, TOLL_FREE_PHONE_NUMBER, ALTERNATE_PHONE_NUMBER, EXPORT_ORDER_DISPENSER_MODULE, DISPENSER_COMM_ENABLED, CHECK_INV_FOR_HOME_DELIVERY, DRUG_LOT_NOT_REQUIRED, ORDER_PULL_DELAY, ENABLE_ITEM_LOCATIONS, RED_HOURS, YELLOW_HOURS, ACTIVE_DIRECTORY_GROUP, PAUSE_ORDER_PROCESSING_DATE, DOC_ERROR_RESET_DATE, DOC_CON_ERROR_RESET_DATE, DISPLAY_TX_COST_ERROR, LANDING_PAGE, STATUS_ALERT_THRESHOLD, PROMISED_DATE_ALERT_THRESHOLD, ORDER_PULL_JOB_FREQUENCY, CHECK_INV_FOR_SPECIALTY, TRANSITION_POLLTIME, TRANSITION_ALERT_THRESHOLD, TRANSITION_AUTO_TASK_DISABLED, TRANSITION_ALERT_EMAIL, PROMISE_DATE_ENABLED, PROMISE_DATE_SUN, PROMISE_DATE_MON, PROMISE_DATE_TUE, PROMISE_DATE_WED, PROMISE_DATE_THU, PROMISE_DATE_FRI, PROMISE_DATE_SAT, AUTO_CANCEL_TO_STORE, QUEUE_MAX_DAYS_BACK, CHECK_INV_FOR_STORE_DELIVERY, MAINTAIN_INVENTORY_QUANTITIES, PO_EMAIL, ORDER_PULL_THREAD_CNT, ORDER_PULL_MAX_CNT, ENABLE_HOLD_SPECIALTY_ORDERS, LAST_UPDATED_DATE, LAST_UPDATED_USER_ID, ENABLE_ORDER_CANCEL_REASON, DASHBOARD_JOB_ENABLED, STATUS_UPDATE_MAX_DAYS_BACK, IGNORE_PROM_DATE_HOME_DELIVERY, IGNORE_PROM_DATE_SPECIALTY, CHECK_INV_FOR_UNIT_DOSE, START_OF_DAY_TIME, ADHERIS_DOCUMENT_SIZE) AS
select "TENANT_ID","ID","SHORT_NAME","NAME","ADDRESS_LINE_1","ADDRESS_LINE_2","CITY","STATE","ZIP","COUNTY","DEA_NUMBER","FEDERAL_TAX_IDENTIFIER","NCPDP_NUMBER","NHINID","DEA_EXPIRATION_DATE","TIME_ZONE","LOCAL_PHONE_NUMBER","TOLL_FREE_PHONE_NUMBER","ALTERNATE_PHONE_NUMBER","EXPORT_ORDER_DISPENSER_MODULE","DISPENSER_COMM_ENABLED","CHECK_INV_FOR_HOME_DELIVERY","DRUG_LOT_NOT_REQUIRED","ORDER_PULL_DELAY","ENABLE_ITEM_LOCATIONS","RED_HOURS","YELLOW_HOURS","ACTIVE_DIRECTORY_GROUP","PAUSE_ORDER_PROCESSING_DATE","DOC_ERROR_RESET_DATE","DOC_CON_ERROR_RESET_DATE","DISPLAY_TX_COST_ERROR","LANDING_PAGE","STATUS_ALERT_THRESHOLD","PROMISED_DATE_ALERT_THRESHOLD","ORDER_PULL_JOB_FREQUENCY","CHECK_INV_FOR_SPECIALTY","TRANSITION_POLLTIME","TRANSITION_ALERT_THRESHOLD","TRANSITION_AUTO_TASK_DISABLED","TRANSITION_ALERT_EMAIL","PROMISE_DATE_ENABLED","PROMISE_DATE_SUN","PROMISE_DATE_MON","PROMISE_DATE_TUE","PROMISE_DATE_WED","PROMISE_DATE_THU","PROMISE_DATE_FRI","PROMISE_DATE_SAT","AUTO_CANCEL_TO_STORE","QUEUE_MAX_DAYS_BACK","CHECK_INV_FOR_STORE_DELIVERY","MAINTAIN_INVENTORY_QUANTITIES","PO_EMAIL","ORDER_PULL_THREAD_CNT","ORDER_PULL_MAX_CNT","ENABLE_HOLD_SPECIALTY_ORDERS","LAST_UPDATED_DATE","LAST_UPDATED_USER_ID","ENABLE_ORDER_CANCEL_REASON","DASHBOARD_JOB_ENABLED","STATUS_UPDATE_MAX_DAYS_BACK","IGNORE_PROM_DATE_HOME_DELIVERY","IGNORE_PROM_DATE_SPECIALTY","CHECK_INV_FOR_UNIT_DOSE","START_OF_DAY_TIME","ADHERIS_DOCUMENT_SIZE" from SBMO.FACILITIES WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.FORMULARY (TENANT_ID, ID, DEACTIVATED_DATE, EFFECTIVE_DATE, CONSIGNED, LAST_UPDATED_DATE, NDC, ALLOCATED_QTY, ONHAND_QTY, DRUG_ID, VENDOR_ID, INVENTORY_ID, LAST_DISPENSED_DATE, AVAILABLE_FOR_TYPE, ONHAND_ORIG_QTY, OVERRIDE_SHIP_ID, PRIORITY, OVERRIDE_INVENTORY, FILLING_STATION_ID, DISPENSED_INCREMENT, NOTE) AS
select "TENANT_ID","ID","DEACTIVATED_DATE","EFFECTIVE_DATE","CONSIGNED","LAST_UPDATED_DATE","NDC","ALLOCATED_QTY","ONHAND_QTY","DRUG_ID","VENDOR_ID","INVENTORY_ID","LAST_DISPENSED_DATE","AVAILABLE_FOR_TYPE","ONHAND_ORIG_QTY","OVERRIDE_SHIP_ID","PRIORITY","OVERRIDE_INVENTORY","FILLING_STATION_ID","DISPENSED_INCREMENT","NOTE" from SBMO.formulary where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.FORMULARY_REORDER (TENANT_ID, ID, ORDER_POINT, ORDER_QTY, MINIMUM_QTY, LAST_ORDER_DATE, HOLD_UNTIL_DATE) AS
select "TENANT_ID","ID","ORDER_POINT","ORDER_QTY","MINIMUM_QTY","LAST_ORDER_DATE","HOLD_UNTIL_DATE" from SBMO.FORMULARY_REORDER where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.INVENTORY (TENANT_ID, ID, "NAME", DATE_OF_LAST_PHYSICAL_COUNT, FACILITY_ID, AVAILABLE_FOR_TYPE, IGNORE_NDC_FORMULARY_STORE_DEL, IGNORE_NDC_FORMULARY_MAIL_DEL, IGNORE_NDC_FORMULARY_SPECIALTY) AS
select "TENANT_ID","ID","NAME","DATE_OF_LAST_PHYSICAL_COUNT","FACILITY_ID","AVAILABLE_FOR_TYPE","IGNORE_NDC_FORMULARY_STORE_DEL","IGNORE_NDC_FORMULARY_MAIL_DEL","IGNORE_NDC_FORMULARY_SPECIALTY" from SBMO.INVENTORY where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.INVENTORY_AUDIT (TENANT_ID, ID, ALLOCATED_CHANGE, ONHAND_CHANGE, UPDATED_DATE, DRUG_ORDER_ID, FORMULARY_ID, RET_ADJ_ID, RX_ID, CREATED_DATE) AS
select "TENANT_ID","ID","ALLOCATED_CHANGE","ONHAND_CHANGE","UPDATED_DATE","DRUG_ORDER_ID","FORMULARY_ID","RET_ADJ_ID","RX_ID","CREATED_DATE" from SBMO.INVENTORY_AUDIT where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.INVENTORY_DATE (TENANT_ID, ID, INVENTORY_LAST_UPDATED_DATE) AS
select "TENANT_ID","ID","INVENTORY_LAST_UPDATED_DATE" from SBMO.INVENTORY_DATE where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.ITEM_LOCATION (TENANT_ID, ID, FORMULARY_ID, QUANTITY) AS
select "TENANT_ID","ID","FORMULARY_ID","QUANTITY" from SBMO.ITEM_LOCATION where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.LABEL_IMAGES (TENANT_ID, ID, IMAGE_DATA, IMAGE_FORMAT, IMAGE_NAME, IMAGE_SOURCE) AS
select "TENANT_ID","ID","IMAGE_DATA","IMAGE_FORMAT","IMAGE_NAME","IMAGE_SOURCE" from SBMO.LABEL_IMAGES where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.LOCATION (TENANT_ID, ID, LOCATION_TYPE, PARENT_ID, USE_TYPE, DESCRIPTOR, LOCATION_STATUS) AS
select "TENANT_ID","ID","LOCATION_TYPE","PARENT_ID","USE_TYPE","DESCRIPTOR","LOCATION_STATUS" from SBMO.LOCATION where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.MASTER_PRODUCT_PO_VERIFY (TENANT_ID, ID, PURCHASE_ORDER_ID, VENDOR_ID, ORDER_DATE, TOTAL_ITEMS, PERCENT_SCANNED, PERCENT_PASSED, CREATED_DATE, PURCHASE_ORDER_STATUS) AS
select "TENANT_ID","ID","PURCHASE_ORDER_ID","VENDOR_ID","ORDER_DATE","TOTAL_ITEMS","PERCENT_SCANNED","PERCENT_PASSED","CREATED_DATE","PURCHASE_ORDER_STATUS" from SBMO.master_product_po_verify WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.MESSAGE_LOG (TENANT_ID, ID, MESSAGE_DATE, MESSAGE, STORE_ID, USER_INITS, CREATED_DATE) AS
select "TENANT_ID","ID","MESSAGE_DATE","MESSAGE","STORE_ID","USER_INITS","CREATED_DATE" from SBMO.MESSAGE_LOG where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.MONTHLY_SCHEDULED_TASKS (TENANT_ID, ID, APRIL, AUGUST, DECEMBER, FEBRUARY, JANUARY, JULY, JUNE, MARCH, MAY, NOVEMBER, OCTOBER, SEPTEMBER, "TYPE", DATE_OF_MONTH, DAY_OF_MONTH, FIRST_LAST, DAY_TYPE, FACILITY_ID) AS
select "TENANT_ID","ID","APRIL","AUGUST","DECEMBER","FEBRUARY","JANUARY","JULY","JUNE","MARCH","MAY","NOVEMBER","OCTOBER","SEPTEMBER","TYPE","DATE_OF_MONTH","DAY_OF_MONTH","FIRST_LAST","DAY_TYPE","FACILITY_ID" from SBMO.MONTHLY_SCHEDULED_TASKS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.ONCE_SCHEDULED_TASKS (TENANT_ID, ID, START_DATE, FACILITY_ID) AS
select "TENANT_ID","ID","START_DATE","FACILITY_ID" from SBMO.ONCE_SCHEDULED_TASKS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.ORDERS (TENANT_ID, ID, PARTITION_STAMP, ORDER_NUMBER, SHIP_ADDRESS, SHIP_ADDRESS2, SHIP_CITY, SHIP_FIRST_NAME, SHIP_MIDDLE_NAME, SHIP_LAST_NAME, SHIP_PHONE, SHIP_STATE, ORDER_TYPE, SHIP_TYPE, SHIP_ZIP, STORE_DEA, STORE_LIC, STORE_EST_SHIP_AMT, SIGNATURE_REQUIRED, STORE_ID, ORDER_PROCESSED, INVENTORY_ID, GROUPING_CODE, ALLOW_GROUPING, BATCH_IDENTIFIER, CREATED_DATE, PROMISED_DATE, PROMISE_DATE_OVERRIDE, REQUESTED_SHIP_DATE, SHIPPING_INSTRUCTIONS, EXTERNAL_ORDER_IDENTIFIER, VENDOR_CARRIER_CODE_IDENT, VENDOR_CARRIER_CODE_DESC, VENDOR_SHIP_BOX_IDENT) AS
select "TENANT_ID","ID","PARTITION_STAMP","ORDER_NUMBER","SHIP_ADDRESS","SHIP_ADDRESS2","SHIP_CITY","SHIP_FIRST_NAME","SHIP_MIDDLE_NAME","SHIP_LAST_NAME","SHIP_PHONE","SHIP_STATE","ORDER_TYPE","SHIP_TYPE","SHIP_ZIP","STORE_DEA","STORE_LIC","STORE_EST_SHIP_AMT","SIGNATURE_REQUIRED","STORE_ID","ORDER_PROCESSED","INVENTORY_ID","GROUPING_CODE","ALLOW_GROUPING","BATCH_IDENTIFIER","CREATED_DATE","PROMISED_DATE","PROMISE_DATE_OVERRIDE","REQUESTED_SHIP_DATE","SHIPPING_INSTRUCTIONS","EXTERNAL_ORDER_IDENTIFIER","VENDOR_CARRIER_CODE_IDENT","VENDOR_CARRIER_CODE_DESC","VENDOR_SHIP_BOX_IDENT" from SBMO.ORDERS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.PHONE_ADDRESS_OWNERS (TENANT_ID, ID) AS
select "TENANT_ID","ID" from SBMO.PHONE_ADDRESS_OWNERS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.PHONES (TENANT_ID, ID, PHONE_NUMBER, OWNER_ID, IDX) AS
select "TENANT_ID","ID","PHONE_NUMBER","OWNER_ID","IDX" from SBMO.PHONES where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.PRIORITY_CHANGE_ALERTS (TENANT_ID, ID, FORMULARY_ID, NDC, ACTION, ADDED_DATE, ACKNOWLEDGED, ACKNOWLEDGED_BY, FACILITY_ID) AS
select "TENANT_ID","ID","FORMULARY_ID","NDC","ACTION","ADDED_DATE","ACKNOWLEDGED","ACKNOWLEDGED_BY","FACILITY_ID" from SBMO.PRIORITY_CHANGE_ALERTS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.PURCHASE_ORDER (TENANT_ID, ID, PARTITION_STAMP, PO_GROUP_ID, CONSIGNED, VENDOR_ID, PURCHASE_ORDER_NUMBER, ACK_RECEIVED_USER_ID, CREATED_USER_ID, APPLIED_TO_INVENTORY_DATE, ACK_RECEIVED_DATE, APPLIED_TO_INVENTORY_USER_ID, ORDER_TRANSMIT_DATE, ORDER_TRANSMIT_USER_ID, CREATED_DATE, CHECK_IN_DATE, SUBMIT_DATE, CONTROL_NUMBER, INVOICE_NUMBER) AS
select "TENANT_ID","ID","PARTITION_STAMP","PO_GROUP_ID","CONSIGNED","VENDOR_ID","PURCHASE_ORDER_NUMBER","ACK_RECEIVED_USER_ID","CREATED_USER_ID","APPLIED_TO_INVENTORY_DATE","ACK_RECEIVED_DATE","APPLIED_TO_INVENTORY_USER_ID","ORDER_TRANSMIT_DATE","ORDER_TRANSMIT_USER_ID","CREATED_DATE","CHECK_IN_DATE","SUBMIT_DATE","CONTROL_NUMBER","INVOICE_NUMBER" from SBMO.PURCHASE_ORDER where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.PURCHASE_ORDER_GROUP (TENANT_ID, ID, CREATED_DATE, INVENTORY_ID) AS
select "TENANT_ID","ID","CREATED_DATE","INVENTORY_ID" from SBMO.PURCHASE_ORDER_GROUP where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.REGION (TENANT_ID, ID, "NAME", SUN_START_TIME, SUN_STOP_TIME, MON_START_TIME, MON_STOP_TIME, TUE_START_TIME, TUE_STOP_TIME, WED_START_TIME, WED_STOP_TIME, THU_START_TIME, THU_STOP_TIME, FRI_START_TIME, FRI_STOP_TIME, SAT_START_TIME, SAT_STOP_TIME) AS
select "TENANT_ID","ID","NAME","SUN_START_TIME","SUN_STOP_TIME","MON_START_TIME","MON_STOP_TIME","TUE_START_TIME","TUE_STOP_TIME","WED_START_TIME","WED_STOP_TIME","THU_START_TIME","THU_STOP_TIME","FRI_START_TIME","FRI_STOP_TIME","SAT_START_TIME","SAT_STOP_TIME" from SBMO.REGION where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.REPORT_REQUEST (TENANT_ID, ID, REPORT_NAME, USER_ID, FORMAT, SUBMISSION_DATE, START_DATE, COMPLETION_DATE, STATUS, DOWNLOAD_LINK, "HASH", FACILITY_ID) AS
select "TENANT_ID","ID","REPORT_NAME","USER_ID","FORMAT","SUBMISSION_DATE","START_DATE","COMPLETION_DATE","STATUS","DOWNLOAD_LINK","HASH","FACILITY_ID" from SBMO.REPORT_REQUEST where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.REPORT_REQUEST_PARAMETER (TENANT_ID, ID, REPORT_REQUEST_ID, PARAMETER_NAME, PARAMETER_VALUE) AS
select "TENANT_ID","ID","REPORT_REQUEST_ID","PARAMETER_NAME","PARAMETER_VALUE" from SBMO.REPORT_REQUEST_PARAMETER where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RETAIL_COST (TENANT_ID, ID, MAIL_ACQ_LAST_UPDATED, MAIL_ACQ, STORE_ACQ_LAST_UPDATED, STORE_ACQ, VENDOR_ID, CHAIN_ID, DRUG_ID, LAST_UPDATED_DATE, LAST_UPDATED_USER_ID) AS
select "TENANT_ID","ID","MAIL_ACQ_LAST_UPDATED","MAIL_ACQ","STORE_ACQ_LAST_UPDATED","STORE_ACQ","VENDOR_ID","CHAIN_ID","DRUG_ID","LAST_UPDATED_DATE","LAST_UPDATED_USER_ID" from SBMO.RETAIL_COST where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RETURN_AND_ADJUSTMENT (TENANT_ID, ID, PARTITION_STAMP, FORMULARY_ID, VENDOR_ID, ITEM_DESCRIPTION, ADJUSTMENT_CODE_ID, ADDED_BY_INVENTORY_COUNT, INVENTORY_AMOUNT, APPLIED_DATE, CREATED_DATE, ADDED_BY_USER, DESCRIPTION, ITEM_NUMBER, ADJUSTMENT_GROUP_ID, ITEM_LOCATION_ID, APPLY_ONLY_TO_ITEM_LOCATION) AS
select "TENANT_ID","ID","PARTITION_STAMP","FORMULARY_ID","VENDOR_ID","ITEM_DESCRIPTION","ADJUSTMENT_CODE_ID","ADDED_BY_INVENTORY_COUNT","INVENTORY_AMOUNT","APPLIED_DATE","CREATED_DATE","ADDED_BY_USER","DESCRIPTION","ITEM_NUMBER","ADJUSTMENT_GROUP_ID","ITEM_LOCATION_ID","APPLY_ONLY_TO_ITEM_LOCATION" from SBMO.RETURN_AND_ADJUSTMENT where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_CORES (TENANT_ID, ID, PARTITION_STAMP, DISPENSED_QTY, DAYS_SUPPLY, PRIORITY, RXNUM, STORE_CF_QUEUE_NUM, CF_QUEUE_NUM, TXNUM, ORDER_ID, SHIPPING_PACKAGE_ID, FILLED_VENDOR_ID, DISPENSED_NDC, REQUEST_NDC, ADDED_DATE, CANCELLED_DATE, LAST_UPDATE_DATE, STATUS, REQUEST_QTY, REQUEST_DECIMAL_QTY, STORE_NHINID, ERROR_TEXT, FILL_OPERATOR_ID, FILL_OPERATOR_INITIALS, POS_BARCODE_ID, AUTO_DISPENSED, CANCEL_ID, CANCEL_INITIALS, MISSING_INITIALS, MISSING_ID, DISPENSED_DATE, FOUND_INITIALS, FOUND_ID, COMPLETED_DATE, STATUS_LAST_UPDATE_DATE, HOLD_RX_AT_SBMO, STORE_REQUESTED_CANCEL, DOCUMENT_QUEUE_COMPLETE, EXPEDITE, CREATED_DATE, SPECIALTY, DISPENSED_DECIMAL_QTY, HOLD_RX_DUE_INV, MAIL_ORDER_USE_LOCAL_INVENTORY, PRESCRIBED_QTY, QTY_LEFT, FILLING_STATION_ID, ORDER_PULL_RETRY_COUNT, ACCEPTED_DATE, ADHERIS_RETRY_COUNT) AS
select "TENANT_ID","ID","PARTITION_STAMP","DISPENSED_QTY","DAYS_SUPPLY","PRIORITY","RXNUM","STORE_CF_QUEUE_NUM","CF_QUEUE_NUM","TXNUM","ORDER_ID","SHIPPING_PACKAGE_ID","FILLED_VENDOR_ID","DISPENSED_NDC","REQUEST_NDC","ADDED_DATE","CANCELLED_DATE","LAST_UPDATE_DATE","STATUS","REQUEST_QTY","REQUEST_DECIMAL_QTY","STORE_NHINID","ERROR_TEXT","FILL_OPERATOR_ID","FILL_OPERATOR_INITIALS","POS_BARCODE_ID","AUTO_DISPENSED","CANCEL_ID","CANCEL_INITIALS","MISSING_INITIALS","MISSING_ID","DISPENSED_DATE","FOUND_INITIALS","FOUND_ID","COMPLETED_DATE","STATUS_LAST_UPDATE_DATE","HOLD_RX_AT_SBMO","STORE_REQUESTED_CANCEL","DOCUMENT_QUEUE_COMPLETE","EXPEDITE","CREATED_DATE","SPECIALTY","DISPENSED_DECIMAL_QTY","HOLD_RX_DUE_INV","MAIL_ORDER_USE_LOCAL_INVENTORY","PRESCRIBED_QTY","QTY_LEFT","FILLING_STATION_ID","ORDER_PULL_RETRY_COUNT","ACCEPTED_DATE","ADHERIS_RETRY_COUNT" from SBMO.RX_CORES where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_CORES_MIN_DATE (TENANT_ID, ID, STATUS, MIN_DATE, DATE_TYPE, FACILITY_ID) AS
select "TENANT_ID","ID","STATUS","MIN_DATE","DATE_TYPE","FACILITY_ID" from SBMO.RX_CORES_MIN_DATE where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_DETAILS (TENANT_ID, ID, PARTITION_STAMP, CONSIGNED, STORE_ACQCOST, ALT_PRESCRIBER_NAME, PRESCRIBER_DEA, PRESCRIBER_FIRST_NAME, PRESCRIBER_MIDDLE_NAME, PRESCRIBER_LAST_NAME, PRESCRIBER_PHONE, PRESCRIBER_TYPE, DRUG_NAME, DRUG_FULL_NAME, FILL_DATE, PATIENT_ALLOWS_GENERIC, GENERIC_NAME, REFILL_NUM, REFILLS_REMAIN, RX_WRITTEN_DATE, RX_EXPIRES, RX_FIRST_FILLED, SAFETY_CAP, SIG_TEXT, SUBSTITUTED_FOR_NAME, TX_MESSAGE, DRUG_UNIT, DRUG_MANUFACTURER, NET_DUE, DRUG_IMPRINT, DIF_DRUG_LAST_FILL, GENERIC_FULL_NAME, PRINT_FILLED_DATE, TX_COST, FILLED_DISPENSER_ID, TX_VIA_AUTO_FILL, TOTAL_TP_BALANCE, TP_AUTH_NUM, TX_PRICE, PRESCRIBER_NPI, UC_PRICE, PARTIAL_FILL_STATUS, RX_SOURCE, PREVIOUS_PHARMACY, ALT_PRESCRIBER_TYPE, USER_DEFINED_DRUG_NAME, AUTOFILL_ENABLED, AUTOPAY_ENABLED, OVERRIDDEN_PRICE_AMOUNT, CIM_CORRECTION_WRITTEN, CREATED_DATE, CIM_CANCEL_WRITTEN, CIM_LAST_UPDATE_DATE, PRESCRIBER_ADDRESS, PRESCRIBER_ADDRESS_LINE_2, PRESCRIBER_CITY, PRESCRIBER_STATE, PRESCRIBER_ZIP, TAXABLE_OTC, DRUG_SCHEDULE, DAW, REFILLS_AUTHORIZED, DRUG_DOSAGE_FORM, DRUG_COLOR, DRUG_CLARITY, DRUG_SCORE, DRUG_SHAPE, DRUG_FLAVOR, DRUG_IMPRINT_SIDE1, DRUG_IMPRINT_SIDE2, DRUG_COATING, GENERIC, RX_MATCH_KEY, RX_IMAGE_IDENT, OLD_RX_NUMBER, FILL_NOTE, REQUIRE_UNIT_DOSE, COPAY_AMOUNT, ALT_NHIN_DRUG_NAME, NARCOTIC_INDICATOR, BIN_CODE, BIN_STORAGE_TYPE, HAZARDOUS_DRUG) AS
select "TENANT_ID","ID","PARTITION_STAMP","CONSIGNED","STORE_ACQCOST","ALT_PRESCRIBER_NAME","PRESCRIBER_DEA","PRESCRIBER_FIRST_NAME","PRESCRIBER_MIDDLE_NAME","PRESCRIBER_LAST_NAME","PRESCRIBER_PHONE","PRESCRIBER_TYPE","DRUG_NAME","DRUG_FULL_NAME","FILL_DATE","PATIENT_ALLOWS_GENERIC","GENERIC_NAME","REFILL_NUM","REFILLS_REMAIN","RX_WRITTEN_DATE","RX_EXPIRES","RX_FIRST_FILLED","SAFETY_CAP","SIG_TEXT","SUBSTITUTED_FOR_NAME","TX_MESSAGE","DRUG_UNIT","DRUG_MANUFACTURER","NET_DUE","DRUG_IMPRINT","DIF_DRUG_LAST_FILL","GENERIC_FULL_NAME","PRINT_FILLED_DATE","TX_COST","FILLED_DISPENSER_ID","TX_VIA_AUTO_FILL","TOTAL_TP_BALANCE","TP_AUTH_NUM","TX_PRICE","PRESCRIBER_NPI","UC_PRICE","PARTIAL_FILL_STATUS","RX_SOURCE","PREVIOUS_PHARMACY","ALT_PRESCRIBER_TYPE","USER_DEFINED_DRUG_NAME","AUTOFILL_ENABLED","AUTOPAY_ENABLED","OVERRIDDEN_PRICE_AMOUNT","CIM_CORRECTION_WRITTEN","CREATED_DATE","CIM_CANCEL_WRITTEN","CIM_LAST_UPDATE_DATE","PRESCRIBER_ADDRESS","PRESCRIBER_ADDRESS_LINE_2","PRESCRIBER_CITY","PRESCRIBER_STATE","PRESCRIBER_ZIP","TAXABLE_OTC","DRUG_SCHEDULE","DAW","REFILLS_AUTHORIZED","DRUG_DOSAGE_FORM","DRUG_COLOR","DRUG_CLARITY","DRUG_SCORE","DRUG_SHAPE","DRUG_FLAVOR","DRUG_IMPRINT_SIDE1","DRUG_IMPRINT_SIDE2","DRUG_COATING","GENERIC","RX_MATCH_KEY","RX_IMAGE_IDENT","OLD_RX_NUMBER","FILL_NOTE","REQUIRE_UNIT_DOSE","COPAY_AMOUNT","ALT_NHIN_DRUG_NAME","NARCOTIC_INDICATOR","BIN_CODE","BIN_STORAGE_TYPE","HAZARDOUS_DRUG" from SBMO.rx_details WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_DOCUMENTS (ID, TENANT_ID, PROGRAM_CODE, DOCUMENT_CODE, CHECK_SUM, RX_CORES_ID, FILE_CONTENTS, CREATED_DATE) AS
select "ID","TENANT_ID","PROGRAM_CODE","DOCUMENT_CODE","CHECK_SUM","RX_CORES_ID","FILE_CONTENTS","CREATED_DATE" from SBMO.rx_documents WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_LOTS (TENANT_ID, ID, PARTITION_STAMP, NUM, RX_ID, EXPIRE, CREATED_DATE, SERIAL_NUMBER, BARCODE_TYPE, BARCODE_RAW_DATA) AS
select "TENANT_ID","ID","PARTITION_STAMP","NUM","RX_ID","EXPIRE","CREATED_DATE","SERIAL_NUMBER","BARCODE_TYPE","BARCODE_RAW_DATA" from SBMO.rx_lots WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_PATSTORES (TENANT_ID, ID, PARTITION_STAMP, FIRST_NAME, LAST_NAME, MIDDLE_NAME, PATIENT_ID, STORE_RPH_INITS, STORE_RPH_NAME, STORE_USER_INITS, STORE_USER_ID, STORE_TECH_INITS, STORE_RPH_LICENSE_NUM, ADDRESS, ADDRESS2, CITY, STATE, ZIP, BIRTH_DATE, PHONE, PATIENT_RXCOM_ID, STORE_RPH_ID, STORE_TECH_ID, CARDHOLDERID, DRUG_UPC, PATIENT_DL_NUM, STORE_PATIENT_CODE, MEDICAL_RECORD_NUMBER, LANGUAGE, GENDER, PATIENT_EMAIL_ADDRESS, LOYALTY_CARD_NUMBER, IS_NEW_PATIENT, PATIENT_RECORD_TYPE, ANIMAL_TYPE, CARRIER_CODE, PLAN_CODE, PLAN_NAME, BIN, PCN, CREATED_DATE, RESPONSIBLE_PARTY_LAST_NAME, RESPONSIBLE_PARTY_FIRST_NAME, VISUALLY_IMPAIRED, PATIENT_DIGITAL_DOC_STATUS) AS
select "TENANT_ID","ID","PARTITION_STAMP","FIRST_NAME","LAST_NAME","MIDDLE_NAME","PATIENT_ID","STORE_RPH_INITS","STORE_RPH_NAME","STORE_USER_INITS","STORE_USER_ID","STORE_TECH_INITS","STORE_RPH_LICENSE_NUM","ADDRESS","ADDRESS2","CITY","STATE","ZIP","BIRTH_DATE","PHONE","PATIENT_RXCOM_ID","STORE_RPH_ID","STORE_TECH_ID","CARDHOLDERID","DRUG_UPC","PATIENT_DL_NUM","STORE_PATIENT_CODE","MEDICAL_RECORD_NUMBER","LANGUAGE","GENDER","PATIENT_EMAIL_ADDRESS","LOYALTY_CARD_NUMBER","IS_NEW_PATIENT","PATIENT_RECORD_TYPE","ANIMAL_TYPE","CARRIER_CODE","PLAN_CODE","PLAN_NAME","BIN","PCN","CREATED_DATE","RESPONSIBLE_PARTY_LAST_NAME","RESPONSIBLE_PARTY_FIRST_NAME","VISUALLY_IMPAIRED","PATIENT_DIGITAL_DOC_STATUS" from SBMO.RX_PATSTORES WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_PRINT_CHR (TENANT_ID, ID, RX_ID, CHR_CONTENT_CODE, CHR_CONTENT, CREATED_DATE) AS
select "TENANT_ID","ID","RX_ID","CHR_CONTENT_CODE","CHR_CONTENT","CREATED_DATE" from SBMO.RX_PRINT_CHR where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_PRINT_INFO (TENANT_ID, ID, PARTITION_STAMP, LABEL, PATIENT_ED, CREATED_DATE, FREE_FORM_REPORT_FORMAT, FREE_FORM_REPORT_MESSAGE, FREE_FORM_LABEL_FORMAT, FREE_FORM_LABEL_MESSAGE) AS
select "TENANT_ID","ID","PARTITION_STAMP","LABEL","PATIENT_ED","CREATED_DATE","FREE_FORM_REPORT_FORMAT","FREE_FORM_REPORT_MESSAGE","FREE_FORM_LABEL_FORMAT","FREE_FORM_LABEL_MESSAGE" from SBMO.RX_PRINT_INFO where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_REQUEST_ERROR (TENANT_ID, ID, DRUG_NAME, ORDER_TYPE, STORE_NHINID, ADDED_DATE, NDC, STATUS, INVENTORY_NAME, ERROR_CODE, ERROR_MESSAGE, REQUEST_DECIMAL_QTY, REQUEST_QTY, RXNUM, STORE_CF_QUEUE_NUM, CREATED_DATE, TXNUM, SPECIALTY, FACILITY_ID, INVENTORY_ID, VENDOR_ID) AS
select "TENANT_ID","ID","DRUG_NAME","ORDER_TYPE","STORE_NHINID","ADDED_DATE","NDC","STATUS","INVENTORY_NAME","ERROR_CODE","ERROR_MESSAGE","REQUEST_DECIMAL_QTY","REQUEST_QTY","RXNUM","STORE_CF_QUEUE_NUM","CREATED_DATE","TXNUM","SPECIALTY","FACILITY_ID","INVENTORY_ID","VENDOR_ID" from SBMO.rx_request_error WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_SHIPPING_PACKAGES (TENANT_ID, ID, PARTITION_STAMP, SHIPPED_DATE, OUNCES, TRACKING_NUMBER, PACKER_INITIALS, PACKER_ID, MANIFEST_INITIALS, MANIFEST_ID, TRUE_SHIP_AMT, FILLED_DISPENSER_ID, PARENT_ID, BARCODE, SHIP_SYS_SHPT_IDENTIFIER, SHIP_SYS_PKG_IDENTIFIER, RETURN_ADDRESS, RETURN_ADDRESS2, RETURN_CITY, RETURN_NAME, RETURN_PHONE, RETURN_STATE, SHIP_TO_ADDRESS, SHIP_TO_ADDRESS2, SHIP_TO_CITY, SHIP_TO_NAME, SHIP_TO_PHONE, SHIP_TO_STATE, RETURN_ZIP, SHIP_TO_ZIP, RETURN_COUNTRY, SHIP_TO_COUNTRY, CARRIER, SHIP_ADDON_AMOUNT, CREATED_DATE) AS
select "TENANT_ID","ID","PARTITION_STAMP","SHIPPED_DATE","OUNCES","TRACKING_NUMBER","PACKER_INITIALS","PACKER_ID","MANIFEST_INITIALS","MANIFEST_ID","TRUE_SHIP_AMT","FILLED_DISPENSER_ID","PARENT_ID","BARCODE","SHIP_SYS_SHPT_IDENTIFIER","SHIP_SYS_PKG_IDENTIFIER","RETURN_ADDRESS","RETURN_ADDRESS2","RETURN_CITY","RETURN_NAME","RETURN_PHONE","RETURN_STATE","SHIP_TO_ADDRESS","SHIP_TO_ADDRESS2","SHIP_TO_CITY","SHIP_TO_NAME","SHIP_TO_PHONE","SHIP_TO_STATE","RETURN_ZIP","SHIP_TO_ZIP","RETURN_COUNTRY","SHIP_TO_COUNTRY","CARRIER","SHIP_ADDON_AMOUNT","CREATED_DATE" from SBMO.rx_shipping_packages WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_STATE_TRANSITION (TENANT_ID, ID, RX_CORE_ID, TRANSITION_TYPE, TRANSITION_TIME, USER_ID, NOTIFICATION_SENT) AS
select "TENANT_ID","ID","RX_CORE_ID","TRANSITION_TYPE","TRANSITION_TIME","USER_ID","NOTIFICATION_SENT" from SBMO.RX_STATE_TRANSITION where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_TP_INFO (TENANT_ID, ID, RX_ID, ORDINAL, CARRIER_CODE, PLAN_CODE, PLAN_NAME, BIN, PCN, PLAN_GROUP_CODE, RELATIONSHIP_CODE, PLAN_TYPE, CARD_IDENTIFIER, TP_AUTH_NUM, CREATED_DATE, DISALLOW_INCENTIVES, INSURANCE_PAID) AS
select "TENANT_ID","ID","RX_ID","ORDINAL","CARRIER_CODE","PLAN_CODE","PLAN_NAME","BIN","PCN","PLAN_GROUP_CODE","RELATIONSHIP_CODE","PLAN_TYPE","CARD_IDENTIFIER","TP_AUTH_NUM","CREATED_DATE","DISALLOW_INCENTIVES","INSURANCE_PAID" from SBMO.RX_TP_INFO where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_VIAL_INFOS (TENANT_ID, ID, PARTITION_STAMP, QC_RPH_INIT, QC_RPH_ID, QC_RPH_LICENSE_NUMBER, RX_ID, VIAL_NUMBER, VIAL_QUANTITY, CREATED_DATE, VIAL_DECIMAL_QTY, QC_RPH_LAST_NAME, QC_RPH_FIRST_NAME, REPLENISH_RPH_FIRST_NAME, REPLENISH_RPH_LAST_NAME, REPLENISH_RPH_LICENSE_NUM, REPLENISH_RPH_EMPLOYEE_NUM, REPLENISH_TECH_FIRST_NAME, REPLENISH_TECH_LAST_NAME, REPLENISH_TECH_LICENSE_NUM, REPLENISH_TECH_EMPLOYEE_NUM, DISPENSER_STATION_IDENT, DISPENSER_CELL_IDENT) AS
select "TENANT_ID","ID","PARTITION_STAMP","QC_RPH_INIT","QC_RPH_ID","QC_RPH_LICENSE_NUMBER","RX_ID","VIAL_NUMBER","VIAL_QUANTITY","CREATED_DATE","VIAL_DECIMAL_QTY","QC_RPH_LAST_NAME","QC_RPH_FIRST_NAME","REPLENISH_RPH_FIRST_NAME","REPLENISH_RPH_LAST_NAME","REPLENISH_RPH_LICENSE_NUM","REPLENISH_RPH_EMPLOYEE_NUM","REPLENISH_TECH_FIRST_NAME","REPLENISH_TECH_LAST_NAME","REPLENISH_TECH_LICENSE_NUM","REPLENISH_TECH_EMPLOYEE_NUM","DISPENSER_STATION_IDENT","DISPENSER_CELL_IDENT" from SBMO.rx_vial_infos WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_WARNING_LABEL_CODES (TENANT_ID, ID, PARTITION_STAMP, LABEL_CODE, LABEL_LANGUAGE, SOURCE, IDX, RX_WARNING_LABEL_ID, WARNING_LABEL_GROUP) AS
select "TENANT_ID","ID","PARTITION_STAMP","LABEL_CODE","LABEL_LANGUAGE","SOURCE","IDX","RX_WARNING_LABEL_ID","WARNING_LABEL_GROUP" from SBMO.RX_WARNING_LABEL_CODES where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.RX_WARNING_LABELS (TENANT_ID, ID, RX_ID, IDX, PARTITION_STAMP, CREATED_DATE) AS
select "TENANT_ID","ID","RX_ID","IDX","PARTITION_STAMP","CREATED_DATE" from SBMO.RX_WARNING_LABELS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.SCHEDULED_TASKS (TENANT_ID, ID, JOB_NAME, REPEAT, REPEAT_INTERVAL, REPEAT_INTERVAL_UNIT, TASK_NAME, START_TIME, ENABLED, LAST_EXECUTION_DATE, LAST_EXECUTION_RESULT, PROPS, FACILITY_ID) AS
select "TENANT_ID","ID","JOB_NAME","REPEAT","REPEAT_INTERVAL","REPEAT_INTERVAL_UNIT","TASK_NAME","START_TIME","ENABLED","LAST_EXECUTION_DATE","LAST_EXECUTION_RESULT","PROPS","FACILITY_ID" from SBMO.SCHEDULED_TASKS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.SHIP_ITEMS (TENANT_ID, ID, PARTITION_STAMP, PURCHASE_ORDER_NUMBER, SHIPMENT_ID) AS
select "TENANT_ID","ID","PARTITION_STAMP","PURCHASE_ORDER_NUMBER","SHIPMENT_ID" from SBMO.SHIP_ITEMS where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.SHIPMENT (TENANT_ID, ID, PARTITION_STAMP, SIGNATURE, RECEIVED_DATE, PRINTED_NAME, RECEIVE_USERID) AS
select "TENANT_ID","ID","PARTITION_STAMP","SIGNATURE","RECEIVED_DATE","PRINTED_NAME","RECEIVE_USERID" from SBMO.SHIPMENT where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.STORE_SHIP_VIA (TENANT_ID, ID, ORDER_TYPE, SHIP_TYPE, SHIP_VIA, STORE_ID) AS
select "TENANT_ID","ID","ORDER_TYPE","SHIP_TYPE","SHIP_VIA","STORE_ID" from SBMO.STORE_SHIP_VIA where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.STORE_VENDOR_ACCOUNT (TENANT_ID, ID, MAIL_ACCOUNT_NUM, STORE_ID, STORE_ACCOUNT_NUM, VENDOR_ID) AS
select "TENANT_ID","ID","MAIL_ACCOUNT_NUM","STORE_ID","STORE_ACCOUNT_NUM","VENDOR_ID" from SBMO.STORE_VENDOR_ACCOUNT where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.STORES (TENANT_ID, ID, MAIL_INVENTORY_ID, STORE_INVENTORY_ID, STATE_CONTROLLED_SUB_LIC_NUM, DEA_EXPIRE_DATE, DEA_NUMBER, FEDERAL_TAX_NUMBER, STATE_LICENSE_NUMBER, "NAME", NCPDP, NHINID, STORE_NUMBER, DEACTIVATED_DATE, CHAIN_ID, STORE_LOGO_FILENAME, REGION_ID, STORE_DELIVERY_SHIP_TYPE, DEPARTMENT, SUPPRESS_DEA_PRINTING, NPI_NUM, LAST_STATUS_UPDATE_DATE, ENABLE_SU_ALERT_NOTIFICATION, FORCE_FORMULARY_DOWNLOAD, STORE_ORIG_INVENTORY_ID, MAIL_ORIG_INVENTORY_ID) AS
select "TENANT_ID","ID","MAIL_INVENTORY_ID","STORE_INVENTORY_ID","STATE_CONTROLLED_SUB_LIC_NUM","DEA_EXPIRE_DATE","DEA_NUMBER","FEDERAL_TAX_NUMBER","STATE_LICENSE_NUMBER","NAME","NCPDP","NHINID","STORE_NUMBER","DEACTIVATED_DATE","CHAIN_ID","STORE_LOGO_FILENAME","REGION_ID","STORE_DELIVERY_SHIP_TYPE","DEPARTMENT","SUPPRESS_DEA_PRINTING","NPI_NUM","LAST_STATUS_UPDATE_DATE","ENABLE_SU_ALERT_NOTIFICATION","FORCE_FORMULARY_DOWNLOAD","STORE_ORIG_INVENTORY_ID","MAIL_ORIG_INVENTORY_ID" from SBMO.STORES where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.SYSTEM_MESSAGES (TENANT_ID, ID, PARTITION_STAMP, MESSAGE, ADDED_DATE, MESSAGE_TYPE, ACKNOWLEDGED_BY, ACKNOWLEDGED, DATA, ERROR_TYPE, RESOLUTION_TEXT, REFERENCE_ID, REFERENCE_TYPE, CREATED_DATE, FACILITY_ID) AS
select "TENANT_ID","ID","PARTITION_STAMP","MESSAGE","ADDED_DATE","MESSAGE_TYPE","ACKNOWLEDGED_BY","ACKNOWLEDGED","DATA","ERROR_TYPE","RESOLUTION_TEXT","REFERENCE_ID","REFERENCE_TYPE","CREATED_DATE","FACILITY_ID" from SBMO.SYSTEM_MESSAGES where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.TENANTS (ID, "NAME", ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP, COUNTY, NHINID, TIME_ZONE, LOCAL_PHONE_NUMBER, TOLL_FREE_PHONE_NUMBER, ALTERNATE_PHONE_NUMBER, ACTIVE_DIRECTORY_GROUP, IS_RXCOM, NHIN_NAME_ABBREVIATION) AS
select "ID","NAME","ADDRESS_LINE_1","ADDRESS_LINE_2","CITY","STATE","ZIP","COUNTY","NHINID","TIME_ZONE","LOCAL_PHONE_NUMBER","TOLL_FREE_PHONE_NUMBER","ALTERNATE_PHONE_NUMBER","ACTIVE_DIRECTORY_GROUP","IS_RXCOM","NHIN_NAME_ABBREVIATION" from SBMO.tenants
/
CREATE OR REPLACE VIEW SBMO_MEIJER.VENDOR (TENANT_ID, ID, DEACTIVATE, "NAME", NHINVEN, NHINVENLEV, DEFAULT_ITEM_NUMBER_QUALIFIER, TRANSPORT_TYPE, TRANSPORT_PROPERTIES, BILLING_TEMPLATE_PATH, BILLING_TEMPLATE_PROPERTIES, DAY_SUPPLY_THRESHOLD, BILLING_TRANSPORT_TYPE, FORMULARY_INVENTORY_TYPE, BILLING_TRANSPORT_PROPERTIES, THREE_DIGIT_VENDOR_CODE, MINIMUM_PRICE_OVERRIDE, ALLOW_MULTIPLE_INVENTORIES, EXCLUDE_FROM_BILLING, INV_MGMT_TRANSPORT_TYPE, INV_MGMT_TRANSPORT_PROP, INV_MGMT_TEMPLATE_PATH, LAST_UPDATED_DATE, LAST_UPDATED_USER_ID, DISABLE_856, ALLOW_CSOS, DESCRIPTION, CII_RECEIVING, ENABLE_BAR_CODE_SCANNING, BAR_CODE_TYPE, PERCENTAGE_TO_SCAN_PO, TRANSPORT_855_PROPERTIES, TRANSPORT_855_TYPE) AS
select "TENANT_ID","ID","DEACTIVATE","NAME","NHINVEN","NHINVENLEV","DEFAULT_ITEM_NUMBER_QUALIFIER","TRANSPORT_TYPE","TRANSPORT_PROPERTIES","BILLING_TEMPLATE_PATH","BILLING_TEMPLATE_PROPERTIES","DAY_SUPPLY_THRESHOLD","BILLING_TRANSPORT_TYPE","FORMULARY_INVENTORY_TYPE","BILLING_TRANSPORT_PROPERTIES","THREE_DIGIT_VENDOR_CODE","MINIMUM_PRICE_OVERRIDE","ALLOW_MULTIPLE_INVENTORIES","EXCLUDE_FROM_BILLING","INV_MGMT_TRANSPORT_TYPE","INV_MGMT_TRANSPORT_PROP","INV_MGMT_TEMPLATE_PATH","LAST_UPDATED_DATE","LAST_UPDATED_USER_ID","DISABLE_856","ALLOW_CSOS","DESCRIPTION","CII_RECEIVING","ENABLE_BAR_CODE_SCANNING","BAR_CODE_TYPE","PERCENTAGE_TO_SCAN_PO","TRANSPORT_855_PROPERTIES","TRANSPORT_855_TYPE" from SBMO.VENDOR WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.VENDOR_ITEM_PROP (TENANT_ID, ID, ITEM_NUMBER, UNIT_CODE, ITEM_NUMBER_QUALIFIER, ACQ_COST, VENDOR_ID, DRUG_ID, CONVERSION_FACTOR) AS
select "TENANT_ID","ID","ITEM_NUMBER","UNIT_CODE","ITEM_NUMBER_QUALIFIER","ACQ_COST","VENDOR_ID","DRUG_ID","CONVERSION_FACTOR" from SBMO.vendor_item_prop WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.VENDOR_PO_CREATE_DAYS (ID, TENANT_ID, VENDOR_ID, DAY_OF_WEEK) AS
select "ID","TENANT_ID","VENDOR_ID","DAY_OF_WEEK" from SBMO.vendor_po_create_days WHERE tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.VENDOR_PROP (TENANT_ID, ID, OWNED_ACCOUNT_NUMBER, AUTHORIZATION_INFORMATION, SECURITY_INFORMATION, INTERCHANGE_SENDER_ID_QLF, INTERCHANGE_SENDER_ID, ICHANGE_RECEIVER_ID_QLF, INTERCHANGE_RECEIVER_ID, ICHANGE_CONTROL_STANDARDS_ID, ICHANGE_CTRL_VERSION_NUM, ACK_REQUESTED, USAGE_INDICATOR, COMPONENT_ELEMENT_SEPARATOR, SEGMENT_TERMINATOR, DATA_ELEMENT_SEPARATOR, FUNCTIONAL_IDENTIFIER_CODE, APPLICATION_SENDERS_CODE, APP_RECEIVERS_CODE, RESPONSIBLE_AGENCY_CODE, EDI_VERSION_SUPPORTED, EDI_VERSION_TEXT, PURCHASE_ORDER_TYPE_CODE, IDENTIFICATION_CODE_QLF, IDENTIFICATION_CODE, OWNED_IDENTIFICATION_CODE, CONSIGNED_ACCOUNT_NUMBER, URL_STRING, OWNED_APPLICATION_SENDERS_CODE, OWNED_INTERCHANGE_SENDER_ID, LAST_UPDATED_DATE, LAST_UPDATED_USER_ID) AS
select "TENANT_ID","ID","OWNED_ACCOUNT_NUMBER","AUTHORIZATION_INFORMATION","SECURITY_INFORMATION","INTERCHANGE_SENDER_ID_QLF","INTERCHANGE_SENDER_ID","ICHANGE_RECEIVER_ID_QLF","INTERCHANGE_RECEIVER_ID","ICHANGE_CONTROL_STANDARDS_ID","ICHANGE_CTRL_VERSION_NUM","ACK_REQUESTED","USAGE_INDICATOR","COMPONENT_ELEMENT_SEPARATOR","SEGMENT_TERMINATOR","DATA_ELEMENT_SEPARATOR","FUNCTIONAL_IDENTIFIER_CODE","APPLICATION_SENDERS_CODE","APP_RECEIVERS_CODE","RESPONSIBLE_AGENCY_CODE","EDI_VERSION_SUPPORTED","EDI_VERSION_TEXT","PURCHASE_ORDER_TYPE_CODE","IDENTIFICATION_CODE_QLF","IDENTIFICATION_CODE","OWNED_IDENTIFICATION_CODE","CONSIGNED_ACCOUNT_NUMBER","URL_STRING","OWNED_APPLICATION_SENDERS_CODE","OWNED_INTERCHANGE_SENDER_ID","LAST_UPDATED_DATE","LAST_UPDATED_USER_ID" from SBMO.VENDOR_PROP where tenant_id = 3
/
CREATE OR REPLACE VIEW SBMO_MEIJER.WEEKLY_SCHEDULED_TASKS (TENANT_ID, ID, FRIDAY, MONDAY, SATURDAY, SUNDAY, THURSDAY, TUESDAY, WEDNESDAY, FACILITY_ID) AS
select "TENANT_ID","ID","FRIDAY","MONDAY","SATURDAY","SUNDAY","THURSDAY","TUESDAY","WEDNESDAY","FACILITY_ID" from SBMO.WEEKLY_SCHEDULED_TASKS where tenant_id = 3
/
