-- BATCH 4 CONSTRAINTS
-- Schema: SBMO

ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_H]
ADD CONSTRAINT [PDX_SCHEMA_UPD_HLPR_DBG_H_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_PKGCALL_ERR_LOG]
ADD CONSTRAINT [PDX_SCHEMA_UPD_PKGCALL_ELOG_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_PKGCALL_ERR_LOG]
ADD CONSTRAINT [PDX_SCHEMA_UPD_PKGCALL_ELG_FK1] FOREIGN KEY ([ID])
REFERENCES [SBMO].[PDX_SCHEMA_UPD_PKGCALL_HIST] ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_PKGCALL_HIST]
ADD CONSTRAINT [PDX_SCHEMA_UPD_PKGCALL_HIST_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPDATER_MANIFEST]
ADD CONSTRAINT [PDX_SCHEMA_UPDATER_MANIFEST_PK] PRIMARY KEY ([VERSION]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPDATER_MANIFEST]
ADD CONSTRAINT [PDX_SCHEMA_UPDATER_MANIFST_UK1] UNIQUE ([FILE_NAME]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPDATER_MANIFEST]
ADD CONSTRAINT [PDX_SCHEMA_UPDATER_MANIFST_UK2] UNIQUE ([APPLY_ORDER]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPDATER_SQL]
ADD CONSTRAINT [PDX_SCHEMA_UPDATER_SQL_PK] PRIMARY KEY ([FILE_NAME]);

ALTER TABLE [SBMO].[PDX_SCHEMA_VERSION_ERROR_LOG]
ADD CONSTRAINT [PDX_SCHEMA_VERSION_ERR_LOG_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_VERSION_ERROR_LOG]
ADD CONSTRAINT [PDX_SCHEMA_VERSION_ERR_LOG_FK1] FOREIGN KEY ([ID])
REFERENCES [SBMO].[PDX_SCHEMA_VERSION_HISTORY] ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_VERSION_HISTORY]
ADD CONSTRAINT [PDX_SCHEMA_VERSION_HISTORY_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_VERSION_HISTORY]
ADD CONSTRAINT [PDX_SCHEMA_VERSION_HISTORY_FK1] FOREIGN KEY ([PDX_SCHEMA_UPD_PKGCALL_HIST_ID])
REFERENCES [SBMO].[PDX_SCHEMA_UPD_PKGCALL_HIST] ([ID]);

ALTER TABLE [SBMO].[PHONE_ADDRESS_OWNERS]
ADD CONSTRAINT [PHONE_ADDRESS_OWNERS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PHONE_ADDRESS_OWNERS]
ADD CONSTRAINT [PHONE_ADDRESS_OWNERS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[PHONES]
ADD CONSTRAINT [PHONES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PHONES]
ADD CONSTRAINT [PHONES_UK1] UNIQUE ([TENANT_ID], [OWNER_ID], [IDX]);

ALTER TABLE [SBMO].[PHONES]
ADD CONSTRAINT [PHONES_FK2] FOREIGN KEY ([TENANT_ID], [OWNER_ID])
REFERENCES [SBMO].[PHONE_ADDRESS_OWNERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PHONES]
ADD CONSTRAINT [PHONES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[PRIORITY_CHANGE_ALERTS]
ADD CONSTRAINT [PRIORITY_CHANGE_ALERTS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PRIORITY_CHANGE_ALERTS]
ADD CONSTRAINT [PRIORITY_CHANGE_ALERTS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PRIORITY_CHANGE_ALERTS]
ADD CONSTRAINT [PRIORITY_CHANGE_ALERTS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[PRIORITY_CHANGE_ALERTS]
ADD CONSTRAINT [PRIORITY_CHANGE_ALERTS_FK2] FOREIGN KEY ([TENANT_ID], [FORMULARY_ID])
REFERENCES [SBMO].[FORMULARY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PURCHASE_ORDER]
ADD CONSTRAINT [PURCHASE_ORDER_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PURCHASE_ORDER]
ADD CONSTRAINT [PURCHASE_ORDER_UK1] UNIQUE ([TENANT_ID], [PURCHASE_ORDER_NUMBER]);

ALTER TABLE [SBMO].[PURCHASE_ORDER]
ADD CONSTRAINT [PURCHASE_ORDER_FK4] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PURCHASE_ORDER]
ADD CONSTRAINT [PURCHASE_ORDER_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[PURCHASE_ORDER]
ADD CONSTRAINT [PURCHASE_ORDER_FK2] FOREIGN KEY ([TENANT_ID], [PO_GROUP_ID])
REFERENCES [SBMO].[PURCHASE_ORDER_GROUP] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PURCHASE_ORDER]
ADD CONSTRAINT [PURCHASE_ORDER_FK3] FOREIGN KEY ([TENANT_ID], [VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PURCHASE_ORDER_GROUP]
ADD CONSTRAINT [PURCHASE_ORDER_GROUP_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PURCHASE_ORDER_GROUP]
ADD CONSTRAINT [PURCHASE_ORDER_GROUP_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[PURCHASE_ORDER_GROUP]
ADD CONSTRAINT [PURCHASE_ORDER_GROUP_FK2] FOREIGN KEY ([TENANT_ID], [INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PURGE_CONFIG_SETTINGS]
ADD CONSTRAINT [PURGE_CONFIG_SETTINGS_PK] PRIMARY KEY ([NAME]);

ALTER TABLE [SBMO].[PURGE_ERROR_LOG]
ADD CONSTRAINT [PURGE_ERROR_LOG_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PURGE_HISTORY]
ADD CONSTRAINT [PURGE_HISTORY_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PURGE_HISTORY]
ADD CONSTRAINT [PURGE_HISTORY_FK1] FOREIGN KEY ([TABLE_NAME])
REFERENCES [SBMO].[PURGE_TABLES] ([TABLE_NAME]);

ALTER TABLE [SBMO].[PURGE_HISTORY_CHUNKS]
ADD CONSTRAINT [PURGE_HISTORY_CHUNKS_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PURGE_HISTORY_CHUNKS]
ADD CONSTRAINT [PURGE_HISTORY_CHUNKS_FK1] FOREIGN KEY ([ID_PURGE_HISTORY_PARTITIONS])
REFERENCES [SBMO].[PURGE_HISTORY_PARTITIONS] ([ID]);

ALTER TABLE [SBMO].[PURGE_HISTORY_PARTITIONS]
ADD CONSTRAINT [PURGE_HISTORY_PARTITIONS_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PURGE_HISTORY_PARTITIONS]
ADD CONSTRAINT [PURGE_HISTORY_PARTITIONS_FK1] FOREIGN KEY ([ID_PURGE_HISTORY])
REFERENCES [SBMO].[PURGE_HISTORY] ([ID]);

