-- BATCH 3 CONSTRAINTS
-- Schema: SBMO

ALTER TABLE [SBMO].[MONTHLY_SCHEDULED_TASKS]
ADD CONSTRAINT [MONTHLY_SCHEDULED_TASKS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MONTHLY_SCHEDULED_TASKS]
ADD CONSTRAINT [MONTHLY_SCHEDULED_TASKS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MONTHLY_SCHEDULED_TASKS]
ADD CONSTRAINT [MONTHLY_SCHEDULED_TASKS_FK2] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[SCHEDULED_TASKS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MONTHLY_SCHEDULED_TASKS]
ADD CONSTRAINT [MONTHLY_SCHEDULED_TASKS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[MUTEX]
ADD CONSTRAINT [MUTEX_PK] PRIMARY KEY ([NAME]);

ALTER TABLE [SBMO].[ONCE_SCHEDULED_TASKS]
ADD CONSTRAINT [ONCE_SCHEDULED_TASKS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ONCE_SCHEDULED_TASKS]
ADD CONSTRAINT [ONCE_SCHEDULED_TASKS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ONCE_SCHEDULED_TASKS]
ADD CONSTRAINT [ONCE_SCHEDULED_TASKS_FK2] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[SCHEDULED_TASKS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ONCE_SCHEDULED_TASKS]
ADD CONSTRAINT [ONCE_SCHEDULED_TASKS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[ORDERS]
ADD CONSTRAINT [ORDERS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ORDERS]
ADD CONSTRAINT [ORDERS_UQ_ORDER_NUMBER] UNIQUE ([ORDER_NUMBER]);

ALTER TABLE [SBMO].[ORDERS]
ADD CONSTRAINT [ORDERS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[ORDERS]
ADD CONSTRAINT [ORDERS_FK2] FOREIGN KEY ([TENANT_ID], [INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ORDERS]
ADD CONSTRAINT [ORDERS_FK3] FOREIGN KEY ([TENANT_ID], [STORE_ID])
REFERENCES [SBMO].[STORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[PARTITION_SQL_HISTORY]
ADD CONSTRAINT [SQL_HISTORY_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_DBA_APPLIED]
ADD CONSTRAINT [PDX_DBA_APPLIED_PK] PRIMARY KEY ([TASK_NAME]);

ALTER TABLE [SBMO].[PDX_SCHEMA_CONFIG]
ADD CONSTRAINT [PDX_SCHEMA_CONFIG_PK] PRIMARY KEY ([KEY]);

ALTER TABLE [SBMO].[PDX_SCHEMA_FILE_HASH]
ADD CONSTRAINT [PDX_SCHEMA_FILE_HASH_PK] PRIMARY KEY ([FILE_NAME], [FILE_SOURCE]);

ALTER TABLE [SBMO].[PDX_SCHEMA_FILE_TASKVER]
ADD CONSTRAINT [PDX_SCHEMA_FILE_TASKVER_PK] PRIMARY KEY ([FILE_NAME]);

ALTER TABLE [SBMO].[PDX_SCHEMA_FILE_TASKVER]
ADD CONSTRAINT [PDX_SCHEMA_FILE_TASKVER_UK1] UNIQUE ([TASK_VERSION]);

ALTER TABLE [SBMO].[PDX_SCHEMA_MAPPING]
ADD CONSTRAINT [PDX_SCHEMA_MAPPING_PK] PRIMARY KEY ([SEARCH]);

ALTER TABLE [SBMO].[PDX_SCHEMA_PRIV_DEFAULT]
ADD CONSTRAINT [PDX_SCHEMA_PRIV_DEFAULT_PK] PRIMARY KEY ([GRANTEE], [OBJECT_TYPE], [PRIVILEGE]);

ALTER TABLE [SBMO].[PDX_SCHEMA_PRIV_EXCEPTION]
ADD CONSTRAINT [PDX_SCHEMA_PRIV_EXCEPTION_PK] PRIMARY KEY ([GRANTEE], [OBJECT_TYPE], [OBJECT_NAME], [PRIVILEGE]);

ALTER TABLE [SBMO].[PDX_SCHEMA_PROCESS_HISTORY]
ADD CONSTRAINT [PDX_SCHEMA_PROCESS_HISTORY_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_PROCESS_HISTORY]
ADD CONSTRAINT [PDX_SCHEMA_PROCESS_HISTORY_UK1] UNIQUE ([PDX_SCHEMA_UPD_PKGCALL_HIST_ID], [PDX_SCHEMA_VERSION_HISTORY_ID], [PROCESS]);

ALTER TABLE [SBMO].[PDX_SCHEMA_PROCESS_HISTORY]
ADD CONSTRAINT [PDX_SCHEMA_PROCESS_HISTORY_FK1] FOREIGN KEY ([PDX_SCHEMA_UPD_PKGCALL_HIST_ID])
REFERENCES [SBMO].[PDX_SCHEMA_UPD_PKGCALL_HIST] ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_PROCESS_HISTORY]
ADD CONSTRAINT [PDX_SCHEMA_PROCESS_HISTORY_FK2] FOREIGN KEY ([PDX_SCHEMA_VERSION_HISTORY_ID])
REFERENCES [SBMO].[PDX_SCHEMA_VERSION_HISTORY] ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_TASK_ERROR_LOG]
ADD CONSTRAINT [PDX_SCHEMA_TASK_ERROR_LOG_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_TASK_ERROR_LOG]
ADD CONSTRAINT [PDX_SCHEMA_TASK_ERROR_LOG_FK1] FOREIGN KEY ([ID])
REFERENCES [SBMO].[PDX_SCHEMA_TASK_HISTORY] ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_TASK_HISTORY]
ADD CONSTRAINT [PDX_SCHEMA_TASK_HISTORY_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_TASK_HISTORY]
ADD CONSTRAINT [PDX_SCHEMA_TASK_HISTORY_FK1] FOREIGN KEY ([PDX_SCHEMA_UPD_PKGCALL_HIST_ID])
REFERENCES [SBMO].[PDX_SCHEMA_UPD_PKGCALL_HIST] ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_TASK_HISTORY]
ADD CONSTRAINT [PDX_SCHEMA_TASK_HISTORY_FK2] FOREIGN KEY ([PDX_SCHEMA_VERSION_HISTORY_ID])
REFERENCES [SBMO].[PDX_SCHEMA_VERSION_HISTORY] ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_TASKVER_META]
ADD CONSTRAINT [PDX_SCHEMA_TASKVER_META_PK] PRIMARY KEY ([TASK_VERSION], [TASK_SOURCE], [META_TAG], [TASK_VERSION_VALUE]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_D]
ADD CONSTRAINT [PDX_SCHEMA_UPD_HLPR_DBG_D_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_D]
ADD CONSTRAINT [PDX_SCHEMA_UPD_HLPR_DBG_D_FK1] FOREIGN KEY ([PDX_SCHEMA_UPD_HLPR_DBG_H_ID])
REFERENCES [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_H] ([ID]);

