-- BATCH 5 CONSTRAINTS
-- Schema: SBMO

ALTER TABLE [SBMO].[PURGE_TABLES]
ADD CONSTRAINT [PURGE_TABLES_PK] PRIMARY KEY ([TABLE_NAME]);

ALTER TABLE [SBMO].[QRTZ_BLOB_TRIGGERS]
ADD CONSTRAINT [QRTZ_BLOB_TRIGGERS_PK] PRIMARY KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);

ALTER TABLE [SBMO].[QRTZ_BLOB_TRIGGERS]
ADD CONSTRAINT [QRTZ_BLOB_TRIGGERS_FK1] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
REFERENCES [SBMO].[QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);

ALTER TABLE [SBMO].[QRTZ_CALENDARS]
ADD CONSTRAINT [QRTZ_CALENDARS_PK] PRIMARY KEY ([SCHED_NAME], [CALENDAR_NAME]);

ALTER TABLE [SBMO].[QRTZ_CRON_TRIGGERS]
ADD CONSTRAINT [QRTZ_CRON_TRIGGERS_PK] PRIMARY KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);

ALTER TABLE [SBMO].[QRTZ_CRON_TRIGGERS]
ADD CONSTRAINT [QRTZ_CRON_TRIGGERS_FK1] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
REFERENCES [SBMO].[QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);

ALTER TABLE [SBMO].[QRTZ_FIRED_TRIGGERS]
ADD CONSTRAINT [QRTZ_FIRED_TRIGGERS_PK] PRIMARY KEY ([SCHED_NAME], [ENTRY_ID]);

ALTER TABLE [SBMO].[QRTZ_JOB_DETAILS]
ADD CONSTRAINT [QRTZ_JOB_DETAILS_PK] PRIMARY KEY ([SCHED_NAME], [JOB_NAME], [JOB_GROUP]);

ALTER TABLE [SBMO].[QRTZ_LOCKS]
ADD CONSTRAINT [QRTZ_LOCKS_PK] PRIMARY KEY ([SCHED_NAME], [LOCK_NAME]);

ALTER TABLE [SBMO].[QRTZ_PAUSED_TRIGGER_GRPS]
ADD CONSTRAINT [QRTZ_PAUSED_TRIGGER_GRPS_PK] PRIMARY KEY ([SCHED_NAME], [TRIGGER_GROUP]);

ALTER TABLE [SBMO].[QRTZ_SCHEDULER_STATE]
ADD CONSTRAINT [QRTZ_SCHEDULER_STATE_PK] PRIMARY KEY ([SCHED_NAME], [INSTANCE_NAME]);

ALTER TABLE [SBMO].[QRTZ_SIMPLE_TRIGGERS]
ADD CONSTRAINT [QRTZ_SIMPLE_TRIGGERS_PK] PRIMARY KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);

ALTER TABLE [SBMO].[QRTZ_SIMPLE_TRIGGERS]
ADD CONSTRAINT [QRTZ_SIMPLE_TRIGGERS_FK1] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
REFERENCES [SBMO].[QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);

ALTER TABLE [SBMO].[QRTZ_SIMPROP_TRIGGERS]
ADD CONSTRAINT [QRTZ_SIMPROP_TRIGGERS_PK] PRIMARY KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);

ALTER TABLE [SBMO].[QRTZ_SIMPROP_TRIGGERS]
ADD CONSTRAINT [QRTZ_SIMPROP_TRIGGERS_FK1] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
REFERENCES [SBMO].[QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);

ALTER TABLE [SBMO].[QRTZ_TRIGGERS]
ADD CONSTRAINT [QRTZ_TRIGGERS_PK] PRIMARY KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]);

ALTER TABLE [SBMO].[QRTZ_TRIGGERS]
ADD CONSTRAINT [QRTZ_TRIGGERS_FK1] FOREIGN KEY ([SCHED_NAME], [JOB_NAME], [JOB_GROUP])
REFERENCES [SBMO].[QRTZ_JOB_DETAILS] ([SCHED_NAME], [JOB_NAME], [JOB_GROUP]);

ALTER TABLE [SBMO].[REGION]
ADD CONSTRAINT [REGION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[REGION]
ADD CONSTRAINT [REGION_UK1] UNIQUE ([TENANT_ID], [NAME]);

ALTER TABLE [SBMO].[REGION]
ADD CONSTRAINT [REGION_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[REPORT_REQUEST]
ADD CONSTRAINT [REPORT_REQUEST_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[REPORT_REQUEST]
ADD CONSTRAINT [REPORT_REQUEST_FK1] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[REPORT_REQUEST_PARAMETER]
ADD CONSTRAINT [REPORT_REQUEST_PARAMETER_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[REPORT_REQUEST_PARAMETER]
ADD CONSTRAINT [REPORT_REQUEST_PARAMETER_FK1] FOREIGN KEY ([TENANT_ID], [REPORT_REQUEST_ID])
REFERENCES [SBMO].[REPORT_REQUEST] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETAIL_COST]
ADD CONSTRAINT [RETAIL_COST_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETAIL_COST]
ADD CONSTRAINT [RET_COST_UQ_VEND_CHAIN_DRUG] UNIQUE ([VENDOR_ID], [CHAIN_ID], [DRUG_ID]);

ALTER TABLE [SBMO].[RETAIL_COST]
ADD CONSTRAINT [RETAIL_COST_FK3] FOREIGN KEY ([TENANT_ID], [VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETAIL_COST]
ADD CONSTRAINT [RETAIL_COST_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RETAIL_COST]
ADD CONSTRAINT [RETAIL_COST_FK_DRUG_ID] FOREIGN KEY ([DRUG_ID])
REFERENCES [SBMO].[DRUGS] ([ID]);

ALTER TABLE [SBMO].[RETAIL_COST]
ADD CONSTRAINT [RETAIL_COST_FK2] FOREIGN KEY ([TENANT_ID], [CHAIN_ID])
REFERENCES [SBMO].[CHAINS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_FK5] FOREIGN KEY ([TENANT_ID], [ITEM_LOCATION_ID])
REFERENCES [SBMO].[ITEM_LOCATION] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_FK6] FOREIGN KEY ([TENANT_ID], [ADJUSTMENT_GROUP_ID])
REFERENCES [SBMO].[ADJUSTMENT_GROUP] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURNADJUST_FK_ADJCODEID] FOREIGN KEY ([ADJUSTMENT_CODE_ID])
REFERENCES [SBMO].[ADJUSTMENT_CODES] ([ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_FK3] FOREIGN KEY ([TENANT_ID], [FORMULARY_ID])
REFERENCES [SBMO].[FORMULARY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RETURN_AND_ADJUSTMENT]
ADD CONSTRAINT [RETURN_AND_ADJUSTMENT_FK4] FOREIGN KEY ([TENANT_ID], [VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_UQ_CFQUEUENUM] UNIQUE ([CF_QUEUE_NUM]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK8] FOREIGN KEY ([TENANT_ID], [FILLING_STATION_ID])
REFERENCES [SBMO].[FILLING_STATION] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK2] FOREIGN KEY ([TENANT_ID], [FILLED_VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK3] FOREIGN KEY ([TENANT_ID], [ORDER_ID])
REFERENCES [SBMO].[ORDERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK4] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[RX_DETAILS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK5] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[RX_PATSTORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK6] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[RX_PRINT_INFO] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES]
ADD CONSTRAINT [RX_CORES_FK7] FOREIGN KEY ([TENANT_ID], [SHIPPING_PACKAGE_ID])
REFERENCES [SBMO].[RX_SHIPPING_PACKAGES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES_MIN_DATE]
ADD CONSTRAINT [RX_CORES_MIN_DATE_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES_MIN_DATE]
ADD CONSTRAINT [RX_CORES_MIN_DATE_UK1] UNIQUE ([TENANT_ID], [FACILITY_ID], [DATE_TYPE], [STATUS]);

ALTER TABLE [SBMO].[RX_CORES_MIN_DATE]
ADD CONSTRAINT [RX_CORES_MIN_DATE_FK2] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[RX_CORES_MIN_DATE]
ADD CONSTRAINT [RX_CORES_MIN_DATE_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

