-- BATCH 7 CONSTRAINTS (FINAL)
-- Schema: SBMO

ALTER TABLE [SBMO].[SCHEMA_UPDATER_MANIFEST]
ADD CONSTRAINT [SCHEMA_UPDATER_MANIFEST_PK] PRIMARY KEY ([FILE_NAME]);

ALTER TABLE [SBMO].[SCHEMA_UPDATER_MANIFEST]
ADD CONSTRAINT [SCHEMA_UPDATER_MANIFEST_UK1] UNIQUE ([VERSION]);

ALTER TABLE [SBMO].[SCHEMA_UPDATER_MANIFEST]
ADD CONSTRAINT [SCHEMA_UPDATER_MANIFST_UK2] UNIQUE ([APPLY_ORDER]);

ALTER TABLE [SBMO].[SCHEMA_UPDATER_SQL]
ADD CONSTRAINT [SCHEMA_UPDATER_SQL_PK] PRIMARY KEY ([FILE_NAME]);

ALTER TABLE [SBMO].[SHIP_ITEMS]
ADD CONSTRAINT [SHIP_ITEMS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SHIP_ITEMS]
ADD CONSTRAINT [SHIP_ITEMS_FK2] FOREIGN KEY ([TENANT_ID], [SHIPMENT_ID])
REFERENCES [SBMO].[SHIPMENT] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SHIP_ITEMS]
ADD CONSTRAINT [SHIP_ITEMS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[SHIPMENT]
ADD CONSTRAINT [SHIPMENT_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SHIPMENT]
ADD CONSTRAINT [SHIPMENT_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[STORE_SHIP_VIA]
ADD CONSTRAINT [STORE_SHIP_VIA_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORE_SHIP_VIA]
ADD CONSTRAINT [STORE_SHIP_VIA_FK2] FOREIGN KEY ([TENANT_ID], [STORE_ID])
REFERENCES [SBMO].[STORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORE_SHIP_VIA]
ADD CONSTRAINT [STORE_SHIP_VIA_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[STORE_VENDOR_ACCOUNT]
ADD CONSTRAINT [STORE_VENDOR_ACCOUNT_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORE_VENDOR_ACCOUNT]
ADD CONSTRAINT [STORE_VENDOR_ACCOUNT_FK2] FOREIGN KEY ([TENANT_ID], [STORE_ID])
REFERENCES [SBMO].[STORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORE_VENDOR_ACCOUNT]
ADD CONSTRAINT [STORE_VENDOR_ACCOUNT_FK3] FOREIGN KEY ([TENANT_ID], [VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORE_VENDOR_ACCOUNT]
ADD CONSTRAINT [STORE_VENDOR_ACCOUNT_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_UK2] UNIQUE ([NPI_NUM]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_UK1] UNIQUE ([TENANT_ID], [NCPDP], [DEPARTMENT]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_UQ_NHINID] UNIQUE ([NHINID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_FK9] FOREIGN KEY ([TENANT_ID], [STORE_ORIG_INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_FK10] FOREIGN KEY ([TENANT_ID], [MAIL_ORIG_INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_FK2] FOREIGN KEY ([TENANT_ID], [CHAIN_ID])
REFERENCES [SBMO].[CHAINS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_FK3] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[ENTITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_FK4] FOREIGN KEY ([TENANT_ID], [MAIL_INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_FK5] FOREIGN KEY ([TENANT_ID], [STORE_INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_FK6] FOREIGN KEY ([TENANT_ID], [REGION_ID])
REFERENCES [SBMO].[REGION] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_FK11] FOREIGN KEY ([TENANT_ID], [UNIT_DOSE_INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[STORES]
ADD CONSTRAINT [STORES_FK12] FOREIGN KEY ([TENANT_ID], [UNIT_DOSE_ORIG_INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SYSTEM_MESSAGES]
ADD CONSTRAINT [SYSTEM_MESSAGES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SYSTEM_MESSAGES]
ADD CONSTRAINT [SYSTEM_MESSAGES_FK2] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[SYSTEM_MESSAGES]
ADD CONSTRAINT [SYSTEM_MESSAGES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[TENANTS]
ADD CONSTRAINT [TENANTS_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[TENANTS]
ADD CONSTRAINT [TENANTS_UK1] UNIQUE ([NAME]);

ALTER TABLE [SBMO].[USER_AUDIT_LOG]
ADD CONSTRAINT [USER_AUDIT_LOG_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[VENDOR]
ADD CONSTRAINT [VENDOR_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR]
ADD CONSTRAINT [VENDOR_UK1] UNIQUE ([TENANT_ID], [NHINVEN]);

ALTER TABLE [SBMO].[VENDOR]
ADD CONSTRAINT [VENDOR_FK2] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[ENTITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR]
ADD CONSTRAINT [VENDOR_FK3] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[VENDOR_PROP] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR]
ADD CONSTRAINT [VENDOR_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[VENDOR_ITEM_PROP]
ADD CONSTRAINT [VENDOR_ITEM_PROP_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR_ITEM_PROP]
ADD CONSTRAINT [VENDOR_ITEM_PROP_UK1] UNIQUE ([TENANT_ID], [VENDOR_ID], [DRUG_ID]);

ALTER TABLE [SBMO].[VENDOR_ITEM_PROP]
ADD CONSTRAINT [VENDOR_ITEM_PROP_FK2] FOREIGN KEY ([TENANT_ID], [VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR_ITEM_PROP]
ADD CONSTRAINT [VENDOR_ITEM_PROP_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[VENDOR_ITEM_PROP]
ADD CONSTRAINT [VENDOR_ITEM_PROP_FK_DRUG_ID] FOREIGN KEY ([DRUG_ID])
REFERENCES [SBMO].[DRUGS] ([ID]);

ALTER TABLE [SBMO].[VENDOR_PO_CREATE_DAYS]
ADD CONSTRAINT [VENDOR_PO_CREATE_DAYS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR_PO_CREATE_DAYS]
ADD CONSTRAINT [VENDOR_PO_CREATE_DAYS_UK1] UNIQUE ([TENANT_ID], [VENDOR_ID], [DAY_OF_WEEK]);

ALTER TABLE [SBMO].[VENDOR_PO_CREATE_DAYS]
ADD CONSTRAINT [VENDOR_PO_CREATE_DAYS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[VENDOR_PO_CREATE_DAYS]
ADD CONSTRAINT [VENDOR_PO_CREATE_DAYS_FK2] FOREIGN KEY ([TENANT_ID], [VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR_PROP]
ADD CONSTRAINT [VENDOR_PROP_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[VENDOR_PROP]
ADD CONSTRAINT [VENDOR_PROP_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[WEEKLY_SCHEDULED_TASKS]
ADD CONSTRAINT [WEEKLY_SCHEDULED_TASKS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[WEEKLY_SCHEDULED_TASKS]
ADD CONSTRAINT [WEEKLY_SCHEDULED_TASKS_FK2] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[SCHEDULED_TASKS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[WEEKLY_SCHEDULED_TASKS]
ADD CONSTRAINT [WEEKLY_SCHEDULED_TASKS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[WEEKLY_SCHEDULED_TASKS]
ADD CONSTRAINT [WEEKLY_SCHEDULED_TASKS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

