-- BATCH 1 CONSTRAINTS
-- Schema: SBMO

ALTER TABLE [SBMO].[ADDRESSES]
ADD CONSTRAINT [ADDRESSES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ADDRESSES]
ADD CONSTRAINT [ADDRESSES_FK2] FOREIGN KEY ([TENANT_ID], [OWNER_ID])
REFERENCES [SBMO].[PHONE_ADDRESS_OWNERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ADDRESSES]
ADD CONSTRAINT [ADDRESSES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[ADJUSTMENT_CODES]
ADD CONSTRAINT [ADJUSTMENT_CODES_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[ADJUSTMENT_GROUP]
ADD CONSTRAINT [ADJUSTMENT_GROUP_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ADJUSTMENT_GROUP]
ADD CONSTRAINT [ADJUSTMENT_GROUP_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[ADJUSTMENT_GROUP]
ADD CONSTRAINT [ADJUSTMENT_GROUP_FK2] FOREIGN KEY ([TENANT_ID], [INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[AUDIT_DBU_LOG]
ADD CONSTRAINT [AUDIT_DBU_LOG_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[AUDIT_LOG]
ADD CONSTRAINT [AUDIT_LOG_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[AUDIT_LOG]
ADD CONSTRAINT [AUDIT_LOG_FK2] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[AUDIT_LOG]
ADD CONSTRAINT [AUDIT_LOG_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[BIN_UPC_LINK]
ADD CONSTRAINT [BIN_UPC_LINK_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[BIN_UPC_LINK]
ADD CONSTRAINT [BIN_UPC_LINK_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[CARRIER]
ADD CONSTRAINT [CARRIER_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CARRIER]
ADD CONSTRAINT [CARRIER_UK1] UNIQUE ([TENANT_ID], [NAME]);

ALTER TABLE [SBMO].[CARRIER]
ADD CONSTRAINT [CARRIER_UK2] UNIQUE ([TENANT_ID], [SHIP_IDENT]);

ALTER TABLE [SBMO].[CARRIER]
ADD CONSTRAINT [CARRIER_UK3] UNIQUE ([TENANT_ID], [SHIP_PRIORITY]);

ALTER TABLE [SBMO].[CARRIER]
ADD CONSTRAINT [CARRIER_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[CF_SEC_CHAIN]
ADD CONSTRAINT [CF_SEC_CHAIN_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CF_SEC_CHAIN]
ADD CONSTRAINT [CF_SEC_CHAIN_FK2] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[CHAINS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CF_SEC_CHAIN]
ADD CONSTRAINT [CF_SEC_CHAIN_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[CF_SEC_STORE]
ADD CONSTRAINT [CF_SEC_STORE_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CF_SEC_STORE]
ADD CONSTRAINT [CF_SEC_STORE_FK2] FOREIGN KEY ([TENANT_ID], [CHAIN_ID])
REFERENCES [SBMO].[CF_SEC_CHAIN] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CF_SEC_STORE]
ADD CONSTRAINT [CF_SEC_STORE_FK3] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[STORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CF_SEC_STORE]
ADD CONSTRAINT [CF_SEC_STORE_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[CHAINS]
ADD CONSTRAINT [CHAINS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CHAINS]
ADD CONSTRAINT [CHAINS_UQ_HQID] UNIQUE ([HQ_ID]);

ALTER TABLE [SBMO].[CHAINS]
ADD CONSTRAINT [CHAINS_UQ_NHINID] UNIQUE ([NHINID]);

ALTER TABLE [SBMO].[CHAINS]
ADD CONSTRAINT [CHAINS_FK2] FOREIGN KEY ([TENANT_ID], [PARENT_ID])
REFERENCES [SBMO].[CHAINS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CHAINS]
ADD CONSTRAINT [CHAINS_FK3] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[ENTITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CHAINS]
ADD CONSTRAINT [CHAINS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[CHARGE_PAYMENT_INFO]
ADD CONSTRAINT [CHARGE_PAYMENT_INFO_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CHARGE_PAYMENT_INFO]
ADD CONSTRAINT [CHARGE_PAYMENT_INFO_FK1] FOREIGN KEY ([TENANT_ID], [ORDER_ID])
REFERENCES [SBMO].[ORDERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CONTACTS]
ADD CONSTRAINT [CONTACTS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CONTACTS]
ADD CONSTRAINT [CONTACTS_FK2] FOREIGN KEY ([TENANT_ID], [ENTITY_ID])
REFERENCES [SBMO].[ENTITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CONTACTS]
ADD CONSTRAINT [CONTACTS_FK3] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[PHONE_ADDRESS_OWNERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CONTACTS]
ADD CONSTRAINT [CONTACTS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[CUSTOM_SCHEDULED_TASK]
ADD CONSTRAINT [CUSTOM_SCHEDULED_TASK_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CUSTOM_SCHEDULED_TASK]
ADD CONSTRAINT [CUSTOM_SCHEDULED_TASK_UK1] UNIQUE ([TENANT_ID], [TASK_DAY], [SCHEDULE_GROUPING]);

ALTER TABLE [SBMO].[CUSTOM_SCHEDULED_TASK]
ADD CONSTRAINT [CUSTOM_SCHEDULED_TASK_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[CUSTOM_SCHEDULED_TASK]
ADD CONSTRAINT [CUSTOM_SCHEDULED_TASK_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[CUSTOM_SCHEDULED_TASK]
ADD CONSTRAINT [CUSTOM_SCHEDULED_TASK_FK2] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[SCHEDULED_TASKS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DAILY_SCHEDULED_TASKS]
ADD CONSTRAINT [DAILY_SCHEDULED_TASKS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DAILY_SCHEDULED_TASKS]
ADD CONSTRAINT [DAILY_SCHEDULED_TASKS_FK2] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[SCHEDULED_TASKS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DAILY_SCHEDULED_TASKS]
ADD CONSTRAINT [DAILY_SCHEDULED_TASKS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[DAILY_SCHEDULED_TASKS]
ADD CONSTRAINT [DAILY_SCHEDULED_TASKS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DASHBOARD_SETTINGS]
ADD CONSTRAINT [DASHBOARD_SETTINGS_PK] PRIMARY KEY ([TENANT_ID], [FACILITY_ID], [ID]);

ALTER TABLE [SBMO].[DASHBOARD_SETTINGS]
ADD CONSTRAINT [DASHBOARD_SETTINGS_UK1] UNIQUE ([TENANT_ID], [FACILITY_ID], [DAY_OF_WEEK]);

ALTER TABLE [SBMO].[DASHBOARD_SETTINGS]
ADD CONSTRAINT [DASHBOARD_SETTINGS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[DASHBOARD_SETTINGS]
ADD CONSTRAINT [DASHBOARD_SETTINGS_FK2] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DASHBOARD_STATISTICS]
ADD CONSTRAINT [DASHBOARD_STATISTICS_PK] PRIMARY KEY ([TENANT_ID], [FACILITY_ID], [ID]);

ALTER TABLE [SBMO].[DASHBOARD_STATISTICS]
ADD CONSTRAINT [DASHBOARD_STATISTICS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[DASHBOARD_STATISTICS]
ADD CONSTRAINT [DASHBOARD_STATISTICS_FK2] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DISPENSER_LOCATION]
ADD CONSTRAINT [DISPENSER_LOCATION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DISPENSER_LOCATION]
ADD CONSTRAINT [DISPENSER_LOCATION_UK1] UNIQUE ([TENANT_ID], [CELLID], [STATIONID]);

ALTER TABLE [SBMO].[DISPENSER_LOCATION]
ADD CONSTRAINT [DISPENSER_LOCATION_UK2] UNIQUE ([TENANT_ID], [DISPENSER_ID], [LOCATION_ID]);

ALTER TABLE [SBMO].[DISPENSER_LOCATION]
ADD CONSTRAINT [DISP_LOC_UQ_DISP_CELL_STAT] UNIQUE ([DISPENSER_ID], [CELLID], [STATIONID]);

ALTER TABLE [SBMO].[DISPENSER_LOCATION]
ADD CONSTRAINT [DISPENSER_LOCATION_FK2] FOREIGN KEY ([TENANT_ID], [DISPENSER_ID])
REFERENCES [SBMO].[DISPENSERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DISPENSER_LOCATION]
ADD CONSTRAINT [DISPENSER_LOCATION_FK3] FOREIGN KEY ([TENANT_ID], [LOCATION_ID])
REFERENCES [SBMO].[LOCATION] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DISPENSER_LOCATION]
ADD CONSTRAINT [DISPENSER_LOCATION_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[DISPENSERS]
ADD CONSTRAINT [DISPENSERS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DISPENSERS]
ADD CONSTRAINT [DISPENSERS_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DISPENSERS]
ADD CONSTRAINT [DISPENSERS_FK2] FOREIGN KEY ([TENANT_ID], [INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DISPENSERS]
ADD CONSTRAINT [DISPENSERS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[DRUG_ORDER_PRODUCT_VERIFY]
ADD CONSTRAINT [DRUG_ORDER_PRODUCT_VERIFY_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DRUG_ORDER_PRODUCT_VERIFY]
ADD CONSTRAINT [DRUG_ORDER_PRODUCT_VERIFY_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[DRUG_ORDER_PRODUCT_VERIFY]
ADD CONSTRAINT [DRUG_ORDER_PRODUCT_VERIFY_FK2] FOREIGN KEY ([TENANT_ID], [DRUG_ORDERS_ID])
REFERENCES [SBMO].[DRUG_ORDERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DRUG_ORDER_PRODUCT_VERIFY]
ADD CONSTRAINT [DRUG_ORDER_PRODUCT_VERIFY_FK3] FOREIGN KEY ([TENANT_ID], [MASTER_PRODUCT_PO_VERIFY_ID])
REFERENCES [SBMO].[MASTER_PRODUCT_PO_VERIFY] ([TENANT_ID], [ID]);

