-- BATCH 2 CONSTRAINTS
-- Schema: SBMO

ALTER TABLE [SBMO].[DRUG_ORDERS]
ADD CONSTRAINT [DRUG_ORDERS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DRUG_ORDERS]
ADD CONSTRAINT [DRUG_ORDERS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[DRUG_ORDERS]
ADD CONSTRAINT [DRUG_ORDERS_FK2] FOREIGN KEY ([TENANT_ID], [FORMULARY_ID])
REFERENCES [SBMO].[FORMULARY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DRUG_ORDERS]
ADD CONSTRAINT [DRUG_ORDERS_FK3] FOREIGN KEY ([TENANT_ID], [PURCHASE_ORDER_ID])
REFERENCES [SBMO].[PURCHASE_ORDER] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[DRUGS]
ADD CONSTRAINT [DRUGS_PK] PRIMARY KEY ([ID]);

ALTER TABLE [SBMO].[DRUGS]
ADD CONSTRAINT [DRUGS_UQ_NDC] UNIQUE ([NDC]);

ALTER TABLE [SBMO].[ENCRYPTION_KEYS]
ADD CONSTRAINT [ENCRYPTION_KEYS_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ENCRYPTION_KEYS]
ADD CONSTRAINT [ENCRYPTION_KEYS_UK1] UNIQUE ([TENANT_ID], [CREATED_DATE]);

ALTER TABLE [SBMO].[ENCRYPTION_KEYS]
ADD CONSTRAINT [ENCRYPTION_KEYS_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[ENCRYPTION_KEYS_AUDIT]
ADD CONSTRAINT [ENCRYPTION_KEYS_AUDIT_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ENCRYPTION_KEYS_AUDIT]
ADD CONSTRAINT [ENCRYPTION_KEYS_AUDIT_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[ENCRYPTION_KEYS_AUDIT]
ADD CONSTRAINT [ENCRYPTION_KEYS_AUDIT_FK2] FOREIGN KEY ([TENANT_ID], [ENCRYPTION_KEYS_ID])
REFERENCES [SBMO].[ENCRYPTION_KEYS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ENTITIES]
ADD CONSTRAINT [ENTITIES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ENTITIES]
ADD CONSTRAINT [ENTITIES_FK2] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[PHONE_ADDRESS_OWNERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ENTITIES]
ADD CONSTRAINT [ENTITIES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[FACILITIES]
ADD CONSTRAINT [FACILITIES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FACILITIES]
ADD CONSTRAINT [FACILITIES_UK1] UNIQUE ([TENANT_ID], [SHORT_NAME], [NAME]);

ALTER TABLE [SBMO].[FACILITIES]
ADD CONSTRAINT [FACILITIES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[FILLING_STATION]
ADD CONSTRAINT [FILLING_STATION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FILLING_STATION]
ADD CONSTRAINT [FILLING_STATION_UK1] UNIQUE ([TENANT_ID], [FACILITY_ID], [DESCRIPTION]);

ALTER TABLE [SBMO].[FILLING_STATION]
ADD CONSTRAINT [FILLING_STATION_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[FILLING_STATION]
ADD CONSTRAINT [FILLING_STATION_FK2] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_UK1] UNIQUE ([TENANT_ID], [DRUG_ID], [INVENTORY_ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_UQ_DRUG_INV] UNIQUE ([DRUG_ID], [INVENTORY_ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_FK5] FOREIGN KEY ([TENANT_ID], [OVERRIDE_SHIP_ID])
REFERENCES [SBMO].[CARRIER] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_FK2] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[FORMULARY_REORDER] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_FK3] FOREIGN KEY ([TENANT_ID], [INVENTORY_ID])
REFERENCES [SBMO].[INVENTORY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_FK4] FOREIGN KEY ([TENANT_ID], [VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_FK6] FOREIGN KEY ([TENANT_ID], [FILLING_STATION_ID])
REFERENCES [SBMO].[FILLING_STATION] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FORMULARY]
ADD CONSTRAINT [FORMULARY_FK_DRUGID] FOREIGN KEY ([DRUG_ID])
REFERENCES [SBMO].[DRUGS] ([ID]);

ALTER TABLE [SBMO].[FORMULARY_REORDER]
ADD CONSTRAINT [FORMULARY_REORDER_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[FORMULARY_REORDER]
ADD CONSTRAINT [FORMULARY_REORDER_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[INVENTORY]
ADD CONSTRAINT [INVENTORY_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY]
ADD CONSTRAINT [INVENTORY_UK1] UNIQUE ([TENANT_ID], [NAME]);

ALTER TABLE [SBMO].[INVENTORY]
ADD CONSTRAINT [INVENTORY_FK3] FOREIGN KEY ([TENANT_ID], [FACILITY_ID])
REFERENCES [SBMO].[FACILITIES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY]
ADD CONSTRAINT [INVENTORY_FK2] FOREIGN KEY ([TENANT_ID], [ID])
REFERENCES [SBMO].[INVENTORY_DATE] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY]
ADD CONSTRAINT [INVENTORY_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_FK2] FOREIGN KEY ([TENANT_ID], [DRUG_ORDER_ID])
REFERENCES [SBMO].[DRUG_ORDERS] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_FK3] FOREIGN KEY ([TENANT_ID], [FORMULARY_ID])
REFERENCES [SBMO].[FORMULARY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_FK4] FOREIGN KEY ([TENANT_ID], [RET_ADJ_ID])
REFERENCES [SBMO].[RETURN_AND_ADJUSTMENT] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY_AUDIT]
ADD CONSTRAINT [INVENTORY_AUDIT_FK5] FOREIGN KEY ([TENANT_ID], [RX_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY_DATE]
ADD CONSTRAINT [INVENTORY_DATE_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[INVENTORY_DATE]
ADD CONSTRAINT [INVENTORY_DATE_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[ITEM_LOCATION]
ADD CONSTRAINT [ITEM_LOCATION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ITEM_LOCATION]
ADD CONSTRAINT [ITEM_LOCATION_FK2] FOREIGN KEY ([TENANT_ID], [FORMULARY_ID])
REFERENCES [SBMO].[FORMULARY] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[ITEM_LOCATION]
ADD CONSTRAINT [ITEM_LOCATION_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[LABEL_IMAGES]
ADD CONSTRAINT [LABEL_IMAGES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[LABEL_IMAGES]
ADD CONSTRAINT [LABEL_IMAGES_UK1] UNIQUE ([TENANT_ID], [IMAGE_NAME]);

ALTER TABLE [SBMO].[LABEL_IMAGES]
ADD CONSTRAINT [LABEL_IMAGES_UQ_IMAGE_NAME] UNIQUE ([IMAGE_NAME]);

ALTER TABLE [SBMO].[LABEL_IMAGES]
ADD CONSTRAINT [LABEL_IMAGES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[LOCATION]
ADD CONSTRAINT [LOCATION_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[LOCATION]
ADD CONSTRAINT [LOCATION_UK1] UNIQUE ([TENANT_ID], [DESCRIPTOR], [PARENT_ID], [LOCATION_TYPE]);

ALTER TABLE [SBMO].[LOCATION]
ADD CONSTRAINT [LOCATION_FK2] FOREIGN KEY ([TENANT_ID], [PARENT_ID])
REFERENCES [SBMO].[LOCATION] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[LOCATION]
ADD CONSTRAINT [LOCATION_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[MASTER_PRODUCT_PO_VERIFY]
ADD CONSTRAINT [MASTER_PRODUCT_PO_VERIFY_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MASTER_PRODUCT_PO_VERIFY]
ADD CONSTRAINT [MASTER_PRODUCT_PO_VERIFY_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[MASTER_PRODUCT_PO_VERIFY]
ADD CONSTRAINT [MASTER_PRODUCT_PO_VERIFY_FK2] FOREIGN KEY ([TENANT_ID], [PURCHASE_ORDER_ID])
REFERENCES [SBMO].[PURCHASE_ORDER] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MASTER_PRODUCT_PO_VERIFY]
ADD CONSTRAINT [MASTER_PRODUCT_PO_VERIFY_FK3] FOREIGN KEY ([TENANT_ID], [VENDOR_ID])
REFERENCES [SBMO].[VENDOR] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MEDICAL_SUPPLIES]
ADD CONSTRAINT [MEDICAL_SUPPLIES_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MEDICAL_SUPPLIES]
ADD CONSTRAINT [MEDICAL_SUPPLIES_UK1] UNIQUE ([RX_CORE_ID], [NAME]);

ALTER TABLE [SBMO].[MEDICAL_SUPPLIES]
ADD CONSTRAINT [MEDICAL_SUPPLIES_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

ALTER TABLE [SBMO].[MEDICAL_SUPPLIES]
ADD CONSTRAINT [MEDICAL_SUPPLIES_FK2] FOREIGN KEY ([TENANT_ID], [RX_CORE_ID])
REFERENCES [SBMO].[RX_CORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MESSAGE_LOG]
ADD CONSTRAINT [MESSAGE_LOG_PK] PRIMARY KEY ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MESSAGE_LOG]
ADD CONSTRAINT [MESSAGE_LOG_FK2] FOREIGN KEY ([TENANT_ID], [STORE_ID])
REFERENCES [SBMO].[STORES] ([TENANT_ID], [ID]);

ALTER TABLE [SBMO].[MESSAGE_LOG]
ADD CONSTRAINT [MESSAGE_LOG_FK1] FOREIGN KEY ([TENANT_ID])
REFERENCES [SBMO].[TENANTS] ([ID]);

