-- BATCH 1 FOREIGN KEY CONSTRAINTS
-- ----------------------------------------------------------------------------

ALTER TABLE [SBMO].[BIN_UPC_LINK] ADD CONSTRAINT [BIN_UPC_LINK_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[CARRIER] ADD CONSTRAINT [CARRIER_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[ENCRYPTION_KEYS] ADD CONSTRAINT [ENCRYPTION_KEYS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[FACILITIES] ADD CONSTRAINT [FACILITIES_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[FORMULARY_REORDER] ADD CONSTRAINT [FORMULARY_REORDER_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[INVENTORY_DATE] ADD CONSTRAINT [INVENTORY_DATE_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[LABEL_IMAGES] ADD CONSTRAINT [LABEL_IMAGES_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[LOCATION] ADD CONSTRAINT [LOCATION_FK2] FOREIGN KEY ([TENANT_ID], [PARENT_ID]) REFERENCES [SBMO].[LOCATION] ([TENANT_ID], [ID]);
ALTER TABLE [SBMO].[LOCATION] ADD CONSTRAINT [LOCATION_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_D] ADD CONSTRAINT [PDX_SCHEMA_UPD_HLPR_DBG_D_FK1] FOREIGN KEY ([PDX_SCHEMA_UPD_HLPR_DBG_H_ID]) REFERENCES [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_H] ([ID]);
ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_PKGCALL_ERR_LOG] ADD CONSTRAINT [PDX_SCHEMA_UPD_PKGCALL_ELG_FK1] FOREIGN KEY ([ID]) REFERENCES [SBMO].[PDX_SCHEMA_UPD_PKGCALL_HIST] ([ID]);
ALTER TABLE [SBMO].[PDX_SCHEMA_VERSION_HISTORY] ADD CONSTRAINT [PDX_SCHEMA_VERSION_HISTORY_FK1] FOREIGN KEY ([PDX_SCHEMA_UPD_PKGCALL_HIST_ID]) REFERENCES [SBMO].[PDX_SCHEMA_UPD_PKGCALL_HIST] ([ID]);
ALTER TABLE [SBMO].[PHONE_ADDRESS_OWNERS] ADD CONSTRAINT [PHONE_ADDRESS_OWNERS_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[PURGE_HISTORY] ADD CONSTRAINT [PURGE_HISTORY_FK1] FOREIGN KEY ([TABLE_NAME]) REFERENCES [SBMO].[PURGE_TABLES] ([TABLE_NAME]);
ALTER TABLE [SBMO].[QRTZ_TRIGGERS] ADD CONSTRAINT [QRTZ_TRIGGERS_FK1] FOREIGN KEY ([SCHED_NAME], [JOB_NAME], [JOB_GROUP]) REFERENCES [SBMO].[QRTZ_JOB_DETAILS] ([SCHED_NAME], [JOB_NAME], [JOB_GROUP]);
ALTER TABLE [SBMO].[REGION] ADD CONSTRAINT [REGION_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[RX_PATSTORES] ADD CONSTRAINT [RX_PATSTORES_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[RX_PRINT_INFO] ADD CONSTRAINT [RX_PRINT_INFO_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[SHIPMENT] ADD CONSTRAINT [SHIPMENT_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
ALTER TABLE [SBMO].[VENDOR_PROP] ADD CONSTRAINT [VENDOR_PROP_FK1] FOREIGN KEY ([TENANT_ID]) REFERENCES [SBMO].[TENANTS] ([ID]);
