-- BATCH 1 PRIMARY KEY AND UNIQUE CONSTRAINTS
-- ------------------------------------------------------------------

ALTER TABLE [SBMO].[LABEL_IMAGES] ADD CONSTRAINT [LABEL_IMAGES_UQ_IMAGE_NAME] UNIQUE ([IMAGE_NAME]);
ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_HELPER_DEBUG_D] ADD CONSTRAINT [PK_PDX_SCHEMA_UPD_HELPER_DEBUG_D] PRIMARY KEY ([ID]);
ALTER TABLE [SBMO].[PDX_SCHEMA_UPD_PKGCALL_ERR_LOG] ADD CONSTRAINT [PK_PDX_SCHEMA_UPD_PKGCALL_ERR_LOG] PRIMARY KEY ([ID]);
ALTER TABLE [SBMO].[PDX_SCHEMA_VERSION_HISTORY] ADD CONSTRAINT [PK_PDX_SCHEMA_VERSION_HISTORY] PRIMARY KEY ([ID]);
ALTER TABLE [SBMO].[PURGE_HISTORY] ADD CONSTRAINT [PK_PURGE_HISTORY] PRIMARY KEY ([ID]);
